### ISSUE TITLE
Access denied with private s3 url

### ISSUE THREAD

**Issue by MincheolC** [serverless/serverless#10010]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Im trying to use Code Source of Lambda with S3 Location (**Private object**).
Even though i setup the IAM (permissions), "Access Denied" has been keep occurred.

If i changed to Public object, then it works fine looool.

### Service configuration (serverless.yml) content

```yaml
service: test

frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: java11
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-northeast-2
  profile: me
  memorySize: 512
  timeout: 30
  logRetentionInDays: 14

functions:
  hello-world:
    handler: handler::handler
    role: [my-role]
    package:
      artifact: [s3-path-url]
      individually: true
```

### Command name and used flags

serverless deploy

### Command output

```shell
Serverless: Downloading target/lambda-455.jar from bucket charles-serverless-deployments

 Access Denied -------------------------------------------

  AccessDenied: Access Denied
      at Request.extractError (/Users/charles/.nvm/versions/node/v16.4.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/services/s3.js:714:35)
      at Request.callListeners (/Users/charles/.nvm/versions/node/v16.4.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at Request.emit (/Users/charles/.nvm/versions/node/v16.4.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/Users/charles/.nvm/versions/node/v16.4.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:688:14)
      at Request.transition (/Users/charles/.nvm/versions/node/v16.4.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/Users/charles/.nvm/versions/node/v16.4.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /Users/charles/.nvm/versions/node/v16.4.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/Users/charles/.nvm/versions/node/v16.4.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/Users/charles/.nvm/versions/node/v16.4.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:690:12)
      at Request.callListeners (/Users/charles/.nvm/versions/node/v16.4.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at Request.emit (/Users/charles/.nvm/versions/node/v16.4.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/Users/charles/.nvm/versions/node/v16.4.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:688:14)
      at Request.transition (/Users/charles/.nvm/versions/node/v16.4.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/Users/charles/.nvm/versions/node/v16.4.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /Users/charles/.nvm/versions/node/v16.4.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/Users/charles/.nvm/versions/node/v16.4.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/Users/charles/.nvm/versions/node/v16.4.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:690:12)
      at Request.callListeners (/Users/charles/.nvm/versions/node/v16.4.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at callNextListener (/Users/charles/.nvm/versions/node/v16.4.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
      at IncomingMessage.onEnd (/Users/charles/.nvm/versions/node/v16.4.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/event_listeners.js:336:13)
      at IncomingMessage.emit (node:events:406:35)
      at IncomingMessage.emit (node:domain:470:12)
      at endReadableNT (node:internal/streams/readable:1329:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

### Environment information

```shell
sFramework Core: 2.59.0
Plugin: 5.4.4
SDK: 4.3.0
Components: 3.17.0
```

**Comment by medikoo** [comment]
@MincheolC I'm moving it to discussions, as it's most likely some issue in your setup.
