### ISSUE TITLE
Latest build V2.66.0 is causing deployment failures for services using serverless prod

### ISSUE THREAD

**Issue by SrushithR** [serverless/serverless#10220]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Since the version upgrade to [V2.66.0](https://github.com/serverless/serverless/releases/tag/v2.66.0), deployments with the serverless pro have started failing. The same stack without the serverless pro details deploys without any issues.

Here is the error details:
```
TypeError: Cannot read property 'getApiGatewayName' of undefined
      at BbPromise.then.apiGatewayRestApiId (/data/jenkins/node_modules/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js:153:25)
      at Promise._execute (/data/jenkins/node_modules/lib/node_modules/serverless/node_modules/bluebird/js/release/debuggability.js:384:9)
      at Promise._resolveFromExecutor (/data/jenkins/node_modules/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:518:18)
      at new Promise (/data/jenkins/node_modules/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:103:10)
      at AwsCompileApigEvents.resolveRestApiId (/data/jenkins/node_modules/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js:131:10)
```

For now, I have downgraded the serverless package version to 2.65.0 and the deployments are working fine. 

### Service configuration (serverless.yml) content

```yaml
NA
```

### Command name and used flags

serverless deploy

### Command output

```shell
TypeError: Cannot read property 'getApiGatewayName' of undefined
      at BbPromise.then.apiGatewayRestApiId (/data/jenkins/node_modules/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js:153:25)
      at Promise._execute (/data/jenkins/node_modules/lib/node_modules/serverless/node_modules/bluebird/js/release/debuggability.js:384:9)
      at Promise._resolveFromExecutor (/data/jenkins/node_modules/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:518:18)
      at new Promise (/data/jenkins/node_modules/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:103:10)
      at AwsCompileApigEvents.resolveRestApiId (/data/jenkins/node_modules/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js:131:10)
```

### Environment information

```shell
Operating System:          linux
Node Version:              12.16.1
Framework Version:         2.66.0
Plugin Version:            5.5.1
SDK Version:               4.3.0
Components Version:        3.17.2
```

**Comment by pgrzesik** [comment]
Thanks for detailed description @SrushithR :bow: I've already prepared a PR and after it's merged I will issue a new release.
