### ISSUE TITLE
New SSM SecureString behavior is parsing the decoded string to an object when it shouldn't

### ISSUE THREAD

**Issue by DaveLo** [serverless/serverless#10228]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

It looks like the new variablesResolutionMode in conjunction with autodetecting SSM secure strings is misreading a json stringified object as a js object.  

I can confirm that using the old variable mode and `~true` the env variable from ssm populates into my code as a string that needs to be parsed into an object value, but when I attempt to deploy using the new method I get this error.
> expected type: String, found: JSONObject

### Service configuration (serverless.yml) content

```yaml
service: test-case

frameworkVersion: '2'
# variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: us-east-1
  stage: dev
  eventBridge:
    useCloudFormation: true

package:
  individually: true
  patterns:
    - "!*.json"
    - "!*.md"

functions:
  hello:
    handler: src/hello.handler
    environment: 
      TEST: ${ssm:/some/secure/string/var~true}


# var {"key": "value"}
```

### Command name and used flags

sls deploy

### Command output

```shell
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: [AWS ssm 200 0.185s 0 retries] getParameter({ Name: '/some/secure/string/var', WithDecryption: true })
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Configuration warning at 'functions.hello.environment.TEST': unsupported object format
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: [AWS sts 200 1.026s 0 retries] getCallerIdentity({})
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 400 0.225s 0 retries] describeStacks({ StackName: 'sfn-test-case-dev' })
Serverless: Creating Stack...
Serverless: [AWS cloudformation 200 0.337s 0 retries] createStack({
  StackName: 'sfn-test-case-dev',
  OnFailure: 'DELETE',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateBody: '{"AWSTemplateFormatVersion":"2010-09-09","Description":"The AWS CloudFormation template for this Serverless application","Resources":{"ServerlessDeploymentBucket":{"Type":"AWS::S3::Bucket","Properties":{"BucketEncryption":{"ServerSideEncryptionConfiguration":[{"ServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}}},"ServerlessDeploymentBucketPolicy":{"Type":"AWS::S3::BucketPolicy","Properties":{"Bucket":{"Ref":"ServerlessDeploymentBucket"},"PolicyDocument":{"Statement":[{"Action":"s3:*","Effect":"Deny","Principal":"*","Resource":[{"Fn::Join":["",["arn:",{"Ref":"AWS::Partition"},":s3:::",{"Ref":"ServerlessDeploymentBucket"},"/*"]]},{"Fn::Join":["",["arn:",{"Ref":"AWS::Partition"},":s3:::",{"Ref":"ServerlessDeploymentBucket"}]]}],"Condition":{"Bool":{"aws:SecureTransport":false}}}]}}}},"Outputs":{"ServerlessDeploymentBucketName":{"Value":{"Ref":"ServerlessDeploymentBucket"}}}}',
  Tags: [ { Key: 'STAGE', Value: 'dev' }, [length]: 1 ]
})
Serverless: Checking Stack create progress...
Serverless: [AWS cloudformation 200 0.163s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1::stack/sfn-test-case-dev/85ed4bd0-4254-11ec-add1-1211720f8967'
})
..Serverless: [AWS cloudformation 200 0.21s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1: :stack/sfn-test-case-dev/85ed4bd0-4254-11ec-add1-1211720f8967'
})
.Serverless: [AWS cloudformation 200 0.216s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1::stack/sfn-test-case-dev/85ed4bd0-4254-11ec-add1-1211720f8967'
})
Serverless: [AWS cloudformation 200 0.191s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1::stack/sfn-test-case-dev/85ed4bd0-4254-11ec-add1-1211720f8967'
})
Serverless: [AWS cloudformation 200 0.163s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1::stack/sfn-test-case-dev/85ed4bd0-4254-11ec-add1-1211720f8967'
})
Serverless: [AWS cloudformation 200 0.182s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1::stack/sfn-test-case-dev/85ed4bd0-4254-11ec-add1-1211720f8967'
})
..Serverless: [AWS cloudformation 200 0.131s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1::stack/sfn-test-case-dev/85ed4bd0-4254-11ec-add1-1211720f8967'
})
...
Serverless: Stack create finished...
Serverless: [AWS cloudformation 200 0.14s 0 retries] describeStackResource({
  StackName: 'sfn-test-case-dev',
  LogicalResourceId: 'ServerlessDeploymentBucket'
})
Serverless: [AWS s3 200 0.743s 0 retries] listObjectsV2({
  Bucket: 'sfn-test-case-dev-serverlessdeploymentbucket',
  Prefix: 'serverless/sfn-test-case/dev'
})
Serverless: [AWS lambda 404 0.151s 0 retries] getFunction({ FunctionName: 'sfn-test-case-dev-hello' })
Serverless: Uploading CloudFormation file to S3...
Serverless: [AWS s3 200 0.22s 0 retries] putObject({
  Body: <Buffer 7b 22 41 57 53 54 65 6d 70 6c 61 74 65 46 6f 72 6d 61 74 56 65 72 73 69 6f 6e 22 3a 22 32 30 31 30 2d 30 39 2d 30 39 22 2c 22 44 65 73 63 72 69 70 74 ... 2838 more bytes>,
  Bucket: '',
  Key: 'serverless/sfn-test-case/dev//compiled-cloudformation-template.json',
  ContentType: 'application/json',
  Metadata: { filesha256: '' }
})
Serverless: Uploading artifacts...
Serverless: Uploading service hello.zip file to S3 (82.68 kB)...
Serverless: [AWS s3 200 0.678s 0 retries] putObject({
  Body: <Buffer 50 4b 03 04 14 00 08 00 08 00 00 00 21 00 00 00 00 00 00 00 00 00 00 00 00 00 1c 00 00 00 6e 6f 64 65 5f 6d 6f 64 75 6c 65 73 2f 2e 62 69 6e 2f 63 6f ... 82628 more bytes>,
  Bucket: ',
  Key: 'serverless/sfn-test-case/dev/1636569132782-2021-11-10T18:32:12.782Z/hello.zip',
  ContentType: 'application/zip',
  Metadata: { filesha256: 'a9h6o2fdPpG2GzZ+9TOJHfbBobH+swaLGR7bi5F2m1Y=' }
})
Serverless: Validating template...
Serverless: [AWS cloudformation 200 0.294s 0 retries] validateTemplate({
  TemplateURL: ''
})
Serverless: Updating Stack...
Serverless: [AWS cloudformation 200 0.468s 0 retries] updateStack({
  StackName: 'sfn-test-case-dev',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL: '',
  Tags: [ { Key: 'STAGE', Value: 'dev' }, [length]: 1 ]
})
Serverless: Checking Stack update progress...
Serverless: [AWS cloudformation 200 0.161s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1::stack/sfn-test-case-dev/85ed4bd0-4254-11ec-add1-1211720f8967'
})
.Serverless: [AWS cloudformation 200 0.192s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1::stack/sfn-test-case-dev/85ed4bd0-4254-11ec-add1-1211720f8967'
})
.....Serverless: [AWS cloudformation 200 0.216s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1::stack/sfn-test-case-dev/85ed4bd0-4254-11ec-add1-1211720f8967'
})
Serverless: [AWS cloudformation 200 0.154s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1::stack/sfn-test-case-dev/85ed4bd0-4254-11ec-add1-1211720f8967'
})
Serverless: [AWS cloudformation 200 0.157s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1::stack/sfn-test-case-dev/85ed4bd0-4254-11ec-add1-1211720f8967'
})
..Serverless: [AWS cloudformation 200 0.183s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1::stack/sfn-test-case-dev/85ed4bd0-4254-11ec-add1-1211720f8967'
})
..
Serverless: Operation failed!
Serverless: View the full error output: https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%%3Astack%2Fsfn-test-case-dev%2F85ed4bd0-4254-11ec-add1-1211720f8967
 
 Serverless Error ----------------------------------------
 
  ServerlessError: An error occurred: HelloLambdaFunction - Properties validation failed for resource HelloLambdaFunction with message:
  #/Environment/Variables/TEST: expected type: String, found: JSONObject.
      at /Users/**/**/sfn-test-case/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:143:23
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async AwsDeploy.update (/Users/**/**/sfn-test-case/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:146:5)
```

### Environment information

```shell
Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              16.4.0
     Framework Version:         2.66.0 (local)
     Plugin Version:            5.5.1
     SDK Version:               4.3.0
     Components Version:        3.17.2
```

**Comment by pgrzesik** [comment]
Hello - this is intended behavior with new resolver and you can opt-out from JSON parsing with `raw` param - here are more details about that: https://www.serverless.com/framework/docs/providers/aws/guide/variables/#auto-decrypting-of-securestring-type-parameters

**Comment by DaveLo** [comment]
@pgrzesik , that works. I generally would expect a secure string to act as a string but I'm sure the decision is useful for other use cases
