### ISSUE TITLE
[serverless function run] errors - not using [serverless-webpack-plugin] ?

### ISSUE THREAD

**Issue by BerndWessels** [serverless/serverless#1023]
When running `serverless function run myFunction -s dev` I get an error (see at the bottom).

This is myFunction:

    import path from 'path';

    export default ({something}, context, cb) => {
      return cb(null, {
        message: `Go serverless ${something}? Here we are: ${path.isAbsolute(__dirname)}`
      });
    }

I believe that the problem is that `serverless function run` does not use the `serverless-webpack-plugin` to transform myFunction before running it locally.

Is there a way to make it work?

This is on a Windows 10 with:

    serverless 0.5.5

    "devDependencies": {
      "babel-loader": "^6.0.0",
      "serverless-client-s3": "^2.0.0",
      "serverless-webpack-plugin": "^0.4.0",
      "webpack": "^1.0.0"
    }

This is the error:

    C:\Users\dev\Documents\WebstormProjects\manapaho-aws>serverless function run myFunction
    Serverless: Running myFunction...
    Serverless: WARNING: This variable is not defined: region
    Serverless: -----------------
      Serverless: Failed - This Error Was Thrown:
      Serverless: SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at C:\Users\dev\AppData\Roaming\npm\node_modules\serverless\lib\RuntimeNode43.js:36:34
    From previous event:
      at RuntimeNode43.run (C:\Users\dev\AppData\Roaming\npm\node_modules\serverless\lib\RuntimeNode43.js:29:12)
    at Function.run (C:\Users\dev\AppData\Roaming\npm\node_modules\serverless\lib\Function.js:238:32)
    at FunctionRun._runLocal (C:\Users\dev\AppData\Roaming\npm\node_modules\serverless\lib\actions\FunctionRun.js:177:28)
    at FunctionRun.<anonymous> (C:\Users\dev\AppData\Roaming\npm\node_modules\serverless\lib\actions\FunctionRun.js:87:25)
    From previous event:
      at FunctionRun.functionRun (C:\Users\dev\AppData\Roaming\npm\node_modules\serverless\lib\actions\FunctionRun.js:82:10)
    From previous event:
      at C:\Users\dev\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:186:31
    at Array.reduce (native)
    at C:\Users\dev\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:185:32
    From previous event:
      at Serverless._execute (C:\Users\dev\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:183:12)
    at Serverless.actions.(anonymous function) (C:\Users\dev\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:429:20)
    at Serverless.command (C:\Users\dev\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:398:38)
    at C:\Users\dev\AppData\Roaming\npm\node_modules\serverless\bin\serverless:19:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
    From previous event:
      at Object.<anonymous> (C:\Users\dev\AppData\Roaming\npm\node_modules\serverless\bin\serverless:18:4)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by patoncrispy** [comment]
I'm also having this issue, though my stack trace differs slightly at the top (I'm also on a mac):

```
Serverless: Failed - This Error Was Thrown:
Serverless: SyntaxError: Unexpected reserved word
  at exports.runInThisContext (vm.js:53:16)
  at Module._compile (module.js:373:25)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (/Users/Chris/Development/project/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at /Users/Chris/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/lib/RuntimeNode43.js:36:34
```

**Comment by marcoslhc** [comment]
On a mac too. Everything works fine testing locally with serverless offline plugin but in AWS I get:
```json
{
  "errorMessage": "Unexpected reserved word",
  "errorType": "SyntaxError",
  "stackTrace": [
    "Object.Module._extensions..js (module.js:416:10)",
    "Module.load (module.js:343:32)",
    "Function.Module._load (module.js:300:12)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)",
    "Object.<anonymous> (/var/task/_serverless_handler.js:11:29)",
    "Module._compile (module.js:409:26)",
    "Object.Module._extensions..js (module.js:416:10)"
  ]
}
```

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.

**Comment by jlsjonas** [comment]
This issue still/again exists on v1.8.0, on `serverless deploy function -f functionName`, serverless-babel-plugin is not triggered/used causing incompatible code to be uploaded

**Comment by pmuens** [comment]
@jlsjonas yes, this seems to be a problem with the plugin.

You can see more information in this related issue here: https://github.com/serverless/serverless/issues/3320
