### ISSUE TITLE
Support API paths with "."

### ISSUE THREAD

**Issue by jatsrt** [serverless/serverless#1041]
Trying to incorporate an self updating letsencrypts workflow.  So, I would like to have a function that responds to the manual challenge of lets encrypt.  

This means the path looks like:
"/.well-known/acme-challenge/{id}"

The path is supported in API gateway, but when deploying this via server less I get the following:
```
Serverless:   GET - .well-known/acme-challenge/{id}: 1 validation error detected: Value 's_apig_.well-known_acme-challenge__id__GET' at 'statementId' failed to satisfy constraint: Member must satisfy regular expression pattern: ([a-zA-Z0-9-_]+)  
  serverless:lib.node_modules.serverless.lib.actions.EndpointDeploy ServerlessError: 1 validation error detected: Value 's_apig_.well-known_acme-challenge__id__GET' at 'statementId' failed to satisfy constraint: Member must satisfy regular expression pattern: ([a-zA-Z0-9-_]+)
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/Error.js:17:11)
    at /usr/local/lib/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js:859:17
From previous event:
    at Builder._addLambdaPermissionForEndpoint (/usr/local/lib/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js:858:15)
From previous event:
    at Builder._manageLambdaAccessPolicy (/usr/local/lib/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js:751:10)
From previous event:
    at Builder.build (/usr/local/lib/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js:80:10)
    at EndpointBuildApiGateway.endpointBuildApiGateway (/usr/local/lib/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js:54:22)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:211:25
    at Array.reduce (native)
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:210:26)
    at Object.actions.(anonymous function) [as endpointBuildApiGateway] (/usr/local/lib/node_modules/serverless/lib/Serverless.js:429:20)
    at /usr/local/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:172:36
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:146:35
    at /usr/local/lib/node_modules/serverless/node_modules/async/lib/async.js:181:20
    at iterate (/usr/local/lib/node_modules/serverless/node_modules/async/lib/async.js:262:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (/usr/local/lib/node_modules/serverless/node_modules/async/lib/async.js:281:9)
    at Object.async.forEachSeries.async.eachSeries (/usr/local/lib/node_modules/serverless/node_modules/async/lib/async.js:214:22)
    at /usr/local/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:144:19
From previous event:
    at EndpointDeployApiGateway.<anonymous> (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:141:18)
From previous event:
    at EndpointDeployApiGateway._processRegionDeployment (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:137:10)
    at EndpointDeployApiGateway.<anonymous> (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:94:24)
From previous event:
    at EndpointDeployApiGateway._processDeployment (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:91:10)
From previous event:
    at EndpointDeployApiGateway.endpointDeployApiGateway (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:55:10)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:211:25
    at Array.reduce (native)
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:210:26)
    at Object.actions.(anonymous function) [as endpointDeployApiGateway] (/usr/local/lib/node_modules/serverless/lib/Serverless.js:429:20)
    at EndpointDeploy._processDeployment (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:212:24)
From previous event:
    at EndpointDeploy.endpointDeploy (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:101:12)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:211:25
    at Array.reduce (native)
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:210:26)
    at Object.actions.(anonymous function) [as endpointDeploy] (/usr/local/lib/node_modules/serverless/lib/Serverless.js:429:20)
    at /usr/local/lib/node_modules/serverless/lib/actions/DashDeploy.js:251:28
From previous event:
    at DashDeploy._deploy (/usr/local/lib/node_modules/serverless/lib/actions/DashDeploy.js:246:10)
From previous event:
    at DashDeploy.dashDeploy (/usr/local/lib/node_modules/serverless/lib/actions/DashDeploy.js:126:10)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:186:31
    at Array.reduce (native)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:185:32
From previous event:
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:183:12)
    at Serverless.actions.(anonymous function) (/usr/local/lib/node_modules/serverless/lib/Serverless.js:429:20)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:398:38)
    at /usr/local/lib/node_modules/serverless/bin/serverless:19:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3 +727ms
Serverless:   
Serverless: Run this again with --debug to get more error information... 
```

So one of the generated variable names does not properly handle the "." and maybe convert it to "_"

**Comment by jatsrt** [comment]
Could change:
serverless/lib/actions/EndpointBuildApiGateway.js

```

// Prepare StatementId
          _this.lambdaPolicyStatementId = ('s_apig' + _this.endpoint.path + '_' + _this.endpoint.method).replace(/[\/{}]/g, '_');

```


To(assuming my regex is right)

```
// Prepare StatementId
          _this.lambdaPolicyStatementId = ('s_apig' + _this.endpoint.path + '_' + _this.endpoint.method).replace(/[\/{}.]/g, '_');
```

**Comment by eahefnawy** [comment]
wow thanks for reporting this @jatsrt ! This is for sure an issue. I remember someone else reported a similar issue where they needed to construct a path that looks like this `/path/users.json`

Will get it done asap 😊

**Comment by borosio** [comment]
I have executed sls project init with intention to change the profile. After that, when I try to deploy a function with endpoint, I have error 

> The statement id (s_apig_namefunction_POST) provided already exists. Please provide a new statement id, or remove the existing statement

.
`Serverless: Failed to deploy endpoints in "dev" to the following regions:
Serverless: us-east-1 ------------------------
Serverless:   POST - functionname: The statement id (s_apig_functionname_POST) provided already exists. Please provide a new statement id, or remove the existing statement.
  serverless:lib.actions.EndpointDeploy ServerlessError: The statement id (s_apig_functionname_POST) provided already exists. Please provide a new statement id, or remove the existing statement.
    at new ServerlessError (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Error.js:17:11)
    at C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointBuildApiGateway.js:859:17
From previous event:
    at Builder._addLambdaPermissionForEndpoint (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointBuildApiGateway.js:858:15)
From previous event:
    at Builder._manageLambdaAccessPolicy (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointBuildApiGateway.js:751:10)
From previous event:
    at Builder.build (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointBuildApiGateway.js:80:10)
    at EndpointBuildApiGateway.endpointBuildApiGateway (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointBuildApiGateway.js:54:22)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:211:25
    at Array.reduce (native)
    at Serverless._execute (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:210:26)
    at Object.actions.(anonymous function) [as endpointBuildApiGateway] (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:429:20)
    at C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointDeployApiGateway.js:172:36
From previous event:
    at C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointDeployApiGateway.js:146:35
    at C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\node_modules\async\lib\async.js:181:20
    at iterate (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\node_modules\async\lib\async.js:262:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\node_modules\async\lib\async.js:281:9)
    at Object.async.forEachSeries.async.eachSeries (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\node_modules\async\lib\async.js:214:22)
    at C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointDeployApiGateway.js:144:19
From previous event:
    at EndpointDeployApiGateway.<anonymous> (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointDeployApiGateway.js:141:18)
From previous event:
    at EndpointDeployApiGateway._processRegionDeployment (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointDeployApiGateway.js:137:10)
    at EndpointDeployApiGateway.<anonymous> (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointDeployApiGateway.js:94:24)
From previous event:
    at EndpointDeployApiGateway._processDeployment (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointDeployApiGateway.js:91:10)
From previous event:
    at EndpointDeployApiGateway.endpointDeployApiGateway (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointDeployApiGateway.js:55:10)
From previous event:
    at C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:211:25
    at Array.reduce (native)
    at Serverless._execute (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:210:26)
    at Object.actions.(anonymous function) [as endpointDeployApiGateway] (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:429:20)
    at EndpointDeploy._processDeployment (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointDeploy.js:213:24)
From previous event:
    at EndpointDeploy.endpointDeploy (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointDeploy.js:101:12)
From previous event:
    at C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:211:25
    at Array.reduce (native)
    at Serverless._execute (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:210:26)
    at Object.actions.(anonymous function) [as endpointDeploy] (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:429:20)
    at C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\DashDeploy.js:251:28
From previous event:
    at DashDeploy._deploy (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\DashDeploy.js:246:10)
From previous event:
    at DashDeploy.dashDeploy (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\DashDeploy.js:126:10)
From previous event:
    at C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:186:31
    at Array.reduce (native)
    at C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:185:32
From previous event:
    at Serverless._execute (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:183:12)
    at Serverless.actions.(anonymous function) (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:429:20)
    at Serverless.command (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:398:38)
    at C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\bin\serverless:19:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Object.<anonymous> (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\bin\serverless:18:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3 +437ms
``
