### ISSUE TITLE
add the service name to ApiResource name

### ISSUE THREAD

**Issue by wildcats1369** [serverless/serverless#10493]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

I have 2 projects that will point to the same AG ( we have grouped AG based on user type that access our projects which can share features )

Project1 paths
- /merchant/{merchant_id}
- /merchant
Project2 paths
- /merchant/{merchant_id}/tax/country

The issue is because both having the pattern "/merchant" each CF will generate `ApiGatewayResourceMerchant` object to create the /merchant part of the api.

### Proposed solution (optional)

with this can we add the service name to the ApiGatewayResource name so resource name will be unnique per yml file?
Expected:
ProjectDash1ApiGatewayResourceMerchant
ProjectDash2ApiGatewayResourceMerchant

**Comment by pgrzesik** [comment]
Hello, could you share a small reproducible example to illustrate your issue better and reproduce it on my side? What exactly is failing? Could you please include the output of `SLS_DEBUG=* sls deploy` command?

**Comment by wildcats1369** [comment]
> 

based on the example above i have /merchant/{merchant_id} on one aml and tha same partial path on another yml in another project, then im getting an error like this
![image](https://user-images.githubusercontent.com/8967830/149250467-156019e6-e099-408a-9c93-106cbd1b34ad.png)

i checked the template generated by the sls via CF and they both have `ApiGatewayResourceMerchant`
![image](https://user-images.githubusercontent.com/8967830/149250995-e15a8c2b-b0f1-4b58-acf8-191a0bda9fe2.png)


when i removed the `/merchant/{merchant_id}/something/something2` on one project it was a success

**Comment by wildcats1369** [comment]
here is the SLS log
```
$ serverless deploy --config serverless.merchant.yml --stage dev --region us-west-2 --verbose
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.31.0")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command invoke
Serverless: Load command invoke:stepf
Serverless: Load command dynamodb
Serverless: Load command dynamodb:migrate
Serverless: Load command dynamodb:seed
Serverless: Load command dynamodb:start
Serverless: Load command dynamodb:noStart
Serverless: Load command dynamodb:remove
Serverless: Load command dynamodb:install
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Configuration warning at 'functions['create-country-tax'].events[0].http.authorizer.type': unsupported configuration format
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Deprecation warning: Starting with next major, Serverless will throw on configuration errors by default. Adapt to this behavior now by adding "configValidationMode: error" to service configuration
            More Info: https://www.serverless.com/framework/docs/deprecations/#CONFIG_VALIDATION_MODE_DEFAULT
Serverless: Deprecation warning: Starting with version 3.0.0, following property will be replaced:
              "provider.iamRoleStatements" -> "provider.iam.role.statements"
            More Info: https://www.serverless.com/framework/docs/deprecations/#PROVIDER_IAM_SETTINGS
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
AWS Pseudo Parameters
Skipping automatic replacement of regions with account region!
AWS Pseudo Parameter: Resources::IamRoleLambdaExecution::Properties::Policies::0::PolicyDocument::Statement::2::Resource Replaced AWS::Region with ${AWS::Region}
AWS Pseudo Parameter: Resources::IamRoleLambdaExecution::Properties::Policies::0::PolicyDocument::Statement::2::Resource Replaced AWS::AccountId with ${AWS::AccountId}
AWS Pseudo Parameter: Resources::IamRoleLambdaExecution::Properties::Policies::0::PolicyDocument::Statement::3::Resource::0::Fn::Sub Replaced AWS::Region with ${AWS::Region}
AWS Pseudo Parameter: Resources::IamRoleLambdaExecution::Properties::Policies::0::PolicyDocument::Statement::3::Resource::0::Fn::Sub Replaced AWS::AccountId with ${AWS::AccountId}
AWS Pseudo Parameter: Resources::IamRoleLambdaExecution::Properties::Policies::0::PolicyDocument::Statement::3::Resource::1::Fn::Sub Replaced AWS::Region with ${AWS::Region}
AWS Pseudo Parameter: Resources::IamRoleLambdaExecution::Properties::Policies::0::PolicyDocument::Statement::3::Resource::1::Fn::Sub Replaced AWS::AccountId with ${AWS::AccountId}
AWS Pseudo Parameter: Resources::IamRoleLambdaExecution::Properties::Policies::0::PolicyDocument::Statement::4::Resource::Fn::Sub Replaced AWS::Region with ${AWS::Region}
AWS Pseudo Parameter: Resources::IamRoleLambdaExecution::Properties::Policies::0::PolicyDocument::Statement::4::Resource::Fn::Sub Replaced AWS::AccountId with ${AWS::AccountId}
AWS Pseudo Parameter: Resources::IamRoleLambdaExecution::Properties::Policies::0::PolicyDocument::Statement::4::Condition::ArnLike::AWS:SourceArn Replaced AWS::Region with ${AWS::Region}
AWS Pseudo Parameter: Resources::IamRoleLambdaExecution::Properties::Policies::0::PolicyDocument::Statement::4::Condition::ArnLike::AWS:SourceArn Replaced AWS::AccountId with ${AWS::AccountId}
AWS Pseudo Parameter: Resources::CreateDashcountryDashtaxLambdaFunction::Properties::Layers::0 Replaced AWS::Region with ${AWS::Region}
AWS Pseudo Parameter: Resources::CreateDashcountryDashtaxLambdaFunction::Properties::Layers::0 Replaced AWS::AccountId with ${AWS::AccountId}
AWS Pseudo Parameter: Resources::CreateDashcountryDashtaxLambdaFunction::Properties::Layers::1 Replaced AWS::Region with ${AWS::Region}
AWS Pseudo Parameter: Resources::CreateDashcountryDashtaxLambdaFunction::Properties::Layers::1 Replaced AWS::AccountId with ${AWS::AccountId}
Serverless: [serverless-latest-layer-version] Resolved arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:dev-foo-tax-layer:latest to arn:aws:lambda:us-west-2:496261851893:layer:dev-foo-tax-layer:4
Serverless: [serverless-latest-layer-version] Resolved arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:dev-helpers:latest to arn:aws:lambda:us-west-2:496261851893:layer:dev-helpers:15
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service create-country-tax.zip file to S3 (1.08 KB)...
Serverless: Validating template...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - tax-merchant-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - CreateDashcountryDashtaxLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Resource - ApiGatewayResourceMerchant
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_FAILED - AWS::ApiGateway::Resource - ApiGatewayResourceMerchant
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - CreateDashcountryDashtaxLogGroup
CloudFormation - CREATE_FAILED - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_FAILED - AWS::Logs::LogGroup - CreateDashcountryDashtaxLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::CloudFormation::Stack - tax-merchant-dev
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - CreateDashcountryDashtaxLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - CreateDashcountryDashtaxLogGroup
CloudFormation - DELETE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - DELETE_COMPLETE - AWS::ApiGateway::Resource - ApiGatewayResourceMerchant
CloudFormation - DELETE_COMPLETE - AWS::CloudFormation::Stack - tax-merchant-dev
Serverless: Operation failed!
Serverless: View the full error output: https://us-west-2.console.aws.amazon.com/cloudformation/home?region=us-west-2#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-west-2%3A496261851893%3Astack%2Ftax-merchant-dev%2Ff5fc2dd0-7416-11ec-bfbf-0af375e22687
 
  Serverless Error ---------------------------------------
 
  ServerlessError: An error occurred: ApiGatewayResourceMerchant - Resource handler returned message: "Another resource with the same parent already has this name: merchant (Service: ApiGateway, Status Code: 409, Request ID: 93734253-bfe7-45dc-b2e5-95a1a4d225c8, Extended Request ID: null)" (RequestToken: b50174b0-b810-7a1a-4b5b-c78fc6c2d385, HandlerErrorCode: AlreadyExists).
      at /Users/mark.raymond/Codes/Projects/foo-serverless/foo-serverless-tax/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:94:23
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.4.0
     Framework Version:         2.4.0 (local)
     Plugin Version:            4.5.0
     SDK Version:               n/a
     Components Version:        3.7.3
```

**Comment by ssimontis** [comment]
Hello, have you looked into the shouldStartNameWithService parameter that you can add to provider:apiGateway in your serverless.yml file? It seems like this might alleviate your issue.

**Comment by wildcats1369** [comment]
hi i tried the parameter it did not seems to do the trick
the name is still the same
```
CloudFormation - UPDATE_COMPLETE - AWS::ApiGateway::Method - ApiGatewayMethodTaxMerchantMerchantidVarTaxCountryOptions
CloudFormation - CREATE_FAILED - AWS::ApiGateway::Resource - ApiGatewayResourceMerchant
CloudFormation - UPDATE_FAILED - AWS::Lambda::Function - ListDashcountryDashtaxesLambdaFunction
```
The provider is like this
```
provider:
  lambdaHashingVersion: "20201221"
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  apiGateway:
    restApiId: ${self:custom.${self:provider.stage}.restApiId}
    restApiRootResourceId: ${self:custom.${self:provider.stage}.restApiRootResourceId}
    shouldStartNameWithService: true
```
```
Serverless Error ---------------------------------------
 
  An error occurred: ApiGatewayResourceMerchant - Resource handler returned message: "Another resource with the same parent already has this name: merchant (Service: ApiGateway, Status Code: 409, Request ID: 3c4ba9fd-87e8-4adb-acc7-e88323569b22, Extended Request ID: null)" (RequestToken: 1c7cdb83-d243-c81a-8891-e4440c2f85b4, HandlerErrorCode: AlreadyExists).
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.4.0
     Framework Version:         2.4.0 (local)
     Plugin Version:            4.5.0
     SDK Version:               n/a
     Components Version:        3.7.3
     ```
     package.json 
     ```
     {
  "name": "serverless-project",
  "description": "",
  "version": "0.1.0",
  "scripts": {
    "test": "pytest"
  },
  "dependencies": {
    "serverless": "2.71.0",
    "serverless-api-gateway-caching": "1.6.0",
    "serverless-aws-documentation": "1.1.0",
    "serverless-dynalite": "^1.4.0",
    "serverless-iam-roles-per-function": "^3.2.0-e97ab49",
    "serverless-latest-layer-version": "^2.1.1",
    "serverless-pseudo-parameters": "2.5.0",
    "serverless-python-requirements": "5.1.0",
    "serverless-reqvalidator-plugin": "1.0.3",
    "serverless-step-functions": "2.26.0",
    "webpack": "^5.66.0"
  },
  "devDependencies": {
    "serverless": "2.31.0",
    "serverless-dynamodb-local": "^0.2.40",
    "serverless-dynamodb-seed": "0.3.0",
    "serverless-offline": "^5.12.1",
    "serverless-offline-dynamodb-streams": "4.2.0",
    "serverless-webpack": "^5.6.0"
  }
}

     ```

**Comment by pgrzesik** [comment]
I think the problem in this case is that the path in both cases share the same root of the path and I'm not sure that can be supported in this case well. e.g. if you have something like that:
```
- http:
            path: getSth/{val}/another
            method: get
```

then resources are generated for each part of the path, so there's:
```
- ApiGatewayResourceGetsth
- ApiGatewayResourceGetsthValVar
- ApiGatewayResourceGetsthValVarAnother
```

resources. 

If you have an idea for a solution for this - please let us know
