### ISSUE TITLE
Variables that happen to be arrays (maybe objects too) can't be used directly in cloud formation templates

### ISSUE THREAD

**Issue by Josh-a-e** [serverless/serverless#1050]
Serverless version: 5.5

**Setup**

In `s-variables-stage-location.json`:
```
{
  ...
  "subnetIds": [
    "subnet-www",
    "subnet-xxx",
    "subnet-yyy",
    "subnet-zzz"
  ]
}
```

In `s-function.json`:
```
{
  ...
  "vpc": {
    "securityGroupIds": "${locationsPostgresSecurityGroupId}",
    "subnetIds": "${subnetIds}"
  }
}
```

**Expected behaviour:**
The function gets deployed to the specified subnets

**Actual behaviour:**
Cloud formation error thrown: `Expected params.VpcConfig.SecurityGroupIds to be an Array`

Stack:
```
ServerlessError: Function Deployment Failed
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/Error.js:17:11)
    at FunctionDeploy.<anonymous> (/usr/local/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:126:19)
    at next (/usr/local/lib/node_modules/serverless/node_modules/rimraf/rimraf.js:74:7)
    at FSReqWrap.CB [as oncomplete] (/usr/local/lib/node_modules/serverless/node_modules/rimraf/rimraf.js:110:9)
From previous event:
    at FunctionDeploy.functionDeploy (/usr/local/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:105:10)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:211:25
    at Array.reduce (native)
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:210:26)
    at Object.actions.(anonymous function) [as functionDeploy] (/usr/local/lib/node_modules/serverless/lib/Serverless.js:429:20)
    at /usr/local/lib/node_modules/serverless/lib/actions/DashDeploy.js:234:26
From previous event:
    at DashDeploy._deploy (/usr/local/lib/node_modules/serverless/lib/actions/DashDeploy.js:229:14)
From previous event:
    at DashDeploy.dashDeploy (/usr/local/lib/node_modules/serverless/lib/actions/DashDeploy.js:126:10)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:186:31
    at Array.reduce (native)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:185:32
From previous event:
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:183:12)
    at Serverless.actions.(anonymous function) (/usr/local/lib/node_modules/serverless/lib/Serverless.js:429:20)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:398:38)
    at /usr/local/lib/node_modules/serverless/bin/serverless:19:16
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
```

@HyperBrain informs me this is likely an issue with the populate function

**Comment by Josh-a-e** [comment]
Nope, this actually performs just the way it should: I didn't read the error properly:

`"Expected params.VpcConfig.SecurityGroupIds to be an Array"`

and as we can see:

```
"vpc": {
    "securityGroupIds": "${locationsPostgresSecurityGroupId}",
```

`securityGroupIds` certainly isn't an array, should have been `"securityGroupIds": [ "${locationsPostgresSecurityGroupId}" ],`

**Comment by jaminto** [comment]
To be explicit, i got it to work with this setup...

*s-variables-stage.json*:
```
{
  "securityGroupIds" : ["sg-XXX"],
  "subnetIds": ["subnet-YYY", "subnet-ZZZ"]
}
```
*s-function.json*:
```
{
  ...
  "vpc": {
    "securityGroupIds": "${securityGroupIds}",
    "subnetIds": "${subnetIds}"
  }
  ...
}
```
Which confuses me because it seems like it's what @Josh-a-e had in his original post but he said it was not working.   I am using 0.5.3.

I could not find this simple example anywhere else on the internet, so hopefully it helps someone.
