### ISSUE TITLE
update docs: Function logs accepts unique name not path

### ISSUE THREAD

**Issue by aexmachina** [serverless/serverless#1057]
When I run `sls function logs functions/donationCreate` I get `Cannot read property 'getDeployedName' of undefined`.

I'm using serverless v0.5.5 with serverless-runtime-babel plugin, although the problem persists if I remove this plugin. I've tried using the master branch and it doesn't help.

Here's the stack trace:

```
/Users/simonwade/.nvm/versions/node/v6.0.0/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

TypeError: Cannot read property 'getDeployedName' of undefined
    at FunctionLogs._validateAndPrepare (/Users/simonwade/.nvm/versions/node/v6.0.0/lib/node_modules/serverless/lib/actions/FunctionLogs.js:126:39)
From previous event:
    at FunctionLogs.functionLogs (/Users/simonwade/.nvm/versions/node/v6.0.0/lib/node_modules/serverless/lib/actions/FunctionLogs.js:95:10)
From previous event:
    at /Users/simonwade/.nvm/versions/node/v6.0.0/lib/node_modules/serverless/lib/Serverless.js:186:31
    at Array.reduce (native)
    at /Users/simonwade/.nvm/versions/node/v6.0.0/lib/node_modules/serverless/lib/Serverless.js:185:32
From previous event:
    at Serverless._execute (/Users/simonwade/.nvm/versions/node/v6.0.0/lib/node_modules/serverless/lib/Serverless.js:183:12)
    at Serverless.actions.(anonymous function) (/Users/simonwade/.nvm/versions/node/v6.0.0/lib/node_modules/serverless/lib/Serverless.js:429:20)
    at Serverless.command (/Users/simonwade/.nvm/versions/node/v6.0.0/lib/node_modules/serverless/lib/Serverless.js:398:38)
    at /Users/simonwade/.nvm/versions/node/v6.0.0/lib/node_modules/serverless/bin/serverless:19:16
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at Object.<anonymous> (/Users/simonwade/.nvm/versions/node/v6.0.0/lib/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3
```

**Comment by aexmachina** [comment]
The solution to this issue is simple: `function logs` only accepts the last part of the function, so if I change this to `sls function logs donationCreate` then it works :)

This is pretty confusing for newcomers, particularly when `function create` does require the relative path to the function. I suggest that the various `function` actions should accept the function name either with or without the relative path.

**Comment by eahefnawy** [comment]
hmmm @aexmachina yeah we're now enforcing unique function names across your project to make it easy to reference your functions without having to specify the path. So it's intended to work this way. Maybe the docs doesn't cover that change yet. Really sorry about that :/

Will update the docs today. Thanks for reporting 😊

**Comment by flomotlik** [comment]
Our new logs plugin for V1 doesn't have this issue any more. Closing therefore
