### ISSUE TITLE
Error executing sls migrations with sequelize

### ISSUE THREAD

**Issue by evandro-araujo-ir** [serverless/serverless#10628]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I've installed sequelize plugin through sls cli: sls plugin install --name serverless-sequelize-migrations 

when I try the command sls migrations, I receive the error below:
Environment: linux, node 17.4.0, framework 3.0.1, plugin 6.0.0, SDK 4.3.0
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
TypeError: this.serverless.cli.generateCommandsHelp is not a function
    at SequelizeMigrations.showPluginInfo (/home/evandro/letz/payment-service/test-sequelize/test-seq/node_modules/serverless-sequelize-migrations/index.js:137:25)
    at PluginManager.runHooks (/home/evandro/.nvm/versions/node/v17.4.0/lib/node_modules/serverless/lib/classes/plugin-manager.js:520:41)
    at PluginManager.invoke (/home/evandro/.nvm/versions/node/v17.4.0/lib/node_modules/serverless/lib/classes/plugin-manager.js:550:20)
    at async PluginManager.run (/home/evandro/.nvm/versions/node/v17.4.0/lib/node_modules/serverless/lib/classes/plugin-manager.js:590:7)
    at async Serverless.run (/home/evandro/.nvm/versions/node/v17.4.0/lib/node_modules/serverless/lib/serverless.js:169:5)
    at async /home/evandro/.nvm/versions/node/v17.4.0/lib/node_modules/serverless/scripts/serverless.js:675:9

### Service configuration (serverless.yml) content

```yaml
service: test-seq
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-sequelize-migrations
```

### Command name and used flags

sls migrations

### Command output

```shell
I've installed sequelize plugin through sls cli: sls plugin install --name serverless-sequelize-migrations 

when I try the command sls migrations, I receive the error below:
Environment: linux, node 17.4.0, framework 3.0.1, plugin 6.0.0, SDK 4.3.0
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
TypeError: this.serverless.cli.generateCommandsHelp is not a function
    at SequelizeMigrations.showPluginInfo (/home/evandro/letz/payment-service/test-sequelize/test-seq/node_modules/serverless-sequelize-migrations/index.js:137:25)
    at PluginManager.runHooks (/home/evandro/.nvm/versions/node/v17.4.0/lib/node_modules/serverless/lib/classes/plugin-manager.js:520:41)
    at PluginManager.invoke (/home/evandro/.nvm/versions/node/v17.4.0/lib/node_modules/serverless/lib/classes/plugin-manager.js:550:20)
    at async PluginManager.run (/home/evandro/.nvm/versions/node/v17.4.0/lib/node_modules/serverless/lib/classes/plugin-manager.js:590:7)
    at async Serverless.run (/home/evandro/.nvm/versions/node/v17.4.0/lib/node_modules/serverless/lib/serverless.js:169:5)
    at async /home/evandro/.nvm/versions/node/v17.4.0/lib/node_modules/serverless/scripts/serverless.js:675:9
```

### Environment information

```shell
Framework Core: 3.0.1
Plugin: 6.0.0
SDK: 4.3.0
```

**Comment by pgrzesik** [comment]
Hello @evandro-araujo-ir - it looks like an issue with that specific plugin - please move the issue to plugin's repository. I'm going to close this issue here.
