### ISSUE TITLE
Error while trying to deploy after adding request to plugins

### ISSUE THREAD

**Issue by selvameenal** [serverless/serverless#1074]
I did:

npm install request --save

Then added it to s-project.json:
"plugins": ["request"]

When I do server less dash deploy, I get the following error:
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
fn = function () { throw arg; };
^

Error: options.uri is a required argument
at Request.init (/Users/Meenals/workspace/lambdas/RegistrationLogin/node_modules/request/request.js:246:31)
at new Request (/Users/Meenals/workspace/lambdas/RegistrationLogin/node_modules/request/request.js:142:8)
at request (/Users/Meenals/workspace/lambdas/RegistrationLogin/node_modules/request/index.js:55:10)
at Serverless._loadPlugins (/usr/local/lib/node_modules/serverless/lib/Serverless.js:291:25)
at Serverless.loadProjectPlugins (/usr/local/lib/node_modules/serverless/lib/Serverless.js:245:10)
at /usr/local/lib/node_modules/serverless/lib/Serverless.js:76:41
From previous event:
at Serverless.init (/usr/local/lib/node_modules/serverless/lib/Serverless.js:72:25)
at Object. (/usr/local/lib/node_modules/serverless/bin/serverless:17:12)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain (module.js:441:10)
at startup (node.js:139:18)
at node.js:968:3

When loading the plugin itself, it is trying to create a new Request object, which in turn is erroring out, since the required variables are niot present

**Comment by arabold** [comment]
`request` is a regular NPM module, not a Serverless plugin. You include it in your JavaScript code using `var request = require('request');` or something similar. There's absolutely no need to load NPM modules as Serverless plugins. Those are two totally different concepts:
* NPM modules are dependencies in your project, such as `request`
* Serverless plugins are extending the Serverless framework with additional functionality

The only thing both have in common is that many Serverless plugins are in fact installable via NPM.

**Comment by selvameenal** [comment]
Thanks for the response.

Now I understand the difference between the plugin and npm modules. 

I removed the request npm module from my plugins list. But in the bundled package, I cannot see the folder node_modules. Because of this I get an error message:

{
  "errorMessage": "Cannot find module 'request'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._load (module.js:276:25)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)",
    "Object.<anonymous> (/var/task/handler.js:1:75)",
    "Module._compile (module.js:409:26)",
    "Object.Module._extensions..js (module.js:416:10)",
    "Module.load (module.js:343:32)",
    "Function.Module._load (module.js:300:12)",
    "Module.require (module.js:353:17)"
  ]
}
Can you point me to the documentation how to bundle the dependant modules with the package that is deployed on lambda

**Comment by flomotlik** [comment]
When you do npm install in your Serverless folder it should create the node_modules folder in the same folder. If it doesn't could you check in another Node folder if you can see the dependencies being installed somewhere else?
