### ISSUE TITLE
knative quick-start error - The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by DineshChacko** [serverless/serverless#11022]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

cannot complete steps in quickstart guide - https://www.serverless.com/framework/docs/providers/knative/guide/quick-start
error: The "path" argument must be of type string. Received undefined

### Service configuration (serverless.yml) content

```yaml
service: my-service

frameworkVersion: '3'

provider:
  name: knative
  # optional Docker Hub credentials you need if you're using local Dockerfiles as function handlers
  docker:
    username: ${env:DOCKER_HUB_USERNAME}
    password: ${env:DOCKER_HUB_PASSWORD}

functions:
  hello:
    handler: hello-world.dockerfile
    context: ./code

plugins:
  - serverless-knative
```

### Command name and used flags

serverless deploy

### Command output

```shell
Environment: win32, node 16.14.2, framework 3.10.2, plugin 6.2.1, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:120:11)
    at Object.join (node:path:429:7)
    at Object.<anonymous> (C:\Programming\serverless\example\serverless-knative-example\my-service\node_modules\@serverless\kubernetes-namespace\serverless.js:7:24)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Programming\serverless\example\serverless-knative-example\my-service\node_modules\serverless-knative\deploy\lib\ensureNamespace.js:4:29)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Programming\serverless\example\serverless-knative-example\my-service\node_modules\serverless-knative\deploy\knativeDeploy.js:4:25)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Programming\serverless\example\serverless-knative-example\my-service\node_modules\serverless-knative\index.js:5:23)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at module.exports (C:\Users\dines\AppData\Roaming\npm\node_modules\serverless\lib\utils\import-module.js:5:12)
    at PluginManager.requireServicePlugin (C:\Users\dines\AppData\Roaming\npm\node_modules\serverless\lib\classes\plugin-manager.js:171:14)
    at PluginManager.resolveServicePlugins (C:\Users\dines\AppData\Roaming\npm\node_modules\serverless\lib\classes\plugin-manager.js:198:29)
    at PluginManager.loadAllPlugins (C:\Users\dines\AppData\Roaming\npm\node_modules\serverless\lib\classes\plugin-manager.js:136:47)
    at Serverless.init (C:\Users\dines\AppData\Roaming\npm\node_modules\serverless\lib\serverless.js:141:30)
    at async C:\Users\dines\AppData\Roaming\npm\node_modules\serverless\scripts\serverless.js:572:7
```

### Environment information

```shell
Framework Core: 3.10.2
Plugin: 6.2.1
SDK: 4.3.2

node -v
v16.14.2

npm -v
8.5.0
```

**Comment by pgrzesik** [comment]
Hello @DineshChacko - thanks a lot for reporting - as this is related to specific provider, please report the issue at `serverless-knative` repository. I'm going to close this one.
