### ISSUE TITLE
Serverless Core 3.16 + offline plugin - UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by naretini** [serverless/serverless#11030]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Updating my local dev env to Serverless core 3.16 

I'm getting the following error on every project after execution of :

`sls offline start`

Error:

`(node:39591) UnhandledPromiseRejectionWarning: Error: offline: one of the module nesting [object Object] for handler <MY-HANDLER> is undefined or not exported
    at InProcessRunner.run ([...]./node_modules/serverless-offline/dist/lambda/handler-runner/in-process-runner/InProcessRunner.js:171:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async process.<anonymous> ([...]./node_modules/serverless-offline/dist/lambda/handler-runner/child-process-runner/childProcessHelper.js:37:18)`

If I rollback to Serverless core 3.12 , all get back  working properly

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

sls offline start

### Command output

```shell
(node:39591) UnhandledPromiseRejectionWarning: Error: offline: one of the module nesting [object Object] for handler <MY-HANDLER> is undefined or not exported
    at InProcessRunner.run ([...]./node_modules/serverless-offline/dist/lambda/handler-runner/in-process-runner/InProcessRunner.js:171:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async process.<anonymous> ([...]./node_modules/serverless-offline/dist/lambda/handler-runner/child-process-runner/childProcessHelper.js:37:18)
```

### Environment information

```shell
Framework Core: 3.16.0 (local)
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by mnapoli** [comment]
Given the error message:

```
Error: offline: one of the module nesting [object Object] for handler <MY-HANDLER> is undefined or not exported at InProcessRunner.run ([...]./node_modules/serverless-offline/...
```

It looks like an error with the `serverless-offline` plugin. I think the next step would be to open an issue in their repository instead.

In the meantime I'll close this one. Let's reopen if needed!

**Comment by naretini** [comment]
I agree thanks, moved to [https://github.com/dherault/serverless-offline/issues/1390](serverless-offline)
