### ISSUE TITLE
ServerlessError: The Serverless version (1.58.0) does not satisfy the "frameworkVersion" (3) in serverless.yml

### ISSUE THREAD

**Issue by backseats** [serverless/serverless#11173]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I've installed, uninstalled, and re-installed serverless and I keep getting the following error whenever I try to do anything

> ServerlessError: The Serverless version (1.58.0) does not satisfy the "frameworkVersion" (3) in serverless.yml

I've tried the things that other tickets suggested, installing globally, upgrading as my terminal recommended, all to no avail.

Removing `frameworkVersion` from my `serverless.yml` file seemed to work for local development so the error didn't block me but on `serverless deploy`, I get this error:

> Error: Unknown object type "asyncfunction"

So I added back in the `frameworkVersion` line and now I can't deploy (or do anything else)

Would love some help. Thanks!

### Service configuration (serverless.yml) content

```yaml
service: myapp

frameworkVersion: "3"

provider:
  name: aws
  stage: prod
  runtime: nodejs16.x

functions:
  invisibles:
    handler: handler.invisibles
    events:
      - http:
          path: invisibles/{id}
          method: GET
          cors: true
          request:
            parameters:
              paths:
                id: true
    url:
      cors: true

  birbs:
    handler: handler.birbs
    events:
      - http:
          path: birbs/{id}
          method: GET
          cors: true
          request:
            parameters:
              paths:
                id: true
    url:
      cors: true
```
```


### Command name and used flags

serverless deploy

### Command output

```shell
$ serverless deploy
 
  Serverless Error ---------------------------------------
 
  ServerlessError: The Serverless version (1.58.0) does not satisfy the "frameworkVersion" (3) in serverless.yml
      at Service.loadServiceFileParam (/usr/local/lib/node_modules/serverless/lib/classes/Service.js:69:13)
      at /usr/local/lib/node_modules/serverless/lib/classes/Service.js:52:26
      at processImmediate (node:internal/timers:464:21)
  From previous event:
      at Service.load (/usr/local/lib/node_modules/serverless/lib/classes/Service.js:52:8)
      at /usr/local/lib/node_modules/serverless/lib/Serverless.js:74:29
      at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:90:16
      at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
  From previous event:
      at Serverless.init (/usr/local/lib/node_modules/serverless/lib/Serverless.js:66:8)
      at /usr/local/lib/node_modules/serverless/bin/serverless.js:71:8
      at processImmediate (node:internal/timers:464:21)
  From previous event:
      at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless.js:61:4)
      at Module._compile (node:internal/modules/cjs/loader:1109:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
      at Module.load (node:internal/modules/cjs/loader:989:32)
      at Function.Module._load (node:internal/modules/cjs/loader:829:14)
      at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
      at node:internal/main/run_main_module:17:47
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              16.3.0
     Framework Version:         1.58.0
     Plugin Version:            3.2.5
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```
```


### Environment information

```shell
$ serverless --version
 
  Serverless Error ---------------------------------------
 
  ServerlessError: The Serverless version (1.58.0) does not satisfy the "frameworkVersion" (3) in serverless.yml
      at Service.loadServiceFileParam (/usr/local/lib/node_modules/serverless/lib/classes/Service.js:69:13)
      at /usr/local/lib/node_modules/serverless/lib/classes/Service.js:52:26
      at processImmediate (node:internal/timers:464:21)
  From previous event:
      at Service.load (/usr/local/lib/node_modules/serverless/lib/classes/Service.js:52:8)
      at /usr/local/lib/node_modules/serverless/lib/Serverless.js:74:29
      at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:90:16
      at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
  From previous event:
      at Serverless.init (/usr/local/lib/node_modules/serverless/lib/Serverless.js:66:8)
      at /usr/local/lib/node_modules/serverless/bin/serverless.js:71:8
      at processImmediate (node:internal/timers:464:21)
  From previous event:
      at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless.js:61:4)
      at Module._compile (node:internal/modules/cjs/loader:1109:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
      at Module.load (node:internal/modules/cjs/loader:989:32)
      at Function.Module._load (node:internal/modules/cjs/loader:829:14)
      at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
      at node:internal/main/run_main_module:17:47
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              16.3.0
     Framework Version:         1.58.0
     Plugin Version:            3.2.5
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```
```

**Comment by pgrzesik** [comment]
Hello @backseats,

you've mention that you've reinstalled `serverless` - which method did you use to do so? Are you sure you don't have `serverless` installed somewhere on your system in older version? Setting `frameworkVersion: '3'` in your config won't automatically install that version for you, it will use the one you already have and warn you if the requirement is not satisfied.


I'll move this to discussions as it does not seem like a bug in the Framework.
