### ISSUE TITLE
TEMPLATE_DOWNLOAD_FAILED Timeout

### ISSUE THREAD

**Issue by guruavvaru** [serverless/serverless#11224]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I am behind corporate proxy, trying to download template but seeing timeout

  { ServerlessError: Could not download template. Ensure that you are using the latest version of Serverless Framework: Timeout awaiting 'request' for 30000ms
       at downloadTemplateFromExamples (/usr/local/lib/node_modules/serverless/lib/utils/download-template-from-examples.js:56:11)
       at processTicksAndRejections (node:internal/process/task_queues:96:5)
       at async Create.create (/usr/local/lib/node_modules/serverless/lib/plugins/create/create.js:49:7)
     [stack]:
      "ServerlessError: Could not download template. Ensure that you are using the latest version of Serverless Framework: Timeout awaiting 'request' for 30000ms\n    at downloadTemplateFromExamples (/usr/local/lib/node_modules/serverless/lib/utils/download-template-from-examples.js:56:11)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Create.create (/usr/local/lib/node_modules/serverless/lib/plugins/create/create.js:49:7)",
     [message]:
      "Could not download template. Ensure that you are using the latest version of Serverless Framework: Timeout awaiting 'request' for 30000ms",
     code: 'TEMPLATE_DOWNLOAD_FAILED',
     decoratedMessage: undefined,
     [name]: 'ServerlessError' },

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

 serverless create --template aws-nodejs --path todos1 --verbose --debug="*"

### Command output

```shell
process: resolve CLI input (no service schema)
process: construct Serverless instance
process: initialize Serverless instance
lifecycle:command:register: config
lifecycle:command:register: config:credentials
lifecycle:command:register: create
lifecycle:command:register: install
lifecycle:command:register: package
lifecycle:command:register: package:function
lifecycle:command:register: deploy
lifecycle:command:register: deploy:function
lifecycle:command:register: deploy:list
lifecycle:command:register: deploy:list:functions
lifecycle:command:register: invoke
lifecycle:command:register: invoke:local
lifecycle:command:register: info
lifecycle:command:register: logs
lifecycle:command:register: metrics
lifecycle:command:register: print
lifecycle:command:register: remove
lifecycle:command:register: rollback
lifecycle:command:register: rollback:function
lifecycle:command:register: slstats
lifecycle:command:register: plugin
lifecycle:command:register: plugin
lifecycle:command:register: plugin:list
lifecycle:command:register: plugin
lifecycle:command:register: plugin:search
lifecycle:command:register: config
lifecycle:command:register: config:credentials
lifecycle:command:register: upgrade
lifecycle:command:register: uninstall
lifecycle:command:register: login
lifecycle:command:register: logout
lifecycle:command:register: generate-event
lifecycle:command:register: test
lifecycle:command:register: dashboard
lifecycle:command:register: output
lifecycle:command:register: output:get
lifecycle:command:register: output:list
lifecycle:command:register: param
lifecycle:command:register: param:get
lifecycle:command:register: param:list
process: run Serverless instance
lifecycle:command:invoke: Invoke create
lifecycle:command:invoke:hook: [2] < create:create
Setting up a new project
(node:93522) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
lifecycle:command:invoke:hook: [2] > create:create
process: handle error
process: finalize { error:
   { ServerlessError: Could not download template. Ensure that you are using the latest version of Serverless Framework: Timeout awaiting 'request' for 30000ms
       at downloadTemplateFromExamples (/usr/local/lib/node_modules/serverless/lib/utils/download-template-from-examples.js:56:11)
       at processTicksAndRejections (node:internal/process/task_queues:96:5)
       at async Create.create (/usr/local/lib/node_modules/serverless/lib/plugins/create/create.js:49:7)
     [stack]:
      "ServerlessError: Could not download template. Ensure that you are using the latest version of Serverless Framework: Timeout awaiting 'request' for 30000ms\n    at downloadTemplateFromExamples (/usr/local/lib/node_modules/serverless/lib/utils/download-template-from-examples.js:56:11)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Create.create (/usr/local/lib/node_modules/serverless/lib/plugins/create/create.js:49:7)",
     [message]:
      "Could not download template. Ensure that you are using the latest version of Serverless Framework: Timeout awaiting 'request' for 30000ms",
     code: 'TEMPLATE_DOWNLOAD_FAILED',
     decoratedMessage: undefined,
     [name]: 'ServerlessError' },
  shouldBeSync: undefined,
  telemetryData: undefined,
  shouldSendTelemetry: undefined }
Environment: darwin, node 16.14.2, framework 3.20.0, plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Could not download template. Ensure that you are using the latest version of Serverless Framework: Timeout awaiting 'request' for 30000ms
telemetry: payload { ciName: null,
  isTtyTerminal: true,
  cliName: 'serverless',
  command: 'create',
  commandOptionNames: [ 'template', 'path', 'verbose', 'debug', [length]: 4 ],
  console: { userId: null },
  dashboard: { userId: null },
  firstLocalInstallationTimestamp: 1657138016,
  frameworkLocalUserId: '2f866b40-fd67-11ec-994c-871f18284980',
  installationType: 'global:npm',
  isAutoUpdateEnabled: false,
  isUsingCompose: false,
  notificationsMode: 'on',
  timestamp: 1657294281550,
  timezone: 'America/Los_Angeles',
  triggeredDeprecations: [ [length]: 0 ],
  versions: { serverless: '3.20.0', '@serverless/dashboard-plugin': '6.2.2' },
  commandDurationMs: 32802,
  commandUsage: {} }
```

### Environment information

```shell
Framework Core: 3.20.0
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by pgrzesik** [comment]
Hey @guruavvaru - thanks a lot for reporting and sorry you've run into trouble. Are you still running into this problem? We currently have it set strictly to 30 seconds of timeout, but maybe it should be configurable in such instances? What do you think?

**Comment by usualiron6413** [comment]
I'm getting the same error because I'm also behind some kind of corporate proxy. Mine doesn't timeout but just fails due to `self signed certificate in certificate chain`. Is there anyway to disable the certificate check?

**Comment by techbirds** [comment]
> Hey @guruavvaru - thanks a lot for reporting and sorry you've run into trouble. Are you still running into this problem? We currently have it set strictly to 30 seconds of timeout, but maybe it should be configurable in such instances? What do you think?

I also encountered it, and then solved it by modifying the timeout period of the source code. I have submitted a [PR](https://github.com/serverless/serverless/pull/11301) for this. Please review it, if there are any problems, I can further modify the [PR](https://github.com/serverless/serverless/pull/11301). thanks.

**Comment by mohammad-ahmadi-r** [comment]
i got the same issue

i have a terminal running localstack and also a running docker, so i stoped them all and in new termianl:
  npm install -g serverless@3.25.1

**Comment by yiGmMk** [comment]
this happens to me when I try to create a project using template like this (no login) and no err after I login in the console
`sls create -t aws-go-mod   `

Framework Core: 3.30.1
Plugin: 6.2.3
SDK: 4.3.2

Environment: linux, node 12.16.1, framework 3.30.1, plugin 6.2.3, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
Error:
Could not download template. Ensure that you are using the latest version of Serverless Framework: Timeout awaiting 'request' for 30000ms
