### ISSUE TITLE
Testing: ERROR: Error: Cannot find module '@serverless/test/setup/log'

### ISSUE THREAD

**Issue by pjmattingly** [serverless/serverless#11248]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

This seems to be related to the new version 3.21.0. I had attempted to test previous to this release and had no issue.

Steps to reproduce:

1) Clone serverless/serverless
2) `npm install`
3) `npm test`

----

In addition, there seems to be an issue with a call to `opencollective-postinstall`, which may be at the root of the issue:

```
'opencollective-postinstall' is not recognized as an internal or external command,
operable program or batch file.
```

See additional output from `npm install`, below.

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

N/A

### Command output

```shell
npm test

> serverless@3.21.0 test C:\Users\pmatt\Documents\Professional Work\Work\dev\dev, personal development\Minimize lodash dependency; #7747\serverless
> mocha "test/unit/**/*.test.js"


× ERROR: Error: Cannot find module '@serverless/test/setup/log'
Require stack:
- C:\Users\pmatt\AppData\Roaming\nvm\v12.22.12\node_modules\mocha\lib\nodejs\esm-utils.js
- C:\Users\pmatt\AppData\Roaming\nvm\v12.22.12\node_modules\mocha\lib\mocha.js
- C:\Users\pmatt\AppData\Roaming\nvm\v12.22.12\node_modules\mocha\lib\cli\one-and-dones.js
- C:\Users\pmatt\AppData\Roaming\nvm\v12.22.12\node_modules\mocha\lib\cli\options.js
- C:\Users\pmatt\AppData\Roaming\nvm\v12.22.12\node_modules\mocha\bin\mocha
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at exports.requireOrImport (C:\Users\pmatt\AppData\Roaming\nvm\v12.22.12\node_modules\mocha\lib\nodejs\esm-utils.js:60:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\pmatt\\AppData\\Roaming\\nvm\\v12.22.12\\node_modules\\mocha\\lib\\nodejs\\esm-utils.js',
    'C:\\Users\\pmatt\\AppData\\Roaming\\nvm\\v12.22.12\\node_modules\\mocha\\lib\\mocha.js',
    'C:\\Users\\pmatt\\AppData\\Roaming\\nvm\\v12.22.12\\node_modules\\mocha\\lib\\cli\\one-and-dones.js',
    'C:\\Users\\pmatt\\AppData\\Roaming\\nvm\\v12.22.12\\node_modules\\mocha\\lib\\cli\\options.js',
    'C:\\Users\\pmatt\\AppData\\Roaming\\nvm\\v12.22.12\\node_modules\\mocha\\bin\\mocha'
  ]
}
npm ERR! Test failed.  See above for more details.

----

 npm install

> husky@4.3.8 install C:\Users\pmatt\Documents\Professional Work\Work\dev\dev, personal development\Minimize lodash dependency; #7747\serverless\node_modules\husky
> node husky install

husky > Setting up git hooks
husky > Done

> es5-ext@0.10.61 postinstall C:\Users\pmatt\Documents\Professional Work\Work\dev\dev, personal development\Minimize lodash dependency; #7747\serverless\node_modules\es5-ext
>  node -e "try{require('./_postinstall')}catch(e){}" || exit 0


> husky@4.3.8 postinstall C:\Users\pmatt\Documents\Professional Work\Work\dev\dev, personal development\Minimize lodash dependency; #7747\serverless\node_modules\husky
> opencollective-postinstall || exit 0

'opencollective-postinstall' is not recognized as an internal or external command,
operable program or batch file.

> serverless@3.21.0 postinstall C:\Users\pmatt\Documents\Professional Work\Work\dev\dev, personal development\Minimize lodash dependency; #7747\serverless
> node ./scripts/postinstall.js

Serverless Framework successfully installed!

To start your first project run “serverless”.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1018 packages from 614 contributors and audited 1057 packages in 72.386s

159 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

### Environment information

```shell
serverless --version
'serverless' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by pjmattingly** [comment]
Even after installing WSL and trying it in Ubuntu the install still fails.

**Comment by pgrzesik** [comment]
Thanks for sharing @pjmattingly - could you share specific setup of your windows machine that you've experienced errors on? We're running installs and tests on Windows in CI and we've never run into this problem before.

**Comment by pjmattingly** [comment]
Sure, see the below link for the output of `msinfo32`. Then, as it seems pertinent, the issue seemed to start happening with the latest Windows update (KB5015814).

https://drive.google.com/file/d/165hzq4neTDPbODQxZW8KIYgbjGTUvuPf/view?usp=sharing
