### ISSUE TITLE
test/integration/curated-plugins-python.test.js failed

### ISSUE THREAD

**Issue by pjmattingly** [serverless/serverless#11297]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I was working on doing integration testing for #11281 and #11267, and found a repeatable failed test. Note here that we feed in the environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` with valid values; See https://github.com/serverless/serverless/issues/11281#issuecomment-1197993827

The test is `test/integration/curated-plugins-python.test.js`. Oddly this test fails in two different ways if ran by itself, or with the other integration tests. First, running the test by itself and its output:

```
AWS_ACCESS_KEY_ID=xxx AWS_SECRET_ACCESS_KEY=xxx npx mocha-isolated --pass-through-aws-creds --skip-fs-cleanup-check --max-workers=20 "test/integration/curated-plugins-python.test.js"
````
```
node /home/peter/dev_personal_development/serverless/node_modules/mocha/bin/_mocha test/integration/curated-plugins-python.test.js` Exited with code 1

test/integration/curated-plugins-python.test.js failed


test/integration/curated-plugins-python.test.js failed
```

Then when running it with a group of tests:
```
AWS_ACCESS_KEY_ID=xxx AWS_SECRET_ACCESS_KEY=xxx npx mocha-isolated --pass-through-aws-creds --skip-fs-cleanup-check --max-workers=20 "test/integration/{*.test.js,aws/*.test.js}"
```
```
\x1B[91mError:\x1B[39m\nError: STDOUT: \n\nSTDERR: /usr/bin/python3.8: No module named pip\n\n    at /tmp/tmpdirs-serverless/a234/9ffa32/node_modules/serverless-python-requirements/lib/pip.js:331:13\n    at Array.forEach (<anonymous>)\n    at installRequirements (/tmp/tmpdirs-serverless/a234/9ffa32/node_modules/serverless-python-requirements/lib/pip.js:318:28)\n    at installRequirementsIfNeeded (/tmp/tmpdirs-serverless/a234/9ffa32/node_modules/serverless-python-requirements/lib/pip.js:576:3)\n    at ServerlessPythonRequirements.installAllRequirements (/tmp/tmpdirs-serverless/a234/9ffa32/node_modules/serverless-python-requirements/lib/pip.js:655:29)\n    at ServerlessPythonRequirements.tryCatcher (/tmp/tmpdirs-serverless/a234/9ffa32/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/tmp/tmpdirs-serverless/a234/9ffa32/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/tmp/tmpdirs-serverless/a234/9ffa32/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/tmp/tmpdirs-serverless/a234/9ffa32/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/tmp/tmpdirs-serverless/a234/9ffa32/node_modules/bluebird/js/release/promise.js:729:18)\n    at _drainQueueStep (/tmp/tmpdirs-serverless/a234/9ffa32/node_modules/bluebird/js/release/async.js:93:12)\n
  at _drainQueue (/tmp/tmpdirs-serverless/a234/9ffa32/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/tmp/tmpdirs-serverless/a234/9ffa32/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/tmp/tmpdirs-serverless/a234/9ffa32/node_modules/bluebird/js/release/async.js:15:14)\n    at processImmediate (internal/timers.js:464:21)\n

`node /home/peter/dev_personal_development/serverless/node_modules/mocha/bin/_mocha test/integration/curated-plugins-python.test.js` Exited with code 1

test/integration/curated-plugins-python.test.js failed


test/integration/curated-plugins-python.test.js failed
```

Here we can see that the test seems to implicitly depend on `pip`. Installing `pip` seems to resolve the issue (`sudo apt install python3-pip`). Installing Ubuntu into WSL2 does not seem to include `pip` by default.

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
peter@DESKTOP-NHCM1G9:~/dev_personal_development/serverless$ serverless --version
Framework Core: 3.21.0
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by pgrzesik** [comment]
Hey @pjmattingly, thanks a lot for reporting. I think it's an implicit dependency of this test and the best we could potentially do is to add a note in documentation about it. Do you see any other potential improvement here?

**Comment by pjmattingly** [comment]
@pgrzesik 

Documentation seems to be a good first step. But I wonder if it would be possible to detect a python environment and skip or run tests based on that? The normal tests seem to have something like that:

```
 Notice: Some tests were skipped due to following environment issues:

 - test/unit/lib/plugins/aws/invokeLocal/index.test.js: Python: "before all" hook in "Python" (in: /serverless/test/unit/lib/plugins/aws/invoke-local/index.test.js)

   Python runtime is not installed
```

**Comment by pjmattingly** [comment]
@pgrzesik 

I made some small documentation changes to note this; See: https://github.com/serverless/serverless/pull/11298
