### ISSUE TITLE
serverless login throws SyntaxError: The URL's protocol must be... 

### ISSUE THREAD

**Issue by shukar1** [serverless/serverless#11346]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

`serverless login` throws and exception:

SyntaxError: The URL's protocol must be one of "ws:", "wss:", or "ws+unix:"

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

serverless login

### Command output

```shell
SyntaxError: The URL's protocol must be one of "ws:", "wss:", or "ws+unix:"
    at initAsClient (.../node_modules/ws/lib/websocket.js:693:17)
    at new WebSocket (.../node_modules/ws/lib/websocket.js:85:7)
    at ServerlessSDK.loginIdentity (.../node_modules/@serverless/platform-client/src/index.js:1066:16)
    at ServerlessSDK.login (.../node_modules/@serverless/platform-client/src/index.js:1139:70)
    at module.exports (.../node_modules/serverless/lib/commands/login/dashboard.js:13:64)
    at module.exports (.../node_modules/serverless/commands/login.js:43:55)
    at async .../node_modules/serverless/scripts/serverless.js:539:9
```

### Environment information

```shell
Framework Core: 3.22.0 (local) 3.22.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by mnapoli** [comment]
Hi, I can't reproduce the problem. Could you provide the complete command output instead of just the error?

**Comment by morficus** [comment]
Hello! 👋 
I'm running into this exact same error when using the `serveless login` command


```bash
$  serverless login
Running "serverless" from node_modules
Logging into the Serverless Dashboard via the browser
Environment: darwin, node 18.12.1, framework 3.26.0 (local) 3.10.2v (global), plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error:
SyntaxError: The URL's protocol must be one of "ws:", "wss:", or "ws+unix:"
    at initAsClient (<<path-to-project>>/node_modules/ws/lib/websocket.js:693:17)
    at new WebSocket (<<path-to-project>>/node_modules/ws/lib/websocket.js:85:7)
    at ServerlessSDK.loginIdentity (<<path-to-project>>/node_modules/@serverless/platform-client/src/index.js:1066:16)
    at ServerlessSDK.login (<<path-to-project>>/node_modules/@serverless/platform-client/src/index.js:1139:70)
    at module.exports (<<path-to-project>>/node_modules/serverless/lib/commands/login/dashboard.js:13:64)
    at module.exports (<<path-to-project>>/node_modules/serverless/commands/login.js:36:55)
    at async <<path-to-project>>/node_modules/serverless/scripts/serverless.js:556:9
```

**Comment by RobbyKetchell** [comment]
Hi, I had a similar issue. Try removing `node_modules`, deleting `package-lock.json` and running `npm cache clean --force`.  Then reinstall your dependencies with `npm install` and try again.

**Comment by burslf** [comment]
@RobbyKetchell this didn't work for me, that is weird because it  was working before, and on my other projects when i run the command it works.

**Comment by codedge** [comment]
I get this error too.

Environment: darwin
node 19.6.0
framework 3.27.0 (local) 3.27.0v (global)
plugin 6.2.3
SDK 4.3.2

```
serverless login
Running "serverless" from node_modules
(node:48475) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
Logging into the Serverless Dashboard via the browser
Environment: darwin, node 19.6.0, framework 3.27.0 (local) 3.27.0v (global), plugin 6.2.3, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
SyntaxError: The URL's protocol must be one of "ws:", "wss:", or "ws+unix:"
    at initAsClient (/Users/holger/node_modules/ws/lib/websocket.js:695:17)
    at new WebSocket (/Users/holger/node_modules/ws/lib/websocket.js:85:7)
    at ServerlessSDK.loginIdentity (/Users/holger/node_modules/@serverless/platform-client/src/index.js:1066:16)
    at ServerlessSDK.login (/Users/holger/node_modules/@serverless/platform-client/src/index.js:1139:70)
    at module.exports (/Users/holger/node_modules/serverless/lib/commands/login/dashboard.js:13:64)
    at module.exports (/Users/holger/node_modules/serverless/commands/login.js:36:55)
    at async /Users/holger/node_modules/serverless/scripts/serverless.js:556:9
```

No idea how to proceed deploying.

**Comment by FloUz-ai** [comment]
same here

**Comment by Jacesheck** [comment]
Had the same problem. Deleting my entire personal git project on my computer and pulling from git worked for me. I was on the careful side and ran serverless login directly after cloning.

**Comment by safa-kajabi** [comment]
Could someone please assist me with this? I'm encountering the same issue.

**Comment by arjunkmrm** [comment]
I fixed this with a node upgrade. Node 18 was causing issues, and the update to latest solved. 
```shell
nvm install --lts
```

and also run this within your project directory:
```shell
nvm use 22.13.1
```

refer to for nvm installation: https://github.com/nvm-sh/nvm
