### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by ianzone** [serverless/serverless#11358]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

see command output below

### Service configuration (serverless.yml) content

```yaml
"N/A"
```

### Command name and used flags

sls package --stage prod

### Command output

```shell
Using local credentials. Add provider credentials via dashboard: https://app.serverless.com//providers

Packaging nylas-integration-api for stage prod (us-east-1)
Environment: linux, node 16.17.0, framework 3.22.0 (local) 3.22.0v (global), plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
TypeError: Cannot read properties of undefined (reading 'includes')
    at ServerlessEnterprisePlugin.<anonymous> (/home/ian/serverless-projects/nylas/api/node_modules/@serverless/dashboard-plugin/lib/plugin.js:242:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PluginManager.runHooks (/home/ian/serverless-projects/nylas/api/node_modules/serverless/lib/classes/plugin-manager.js:530:9)
    at async PluginManager.invoke (/home/ian/serverless-projects/nylas/api/node_modules/serverless/lib/classes/plugin-manager.js:563:9)
    at async PluginManager.run (/home/ian/serverless-projects/nylas/api/node_modules/serverless/lib/classes/plugin-manager.js:604:7)
    at async Serverless.run (/home/ian/serverless-projects/nylas/api/node_modules/serverless/lib/serverless.js:174:5)
    at async /home/ian/serverless-projects/nylas/api/node_modules/serverless/scripts/serverless.js:771:9
```
```


### Environment information

```shell
Framework Core: 3.22.0 (local) 3.22.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
Tencent CLI: 3.21.6 (binary)
```

**Comment by medikoo** [comment]
@ianzone I believe it was some temporary issue with Dashboard service, or do you observe it constantly?
