### ISSUE TITLE
serverless compose deploy consistently fails with statusCode 401 message Unauthorized

### ISSUE THREAD

**Issue by miguelespinoza** [serverless/serverless#11457]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I'm unable to deploy using serverless compose.
When I originally migrated to serverless v3, I moved to serverless compose, and things worked. But unexpectedly I've been unable to successfully deploy all services.

It only works if I individually deploy a service using this syntax: `serverless service-1:deploy --stage staging`. Ideally, I would like to avoid this.

Just before posting this, I upgraded to the latest v3.23.0 and still got the same error message

### Service configuration (serverless.yml) content

```yaml
# serverless-compose.yml
services:
  service-1:
    path: services/service-1
# same for service-2 -> service-5

# services/service-1/serverless.yml
console: true
org: ***
app: ***
service: collect
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

custom:
  stages:
    - local
    - dev
    - staging
    - prod
  currentStage: ${opt:stage, self:provider.stage}

  esbuild:
    exclude: ['aws-sdk', 'pg-native']
    plugins: ./esbuild-plugins.js
    bundle: true
    minify: true
    sourcemap: true


functions:
  main:
    handler: handler.main
    name: ${self:custom.currentStage}-service-1-job
    timeout: 30
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - CollectQueue
              - Arn
          batchSize: 1

resources:
  Resources:
    # some queues created

plugins:
  - serverless-esbuild
  - serverless-stage-manager
  - serverless-offline
  - serverless-apigateway-service-proxy
```

### Command name and used flags

serverless deploy --stage staging

### Command output

```shell
Deploying to stage staging
service-1 › waiting
service-2 › waiting
service-3 › waiting
service-4 › waiting
service-5 › waiting
service-6 › waiting
service-1 › deploying
service-2 › deploying
service-5 › deploying
service-6 › deploying
service-1 › Running "serverless deploy --stage staging"
service-2 › Running "serverless deploy --stage staging"
service-5 › Running "serverless deploy --stage staging"
service-6 › Running "serverless deploy --stage staging"
service-1 › Environment: darwin, node 16.16.0, framework 3.22.0 (local), plugin 6.2.2, SDK 4.3.2
service-1 › Credentials: Serverless Dashboard, "project-aws" provider (https://app.serverless.com/project/service-1/staging/us-east-1/providers)
service-1 › Docs:        docs.serverless.com
service-1 › Support:     forum.serverless.com
service-1 › Bugs:        github.com/serverless/serverless/issues
service-1 › Error:
service-1 › Error: Console server error: {"statusCode":401,"message":"Unauthorized"}
service-1 ›     at module.exports (/Users/hello/Code/project/node_modules/@serverless/utils/auth/resolve-token.js:70:13)
service-1 ›     at processTicksAndRejections (node:internal/process/task_queues:96:5)
service-1 ›     at async /Users/hello/Code/project/node_modules/@serverless/utils/auth/resolve-mode.js:11:7
service-1 ›     at async module.exports (/Users/hello/Code/project/node_modules/@serverless/utils/auth/resolve-mode.js:9:22)
service-1 ›     at async Console.initialize (/Users/hello/Code/project/node_modules/serverless/lib/classes/console.js:64:11)
service-1 ›     at async Serverless.run (/Users/hello/Code/project/node_modules/serverless/lib/serverless.js:167:7)
service-1 ›     at async /Users/hello/Code/project/node_modules/serverless/scripts/serverless.js:771:9
service-6 › Environment: darwin, node 16.16.0, framework 3.22.0 (local), plugin 6.2.2, SDK 4.3.2
service-6 › Credentials: Serverless Dashboard, "project-aws" provider (https://app.serverless.com/project/service-6/staging/us-east-1/providers)
service-6 › Docs:        docs.serverless.com
service-6 › Support:     forum.serverless.com
service-6 › Bugs:        github.com/serverless/serverless/issues
service-6 › Error:
service-6 › Error: Console server error: {"statusCode":401,"message":"Unauthorized"}
service-6 ›     at module.exports (/Users/hello/Code/project/node_modules/@serverless/utils/auth/resolve-token.js:70:13)
service-6 ›     at processTicksAndRejections (node:internal/process/task_queues:96:5)
service-6 ›     at async /Users/hello/Code/project/node_modules/@serverless/utils/auth/resolve-mode.js:11:7
service-6 ›     at async module.exports (/Users/hello/Code/project/node_modules/@serverless/utils/auth/resolve-mode.js:9:22)
service-6 ›     at async Console.initialize (/Users/hello/Code/project/node_modules/serverless/lib/classes/console.js:64:11)
service-6 ›     at async Serverless.run (/Users/hello/Code/project/node_modules/serverless/lib/serverless.js:167:7)
service-6 ›     at async /Users/hello/Code/project/node_modules/serverless/scripts/serverless.js:771:9
service-5 › Deploying service-5 to stage staging (us-east-1, "project-aws" provider)
service-2 › Environment: darwin, node 16.16.0, framework 3.22.0 (local), plugin 6.2.2, SDK 4.3.2
service-2 › Credentials: Serverless Dashboard, "project-aws" provider (https://app.serverless.com/project/service-2/staging/us-east-1/providers)
service-2 › Docs:        docs.serverless.com
service-2 › Support:     forum.serverless.com
service-2 › Bugs:        github.com/serverless/serverless/issues
service-2 › Error:
service-2 › Error: Console server error: {"statusCode":401,"message":"Unauthorized"}
service-2 ›     at module.exports (/Users/hello/Code/project/node_modules/@serverless/utils/auth/resolve-token.js:70:13)
service-2 ›     at processTicksAndRejections (node:internal/process/task_queues:96:5)
service-2 ›     at async /Users/hello/Code/project/node_modules/@serverless/utils/auth/resolve-mode.js:11:7
service-2 ›     at async module.exports (/Users/hello/Code/project/node_modules/@serverless/utils/auth/resolve-mode.js:9:22)
service-2 ›     at async Console.initialize (/Users/hello/Code/project/node_modules/serverless/lib/classes/console.js:64:11)
service-2 ›     at async Serverless.run (/Users/hello/Code/project/node_modules/serverless/lib/serverless.js:167:7)
service-2 ›     at async /Users/hello/Code/project/node_modules/serverless/scripts/serverless.js:771:9
service-1 › error
service-1 › Error:
service-1 › Error: Console server error: {"statusCode":401,"message":"Unauthorized"}
service-1 ›     at module.exports (/Users/hello/Code/project/node_modules/@serverless/utils/auth/resolve-token.js:70:13)
service-1 ›     at processTicksAndRejections (node:internal/process/task_queues:96:5)
service-1 ›     at async /Users/hello/Code/project/node_modules/@serverless/utils/auth/resolve-mode.js:11:7
service-1 ›     at async module.exports (/Users/hello/Code/project/node_modules/@serverless/utils/auth/resolve-mode.js:9:22)
service-1 ›     at async Console.initialize (/Users/hello/Code/project/node_modules/serverless/lib/classes/console.js:64:11)
service-1 ›     at async Serverless.run (/Users/hello/Code/project/node_modules/serverless/lib/serverless.js:167:7)
service-1 ›     at async /Users/hello/Code/project/node_modules/serverless/scripts/serverless.js:771:9
service-1 ›
service-6 › error
service-6 › Error:
service-6 › Error: Console server error: {"statusCode":401,"message":"Unauthorized"}
service-6 ›     at module.exports (/Users/hello/Code/project/node_modules/@serverless/utils/auth/resolve-token.js:70:13)
service-6 ›     at processTicksAndRejections (node:internal/process/task_queues:96:5)
service-6 ›     at async /Users/hello/Code/project/node_modules/@serverless/utils/auth/resolve-mode.js:11:7
service-6 ›     at async module.exports (/Users/hello/Code/project/node_modules/@serverless/utils/auth/resolve-mode.js:9:22)
service-6 ›     at async Console.initialize (/Users/hello/Code/project/node_modules/serverless/lib/classes/console.js:64:11)
service-6 ›     at async Serverless.run (/Users/hello/Code/project/node_modules/serverless/lib/serverless.js:167:7)
service-6 ›     at async /Users/hello/Code/project/node_modules/serverless/scripts/serverless.js:771:9
service-6 ›
service-2 › error
service-2 › Error:
service-2 › Error: Console server error: {"statusCode":401,"message":"Unauthorized"}
service-2 ›     at module.exports (/Users/hello/Code/project/node_modules/@serverless/utils/auth/resolve-token.js:70:13)
service-2 ›     at processTicksAndRejections (node:internal/process/task_queues:96:5)
service-2 ›     at async /Users/hello/Code/project/node_modules/@serverless/utils/auth/resolve-mode.js:11:7
service-2 ›     at async module.exports (/Users/hello/Code/project/node_modules/@serverless/utils/auth/resolve-mode.js:9:22)
service-2 ›     at async Console.initialize (/Users/hello/Code/project/node_modules/serverless/lib/classes/console.js:64:11)
service-2 ›     at async Serverless.run (/Users/hello/Code/project/node_modules/serverless/lib/serverless.js:167:7)
service-2 ›     at async /Users/hello/Code/project/node_modules/serverless/scripts/serverless.js:771:9
service-2 ›
service-5 › ✔ Service deployed to stack service-5-staging (113s)
service-5 › console: https://console.serverless.com/project/metrics/functions?globalEnvironments=staging&globalNamespaces=service-5&globalRegions=us-east-1&globalScope=functions&globalTimeFrame=15m
service-5 › dashboard: https://app.serverless.com/project/service-5/staging/us-east-1
service-5 › functions:
service-5 ›   main: staging-service-5 (18 MB)
service-5 › Running "serverless info --verbose --stage staging"
service-5 › Environment: darwin, node 16.16.0, framework 3.22.0 (local), plugin 6.2.2, SDK 4.3.2
service-5 › Credentials: Serverless Dashboard, "project-aws" provider (https://app.serverless.com/project/service-5/staging/us-east-1/providers)
service-5 › Docs:        docs.serverless.com
service-5 › Support:     forum.serverless.com
service-5 › Bugs:        github.com/serverless/serverless/issues
service-5 › Error:
service-5 › You are not currently logged in. To log in, run "serverless login --console"
service-5 › error
service-5 › Error:
service-5 › You are not currently logged in. To log in, run "serverless login --console"
service-5 ›
service-3 › skipped
service-4 › skipped
```

### Environment information

```shell
Framework Core: 3.22.0 (local) 3.22.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by medikoo** [comment]
@miguelespinoza Did you succeed in deploying to Console with Serverless Compose in the past? Or have error occurred once you've enabled Console?

**Comment by medikoo** [comment]
@miguelespinoza Compose, due to its internal design, cannot work reliably with this version of the Serverless Console, and this problem surfaces once you add more services.

Still, shortly we should roll out upgrade to the Serverless Console and this new version should work with compose without issues

**Comment by miguelespinoza** [comment]
yikes, what a bummer!

what's the schedule for the latest upgrade to the Serverless Console?
