### ISSUE TITLE
Name of authorizerFunction doesn't work with environment variables

### ISSUE THREAD

**Issue by OneMuppet** [serverless/serverless#1190]
I can use the custom name property to name my custom authorizer lambda function with environment variables, like this:
```json
"customName": "${project}-${stage}-auth",
```

but when I want to specify a custom authorizer lambda in any of my s-function.json files, like this:
```json
"authorizerFunction": "${project}-${stage}-auth",
```

I get this error when deploying:
```bash
<function name> has an 'authorizerFunction' specified that does not exist in this project.  Make sure the function's 'authorizer' property is filled in  
```

stacktrace:
```
at /Users/username/.node/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:154:29
From previous event:
  at /Users/username/.node/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:146:35
  at /Users/username/.node/lib/node_modules/serverless/node_modules/async/lib/async.js:181:20
  at iterate (/Users/username/.node/lib/node_modules/serverless/node_modules/async/lib/async.js:262:13)
  at /Users/username/.node/lib/node_modules/serverless/node_modules/async/lib/async.js:274:29
  at /Users/username/.node/lib/node_modules/serverless/node_modules/async/lib/async.js:44:16
  at /Users/username/.node/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:185:26
From previous event:
  at /Users/username/.node/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:174:18
  at /Users/username/.node/lib/node_modules/serverless/node_modules/async/lib/async.js:181:20
  at iterate (/Users/username/.node/lib/node_modules/serverless/node_modules/async/lib/async.js:262:13)
  at Object.async.forEachOfSeries.async.eachOfSeries (/Users/username/.node/lib/node_modules/serverless/node_modules/async/lib/async.js:281:9)
  at Object.async.forEachSeries.async.eachSeries (/Users/username/.node/lib/node_modules/serverless/node_modules/async/lib/async.js:214:22)
  at /Users/username/.node/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:144:19
From previous event:
  at EndpointDeployApiGateway.<anonymous> (/Users/username/.node/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:141:18)
From previous event:
  at EndpointDeployApiGateway._processRegionDeployment (/Users/username/.node/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:137:10)
  at EndpointDeployApiGateway.<anonymous> (/Users/username/.node/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:94:24)
From previous event:
  at EndpointDeployApiGateway._processDeployment (/Users/username/.node/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:91:10)
From previous event:
  at EndpointDeployApiGateway.endpointDeployApiGateway (/Users/username/.node/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:55:10)
From previous event:
  at /Users/username/.node/lib/node_modules/serverless/lib/Serverless.js:211:25
  at Array.reduce (native)
  at Serverless._execute (/Users/username/.node/lib/node_modules/serverless/lib/Serverless.js:210:26)
  at Object.actions.(anonymous function) [as endpointDeployApiGateway] (/Users/username/.node/lib/node_modules/serverless/lib/Serverless.js:429:20)
  at EndpointDeploy._processDeployment (/Users/username/.node/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:212:24)
From previous event:
  at EndpointDeploy.endpointDeploy (/Users/username/.node/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:101:12)
From previous event:
  at /Users/username/.node/lib/node_modules/serverless/lib/Serverless.js:186:31
  at Array.reduce (native)
  at /Users/username/.node/lib/node_modules/serverless/lib/Serverless.js:185:32
From previous event:
  at Serverless._execute (/Users/username/.node/lib/node_modules/serverless/lib/Serverless.js:183:12)
  at Serverless.actions.(anonymous function) (/Users/username/.node/lib/node_modules/serverless/lib/Serverless.js:429:20)
  at Serverless.command (/Users/username/.node/lib/node_modules/serverless/lib/Serverless.js:398:38)
  at /Users/username/.node/lib/node_modules/serverless/bin/serverless:19:16
  at processImmediate [as _immediateCallback] (timers.js:384:17)
From previous event:
  at Object.<anonymous> (/Users/username/.node/lib/node_modules/serverless/bin/serverless:18:4)
  at Module._compile (module.js:399:26)
  at Object.Module._extensions..js (module.js:406:10)
  at Module.load (module.js:345:32)
  at Function.Module._load (module.js:302:12)
  at Function.Module.runMain (module.js:431:10)
  at startup (node.js:141:18)
```

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
