### ISSUE TITLE
npm ERR! notarget No matching version found for xml2js@0.5.0.

### ISSUE THREAD

**Issue by vishwakarma-ashish-lgim** [serverless/serverless#11911]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Hi All,
We are using serverless-s3-sync@2.0.0 in our application. We do deploy our code through CD which was working correct previously but now suddenly its getting failed with the below error. We checked the xml2js version which was upgraded recently in 
serverless-s3-sync@2.0.0.

We tried to use version 3.1.0 but getting below error after executing below command.
serverless plugin install --name serverless-s3-sync@3.1.0 --stage dev --param=appVersion=5.0.6 --param=gitHash=7489b9c839

npm ERR! code ETARGET
17:39:22    npm ERR! notarget No matching version found for json-cycle@^1.4.0.
17:39:22    npm ERR! notarget In most cases you or one of your dependencies are requesting
17:39:22    npm ERR! notarget a package version that doesn't exist.
17:39:22    
17:39:22    npm ERR! A complete log of this run can be found in:
17:39:22    npm ERR!     /opt/jenkins/npm-repo-v2/_logs/2023-04-12T16_39_15_632Z-debug.log
17:39:22    
17:39:22  Environment: linux, node 16.16.0, framework 3.25.0 (standalone), plugin 6.2.2, SDK 4.3.2
17:39:22  Docs:        docs.serverless.com
17:39:22  Support:     forum.serverless.com
17:39:22  Bugs:        github.com/serverless/serverless/issues
17:39:22  
17:39:22  Error:
17:39:22  Error: `node /snapshot/serverless/node_modules/npm/bin/npm-cli.js install --save-dev serverless-s3-sync@3.1.0` Exited with code 1
17:39:22      at ChildProcess.<anonymous> (/snapshot/serverless/node_modules/child-process-ext/spawn.js:38:8)
17:39:22      at ChildProcess.emit (node:events:527:28)
17:39:22      at ChildProcess.emit (node:domain:475:12)
17:39:22      at maybeClose (node:internal/child_process:1092:16)
17:39:22      at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

serverless plugin install --name serverless-s3-sync@3.1.0 --stage dev --param=appVersion=5.0.6 --param=gitHash=7489b9c839

### Command output

```shell
npm ERR! code ETARGET
17:39:22    npm ERR! notarget No matching version found for json-cycle@^1.4.0.
17:39:22    npm ERR! notarget In most cases you or one of your dependencies are requesting
17:39:22    npm ERR! notarget a package version that doesn't exist.
17:39:22    
17:39:22    npm ERR! A complete log of this run can be found in:
17:39:22    npm ERR!     /opt/jenkins/npm-repo-v2/_logs/2023-04-12T16_39_15_632Z-debug.log
17:39:22    
17:39:22  Environment: linux, node 16.16.0, framework 3.25.0 (standalone), plugin 6.2.2, SDK 4.3.2
17:39:22  Docs:        docs.serverless.com
17:39:22  Support:     forum.serverless.com
17:39:22  Bugs:        github.com/serverless/serverless/issues
17:39:22  
17:39:22  Error:
17:39:22  Error: `node /snapshot/serverless/node_modules/npm/bin/npm-cli.js install --save-dev serverless-s3-sync@3.1.0` Exited with code 1
17:39:22      at ChildProcess.<anonymous> (/snapshot/serverless/node_modules/child-process-ext/spawn.js:38:8)
17:39:22      at ChildProcess.emit (node:events:527:28)
17:39:22      at ChildProcess.emit (node:domain:475:12)
17:39:22      at maybeClose (node:internal/child_process:1092:16)
17:39:22      at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

### Environment information

```shell
3.1.0
```

**Comment by medikoo** [comment]
@vishwakarma-ashish-lgim this looks as issue in `serverless-s3-sync` and not in the Framework, please report at their repository
