### ISSUE TITLE
deploy and package don't work if you run them in parallel for the same service

### ISSUE THREAD

**Issue by fackyhigh** [serverless/serverless#11957]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Issue partly related to: https://github.com/serverless/serverless/issues/3525

Description: We have **one** service and different environments for it to deploy. We use the following scripts:
for packaging: `sls package -s "${ENVIRONMENT:-dev}" --package "./sls-package-${ENVIRONMENT:-dev}"`
for deploy: `sls deploy -s "${ENVIRONMENT:-dev}" --force --verbose --package "./sls-package-${ENVIRONMENT:-dev}"`

The `ENVIRONMENT` param is taken from environment variable that set by CI server.

When we run packaging or deployment in multiple environments sequentially, a job succeeds. When we run it in parallel it fails.

The problem is, that in time of packaging or deployment, serverless creates .serverless folder which simultaneously used by all copies of the service in the root of the project. Because of that a race condition happens.

The solution is to create .serverless folder under the folder which was passed as the argument for --package parameter. Like this: `./sls-package-dev/.serverless`.

I don't know if it's mandatory to create .serverless folder in the root of the project for packaging. But for deploy this temporary folder may be created inside the --package dir, for sure.

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

sls deploy -s <dev|dev1|dev2> --force --verbose --package ./sls-package-<dev|dev1|dev2>

### Command output

```shell
For parallel deployment of one service to multiple environments we may have different errors for each stage.

Example:

dev environment:
No /opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/.serverless/pip-ocr-preprocessing.zip file found in the package path you provided.

dev1 evironment:
Error: EEXIST: file already exists, mkdir '/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/.serverless/requirements/aws_lambda_powertools/middleware_factory'
    at Object.mkdirSync (node:fs:1349:3)
    at mkDirAndCopy (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/fs-extra/lib/copy/copy-sync.js:112:6)
    at onDir (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/fs-extra/lib/copy/copy-sync.js:107:25)
    at getStats (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/fs-extra/lib/copy/copy-sync.js:48:37)
    at startCopy (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/fs-extra/lib/copy/copy-sync.js:41:10)
    at copyDirItem (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/fs-extra/lib/copy/copy-sync.js:125:10)
    at /opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/fs-extra/lib/copy/copy-sync.js:118:39
    at Array.forEach (<anonymous>)
    at copyDir (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/fs-extra/lib/copy/copy-sync.js:118:23)
    at mkDirAndCopy (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/fs-extra/lib/copy/copy-sync.js:113:3)
    at onDir (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/fs-extra/lib/copy/copy-sync.js:107:25)
    at getStats (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/fs-extra/lib/copy/copy-sync.js:48:37)
    at startCopy (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/fs-extra/lib/copy/copy-sync.js:41:10)
    at copyDirItem (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/fs-extra/lib/copy/copy-sync.js:125:10)
    at /opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/fs-extra/lib/copy/copy-sync.js:118:39
    at Array.forEach (<anonymous>)
    at copyDir (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/fs-extra/lib/copy/copy-sync.js:118:23)
    at onDir (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/fs-extra/lib/copy/copy-sync.js:108:10)
    at getStats (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/fs-extra/lib/copy/copy-sync.js:48:37)
    at startCopy (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/fs-extra/lib/copy/copy-sync.js:41:10)
    at copyDirItem (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/fs-extra/lib/copy/copy-sync.js:125:10)
    at /opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/fs-extra/lib/copy/copy-sync.js:118:39
    at Array.forEach (<anonymous>)
    at copyDir (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/fs-extra/lib/copy/copy-sync.js:118:23)
    at onDir (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/fs-extra/lib/copy/copy-sync.js:108:10)
    at getStats (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/fs-extra/lib/copy/copy-sync.js:48:37)
    at handleFilterAndCopy (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/fs-extra/lib/copy/copy-sync.js:36:10)
    at Object.copySync (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/fs-extra/lib/copy/copy-sync.js:29:10)
    at copyDirContentsSync (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/serverless/lib/utils/fs/copy-dir-contents-sync.js:12:7)
    at Utils.copyDirContentsSync (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/serverless/lib/classes/utils.js:90:12)
    at AwsCommon.moveArtifactsToTemp (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/serverless/lib/plugins/aws/common/lib/artifacts.js:43:31)
    at aws:common:moveArtifactsToTemp:move (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/serverless/lib/plugins/aws/common/index.js:54:57)
    at PluginManager.runHooks (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/serverless/lib/classes/plugin-manager.js:530:15)
    at PluginManager.invoke (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/serverless/lib/classes/plugin-manager.js:564:20)
    at async PluginManager.spawn (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/serverless/lib/classes/plugin-manager.js:585:5)
    at async before:deploy:deploy (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/serverless/lib/plugins/aws/deploy/index.js:127:9)
    at async PluginManager.runHooks (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/serverless/lib/classes/plugin-manager.js:530:9)
    at async PluginManager.invoke (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/serverless/lib/classes/plugin-manager.js:563:9)
    at async PluginManager.run (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/serverless/lib/classes/plugin-manager.js:604:7)
    at async Serverless.run (/opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/serverless/lib/serverless.js:179:5)
    at async /opt/jenkins/workspace/MAL/PROJECTS/DBI/PIP/PIP/ocr-preprocessing/develop/14/ocr-preprocessing/node_modules/serverless/scripts/serverless.js:812:9

dev3:
Stack deployed successfully
```

### Environment information

```shell
Framework Core: 3.30.1 (local)
Plugin: 6.2.3
SDK: 4.3.2
```

**Comment by medikoo** [comment]
@fackyhigh yes, using `serverless` command simultaneously on the same service (folder) is definitely not supported, yet there's no validation implied for that.

We could probably create some sort of _lock_ file, to deal with that (if anyone is interested PR's welcome, but let's first agree on methodology)

Otherwise, in your case, I believe solution is to either deploy one by one. or clone the service into multiple folders and deploy from each folder independently different service setting

**Comment by fackyhigh** [comment]
@medikoo thank you for your answer.

> We could probably create some sort of lock file, to deal with that (if anyone is interested PR's welcome, but let's first agree on methodology)
— We use Jenkins for the pipeline mentioned above. It's already have the lock mechanism, and we use it right now. Because without it we face the race condition. So, regarding the lock file it's up to you.

> Otherwise, in your case, I believe solution is to either deploy one by one. 
— As I said, for now, we deploy one by one. But our goal is to deploy simultaneously. Nowadays, the fast delivery of your code to customers is very important factor to be successful company. That's why we need to deploy in parallel. And I guess not only our company thinks so.

> or clone the service into multiple folders and deploy from each folder independently different service setting
— Did it already. The downsides of this approach are speed and disk space. Copy all files N-times and then deploy in parallel is slower than doing it without cloning. I measured the speed for average sized repository. With cloning all files and deploying them in parallel it took 13 minutes. Deploying one by one took 14 minutes. Imagine what will be if we have a bigger git repository to clone it multiple times, then it'll be even slower than deploy it one by one. Moreover, you have to have bigger disks for that, plus cleaning those copies will take extra time.

Our suggestion is to create the .serverless temporary folder under the folder which you passed as the argument for the --package flag. If there is on --package flag create the folder in the root of the project. Why don't want to do so?
