### ISSUE TITLE
Error: Cannot find module './util'

### ISSUE THREAD

**Issue by ammaratef45** [serverless/serverless#12006]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When I run `serverless deploy` or simply `serverless` I get the error below

```
ammarhs@88665a58d58c api % serverless deploy   
Environment: darwin, node 20.2.0, framework 3.32.2, plugin 6.2.3, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: Cannot find module './util'
Require stack:
- /Users/ammarhs/Desktop/aws-iot-chat-example/api/node_modules/bluebird/js/release/promise.js
- /Users/ammarhs/Desktop/aws-iot-chat-example/api/node_modules/bluebird/js/release/bluebird.js
- /Users/ammarhs/Desktop/aws-iot-chat-example/api/node_modules/serverless-webpack/index.js
- /usr/local/lib/node_modules/serverless/lib/utils/require-with-import-fallback.js
- /usr/local/lib/node_modules/serverless/lib/classes/plugin-manager.js
- /usr/local/lib/node_modules/serverless/lib/serverless.js
- /usr/local/lib/node_modules/serverless/scripts/serverless.js
- /usr/local/lib/node_modules/serverless/bin/serverless.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1070:15)
    at Module._load (node:internal/modules/cjs/loader:923:27)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at require (node:internal/modules/helpers:121:18)
    at module.exports (/Users/ammarhs/Desktop/aws-iot-chat-example/api/node_modules/bluebird/js/release/promise.js:14:12)
    at Object.<anonymous> (/Users/ammarhs/Desktop/aws-iot-chat-example/api/node_modules/bluebird/js/release/bluebird.js:9:36)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at require (node:internal/modules/helpers:121:18)
    at Object.<anonymous> (/Users/ammarhs/Desktop/aws-iot-chat-example/api/node_modules/serverless-webpack/index.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at require (node:internal/modules/helpers:121:18)
    at module.exports (/usr/local/lib/node_modules/serverless/lib/utils/require-with-import-fallback.js:5:12)
    at PluginManager.requireServicePlugin (/usr/local/lib/node_modules/serverless/lib/classes/plugin-manager.js:171:14)
    at PluginManager.resolveServicePlugins (/usr/local/lib/node_modules/serverless/lib/classes/plugin-manager.js:198:29)
    at PluginManager.loadAllPlugins (/usr/local/lib/node_modules/serverless/lib/classes/plugin-manager.js:136:47)
    at Serverless.init (/usr/local/lib/node_modules/serverless/lib/serverless.js:146:30)
    at async /usr/local/lib/node_modules/serverless/scripts/serverless.js:616:7
```

### Service configuration (serverless.yml) content

```yaml
The one from [this repo](https://github.com/aws-samples/aws-iot-chat-example/blob/master/api/serverless.yml)
```

### Command name and used flags

serverless deploy

### Command output

```shell
Environment: darwin, node 20.2.0, framework 3.32.2, plugin 6.2.3, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: Cannot find module './util'
Require stack:
- /Users/ammarhs/Desktop/aws-iot-chat-example/api/node_modules/bluebird/js/release/promise.js
- /Users/ammarhs/Desktop/aws-iot-chat-example/api/node_modules/bluebird/js/release/bluebird.js
- /Users/ammarhs/Desktop/aws-iot-chat-example/api/node_modules/serverless-webpack/index.js
- /usr/local/lib/node_modules/serverless/lib/utils/require-with-import-fallback.js
- /usr/local/lib/node_modules/serverless/lib/classes/plugin-manager.js
- /usr/local/lib/node_modules/serverless/lib/serverless.js
- /usr/local/lib/node_modules/serverless/scripts/serverless.js
- /usr/local/lib/node_modules/serverless/bin/serverless.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1070:15)
    at Module._load (node:internal/modules/cjs/loader:923:27)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at require (node:internal/modules/helpers:121:18)
    at module.exports (/Users/ammarhs/Desktop/aws-iot-chat-example/api/node_modules/bluebird/js/release/promise.js:14:12)
    at Object.<anonymous> (/Users/ammarhs/Desktop/aws-iot-chat-example/api/node_modules/bluebird/js/release/bluebird.js:9:36)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at require (node:internal/modules/helpers:121:18)
    at Object.<anonymous> (/Users/ammarhs/Desktop/aws-iot-chat-example/api/node_modules/serverless-webpack/index.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at require (node:internal/modules/helpers:121:18)
    at module.exports (/usr/local/lib/node_modules/serverless/lib/utils/require-with-import-fallback.js:5:12)
    at PluginManager.requireServicePlugin (/usr/local/lib/node_modules/serverless/lib/classes/plugin-manager.js:171:14)
    at PluginManager.resolveServicePlugins (/usr/local/lib/node_modules/serverless/lib/classes/plugin-manager.js:198:29)
    at PluginManager.loadAllPlugins (/usr/local/lib/node_modules/serverless/lib/classes/plugin-manager.js:136:47)
    at Serverless.init (/usr/local/lib/node_modules/serverless/lib/serverless.js:146:30)
    at async /usr/local/lib/node_modules/serverless/scripts/serverless.js:616:7
```
```


### Environment information

```shell
ammarhs@88665a58d58c api % serverless --version
Framework Core: 3.32.2
Plugin: 6.2.3
SDK: 4.3.2
```
```

**Comment by medikoo** [comment]
@ammaratef45 there's some definitive issue in your setup. What probably could help is removing the installation and installing it again
