### ISSUE TITLE
dynamodb local

### ISSUE THREAD

**Issue by fjbalsamo** [serverless/serverless#12016]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When I try to install dynamodb by running `sls dynamodb install` it fails because it tries to download the dynamodb package from http://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz

> The error is in the link, that URL should be http://s3.us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz

### Service configuration (serverless.yml) content

```yaml
"N/A"
```

### Command name and used flags

sls dynamodb install

### Command output

```shell
Started downloading dynamodb-local from http://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz into ~/aws-node-express-dynamodb-api-project/.dynamodb. Process may take few minutes.
✖ Uncaught exception
Environment: linux, node 16.14.2, framework 3.14.0 (standalone), plugin 6.2.1, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: Error getting DynamoDb local latest tar.gz location undefined: 403
    at ClientRequest.<anonymous> (~/aws-node-express-dynamodb-api-project/node_modules/dynamodb-localhost/dynamodb/installer.js:29:15)
    at Object.onceWrapper (node:events:646:26)
    at ClientRequest.emit (node:events:526:28)
    at ClientRequest.emit (node:domain:475:12)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:618:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at Socket.socketOnData (node:_http_client:482:22)
    at Socket.emit (node:events:526:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

1 deprecation found: run 'serverless doctor' for more details
~/aws-node-express-dynamodb-api-project/node_modules/dynamodb-localhost/dynamodb/installer.js:55
      throw new Error("Error in downloading Dynamodb local " + err);
      ^

Error: Error in downloading Dynamodb local Error: Parse Error: User callback error
    at ClientRequest.<anonymous> (~/aws-node-express-dynamodb-api-project/node_modules/dynamodb-localhost/dynamodb/installer.js:55:13)
    at ClientRequest.emit (node:events:526:28)
    at ClientRequest.emit (node:domain:475:12)
    at Socket.socketOnData (node:_http_client:491:9)
    at Socket.emit (node:events:526:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

### Environment information

```shell
Framework Core: 3.14.0 (standalone)
Plugin: 6.2.1
SDK: 4.3.2
```

**Comment by medikoo** [comment]
@fjbalsamo please report at repository of a plugin which introduces `dynamodb` command (it's not part of the core)

**Comment by griffithsbs** [comment]
N.B. @fjbalsamo this is already reported - and some workarounds are discussed - at https://github.com/99x/serverless-dynamodb-local/issues/294

**Comment by domdomegg** [comment]
FYI: The referenced problematic package (`serverless-dynamodb-local`) doesn't appear to be maintained, with no new releases to NPM in over 2 years. The linked workarounds that require creative uses of patch-package or sed can be fragile, and are a pain to maintain on each repo.

**Solution:** You can use [serverless-dynamodb](https://www.npmjs.com/package/serverless-dynamodb), a maintained fork, instead. (Disclaimer: I am a contributor to this fork). It is a drop-in replacement for this package, and is updated to fix this bug. This is a drop-in replacement for `serverless-dynamodb-local`, so to upgrade simply:

1. Uninstall `serverless-dynamodb-local`, e.g. `npm uninstall serverless-dynamodb-local`
2. Install `serverless-dynamodb`, e.g. `npm install serverless-dynamodb`
3. Update references in your code, including your serverless config, from `serverless-dynamodb-local` to `serverless-dynamodb` (quite possible that you won't have any, as you just refer to it from your serverless config)
4. (optional) Update your serverless config custom `dynamodb` key to `serverless-dynamodb`

Of course, it's all still [open-source](https://github.com/raisenational/serverless-dynamodb) and MIT licensed. Ownership of this new package sits with a registered charity, that is committed to maintaining the package into the future and is open to contributions from the community.

There's [an explanation as to the intentions behind this fork, and how it compares to other forks in the README](https://github.com/raisenational/serverless-dynamodb#why-fork).

In any case would be open to feedback on the fork - can drop [create an issue in that repository](https://github.com/raisenational/serverless-dynamodb/issues/new) or email me (address on [profile](http://github.com/domdomegg)).
