### ISSUE TITLE
Resource Diff wrong resulting in resource deployment fail

### ISSUE THREAD

**Issue by franz-josef-kaiser** [serverless/serverless#1202]
When changing _DynamoDB_ table resources in `project/s-resources-cf.json`, the resource deployment fails:

```bash
$ sls resources deploy

Serverless: Deploying resources to stage "dev" in region "eu-central-1" via Cloudformation (~3 minutes)...  
/Users/me/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

ServerlessError: ServerlessError: An error occurred while provisioning your cloudformation: The following resource(s) failed to update: [IntercomTasksTable]. 
    at new ServerlessError (/Users/nzzkaiserf/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/lib/Error.js:17:11)
    at ResourcesDeploy.<anonymous> (/Users/nzzkaiserf/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:242:25)
    at ResourcesDeploy.tryCatcher (/Users/nzzkaiserf/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/nzzkaiserf/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/nzzkaiserf/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/nzzkaiserf/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/nzzkaiserf/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:679:18)
    at Async._drainQueue (/Users/nzzkaiserf/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/nzzkaiserf/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/nzzkaiserf/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

The current (changed) table JSON:

```json
"TasksTable" : {
	"Type"           : "AWS::DynamoDB::Table",
	"DeletionPolicy" : "Retain",
	"Properties"     : {
		"TableName"             : "${region}-${stage}-intercom-tasks",
		"AttributeDefinitions"  : [
			{
				"AttributeName"  : "id",
				"AttributeType" : "S"
			},
			{
				"AttributeName" : "created_at",
				"AttributeType" : "S"
			}
		],
		"KeySchema"             : [
			{
				"AttributeName" : "id",
				"KeyType"       : "HASH"
			},
			{
				"AttributeName" : "created_at",
				"KeyType"       : "RANGE"
			}
		],
		"ProvisionedThroughput" : {
			"ReadCapacityUnits"  : 1,
			"WriteCapacityUnits" : 1
		}
	}
}
```

As the deployment fails for no obvious reason (the change was just a tables sort key name from `started_at` to `created_at`, the `id` actually is the same), the next step shows the diff. 

```patch
sls resources diff
 {
   Resources: {
     TasksTable: {
       Properties: {
         AttributeDefinitions: [
           {
-            AttributeName: "id"
+            AttributeName: "created_at"
           }
-          {
-            AttributeName: "started_at"
-            AttributeType: "S"
-          }
+          {
+            AttributeName: "created_at"
+            AttributeType: "S"
+          }
         ]
         KeySchema: [
           ...
           {
-            AttributeName: "started_at"
+            AttributeName: "created_at"
           }
         ]
       }
     }
   }
 }
```

Deleting the table manually does not change the local behavior: It seems like serverless still assumes that the table exists.

**Update:** With Nodejs 6.2.0, the error message got more verbose, explaining why it actually fails:

````
ServerlessError: ServerlessError: Stack:arn:aws:cloudformation:eu-central-1:{int}:stack/projectname-dev-r/{hash} is in UPDATE_ROLLBACK_IN_PROGRESS state and can not be updated.
```

While this helps with the deployment problem, the `diff` problem still stays.

**Update 2:** Above error message only is shown when the `diff` does **not** fail. Else just the resource name failing is stated. I would assume that it fails as the key is wrong.

**Update 3:** While the progress of AWS internal DynamoDB clean up steps seems to progress, there's the following error message, which is just `undefined`:

```bash
# last step before undefined:
ServerlessError: ServerlessError: Stack:arn:aws:cloudformation:eu-central-1:{int}:stack/projectname-dev-r/{hash} is in UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS state and can not be updated.
# undefined progress step
ServerlessError: ServerlessError: An error occurred while provisioning your cloudformation: undefined
# progress step afterwards: 
ServerlessError: ServerlessError: An error occurred while provisioning your cloudformation: The following resource(s) failed to update: [TasksTable].
```

At this stage, _CloudFormation_ tells that the `TasksTable` still exists and that its status is `UPDATE_COMPLETE`, while in _DynamoDB_ the table does not exist. Looking at the logs in _CloudFormation_, I can see the same problem:

> Property AttributeDefinitions is inconsistent with the KeySchema of the table and the secondary indexes

Point is, that I seem to be unable to make this consistent as the `diff` is wrong.

### Workaround

For everyone currently running into the same wall: It seems the only way to currently get around this is to …

* clean the table locally completely by removing the table from the JSON
* `sls resources deploy`
* inspect the _CloudFormation_ resource log and wait until the table update has gone from `DELETE_COMPLETE` to `UPDATE_COMPLETE`
* add the table back again with the changed keys
* `sls resources deploy` … again

### Version stack

CLI: OS X default terminal
Serverless: 5.5
Nodejs (via NVM): 6.2.0, 5.9.1, 4.3.0

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.

**Comment by zahiruldu** [comment]
I have faced same problem and finally got the solution to mention only the primary and indexable key. It is preferred to define only attributes that will be used as indexed, primary keys. You can add more attributes when saving the data for this primary keys. You are not bound to define all the properties at first.
