### ISSUE TITLE
python3.11 support

### ISSUE THREAD

**Issue by dipti-coding** [serverless/serverless#12101]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

AWS just released support for the python3.11 lambda runtime, would be great if there could be support added in Serverless for the same
https://aws.amazon.com/blogs/compute/python-3-11-runtime-now-available-in-aws-lambda/

**Comment by pgrzesik** [comment]
Hey @dipti-coding 👋 

Serverless Framework in latest version is properly recognizing Python 3.11 runtime (and older versions should also support it just fine, however with a schema validation error/warning). Are you on the latest Framework version by any chance?

**Comment by dipti-coding** [comment]
Ah looks like we're not on the latest version. Currently using 3.33.0.

I posted the issue since we started seeing this warning during deploys once we upgraded to Python 3.11 runtime and saw it missing in the warning below.

```
Warning: Invalid configuration encountered
  at 'provider.runtime': must be equal to one of the allowed values [dotnet6, go1.x, java17, java11, java8, java8.al2, nodejs14.x, nodejs16.x, nodejs18.x, provided, provided.al2, python3.7, python3.8, python3.9, python3.10, ruby2.7, ruby3.2]
```
Feel free to close this issue out if it's a matter of us upgrading the serverless version on our end.

**Comment by major-mayer** [comment]
Python 3.11 runtimes seem to have some problems:
```
  File "/home/path/get_upload_url/serverless_sdk/vendor/wrapt/decorators.py", line 34, in <module>
    from inspect import ismethod, isclass, formatargspec
ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/lib/python3.11/inspect.py)
```

This seems to be related to a bug in the wrapt library: https://github.com/GrahamDumpleton/wrapt/issues/196

**Comment by petersaalbrink** [comment]
> Python 3.11 runtimes seem to have some problems:
> 
> ```
>   File "/home/path/get_upload_url/serverless_sdk/vendor/wrapt/decorators.py", line 34, in <module>
>     from inspect import ismethod, isclass, formatargspec
> ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/lib/python3.11/inspect.py)
> ```

I am also facing this error when using the Python 3.11 Lambda runtime with Serverless.

When I install the latest version of `serverless_sdk` from PyPI (https://pypi.org/project/serverless-sdk/0.5.4/), I do not face this issue; in fact, `wrapt` is not even vendored nor used by `serverless_sdk` anymore.

I suspect an old version of `serverless_sdk` is installed by one of my plugins. This is from my `serverless.yml`:
```yaml
plugins:
  - serverless-plugin-lambda-insights
  - serverless-plugin-optimize
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-plugin-warmup
```

When I search my local `node_modules`, I can find the vendored `wrapt` inside `serverless_sdk` in `node_modules/@serverless/dashboard-plugin/sdk-py`.
So, the old version of `serverless_sdk` is likely installed by `@serverless/dashboard-plugin`.

I will open an issue at https://github.com/serverless/dashboard-plugin.

**Comment by cgrundem** [comment]
@petersaalbrink how did you end up fixing things? just running `pip install serverless-sdk`?

**Comment by petersaalbrink** [comment]
Update: I don't know how to update this, unfortunately. Hoping someone else does!

Meanwhile, I am curious to know if there are people who are using AWS Lambda python3.11 + Serverless 3.34.0 successfully, and what their configuration is (plugins, Dashboard y/n, Console y/n).

**Comment by ctg3** [comment]
@petersaalbrink - same issue here with Python 3.11, no issues with only changing to Python 3.10.

Error:
"[ERROR] Runtime.ImportModuleError: Unable to import module 's_file_name': cannot import name 'formatargspec' from 'inspect' (/var/lang/lib/python3.11/inspect.py)"

Configuration:
"serverless": "^3.34.0",
"@serverless/safeguards-plugin": "^1.2.1",
"serverless-plugin-aws-alerts": "^1.7.5",
"serverless-plugin-split-stacks": "^1.13.0",
"serverless-python-requirements": "^6.0.0"

Our only overlapping plugin is serverless-python-requirements.

**Comment by vinhbuifpt** [comment]
Hi, I use version 3.34.0 and get this error when I try to upgrade to Python 3.11, it's fine with Python 3.9

`Environment: linux, node 12.18.1, framework 3.34.0, plugin 6.4.0, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
python3.11 not found! Install it according to the poetry docs.
script returned exit code 1`

Can you guys know why it happens? This is my package.json
`  "serverless-domain-manager": "3.3.1",
    "serverless-plugin-split-stacks": "1.11.3",
    "serverless-plugin-warmup": "4.9.0",
    "serverless-pseudo-parameters": "1.6.0",
    "serverless-python-requirements": "^6.0.0",
    "utf-8-validate": "^5.0.2"`

**Comment by ggmartins** [comment]
I'm having this error below:
```
INIT_START Runtime Version: python:3.11.v16	Runtime Version ARN: arn:aws:lambda:us-east-2::runtime:XXXX
START
[ERROR] Runtime.ImportModuleError: Unable to import module 'src/http/save_data/handler': cannot import name 'Sequence' from 'collections' (/var/lang/lib/python3.11/collections/__init__.py)
Traceback (most recent call last):
```
any tips other than downgrading? thanks

**Comment by czubocha** [comment]
Closing this as `python3.11` runtime is supported in Serverless Framework starting [v3.34.0](https://github.com/serverless/serverless/releases/tag/v3.34.0)
