### ISSUE TITLE
s-templates.json parsing fails

### ISSUE THREAD

**Issue by hakenmt** [serverless/serverless#1215]
When running any serverless command after creating an s-templates.json file at the root of the project (or in any sub folder), I receive a parsing error. I'm running version 0.5.5 on Windows 10 1511 with node.js version 5.6.0. The example json I'm using is:
```
{
  "test" :  "testing"
}
```
The error I receive is:
```
C:\Workspaces\AWS\SlsProject\RootFolder>sls dash deploy
C:\Users\michael.haken\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:61
        fn = function () { throw arg; };
                           ^

ServerlessError: Could not parse JSON in file: C:\Workspaces\AWS\SlsProject\RootFolder\s-templates.json
    at new ServerlessError (C:\Users\michael.haken\AppData\Roaming\npm\node_modules\serverless\lib\Error.js:17:11)
    at Object.module.exports.readFileSync (C:\Users\michael.haken\AppData\Roaming\npm\node_modules\serverless\lib\utils\index.js:196:15)
    at C:\Users\michael.haken\AppData\Roaming\npm\node_modules\serverless\lib\Serializer.js:448:42
From previous event:
    at Templates.deserializeTemplates (C:\Users\michael.haken\AppData\Roaming\npm\node_modules\serverless\lib\Serializer.js:438:27)
    at Templates.deserialize (C:\Users\michael.haken\AppData\Roaming\npm\node_modules\serverless\lib\Serializer.js:27:57)
    at Templates.load (C:\Users\michael.haken\AppData\Roaming\npm\node_modules\serverless\lib\Templates.js:24:19)
    at C:\Users\michael.haken\AppData\Roaming\npm\node_modules\serverless\lib\Serializer.js:54:31
From previous event:
    at C:\Users\michael.haken\AppData\Roaming\npm\node_modules\serverless\lib\Serializer.js:48:28
From previous event:
    at Project.deserializeProject (C:\Users\michael.haken\AppData\Roaming\npm\node_modules\serverless\lib\Serializer.js:46:10)
    at Project.deserialize (C:\Users\michael.haken\AppData\Roaming\npm\node_modules\serverless\lib\Serializer.js:27:57)
    at Project.load (C:\Users\michael.haken\AppData\Roaming\npm\node_modules\serverless\lib\Project.js:36:19)
    at C:\Users\michael.haken\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:87:35
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Serverless.init (C:\Users\michael.haken\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:79:10)
    at Object.<anonymous> (C:\Users\michael.haken\AppData\Roaming\npm\node_modules\serverless\bin\serverless:17:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3
```

This issue is preventing running any kind of deployment or creating new functions, etc. I get the error both with complex json and the simple test json object provided. If I remove the s-templates.json from the root and all sub folders, I (obviously) don't get the parsing error when running sls commands.

**Comment by hakenmt** [comment]
So I just figured out the issue. When the json files are created/edited in Visual Studio, they are saved with a CR LF line ending. In order to be properly parsed, the template files need to be saved with UTF-8 no signature or ASCII with Unix style line endings (LF) in order to be successfully parsed. I didn't see this issue in any other json file, like the s-project or s-function files. I would recommend the parser accepting both style of line endings.

**Comment by mariaugust2015** [comment]
Can you please help me resolve this issue, because I didn't even create this account, I just put' me email and it stated that I did have an account.  I have been hacked into all my emails, even the main one with all of my home's private information, I will look into that email as well.  I would gladly appreciate anything that you can do to help me with all my emails issues.  Thank you so very much.  God bless

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
