### ISSUE TITLE
Error while installing serverless-pseudo-parameter

### ISSUE THREAD

**Issue by psycheCoder** [serverless/serverless#12205]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

<html>
<body>

[Container] 2023/10/05 12:35:51 Running command serverless plugin install -n serverless-pseudo-parameters@3.3.0
--
64 | Running "serverless" from node_modules
65 | (node:290) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
66 |  
67 | Please migrate your code to use AWS SDK for JavaScript (v3).
68 | For more information, check the migration guide at https://a.co/7PzMCcy
69 | (Use `node --trace-warnings ...` to show where the warning was created)
70 | × npm ERR! code ETARGET
71 | npm ERR! notarget No matching version found for serverless-pseudo-parameters@3.3.0.
72 | npm ERR! notarget In most cases you or one of your dependencies are requesting
73 | npm ERR! notarget a package version that doesn't exist.
74 |  
75 | npm ERR! A complete log of this run can be found in:
76 | npm ERR!     /root/.npm/_logs/2023-10-05T12_35_53_271Z-debug-0.log
77 |  
78 | Environment: linux, node 16.20.1, framework 3.3.0 (local) 3.3.0v (global), plugin 6.4.0, SDK 4.4.0
79 | Docs:        docs.serverless.com
80 | Support:     forum.serverless.com
81 | Bugs:        github.com/serverless/serverless/issues
82 |  
83 | Error:
84 | Error: `npm install --save-dev serverless-pseudo-parameters@3.3.0` Exited with code 1
85 | at ChildProcess.<anonymous> (/codebuild/output/src4047125229/src/node_modules/child-process-ext/spawn.js:38:8)
86 | at ChildProcess.emit (node:events:513:28)
87 | at ChildProcess.emit (node:domain:489:12)
88 | at maybeClose (node:internal/child_process:1100:16)
89 | at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)

</body>
</html>

### Service configuration (serverless.yml) content

```yaml
[Container] 2023/10/05 12:35:51 Running command serverless plugin install -n serverless-pseudo-parameters@3.3.0
Running "serverless" from node_modules
(node:290) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
× npm ERR! code ETARGET
  npm ERR! notarget No matching version found for serverless-pseudo-parameters@3.3.0.
  npm ERR! notarget In most cases you or one of your dependencies are requesting
  npm ERR! notarget a package version that doesn't exist.
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /root/.npm/_logs/2023-10-05T12_35_53_271Z-debug-0.log
  
Environment: linux, node 16.20.1, framework 3.3.0 (local) 3.3.0v (global), plugin 6.4.0, SDK 4.4.0
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: `npm install --save-dev serverless-pseudo-parameters@3.3.0` Exited with code 1
    at ChildProcess.<anonymous> (/codebuild/output/src4047125229/src/node_modules/child-process-ext/spawn.js:38:8)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

### Command name and used flags

npm install --save-dev serverless-pseudo-parameters@3.3.0

### Command output

```shell
[Container] 2023/10/05 12:35:51 Running command serverless plugin install -n serverless-pseudo-parameters@3.3.0
Running "serverless" from node_modules
(node:290) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
× npm ERR! code ETARGET
  npm ERR! notarget No matching version found for serverless-pseudo-parameters@3.3.0.
  npm ERR! notarget In most cases you or one of your dependencies are requesting
  npm ERR! notarget a package version that doesn't exist.
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /root/.npm/_logs/2023-10-05T12_35_53_271Z-debug-0.log
  
Environment: linux, node 16.20.1, framework 3.3.0 (local) 3.3.0v (global), plugin 6.4.0, SDK 4.4.0
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: `npm install --save-dev serverless-pseudo-parameters@3.3.0` Exited with code 1
    at ChildProcess.<anonymous> (/codebuild/output/src4047125229/src/node_modules/child-process-ext/spawn.js:38:8)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

### Environment information

```shell
3.3.0
```

**Comment by JaredAAT** [comment]
The last version of serverless-pseudo-parameters was 2.6.1 so 3.3.0 does not exist...  it's also been deprecated and you should be using ${aws:region}:${aws:accountId} naturally in serverless 3

https://www.npmjs.com/package/serverless-pseudo-parameters

**Comment by rkumar2-som** [comment]
<html>
<body>


Error:
--
106 | Cannot resolve serverless.yml: Variables resolution errored with:
107 | - Cannot resolve variable at "provider.stackName": Value not found at "opt" source,
108 | - Cannot resolve variable at "provider.apiName": Value not found at "opt" source,
109 | - Cannot resolve variable at "provider.vpcEndpointIds.0": Value not found at "opt" source,
110 | - Cannot resolve variable at "provider.apiGateway.apiKeys.0": Value not found at "opt" source,
111 | - Cannot resolve variable at "custom.warmup.concurrency": Value not found at "opt" source,
112 | - Cannot resolve variable at "custom.warmup.schedule": Value not found at "opt" source,
113 | - Cannot resolve variable at "custom.warmup.name": Value not found at "opt" source,
114 | - Cannot resolve variable at "functions.b2bSoEventFunction.name": Value not found at "opt" source,
115 | - Cannot resolve variable at "functions.b2bSoEventFunction.vpc.securityGroupIds.0": Value not found at "opt" source,
116 | - Cannot resolve variable at "functions.b2bSoEventFunction.vpc.subnetIds.0": Value not found at "opt" source,
117 | - Cannot resolve variable at "functions.b2bSoEventFunction.vpc.subnetIds.1": Value not found at "opt" source


</body>
</html>
