### ISSUE TITLE
Unable to login via CLI 

### ISSUE THREAD

**Issue by nappernick** [serverless/serverless#12302]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Every time I try to login to through the CLI, I am authed in the browser, but the CLI hangs. When I open my .serverlessrc, it's just this:
```
{
  "userId": null,
  "frameworkId": "76647130-9df0-11ee-b258-116157d298be",
  "trackingDisabled": false,
  "enterpriseDisabled": false,
  "meta": {
    "created_at": 1702936660,
    "updated_at": 1702936660
  }
}
```

I have tried uninstalling & reinstalling, deleting the .serverlessrc, creating a brand new account, and yet, nothing works.
@avasilenko92 @nappernick

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

serverless login --verbose

### Command output

```shell
Hangs indefinitely.
```

### Environment information

```shell
Framework Core: 3.38.0
Plugin: 7.2.0
SDK: 4.5.1
```

**Comment by nappernick** [comment]
Now using node v18.19.0 (npm v10.2.3)

**Comment by nappernick** [comment]
Bit more context:
``` sls login
Logging into the Serverless Framework via the browser
If your browser does not open automatically, please open this URL:
https://app.serverless.com?client=cli&transactionId=pfvUPq3m96Ol958EDjbRy
```
[hangs....]

```
sls doctor
2 deprecations triggered in the last command:

Support for "package.include" and "package.exclude" will be removed in the next major release. Please use "package.patterns" instead
More info: https://serverless.com/framework/docs/deprecations/#PACKAGE_PATTERNS
Starting with version 4.0.0, following property will be replaced:
  "provider.iamRoleStatements" -> "provider.iam.role.statements"
More info: https://serverless.com/framework/docs/deprecations/#PROVIDER_IAM_SETTINGS_V3
```

```
serverless info --verbose
Environment: darwin, node 20.10.0, framework 3.38.0, plugin 7.2.0, SDK 4.5.1
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
You are not currently logged in. To log in, use: $ serverless login

2 deprecations found: run 'serverless doctor' for more details
```

**Comment by nappernick** [comment]
The console on the browser says:
```
js.stripe.com/v3/controller-8324c09573d1c228d18b64f31ad6df01.html#apiKey=pk_live_fUrnuMKodQM6UMXPZnFcNQ3N002icn5R5D&stripeJsId=d531ea73-6576-43e4-8865-ee1885d2a813&stripeJsLoadTime=1703015814586&manualBrowserDeprecationRollout=false&referrer=https%3A%2F%2Fapp.serverless.com%2F%3Fclient%3Dcli%26transactionId%3DcK4pLrdZ_2dgRCNoncBG4&controllerId=__privateStripeController0571:1 The source list for the Content Security Policy directive 'style-src' contains an invalid source: '://:'. It will be ignored.
js.stripe.com/v3/controller-8324c09573d1c228d18b64f31ad6df01.html#apiKey=pk_live_fUrnuMKodQM6UMXPZnFcNQ3N002icn5R5D&stripeJsId=d531ea73-6576-43e4-8865-ee1885d2a813&stripeJsLoadTime=1703015814586&manualBrowserDeprecationRollout=false&referrer=https%3A%2F%2Fapp.serverless.com%2F%3Fclient%3Dcli%26transactionId%3DcK4pLrdZ_2dgRCNoncBG4&controllerId=__privateStripeController0571:1 The source list for the Content Security Policy directive 'style-src' contains an invalid source: '://:'. It will be ignored.
api.serverless.com/login/complete:1 
        
        
       Failed to load resource: the server responded with a status of 500 (Internal Server Error)
m.stripe.network/inner.html#url=https%3A%2F%2Fapp.serverless.com%2F%3Fclient%3Dcli%26transactionId%3DcK4pLrdZ_2dgRCNoncBG4&title=Serverless&referrer=&muid=ea220a2d-247b-42f3-8f09-c0c182b4edc121f5c4&sid=b549f080-d18d-40a2-8168-87b0baf69458c79206&version=6&preview=false:1 The source list for the Content Security Policy directive 'style-src' contains an invalid source: '://:'. It will be ignored.
```
[app.serverless.com-1703016048959.log](https://github.com/serverless/serverless/files/13719818/app.serverless.com-1703016048959.log)

**Comment by nappernick** [comment]
I've been able to troubleshoot logging in, but I'm still getting this error:
```
Typescript compiled.

✖ Stack api-gateway-dev failed to deploy (86s)
Environment: darwin, node 16.16.0, framework 3.38.0 (local) 3.38.0v (global), plugin 7.2.0, SDK 4.5.1
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: Tenant not found. - Please contact support and provide this identifier to reference this issue - YZQPZBX5PNCZ
    at Object.request (/Users/nappernick/node_modules/@serverless/platform-client/src/utils.js:64:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/Users/nappernick/node_modules/@serverless/dashboard-plugin/lib/app-uids.js:7:15)
    at async ServerlessEnterprisePlugin.<anonymous> (/Users/nappernick/node_modules/@serverless/dashboard-plugin/lib/plugin.js:251:13)
    at async PluginManager.runHooks (/Users/nappernick/node_modules/serverless/lib/classes/plugin-manager.js:530:9)
    at async PluginManager.invoke (/Users/nappernick/node_modules/serverless/lib/classes/plugin-manager.js:563:9)
    at async PluginManager.spawn (/Users/nappernick/node_modules/serverless/lib/classes/plugin-manager.js:585:5)
    at async before:deploy:deploy (/Users/nappernick/node_modules/serverless/lib/plugins/deploy.js:48:11)
    at async PluginManager.runHooks (/Users/nappernick/node_modules/serverless/lib/classes/plugin-manager.js:530:9)
    at async PluginManager.invoke (/Users/nappernick/node_modules/serverless/lib/classes/plugin-manager.js:563:9)
    at async PluginManager.run (/Users/nappernick/node_modules/serverless/lib/classes/plugin-manager.js:604:7)
    at async Serverless.run (/Users/nappernick/node_modules/serverless/lib/serverless.js:179:5)
    at async /Users/nappernick/node_modules/serverless/scripts/serverless.js:819:9
```

**Comment by sonmez3** [comment]
Is there any update ?
