### ISSUE TITLE
Resolving an unknown error in a Github Action running `serverless deploy`

### ISSUE THREAD

**Issue by ajay-bhargava** [serverless/serverless#12347]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

If you are getting this error while running Serverless as part of a Github Action: 

```Error:
Error: Application not found. - Please contact support and provide this identifier to reference this issue - 108X9CVQDJW8
    at Object.request (/home/runner/work/mnist-sagemaker-ci-cd/mnist-sagemaker-ci-cd/src/serverless/node_modules/@serverless/platform-client/src/utils.js:64:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async module.exports (/home/runner/work/mnist-sagemaker-ci-cd/mnist-sagemaker-ci-cd/src/serverless/node_modules/@serverless/dashboard-plugin/lib/app-uids.js:7:15)
    at async ServerlessEnterprisePlugin.<anonymous> (/home/runner/work/mnist-sagemaker-ci-cd/mnist-sagemaker-ci-cd/src/serverless/node_modules/@serverless/dashboard-plugin/lib/plugin.js:251:13)
    at async PluginManager.runHooks (/home/runner/work/mnist-sagemaker-ci-cd/mnist-sagemaker-ci-cd/src/serverless/node_modules/serverless/lib/classes/plugin-manager.js:[53](https://github.com/ajay-bhargava/mnist-sagemaker-ci-cd/actions/runs/7790321149/job/21243924402#step:5:54)0:9)
    at async PluginManager.invoke (/home/runner/work/mnist-sagemaker-ci-cd/mnist-sagemaker-ci-cd/src/serverless/node_modules/serverless/lib/classes/plugin-manager.js:[56](https://github.com/ajay-bhargava/mnist-sagemaker-ci-cd/actions/runs/7790321149/job/21243924402#step:5:57)3:9)
    at async PluginManager.spawn (/home/runner/work/mnist-sagemaker-ci-cd/mnist-sagemaker-ci-cd/src/serverless/node_modules/serverless/lib/classes/plugin-manager.js:[58](https://github.com/ajay-bhargava/mnist-sagemaker-ci-cd/actions/runs/7790321149/job/21243924402#step:5:59)5:5)
    at async before:deploy:deploy (/home/runner/work/mnist-sagemaker-ci-cd/mnist-sagemaker-ci-cd/src/serverless/node_modules/serverless/lib/plugins/deploy.js:48:11)
    at async PluginManager.runHooks (/home/runner/work/mnist-sagemaker-ci-cd/mnist-sagemaker-ci-cd/src/serverless/node_modules/serverless/lib/classes/plugin-manager.js:530:9)
    at async PluginManager.invoke (/home/runner/work/mnist-sagemaker-ci-cd/mnist-sagemaker-ci-cd/src/serverless/node_modules/serverless/lib/classes/plugin-manager.js:563:9)
    at async PluginManager.run (/home/runner/work/mnist-sagemaker-ci-cd/mnist-sagemaker-ci-cd/src/serverless/node_modules/serverless/lib/classes/plugin-manager.js:[60](https://github.com/ajay-bhargava/mnist-sagemaker-ci-cd/actions/runs/7790321149/job/21243924402#step:5:61)4:7)
    at async Serverless.run (/home/runner/work/mnist-sagemaker-ci-cd/mnist-sagemaker-ci-cd/src/serverless/node_modules/serverless/lib/serverless.js:179:5)
    at async /home/runner/work/mnist-sagemaker-ci-cd/mnist-sagemaker-ci-cd/src/serverless/node_modules/serverless/scripts/serverless.js:819:9
```

Remove the `app` and `org` variables from your `serverless.yml` file. This will avoid installing the dashboard utilities and prevent this error from being thrown. 

Example (before removal): 

```yml
service: mnist
frameworkVersion: "3"
org: xyz
app: mnist
```

after
```yml
service: mnist
frameworkVersion: "3"
```

### Service configuration (serverless.yml) content

```yaml
service: mnist
frameworkVersion: "3"
org: xyz
app: mnist
```

### Command name and used flags

serverless deploy --verbose

### Command output

```shell
:
Error: Application not found. - Please contact support and provide this identifier to reference this issue - 108X9CVQDJW8
    at Object.request (/home/runner/work/mnist-sagemaker-ci-cd/mnist-sagemaker-ci-cd/src/serverless/node_modules/@serverless/platform-client/src/utils.js:64:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async module.exports (/home/runner/work/mnist-sagemaker-ci-cd/mnist-sagemaker-ci-cd/src/serverless/node_modules/@serverless/dashboard-plugin/lib/app-uids.js:7:15)
    at async ServerlessEnterprisePlugin.<anonymous> (/home/runner/work/mnist-sagemaker-ci-cd/mnist-sagemaker-ci-cd/src/serverless/node_modules/@serverless/dashboard-plugin/lib/plugin.js:251:13)
    at async PluginManager.runHooks (/home/runner/work/mnist-sagemaker-ci-cd/mnist-sagemaker-ci-cd/src/serverless/node_modules/serverless/lib/classes/plugin-manager.js:[53](https://github.com/ajay-bhargava/mnist-sagemaker-ci-cd/actions/runs/7790321149/job/21243924402#step:5:54)0:9)
    at async PluginManager.invoke (/home/runner/work/mnist-sagemaker-ci-cd/mnist-sagemaker-ci-cd/src/serverless/node_modules/serverless/lib/classes/plugin-manager.js:[56](https://github.com/ajay-bhargava/mnist-sagemaker-ci-cd/actions/runs/7790321149/job/21243924402#step:5:57)3:9)
    at async PluginManager.spawn (/home/runner/work/mnist-sagemaker-ci-cd/mnist-sagemaker-ci-cd/src/serverless/node_modules/serverless/lib/classes/plugin-manager.js:[58](https://github.com/ajay-bhargava/mnist-sagemaker-ci-cd/actions/runs/7790321149/job/21243924402#step:5:59)5:5)
    at async before:deploy:deploy (/home/runner/work/mnist-sagemaker-ci-cd/mnist-sagemaker-ci-cd/src/serverless/node_modules/serverless/lib/plugins/deploy.js:48:11)
    at async PluginManager.runHooks (/home/runner/work/mnist-sagemaker-ci-cd/mnist-sagemaker-ci-cd/src/serverless/node_modules/serverless/lib/classes/plugin-manager.js:530:9)
    at async PluginManager.invoke (/home/runner/work/mnist-sagemaker-ci-cd/mnist-sagemaker-ci-cd/src/serverless/node_modules/serverless/lib/classes/plugin-manager.js:563:9)
    at async PluginManager.run (/home/runner/work/mnist-sagemaker-ci-cd/mnist-sagemaker-ci-cd/src/serverless/node_modules/serverless/lib/classes/plugin-manager.js:[60](https://github.com/ajay-bhargava/mnist-sagemaker-ci-cd/actions/runs/7790321149/job/21243924402#step:5:61)4:7)
    at async Serverless.run (/home/runner/work/mnist-sagemaker-ci-cd/mnist-sagemaker-ci-cd/src/serverless/node_modules/serverless/lib/serverless.js:179:5)
    at async /home/runner/work/mnist-sagemaker-ci-cd/mnist-sagemaker-ci-cd/src/serverless/node_modules/serverless/scripts/serverless.js:819:9
```

### Environment information

```shell
Environment: linux, node 18.19.0, framework 3.38.0 (local) 3.38.0v (global), plugin 7.2.0, SDK 4.5.1
```

**Comment by ajay-bhargava** [comment]
Even though this error is cryptic, I found the reason behind this error. If you do not specify the app name in the serverless dashboard by "+Create App" prior to running the `serverless.yml` file via `sls deploy` then you will be presented with this error. This would _also_ be true in CI/CD.
