### ISSUE TITLE
Serverless transpiling before provider environment variables initialization

### ISSUE THREAD

**Issue by Vrrl** [serverless/serverless#12437]
### Issue description

While using Inversify, i'm not able to run `sls package` because my injectable class depends of an environment variable in the constructor wich is not initialized yet by serverless. 

### Context

Framework Core: 3.38.0 (local)
Plugin: 7.2.3
SDK: 4.5.1
Node: v20.11.0

```json
"dependencies": {
    "@aws-sdk/client-cognito-identity-provider": "^3.427.0",
    "@aws-sdk/client-dynamodb": "^3.415.0",
    "@aws-sdk/client-s3": "^3.454.0",
    "@aws-sdk/client-sns": "^3.535.0",
    "@aws-sdk/util-dynamodb": "^3.415.0",
    "@middy/core": "^4.7",
    "@middy/http-header-normalizer": "^4.7",
    "@middy/http-json-body-parser": "^4.7",
    "@middy/http-router": "^4.7",
    "@middy/validator": "^4.7",
    "date-fns": "^3.3.1",
    "inversify": "^6.0.2",
    "inversify-binding-decorators": "^4.0.0",
    "reflect-metadata": "^0.2.1",
    "serverless-http": "^3.2.0",
    "uuid": "^9.0.1",
    "zod": "^3.22.2"
  },
  "devDependencies": {
    "@aws-sdk/types": "^3.415.0",
    "@serverless/compose": "^1.3.0",
    "@serverless/typescript": "^3.0.0",
    "@types/aws-lambda": "^8.10.71",
    "@types/js-yaml": "^4.0.6",
    "@types/node": "^20.11.24",
    "@types/uuid": "^9.0.5",
    "@typescript-eslint/eslint-plugin": "^7.1.0",
    "@typescript-eslint/parser": "^7.1.0",
    "@vitest/coverage-v8": "^1.5.0",
    "esbuild": "^0.20.1",
    "eslint": "^8.49.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-config-standard-with-typescript": "^43.0.1",
    "eslint-plugin-prettier": "^5.0.0",
    "json-schema-to-ts": "^3.0.0",
    "prettier": "^3.0.3",
    "serverless": "^3.0.0",
    "serverless-esbuild": "^1.48.0",
    "serverless-offline": "^13.3.3",
    "ts-node": "^10.4.0",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.3.3",
    "vitest": "^1.3.1",
    "vitest-mock-extended": "^1.2.1"
  },
```

```ts
// serverless.ts
import type { AWS } from '@serverless/typescript';
import functions from '@src/modules/order-management/infra/serverless/functions';
import iam from '@src/modules/order-management/infra/serverless/iam';
import resources from '@src/modules/order-management/infra/serverless/resources';
import * as environment from '@src/modules/order-management/infra/serverless/provider-environment';

const serverlessConfiguration: AWS = {
  service: 'OrderManagementAPI',
  frameworkVersion: '3',
  plugins: ['serverless-esbuild', 'serverless-offline'],
  provider: {
    name: 'aws',
    runtime: 'nodejs20.x',
    deploymentMethod: 'direct',
    versionFunctions: false,
    timeout: 30,
    apiGateway: {
      minimumCompressionSize: 1024,
      shouldStartNameWithService: true,
    },
    httpApi: {
      cors: true,
    },
    environment,
    iam,
  },
  functions,
  resources,
  package: { individually: true },
  custom: {
    yarn: {
      enable: true,
    },
    esbuild: {
      bundle: true,
      minify: false,
      sourcemap: false,
      exclude: ['aws-sdk'],
      target: 'node16',
      define: { 'require.resolve': undefined },
      platform: 'node',
      concurrency: 10,
    },
    'serverless-offline': { noPrependStageInUrl: true },
  },
};

module.exports = serverlessConfiguration;

```

```ts
// provider-environment.ts
export const STAGE = 'production';
export const NODE_ENV = STAGE;
export const NODE_OPTIONS = '--enable-source-maps --stack-trace-limit=1000';
export const AWS_NODEJS_CONNECTION_REUSE_ENABLED = '1';
export const DYNAMO_ORDERS_TABLE = `orders-${STAGE}`;
export const COGNITO_USER_POOL_ID = `us-east-1_sFRX8****`;
export const COGNITO_CLIENT_ID = `4gf66pspl04sc*****`;
export const SNS_ORDER_TOPIC = `test`;
```

```ts
// injector.ts
// ... imports
const container = new Container();
// ... others binds
container.bind<IOrderCommandRepository>(TYPES.IOrderCommandRepository).to(OrderCommandRepository);

export default container;
```

```ts
// order-command-repository.ts
import TYPES from '@src/core/types';
import { DynamoDBClient, PutItemCommand } from '@aws-sdk/client-dynamodb';
import { marshall } from '@aws-sdk/util-dynamodb';
import { Order } from '../../../domain/order';
import { IOrderCommandRepository } from '../order-command-repository';
import { throwIfUndefinedOrEmptyString } from '@src/core/infra/helpers/validation';
import { inject, injectable } from 'inversify/lib/inversify';

@injectable()
export class OrderCommandRepository implements IOrderCommandRepository {
  DYNAMO_ORDERS_TABLE: string;

  constructor(@inject(TYPES.DynamoDBClient) private dynamoClient: DynamoDBClient) {
   // this line causes the error. It works fine if i remove the validation and the env variable is initialized during execution time (offline & deployed)
    this.DYNAMO_ORDERS_TABLE = throwIfUndefinedOrEmptyString(
      process.env.DYNAMO_ORDERS_TABLE,
      'Env Parameter DYNAMO_ORDERS_TABLE is required',
    );
  }

  async save(order: Order): Promise<void> {
    // do some irrelevant stuff
  }
}
```

command executed: `sls package`

Received error:
```cli
Cannot load "serverless.ts": Initialization error: Error: Env Parameter DYNAMO_ORDERS_TABLE is required                                                                                     
order-management ›     at throwIfUndefinedOrEmptyString (E:\projects\stocks API\src\core\infra\helpers\validation.ts:3:11)
order-management ›     at new OrderCommandRepository (E:\projects\stocks API\src\modules\order-management\infra\db\dynamo\order-command-repository.ts:14:61)
order-management ›     at createInstanceWithInjections (E:\projects\stocks API\node_modules\inversify\lib\resolution\instantiation.js:119:20)
order-management ›     at _createInstance (E:\projects\stocks API\node_modules\inversify\lib\resolution\instantiation.js:109:22)
order-management ›     at resolveInstance (E:\projects\stocks API\node_modules\inversify\lib\resolution\instantiation.js:204:18)
order-management ›     at _getResolvedFromBinding (E:\projects\stocks API\node_modules\inversify\lib\resolution\resolver.js:109:58)
order-management ›     at E:\projects\stocks API\node_modules\inversify\lib\resolution\resolver.js:127:22
order-management ›     at _resolveInScope (E:\projects\stocks API\node_modules\inversify\lib\resolution\resolver.js:121:14)
order-management ›     at _resolveBinding (E:\projects\stocks API\node_modules\inversify\lib\resolution\resolver.js:126:12)
order-management ›     at E:\projects\stocks API\node_modules\inversify\lib\resolution\resolver.js:88:20
order-management ›     at childRequests.reduce.constructorInjections (E:\projects\stocks API\node_modules\inversify\lib\resolution\instantiation.js:85:25)
order-management ›     at Array.reduce (<anonymous>)
order-management ›     at _resolveRequests (E:\projects\stocks API\node_modules\inversify\lib\resolution\instantiation.js:84:26)
order-management ›     at _createInstance (E:\projects\stocks API\node_modules\inversify\lib\resolution\instantiation.js:103:24)
order-management ›     at resolveInstance (E:\projects\stocks API\node_modules\inversify\lib\resolution\instantiation.js:204:18)
order-management ›     at _getResolvedFromBinding (E:\projects\stocks API\node_modules\inversify\lib\resolution\resolver.js:109:58)
order-management ›     at E:\projects\stocks API\node_modules\inversify\lib\resolution\resolver.js:127:22
order-management ›     at _resolveInScope (E:\projects\stocks API\node_modules\inversify\lib\resolution\resolver.js:121:14)
order-management ›     at _resolveBinding (E:\projects\stocks API\node_modules\inversify\lib\resolution\resolver.js:126:12)
order-management ›     at E:\projects\stocks API\node_modules\inversify\lib\resolution\resolver.js:88:20
order-management ›     at childRequests.reduce.constructorInjections (E:\projects\stocks API\node_modules\inversify\lib\resolution\instantiation.js:85:25)
order-management ›     at Array.reduce (<anonymous>)
order-management ›     at _resolveRequests (E:\projects\stocks API\node_modules\inversify\lib\resolution\instantiation.js:84:26)
order-management ›     at _createInstance (E:\projects\stocks API\node_modules\inversify\lib\resolution\instantiation.js:103:24)
order-management ›     at resolveInstance (E:\projects\stocks API\node_modules\inversify\lib\resolution\instantiation.js:204:18)
order-management ›     at _getResolvedFromBinding (E:\projects\stocks API\node_modules\inversify\lib\resolution\resolver.js:109:58)
order-management ›     at E:\projects\stocks API\node_modules\inversify\lib\resolution\resolver.js:127:22
order-management ›     at _resolveInScope (E:\projects\stocks API\node_modules\inversify\lib\resolution\resolver.js:121:14)
order-management ›     at _resolveBinding (E:\projects\stocks API\node_modules\inversify\lib\resolution\resolver.js:126:12)
order-management ›     at E:\projects\stocks API\node_modules\inversify\lib\resolution\resolver.js:88:20
order-management ›     at resolve (E:\projects\stocks API\node_modules\inversify\lib\resolution\resolver.js:225:12)
order-management ›     at E:\projects\stocks API\node_modules\inversify\lib\container\container.js:628:49
order-management ›     at Container._get (E:\projects\stocks API\node_modules\inversify\lib\container\container.js:596:38)
order-management ›     at Container._getButThrowIfAsync (E:\projects\stocks API\node_modules\inversify\lib\container\container.js:599:27)
order-management ›     at Container.get (E:\projects\stocks API\node_modules\inversify\lib\container\container.js:374:21)
order-management ›     at Container.resolve (E:\projects\stocks API\node_modules\inversify\lib\container\container.js:431:29)
order-management ›     at Object.<anonymous> (E:\projects\stocks API\src\modules\order-management\infra\http\routes.ts:7:30)
order-management ›     at Module._compile (node:internal/modules/cjs/loader:1376:14)
order-management ›     at Module.m._compile (E:\projects\stocks API\node_modules\ts-node\src\index.ts:1618:23)
order-management ›     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
order-management ›     at Object.require.extensions.<computed> [as .ts] (E:\projects\stocks API\node_modules\ts-node\src\index.ts:1621:12)
order-management ›     at Module.load (node:internal/modules/cjs/loader:1207:32)
order-management ›     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
order-management ›     at Module.require (node:internal/modules/cjs/loader:1235:19)
order-management ›     at require (node:internal/modules/helpers:176:18)
order-management ›     at Object.<anonymous> (E:\projects\stocks API\src\modules\order-management\infra\serverless\functions.ts:3:1)
order-management ›     at Module._compile (node:internal/modules/cjs/loader:1376:14)
order-management ›     at Module.m._compile (E:\projects\stocks API\node_modules\ts-node\src\index.ts:1618:23)
order-management ›     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
order-management ›     at Object.require.extensions.<computed> [as .ts] (E:\projects\stocks API\node_modules\ts-node\src\index.ts:1621:12)
order-management ›     at Module.load (node:internal/modules/cjs/loader:1207:32)
order-management ›     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
order-management ›     at Module.require (node:internal/modules/cjs/loader:1235:19)
order-management ›     at require (node:internal/modules/helpers:176:18)
order-management ›     at Object.<anonymous> (E:\projects\stocks API\src\modules\order-management\serverless.ts:2:1)
order-management ›     at Module._compile (node:internal/modules/cjs/loader:1376:14)
order-management ›     at Module.m._compile (E:\projects\stocks API\node_modules\ts-node\src\index.ts:1618:23)
order-management ›     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
order-management ›     at Object.require.extensions.<computed> [as .ts] (E:\projects\stocks API\node_modules\ts-node\src\index.ts:1621:12)
order-management ›     at Module.load (node:internal/modules/cjs/loader:1207:32)
order-management ›     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
order-management ›     at Module.require (node:internal/modules/cjs/loader:1235:19)
order-management ›     at require (node:internal/modules/helpers:176:18)
order-management ›     at E:\projects\stocks API\node_modules\serverless\lib\configuration\read.js:149:18
order-management ›     at parseConfigurationFile (E:\projects\stocks API\node_modules\serverless\lib\configuration\read.js:158:9)
order-management ›     at async module.exports (E:\projects\stocks API\node_modules\serverless\lib\configuration\read.js:207:23)
order-management ›     at async E:\projects\stocks API\node_modules\serverless\scripts\serverless.js:232:22
order-management ›     at async E:\projects\stocks API\node_modules\serverless\scripts\serverless.js:230:11
```

**Comment by Vrrl** [comment]
This is not related with serverless as the bug happens because i've to dynamic build all the functions before the execution. Solved loading env variables apart.
