### ISSUE TITLE
V4: Default literal value for a parameter resolver is parsed incorrectly if it contains :

### ISSUE THREAD

**Issue by garethmcc** [serverless/serverless#12525]
### Issue description

When setting a parameter with ${param} syntax, you can set a default string literal to be used if the parameter does not resolve correctly. However, if that string literal contains a : within it, the resolver errors. For example, consider a parameter configured as:

`MONGO_URI: ${param:MONGO_URI, 'mongodb+srv//user:asdadasda@mongodb.net/dbname'}`

When running `serverless print`, an error is printed as follows:

```
✖ Resolver provider 'mongodb+srv//user is not supported
Error: Resolver provider 'mongodb+srv//user is not supported
    at createResolverProvider (file:///home/garethm/.serverless/releases/4.0.24/package/dist/sf-core.js:989:12273)
    at #addResolverProvider (file:///home/garethm/.serverless/releases/4.0.24/package/dist/sf-core.js:989:19249)
    at #handleProviderNode (file:///home/garethm/.serverless/releases/4.0.24/package/dist/sf-core.js:989:19703)
    at file:///home/garethm/.serverless/releases/4.0.24/package/dist/sf-core.js:989:18427
    at processNodeAndHandleCompletion (file:///home/garethm/.serverless/releases/4.0.24/package/dist/sf-core.js:989:13727)
    at processNodeAndManagePromise (file:///home/garethm/.serverless/releases/4.0.24/package/dist/sf-core.js:989:14363)
    at file:///home/garethm/.serverless/releases/4.0.24/package/dist/sf-core.js:989:14180
    at Array.forEach (<anonymous>)
    at processSinks (file:///home/garethm/.serverless/releases/4.0.24/package/dist/sf-core.js:989:14135)
    at processGraphInParallel (file:///home/garethm/.serverless/releases/4.0.24/package/dist/sf-core.js:989:13831)
    at #resolveAndReplacePlaceholders (file:///home/garethm/.serverless/releases/4.0.24/package/dist/sf-core.js:989:18194)
    at _ResolverManager.resolveAndReplacePlaceholdersInConfig (file:///home/garethm/.serverless/releases/4.0.24/package/dist/sf-core.js:989:17954)
    at Object.resolveServiceConfig (file:///home/garethm/.serverless/releases/4.0.24/package/dist/sf-core.js:989:28521)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/garethm/.serverless/releases/4.0.24/package/dist/sf-core.js:992:1209
    at async route (file:///home/garethm/.serverless/releases/4.0.24/package/dist/sf-core.js:992:1182)
```

### Context

N/A

**Comment by ac360** [comment]
Fixed in https://github.com/serverless/serverless/releases/tag/v4.0.30
