### ISSUE TITLE
Error: Cannot find module 'serverless/lib/serverless-error' While installing the appsync plugin

### ISSUE THREAD

**Issue by Prakashgajapathi** [serverless/serverless#12565]
### Issue description

**We are encountering the below issue while installing the "serverless-appsync-plugin". Kindly help us to resolve this**

`To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^3.38.0")

Environment: linux, node 20.13.1, framework 3.38.0, plugin 7.2.3, SDK 4.5.1
Error:
Error: Cannot find module 'serverless/lib/serverless-error'
Require stack:
- /home/runner/work/smart-contact-center-backend/smart-contact-center-backend/scc-real-time-transcript/node_modules/serverless-appsync-plugin/lib/resources/Schema.js
- /home/runner/work/smart-contact-center-backend/smart-contact-center-backend/scc-real-time-transcript/node_modules/serverless-appsync-plugin/lib/resources/Api.js
- /home/runner/work/smart-contact-center-backend/smart-contact-center-backend/scc-real-time-transcript/node_modules/serverless-appsync-plugin/lib/index.js
- /opt/hostedtoolcache/node/20.13.1/x64/lib/node_modules/serverless/lib/utils/require-with-import-fallback.js
- /opt/hostedtoolcache/node/20.13.1/x64/lib/node_modules/serverless/lib/classes/plugin-manager.js
- /opt/hostedtoolcache/node/20.13.1/x64/lib/node_modules/serverless/lib/serverless.js
- /opt/hostedtoolcache/node/20.13.1/x64/lib/node_modules/serverless/scripts/serverless.js
- /opt/hostedtoolcache/node/20.13.1/x64/lib/node_modules/serverless/bin/serverless.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/runner/work/smart-contact-center-backend/smart-contact-center-backend/scc-real-time-transcript/node_modules/serverless-appsync-plugin/lib/resources/Schema.js:12:42)
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1[41](https://github.com/RozieAI/smart-contact-center-backend/actions/runs/9301328959/job/25599244784#step:8:42)6:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/runner/work/smart-contact-center-backend/smart-contact-center-backend/scc-real-time-transcript/node_modules/serverless-appsync-plugin/lib/resources/Api.js:31:16)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/runner/work/smart-contact-center-backend/smart-contact-center-backend/scc-real-time-transcript/node_modules/serverless-appsync-plugin/lib/index.js:52:13)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at module.exports (/opt/hostedtoolcache/node/20.13.1/x64/lib/node_modules/serverless/lib/utils/require-with-import-fallback.js:5:12)
    at PluginManager.requireServicePlugin (/opt/hostedtoolcache/node/20.13.1/x64/lib/node_modules/serverless/lib/classes/plugin-manager.js:171:14)
    at PluginManager.resolveServicePlugins (/opt/hostedtoolcache/node/20.13.1/x64/lib/node_modules/serverless/lib/classes/plugin-manager.js:198:29)
    at PluginManager.loadAllPlugins (/opt/hostedtoolcache/node/20.13.1/x64/lib/node_modules/serverless/lib/classes/plugin-manager.js:136:47)
    at Serverless.init (/opt/hostedtoolcache/node/20.13.1/x64/lib/node_modules/serverless/lib/serverless.js:1[46](https://github.com/RozieAI/smart-contact-center-backend/actions/runs/9301328959/job/25599244784#step:8:47):30)
    at async /opt/hostedtoolcache/node/20.13.1/x64/lib/node_modules/serverless/scripts/serverless.js:601:7
Error: Process completed with exit code 1.`

### Context

Serverless version:
Framework Core: 3.38.0 (global)
Plugin: 7.2.3
SDK: 4.5.1

Plugin Version:
  "devDependencies": {
    "serverless-appsync-plugin": "^2.7.0"
  }

**Comment by clayhorste** [comment]
I've run into this as well. Is there some sort of workaround? My googling hasn't revealed much.

**Comment by jessica-busatto** [comment]
> I've run into this as well. Is there some sort of workaround? My googling hasn't revealed much.

I threw away the plugin and created the resources differently.
