### ISSUE TITLE
[windows][v4] serverless invoke local is failing to load handlers

### ISSUE THREAD

**Issue by cedric-vermeulen** [serverless/serverless#12621]
### Issue description

I did update to serverless V4 with success. If running serverless dev, I have no issue. 
But when i try to run `serverless invoke local -f handler` it does fail with this kind of issue:

![image](https://github.com/serverless/serverless/assets/3263619/4a2a0318-724d-4a65-a684-174975370127)

I could pinpoint the exact location and fix.

In _.serverless\releases\4.1.5\package\dist\sf-core.js_
Line 1025 i did change:
`path47.join(this.serverless.serviceDir,this.options.extraServicePath||"",handlerPath)`
to
`path47.join("file://",this.serverless.serviceDir,this.options.extraServicePath||"",handlerPath)`

Of course it's a bit of a hack, I've seen in the file that we do handle file system more cleanly but I needed a quick fix. 

I hope this is enough informations to help you fix the issue. 

# Service Overview
- Serverless Framework Version: 4.1.5
- Command:  --version true

# Service Overview
- Serverless Framework Version: 4.1.5
- Service Config File: serverless.ts
- Service Name: project-manager
- Service Runtime: nodejs20.x
- Service Stage: dev
- Service Region: us-east-1
- Command: invoke local --function hello

## Service Path
E:\kkk\gestion\gestion.services\project-manager

## Service Config
```
import type { AWS } from '@serverless/typescript';
import hello from '@functions/hello';
const serverlessConfiguration: AWS = {
  service: 'project-manager',
  org: 'slade',
  frameworkVersion: '4',
  plugins: [],
  provider: {
    name: 'aws',
    runtime: 'nodejs20.x',
    environment: {
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1',
      AWS_REGION: 'eu-west-1',
      AWS_ACCESS_KEY_ID: '$AWS_ACCESS_KEY_ID',
      AWS_SECRET_ACCESS_KEY: '$AWS_SECRET_ACCESS_KEY',
      NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000',
    },
  },
  functions: { hello },
  custom: {},
};
module.exports = serverlessConfiguration;
```

Thank you,
Have a nice day,

**Comment by eahefnawy** [comment]
Thanks a lot for the detailed report @cedric-vermeulen ... We really appreciate such reports ❤️ ... I'll look into this.

**Comment by NicoHinderling** [comment]
I just wanted to +1 to this. I tried running a local command that worked in v3 and got the following stacktrace:

```
npm exec sls invoke local --function fireball --stage prod --data {"function": "nico"}

Warning: Using serverless deploy -f option only updates the function code and will not update CloudFormation stack (env variables included).
✖ ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/Users/nicolashinderling/dev/emerge-pnpm-on-hold/backend/services/emerge/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///Users/nicolashinderling/dev/emerge-pnpm-on-hold/backend/services/emerge/.serverless/build/src/fireball/fireball.js:224:2761
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadModule (file:///Users/nicolashinderling/.serverless/releases/4.1.5/package/dist/sf-core.js:1025:9923)
    at async AwsInvokeLocal.invokeLocalNodeJs (file:///Users/nicolashinderling/.serverless/releases/4.1.5/package/dist/sf-core.js:1025:9253)
    at async PluginManager.runHooks (file:///Users/nicolashinderling/.serverless/releases/4.1.5/package/dist/sf-core.js:1028:9294)
    at async PluginManager.invoke (file:///Users/nicolashinderling/.serverless/releases/4.1.5/package/dist/sf-core.js:1028:10064)
    at async PluginManager.run (file:///Users/nicolashinderling/.serverless/releases/4.1.5/package/dist/sf-core.js:1028:10788)
    at async Serverless.run (file:///Users/nicolashinderling/.serverless/releases/4.1.5/package/dist/sf-core.js:1035:10442)
    at async runFramework (file:///Users/nicolashinderling/.serverless/releases/4.1.5/package/dist/sf-core.js:1079:2314)
    at async route (file:///Users/nicolashinderling/.serverless/releases/4.1.5/package/dist/sf-core.js:1088:14692)
    at async Object.run2 [as run] (file:///Users/nicolashinderling/.serverless/releases/4.1.5/package/dist/sf-core.js:1088:15090)
    at async run3 (file:///Users/nicolashinderling/.serverless/releases/4.1.5/package/dist/sf-core.js:1088:16324)


✖ Exception encountered when loading /Users/nicolashinderling/dev/emerge-pnpm-on-hold/backend/services/emerge/.serverless/build/src/fireball/fireball
ServerlessError2: Exception encountered when loading /Users/nicolashinderling/dev/emerge-pnpm-on-hold/backend/services/emerge/.serverless/build/src/fireball/fireball
    at AwsInvokeLocal.invokeLocalNodeJs (file:///Users/nicolashinderling/.serverless/releases/4.1.5/package/dist/sf-core.js:1025:9347)
    at async PluginManager.runHooks (file:///Users/nicolashinderling/.serverless/releases/4.1.5/package/dist/sf-core.js:1028:9294)
    at async PluginManager.invoke (file:///Users/nicolashinderling/.serverless/releases/4.1.5/package/dist/sf-core.js:1028:10064)
    at async PluginManager.run (file:///Users/nicolashinderling/.serverless/releases/4.1.5/package/dist/sf-core.js:1028:10788)
    at async Serverless.run (file:///Users/nicolashinderling/.serverless/releases/4.1.5/package/dist/sf-core.js:1035:10442)
    at async runFramework (file:///Users/nicolashinderling/.serverless/releases/4.1.5/package/dist/sf-core.js:1079:2314)
    at async route (file:///Users/nicolashinderling/.serverless/releases/4.1.5/package/dist/sf-core.js:1088:14692)
    at async Object.run2 [as run] (file:///Users/nicolashinderling/.serverless/releases/4.1.5/package/dist/sf-core.js:1088:15090)
    at async run3 (file:///Users/nicolashinderling/.serverless/releases/4.1.5/package/dist/sf-core.js:1088:16324)

For help, try the following:
  • Run the command again with the "--debug" option
  • Run "serverless support"
  • Review the docs: https://www.serverless.com/framework/docs/

npm verb exit 1
npm verb code 1
```

**Comment by NicoHinderling** [comment]
@eahefnawy was this change released? I tried running `npx serverless update` and am still seeing errors when running my local invoke command (slightly different error message but still similar... I can post the error logs if needed)

**Comment by eahefnawy** [comment]
Yeah it was released. What's the new error you're seeing? 🤔

**Comment by NicoHinderling** [comment]
Hey @eahefnawy my apologies, I had something messed up locally. I re-setup my local and my npx invoke local is working now! Sorry about that!

**Comment by eahefnawy** [comment]
Great to hear! 🙌
