### ISSUE TITLE
Bug with version 4.1.8 when trying to deploy

### ISSUE THREAD

**Issue by NicoHinderling** [serverless/serverless#12656]
### Issue description

reporting this because it appears to go away when I pin to version 4.1.7

`Run npx serverless deploy --region us-west-1 --stage dev`

```
Deploying "emerge" to stage "dev" (us-west-1)
✖ Stack emerge-dev failed to deploy (0s)

✖ ENOENT: no such file or directory, open '/home/runner/.serverless/releases/4.1.8/package/lib/plugins/aws/package/lib/core-cloudformation-template.json'
Error: ENOENT: no such file or directory, open '/home/runner/.serverless/releases/4.1.8/package/lib/plugins/aws/package/lib/core-cloudformation-template.json'
    at Object.openSync (node:fs:573:18)
    at Object.readFileSync (node:fs:452:35)
    at readFileSync4 (file:///home/runner/.serverless/releases/4.1.8/package/dist/sf-core.js:1033:4216)
    at Utils.readFileSync (file:///home/runner/.serverless/releases/4.1.8/package/dist/sf-core.js:1033:5766)
    at AwsPackage.generateCoreTemplate (file:///home/runner/.serverless/releases/4.1.8/package/dist/sf-core.js:833:11392)
    at package:initialize (file:///home/runner/.serverless/releases/4.1.8/package/dist/sf-core.js:833:248[12](https://github.com/EmergeTools/emerge/actions/runs/9750341839/job/26909563790#step:8:13))
    at PluginManager.runHooks (file:///home/runner/.serverless/releases/4.1.8/package/dist/sf-core.js:1032:9302)
    at PluginManager.invoke (file:///home/runner/.serverless/releases/4.1.8/package/dist/sf-core.js:1032:10077)
    at async PluginManager.spawn (file:///home/runner/.serverless/releases/4.1.8/package/dist/sf-core.js:1032:10427)
    at async before:deploy:deploy (file:///home/runner/.serverless/releases/4.1.8/package/dist/sf-core.js:816:39201)
    at async PluginManager.runHooks (file:///home/runner/.serverless/releases/4.1.8/package/dist/sf-core.js:1032:9296)
    at async PluginManager.invoke (file:///home/runner/.serverless/releases/4.1.8/package/dist/sf-core.js:1032:10007)
    at async PluginManager.run (file:///home/runner/.serverless/releases/4.1.8/package/dist/sf-core.js:1032:10790)
    at async Serverless.run (file:///home/runner/.serverless/releases/4.1.8/package/dist/sf-core.js:1039:10442)
    at async runFramework (file:///home/runner/.serverless/releases/4.1.8/package/dist/sf-core.js:1087:23[14](https://github.com/EmergeTools/emerge/actions/runs/9750341839/job/26909563790#step:8:15))
    at async route (file:///home/runner/.serverless/releases/4.1.8/package/dist/sf-core.js:1098:[15](https://github.com/EmergeTools/emerge/actions/runs/9750341839/job/26909563790#step:8:16)943)
    at async Object.run2 [as run] (file:///home/runner/.serverless/releases/4.1.8/package/dist/sf-core.js:1098:[16](https://github.com/EmergeTools/emerge/actions/runs/9750341839/job/26909563790#step:8:17)341)
    at async run3 (file:///home/runner/.serverless/releases/4.1.8/package/dist/sf-core.js:1098:17601)

For help, try the following:
  • Run the command again with the "--debug" option
  • Run "serverless support"
  • Review the docs: https://www.serverless.com/framework/docs/
  ```
  
  i can run it in debug mode if that's helpful too.

**Comment by NicoHinderling** [comment]
Sick that fixed it, thanks
