### ISSUE TITLE
Error when integrating axiom

### ISSUE THREAD

**Issue by mishabhi** [serverless/serverless#12827]
### Issue description

When integrating axiom as per `https://www.serverless.com/framework/docs/guides/observability/axiom` , I am getting below error. What exactly is this? I have axiom token and everything properly setup and I am using SLS v4.

```
s:core:meta: saving meta record to global .serverless directory.
s:cli-error-handler: "size" must be less than or equal to 100
BadRequestError: "size" must be less than or equal to 100
    at QueryClient.makeRequest (/home/abhishek/.serverless/releases/node_modules/@serverless-inc/sdk/src/baseClient.ts:106:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at QueryClient._post (/home/abhishek/.serverless/releases/node_modules/@serverless-inc/sdk/src/baseClient.ts:50:17)
    at getIntegratedFunctions (/home/abhishek/.serverless/releases/4.2.5/sf-core/src/lib/observability/dashboard/index.js:552:20)
    at isAnyFunctionIntegrated (/home/abhishek/.serverless/releases/4.2.5/sf-core/src/lib/observability/dashboard/index.js:533:31)
    at validateAndGetToken (/home/abhishek/.serverless/releases/4.2.5/sf-core/src/lib/observability/axiom/index.js:143:5)
    at Axiom2.addEnvVarsAndLayer (/home/abhishek/.serverless/releases/4.2.5/serverless/lib/plugins/observability/axiom/index.js:45:28)
    at PluginManager.runHooks (/home/abhishek/.serverless/releases/4.2.5/serverless/lib/classes/plugin-manager.js:680:9)
    at PluginManager.invoke (/home/abhishek/.serverless/releases/4.2.5/serverless/lib/classes/plugin-manager.js:720:9)
    at PluginManager.spawn (/home/abhishek/.serverless/releases/4.2.5/serverless/lib/classes/plugin-manager.js:740:5)
```

**Comment by czubocha** [comment]
Thanks for reporting @mishabhi, we're looking into it.

**Comment by czubocha** [comment]
@mishabhi the fix is ready for release. I’ll let you know as soon as it’s live.

**Comment by sumit4way** [comment]
Hi @czubocha, could you please provide an estimate for when it will go live?

**Comment by czubocha** [comment]
@sumit4way @mishabhi It’s live now in version 4.4.2. Feel free to test it out and let us know if you encounter any issues.
