### ISSUE TITLE
Plugin issue | serverless-aws-alias

### ISSUE THREAD

**Issue by danyal2050** [serverless/serverless#12834]
### Issue description

When I installed that plugin and tried to run it, it failed.
https://www.serverless.com/plugins/serverless-aws-alias
Error: Cannot find module '/home/cloud_user/service/node_modules/serverless/lib/plugins/aws/lib/monitorStack'
Require stack:
- /home/cloud_user/service/node_modules/serverless-aws-alias/index.js
- /home/cloud_user/service/node_modules/serverless/lib/utils/require-with-import-fallback.js
- /home/cloud_user/service/node_modules/serverless/lib/classes/plugin-manager.js
- /home/cloud_user/service/node_modules/serverless/lib/serverless.js
- /home/cloud_user/service/node_modules/serverless/scripts/serverless.js
- /home/cloud_user/service/node_modules/serverless/bin/serverless.js
- /home/cloud_user/.nvm/versions/node/v20.17.0/lib/node_modules/serverless/bin/serverless.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at new AwsAlias (/home/cloud_user/service/node_modules/serverless-aws-alias/index.js:43:24)
    at PluginManager.addPlugin (/home/cloud_user/service/node_modules/serverless/lib/classes/plugin-manager.js:91:28)
    at /home/cloud_user/service/node_modules/serverless/lib/classes/plugin-manager.js:137:69
    at Array.forEach (<anonymous>)
    at PluginManager.loadAllPlugins (/home/cloud_user/service/node_modules/serverless/lib/classes/plugin-manager.js:137:44)
    at async Serverless.init (/home/cloud_user/service/node_modules/serverless/lib/serverless.js:146:5)
    at async /home/cloud_user/service/node_modules/serverless/scripts/serverless.js:601:7

### Context

![Uploading Screenshot 2024-09-27 at 14.23.27.png…]()

**Comment by skierkowski** [comment]
Closing as there is too little context here.
