### ISSUE TITLE
Github API rate exceeded when deploying with Axiom integration

### ISSUE THREAD

**Issue by purrplehaze** [serverless/serverless#12839]
### Issue description

Service deployment fails with Axiom integration enabled because of Github API rate limits for unauthenticated requests. I haven't found ways to substitute my auth token to circumvent this limitation.

### Context

# Service Overview
- Serverless Framework Version: 4.4.2
- Service Config File: serverless.yml
- Service Name: evoratool-backend
- Service Runtime: nodejs20.x
- Service Stage: dev
- Service Region: eu-central-1
- Command: deploy --verbose true,--debug *

## Service Path
/Users/crazydevil44/ghq/github.com/purrplehaze/evoratool/apps/backend

## Error Message
API rate limit exceeded for <IP_ADDRESS>. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) - https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting

## Error Stacktrace
```
at fetchWrapper (/Users/crazydevil44/.serverless/releases/4.4.2/sf-core/node_modules/@octokit/request/dist-bundle/index.js:119:11)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at fetchLatestLayerVersion (/Users/crazydevil44/.serverless/releases/4.4.2/sf-core/src/lib/observability/axiom/layer.js:11:20)
at getLambdaConfigsForFunctions (/Users/crazydevil44/.serverless/releases/4.4.2/sf-core/src/lib/observability/axiom/lambda.js:65:24)
at getLambdaConfigs (/Users/crazydevil44/.serverless/releases/4.4.2/sf-core/src/lib/observability/axiom/index.js:238:25)
at Axiom2.addEnvVarsAndLayer (/Users/crazydevil44/.serverless/releases/4.4.2/serverless/lib/plugins/observability/axiom/index.js:56:31)
at PluginManager.runHooks (/Users/crazydevil44/.serverless/releases/4.4.2/serverless/lib/classes/plugin-manager.js:680:9)
at PluginManager.invoke (/Users/crazydevil44/.serverless/releases/4.4.2/serverless/lib/classes/plugin-manager.js:720:9)
at PluginManager.spawn (/Users/crazydevil44/.serverless/releases/4.4.2/serverless/lib/classes/plugin-manager.js:740:5)
at before:deploy:deploy (/Users/crazydevil44/.serverless/releases/4.4.2/serverless/lib/plugins/deploy.js:37:11)
```

# Service Overview
- Serverless Framework Version: 4.4.3
- Command: support --summary true

**Comment by czubocha** [comment]
Hey @purrplehaze, thanks for reporting this. Could you let us know if it occurred during a single deployment, or after multiple deployments from your IP address with Axiom enabled over time?

**Comment by purrplehaze** [comment]
> Hey @purrplehaze, thanks for reporting this. Could you let us know if it occurred during a single deployment, or after multiple deployments from your IP address with Axiom enabled over time?

Hey @czubocha, It occurred during the single deployment, the first single deployment during the day.

**Comment by czubocha** [comment]
We will soon provide the option to authenticate GitHub requests using a token in an environment variable, which will increase the rate limit to 5000 requests per hour.

**Comment by czubocha** [comment]
@purrplehaze starting with [v4.4.5](https://github.com/serverless/serverless/releases/tag/v4.4.5) it's now possible to authenticate GitHub requests by setting the `GITHUB_TOKEN` environment variable. Feel free to let us know if you run into any more issues.
