### ISSUE TITLE
TypeError: Cannot redefine property: default

### ISSUE THREAD

**Issue by gbecerra-bornan** [serverless/serverless#12862]
### Issue description

```
TypeError: Cannot redefine property: default
    at Function.defineProperty (<anonymous>)
    at .serverless/releases/4.4.6/package/dist/sf-core.js:407:46537
    at Array.forEach (<anonymous>)
    at getProfiles (.serverless/releases/4.4.6/package/dist/sf-core.js:407:46464)
    at constructor.loadFrom (.serverless/releases/4.4.6/package/dist/sf-core.js:407:47427)
    at getRegion (.serverless/releases/4.4.6/package/dist/sf-core.js:419:24937)
    at constructor.region (.serverless/releases/4.4.6/package/dist/sf-core.js:419:26230)
    at constructor.set (.serverless/releases/4.4.6/package/dist/sf-core.js:392:100915)
    at constructor.<anonymous> (.serverless/releases/4.4.6/package/dist/sf-core.js:392:98177)
    at constructor.each (.serverless/releases/4.4.6/package/dist/sf-core.js:407:20954)
```

### Context

I'm having this error when I trying to run sls command, I was searching info on internet and try to apply multiple solves what I've saw but nothing works

**Comment by skierkowski** [comment]
@gbecerra-bornan I'd like to help but I need a little more context. Can you do a couple things for me?

1. Run the failing command again
2. Run `sls support --github`
3. Share the output of the `sls support --github` command here.
