### ISSUE TITLE
function deploy throws exception

### ISSUE THREAD

**Issue by dwtowner** [serverless/serverless#1287]
serverless version 0.5.5, running on Ubuntu 14.04 LTS on x86_64 with node v4.0.0pre

On a working sls project I made various edits to a function handler (added sub-directory, changed the handler slightly), and now the `function deploy' command produces an error. The callstack is attached below but it isn't clear to me from that what has gone wrong with the deployment. Another sls project can still have its functions deployed, so it isn't an issue with my AWS setup.

---

erverless: Deploying the specified functions in "dev" to the following regions: eu-west-1                                                                                        
Serverless: ------------------------  
Serverless: Failed to deploy the following functions in "dev" to the following regions:  
Serverless: eu-west-1 ------------------------  
Serverless:   addBooking: undefined  
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

ServerlessError: Function Deployment Failed
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/Error.js:17:11)
    at FunctionDeploy.<anonymous> (/usr/local/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:126:19)
    at next (/usr/local/lib/node_modules/serverless/node_modules/fs-extra/node_modules/rimraf/rimraf.js:74:7)
    at FSReqWrap.CB [as oncomplete] (/usr/local/lib/node_modules/serverless/node_modules/fs-extra/node_modules/rimraf/rimraf.js:110:9)
From previous event:
    at FunctionDeploy.functionDeploy (/usr/local/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:105:10)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:186:31
    at Array.reduce (native)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:185:32
From previous event:
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:183:12)
    at Serverless.actions.(anonymous function) (/usr/local/lib/node_modules/serverless/lib/Serverless.js:429:20)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:398:38)
    at /usr/local/lib/node_modules/serverless/bin/serverless:19:16
    at processImmediate [as _immediateCallback] (timers.js:371:17)
From previous event:
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

**Comment by mankins** [comment]
Did you figure this out? I'm having a similar issue, also with an "undefined" at the last Serverless: line

**Comment by mankins** [comment]
I was able to trace this down:

[{"errno":-2,"code":"ENOENT","syscall":"stat","path":"PATHHERE/.bin/webpack"}] from _deployCodeByRegion of FunctionDeploy.js .. it looks like a symbolic link which went missing

As soon as I fixed that (by removing the bad symlink), I was able to build again.

In the "catch" block of _deployCodeByRegion, it looks as if in this case the error "e" doesn't have message/stack, so the real error message gets hidden. 

Hope that helps.

**Comment by JDFagan** [comment]
serverless version 0.5.6, running on Mac OS 10.11.4 with node v6.1.0

I seem to have similar stack trace but perhaps different "from previous event" origins.  I haven't resolved this issue yet so if you have any ideas for work arounds I'm game:

/Users/jfagan/.nodenv/versions/6.1.0/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

ServerlessError: Function Deployment Failed
    at new ServerlessError (/Users/jfagan/.nodenv/versions/6.1.0/lib/node_modules/serverless/lib/Error.js:17:11)
    at FunctionDeploy.<anonymous> (/Users/jfagan/.nodenv/versions/6.1.0/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:126:19)
    at next (/Users/jfagan/.nodenv/versions/6.1.0/lib/node_modules/serverless/node_modules/rimraf/rimraf.js:74:7)
    at FSReqWrap.CB [as oncomplete] (/Users/jfagan/.nodenv/versions/6.1.0/lib/node_modules/serverless/node_modules/rimraf/rimraf.js:110:9)
From previous event:
    at FunctionDeploy.functionDeploy (/Users/jfagan/.nodenv/versions/6.1.0/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:105:10)
From previous event:
    at /Users/jfagan/.nodenv/versions/6.1.0/lib/node_modules/serverless/lib/Serverless.js:211:25

**Comment by JDFagan** [comment]
Note: I was using wrong version of Node.  I downgraded to version 4.4.4 and now am not getting this error message anymore.

**Comment by JDFagan** [comment]
Hmmm...I seem to have run into it again even with Node version 4.4.4.  It seems when I have multiple "stages" I get this error.  I also noticed that in s-variables-{$stage}-{$region}.json file only now has region field and has lost following these fields (resourcesStackName, iamRoleArnLambda, apiGatewayApi) after adding stages:

Serverless:   groups: Missing required key 'Role' in params
/Users/jfagan/.nodenv/versions/4.4.4/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

ServerlessError: Function Deployment Failed
    at new ServerlessError (/Users/jfagan/.nodenv/versions/4.4.4/lib/node_modules/serverless/lib/Error.js:17:11)
    at FunctionDeploy.<anonymous> (/Users/jfagan/.nodenv/versions/4.4.4/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:126:19)
    at next (/Users/jfagan/.nodenv/versions/4.4.4/lib/node_modules/serverless/node_modules/fs-extra/node_modules/rimraf/rimraf.js:74:7)
    at FSReqWrap.CB [as oncomplete] (/Users/jfagan/.nodenv/versions/4.4.4/lib/node_modules/serverless/node_modules/fs-extra/node_modules/rimraf/rimraf.js:110:9)
From previous event:
    at FunctionDeploy.functionDeploy (/Users/jfagan/.nodenv/versions/4.4.4/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:105:10)
From previous event:
    at /Users/jfagan/.nodenv/versions/4.4.4/lib/node_modules/serverless/lib/Serverless.js:211:25
    at Array.reduce (native)
    at Serverless._execute (/Users/jfagan/.nodenv/versions/4.4.4/lib/node_modules/serverless/lib/Serverless.js:210:26)
    at Object.actions.(anonymous function) [as functionDeploy] (/Users/jfagan/.nodenv/versions/4.4.4/lib/node_modules/serverless/lib/Serverless.js:429:20)
    at /Users/jfagan/.nodenv/versions/4.4.4/lib/node_modules/serverless/lib/actions/DashDeploy.js:234:26
From previous event:
    at DashDeploy._deploy (/Users/jfagan/.nodenv/versions/4.4.4/lib/node_modules/serverless/lib/actions/DashDeploy.js:229:14)
From previous event:
    at DashDeploy.dashDeploy (/Users/jfagan/.nodenv/versions/4.4.4/lib/node_modules/serverless/lib/actions/DashDeploy.js:126:10)
From previous event:
    at /Users/jfagan/.nodenv/versions/4.4.4/lib/node_modules/serverless/lib/Serverless.js:186:31
    at Array.reduce (native)
    at /Users/jfagan/.nodenv/versions/4.4.4/lib/node_modules/serverless/lib/Serverless.js:185:32
From previous event:
    at Serverless._execute (/Users/jfagan/.nodenv/versions/4.4.4/lib/node_modules/serverless/lib/Serverless.js:183:12)
    at Serverless.actions.(anonymous function) (/Users/jfagan/.nodenv/versions/4.4.4/lib/node_modules/serverless/lib/Serverless.js:429:20)
    at Serverless.command (/Users/jfagan/.nodenv/versions/4.4.4/lib/node_modules/serverless/lib/Serverless.js:398:38)
    at /Users/jfagan/.nodenv/versions/4.4.4/lib/node_modules/serverless/bin/serverless:19:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Object.<anonymous> (/Users/jfagan/.nodenv/versions/4.4.4/lib/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by dwtowner** [comment]
I'm hitting it again too. The error went away for a bit after I deleted the
region and then recreated it and redeployed, but its come back again and
the region delete/create trick doesn't have any effect any more. There
aren't any symlinks in my directories either for me to fix (as Matt Mankins
reports that deleting some invalid symlinks worked for him).

dan.

**Comment by dwtowner** [comment]
p.s. It reliably fails now, all the time, so if a maintainer wants me to
try anything I can do so.

**Comment by jvallarvisp** [comment]
I was reproducing this issue. I only delete the project and 
git clone
npm install
sls project init

**Comment by dtslvr** [comment]
I have the same issue with serverless 0.5.5. It's annoying :/

**Comment by cspeer** [comment]
+1 Running into it with 0.5.6 :(

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.

**Comment by stevecrozz** [comment]
V1.0 is in beta. Is there no current release version of serverless that is also supported by serverless? That might be ok for the 0.x series, but I'd like to point out that this attitude causes me some concern over the level of support I can expect from the team on future releases. When 1.0 is officially released, I'll be particularly interested in seeing an announcement on how long support can be expected for the 1.0 series.

**Comment by flomotlik** [comment]
@stevecrozz Yes we'll release more info on our longer term plans soonish. The company is definitely growing and we have some great updates to share over the next weeks.

The main reason why we stopped 0.5 development and fully focused on 1.0 is so we have an architecture in place we can support longer term. By building everything into this clear plugin system its much easier for us to develop serverless for a long time without having to introduce constant breaking changes.
