### ISSUE TITLE
[v4] Automatically trigger aws sso login when expired session

### ISSUE THREAD

**Issue by kdybicz** [serverless/serverless#12876]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Due to how strict security policies are in my company a couple of times a day I'm facing the below error. I've already learned to recognize it and to manually trigger the `aws sso login`, but I started to wonder if Serverless could trigger SSO login automatically? I saw such behavior in some of our internal tools and I believe it might help to save some people a couple of minutes a day of their file 😄 

```
✖ Error: Failed to resolve variable '/some/secret/key' with resolver 'ssm' and provider 'default-aws-credential-resolver': Error: AWS credentials missing or invalid. Original error from AWS: The SSO session associated with this profile has expired. To refresh this SSO session run aws sso login with the corresponding profile.
    at #resolveKey (file:///Users/random/.serverless/releases/4.4.6/package/dist/sf-core.js:693:50290)
    at async _ResolverManager.resolve (file:///Users/random/.serverless/releases/4.4.6/package/dist/sf-core.js:693:55683)
    at async #handlePlaceholderNode (file:///Users/random/.serverless/releases/4.4.6/package/dist/sf-core.js:693:54452)
    at async file:///Users/random/.serverless/releases/4.4.6/package/dist/sf-core.js:693:52444
    at async processNodeAndHandleCompletion (file:///Users/random/.serverless/releases/4.4.6/package/dist/sf-core.js:693:43086)
```

### Proposed solution (optional)

Serverless v4.4.6

**Comment by ethanherbertson** [comment]
A pattern my team uses is to define scripts in package.json that run the various Serverless CLI commands we frequently use (e.g. `sls deploy` and `sls remove`). One thing this allows us to do is to "bake in" CLI options that we consider best practice, e.g. the new `--conceal` flag. But an additional benefit is that you can prepend commands like `aws sso login` to those scripts for convenience:

```json
  "scripts": {
    "coverage": "nyc report --reporter=text-summary",
    "lint": "semistandard --verbose | snazzy",
    "lint-fix": "semistandard --verbose --fix",
    "mocha": "mocha --recursive",
    "test": "semistandard --verbose | snazzy && nyc mocha --recursive",
    "test-grep": "semistandard --verbose | snazzy && mocha --recursive --grep",
    "deploy-stage": "aws sso login && serverless deploy --conceal -s",
    "serverless-version": "serverless version",
    "teardown-stage": "aws sso login && serverless remove -s"
  },
```

The `deploy-stage` and `teardown-stage` scripts expect the user to specify a stage name when used, e.g. `yarn deploy-stage my-stage-name` and `yarn teardown-stage my-stage-name`. Similarly the `test-grep` script expects a pattern. Obviously that's not a perfectly flexible pattern, in that it relies on positional parameters, but we've been doing this comfortably for years on my team at this point.

We don't use SSO on my team, so I can't directly verify that the above will work... but it should, assuming that `aws sso login` exits with appropriate truthy/falsey codes for your shell.

**Comment by kdybicz** [comment]
> Also assuming that `aws sso login` does the convenient early-out thing when you're already/still logged in...

@ethanherbertson Unfortunately, it does not 😞

**Comment by czubocha** [comment]
Additional context from duplicate #13139:

> I'm trying to create a nice development workflow that works with our SSO profiles. At the moment if your aws sso login --profile <name> has timed out, serverless will throw a:
> 
> AWS credentials missing or invalid. Original error from AWS: The SSO session token associated with profile=dev was not found or is invalid. To refresh this SSO session run 'aws sso login' with the corresponding profile..
> 
> It would be nice if serverless could see you are using sso sessions, and refresh your logins on use: calling aws sso login --profile <provider.profile> for you.
> 
> At the moment I'm prepending this all over the place to commands:
> 
> (aws sts get-caller-identity --profile=$PROFILE >/dev/null 2>&1 || aws sso login --profile=$PROFILE) && serverless deploy --stage alpha
> 
> This gets quite messy.
> 
> I have tried creating a plugin for this, but I don't believe it's possible for me to hook in before serverless throws this exception via the initialize lifecycle hook, or even the plugin loading constructor.

https://github.com/serverless/serverless/issues/13139#issue-3530296597
