### ISSUE TITLE
Serverless isn't creating default deployment bucket anymore?

### ISSUE THREAD

**Issue by cb-alyn** [serverless/serverless#12896]
### Issue description

Serverless version: 2.72.4
Node version: 12.22.12 (We've also tried 14.2)

Before Oct 28th, we were able to deploy serverless over an existing cloudformation stack without a problem but now, serverless isn't creating the deployment bucket, and fails in the ensure-bucket-exists.js:

```
"Serverless: Ensuring that deployment bucket exists", "Serverless: Deployment bucket not found. Updating stack to include deployment bucket definition.", " ", " Syntax Error --------------------------------------------", " ", "  
SyntaxError: Unexpected token A in JSON at position 0", "     
 at JSON.parse (<anonymous>)", "     
 at AwsDeploy.ensureValidBucketExists
``` 

Logs with SLS_DEBUG=* enabled:
```
SServerless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Invoke deploy
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:moveArtifactsToTemp
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS sts 200 0.415s 0 retries] getCallerIdentity({})
Serverless: [AWS cloudformation 200 0.332s 0 retries] describeStacks({ StackName: 'OBFUSCATED' })
Serverless: Ensuring that deployment bucket exists
Serverless: [AWS cloudformation 400 1.389s 0 retries] describeStackResource({
  StackName: 'OBFUSCATED,
  LogicalResourceId: 'ServerlessDeploymentBucket'
})
Serverless: Deployment bucket not found. Updating stack to include deployment bucket definition.
Serverless: [AWS cloudformation 200 0.705s 0 retries] getTemplate({ StackName: 'OBFUSCATED', TemplateStage: 'Original' })
 
 Syntax Error --------------------------------------------
 
  SyntaxError: Unexpected token A in JSON at position 0
      at JSON.parse (<anonymous>)
      at AwsDeploy.ensureValidBucketExists (/Users/OBFUSCATED/.nvm/versions/node/v12.22.12/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/ensure-valid-bucket-exists.js:82:31)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async aws:deploy:deploy:checkForChanges (/Users/OBFUSCATED/.nvm/versions/node/v12.22.12/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:127:9)
      at async PluginManager.runHooks (/Users/OBFUSCATED/.nvm/versions/node/v12.22.12/lib/node_modules/serverless/lib/classes/PluginManager.js:601:35)
      at async PluginManager.invoke (/Users/OBFUSCATED/.nvm/versions/node/v12.22.12/lib/node_modules/serverless/lib/classes/PluginManager.js:639:9)
      at async PluginManager.spawn (/Users/OBFUSCATED/.nvm/versions/node/v12.22.12/lib/node_modules/serverless/lib/classes/PluginManager.js:663:5)
      at async PluginManager.runHooks (/Users/OBFUSCATED/.nvm/versions/node/v12.22.12/lib/node_modules/serverless/lib/classes/PluginManager.js:601:35)
      at async PluginManager.invoke (/Users/OBFUSCATED/.nvm/versions/node/v12.22.12/lib/node_modules/serverless/lib/classes/PluginManager.js:639:9)
      at async PluginManager.run (/Users/OBFUSCATED/.nvm/versions/node/v12.22.12/lib/node_modules/serverless/lib/classes/PluginManager.js:700:7)
      at async Serverless.run (/Users/OBFUSCATED/.nvm/versions/node/v12.22.12/lib/node_modules/serverless/lib/Serverless.js:468:5)
      at async /Users/OBFUSCATED/.nvm/versions/node/v12.22.12/lib/node_modules/serverless/scripts/serverless.js:836:9
``` 

We are trying to stand up our test environment and 3 S3 buckets of backup data that we need to import into the stack to continue producing backups. We do this through AWS Cloudformation by importing existing resources through a changeset. After successfully importing, we would update the stack to deploy the rest of the resources through the serverless stack and it would create everything including the deployment bucket. This is all instrumented through ansible. Now, since Oct 28th, it errors out  with the message above as we are trying to stand up our test environment. 

Note: If we do a fresh Serverless deploy without the existing AWS Cloudformation stack, it will work and create the Serverless Deployment Bucket long with all the other resources.

We're still trying to diagnose why this is just now occurring as we have not changed anything, with our most recent successful deployment on Oct. 25th. We understand that it can't find the Serverless Deployment bucket since it isn't originally a Serverless Stack but it worked prior to October 28th.

### Context

Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.22.12
     Framework Version:         2.72.4
     Plugin Version:            5.5.4
     SDK Version:               4.5.1
     Components Version:        3.18.2

**Comment by czubocha** [comment]
Hey @cb-alyn! It looks like you’re using a very outdated version of Serverless (2.72.4). There haven’t been any recent changes to the v2, so this behaviour is likely unrelated to a change on Serverless’s end.
