### ISSUE TITLE
Upgrading to Serverless V4 with Serverless compose is broken

### ISSUE THREAD

**Issue by kesavab** [serverless/serverless#12906]
### Issue description

I am using Serverless compose for composing my services and it was all fine in V3. When I upgraded to V4, I get error like below

` Error: An error occurred while fetching the SSM parameter "/serverless-framework/state/s3-bucket": User: xxxx is not authorized to perform: ssm:GetParameter on resource: xxx:parameter/serverless-framework/state/s3-bucket with an explicit deny in a service control policy
    at <anonymous> (/Users/xxxxi/.serverless/releases/4.4.7/sf-core/src/utils/globalBucket/index.js:81:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at checkStoredBucket (/Users/xxx/.serverless/releases/4.4.7/sf-core/src/utils/globalBucket/index.js:75:28)
    at getOrCreateDefaultBucket (/Users/xxx/.serverless/releases/4.4.7/sf-core/src/utils/globalBucket/index.js:38:24)
    at <anonymous> (/Users/xxx/.serverless/releases/4.4.7/sf-core/src/lib/compose/state.js:256:16)
    at getOrCreateStateStore (/Users/xxx/.serverless/releases/4.4.7/sf-core/src/lib/compose/state.js:254:42)
    at resolveStateStore (/Users/xxx/.serverless/releases/4.4.7/sf-core/src/lib/compose/state.js:105:40)
    at runCompose (/Users/xxx/.serverless/releases/4.4.7/sf-core/src/lib/runners/compose.js:103:50)
    at route (/Users/xxx/.serverless/releases/4.4.7/sf-core/src/lib/router.js:164:12)
    at Object.run2 (/Users/xxx/.serverless/releases/4.4.7/sf-core/src/index.js:45:3)`

What I don't understand is why is it creating/accessing resources in us-east-1 region? I don't have access in that region. 

From docs, I see that as part of V4, there is a new shared state etc. Is the issue due to the shared state being created in us-east-1 region?  If yes, is there anyway I can use zero setup config with just region? 

Also how is this S3 bucket used for state different from the deployment bucket already created by serverless compose? And if I create a new bucket for state what happens to the existing deployment bucket? Hope it will not cause any confusion and recreate resources during deployment?

### Context

**Summary:**

Serverless ϟ Support

This generates a report from your last Serverless Framework command (including any errors) to use for Github Issues, debugging w/ AI, or creating a support ticket w/ Serverless Inc.

Summary Report -----------------

No previous command information was found

To include more details, please run a serverless command before running 'serverless support'

 Service Overview
- Serverless Framework Version: 4.4.7

Above is a summary report of your last Serverless Framework command.

Use it to debug with AI (e.g. ChatGPT) or report a new Github Issue: https://slss.io/issue

# My Compse yaml:
```
services:
  deploymentBucket:
    path: ./serverless/deployment-bucket

  commonLambdaLayer:
    path: ./lambda-layers/packages/common
    params:
      deploymentBucketName: ${deploymentBucket.deploymentBucketName}
```

#  My Serverless yaml

```
service: efa-db-deployment-bucket
frameworkVersion: "4"


provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage,'dev'}
  region: ${env:AWS_REGION, "eu-west-1"}
  deploymentBucket:
    blockPublicAccess: true
    serverSideEncryption: AES256

resources:
  Resources:
```

Removed other bits for sake of privacy. 

#  Command I ran 

`serverless print --debug  --stage dev`

And output is 

```
$ serverless print --debug  --stage dev

s:core: {
  node: 'v18.18.2',
  os: 'darwin',
  arch: 'arm64',
  shell: '/bin/zsh',
  cwd: '/Users/xxx/workspace/cus-field-and-asset-efa-db',
  nodeJsPath: '/Users/xxx/versions/node/v18.18.2/bin/node',
  scriptPath: '/Users/xxx/.serverless/releases/4.4.7/package/dist/sf-core.js',
  scriptArgs: [ 'print', '--debug', '--stage', 'dev' ],
  logLevel: 'debug',
  isInteractive: true
}
s:core: { serverless_framework: '4.4.7' }
s:main: Initializing
s:core:router: {
  command: [ 'print' ],
  options: { debug: '*', stage: 'dev' },
  versions: { serverless_framework: '4.4.7' },
  customConfigFilePath: null,
  composeParams: undefined,
  composeResolverProviders: undefined,
  isWithinCompose: false,
  composeOrgName: null,
  composeServiceName: null
}
s:core:resolver:manager: placeholders graph {
  options: { directed: true, multigraph: false, compound: false },
  nodes: [],
  edges: []
}
s:core:auth:get-authenticated-data: license key provided manually
(node:92505) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
s:core:resolver:default-aws-credential-resolver: resolving AWS credentials using the AWS SDK credential provider chain with profile: undefined
s:core:utils:credentials:aws:get-aws-credential-identity-provider: resolved AWS credentials for account ID: xxx in region: us-east-1
s:core:meta: resolved AWS credentials for account ID xxx in region us-east-1
s:core:compose:state: Checking if /serverless-framework/state/s3-bucket exists in SSM
s:core:meta: Skipping analysis event because license key is used
s:cli-error-handler: Error: An error occurred while fetching the SSM parameter "/serverless-framework/state/s3-bucket": User: arn:aws:sts::xxx:assumed-role/xxx/xxx is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:us-east-1:xxx:parameter/serverless-framework/state/s3-bucket with an explicit deny in a service control policy
    at <anonymous> (/Users/xxx/.serverless/releases/4.4.7/sf-core/src/utils/globalBucket/index.js:81:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at checkStoredBucket (/Users/xxx/.serverless/releases/4.4.7/sf-core/src/utils/globalBucket/index.js:75:28)
    at getOrCreateDefaultBucket (/Users/xxx/.serverless/releases/4.4.7/sf-core/src/utils/globalBucket/index.js:38:24)
    at <anonymous> (/Users/xxx/.serverless/releases/4.4.7/sf-core/src/lib/compose/state.js:256:16)
    at getOrCreateStateStore (/Users/xxx/.serverless/releases/4.4.7/sf-core/src/lib/compose/state.js:254:42)
    at resolveStateStore (/Users/xxx/.serverless/releases/4.4.7/sf-core/src/lib/compose/state.js:105:40)
    at runCompose (/Users/xxx/.serverless/releases/4.4.7/sf-core/src/lib/runners/compose.js:103:50)
    at route (/Users/xxx/.serverless/releases/4.4.7/sf-core/src/lib/router.js:164:12)
    at Object.run2 (/Users/xxx/.serverless/releases/4.4.7/sf-core/src/index.js:45:3)

✖ Error: An error occurred while fetching the SSM parameter "/serverless-framework/state/s3-bucket": User: arn:aws:sts::xxx:assumed-role/xxx/xxx is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:us-east-1:xxx:parameter/serverless-framework/state/s3-bucket with an explicit deny in a service control policy
    at <anonymous> (/Users/xxx/.serverless/releases/4.4.7/sf-core/src/utils/globalBucket/index.js:81:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at checkStoredBucket (/Users/xxx/.serverless/releases/4.4.7/sf-core/src/utils/globalBucket/index.js:75:28)
    at getOrCreateDefaultBucket (/Users/xxx/.serverless/releases/4.4.7/sf-core/src/utils/globalBucket/index.js:38:24)
    at <anonymous> (/Users/xxx/.serverless/releases/4.4.7/sf-core/src/lib/compose/state.js:256:16)
    at getOrCreateStateStore (/Users/xxx/.serverless/releases/4.4.7/sf-core/src/lib/compose/state.js:254:42)
    at resolveStateStore (/Users/xxx/.serverless/releases/4.4.7/sf-core/src/lib/compose/state.js:105:40)
    at runCompose (/Users/xxx/.serverless/releases/4.4.7/sf-core/src/lib/runners/compose.js:103:50)
    at route (/Users/xxx/.serverless/releases/4.4.7/sf-core/src/lib/router.js:164:12)
    at Object.run2 (/Users/xxx/.serverless/releases/4.4.7/sf-core/src/index.js:45:3)

For help, try the following:
  • Run the command again with the "--debug" option
  • Run "serverless support"
  • Review the docs: https://www.serverless.com/framework/docs/
```

**Comment by czubocha** [comment]
Hey @kesavab 
> What I don't understand is why is it creating/accessing resources in us-east-1 region? I don't have access in that region.

> From docs, I see that as part of V4, there is a new shared state etc. Is the issue due to the shared state being created in us-east-1 region? If yes, is there anyway I can use zero setup config with just region?

Serverless Framework stores information about the state bucket in an SSM parameter in the `us-east-1` AWS region by default (when using zero-config). Unfortunately, it’s not possible to change only the region for this SSM parameter. However, you can specify a custom state bucket by using the `state` field in your config, as outlined in [the docs](https://www.serverless.com/framework/docs/guides/state#using-a-custom-s3-bucket). If you choose to use a preexisting S3 bucket, ensure that versioning is enabled.

> Also how is this S3 bucket used for state different from the deployment bucket already created by serverless compose? And if I create a new bucket for state what happens to the existing deployment bucket? Hope it will not cause any confusion and recreate resources during deployment?

State bucket is a new feature and serves a different purpose than the deployment bucket. Your existing deployment bucket will continue to function as it is, and using a state bucket will not affect or recreate your deployment bucket or your resources.

**Comment by kesavab** [comment]
@czubocha Now I am on v4.4.10. I created a bucket with versioning enabled and used it with custom config setup as below in sls compose yaml
```
state: s3-state-resolver
stages:
  default:
    resolvers:
      my-aws-account:
        type: aws
        region: eu-west-1
        s3-state-resolver:
          type: s3
          region: eu-west-1
          bucketName: ${opt:stage,'dev'}-sls-state-bucket
``` 

With this I get an error 

```
s:cli-error-handler: Error: An error occurred while checking versioning for bucket "xxx-dev-sls-state-bucket": An error occurred while checking versioning for bucket "xxx-dev-sls-state-bucket": Access Denied
    at <anonymous> (/Users/xxx/.serverless/releases/4.4.10/sf-core/src/lib/compose/state.js:247:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at checkExistingS3StateBucket (/Users/xxx/.serverless/releases/4.4.10/sf-core/src/lib/compose/state.js:241:29)
    at getOrCreateStateStore (/Users/xxx/.serverless/releases/4.4.10/sf-core/src/lib/compose/state.js:335:7)
    at resolveStateStore (/Users/xxx/.serverless/releases/4.4.10/sf-core/src/lib/compose/state.js:138:40)
    at runCompose (/Users/xxx/.serverless/releases/4.4.10/sf-core/src/lib/runners/compose.js:103:50)
    at route (/Users/xxx/.serverless/releases/4.4.10/sf-core/src/lib/router.js:167:12)
    at Object.run2 (/Users/xxx/.serverless/releases/4.4.10/sf-core/src/index.js:45:3)
    at run3 (/Users/xxx/.serverless/releases/4.4.10/sf-core/bin/sf-core.js:33:3)

✖ Error: An error occurred while checking versioning for bucket "xxx-dev-sls-state-bucket": An error occurred while checking versioning for bucket "xxx-dev-sls-state-bucket": Access Denied
    at <anonymous> (/Users/xxx/.serverless/releases/4.4.10/sf-core/src/lib/compose/state.js:247:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at checkExistingS3StateBucket (/Users/xxx/.serverless/releases/4.4.10/sf-core/src/lib/compose/state.js:241:29)
    at getOrCreateStateStore (/Users/xxx/.serverless/releases/4.4.10/sf-core/src/lib/compose/state.js:335:7)
    at resolveStateStore (/Users/xxx/.serverless/releases/4.4.10/sf-core/src/lib/compose/state.js:138:40)
    at runCompose (/Users/xxx/.serverless/releases/4.4.10/sf-core/src/lib/runners/compose.js:103:50)
    at route (/Users/xxx/.serverless/releases/4.4.10/sf-core/src/lib/router.js:167:12)
    at Object.run2 (/Users/xxx/.serverless/releases/4.4.10/sf-core/src/index.js:45:3)
    at run3 (/Users/xxx/.serverless/releases/4.4.10/sf-core/bin/sf-core.js:33:3)
```

I am running `serverless print --debug  --stage dev` command with aws creds set to a role that has admin privileges.
