### ISSUE TITLE
serverless function deploy is failing

### ISSUE THREAD

**Issue by gravisrinivas** [serverless/serverless#1375]
when i am running he command "sls function deploy -s xxxx -r us-east-1 -a", i am getting error as 

Error: EMFILE: too many open files, open 'E:\xxxxxxxxx\xxxx\xxxxxxx\ProjectName\_meta\_tmp\groupusers@1466594578265\base-authorizer\event.json'
  at Error (native)
  at Object.fs.openSync (fs.js:634:18)
  at Object.fs.readFileSync (fs.js:502:33)
  at Walker.<anonymous> (C:\Users\xxxxxxx\AppData\Roaming\npm\node_modules\serverless\lib\actions\CodeDeployLambda.js:123:35)
  at emitOne (events.js:96:13)
  at Walker.emit (events.js:188:7)
  at readableAddChunk (_stream_readable.js:172:18)
  at Walker.Readable.push (_stream_readable.js:130:10)
  at C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\serverless\node_modules\klaw\src\index.js:30:43
  at FSReqWrap.oncomplete (fs.js:117:15)

Does any one has any idea on this?

**Comment by zallek** [comment]
same problem there

**Comment by gravisrinivas** [comment]
reinstalling the serverless has solved the problem for me
