### ISSUE TITLE
attempting to run a non existing command is not handled

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#1379]
```
Eslams-MacBook-Pro:test-projects eslam$ sldev whate
 _______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v1.0.0
`-------'

  Type Error ---------------------------------------------
 
     Cannot read property 'options' of undefined
 
  Stack Trace --------------------------------------------
 
TypeError: Cannot read property 'options' of undefined
    at PluginManager.validateOptions (/Users/eslam/serverless-stuff/serverless/lib/classes/PluginManager.js:31:48)
    at PluginManager.run (/Users/eslam/serverless-stuff/serverless/lib/classes/PluginManager.js:50:10)
    at Serverless.run (/Users/eslam/serverless-stuff/serverless/lib/Serverless.js:64:33)
    at /Users/eslam/serverless-stuff/serverless/bin/serverless:19:50
    at tryCatcher (/Users/eslam/serverless-stuff/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/eslam/serverless-stuff/serverless/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/eslam/serverless-stuff/serverless/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/eslam/serverless-stuff/serverless/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/eslam/serverless-stuff/serverless/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/Users/eslam/serverless-stuff/serverless/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/eslam/serverless-stuff/serverless/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/eslam/serverless-stuff/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
 
  Get Support --------------------------------------------
     Docs:          https://git.io/voP4S
     Bugs:          https://git.io/voP45
 
     Please report this error. We think it might be a bug.
 
Eslams-MacBook-Pro:test-projects eslam$ 
```

**Comment by pmuens** [comment]
Hmm yes. Might be something in the PluginManager. It works this way that the PluginManager looks into all available commands and checks the options for that command shortly after that.

I need to throw an error if the command is not available. Will look into it!

**Comment by pmuens** [comment]
Solved with https://github.com/serverless/serverless/commit/008df83d4294839a493980e1bb5c0605cfcb4bd4
