### ISSUE TITLE
NEW ap-southeast-2 Region Support

### ISSUE THREAD

**Issue by vanerleo** [serverless/serverless#1387]
New Region just announced :  ap-southeast-2
please add

**Comment by tobyhede** [comment]
woot!

**Comment by dcroswell** [comment]
I tried modifying the ProviderAws.js and Region.js files which will allow you to create the cloud front but when you go to deploy, you get an error.   Can't wait to have my code closer to home!

**Comment by vanerleo** [comment]
yeah, i did the same thing , and got the same.

As regions are added all the time, the need for a release for the full project should not rely on a new region added. This should probably be a separate json file, where all can add or remove regions

**Comment by silver2k** [comment]
I need this in my life. I'll look into it tonight if no one else is...

**Comment by tobyhede** [comment]
@dcroswell What was the error?

**Comment by dcroswell** [comment]
@tobyhede C:\Users\me\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:61
fn = function () { throw arg; }; ^
TypeError: Cannot read property 'toLowerCase' of undefined
at C:\Users\AppData\Roaming\npm\node_modules\serverless\lib\Serializer.js:395:168
From previous event:
at Region.deserializeRegion (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Serializer.js:389:27)
at Region.deserialize (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Serializer.js:27:57)
at Region.load (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Region.js:23:19)
at C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Serializer.js:345:25
From previous event:
at Stage.deserializeStage (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Serializer.js:335:10)
at Stage.deserialize (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Serializer.js:27:57)
at Stage.load (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Stage.js:26:19)
at C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Serializer.js:127:32
at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
at C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Serializer.js:103:14
From previous event:
at Project.deserializeProject (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Serializer.js:92:10)
at Project.deserialize (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Serializer.js:27:57)
at Project.load (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Project.js:36:19)
at C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:87:35
at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
at Serverless.init (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:79:10)
at Object.<anonymous> (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\bin\serverless:17:12)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain (module.js:441:10)
at startup (node.js:139:18)
at node.js:968:3

**Comment by tobyhede** [comment]
Thanks @dcroswell I will check it out.

**Comment by silver2k** [comment]
Just modified the same files - and it worked fine eventually. (I had the same error as about - but only because I types southwest rather than southeast)
Try removing `aws-sdk` from the the serverless node_modules folder and installing the latest SDK globally. This might do the trick...

**Comment by egeland** [comment]
Looking forward to being able to try `serverless` in APSE2.. :smile:

**Comment by vanerleo** [comment]
no luck, i've updated the global aws-sdk to latest as well 

when creating a new region :
`
Serverless: Creating region "ap-southeast-2" in stage "dev"...  
Serverless: Deploying resources to stage "dev" in region "ap-southeast-2" via Cloudformation (~3 minutes)...  
~/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
ServerlessError: ServerlessError: Stack:arn:aws:cloudformation:ap-southeast-2:*********:stack/api-dev-r/****** is in UPDATE_ROLLBACK_FAILED state and can not be updated.
  at new ServerlessError (~/.npm-packages/lib/node_modules/serverless/lib/Error.js:17:11)
  at ResourcesDeploy.<anonymous> (~/.npm-packages/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:241:25)
  at ResourcesDeploy.tryCatcher (~/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
  at Promise._settlePromiseFromHandler (~/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:504:31)
  at Promise._settlePromise (~/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:561:18)
  at Promise._settlePromise0 (~/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:606:10)
  at Promise._settlePromises (~/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:681:18)
  at Async._drainQueue (~/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:16)
  at Async._drainQueues (~/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:148:10)
  at Immediate.Async.drainQueues [as _onImmediate] (~/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
  at tryOnImmediate (timers.js:543:15)
  at processImmediate [as _immediateCallback] (timers.js:523:5)
`


and after that any sls commands fail. with error:
`
serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; }; 
TypeError: Cannot read property 'toLowerCase' of undefined
`

**Comment by dcroswell** [comment]
+1 Same exact problem, even if I try and create a new serverless project. 

I can create the project but then, "serverless function create" will result in the same error as vanerleo gets above.

**Comment by dcroswell** [comment]
$ serverless function create base
c:\Users\me\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:61
        fn = function () { throw arg; };
                           ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at c:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Serializer.js:395:168
From previous event:
    at Region.deserializeRegion (c:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Serializer.js:389:27)
    at Region.deserialize (c:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Serializer.js:27:57)
    at Region.load (c:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Region.js:23:19)
    at c:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Serializer.js:345:25
From previous event:
    at Stage.deserializeStage (c:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Serializer.js:335:10)
    at Stage.deserialize (c:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Serializer.js:27:57)
    at Stage.load (c:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Stage.js:26:19)
    at c:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Serializer.js:127:32
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at c:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Serializer.js:103:14
From previous event:
    at Project.deserializeProject (c:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Serializer.js:92:10)
    at Project.deserialize (c:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Serializer.js:27:57)
    at Project.load (c:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Project.js:36:19)
    at c:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:87:35
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Serverless.init (c:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:79:10)
    at Object.<anonymous> (c:\Users\me\AppData\Roaming\npm\node_modules\serverless\bin\serverless:17:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by dcroswell** [comment]
Found in my _meta/variables/s-variables-common.js I had a reference to region. I will delete it later and try again and report my results.

**Comment by vanerleo** [comment]
@dcroswell  it generates : _meta/s-variables-***-apsoutheast-2  ( for each deployed stage) 
the only way to fix  'toLowerCase' of undefined  .. to remove those files

**Comment by vanerleo** [comment]
so whats the status of this?

**Comment by tengis** [comment]
Hi, Could not referenced this issue on pull request. But this #1423 will fix that issue

**Comment by isp0000** [comment]
Is there any workaround available before this is released? Like deploy to supported region and then migrate the CloudFormation to the ap-southeast-2?

**Comment by vanerleo** [comment]
i've applied the change : https://github.com/serverless/serverless/pull/1423/files#r68693900
to my local box

**Comment by silver2k** [comment]
Me too... works fine.

**Comment by flomotlik** [comment]
As we've switched to Cloudformation in the latest release and this works fine on any region I'm going to close this issue.
