### ISSUE TITLE
Promise error / warning on server create

### ISSUE THREAD

**Issue by mpuittinen** [serverless/serverless#1430]
I've started getting systematically (every project create / install) the following warning / error (the operations seems to succeed despite the error). I'm running serverless 0.5.6 on Node 4.4.5.

Serverless: Creating region "ap-northeast-1" in stage "dev"...
Serverless: Deploying resources to stage "dev" in region "ap-northeast-1" via Cloudformation (~3 minutes)...
Serverless: Successfully deployed "dev" resources to "ap-northeast-1"
Warning: a promise was created in a handler but was not returned from it
    at Region.serializeRegion (/Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/Serializer.js:413:27)
    at Region.serialize (/Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/Serializer.js:23:55)
    at Region.save (/Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/Region.js:27:19)
    at /Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:230:32
From previous event:
    at ResourcesDeploy.<anonymous> (/Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:226:24)
From previous event:
    at /Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:187:18
From previous event:
    at ResourcesDeploy._deployResources (/Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:158:12)
From previous event:
    at ResourcesDeploy.resourcesDeploy (/Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:72:12)
From previous event:
    at /Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/Serverless.js:211:25
    at Array.reduce (native)
    at Serverless._execute (/Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/Serverless.js:210:26)
    at Object.actions.(anonymous function) [as resourcesDeploy] (/Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/Serverless.js:429:20)
    at RegionCreate._deployResources (/Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/actions/RegionCreate.js:151:24)
From previous event:
    at RegionCreate.regionCreate (/Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/actions/RegionCreate.js:79:12)
From previous event:
    at /Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/Serverless.js:211:25
    at Array.reduce (native)
    at Serverless._execute (/Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/Serverless.js:210:26)
    at Object.actions.(anonymous function) [as regionCreate] (/Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/Serverless.js:429:20)
    at StageCreate._createRegion (/Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/actions/StageCreate.js:298:24)
From previous event:
    at StageCreate.stageCreate (/Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/actions/StageCreate.js:85:12)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at /Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/Serverless.js:211:25
    at Array.reduce (native)
    at Serverless._execute (/Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/Serverless.js:210:26)
    at Object.actions.(anonymous function) [as stageCreate] (/Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/Serverless.js:429:20)
    at ProjectInit._createStageAndRegion (/Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/actions/ProjectInit.js:265:24)
    at /Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:43:10
From previous event:
    at ProjectInit.projectInit (/Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/actions/ProjectInit.js:93:10)
From previous event:
    at /Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/Serverless.js:211:25
    at Array.reduce (native)
    at Serverless._execute (/Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/Serverless.js:210:26)
    at Object.actions.(anonymous function) [as projectInit] (/Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/Serverless.js:429:20)
    at ProjectCreate.createProject (/Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/actions/ProjectCreate.js:75:24)
From previous event:
    at /Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/Serverless.js:186:31
    at Array.reduce (native)
    at /Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/Serverless.js:185:32
From previous event:
    at Serverless._execute (/Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/Serverless.js:183:12)
    at Serverless.actions.(anonymous function) (/Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/Serverless.js:429:20)
    at Serverless.command (/Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/lib/Serverless.js:398:38)
    at /Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/bin/serverless:19:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Object.<anonymous> (/Users/mikael/.nvm/versions/node/v4.4.5/lib/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

Serverless: Successfully created region "ap-northeast-1" within stage "dev"
Serverless: Successfully created stage "dev"
Serverless: Successfully initialized project "testproject3"

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
