### ISSUE TITLE
Security Token Included In the Request is Invalid

### ISSUE THREAD

**Issue by araines** [serverless/serverless#1518]
##### Expected Behavior:

Serverless to create resources for me at the start of a project

##### Actual Behavior:

```
Serverless: Deploying resources to stage "dev" in region "us-east-1" via Cloudformation (~3 minutes)...
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

ServerlessError: ServerlessError: The security token included in the request is invalid
```

I'm using MFA with the following environment variables already available within the session:

```
$AWS_ACCESS_KEY_ID
$AWS_SECRET_ACCESS_KEY
$AWS_SESSION_TOKEN
```

So I understood that Serverless would pick those up?

I know the environment is working fine, because the AWS CLI tool works fine.

##### Stack-Trace (Optional):

**Comment by araines** [comment]
Ignore me - I haven't got the permissions set up correctly on the AWS end - many apologies I'll get a coffee before reporting bugs in future!

**Comment by araines** [comment]
Reopening this  - I've added full access to the user token and I'm still having the same problem.  I suspect this is actually down to something I'm doing (or not doing), but I'd like to better understand how the security model works.  Based on the documentation I've read I believe it should work.

**Comment by objecteer** [comment]
I created an IAM policy to allow all actions of AWS CloudFormation and attached that policy to the user, and the problem was resolved.

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.

**Comment by gabek** [comment]
@flomotlik I'm getting this same error with 1.0.2.

```
  Serverless Error ---------------------------------------

     The security token included in the request is invalid.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Infomation -----------------------------
     OS:                 darwin
     Node Version:       6.7.0
     Serverless Version: 1.0.2
```

**Comment by brunobc182** [comment]
Same problem here:

`  Error --------------------------------------------------

     ServerlessError: ServerlessError: The security token
     included in the request is invalid.

     For debugging logs, run again after setting SLS_DEBUG env var.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.

  Your Environment Infomation -----------------------------
     OS:                 darwin
     Node Version:       4.6.0
     Serverless Version: 1.0.2`

**Comment by flomotlik** [comment]
@gabek @brunobc182 are those tokens valid ones to talk to AWS? Can you try the same ones with the AWS CLI or try with new ones?

**Comment by TimHeckel** [comment]
I've gotten the same error, and I did run some functions via my AWS credentials using the AWS CLI and things appear to be working as expected. I can try to dig in more -- in the interim, this is the stack trace, if it's any help:

    Error: ServerlessError: ServerlessError: The security token included in the request is invalid.
    at module.exports.logError.words.forEach (/Users/tim/.nvm/versions/v4.4.5/lib/node_modules/serverless/lib/classes/Error.js:82:11)
    at /Users/tim/.nvm/versions/v4.4.5/lib/node_modules/serverless/bin/serverless:20:15
    at tryCatcher (/Users/tim/.nvm/versions/v4.4.5/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/tim/.nvm/versions/v4.4.5/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/tim/.nvm/versions/v4.4.5/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/tim/.nvm/versions/v4.4.5/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/tim/.nvm/versions/v4.4.5/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/Users/tim/.nvm/versions/v4.4.5/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/tim/.nvm/versions/v4.4.5/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/tim/.nvm/versions/v4.4.5/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by bahador** [comment]
I've got the same error as well. I'm following the videos on YouTube from the official Serverless account.

```
Error: ServerlessError: ServerlessError: The security token included in the request is invalid.
    at module.exports.logError (/usr/local/lib/node_modules/serverless/lib/classes/Error.js:95:11)
    at /usr/local/lib/node_modules/serverless/bin/serverless:26:3
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at /usr/local/lib/node_modules/serverless/bin/serverless:24:9
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:27:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
     Please report this error. We think it might be a bug.
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       5.11.0
     Serverless Version: 1.9.0
```

**Comment by pmuens** [comment]
@bahador thanks for reporting!

🤔 Here are some links which might help:
- https://github.com/awslabs/amazon-kinesis-scaling-utils/issues/5
- https://forums.aws.amazon.com/thread.jspa?threadID=86570
- https://github.com/hashicorp/terraform/issues/2693
- http://stackoverflow.com/questions/34582318/how-can-i-resolve-the-error-the-security-token-included-in-the-request-is-inval

Could you try to re-generate the security credentials and try again? Thanks!

**Comment by bahador** [comment]
Thanks for the links. I'll try to take a look at them tomorrow.
I already regenerated the credentials in IAM three times. I got the same error each time.

I'll report back when I find out more.

Looking forward to using Serverless.

**Comment by bahador** [comment]
@pmuens I resolved the issue. My environment was polluted from a previous attempt to get Serverless working a few weeks ago and I totally forgot about it. I also had not fully confirmed my AWS account.

**Comment by pmuens** [comment]
Thanks fro getting back @bahador 👍 

Glad to hear that everything is resolved and working fine 💯

**Comment by MrPeker** [comment]
I had the same problem. I tried `$ export AWS_PROFILE="default"` command and resolved my issue.

**Comment by Kiran01bm** [comment]
I had the same error in spite of using - Correct credentials with Proper permission. The --verbose was not providing anything extra.

So assuming:
1. You have the correct credentials i.e Access Key ID and Secret.
2. The IAM user associated with creds from #1 has the required permissions

Passing the credentials via Environment variables "export AWS_SECRET_ACCESS_KEY=" and "export AWS_ACCESS_KEY_ID=" **- DID NOT WORK**

Now configuring the credentials file with the same KEY and SECRET via "serverless config credentials --provider aws --key YOURKEY --secret YOURSECRET" -- **WORKED FINE**

No idea as to why it fails with the environment variables approach.

**Comment by saurabhpal16** [comment]
ServerlessError: The security token included in the request is invalid. 
   

Serverless Error --------------------------------------- 
  
  ServerlessError: The security token included in the request is invalid. 
  
  Stack Trace -------------------------------------------- 
  
ServerlessError: ServerlessError: The security token included in the request is invalid. 
    at AwsDeploy.BbPromise.bind.then.catch (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:94:15) 
From previous event: 
    at AwsDeploy.createStack (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:85:13) 
From previous event: 
    at Object.aws:deploy:deploy:createStack [as hook] (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:100:10) 
    at BbPromise.reduce (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:422:55) 
From previous event: 
    at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:422:22) 
    at PluginManager.spawn (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:440:17) 
    at AwsDeploy.BbPromise.bind.then (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:93:48) 
From previous event: 
    at Object.deploy:deploy [as hook] (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:89:10) 
    at BbPromise.reduce (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:422:55) 
From previous event: 
    at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:422:22) 
    at PluginManager.run (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:453:17) 
    at variables.populateService.then (/usr/lib/node_modules/serverless/lib/Serverless.js:110:33) 
    at runCallback (timers.js:794:20) 
    at tryOnImmediate (timers.js:752:5) 
    at processImmediate [as _immediateCallback] (timers.js:729:5) 
From previous event: 
    at Serverless.run (/usr/lib/node_modules/serverless/lib/Serverless.js:97:6) 
    at serverless.init.then (/usr/lib/node_modules/serverless/bin/serverless:43:28) 
    at /usr/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16 
    at /usr/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10 
    at FSReqWrap.oncomplete (fs.js:135:15) 
From previous event: 
    at initializeErrorReporter.then (/usr/lib/node_modules/serverless/bin/serverless:43:6) 
    at runCallback (timers.js:794:20) 
    at tryOnImmediate (timers.js:752:5) 
    at processImmediate [as _immediateCallback] (timers.js:729:5) 
From previous event: 
    at /usr/lib/node_modules/serverless/bin/serverless:28:46 
    at Object.<anonymous> (/usr/lib/node_modules/serverless/bin/serverless:65:4) 
    at Module._compile (module.js:652:30) 
    at Object.Module._extensions..js (module.js:663:10) 
    at Module.load (module.js:565:32) 
    at tryModuleLoad (module.js:505:12) 
    at Function.Module._load (module.js:497:3) 
    at Function.Module.runMain (module.js:693:10) 
    at startup (bootstrap_node.js:188:16) 
    at bootstrap_node.js:609:3 
  
  Get Support -------------------------------------------- 
     Docs:          docs.serverless.com 
     Bugs:          github.com/serverless/serverless/issues 
     Issues:        forum.serverless.com 
  
  Your Environment Information --------------------------- 
     OS:                     linux 
     Node Version:           8.10.0 
     Serverless Version:     1.43.0 
  
 
[Container] 2019/06/04 06:41:41 Command did not exit successfully cd $GOPATH/src/adminservice && serverless deploy --stage put exit status 1 
[Container] 2019/06/04 06:41:41 Phase complete: BUILD State: FAILED 
[Container] 2019/06/04 06:41:41 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: cd $GOPATH/src/adminservice && serverless deploy --stage put. Reason: exit status 1

**Comment by saurabhpal16** [comment]
I am facing issue to make serverless deploy, can someone pls guide me.

ServerlessError: The security token included in the request is invalid.

**Comment by iHani** [comment]
This is how I solved it. If you configured your serverless with a `--profile` flag like this:

`sls config credentials --profile <PROFILE_NAME> --provider ... --key ... --secret ...`

then this should solve it:
`export AWS_PROFILE="<PROFILE_NAME>"`

If you didn't specify a `--profile` then the default profile should work as MrPeker mentioned
`export AWS_PROFILE="default"`

**Comment by danielo515** [comment]
> I had the same problem. I tried `$ export AWS_PROFILE="default"` command and resolved my issue.

This was exactly my problem. Isn't any solution that does not involve using environment variables for selecting the profile?

**Comment by simsketch** [comment]
@iHani I think you need to specify --aws-profile and not --profile, because I accidentally deployed to the wrong profile using --profile
https://serverless.com/framework/docs/providers/aws/guide/credentials#using-the-aws-profile-option

**Comment by Nuc94** [comment]
I encountered the same issue and finally solved it by specifying in the serverless.yml the same region I had in my AWS webpage.

**Comment by adminy** [comment]
when defining `serverless.service.functions[functionName].layers = [  { Ref: 'ADefinedLambdaLayer' } ]`
and `serverless.service.layers.ADefinedLambdaLayer = { package: { artifact: '../somefile.zip' } }`

```bash
sls package


Packaging sls-py-req-test for stage dev (us-east-1)
Environment: darwin, node 20.5.1, framework 3.30.1 (local), plugin 6.2.3, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
The security token included in the request is invalid.
```

Why is it trying to make a request before checking local definitions?

**Comment by Cconkers** [comment]
delete from you provider config on .yml the line of region

region: us-east-1

save file and try to deploy again

**Comment by matiasbeckerle** [comment]
If you have 2FA enabled for your AWS account then regardless of setting the right values for `aws_access_key_id` and `aws_secret_access_key` you also have to set an additional `aws_session_token` in the `~/.aws/credentials` file.
