### ISSUE TITLE
cli commands stall on 'select a stage'

### ISSUE THREAD

**Issue by rogueleaderr** [serverless/serverless#1542]
Bug Report Template -----------------------------------------------

##### Serverless Framework Version: 
0.5.6

##### Operating System: 
OSX

##### Expected Behavior: 
do `sls function run` and get Interactive stage selection

##### Actual Behavior: 
CLI stalls waiting for input. Hitting enter causes an exit w/ error message.

##### Stack-Trace (Optional):
 ```

Serverless: Function Run - Choose a stage:
/usr/local/lib/node_modules/serverless/lib/utils/cli.js:386
      if (Select.state.choices[Select.state.index - 1].action
                                                      ^

TypeError: Cannot read property 'action' of undefined
    at ReadStream.keypressHandler (/usr/local/lib/node_modules/serverless/lib/utils/cli.js:386:55)
    at emitTwo (events.js:106:13)
    at ReadStream.emit (events.js:191:7)
    at emitKey (/usr/local/lib/node_modules/serverless/node_modules/keypress/index.js:406:12)
    at ReadStream.onData (/usr/local/lib/node_modules/serverless/node_modules/keypress/index.js:48:14)
    at emitOne (events.js:96:13)
    at ReadStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at ReadStream.Readable.push (_stream_readable.js:135:10)
    at TTY.onread (net.js:542:20)

```

##### Additional Details:

Discussion template  ----------------------------------------------

##### Discussion:

This is on a brand new Macbook with very little command. I normally run zsh but I tried running in bash in default apple terminal with an extremely minimal .bashrc and still see the problem. 

It's only happening with a pre-existing project from my team I'm starting on. It works for my coworker. Also I was able to create a new project via the tutorial and the command runs there correctly. Mysterious but blocking.

**Comment by rogueleaderr** [comment]
I figured it out...I cloned the repo from Github so I was missing the necessary _meta directories. I had my coworker send them and now it works.

So technically this is user error, but it'll probably be a common one so a more helpful error message would be nice.
