### ISSUE TITLE
Cant find AWS credentials

### ISSUE THREAD

**Issue by slitskevich** [serverless/serverless#1569]
I want to start working with existing SLS project which I get from GitHub. The project already has all the necessary stages so I don't run "project init" on it.
When I try to deploy a function into specific stage I get the error: "Cant find AWS credentials". I have proper keys in ~/.aws/credentials. I also tried to duplicate them in admin.env in the project root folder - but it didn't help.

Thanks,
Slava

Bug Report Template -----------------------------------------------

##### Stack-Trace (Optional):

Serverless: Deploying the specified functions in "####" to the following regions: us-east-1  
Serverless: ------------------------  
Serverless: Failed to deploy the following functions in "####" to the following regions:  
Serverless: us-east-1 ------------------------  
Serverless:   #############: Cant find AWS credentials  
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

ServerlessError: Function Deployment Failed
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/Error.js:17:11)
    at FunctionDeploy.<anonymous> (/usr/local/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:126:19)
    at next (/usr/local/lib/node_modules/serverless/node_modules/fs-extra/node_modules/rimraf/rimraf.js:74:7)
    at FSReqWrap.CB [as oncomplete] (/usr/local/lib/node_modules/serverless/node_modules/fs-extra/node_modules/rimraf/rimraf.js:110:9)
From previous event:
    at FunctionDeploy.functionDeploy (/usr/local/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:105:10)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:186:31
    at Array.reduce (native)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:185:32
From previous event:
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:183:12)
    at Serverless.actions.(anonymous function) (/usr/local/lib/node_modules/serverless/lib/Serverless.js:429:20)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:398:38)
    at /usr/local/lib/node_modules/serverless/bin/serverless:19:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

Feature Request Template ------------------------------------------

##### Benefits:

* Benefit one...

##### Drawbacks:

* Drawback one...

##### Additional Details:

Discussion template  ----------------------------------------------

**Comment by slitskevich** [comment]
I solved the issue by setting AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables. 
Apparently SLS ignores credentials in my ~/.aws/credentials file. Although when I ran "sls project init" it asks my to choose credentials profile and offers me the list of profiles specified in the file.

I'd expect it to work without environment variables

**Comment by flomotlik** [comment]
@slitskevich In Version 1 of the Framework we're using the .aws/credentials file, so it should be working out of the box. Closing this issue as its fixed in 1.0
