### ISSUE TITLE
e.message.split is not a function

### ISSUE THREAD

**Issue by johey** [serverless/serverless#1649]
Trying out serverless for the first time, following the guide here: http://blog.serverless.com/serverless-v1-0-alpha1-announcement/

First thing, it seems like the syntax has changed for the create function, as it requires --template. So, trying:

    serverless create --name first-service --template aws-nodejs
    serverless deploy

then there is this error:

##### Serverless Framework Version: 
1.0.0-alpha.2

##### Operating System: 
Windows 10 64bit

##### Expected Behavior:
Actually, I don't know.

##### Actual Behavior:
    $ serverless deploy

      Serverless Error ---------------------------------------

      Type Error ---------------------------------------------

         e.message.split is not a function

         For debugging logs, run again after setting SLS_DEBUG env var.

      Get Support --------------------------------------------
         Docs:          v1.docs.serverless.com
         Bugs:          github.com/serverless/serverless/issues

         Please report this error. We think it might be a bug.

**Comment by eahefnawy** [comment]
@johey This is a bug in our error handling code. Basically something went wrong and our handling made it even worse. This has been fixed and will be released soon.

Not sure if this is the issue, but we've dropped support for the `name` option. So it should just be:

```
serverless create --template aws-nodejs
```
After that you could rename your service to whatever you like by editing the `serverless.yaml` file. If you dont, your AWS account might conflict with services you created/deployed earlier with the default name. Then you can deploy safely and I think it should work.

Hope this helps 🙌

**Comment by jch254** [comment]
I'm experiencing this also on a fresh EC2 instance running Amazon Linux. It worked last night on OSX. I tried moving the existing project that worked on OSX to Amazon Linux - it fails to deploy. I then tried a new project which also fails to deploy. Both failures give e.message.split is not a function. 

[ec2-user@ip-172-31-56-51 test]$ serverless deploy

  Serverless Error ---------------------------------------


  Type Error ---------------------------------------------

     e.message.split is not a function

     For debugging logs, run again after setting SLS_DEBUG env var.

  Stack Trace --------------------------------------------

TypeError: e.message.split is not a function
    at module.exports.logError.words.forEach (/home/ec2-user/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/lib/classes/Error.js:29:27)
    at /home/ec2-user/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/bin/serverless:19:15
    at tryCatcher (/home/ec2-user/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ec2-user/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/home/ec2-user/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/home/ec2-user/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/home/ec2-user/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:681:18)
    at Async._drainQueue (/home/ec2-user/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/ec2-user/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ec2-user/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by jch254** [comment]
The reason I was building on an Amazon Linux was that sometimes node_modules may have to be compiled against an Amazon Linux image on EC2 in order for the compiled addons to be usable on their Lambda service. I was able to copy the built packages from the EC2 instance and deploy with Serverless on OSX which worked.

**Comment by pmuens** [comment]
FYI: This is the corresponding PR which fixes the issue: https://github.com/serverless/serverless/pull/1623

**Comment by Jorenm** [comment]
So how does one set the SLS_DEBUG env var? I can't find anything that says how to do that.

**Comment by jch254** [comment]
@Jorenm I just used export SLS_DEBUG=true - http://www.gnu.org/software/bash/manual/bash.html#index-export

**Comment by Jorenm** [comment]
I'm on windows so I couldn't use that exact command. Adding "@set SLS_DEBUG=true" to cmder's init.bat did it though.

Thanks for pointing me in the right direction.
