### ISSUE TITLE
Serverless deploy errors out.

### ISSUE THREAD

**Issue by Jorenm** [serverless/serverless#1701]
##### Stack-Trace (Optional):

TypeError: e.message.split is not a function
    at module.exports.logError.words.forEach (C:\Users\Ozymandias\AppData\Roaming\npm\node_modules\serverless\lib\classes\Error.js:29:27)
    at C:\Users\Ozymandias\AppData\Roaming\npm\node_modules\serverless\bin\serverless:19:15
    at tryCatcher (C:\Users\Ozymandias\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Ozymandias\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (C:\Users\Ozymandias\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (C:\Users\Ozymandias\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (C:\Users\Ozymandias\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:681:18)
    at Async._drainQueue (C:\Users\Ozymandias\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\Users\Ozymandias\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Ozymandias\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by eahefnawy** [comment]
This has been fixed and will be released with Beta 😊

**Comment by flomotlik** [comment]
@Jorenm in case this isn't fixed with the beta for you please let us know. I'm closing in the meantime
