### ISSUE TITLE
HTTP Events, cannot add methods for root `/`endpoint

### ISSUE THREAD

**Issue by shortjared** [serverless/serverless#1738]
##### Serverless Framework Version:

1.0.0-alpha.2
##### Operating System:

OSX 10.11.6
##### Expected Behavior:

I would expect that I would be able to somehow deploy a method against the root `/` endpoint. Seems like validations block this from happening? Either that or I missed in the docs how to handle this.
##### Actual Behavior:

``` yaml
functions:
  render:
    handler: handler.render
    timeout: 6
    events:
      - http:
          path: /
          method: get
```

```
♪ sls deploy
Serverless: Zipping service...
Serverless: Removing old service versions...
Serverless: Uploading .zip file to S3...
Serverless: Updating Stack...

  Validation Error ---------------------------------------

     Template format error: Unresolved resource dependencies
     [ResourceApigEvent] in the Resources block of the template
```

**Comment by flomotlik** [comment]
@shortjared could you show us the part of the cloud formation template causing this?

**Comment by jatsrt** [comment]
What's the best way to get the generated template?

```
ValidationError: Template format error: Unresolved resource dependencies [ResourceApigEvent] in the Resources block of the template
    at Request.extractError (/Users/jake/code/pocketlist/platform/realist/node_modules/serverless/node_modules/aws-sdk/lib/protocol/query.js:40:29)
    at Request.callListeners (/Users/jake/code/pocketlist/platform/realist/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/jake/code/pocketlist/platform/realist/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/jake/code/pocketlist/platform/realist/node_modules/serverless/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/Users/jake/code/pocketlist/platform/realist/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/jake/code/pocketlist/platform/realist/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/jake/code/pocketlist/platform/realist/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/jake/code/pocketlist/platform/realist/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/jake/code/pocketlist/platform/realist/node_modules/serverless/node_modules/aws-sdk/lib/request.js:617:12)
    at Request.callListeners (/Users/jake/code/pocketlist/platform/realist/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/jake/code/pocketlist/platform/realist/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/jake/code/pocketlist/platform/realist/node_modules/serverless/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/Users/jake/code/pocketlist/platform/realist/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/jake/code/pocketlist/platform/realist/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/jake/code/pocketlist/platform/realist/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/jake/code/pocketlist/platform/realist/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
```

**Comment by jatsrt** [comment]
It never attempts an actual update in cloud formation, it isn't passing validation from the AWS-SDK

**Comment by jatsrt** [comment]
OK: 

Bad:
```
"ResourceApigEventList": {
      "Type": "AWS::ApiGateway::Resource",
      "Properties": {
        "ParentId": {
          "Ref": "ResourceApigEvent"
        },
        "PathPart": "",
        "RestApiId": {
          "Ref": "RestApiApigEvent"
        }
      }
    },
```

Good:
```
"ResourceApigEventListUsers": {
      "Type": "AWS::ApiGateway::Resource",
      "Properties": {
        "ParentId": {
          "Fn::GetAtt": [
            "RestApiApigEvent",
            "RootResourceId"
          ]
        },
        "PathPart": "users",
        "RestApiId": {
          "Ref": "RestApiApigEvent"
        }
      }
    },
```

**Comment by jatsrt** [comment]
These values are from the update method in the aws/deploy/lib/updateStack.js

**Comment by jatsrt** [comment]
[Here is the culprit I think](https://github.com/serverless/serverless/blob/990d7c5a089c2047cdd342fca88f6c006c53c4c3/lib/plugins/aws/deploy/compile/events/apiGateway/lib/resources.js#L50)

Attempting a fix

**Comment by jatsrt** [comment]
It seems to have "support" for a root element, but you cannot "not" have a path, it fails in an earlier check, so the path "/" is the only one that will be validated.  However, that with the split, will short circuit the check:

```
if (resourcesArray.length === 0) {
        resourceParentId = '{ "Fn::GetAtt": ["RestApiApigEvent", "RootResourceId"] }';
      } else {
```

```
"/".split("/") = ["",""]
```

**Comment by nathanlenz** [comment]
I was at the same point you were and changed that line to:

```
const resourcesArray = (path === '/') ? [''] : path.split('/');
```

That seemed to have fixed the Resources section. But I still have a problem down in the outputs section.

```
"Endpoint1": {
            "Description": "Endpoint info",
            "Value": {
                "Fn::Join": ["", ["GET - https://", {
                    "Ref": "RestApiApigEvent"
                }, ".execute-api.us-east-1.amazonaws.com/dev//"]]
            }
        }
```

Notice the **/dev//** part.

**Comment by jatsrt** [comment]
So based on this from cloud formation:

> 	Resource's path part only allow a-zA-Z0-9._- and curly braces at the beginning and the end.

It appears it may not be possible to attach to the root path with cloud formation

**Comment by jatsrt** [comment]
So, not giving up on this, since the resource that is needed is the root resource.

This bit of code is trying to make a new resource, but it already exists as:
RootResourceId

**Comment by jatsrt** [comment]
[This would have to be dynamic](https://github.com/serverless/serverless/blob/990d7c5a089c2047cdd342fca88f6c006c53c4c3/lib/plugins/aws/deploy/compile/events/apiGateway/lib/methods.js#L115)

For cases where path === '/'

You would have to instead use:
```
"ResourceId" : { "Fn::GetAtt": ["RestApiApigEvent", "RootResourceId"] },
```

**Comment by jatsrt** [comment]
it's not pretty but it works

```
var methodTemplateJson = JSON.parse(methodTemplate);

          if (path === "/") {
            methodTemplateJson.Properties.ResourceId = {
              "Fn::GetAtt": ["RestApiApigEvent", "RootResourceId"]
            }
          }
```

**Comment by nathanlenz** [comment]
I got it working also (sorta). Using your changes. Plus, I had to set the PathPart of the unused resource to something in order to get it to take. It creates the unneeded resource, but actually attaches the lambda function to the / GET.

![screenshot 2016-08-05 14 30 36](https://cloud.githubusercontent.com/assets/847457/17448372/867517fe-5b19-11e6-9812-e792a28cdddb.png)

**Comment by jatsrt** [comment]
Ahh, yeah, I added a short circuit to the resources file.

```
if(path === "/") {
        return
      }
```

**Comment by nathanlenz** [comment]
Did you ever get it responding to the root of the API gateway domain, without the stage variable?

**Comment by jatsrt** [comment]
That's only possible though a custom domain mapping

**Comment by flomotlik** [comment]
@nathanlenz @jatsrt could you open a quick pull request to see your changes? This would make it easier to look into it and see what we can introduce or what other potential issues could lurk there.

Thanks for looking into this btw!

**Comment by davidjnelson** [comment]
Specify API Mappings for a Custom Domain Name

http://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains.html#how-to-custom-domains-mapping-console

Curious if this can go two levels deep on paths, ie: /dev/hello

If so, it could solve the entire problem.  If it can only go one level deep, then the fix involves the WIP @nathanlenz commit plus a custom domain name base path mapping it appears.

**Comment by davidjnelson** [comment]
Related question: are Custom Domain Mappings outside the scope of serverless and something that just has to be set up manually in the aws console?  Thanks!

**Comment by ac360** [comment]
Hi @davidjnelson, it's good to see you around the repo! 

V.1 is a CloudFormation abstraction and what I've heard is that CloudFormation does not support API Gateway custom domains at this time.

**Comment by davidjnelson** [comment]
Thanks Austen!  Ok sweet, good to know, thank you.  I'll post here if the deep level paths set up manually is a fix.  Cheers!

**Comment by davidjnelson** [comment]
Following these instructions certainly works: http://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains.html#how-to-custom-domains-mapping-console

The result if you use an empty base path and specify the environment you are working with is that you get:

https://<hostname>/<endpointname>

which does not have the environment as part of the path.  So, the pull request stripping the endpoint name along with following the Custom Domain Mapping guide should make root paths a reality!

**Comment by davidjnelson** [comment]
Does anyone know of good docs for the Method object when creating api gateway methods?  The docs at http://docs.aws.amazon.com/apigateway/api-reference/resource/method/ are lacking in examples, and appear to also be missing some properties.  Thanks :-)

**Comment by flomotlik** [comment]
@davidjnelson we've used the CF docs here: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html

Not sure if that covers everything you need

**Comment by pouledodue** [comment]
```
path: /
```
on four get, put , delete, post routes gives me
```
ServerlessError: Circular dependency between resources: [
ApiGatewayMethodPost, ApiGatewayMethodDelete, ApiGatewayResource, 
ApiGatewayMethodGet, ApiGatewayDeployment1473211661367, ApiGatewayMethodPut
]
```

**Comment by bbilger** [comment]
This prevents usage of greedy path variables on root level, too.

Using `{proxy+}` for `functions/events/http/path`in `serverless.yml` results in the follwing error:
```
  Type Error ---------------------------------------------
 
     path.split is not a function
 
     For debugging logs, run again after setting SLS_DEBUG env var.
 
  Stack Trace --------------------------------------------

TypeError: path.split is not a function
    at functionObject.events.forEach.event (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/apiGateway/lib/resources.js:38:39)
    at Array.forEach (native)
    at _.forEach (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/apiGateway/lib/resources.js:13:29)
    at /usr/lib/node_modules/serverless/node_modules/lodash/lodash.js:4917:15
    at baseForOwn (/usr/lib/node_modules/serverless/node_modules/lodash/lodash.js:2979:24)
    at /usr/lib/node_modules/serverless/node_modules/lodash/lodash.js:4886:18
    at Function.forEach (/usr/lib/node_modules/serverless/node_modules/lodash/lodash.js:9289:14)
    at AwsCompileApigEvents.compileResources (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/apiGateway/lib/resources.js:12:7)
    at AwsCompileApigEvents.tryCatcher (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
```

Using `/{proxy+}` for `functions/events/http/path` in `serverless.yml` results in the already mentioned error:
```
  Serverless Error ---------------------------------------
 
     Template format error: Unresolved resource dependencies
     [ApiGatewayResource] in the Resources block of the template
 
  Stack Trace --------------------------------------------

ServerlessError: Template format error: Unresolved resource dependencies [ApiGatewayResource] in the Resources block of the template
    at Response.req.send (/usr/lib/node_modules/serverless/lib/plugins/aws/index.js:137:20)
    at Request.<anonymous> (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:355:18)
    at Request.callListeners (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:670:12)
    at Request.callListeners (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
```

The only workaround is to use `api/{proxy+}` or something similar for `functions/events/http/path` in`serverless.yml`.

Ref: http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-set-up-simple-proxy.html

**Comment by contractorwolf** [comment]
does anyone know how I can access the {proxy+} data from my path in the handler?

**Comment by contractorwolf** [comment]
and is there an update on whether or not you can use the "/" in your path as the root of your project?

**Comment by bbilger** [comment]
assuming you defined `api/{proxy+}` in API Gateway and use proxy integration, `event.path` should contain the full resolved path `/api/a/b/...`. 
`event.requestContext.resourcePath` should give you `/api/{proxy+}` (`event` is the request object).
or just log the event object ;) 
```
exports.handler = function(event, context) {
console.log(JSON.stringify(event));
...
}
```

**Comment by contractorwolf** [comment]
@bbilger yes I found that when I used /api/{proxy+} in the serverless.yml file the event object showed the proxy value here: event.path.proxy. Thanks for the reply.  Any guesses how to make it work if you didnt want the /api prefix on the url?  How can I proxy the root /{proxy+} (doesnt work)?

**Comment by bbilger** [comment]
@contractorwolf I first wanted to write no but actually it seems that it is possible if you use an alternate syntax:
```yaml
functions:
  whatever:
    handler: yourHandler
    events:
      - http: ANY {proxy+}
```
Instead of this which doesn't work:  
```yaml
functions:
  whatever:
    handler: yourHandler
    events:
      - http:
          path: {proxy+}
          method: any
```

Note: I checked with serverless v1.0.3

**Comment by contractorwolf** [comment]
@bbilger that works but then I am unable to implement my response header and template.  Is there a way to add those if i need them?  This is what I had before:
      - http:
          path: api/{proxy+}
          method: get
          response:
            headers:
              Content-Type: "'text/html'"
            template: $input.path('$')

If I have - http: ANY {proxy+} how do i add the headers and template?

**Comment by bbilger** [comment]
@contractorwolf since you are using _Lambda Proxy Integration_, now, you can set the headers, the status and the body from within your function; see https://serverless.com/framework/docs/providers/aws/events/apigateway/#simple-http-endpoint

**Comment by heph** [comment]
@bbilger, I'm trying with serverless v1.0.3 with the syntax you described but get the following error:

```console
$ curl https://<snip>.execute-api.us-west-2.amazonaws.com/dev/
{"message":"Missing Authentication Token"}
```

My serverless.yml:
```yaml
service: limn
provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: us-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:DescribeInstances"
        - "ec2:DescribeTags"
      Resource: "*"
functions:
  describe:
    handler: limn.describe
    events:
      - http: ANY {proxy+}
```

Am I missing something obvious?

**Comment by bbilger** [comment]
I just wanted to report a bug, why is everybody asking me?
@heph 
Well it's `{proxy+}` not `{proxy*}` (which doesn't exist). So the following URLs would be matched `https://<snip>.execute-api.us-west-2.amazonaws.com/dev/a`, `https://<snip>.execute-api.us-west-2.amazonaws.com/dev/a/b`, ...
You need another mapping to `/` (`http: ANY /`) but this bug prevents doing so.

**Comment by heph** [comment]
Ah, gotcha. Sorry I thought this was a workaround for *that* bug! Thanks for confirming it's still open.

**Comment by contractorwolf** [comment]
@eahefnawy what version contains the fix now?

**Comment by pmuens** [comment]
@contractorwolf the refactorings for the API Gateway event done in #2666 should've added this.

**Comment by Jeff-Tian** [comment]
> @bbilger, I'm trying with serverless v1.0.3 with the syntax you described but get the following error:
> 
> ```
> $ curl https://<snip>.execute-api.us-west-2.amazonaws.com/dev/
> {"message":"Missing Authentication Token"}
> ```
> 
> My serverless.yml:
> 
> ```yaml
> service: limn
> provider:
>   name: aws
>   runtime: python2.7
>   stage: dev
>   region: us-west-2
>   iamRoleStatements:
>     - Effect: "Allow"
>       Action:
>         - "ec2:DescribeInstances"
>         - "ec2:DescribeTags"
>       Resource: "*"
> functions:
>   describe:
>     handler: limn.describe
>     events:
>       - http: ANY {proxy+}
> ```
> 
> Am I missing something obvious?

I met the same error and finally fixed by add an extra http api gateway trigger:

```
  api:
    handler: handler.api
    events:
      - http:
          path: api/
          method: ANY
          cors: true
      - http:
          path: api/{proxy+}
          method: ANY
          cors: true
```

https://github.com/Jeff-Tian/serverless-space/commit/c86fc59c9c04cd1625c37b4cb7849e2cb0a2dbfa

**Comment by gouthamravella** [comment]
@Jeff-Tian This is working for root paths too. Thanks.

```
api:
    handler: handler.api
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
```

Now you can access root perfectly fine. I don't see any downsides till now.

**Comment by ankesh7** [comment]
What is the workaround here? 😕
