### ISSUE TITLE
/myproject/venv/.Python is not existing in ubuntu vagrantbox

### ISSUE THREAD

**Issue by JadyLiu** [serverless/serverless#1852]
Bug Report

##### Stack-Trace (Optional):
Stack Trace --------------------------------------------

Error: ENOENT: no such file or directory, stat '/srv/backup-report/venv/.Python'
    at Error (native)
    at Object.fs.statSync (fs.js:987:18)
    at list.forEach (/usr/local/lib/node_modules/serverless/lib/classes/Utils.js:96:23)
    at Array.forEach (native)
    at Utils.walkDirSync (/usr/local/lib/node_modules/serverless/lib/classes/Utils.js:93:10)
    at list.forEach (/usr/local/lib/node_modules/serverless/lib/classes/Utils.js:98:43)
    at Array.forEach (native)
    at Utils.walkDirSync (/usr/local/lib/node_modules/serverless/lib/classes/Utils.js:93:10)
    at Package.zipService (/usr/local/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:39:27)
    at Package.tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:148:10)

Please advise

Thank you,
Jady

**Comment by flomotlik** [comment]
@JadyLiu as this does not seem to be a Serverless Issue directly we can't give any help here.
