### ISSUE TITLE
Serveless-offline plugin installation problem

### ISSUE THREAD

**Issue by ashachar** [serverless/serverless#1942]
##### Expected Behavior:
I've followed steps a and b listed here:
https://github.com/dherault/serverless-offline/tree/serverless_v1
Then, in step b, Upon adding the following to serverless.yml:

> plugins:
>   - serverless-offline

And invoking "serverless", the console should display Offline as one of the plug-ins now available in your serverless project.

##### Stack-Trace (Optional): 
TypeError: Plugin is not a constructor
  at PluginManager.addPlugin (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:150:28)
  at servicePlugins.forEach (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:186:12)
  at Array.forEach (native)
  at PluginManager.loadServicePlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:183:20)
  at PluginManager.loadAllPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:33:10)
  at service.load.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:60:28)

**Comment by rowanu** [comment]
Shouldn't this be raised on the [serverless-offline](https://github.com/dherault/serverless-offline) repo?

**Comment by pmuens** [comment]
Hey @ashachar thank you for reporting this.

@rowanu is right. It seems like this is an issue with the implementation of the `serverless-offline` plugin and not the Serverless framework itself.

Could you reopen it at the `serverless-offline` repo? Thanks!

**Comment by ashachar** [comment]
Thanks. Will do.
