### ISSUE TITLE
Add extra CF resources in a plugin

### ISSUE THREAD

**Issue by jagi** [serverless/serverless#1982]
Hi I'm using serverless@1.0.0-beta.2. I'm creating plugin that needs to create S3 bucket during `sls deploy`. So I've used the `deploy:compileEvents` hook to add some extra stuff to the resources. Here is what I have:

``` js
deployCompileEvents() {
  const BucketName = this.getBucketName();

  const bucketTemplate = `
    {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "BucketName": "${BucketName}",
        "AccessControl": "PublicRead",
        "WebsiteConfiguration": {
          "IndexDocument": "index.html",
          "ErrorDocument": "error.html"
        }
      }
    }
  `;
  const bucketResourceKey = BucketName.replace(/-/g, '');
  const newBucketObject = {
    [`${bucketResourceKey}S3Deploy`]: JSON.parse(bucketTemplate),
  };

  _.merge(
    this.serverless.service.provider.compiledCloudFormationTemplate.Resources,
    newBucketObject
  );
}
```

But bucket is not being created. So I had to create bucket using AWS S3 api which I wouldn't want to use. Do you know what I'm doing wrong? Or how to attach to the process of creating resources?

**Comment by andymac4182** [comment]
Have you checked the output to ensure it is included in the CF Template?

**Comment by jagi** [comment]
Yes it's included in the CF Template. I've just noticed that bucket get created when I return a promise which is weird, because it's not mentioned in docs. However I have another problem when I try to `putObject` in the `deploy` hook. I get error:

```
OperationAborted: A conflicting conditional operation is currently in progress against this resource. Please try again.
    at Request.extractError (/Users/jagi/workspace/usefulio/plugin/plugins/serverless-s3deploy/node_modules/aws-sdk/lib/services/s3.js:538:35)
    at Request.callListeners (/Users/jagi/workspace/usefulio/plugin/plugins/serverless-s3deploy/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/jagi/workspace/usefulio/plugin/plugins/serverless-s3deploy/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/jagi/workspace/usefulio/plugin/plugins/serverless-s3deploy/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (/Users/jagi/workspace/usefulio/plugin/plugins/serverless-s3deploy/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/jagi/workspace/usefulio/plugin/plugins/serverless-s3deploy/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/jagi/workspace/usefulio/plugin/plugins/serverless-s3deploy/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/jagi/workspace/usefulio/plugin/plugins/serverless-s3deploy/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/jagi/workspace/usefulio/plugin/plugins/serverless-s3deploy/node_modules/aws-sdk/lib/request.js:670:12)
    at Request.callListeners (/Users/jagi/workspace/usefulio/plugin/plugins/serverless-s3deploy/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/jagi/workspace/usefulio/plugin/plugins/serverless-s3deploy/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/jagi/workspace/usefulio/plugin/plugins/serverless-s3deploy/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (/Users/jagi/workspace/usefulio/plugin/plugins/serverless-s3deploy/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/jagi/workspace/usefulio/plugin/plugins/serverless-s3deploy/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/jagi/workspace/usefulio/plugin/plugins/serverless-s3deploy/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/jagi/workspace/usefulio/plugin/plugins/serverless-s3deploy/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/jagi/workspace/usefulio/plugin/plugins/serverless-s3deploy/node_modules/aws-sdk/lib/request.js:670:12)
    at Request.callListeners (/Users/jagi/workspace/usefulio/plugin/plugins/serverless-s3deploy/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/Users/jagi/workspace/usefulio/plugin/plugins/serverless-s3deploy/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at IncomingMessage.onEnd (/Users/jagi/workspace/usefulio/plugin/plugins/serverless-s3deploy/node_modules/aws-sdk/lib/event_listeners.js:211:11)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
```

**Comment by jagi** [comment]
Ok here is the current state:
- I can create a bucket by just attaching extra resources in the `deploy:compileEvents` but I have to use promises.
- I can't use the `s3.putObject` function in the `deploy:deploy` hook to just upload some data to this bucket because it's not yet created.

And that's ok because during deployment bucket does not exist yet. I also tried `after:deploy:deploy` but the same error. But Serverless somehow manages to do that. I'm trying to create similar plugin as this one https://github.com/serverless/serverless-client-s3

And as you can see here https://github.com/serverless/serverless-client-s3/blob/master/index.js#L107 author of this plugin was able (in v0.5) to access aws provider.
And he was able to call:
- `aws.request('createBucket')` - to create bucket https://github.com/serverless/serverless-client-s3/blob/master/index.js#L175
- `aws.request('putObject')` - to upload files https://github.com/serverless/serverless-client-s3/blob/master/index.js#L258

And everything worked well. So how can I access `aws` provider in `1.0.0-beta.2`?

**Comment by jagi** [comment]
I've managed to access this `sdk` property I was talking about in the following way:

```js
getPlugin() {
  const plugins = this.serverless.pluginManager.getPlugins();
  return _.find(plugins, function(plugin) {
    return plugin.constructor.name === 'AwsDeploy';
  });
}
```

Which is a little bit hacky and I see that it was discussed here https://github.com/serverless/serverless/issues/1826

However I still get the following error `ServerlessError: The specified bucket does not exist` when I try to invoke following code in the `deploy:deploy` hook.

```js
deployHook() {
  const plugin = this.getPlugin();

  return plugin.sdk.request('S3', 'putObject', {
    Bucket: 'BucketName',
    Key: 'index.html',
    Body: '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>Document</title></head><body><h1>Hello World Jagi!</h1></body></html>',
    ACL: 'public-read',
    ContentType: 'text/html'
  }, this.options.stage, this.options.region);
}
```

Which is very strange. I'm able to create bucket and upload files manually when using aws sdk for s3 but I'm not able to use serverless version... Could you provide some manual describing this process?

**Comment by andymac4182** [comment]
@jagi Here is a gist of how I am doing some local plugin work at the moment. I don't have to use promises to attach items to the compiled cloudformation. Hopefully this helps. https://gist.github.com/andymac4182/4837f722231ea493685f6b4699c939a1

Do you have the full code for your plugin somewhere?

**Comment by flomotlik** [comment]
Sorry for the late reply on this one, is this still an issue? Closing for now but let us know and we can follow up.
