### ISSUE TITLE
Deploying endpoint with new profile throw The statement id (s_apig_functionname_POST) provided already exists. Please provide a new statement id, or remove the existing statement.

### ISSUE THREAD

**Issue by Tbroycer** [serverless/serverless#1993]
# Can not deploy after switching similar profile using sls project init

## Description
I have executed sls project init with intention to change the profile. After that, when I try to redeploy a function with endpoint, I have the next error message:

> The statement id (s_apig_namefunction_POST) provided already exists. Please provide a new statement id, or remove the existing statement.

The function deployment is successful, but endpoint not.

Before deploying I completed my  s-variables-dev-useast1.json like the original.

`Serverless: Failed to deploy endpoints in "dev" to the following regions:
Serverless: us-east-1 ------------------------
Serverless:   POST - functionname: The statement id (s_apig_functionname_POST) provided already exists. Please provide a new statement id, or remove the existing statement.
  serverless:lib.actions.EndpointDeploy ServerlessError: The statement id (s_apig_functionname_POST) provided already exists. Please provide a new statement id, or remove the existing statement.
    at new ServerlessError (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Error.js:17:11)
    at C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointBuildApiGateway.js:859:17
From previous event:
    at Builder._addLambdaPermissionForEndpoint (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointBuildApiGateway.js:858:15)
From previous event:
    at Builder._manageLambdaAccessPolicy (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointBuildApiGateway.js:751:10)
From previous event:
    at Builder.build (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointBuildApiGateway.js:80:10)
    at EndpointBuildApiGateway.endpointBuildApiGateway (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointBuildApiGateway.js:54:22)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:211:25
    at Array.reduce (native)
    at Serverless._execute (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:210:26)
    at Object.actions.(anonymous function) [as endpointBuildApiGateway] (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:429:20)
    at C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointDeployApiGateway.js:172:36
From previous event:
    at C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointDeployApiGateway.js:146:35
    at C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\node_modules\async\lib\async.js:181:20
    at iterate (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\node_modules\async\lib\async.js:262:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\node_modules\async\lib\async.js:281:9)
    at Object.async.forEachSeries.async.eachSeries (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\node_modules\async\lib\async.js:214:22)
    at C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointDeployApiGateway.js:144:19
From previous event:
    at EndpointDeployApiGateway.<anonymous> (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointDeployApiGateway.js:141:18)
From previous event:
    at EndpointDeployApiGateway._processRegionDeployment (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointDeployApiGateway.js:137:10)
    at EndpointDeployApiGateway.<anonymous> (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointDeployApiGateway.js:94:24)
From previous event:
    at EndpointDeployApiGateway._processDeployment (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointDeployApiGateway.js:91:10)
From previous event:
    at EndpointDeployApiGateway.endpointDeployApiGateway (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointDeployApiGateway.js:55:10)
From previous event:
    at C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:211:25
    at Array.reduce (native)
    at Serverless._execute (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:210:26)
    at Object.actions.(anonymous function) [as endpointDeployApiGateway] (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:429:20)
    at EndpointDeploy._processDeployment (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointDeploy.js:213:24)
From previous event:
    at EndpointDeploy.endpointDeploy (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\EndpointDeploy.js:101:12)
From previous event:
    at C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:211:25
    at Array.reduce (native)
    at Serverless._execute (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:210:26)
    at Object.actions.(anonymous function) [as endpointDeploy] (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:429:20)
    at C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\DashDeploy.js:251:28
From previous event:
    at DashDeploy._deploy (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\DashDeploy.js:246:10)
From previous event:
    at DashDeploy.dashDeploy (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\actions\DashDeploy.js:126:10)
From previous event:
    at C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:186:31
    at Array.reduce (native)
    at C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:185:32
From previous event:
    at Serverless._execute (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:183:12)
    at Serverless.actions.(anonymous function) (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:429:20)
    at Serverless.command (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:398:38)
    at C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\bin\serverless:19:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Object.<anonymous> (C:\Users\developer\AppData\Roaming\npm\node_modules\serverless\bin\serverless:18:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3 +437ms
``
If my new profile have all permissions like the original, the problem is the same. So, permissions is not the problem.
How can I continue deploy with other profile?

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
