### ISSUE TITLE
Resource name <FunctionName> is non alphanumeric.

### ISSUE THREAD

**Issue by medhoover** [serverless/serverless#2017]
# This is a Bug Report

Hi, I'm trying to deploy lambda functions with non alphanumeric names (contain dashes), the stack build is failing, isn't it possible to do so? as the lambda functions already has this 'syntax  service-stage-name' ?

### What went wrong?
When deploying a a service that includes a function with dashes (example: `products-uploader`)
The cli throws: 
```
     Template format error: Resource name products-uploader is non
     alphanumeric.
```
### What did you expect should have happened?
I would like to have the possibility to deploy functions with structured names that suits the use case (example: products, stock etc) as this syntax is better than the camelcase.

### What was the config you used?
```
service: my-service

provider:
  name: aws
  runtime: nodejs4.3
  memorySize: ${memoryVar}
  timeout: ${timeVar}
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "*"
       Resource: "*"

defaults:
  stage: dev
  region: eu-central-1

plugins:
  - serverless-webpack

functions:
  products-uploader:
    handler: functions/products/uploader.handler
...
```
### What stacktrace or error message from your provider did you see?

```
ServerlessError: Template format error: Resource name stock-brax is non alphanumeric.
    at Response.<anonymous> (/usr/local/lib/node_modules/serverless/lib/plugins/aws/index.js:73:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:355:18)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:617:12)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:617:12)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at Request.RESET_RETRY_STATE (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/event_listeners.js:377:9)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:101:18)

```
Similar or dependent issues:
* #1924

**Comment by flomotlik** [comment]
This should be resolved with #1951 

Please install the master with `npm install -g serverless/serverless` (or wait for the release tomorrow) as those will have the fix included.

**Comment by medhoover** [comment]
Great, Many thanks!

**Comment by Everhusk** [comment]
I'm still having this issue

**Comment by Everhusk** [comment]
Fixed by adding 'name' to the function i.e.

Before:
functions:
   my-api-function:
      handler: handler

After:
functions:
   function1:
      name: my-api-function
      handler: handler

Not ideal because it adds a line for every function, but it works!
