### ISSUE TITLE
Threefold command nesting in plugin

### ISSUE THREAD

**Issue by jagi** [serverless/serverless#2037]
Version: `serverless@1.0.0-beta.2`

Hi, is it possible to triply nest commands in Serverless plugin?

I want to invoke command `sls stack build client` but I can't make it work.

```js
'use strict';

const Promise = require('bluebird');

class Stack {
  constructor(serverless, options) {
    this.serverless = serverless;
    this.options = options;

    this.commands = {
      stack: {
        lifecycleEvents: [
          'stack'
        ],
        commands: {
          build: {
            lifecycleEvents: [
              'build'
            ],
            commands: {
              client: {
                lifecycleEvents: [
                  'client'
                ]
              }
            }
          }
        }
      }
    };

    this.hooks = {
      'stack:build:client:client': () => Promise.bind(this)
        .then(this.buildClient)
    };
  }

  buildClient() {
    console.log('buildClient');
  }
}

module.exports = Stack;
```

I get console error:

```
  Serverless Error ---------------------------------------
 
     The command you entered was not found.
     Did you
     spell it correctly?
 
  Stack Trace --------------------------------------------
 
ServerlessError: The command you entered was not found.
     Did you spell it correctly?
    at PluginManager.run (/Users/jagi/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/lib/classes/PluginManager.js:100:13)
    at Serverless.run (/Users/jagi/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/lib/Serverless.js:77:33)
    at /Users/jagi/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/bin/serverless:18:50
 
  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
```

**Comment by rowanu** [comment]
Judging by [this TODO](https://github.com/serverless/serverless/blob/master/lib/classes/PluginManager.js#L117) it's not currently possible.

**Comment by jagi** [comment]
Ok I see, thanks! So they probably plan to work on that

**Comment by dougmoscrop** [comment]
Hey, I have a PR I am going to open soon (gimme another night) and it addresses this.

**Comment by dougmoscrop** [comment]
This should be fixed
