### ISSUE TITLE
Multiple Issues Blocking Windows Contribution

### ISSUE THREAD

**Issue by gwsii** [serverless/serverless#2044]
# This is a Bug Report

## Description

Trying to follow contribution guidance on the Window platform leads to blocking errors.

For bug reports:
* What went wrong?

1) "npm test" will result in an error: SyntaxError: Unexpected token ILLEGAL
2) "npm test" fails because Windows does not honor node shebang.
3) "npm test" zipService tests fail because .unixPermissions is used to evaluate success

* What did you expect should have happened?

"npm test" command runs all unit tests and passes them on Windows OS

* What was the config you used?

N/A

* What stacktrace or error message from your provider did you see?

1) No coverage information was collected, exit without writing coverage information
C:\src\serverless\node_modules\.bin\_mocha.CMD:1
(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\node.exe" (
                                                             ^

SyntaxError: Unexpected token ILLEGAL
   at exports.runInThisContext (vm.js:53:16)
   at Module._compile (module.js:373:25)
   at Object.Module._extensions..js (module.js:416:10)
   at Object.Module._extensions.(anonymous function) [as .js] (C:\src\serverless\node_modules\istanbul\lib\hook.js:109:37)
   at Module.load (module.js:343:32)
   at Function.Module._load (module.js:300:12)
   at Function.Module.runMain (module.js:441:10)
   at runFn (C:\src\serverless\node_modules\istanbul\lib\command\common\run-with-cover.js:122:16)
   at C:\src\serverless\node_modules\istanbul\lib\command\common\run-with-cover.js:251:17
   at C:\src\serverless\node_modules\istanbul\lib\util\file-matcher.js:68:16
npm ERR! Test failed.  See above for more details.

2) child_process.js:507
    throw err;
    ^
Error: Command failed: C:\src\serverless\bin\serverless create --template aws-nodejs
'C:\src\serverless\bin\serverless' is not recognized as an internal or external command,
operable program or batch file.
    at checkExecSyncError (child_process.js:464:13)
    at execSync (child_process.js:504:13)
    at Suite.<anonymous> (C:\src\serverless\tests\classes\PluginManager.js:775:5)
    at Object.create (C:\src\serverless\node_modules\mocha\lib\interfaces\common.js:114:19)
    at context.describe.context.context (C:\src\serverless\node_modules\mocha\lib\interfaces\bdd.js:42:27)
    at Suite.<anonymous> (C:\src\serverless\tests\classes\PluginManager.js:765:3)
    at Object.create (C:\src\serverless\node_modules\mocha\lib\interfaces\common.js:114:19)
    at context.describe.context.context (C:\src\serverless\node_modules\mocha\lib\interfaces\bdd.js:42:27)
    at Object.<anonymous> (C:\src\serverless\tests\classes\PluginManager.js:14:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Object.Module._extensions.(anonymous function) [as .js] (C:\src\serverless\node_modules\istanbul\lib\hook.js:109:37)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\src\serverless\tests\all.js:5:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Object.Module._extensions.(anonymous function) [as .js] (C:\src\serverless\node_modules\istanbul\lib\hook.js:109:37)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at C:\src\serverless\node_modules\mocha\lib\mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\src\serverless\node_modules\mocha\lib\mocha.js:217:14)
    at Mocha.run (C:\src\serverless\node_modules\mocha\lib\mocha.js:485:10)
    at Object.<anonymous> (C:\src\serverless\node_modules\mocha\bin\_mocha:403:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Object.Module._extensions.(anonymous function) [as .js] (C:\src\serverless\node_modules\istanbul\lib\hook.js:109:37)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at runFn (C:\src\serverless\node_modules\istanbul\lib\command\common\run-with-cover.js:122:16)
    at C:\src\serverless\node_modules\istanbul\lib\command\common\run-with-cover.js:251:17
    at C:\src\serverless\node_modules\istanbul\lib\util\file-matcher.js:68:16
    at C:\src\serverless\node_modules\async\lib\async.js:52:16
    at C:\src\serverless\node_modules\async\lib\async.js:361:13
    at C:\src\serverless\node_modules\async\lib\async.js:52:16
    at done (C:\src\serverless\node_modules\async\lib\async.js:246:17)
    at C:\src\serverless\node_modules\async\lib\async.js:44:16
    at C:\src\serverless\node_modules\async\lib\async.js:358:17
    at LOOP (fs.js:1534:14)
    at nextTickCallbackWith0Args (node.js:415:9)
    at process._tickCallback (node.js:344:13)
npm ERR! Test failed.  See above for more details.

3) 

  425 passing (3s)
  1 failing

  1) #zipService() should keep file permissions:

      AssertionError: expected 33060 to equal 33545
      + expected - actual

      -33060
      +33545

      at C:\src\serverless\lib\plugins\package\tests\zipService.js:147:15
      at tryCatcher (C:\src\serverless\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\src\serverless\node_modules\bluebird\js\release\promise.js:509:31)
      at Promise._settlePromise (C:\src\serverless\node_modules\bluebird\js\release\promise.js:566:18)
      at Promise._settlePromise0 (C:\src\serverless\node_modules\bluebird\js\release\promise.js:611:10)
      at Promise._settlePromises (C:\src\serverless\node_modules\bluebird\js\release\promise.js:690:18)
      at Async._drainQueue (C:\src\serverless\node_modules\bluebird\js\release\async.js:138:16)
      at Async._drainQueues (C:\src\serverless\node_modules\bluebird\js\release\async.js:148:10)
      at Immediate.Async.drainQueues [as _onImmediate] (C:\src\serverless\node_modules\bluebird\js\release\async.js:17:14)

## Additional Data

* ***Serverless Framework Version you're using***: 
$ node bin/serverless version
1.0.0-rc.1

* ***Operating System***:
Windows 7 Professional

* ***Stack Trace***:
* ***Provider Error messages***:

See Above.

**Comment by gwsii** [comment]
Working on a PR to address the first two issues. Have both working locally.
