### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by josh9254** [serverless/serverless#2136]
I have this error in version (1.0.0-rc.1)

Serverless: Packaging service...

  Type Error ---------------------------------------------

     Cannot read property 'toLowerCase' of undefined

     For debugging logs, run again after setting SLS_DEBUG env var.

  Stack Trace --------------------------------------------

TypeError: Cannot read property 'toLowerCase' of undefined
    at C:\Users\Josue\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\compile\events\apiGateway\lib\validate.js:16:39
    at Array.forEach (native)
    at C:\Users\Josue\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\compile\events\apiGateway\lib\validate.js:10:29
    at C:\Users\Josue\AppData\Roaming\npm\node_modules\serverless\node_modules\lodash\lodash.js:4738:15
    at baseForOwn (C:\Users\Josue\AppData\Roaming\npm\node_modules\serverless\node_modules\lodash\lodash.js:2879:24)
    at C:\Users\Josue\AppData\Roaming\npm\node_modules\serverless\node_modules\lodash\lodash.js:4707:18
    at Function.forEach (C:\Users\Josue\AppData\Roaming\npm\node_modules\serverless\node_modules\lodash\lodash.js:9011:14)
    at AwsCompileApigEvents.validate (C:\Users\Josue\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\compile\events\apiGateway\lib\validate.js:9:7)
    at AwsCompileApigEvents.tryCatcher (C:\Users\Josue\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Josue\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:509:31)
    at Promise._settlePromise (C:\Users\Josue\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:566:18)
    at Promise._settlePromiseCtx (C:\Users\Josue\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:603:10)
    at Async._drainQueue (C:\Users\Josue\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:143:12)
    at Async._drainQueues (C:\Users\Josue\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Josue\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     **Please report this error. We think it might be a bug.**

**Comment by andymac4182** [comment]
This will be related to your `serverless.yml` One of the events has an incorrect config. I ran into the same issue myself. 

Are you able to post your file?

**Comment by josh9254** [comment]
@andymac4182, I reviewed my file **serverless.yml**  and i found that this function have a problem, but i don't know where because the structure is correctly.
 


![error serv2](https://cloud.githubusercontent.com/assets/17339411/18556162/2a498e9c-7b30-11e6-9086-3aa386567a87.png)

**Comment by andymac4182** [comment]
It looks like your tab indent is wrong. I would check that they are all correct.

**Comment by danielkoo** [comment]
I see a typo there: 'metod' should be 'method'.

FYI, another way to tell is by going to line 16 of lib\plugins\aws\deploy\compile\events\apiGateway\lib\validate.js:16:39
which shows it's trying to call toLowerCase() on the event.http.method attribute

HTH

**Comment by josh9254** [comment]
@danielkoo  oh yes!! you're right thx @andymac4182  & @danielkoo
