### ISSUE TITLE
Cannot read property 'PhysicalResourceId' of undefined

### ISSUE THREAD

**Issue by JakubMatejka** [serverless/serverless#2140]
# Bug Report

## Description

`sls deploy` fails on this error:

```
Type Error ---------------------------------------------

     Cannot read property 'PhysicalResourceId' of undefined

     For debugging logs, run again after setting SLS_DEBUG env var.

  Stack Trace --------------------------------------------

TypeError: Cannot read property 'PhysicalResourceId' of undefined
    at request.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/index.js:109:19)
    at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:509:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:566:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:611:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:690:18)
    at Async._drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.
```

According to the code in https://github.com/serverless/serverless/blob/1.0.0-rc.1/lib/plugins/aws/index.js#L109 it can't find `ServerlessDeploymentBucket` in CF resources but I see it there when I look to aws console.

I am not aware that I would do anything special from last successful deployment. I just added a function and changed some endpoint. But the problem persists when I remove the changes from serverless.yml and `sls remove` fails too so I am stuck and cannot do anything right now. ;o/

## Additional Data

* ***Serverless Framework Version you're using***: 1.0.0-rc1
* ***Operating System***: macOS 10.12
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by JakubMatejka** [comment]
I found the problem. That `describeStackResources` method returns only first 100 resources (see http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFormation.html#describeStackResources-property) but I have 103.

**Comment by JakubMatejka** [comment]
I would change the code something like:

```js
  getServerlessDeploymentBucketName(stage, region) {
    const stackName = `${this.serverless.service.service}-${stage}`;
    return this.request('CloudFormation',
      'describeStackResource',
      { StackName: stackName, LogicalResourceId: 'ServerlessDeploymentBucket' },
      stage,
      region
    ).then((result) => {
      return result.StackResourceDetail.PhysicalResourceId;
    });
  }
```

It will be more effective to not list all the resources. I would even create pull request but to be honest I am not very well familiar with that shorthand syntax and I can't make linter to pass my code. ;o)

**Comment by andymac4182** [comment]
@JakubMatejka Thanks. I can submit a PR on your behalf.

**Comment by andymac4182** [comment]
You can submit the PR since it is your code just cleaned up a bit :) 
https://github.com/serverless/serverless/compare/master...andymac4182:issue_2140?expand=1

**Comment by JakubMatejka** [comment]
;o) Thanks @andymac4182 I am on it.

**Comment by pmuens** [comment]
Thank you guys! 🎉  (Done with #2142)
