### ISSUE TITLE
Unexpected token in JSON when running serverless deploy

### ISSUE THREAD

**Issue by scott-wood-vgh** [serverless/serverless#2153]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

My Serverless deployment of my AWS Lambda function for managing EC2 Snapshots failed.

* What did you expect should have happened?

I had tested the Lambda on its own using the Lambda web interface with no problems.

* What was the config you used?

service: Ec2SnapshotManager

provider:
  name: aws
  runtime: python2.7
  stage: prod
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:DescribeInstances"
        - "ec2:CreateSnapshot"
        - "ec2:DescribeSnapshots"
        - "ec2:DeleteSnapshot"
        - "ses:SendEmail"
      Resource: "*"

package:
  include:
    - createProductionScheduleSnapshots.py
    - cleanProductionScheduleSnapshots.py

functions:
  createProductionScheduleSnapshots:
    handler: createProductionScheduleSnapshots.createProductionScheduleSnapshots
    description: "Creates daily (weekday) snapshots of EC2 schedules."
    memorySize: 128
    timeout: 300
    events:
      - schedule: cron(0 0 0 ? * MON,TUE,WED,THU,FRI *)
  cleanProductionScheduleSnapshots:
    handler: cleanProductionScheduleSnapshots.cleanProductionScheduleSnapshots
    description: "Deletes old snapshots (older than one month, keeps Friday snapshots for each week until then)."
    memorySize: 128
    timeout: 300
    events:
      - schedule: cron(	0 0 0 ? * SAT *)

* What stacktrace or error message from your provider did you see?

With the SLS_DEBUG environment variable set, I got the following:

Serverless: Packaging service...
 
  Syntax Error -------------------------------------------
 
     Unexpected token 	 in JSON at position 140
 
     For debugging logs, run again after setting SLS_DEBUG env var.
 
  Stack Trace --------------------------------------------
 
SyntaxError: Unexpected token 	 in JSON at position 140
    at Object.parse (native)
    at functionObj.events.forEach.event (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/schedule/index.js:87:51)
    at Array.forEach (native)
    at serverless.service.getAllFunctions.forEach (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/schedule/index.js:21:28)
    at Array.forEach (native)
    at AwsCompileScheduledEvents.compileScheduledEvents (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/schedule/index.js:16:47)
    at hooksForEvent.push (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:96:40)
    at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:509:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/serverless/nod

## Additional Data

* ***Serverless Framework Version you're using***:
1.0.0-rc.1
* ***Operating System***:
Mac OS X El Capitain
* ***Stack Trace***:
As above

**Comment by scott-wood-vgh** [comment]
I found the issue and it is horrendous. There was an extra space in my cron specification for the schedule. The error message did not at all point me in that direction, but I combed my serverless.yml and identified it.
