### ISSUE TITLE
Remove serverless-run-python-handler file

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2331]
# This is a Feature Proposal

## Description

Remove the unnecessary `serverless-run-python-handler` file in the `bin` directory.

**Comment by horike37** [comment]
@pmuens 
I implemented this. Cloud you review it?

**Comment by pmuens** [comment]
@horike37 thank you very much! Closing this as it's merged /cc @flomotlik

**Comment by cristim** [comment]
I get errors because of this removal, it turns out it is needed in some cases:

```
./node_modules/serverless/bin/serverless deploy -n -v -s dev
Serverless: Wrote .env file to /home/user/work/app/.env
Serverless: Packaging service...
/home/user/work/app/node_modules/serverless/lib/plugins/package/lib/zipService.js:0

Error: ENOENT: no such file or directory, stat '/home/user/work/app/node_modules/.bin/serverless-run-python-handler'
    at Error (native)
    at Object.fs.statSync (fs.js:987:18)
    at files.forEach (/home/user/work/app/node_modules/serverless/lib/plugins/package/lib/zipService.js:41:26)
    at Array.forEach (native)
    at WriteStream.output.on (/home/user/work/app/node_modules/serverless/lib/plugins/package/lib/zipService.js:35:13)
    at emitOne (events.js:96:13)
    at WriteStream.emit (events.js:188:7)
    at WriteStream.<anonymous> (fs.js:1890:10)
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by pmuens** [comment]
@cristim Thanks for reporting. What version of Serverless are you using? Have you installed serverless through npm or do you use a version cloned from Git?

Seems like smth. is "in the cache" for the zip function.

**Comment by cristim** [comment]
I had it installed from npm. 

I noticed it while trying to  update from 1.0.0-rc2 to 1.0.2, when I needed to get the stack template after the update.
