### ISSUE TITLE
http/https request inside promise throws an error

### ISSUE THREAD

**Issue by jeeng** [serverless/serverless#2400]
# This is a (Bug Report / Feature Proposal)

Bug
## Description

When trying to issue an http request from inside a promise - an error is thrown.
However, doing so inside a callback function instead of a promise - works.
For bug reports:
- What went wrong?
- What did you expect should have happened?
- What was the config you used?
- What stacktrace or error message from your provider did you see?

```
Error: {}                                                                                         
    at module.exports.logError.words.forEach (/usr/local/lib/node_modules/serverless/lib/classes/E
rror.js:82:11)                                                                                    
    at /usr/local/lib/node_modules/serverless/bin/serverless:20:15                                
    at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js
:16:23)                                                                                           
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/blue
bird/js/release/promise.js:510:31)                                                                
    at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/rel
ease/promise.js:567:18)                                                                           
    at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/re
lease/promise.js:612:10)                                                                          
    at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/re
lease/promise.js:687:18)                                                                          
    at Async._drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/
async.js:138:16)                                                                                  
    at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release
/async.js:148:10)                                                                                 
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/serverless/node_
modules/bluebird/js/release/async.js:17:14)                                                       
    at processImmediate [as _immediateCallback] (timers.js:383:17)  

```

For feature proposals:
- What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
- If there is additional config how would it look

Similar or dependent issues:
- #12345
## Additional Data
- **_Serverless Framework Version you're using**_:
  1.0.2
- **_Operating System**_:
  ubuntu 16.04
- **_Stack Trace**_:

```
Error: {}                                                                                         
    at module.exports.logError.words.forEach (/usr/local/lib/node_modules/serverless/lib/classes/E
rror.js:82:11)                                                                                    
    at /usr/local/lib/node_modules/serverless/bin/serverless:20:15                                
    at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js
:16:23)                                                                                           
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/blue
bird/js/release/promise.js:510:31)                                                                
    at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/rel
ease/promise.js:567:18)                                                                           
    at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/re
lease/promise.js:612:10)                                                                          
    at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/re
lease/promise.js:687:18)                                                                          
    at Async._drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/
async.js:138:16)                                                                                  
    at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release
/async.js:148:10)                                                                                 
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/serverless/node_
modules/bluebird/js/release/async.js:17:14)                                                       
    at processImmediate [as _immediateCallback] (timers.js:383:17)  
```
- **_Provider Error messages**_:

```
Error --------------------------------------------------                                        

     {}
```

**Comment by pmuens** [comment]
Hey @jeeng thanks for reporting! 👍 

Could you provide a code example so that we can look into what's going wrong?

**Comment by mthenw** [comment]
Closing for now. 

@jeeng please comment with code block causing this error.
