### ISSUE TITLE
Warning messages when deploying - without AWS credentials

### ISSUE THREAD

**Issue by joseconstela** [serverless/serverless#2535]
# This is a Bug Report
## Description

For bug reports:
- **What went wrong?:** Warning messages when deploying without AWS credentials
- **What did you expect should have happened?:** No warning messages
## Additional Data
- **_Serverless Framework Version you're using**_: 1.0.3
- **_Operating System**_: MacOS Sierra
- **_Stack Trace**_: 

```
Warning: a promise was rejected with a non-error: [object Error]
    at AwsDeploy.<anonymous> (/Users/jose/npm/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:61:17)
From previous event:
    at AwsDeploy.createStack (/Users/jose/npm/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:55:8)
From previous event:
    at AwsDeploy.hooks.deploy:setupProviderConfiguration (/Users/jose/npm/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:45:10)
    at /Users/jose/npm/lib/node_modules/serverless/lib/classes/PluginManager.js:157:50
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at PluginManager.run (/Users/jose/npm/lib/node_modules/serverless/lib/classes/PluginManager.js:157:22)
    at Serverless.run (/Users/jose/npm/lib/node_modules/serverless/lib/Serverless.js:88:31)
    at /Users/jose/npm/lib/node_modules/serverless/bin/serverless:19:50

Warning: a promise was rejected with a non-error: [object Error]
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at PluginManager.run (/Users/jose/npm/lib/node_modules/serverless/lib/classes/PluginManager.js:157:22)
    at Serverless.run (/Users/jose/npm/lib/node_modules/serverless/lib/Serverless.js:88:31)
    at /Users/jose/npm/lib/node_modules/serverless/bin/serverless:19:50

  Error --------------------------------------------------

     ServerlessError: ServerlessError: AWS provider credentials
     not found. You can find more info on how to set up provider
     credentials in our docs here: https://git.io/viZAC

     For debugging logs, run again after setting SLS_DEBUG env var.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.

  Your Environment Infomation -----------------------------
     OS:                 darwin
     Node Version:       5.10.1
     Serverless Version: 1.0.3
```

**Comment by flomotlik** [comment]
@joseconstela did you have the AWS credentials defined? Or why shouldn't they have come up?

**Comment by pmuens** [comment]
Closing this issue since we've updated Serverless in the meantime.
