### ISSUE TITLE
sls deploy looking to default profile for aws credentials, not looking to profile specified in serverless.yml

### ISSUE THREAD

**Issue by stoicism2323** [serverless/serverless#2551]
# This is a (Bug Report / Feature Proposal)

## Description
sls deploy looking to default profile for aws credentials, not looking to profile specified in serverless.yml

For bug reports:
* What went wrong?
Profile specified in serverless.yml is not being used, instead default profile from ~/.aws/credentials is being used. I specified the profile called 'serverless-admin' under 'provider' in serverless.yml:
```

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  profile: serverless-admin

# you can overwrite defaults here
defaults:
  stage: dev
  region: us-west-2


```
* What did you expect should have happened?
Deploy handler.js to aws lambda
* What was the config you used?
* What stacktrace or error message from your provider did you see?
```

[e@localhost mma-info]$ sls deploy
Serverless: Creating Stack...
 
  Serverless Error ---------------------------------------
 
     User: arn:aws:iam::975647746974:user/linux_user is not
     authorized to perform: cloudformation:CreateStack on
     resource: arn:aws:cloudformation:us-west-2:975647746974:stack/mma-info-dev/*
 
  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

```
'linux_user' is my default profile in ~/.aws/credentials. I want it to use 'serverless-admin' profile instead.

## Additional Data

* ***Serverless Framework Version you're using***:
1.0.3
* ***Operating System***:
Arch linux
* ***Stack Trace***:
```
  Stack Trace --------------------------------------------
 
ServerlessError: User: arn:aws:iam::975647746974:user/linux_user is not authorized to perform: cloudformation:CreateStack on resource: arn:aws:cloudformation:us-west-2:975647746974:stack/mma-info-dev/*
    at Response.req.send (/usr/lib/node_modules/serverless/lib/plugins/aws/index.js:73:20)
    at Request.<anonymous> (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:355:18)
    at Request.callListeners (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:617:12)
    at Request.callListeners (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
```

* ***Provider Error messages***:

Thanks for any help!
--stoicism

**Comment by stoicism2323** [comment]
My mistake, wasn't updated to V 1.0.3. Was actually on 1.0.0 beta. Sorry bout that
