### ISSUE TITLE
TypeError in json-refs when using command line utility

### ISSUE THREAD

**Issue by turnshek** [serverless/serverless#2600]
First time using the framework, and ran into an issue right away. Please let me know if I can provide any more information.

# This is a Bug Report

## Description

For bug reports:
* What went wrong?

When running the serverless command line utility, I get a `TypeError` from `json-refs`.

* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***: 1.1.0
* ***Operating System***: macOS Sierra
* ***Stack Trace***: 
```TypeError: obj must be an Array or an Object
    at /Users/turnshek/.nvm/versions/node/v7.0.0/lib/node_modules/serverless/node_modules/json-refs/index.js:1195:15
```
* ***Provider Error messages***:

Here's the full output:
```
$ serverless

  Type Error ---------------------------------------------

     obj must be an Array or an Object

     For debugging logs, run again after setting SLS_DEBUG env var.

  Stack Trace --------------------------------------------

TypeError: obj must be an Array or an Object
    at /Users/turnshek/.nvm/versions/node/v7.0.0/lib/node_modules/serverless/node_modules/json-refs/index.js:1195:15

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       7.0.0
     Serverless Version: 1.1.0
```

**Comment by turnshek** [comment]
Turns out it was just a problem with my serverless.yml config. Chalk this up to a bad error message.
