### ISSUE TITLE
Serverless local invoke failing to capture a purposeful failure

### ISSUE THREAD

**Issue by jtslear** [serverless/serverless#2612]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
I locally invoked a function to purposely fail and serverless threw an error

* What did you expect should have happened?
I expected serverless handle the purposeful failure the same way lambda might
```
serverless-local-invoke-failure master % serverless invoke -f hello
{
    "errorMessage": "fail"
}
```

* What was the config you used?
Code can be found here: https://github.com/jtslear/serverless-local-invoke-failure

* What stacktrace or error message from your provider did you see?
```
serverless-local-invoke-failure master % SLS_DEBUG=true serverless invoke local -f hello

  Error --------------------------------------------------

     fail

     For debugging logs, run again after setting SLS_DEBUG env var.

  Stack Trace --------------------------------------------

Error: fail
    at module.exports.logError.words.forEach (/usr/local/lib/node_modules/serverless/lib/classes/Error.js:82:11)
    at /usr/local/lib/node_modules/serverless/bin/serverless:20:15
    at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       4.3.2
     Serverless Version: 1.1.0
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.1.0
* ***Operating System***: OSX
* ***Stack Trace***: above
* ***Provider Error messages***: above

Unless of course this is expected behavior, feel free to close otherwise.  While building lambda functions I'm purposely failing them for testing, and the `lambci/lambda` docker container handles it like I'd expect, or comfortable with knowing my function failed, and not the serverless local invocation.

**Comment by jtslear** [comment]
A slightly different, and more informative error, occurs when I use an error object as seen on this branch: https://github.com/jtslear/serverless-local-invoke-failure/blob/error-object/handler.js

```
    Error --------------------------------------------------

     fail

     For debugging logs, run again after setting SLS_DEBUG env var.

  Stack Trace --------------------------------------------

Error: fail
    at module.exports.hello (/Users/jskarbek/projects/serverless-local-invoke-failure/handler.js:3:12)
    at AwsInvokeLocal.invokeLocalNodeJs (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:106:12)
    at AwsInvokeLocal.invokeLocal (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:50:19)
    at AwsInvokeLocal.tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       4.3.2
     Serverless Version: 1.1.0
```
