### ISSUE TITLE
AWS Credentials not found

### ISSUE THREAD

**Issue by geotabular** [serverless/serverless#2708]
# This is a (Bug Report)

## Description

For bug reports:
* What went wrong?

Serverless ignores the AWS credentials environment variables when running in atlassian's Bamboo. Works fine from my local machine (my local machine uses ~/.aws/credentials).

* What did you expect should have happened?

Serverless should deploy from bamboo, using the configured environment variables

* What was the config you used?

Tried the following:
inline bamboo build script:

#!/bin/bash
PATH="/usr/local/bin:./node_modules/.bin/:$PATH"
export PATH
set -e
unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
echo "Using profile ${bamboo_profile}" 
if [ \( "${bamboo_profile}" = "prod" \) -o \( "${bamboo_profile}" = "test" \) ] ; then
    echo "Using production aws variables"
    export AWS_ACCESS_KEY_ID=${bamboo_aws_lambda_id_password_prod}
    export AWS_SECRET_ACCESS_KEY=${bamboo_aws_lambda_secret_password_key_prod}
else
    export AWS_ACCESS_KEY_ID=${bamboo_aws_lambda_id_password}
    export AWS_SECRET_ACCESS_KEY=${bamboo_aws_lambda_secret_password_key}
fi

export AWS_DEFAULT_REGION=${bamboo_aws_region}

npm install
npm update
npm test
export SLS_DEBUG=true
sls deploy

* What stacktrace or error message from your provider did you see?

build	15-Nov-2016 10:33:43	  Error --------------------------------------------------
build	15-Nov-2016 10:33:43	 
build	15-Nov-2016 10:33:43	     ServerlessError: ServerlessError: AWS provider credentials
build	15-Nov-2016 10:33:43	     not found. You can find more info on how to set up provider
build	15-Nov-2016 10:33:43	     credentials in our docs here: https://git.io/viZAC
build	15-Nov-2016 10:33:43	 
build	15-Nov-2016 10:33:43	     For debugging logs, run again after setting SLS_DEBUG env var.
build	15-Nov-2016 10:33:43	 
build	15-Nov-2016 10:33:43	  Stack Trace --------------------------------------------
build	15-Nov-2016 10:33:43	 
build	15-Nov-2016 10:33:43	Error: ServerlessError: ServerlessError: AWS provider credentials not found. You can find more info on how to set up provider credentials in our docs here: https://git.io/viZAC
build	15-Nov-2016 10:33:43	    at module.exports.logError.errorHandlingError (/home/bamboo/bamboo-agent-home/xml-data/build-dir/CNS-SLUD-JOB1/node_modules/serverless/lib/classes/Error.js:82:11)
build	15-Nov-2016 10:33:43	    at BbPromise.resolve.then.catch.e (/home/bamboo/bamboo-agent-home/xml-data/build-dir/CNS-SLUD-JOB1/node_modules/serverless/bin/serverless:20:15)
build	15-Nov-2016 10:33:43	    at tryCatcher (/home/bamboo/bamboo-agent-home/xml-data/build-dir/CNS-SLUD-JOB1/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
build	15-Nov-2016 10:33:43	    at Promise._settlePromiseFromHandler (/home/bamboo/bamboo-agent-home/xml-data/build-dir/CNS-SLUD-JOB1/node_modules/serverless/node_modules/bluebird/js/release/promise.js:510:31)
build	15-Nov-2016 10:33:43	    at Promise._settlePromise (/home/bamboo/bamboo-agent-home/xml-data/build-dir/CNS-SLUD-JOB1/node_modules/serverless/node_modules/bluebird/js/release/promise.js:567:18)
build	15-Nov-2016 10:33:43	    at Promise._settlePromise0 (/home/bamboo/bamboo-agent-home/xml-data/build-dir/CNS-SLUD-JOB1/node_modules/serverless/node_modules/bluebird/js/release/promise.js:612:10)
build	15-Nov-2016 10:33:43	    at Promise._settlePromises (/home/bamboo/bamboo-agent-home/xml-data/build-dir/CNS-SLUD-JOB1/node_modules/serverless/node_modules/bluebird/js/release/promise.js:687:18)
build	15-Nov-2016 10:33:43	    at Async._drainQueue (/home/bamboo/bamboo-agent-home/xml-data/build-dir/CNS-SLUD-JOB1/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:16)
build	15-Nov-2016 10:33:43	    at Async._drainQueues (/home/bamboo/bamboo-agent-home/xml-data/build-dir/CNS-SLUD-JOB1/node_modules/serverless/node_modules/bluebird/js/release/async.js:148:10)
build	15-Nov-2016 10:33:43	    at Immediate.Async.drainQueues (/home/bamboo/bamboo-agent-home/xml-data/build-dir/CNS-SLUD-JOB1/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
build	15-Nov-2016 10:33:43	    at runCallback (timers.js:637:20)
build	15-Nov-2016 10:33:43	    at tryOnImmediate (timers.js:610:5)
build	15-Nov-2016 10:33:43	    at processImmediate [as _immediateCallback] (timers.js:582:5)
build	15-Nov-2016 10:33:43	 

I also tried to add credentials as variables in serverless.yml:

...
 credentials:
    accessKeyId: ${env:AWS_ACCESS_KEY_ID}
    secretAccessKey: ${env:AWS_SECRET_ACCESS_KEY}
...

## Additional Data
 Your Environment Information -----------------------------
build	15-Nov-2016 10:33:43	     OS:                 linux
build	15-Nov-2016 10:33:43	     Node Version:       6.9.1
build	15-Nov-2016 10:33:43	     Serverless Version: 1.1.0

This is a show stopper for our organisation. If we can't build it from bamboo, we won't be able to use sls anymore. Please help! 

Thanks in advance

**Comment by geotabular** [comment]
So it appears through pleliminary testing that removing the line:

#!/bin/bash

from the inline script seems to fix this problem
