### ISSUE TITLE
Deploy from scratch fails when use custom role and  'deploymentBucket' together

### ISSUE THREAD

**Issue by RuslanHryn** [serverless/serverless#2815]
# This is a Bug Report

## Description
Deploy fails on Requires capabilities : [CAPABILITY_NAMED_IAM]. I want to deploy a function from scratch. I use a custom role and deployment bucket in serverless.yml file together. If dont use custom deployment bucket then it works fine.
.
For bug reports:
* What went wrong?
Deploy fails with error Requires capabilities : [CAPABILITY_NAMED_IAM]
* What did you expect should have happened?
Success deploy
* What was the config you used?
Here is example of serverless.yml:

```

service: net-test

provider:
  name: aws
  runtime: java8
  region: ${file(./src/main/resources/stages/${opt:stage}.stage.yml):awsRegion}
  deploymentBucket: 'CustomBucket'

package:
  artifact: target/application.jar

functions:
  funcApi:
    role: role1
    handler: com.test.ApiRequestHandler
    name: 
    memorySize : 512
    timeout: 90
    events:
      - http:
          path: observation
          method: GET
          integration: lambda
          private: true
          request:
            parameters:
              querystrings:
                location: false,

resources:
    Resources:
      role1:
            Type: AWS::IAM::Role
            Properties:
              RoleName: role1
              Path: "/"
              AssumeRolePolicyDocument:
                Version: '2010-09-09'
                Statement:
                  - Effect: Allow
                    Principal:
                      Service:
                        - lambda.amazonaws.com
                    Action: sts:AssumeRole
              Policies:
                - PolicyName: policy1
                  PolicyDocument:
                    Version: '2010-09-09'
                    Statement:
                      - Effect: Allow
                        Action:
                          - logs:CreateLogGroup
                          - logs:CreateLogStream
                          - logs:PutLogEvents
                        Resource: arn:aws:logs:us-east-1:xxxx:log-group:/aws/lambda/*:*:*
```
`
* What stacktrace or error message from your provider did you see?
```
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3 (19.98 MB)...
Serverless: Creating Stack...

  Serverless Error ---------------------------------------

     Requires capabilities : [CAPABILITY_NAMED_IAM]

  Stack Trace --------------------------------------------

ServerlessError: Requires capabilities : [CAPABILITY_NAMED_IAM]
    at Response.<anonymous> (C:\Users\Ruslan_Hryn\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\provider\awsProvider.js:167:20)
    at Request.<anonymous> (C:\Users\Ruslan_Hryn\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\request.js:355:18)
    at Request.callListeners (C:\Users\Ruslan_Hryn\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at Request.emit (C:\Users\Ruslan_Hryn\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (C:\Users\Ruslan_Hryn\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\request.js:668:14)
    at Request.transition (C:\Users\Ruslan_Hryn\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\Ruslan_Hryn\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\Ruslan_Hryn\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\Ruslan_Hryn\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\Ruslan_Hryn\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\request.js:670:12)
    at Request.callListeners (C:\Users\Ruslan_Hryn\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\sequential_executor.js:115:18)
    at Request.emit (C:\Users\Ruslan_Hryn\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (C:\Users\Ruslan_Hryn\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\request.js:668:14)
    at Request.transition (C:\Users\Ruslan_Hryn\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\Ruslan_Hryn\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\Ruslan_Hryn\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\state_machine.js:26:10

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Information -----------------------------
     OS:                 win32
     Node Version:       4.5.0
     Serverless Version: 1.2.1


```

## Additional Data

* ***Serverless Framework Version you're using***:
1.2.1
* ***Operating System***:
Windows 7
* ***Stack Trace***:
* ***Provider Error messages***:
Requires capabilities : [CAPABILITY_NAMED_IAM]

**Comment by RuslanHryn** [comment]
The same issue [https://github.com/serverless/serverless/issues/2826](2826)

**Comment by pmuens** [comment]
@RuslanHryn thanks for opening!

I'll close this one as it should be in master (and in the next release). The fix was done in https://github.com/serverless/serverless/pull/2854.

Let us know if this is still a bug!
