### ISSUE TITLE
Serverless does not create ~/.aws/credentials file when using config credentials CLI on OS X El Capitan 10.11.3

### ISSUE THREAD

**Issue by alexbielen** [serverless/serverless#2878]
# This is a (Bug Report / Feature Proposal)
Bug Report
## Description
Same issue as #2857 but also happening on OS X. 
Serverless CLI fails to create `~/.aws/credentials` when calling `serverless config credentials --provider aws -k <key> -s <secret>` 
For bug reports:
* What went wrong?
Serverless did not create the `~/.aws/credentials` file.  After a success message there is a stack trace about failure. 
* What did you expect should have happened?
I expected serverless to create the `~/.aws/credentials` file. 
* What was the config you used?
No config; new project. 
* What stacktrace or error message from your provider did you see?
```
Serverless: Setting up AWS...
Serverless: Saving your AWS profile in "~/.aws/credentials"...
Serverless: Success! Your AWS access keys were stored under the "default" profile.

  Error --------------------------------------------------

     ENOENT: no such file or directory, open '/Users/alexbielen/.aws/credentials'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: ENOENT: no such file or directory, open '/Users/alexbielen/.aws/credentials'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at Object.fs.appendFileSync (fs.js:1392:6)
    at e (/usr/local/lib/node_modules/serverless/lib/classes/Utils.js:81:12)
    at Promise._execute (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:77:14)
    at Utils.appendFileSync (/usr/local/lib/node_modules/serverless/lib/classes/Utils.js:79:12)
    at AwsConfigCredentials.configureCredentials (/usr/local/lib/node_modules/serverless/lib/plugins/aws/configCredentials/awsConfigCredentials.js:94:27)
    at AwsConfigCredentials.tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:148:10)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.7.0
     Serverless Version: 1.3.0
```

Similar or dependent issues:
* #2857

**Comment by DavidWells** [comment]
@alexbielen what is your home directory?

**Comment by DavidWells** [comment]
@pmuens Looks like it's failing if the directory doesn't exist. https://github.com/serverless/serverless/blob/master/lib/plugins/aws/configCredentials/awsConfigCredentials.js#L94

We should probably use `outputFileSync ` https://github.com/jprichardson/node-fs-extra#outputfilefile-data-options-callback which created the directory if it doesn't exist yet

**Comment by pmuens** [comment]
@DavidWells thanks for looking into that!

Good idea! I'll look into that!

**Comment by pmuens** [comment]
@alexbielen thanks for reporting and @DavidWells thanks for chiming in!

Just PRd a bugfix (#2893). 👍
