### ISSUE TITLE
cli issue: Cannot assign to read only property 'events' of 3

### ISSUE THREAD

**Issue by robertcuadra** [serverless/serverless#2886]
# This is a Bug Report

## Description
When running serverless command an error is returned.

For bug reports:
* What went wrong?
zsh> SLS_DEBUG=* sls
Type Error ---------------------------------------------

     Cannot assign to read only property 'events' of 3

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: Cannot assign to read only property 'events' of 3
    at /Users/robertcuadra/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/lib/classes/Service.js:154:49
    at /Users/robertcuadra/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/node_modules/lodash/lodash.js:4917:15
    at baseForOwn (/Users/robertcuadra/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/node_modules/lodash/lodash.js:2979:24)
    at /Users/robertcuadra/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/node_modules/lodash/lodash.js:4886:18
    at Function.forEach (/Users/robertcuadra/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/node_modules/lodash/lodash.js:9289:14)
    at /Users/robertcuadra/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/lib/classes/Service.js:152:11

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       4.3.2
     Serverless Version: 1.3.0

* What did you expect should have happened?
Display information about the current config and plugins.

* What was the config you used?
```
service: myservice

provider:
  name: aws
  runtime: nodejs4.3

functions:
  timeout: 3
  catalog:
    handler: handlers/catalog/catalog.handler
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.3.0
* ***Operating System***: Sierra (OS X 10.12)
* ***Stack Trace***: See above
* ***Provider Error messages***: None

**Comment by robertcuadra** [comment]
User error cause by having timeout under functions.
