### ISSUE TITLE
Cannot read property 'path' of null

### ISSUE THREAD

**Issue by twonder** [serverless/serverless#3022]
# This is a Bug Report / Feature Proposal

## Description
When trying to deploy the hello world project, I'm getting an error: Cannot read property 'path' of null.  Thanks for the help.

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
Below
* What stacktrace or error message from your provider did you see?
Below

## Additional Data

* ***Serverless Framework Version you're using***: 1.4.0
* ***Operating System***: darwin (OS X 10.11.6)
* ***Stack Trace***:
Below
* ***Provider Error messages***:

### Stacktrace
``` 
% SLS_DEBUG=true serverless deploy -v
Serverless: Packaging service...
 
  Type Error ---------------------------------------------
 
     Cannot read property 'path' of null
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
TypeError: Cannot read property 'path' of null
    at AwsCompileApigEvents.getHttpPath (/Users/tim/.nvm/versions/node/v6.9.2/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js:144:20)
    at _.forEach (/Users/tim/.nvm/versions/node/v6.9.2/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js:46:28)
    at arrayEach (/Users/tim/.nvm/versions/node/v6.9.2/lib/node_modules/serverless/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/Users/tim/.nvm/versions/node/v6.9.2/lib/node_modules/serverless/node_modules/lodash/lodash.js:9344:14)
    at _.forEach (/Users/tim/.nvm/versions/node/v6.9.2/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js:42:9)
    at /Users/tim/.nvm/versions/node/v6.9.2/lib/node_modules/serverless/node_modules/lodash/lodash.js:4970:15
    at baseForOwn (/Users/tim/.nvm/versions/node/v6.9.2/lib/node_modules/serverless/node_modules/lodash/lodash.js:3020:24)
    at /Users/tim/.nvm/versions/node/v6.9.2/lib/node_modules/serverless/node_modules/lodash/lodash.js:4939:18
    at Function.forEach (/Users/tim/.nvm/versions/node/v6.9.2/lib/node_modules/serverless/node_modules/lodash/lodash.js:9344:14)
    at AwsCompileApigEvents.validate (/Users/tim/.nvm/versions/node/v6.9.2/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js:41:7)
    at deploy:compileEvents (/Users/tim/.nvm/versions/node/v6.9.2/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/apiGateway/index.js:42:31)
    at BbPromise.reduce (/Users/tim/.nvm/versions/node/v6.9.2/lib/node_modules/serverless/lib/classes/PluginManager.js:160:50)
    at tryCatcher (/Users/tim/.nvm/versions/node/v6.9.2/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/tim/.nvm/versions/node/v6.9.2/lib/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:157:18)
    at Object.gotAccum (/Users/tim/.nvm/versions/node/v6.9.2/lib/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/Users/tim/.nvm/versions/node/v6.9.2/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
     Please report this error. We think it might be a bug.
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.9.2
     Serverless Version: 1.4.0
 
```

### serverless.yml
```
service: serverlessquick

provider:
  name: aws
  runtime: nodejs4.6

functions:
  hello:
    handler: handler.hello
    events:
    	- http:
    		path: hello
    		method: get
```

**Comment by pmuens** [comment]
Hey @twonder 

You've mixed tabs with spaces while indenting. Could you ensure that you only indent with e.g. 2 spaces (or 1 tab) and try again (like this):

```yml
service: serverlessquick

provider:
  name: aws
  runtime: nodejs4.6

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
```

**Comment by twonder** [comment]
Thank you that worked!

**Comment by matt-way** [comment]
Perfect example of why yaml sucks. This (with spaces only) was getting me the same error, making it very difficult to debug.

```
functions:
  hello:
    handler: handler.hello
    events:
      - http:
        path: hello
        method: get
```
It took a while to find the error, so I just altered my config to pure JSON. That way any mistakes are obvious, and will be more likely to be picked up by the parser. If anyone comes across this, use the referenced config below:

```
{
  "service": "serverlessquick",
  "provider": {
    "name": "aws",
    "runtime": "nodejs4.3"
  },
  "functions": {
    "hello": {
      "handler": "handler.hello",
      "events": [
        {
          "http": {
            "path": "hello",
            "method": "get"
          }
        }
      ]
    }
  }
}
```

**Comment by pmuens** [comment]
@matt-way thanks for the clarification.

Yes, YAML is sometimes a little bit strange. Just wanted to drop a reference to the following issue where we've also discussed some YAML weirdness (with an example like above):

https://github.com/serverless/serverless/issues/3029#issuecomment-269593423

**Comment by benburkhart1** [comment]
In case anyone is reading this clueless and wondered what the fix for @matt-way's issue was, he needed extra indentation for the "path" and "method" in his yaml example.

**Comment by krisalexander200** [comment]
@benburkhart1 that ended up being my specific problem, too. Thanks for sharing

**Comment by olivierlesnicki** [comment]
Likewise here
