### ISSUE TITLE
preuninstall and postinstall scripts failing when installing serverless during travis builds

### ISSUE THREAD

**Issue by againer** [serverless/serverless#3091]
# This is a Bug Report

## Description
`serverless` installation fails on Travis when using `npm install -g serverless`. Seems ES6+ related.

For bug reports:
* What went wrong?
`serverless` does not install during a Travis build.
* What did you expect should have happened?
`serverless` should be installed.
* What was the config you used?
`nvm 0.10.48` on a Travis build.
* What stacktrace or error message from your provider did you see?
(see below)

## Additional Data

* ***Serverless Framework Version you're using***: `1.5.0`
* ***Stack Trace***:
```
> serverless@1.5.0 postinstall /home/travis/.nvm/v0.10.48/lib/node_modules/serverless
> node ./scripts/postinstall.js


/home/travis/.nvm/v0.10.48/lib/node_modules/serverless/scripts/postinstall.js:6
(() => {
  ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m Linux 4.4.0-51-generic
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m [0m[35margv[0m "/home/travis/.nvm/v0.10.48/bin/node" "/home/travis/.nvm/v0.10.48/bin/npm" "install" "-g" "serverless"
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m [0m[35mnode[0m v0.10.48
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m [0m[35mnpm [0m v2.15.1
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m [0m[35mcode[0m ELIFECYCLE
[0m
[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m serverless@1.5.0 postinstall: `node ./scripts/postinstall.js`
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m Exit status 8
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m 
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m Failed at the serverless@1.5.0 postinstall script 'node ./scripts/postinstall.js'.
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m This is most likely a problem with the serverless package,
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m not with npm itself.
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m Tell the author that this fails on your system:
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     node ./scripts/postinstall.js
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m You can get information on how to open an issue for this project with:
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     npm bugs serverless
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m Or if that isn't available, you can get their info via:
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m 
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     npm owner ls serverless
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m There is likely additional logging output above.
[0m
> serverless@1.5.0 preuninstall /home/travis/.nvm/v0.10.48/lib/node_modules/serverless
> node ./scripts/preuninstall.js


/home/travis/.nvm/v0.10.48/lib/node_modules/serverless/scripts/preuninstall.js:6
(() => {
  ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
```

**Comment by againer** [comment]
Let me see if using babel-node instead of node to run postinstall and preuninstall helps.

**Comment by againer** [comment]
Ah. Apparently one should not use `babel-node` in production.

**Comment by againer** [comment]
Closing -- `node ./scripts/postinstall.js` assumes a node version with ES6 features.  I will just update my travis config to use a more recent version of node.
