### ISSUE TITLE
ServerlessError: unable to get local issuer certificate 

### ISSUE THREAD

**Issue by amit1980** [serverless/serverless#3127]
# Bug Report : The issue occurs only when deploy to Sydney region (ap-southeast-2) not others. 

## Description
Create a simple template using aws-nodejs 
$ sls create -t aws-nodejs
Serverless: Generating boilerplate...
_______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v1.5.0
-------'

Serverless: Successfully generated boilerplate for template: "aws-nodejs"
Serverless: NOTE: Please update the "service" property in serverless.yml with your service name

Deploy to ap-southeast-2 region
sls deploy -v -r ap-southeast-2
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - aws-nodejs-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - aws-nodejs-dev
Serverless: Stack create finished...
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...

 Serverless Error ---------------------------------------

    unable to get local issuer certificate

 Stack Trace --------------------------------------------

ServerlessError: unable to get local issuer certificate
   at Response.req.send (c:\npm\node_modules\serverless\lib\plugins\aws\provider\awsProvider.js:177:20)
   at Request.<anonymous> (c:\npm\node_modules\serverless\node_modules\aws-sdk\lib\request.js:355:18)
   at Request.callListeners (c:\npm\node_modules\serverless\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
   at Request.emit (c:\npm\node_modules\serverless\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
   at Request.emit (c:\npm\node_modules\serverless\node_modules\aws-sdk\lib\request.js:668:14)
   at Request.transition (c:\npm\node_modules\serverless\node_modules\aws-sdk\lib\request.js:22:10)
   at AcceptorStateMachine.runTo (c:\npm\node_modules\serverless\node_modules\aws-sdk\lib\state_machine.js:14:12)
   at c:\npm\node_modules\serverless\node_modules\aws-sdk\lib\state_machine.js:26:10
   at Request.<anonymous> (c:\npm\node_modules\serverless\node_modules\aws-sdk\lib\request.js:38:9)
   at Request.<anonymous> (c:\npm\node_modules\serverless\node_modules\aws-sdk\lib\request.js:670:12)
   at Request.callListeners (c:\npm\node_modules\serverless\node_modules\aws-sdk\lib\sequential_executor.js:115:18)
   at Request.emit (c:\npm\node_modules\serverless\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
   at Request.emit (c:\npm\node_modules\serverless\node_modules\aws-sdk\lib\request.js:668:14)
   at Request.transition (c:\npm\node_modules\serverless\node_modules\aws-sdk\lib\request.js:22:10)
   at AcceptorStateMachine.runTo (c:\npm\node_modules\serverless\node_modules\aws-sdk\lib\state_machine.js:14:12)
   at c:\npm\node_modules\serverless\node_modules\aws-sdk\lib\state_machine.js:26:10

 Get Support --------------------------------------------
    Docs:          docs.serverless.com
    Bugs:          github.com/serverless/serverless/issues

 Your Environment Information -----------------------------
    OS:                 win32
    Node Version:       6.9.4
    Serverless Version: 1.5.0

**Comment by amit1980** [comment]
The Issue was caused by a network proxy. AWS provider uses following proxies config and pick first in the list. In my case it was picking a wrong proxy that doesn't have access the specific(Sydney) region.
proxy = process.env.proxy
      || process.env.HTTP_PROXY
      || process.env.http_proxy
      || process.env.HTTPS_PROXY
      || process.env.https_proxy;

**Comment by pmuens** [comment]
@amit1980 thanks for posting the solution for this issue 👍
