### ISSUE TITLE
Invoke local Python Error: spawn UNKNOWN 

### ISSUE THREAD

**Issue by jdiazper** [serverless/serverless#3167]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong?
Unable to run `sls invoke local --function hello`

Steps to reproduce this bug are:

1. serverless create --template aws-python --path first-test --name first-test
2. cd first-test
3. sls invoke local --function hello

* What did you expect should have happened?
stdout to return:
```
{
        "message": "Go Serverless v1.0! Your function executed successfully!",
        "input": event
}
```

* What was the config you used?
     OS:                 win32
     Node Version:       6.9.4
     Serverless Version: 1.6.0
     Python Version: 2.7

* What stacktrace or error message from your provider did you see?
```
Error: spawn UNKNOWN
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:380:9)
    at resolve (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:125:22)
    at AwsInvokeLocal.invokeLocalPython (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:124:12)
    at AwsInvokeLocal.invokeLocal (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:113:19)
From previous event:
    at invoke:local:invoke (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:24:10)
    at BbPromise.reduce (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:160:50)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at PluginManager.run (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:160:22)
    at Serverless.run (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:91:31)
    at serverless.init.then (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\bin\serverless:23:50)
```
For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***: 1.6
* ***Operating System***: Windows 10
* ***Stack Trace***: 

```
Error: spawn UNKNOWN
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:380:9)
    at resolve (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:125:22)
    at AwsInvokeLocal.invokeLocalPython (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:124:12)
    at AwsInvokeLocal.invokeLocal (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:113:19)
From previous event:
    at invoke:local:invoke (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:24:10)
    at BbPromise.reduce (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:160:50)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at PluginManager.run (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:160:22)
    at Serverless.run (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:91:31)
    at serverless.init.then (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\bin\serverless:23:50)
```
* ***Provider Error messages***:
spawn UNKNOWN

**Comment by jdiazper** [comment]
Hello again! :)

I've done exactly the same steps but now in Ubuntu 16.4 and it works fine. However it is still not workig on Windows 10.

**Comment by pmuens** [comment]
Thanks for the update @jdiazper

Yes, looks like there smth. wrong with multi platform support. /cc @eahefnawy

**Comment by dschep** [comment]
Yeah, sorry, I didn't test my implementation on windows since I only use Linux and my coworkers use MacOS.

Does the windows python installer not put Python in the `PATH` env var? (or anything else relatively easy to discover)
