### ISSUE TITLE
serverless preuninstall Error: Cannot find module

### ISSUE THREAD

**Issue by JakubMatejka** [serverless/serverless#3251]
# This is a Bug Report

## Description

It looks like the problem in #3079 isn't solved yet. I get this error:

```
[developer-portal] npm install -g serverless@1.7                      master  ✭

> serverless@1.7.0 preuninstall /usr/local/lib/node_modules/serverless
> node ./scripts/preuninstall.js

module.js:472
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/lib/classes/Utils.js:7:36)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/lib/Serverless.js:12:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
npm WARN lifecycle serverless@1.7.0~preuninstall: continuing anyway serverless@1.7.0 preuninstall: `node ./scripts/preuninstall.js`
npm WARN lifecycle Exit status 1
```

(It started with module shelljs and I installed few of the dependencies globally before I realized it is probably a bug in Serverless. ;o)

Similar or dependent issues:
* #3079

## Additional Data

* ***Serverless Framework Version you're using***: 1.7
* ***Operating System***: macOS

**Comment by pmuens** [comment]
Thanks for reporting @JakubMatejka 👍

**Comment by pmuens** [comment]
Just did some more investigation.

Seems like a bug in npms end:

- https://github.com/npm/npm/issues/8806
- https://github.com/npm/npm/issues/12545

**Comment by pmuens** [comment]
Taking this to 1.10 since we have to wait on `npm`...

**Comment by assaflavie** [comment]
So are versions 1.8 & 1.9 simply not installable ATM?

Scratching my head here thinking how to proceed...

**Comment by pmuens** [comment]
@assaflavie no, they're installable. The error might pop up, but it shouldn't affect the installation.

So Serverless should be usable as usual.
