### ISSUE TITLE
Serverless error

### ISSUE THREAD

**Issue by deepan1234** [serverless/serverless#3312]
Serverless: Creating Stack...

  Error --------------------------------------------------

     ServerlessError

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: ServerlessError
    at module.exports.logError.errorHandlingError (/usr/local/lib/node_modules/serverless/lib/classes/Error.js:90:11)
    at BbPromise.resolve.then.catch.e (/usr/local/lib/node_modules/serverless/bin/serverless:26:3)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at __dirname (/usr/local/lib/node_modules/serverless/bin/serverless:24:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:27:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.10.0
     Serverless Version: 1.7.0

**Comment by pmuens** [comment]
Hey @deepan1234 🤔 interesting error message...

Could you please provide a little bit more information? How does your `serverless.yml` look like? How does your `handler` look like?

**Comment by dannycohn** [comment]
S3 is currently down, so deployment will fail. Not sure that this is caused by S3, but I just wanted to point it out. We might see an influx of issues reported over the next few hours

**Comment by pmuens** [comment]
Ah. Yes, true. Nice catch @dannycohn 👍 

We rely on an S3 bucket where we push the deployment artifacts.

BTW. Here's the AWS status board: https://status.aws.amazon.com/

**Comment by HyperBrain** [comment]
@pmuens Due to the S3 outage in us-east-1 also CloudFormation and Lambda is affected. I saw different errors here (internally Lambdas are retrieved from S3 when started and CF information is also loaded from there)

**Comment by HyperBrain** [comment]
FYI: A nice helper with AWS issues is the Personal Health Dashboard:
https://phd.aws.amazon.com/phd/home?region=us-east-1#/dashboard/open-issues

**Comment by pmuens** [comment]
Thanks for the update @HyperBrain 👍

**Comment by HyperBrain** [comment]
Update: Now 27 (!!!) services are affected. Things get worse.

**Comment by deepan1234** [comment]
Works now.. The problem was related to S3 down!!

**Comment by pmuens** [comment]
Thanks for the update @deepan1234 👍
