### ISSUE TITLE
`Cannot find module './stubFalse'` when trying to deploy

### ISSUE THREAD

**Issue by dancrumb** [serverless/serverless#3358]
# This is a Bug Report

## Description

When running `sls deploy`, I get an intermittent error, reportingn`Cannot find module './stubFalse'`.

It happens for no obvious reason and my current resolution is to try again. Generally, it will work the second or third time. I would expect it to work every time.

My serverless.yml file is:

```
service: harvestDone

provider:
  name: aws
  runtime: nodejs4.3

custom:
  babelPresets:
    - env

plugins:
  - serverless-babel-plugin

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
```

## Additional Data
```
Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.9.1
     Serverless Version: 1.8.0
```

* ***Stack Trace***:
```
SLS_DEBUG=* sls deploy
Serverless: Packaging service...
Serverless: Packaging service with compiled files...
 
  Error --------------------------------------------------
 
     Error: Cannot find module './stubFalse' (While processing
     preset: "/Users/danrumney/Projects/harvestDone/.serverless/tmpBabelDirectory/node_modules/babel-preset-env/lib/index.js")

        at Function.Module._resolveFilename (module.js:469:15)

        at Function.Module._load (module.js:417:25)
    at
     Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

        at Object.<anonymous> (/Users/danrumney/Projects/harvestDone/.serverless/tmpBabelDirectory/node_modules/lodash/isBuffer.js:2:17)

        at Module._compile (module.js:570:32)
    at Object.Module._extensions..js
     (module.js:579:10)
    at Module.load (module.js:487:32)

        at tryModuleLoad (module.js:446:12)
    at Function.Module._load
     (module.js:438:3)

 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: Error: Cannot find module './stubFalse' (While processing preset: "/Users/danrumney/Projects/harvestDone/.serverless/tmpBabelDirectory/node_modules/babel-preset-env/lib/index.js")
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/danrumney/Projects/harvestDone/.serverless/tmpBabelDirectory/node_modules/lodash/isBuffer.js:2:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/danrumney/Projects/harvestDone/.serverless/tmpBabelDirectory/node_modules/lodash/isBuffer.js:2:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at module.exports.logError.errorHandlingError (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/lib/classes/Error.js:90:11)
    at BbPromise.resolve.then.catch.e (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/bin/serverless:26:3)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at __dirname (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/bin/serverless:24:9)
    at Object.<anonymous> (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/bin/serverless:27:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by pmuens** [comment]
🤔 this seems to be a problem with the `serverless-babel-plugin` and not with the core framework.

Could you please re-open this issue in the plugins repository. Thanks!

**Comment by dancrumb** [comment]
Thanks - for reference, I opened serverless/serverless-babel-plugin#15
