### ISSUE TITLE
Cross-account pass role is not allowed

### ISSUE THREAD

**Issue by winjer** [serverless/serverless#3374]
# This is a Bug Report

## Description

I have a serverless config that deploys fine using default credentials.

If I set the provider.cfnRole configuration to a valid role (which is working for other cloudformation stacks), then when I run sls deploy I get:

```
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3 (2.97 KB)...
Serverless: Updating Stack...
 
  Serverless Error ---------------------------------------
 
     Cross-account pass role is not allowed
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       6.9.5
     Serverless Version: 1.9.0

```

## Additional Data

* Serverless 1.9.0
* Ubuntu 16.10

**Comment by dfairaizl** [comment]
I see this error as well when using the `--profile` option. It works however using the `AWS_PROFILE` env var - Serverless 1.14.0.

Works:
```
AWS_PROFILE=prodaccess serverless deploy --stage production
```

Does not work:
```
serverless deploy --stage production --profile prodaccess
```

Are AWS_PROFILE and --profile equivalent?

**Comment by pmuens** [comment]
Hey @dfairaizl have you tried the `--aws-profile` option?

We've changed this option so that it's provider specific (in this case we've prefixed `aws-`).

**Comment by dfairaizl** [comment]
Hi @pmuens - Nope that appears to not work either.

```
DBNY-FAIRD-LM:search fairaizld$ SLS_DEBUG=* serverless deploy --aws-profile prodaccess --stage production
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (19.69 MB)...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
...........................Serverless: Deployment failed!
 
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: ReindexLambdaFunction
     - Cross-account pass role is not allowed..
 
  Stack Trace --------------------------------------------
 
ServerlessError: An error occurred while provisioning your stack: ReindexLambdaFunction - Cross-account pass role is not allowed..
    at provider.request.then (/Users/fairaizld/.config/yarn/global/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:109:33)
From previous event:
    at AwsDeploy.monitorStack (/Users/fairaizld/.config/yarn/global/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:26:12)
    at provider.request.then (/Users/fairaizld/.config/yarn/global/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:88:30)
From previous event:
    at AwsDeploy.update (/Users/fairaizld/.config/yarn/global/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:88:8)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/Users/fairaizld/.config/yarn/global/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:105:12)
From previous event:
    at AwsDeploy.updateStack (/Users/fairaizld/.config/yarn/global/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:99:8)
From previous event:
    at Object.aws:deploy:deploy:updateStack [as hook] (/Users/fairaizld/.config/yarn/global/node_modules/serverless/lib/plugins/aws/deploy/index.js:99:10)
    at BbPromise.reduce (/Users/fairaizld/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:234:55)
From previous event:
    at PluginManager.invoke (/Users/fairaizld/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:234:22)
    at PluginManager.spawn (/Users/fairaizld/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:246:17)
    at AwsDeploy.BbPromise.bind.then (/Users/fairaizld/.config/yarn/global/node_modules/serverless/lib/plugins/aws/deploy/index.js:85:48)
From previous event:
    at Object.deploy:deploy [as hook] (/Users/fairaizld/.config/yarn/global/node_modules/serverless/lib/plugins/aws/deploy/index.js:81:10)
    at BbPromise.reduce (/Users/fairaizld/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:234:55)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at PluginManager.invoke (/Users/fairaizld/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:234:22)
    at PluginManager.run (/Users/fairaizld/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:253:17)
    at variables.populateService.then (/Users/fairaizld/.config/yarn/global/node_modules/serverless/lib/Serverless.js:100:33)
From previous event:
    at Serverless.run (/Users/fairaizld/.config/yarn/global/node_modules/serverless/lib/Serverless.js:87:74)
    at serverless.init.then (/Users/fairaizld/.config/yarn/global/node_modules/serverless/bin/serverless:23:50)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       7.6.0
     Serverless Version: 1.14.0
```

**Comment by HyperBrain** [comment]
As you receive a `Cross-account pass role is not allowed`, it seems you're trying to deploy into a different account than the deploying user is in.
Please check your deplyoment user's IAM policy and see if it is allowed to do a sts:assumeRole or sts:passRole into the other account.

Also found this post here:
https://forums.aws.amazon.com/thread.jspa?threadID=244600

**Comment by mayankkumar0072** [comment]
I was also facing the same issue, but after trying this it worked.
 `--stage prod --aws-profile production`
Thanks @pmuens

**Comment by vdanniel** [comment]
Thanks that helped.

**Comment by pmuens** [comment]
Closing since we've updated the way how profiles work. Furthermore there are comments in this thread showing how AWS profiles can be used to make this work.
