### ISSUE TITLE
TypeError: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by thejollyrogers** [serverless/serverless#3414]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong?
serverless deploy
* What did you expect should have happened?
should deply
* What was the config you used?
service: npf-bot # NOTE: update this with your service name

frameworkVersion: ">=1.0.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-east-1
  memorySize: 512
  timeout: 15
  role: arn:aws:iam::redacted:role/redacted::redacted:role/redacted

functions:
  hello:
    handler: bot.handler
    events:
      - http:
        path: path
        method: get
      - http:
        path: path
        method: post
    environment:
      redacted: redacted
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
1.9.0
* ***Operating System***:
mac os
* ***Stack Trace***:
TypeError: Cannot read property 'path' of null
    at AwsCompileApigEvents.getHttpPath (/Users/andrew/.nvm/versions/node/v7.4.0/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js:145:20)
    at _.forEach (/Users/andrew/.nvm/versions/node/v7.4.0/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js:46:28)
    at arrayEach (/Users/andrew/.nvm/versions/node/v7.4.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/Users/andrew/.nvm/versions/node/v7.4.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:9344:14)
    at _.forEach (/Users/andrew/.nvm/versions/node/v7.4.0/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js:42:9)
    at /Users/andrew/.nvm/versions/node/v7.4.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:4970:15
    at baseForOwn (/Users/andrew/.nvm/versions/node/v7.4.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:3020:24)
    at /Users/andrew/.nvm/versions/node/v7.4.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:4939:18
    at Function.forEach (/Users/andrew/.nvm/versions/node/v7.4.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:9344:14)
    at AwsCompileApigEvents.validate (/Users/andrew/.nvm/versions/node/v7.4.0/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js:41:7)
    at deploy:compileEvents (/Users/andrew/.nvm/versions/node/v7.4.0/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/apiGateway/index.js:42:31)
    at BbPromise.reduce (/Users/andrew/.nvm/versions/node/v7.4.0/lib/node_modules/serverless/lib/classes/PluginManager.js:156:50)
From previous event:
    at PluginManager.run (/Users/andrew/.nvm/versions/node/v7.4.0/lib/node_modules/serverless/lib/classes/PluginManager.js:156:22)
    at Serverless.run (/Users/andrew/.nvm/versions/node/v7.4.0/lib/node_modules/serverless/lib/Serverless.js:95:31)
    at serverless.init.then (/Users/andrew/.nvm/versions/node/v7.4.0/lib/node_modules/serverless/bin/serverless:23:50)
    at process._tickCallback (internal/process/next_tick.js:103:7)
* ***Provider Error messages***:
TypeError: Cannot read property 'path' of null
Please report this error. We think it might be a bug.

**Comment by pmuens** [comment]
@thejollyrogers thanks for opening.

Just for the reference: Could you please share how you've resolved this issue? Thanks!

**Comment by thejollyrogers** [comment]
Sure. My serverless.yml file was incorrectly formatted. "path" should have
been indented under -http

**Comment by pmuens** [comment]
Thanks for getting back with the solution @thejollyrogers 👍
