### ISSUE TITLE
Installation warning

### ISSUE THREAD

**Issue by andriytyurnikov** [serverless/serverless#3438]
# This is a Bug Report

## Description

* What went wrong?
Exception messages during global installation process.

## Additional Data
```
> serverless@1.9.0 preuninstall 
Error: Cannot find module 'shelljs/global'
```

* ***Serverless Framework Version you're using***:
serverless@1.10.1 
* ***Operating System***:
OS X 10.12.4, node v6.10.1 (installed with nvm)
* ***Stack Trace***:
```
> serverless@1.9.0 preuninstall /Users/andriytyurnikov/.nvm/versions/node/v6.10.1/lib/node_modules/serverless
> node ./scripts/preuninstall.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'shelljs/global'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/andriytyurnikov/.nvm/versions/node/v6.10.1/lib/node_modules/serverless/lib/Serverless.js:3:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm WARN lifecycle serverless@1.9.0~preuninstall: continuing anyway serverless@1.9.0 preuninstall: `node ./scripts/preuninstall.js`
npm WARN lifecycle Exit status 1
npm WARN gentlyRm not removing /Users/andriytyurnikov/.nvm/versions/node/v6.10.1/bin/serverless as it wasn't installed by /Users/andriytyurnikov/.nvm/versions/node/v6.10.1/lib/node_modules/serverless
npm WARN gentlyRm not removing /Users/andriytyurnikov/.nvm/versions/node/v6.10.1/bin/slss as it wasn't installed by /Users/andriytyurnikov/.nvm/versions/node/v6.10.1/lib/node_modules/serverless
npm WARN gentlyRm not removing /Users/andriytyurnikov/.nvm/versions/node/v6.10.1/bin/sls as it wasn't installed by /Users/andriytyurnikov/.nvm/versions/node/v6.10.1/lib/node_modules/serverless
/Users/andriytyurnikov/.nvm/versions/node/v6.10.1/bin/serverless -> /Users/andriytyurnikov/.nvm/versions/node/v6.10.1/lib/node_modules/serverless/bin/serverless
/Users/andriytyurnikov/.nvm/versions/node/v6.10.1/bin/sls -> /Users/andriytyurnikov/.nvm/versions/node/v6.10.1/lib/node_modules/serverless/bin/serverless
/Users/andriytyurnikov/.nvm/versions/node/v6.10.1/bin/slss -> /Users/andriytyurnikov/.nvm/versions/node/v6.10.1/lib/node_modules/serverless/bin/serverless

> serverless@1.10.1 postinstall /Users/andriytyurnikov/.nvm/versions/node/v6.10.1/lib/node_modules/serverless
> node ./scripts/postinstall.js

/Users/andriytyurnikov/.nvm/versions/node/v6.10.1/lib
└─┬ serverless@1.10.1 
  └── resolve-from@2.0.0 

```

**Comment by pmuens** [comment]
Hey @andriytyurnikov thanks for opening. 👍 

This should've been the last time you've seen this. We've fixed it in 1.10 and updating from this version shouldn't show it again.
