### ISSUE TITLE
Dots in handler file name throws ENOENT no such file or directory error

### ISSUE THREAD

**Issue by coreylight** [serverless/serverless#3455]
# This is a Bug Report

## Description

* What went wrong?
Serverless tried to use the file `/example/handlers/multiple,dots,in,name.js`
* What did you expect should have happened?
Use the file `/example/handlers/multiple.dots.in.name.js`
* What was the config you used?
```
functions:
  multiple-dots-in-name:
    handler: handlers/multiple.dots.in.name.handler
```
* What stacktrace or error message from your provider did you see?
```
Error: Error: ENOENT: no such file or directory, open '/project/example/handlers/multiple,dots,in,name.js'
    at SLSPlugin.getFuncs (/project/dist/index.js:146:15)
    at SLSPlugin.run (/project/dist/index.js:85:12)
    at BbPromise.reduce (/project/example/node_modules/serverless/lib/classes/PluginManager.js:210:55)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
From previous event:
    at PluginManager.invoke (/project/example/node_modules/serverless/lib/classes/PluginManager.js:210:22)
    at PluginManager.run (/project/example/node_modules/serverless/lib/classes/PluginManager.js:225:17)
    at Serverless.run (/project/example/node_modules/serverless/lib/Serverless.js:97:31)
    at serverless.init.then (/project/example/node_modules/serverless/bin/serverless:23:50)
```

I don't know if this is expected or not, so here's the bug report anyway. 🙂
Thanks for the work on Serverless!

## Additional Data

* ***Serverless Framework Version you're using***: `1.8.0`
* ***Operating System***: `macOS 10.12.4`
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by coreylight** [comment]
Shoot, I think this was an error outside of the framework. Was working on a plugin. Closing.
