### ISSUE TITLE
PowerUserAccess policy not allowing creation of API Gateway endpoints

### ISSUE THREAD

**Issue by visualasparagus** [serverless/serverless#352]
This may be related to #351 

Using two projects. One with an Administrator policy and the other with PowerUserAccess policy, I'm having different results deploying endpoints. 

**PowerUserAccess**
API is created but no endpoints are created. The project has one module/function named `lists/add-member`. The command line returns the following error.
```
$ serverless endpoint deploy
Serverless: Deploying endpoints in "development" to the following regions: eu-west-1  
Serverless: | /usr/local/lib/node_modules/serverless/node_modules/bluebird/js/main/promise.js:677
            throw e;
            ^

ServerlessError: The REST API doesn't contain any methods
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/ServerlessError.js:17:11)
    at /usr/local/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:106:17
From previous event:
    at EndpointDeployApiGateway._createDeployment (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:105:15)
From previous event:
    at EndpointDeployApiGateway.endpointDeployApiGateway (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:57:10)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:207:25
    at Array.reduce (native)
    at Object.actions.(anonymous function) [as endpointDeployApiGateway] (/usr/local/lib/node_modules/serverless/lib/Serverless.js:206:25)
    at /usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:390:40
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:381:16
From previous event:
    at EndpointDeploy._deployEndpointsByRegion (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:335:10)
    at EndpointDeploy.<anonymous> (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:287:24)
From previous event:
    at EndpointDeploy._processDeployment (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:281:10)
From previous event:
    at EndpointDeploy.endpointDeploy (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:120:10)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:207:25
    at Array.reduce (native)
    at Serverless.actions.(anonymous function) (/usr/local/lib/node_modules/serverless/lib/Serverless.js:206:25)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:180:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:13:36)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3
```

**AdminstratorAccess**
API is created and also the endpoints. The project has one module/function named `foo/bar`. The command line returns the following.
```
$ serverless endpoint deploy
Serverless: Deploying endpoints in "development" to the following regions: eu-west-1  
Serverless: Successfully deployed endpoints in "development" to the following regions:  
Serverless: eu-west-1 ------------------------  
Serverless:   GET - https://xxxxxx.execute-api.eu-west-1.amazonaws.com/development/foo/bar
```

**Comment by visualasparagus** [comment]
I'm closing this as after further investigations this wasn't an issue withe the power issue in the end, but an issue that the lambda function hadn't been created yet.

**Comment by 954681** [comment]
$ serverless endpoint deploy
Serverless: Deploying endpoints in "development" to the following regions: eu-west-1  
Serverless: | /usr/local/lib/node_modules/serverless/node_modules/bluebird/js/main/promise.js:677
            throw e;
            ^

ServerlessError: The REST API doesn't contain any methods
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/ServerlessError.js:17:11)
    at /usr/local/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:106:17
From previous event:
    at EndpointDeployApiGateway._createDeployment (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:105:15)
From previous event:
    at EndpointDeployApiGateway.endpointDeployApiGateway (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:57:10)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:207:25
    at Array.reduce (native)
    at Object.actions.(anonymous function) [as endpointDeployApiGateway] (/usr/local/lib/node_modules/serverless/lib/Serverless.js:206:25)
    at /usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:390:40
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:381:16
From previous event:
    at EndpointDeploy._deployEndpointsByRegion (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:335:10)
    at EndpointDeploy.<anonymous> (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:287:24)
From previous event:
    at EndpointDeploy._processDeployment (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:281:10)
From previous event:
    at EndpointDeploy.endpointDeploy (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:120:10)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:207:25
    at Array.reduce (native)
    at Serverless.actions.(anonymous function) (/usr/local/lib/node_modules/serverless/lib/Serverless.js:206:25)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:180:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:13:36)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3
