### ISSUE TITLE
postinstall Unexpected token = in JSON on CircleCi Ubuntu

### ISSUE THREAD

**Issue by RickyAbell** [serverless/serverless#3576]
# This is a Bug Report

## Description
Serverless installation fails on postinstall.js step when running on CircleCI with the error `Unhandled rejection SyntaxError: Unexpected token = in JSON at position 1`

* What went wrong?
Serverless fails Postinstall step on CircleCI
* What did you expect should have happened?
For it to install successfully
* What was the config you used?
Ubuntu 14.04 on CircleCI
Node 7.9.0
Serverless 1.12.1
I've also tried with Node 6.10.3 and Serverless 1.11.0
* What stacktrace or error message from your provider did you see?
```
npm i -g serverless@1.12.1
/opt/circleci/nodejs/v7.9.0/bin/serverless -> /opt/circleci/nodejs/v7.9.0/lib/node_modules/serverless/bin/serverless
/opt/circleci/nodejs/v7.9.0/bin/slss -> /opt/circleci/nodejs/v7.9.0/lib/node_modules/serverless/bin/serverless
/opt/circleci/nodejs/v7.9.0/bin/sls -> /opt/circleci/nodejs/v7.9.0/lib/node_modules/serverless/bin/serverless

> serverless@1.12.1 postinstall /opt/circleci/nodejs/v7.9.0/lib/node_modules/serverless
> node ./scripts/postinstall.js

Unhandled rejection SyntaxError: Unexpected token = in JSON at position 1
    at JSON.parse (<anonymous>)
    at exports.parse (/opt/circleci/nodejs/v7.9.0/lib/node_modules/serverless/node_modules/rc/lib/utils.js:15:17)
    at addConfigFile (/opt/circleci/nodejs/v7.9.0/lib/node_modules/serverless/node_modules/rc/index.js:31:20)
    at Array.forEach (native)
    at module.exports (/opt/circleci/nodejs/v7.9.0/lib/node_modules/serverless/node_modules/rc/index.js:44:36)
    at Object.<anonymous> (/opt/circleci/nodejs/v7.9.0/lib/node_modules/serverless/node_modules/get-proxy/index.js:2:25)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/circleci/nodejs/v7.9.0/lib/node_modules/serverless/node_modules/caw/index.js:3:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
``` 

## Additional Data

* ***Serverless Framework Version you're using***: 1.12.1
* ***Operating System***: Ubuntu 14.04

**Comment by brianneisler** [comment]
@pmuens, dove in to this issue just a bit. Seems likely that something is erroring out during the init process of the Serverless class. Probably prudent that we wrap this bit of code in a try/catch to ensure the install process doesn't break if an error is encountered.

https://github.com/serverless/serverless/blob/master/scripts/postinstall.js#L8-L10

**Comment by brianneisler** [comment]
@RickyAbell I followed the module chain and this seems to be associated with the `download` module. However, the only location that we use this module is within the `install` plugin in core and that code should only run when an install/deploy is performed with the serverless framework.  Are you using any plugins by chance?

https://github.com/serverless/serverless/blob/99f90730c099d3f7d4c9ec62fe315d998a6dcf85/lib/plugins/install/install.js#L133

Unfortunately the stack trace is only a partial trace which makes it harder to be sure of what's happening. I've opened this issue to help us with this in the future.

https://github.com/serverless/serverless/issues/3579

Following the code it seems possible that you may have a misconfigured `.npmrc` file. The `get-proxy` module attempts to load `.npmrc` using the `rc` module but it seems to be attempting to parse it as JSON instead of INI. Possibly related to this issue https://github.com/dominictarr/rc/issues/80

**Comment by RickyAbell** [comment]
@brianneisler Nice find, it did turn out to be a misconfigured `.npmrc` file.
Thanks for the help!
