### ISSUE TITLE
Unexpected token : in JSON during deploy

### ISSUE THREAD

**Issue by jtslear** [serverless/serverless#3578]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
A deploy is failing while checking on the update progress.

* What did you expect should have happened?
The update progress to properly determine the status.

* What was the config you used?
https://gist.github.com/jtslear/35ce0fe2c9ffb0a4204e4c9cffed9831

* What stacktrace or error message from your provider did you see?
```
% SLS_DEBUG=1 serverless deploy
Serverless: WARNING: Plugin GoogleDeploy uses deprecated hook before:deploy:initialize
Serverless: WARNING: Plugin GoogleDeploy uses deprecated hook deploy:initialize
Serverless: WARNING: Plugin GoogleDeploy uses deprecated hook deploy:setupProviderConfiguration
Serverless: WARNING: Plugin GoogleDeploy uses deprecated hook before:deploy:compileFunctions
Serverless: Packaging service...
Serverless: Compiling function "first"...
Serverless: Uploading artifacts...
Serverless: Artifacts successfully uploaded...
Serverless: Updating deployment...
Serverless: Checking deployment update progress...

  Error --------------------------------------------------

     Unexpected token : in JSON at position 7

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: Unexpected token : in JSON at position 7
    at provider.request.then.catch (/Users/skajo02/projects/synk/node_modules/serverless-google-cloudfunctions/shared/monitorDeployment.js:51:24)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:234:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:253:17)
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:97:31)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:23:50)


  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.9.5
     Serverless Version: 1.12.1
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.12.1
* ***Operating System***: OSX
* ***serverless-google-cloudfunctions***: 1.0.0

This only appears to be an issue when functions are placed into individual folders.  If I move the function back to the root of the repo the deploy works just fine.

**Comment by pmuens** [comment]
Thanks for reporting @jtslear and trying out the Google Provider integration! 💪 

Could you please re-open this Issue in the Google Plugin repo so that we can track the status there (https://github.com/serverless/serverless-google-cloudfunctions/issues)?

Thanks in advance!
