### ISSUE TITLE
serverless -logs returns invalid date on the start of each line if date is not provided.

### ISSUE THREAD

**Issue by thepont** [serverless/serverless#3594]
# This is a Bug Report

## Description

For bug reports:
* `serverless -logs` attempts to parse the start of a line as a date.
* What did you expect should have happened?
it should return the text unaltered, or atleast if it fails to parse a date it should.
* What was the config you used?

```
service: test-config
provider:
  name: aws
  runtime: java8
  region: ap-southeast-2
package:
  artifact: target/serviceReports.jar
functions:
  test:
    handler: com.blueflag.app.report.serverless.invocation.OtherHandler
    timeout: 300
    events:
      - http: GET /test
```

* What stacktrace or error message from your provider did you see?

## Additional Data

* ***Serverless Framework Version you're using***: 1.2.0, 1.13.0
* ***Operating System***: Linux 4.4.0-75-generic #96-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
* ***Stack Trace***:
```
START RequestId: 2e7fade2-3612-11e7-abc5-b1a3244525e1 Version: $LATEST
Deprecation warning: value provided is not in a recognized ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: Class not found: com.blueflag.app.report.serverless.OtherHandler: class java.lang.ClassNotFoundException
java.lang.ClassNotFoundException: com.blueflag.app.report.serverless.OtherHandler
, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/home/paulesson/.nvm/versions/node/v6.8.1/lib/node_modules/serverless/node_modules/moment/moment.js:309:98)
    at configFromString (/home/paulesson/.nvm/versions/node/v6.8.1/lib/node_modules/serverless/node_modules/moment/moment.js:2048:32)
    at configFromInput (/home/paulesson/.nvm/versions/node/v6.8.1/lib/node_modules/serverless/node_modules/moment/moment.js:2408:13)
    at prepareConfig (/home/paulesson/.nvm/versions/node/v6.8.1/lib/node_modules/serverless/node_modules/moment/moment.js:2391:13)
    at createFromConfig (/home/paulesson/.nvm/versions/node/v6.8.1/lib/node_modules/serverless/node_modules/moment/moment.js:2358:44)
    at createLocalOrUTC (/home/paulesson/.nvm/versions/node/v6.8.1/lib/node_modules/serverless/node_modules/moment/moment.js:2445:16)
    at local__createLocal (/home/paulesson/.nvm/versions/node/v6.8.1/lib/node_modules/serverless/node_modules/moment/moment.js:2449:16)
    at utils_hooks__hooks (/home/paulesson/.nvm/versions/node/v6.8.1/lib/node_modules/serverless/node_modules/moment/moment.js:16:29)
    at formatLambdaLogEvent (/home/paulesson/.nvm/versions/node/v6.8.1/lib/node_modules/serverless/lib/plugins/aws/logs/index.js:94:32)
    at results.events.forEach.e (/home/paulesson/.nvm/versions/node/v6.8.1/lib/node_modules/serverless/lib/plugins/aws/logs/index.js:130:34)
    at Array.forEach (native)
    at provider.request.then.results (/home/paulesson/.nvm/versions/node/v6.8.1/lib/node_modules/serverless/lib/plugins/aws/logs/index.js:129:26)
    at tryCatcher (/home/paulesson/.nvm/versions/node/v6.8.1/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/paulesson/.nvm/versions/node/v6.8.1/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/paulesson/.nvm/versions/node/v6.8.1/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/paulesson/.nvm/versions/node/v6.8.1/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:612:10)
Invalid date	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)

END RequestId: 2e7fade2-3612-11e7-abc5-b1a3244525e1
REPORT RequestId: 2e7fade2-3612-11e7-abc5-b1a3244525e1	Duration: 7.74 ms	Billed Duration: 100 ms 	Memory Size: 1024 MB	Max Memory Used: 25 MB	
```

**Comment by daroot** [comment]
I just commented on the root cause of this over in #1796.   There's a case of checking a Date() against the string "Invalid Date" with identity `===` rather than equality `==` in the log processing code.

**Comment by pmuens** [comment]
Thanks for looking into this @daroot 👍 I just commented in #1796.

Would be really nice to get a PR for this 💯
