### ISSUE TITLE
serverless-google-cloudfunctions plugin does not allow uppercase project names

### ISSUE THREAD

**Issue by gorbypark** [serverless/serverless#3656]
serverless-google-cloudfunctions 1.0.0 (or possibly the serveless cli client itself) throws an error when running the command ```serverless deploy``` while the serverless.yml file contains an uppercase project name.
```
provider:
  name: google
  runtime: nodejs
  project: WBGIS
  credentials: /Users/xxxxxxx/Documents/keys/keyfile.json
  memorySize: 128
  timeout: 5s
```
results in this error:
```
  Error --------------------------------------------------

     Error: Invalid value 'WBGIS'. Values must match the
     following regular expression: '(?:(?:[-a-z0-9]{1,63}\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z](?:[-a-z0-9]{0,61
}[a-z0-9])?))'
```

**Comment by pmuens** [comment]
Thanks for reporting @gorbypark 👍 

Could you export he env variable `SLS_DEBUG=*` so that we can see the strack trace where this error is thrown?

This way we know if this repo or the Google Cloud Function plugin repo is the place where it should be fixed. Thanks 👍

**Comment by gorbypark** [comment]
Sure.
```
    at PluginManager.invoke (/Users/xxxxx/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:234:22)
    at PluginManager.spawn (/Users/xxxxx/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:246:17)
    at Deploy.BbPromise.bind.then (/Users/xxxxx/.config/yarn/global/node_modules/serverless/lib/plugins/deploy/deploy.js:79:48)
From previous event:
    at Object.before:deploy:deploy [as hook] (/Users/xxxxx/.config/yarn/global/node_modules/serverless/lib/plugins/deploy/deploy.js:77:8)
    at BbPromise.reduce (/Users/xxxxx/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:234:55)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at PluginManager.invoke (/Users/xxxxx.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:234:22)
    at PluginManager.run (/Users/xxxxx/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:253:17)
    at variables.populateService.then (/Users/xxxxx/.config/yarn/global/node_modules/serverless/lib/Serverless.js:96:33)
From previous event:
    at Serverless.run (/Users/xxxxx/.config/yarn/global/node_modules/serverless/lib/Serverless.js:87:74)
    at serverless.init.then (/Users/xxxxx/.config/yarn/global/node_modules/serverless/bin/serverless:23:50)
```

**Comment by pmuens** [comment]
Hey @gorbypark thanks for sharing the stack trace! 👍 

This limitation is something on Googles end. They don't support Uppercase names. We could re-open an issue in the Google Provider plugin repository and maybe add a validation there so that a more user friendly error message is displayed.

Thanks for reporting!

**Comment by gorbypark** [comment]
> Unfortunately this limitation is something on Googles end. They don't support Uppercase names. We could re-open an issue in the Google Provider plugin repository and maybe add a validation there so that a more user friendly error message is displayed.

Ok, thanks.  It's weird because they actually do allow uppercase names (WBGIS is an actual project).  I guess their API must differ from their web UI.

**Comment by pmuens** [comment]
> I guess their API must differ from their web UI.

Yes, that seems to be the case since the data is passed directly to the API which then validates it and returns the error message you've provided.
