### ISSUE TITLE
npm install broken

### ISSUE THREAD

**Issue by nenti** [serverless/serverless#3728]
`npm version 5.0.2`
`serverless 1.14.0`

NPM Debug:
```
144 silly pacote remote manifest for get-stream@https://registry.npmjs.org/get-stream/-/get-stream-3.0.0.tgz fetched in 13ms
145 verbose stack TypeError: Cannot read property 'find' of undefined
145 verbose stack     at opts.integrity.digests.find.hash (C:\Users\piust\AppData\Roaming\npm\node_modules\npm\node_modules\ssri\index.js:264:33)
145 verbose stack     at Array.find (native)
145 verbose stack     at Transform.on (C:\Users\piust\AppData\Roaming\npm\node_modules\npm\node_modules\ssri\index.js:263:15)
145 verbose stack     at emitNone (events.js:91:20)
145 verbose stack     at Transform.emit (events.js:188:7)
145 verbose stack     at endReadableNT (_stream_readable.js:974:12)
145 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:80:11)
145 verbose stack     at process._tickCallback (internal/process/next_tick.js:104:9)
146 verbose cwd C:\Users\piust\Documents\Masterbaker\serverless\products
147 verbose Windows_NT 10.0.15063
148 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\piust\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "serverless"
149 verbose node v7.7.2
150 verbose npm  v5.0.2
151 error Cannot read property 'find' of undefined
152 verbose exit [ 1, true ]
```

**Comment by pmuens** [comment]
Thank for reporting @nenti 👍 

Dropping https://github.com/Polymer/polymer-cli/issues/784 where this problem also occurred.

**Comment by superandrew213** [comment]
Updating to latest npm (5.0.3 at the moment) fixes this for me.

**Comment by nenti** [comment]
Me too. Thx! `npm i -g npm`

**Comment by pmuens** [comment]
Great 👍 

Thanks @superandrew213 for providing the solution and thanks @nenti for confirming!
