### ISSUE TITLE
Latest Version Fails Post install when permissions are tight

### ISSUE THREAD

**Issue by jtslear** [serverless/serverless#3757]
# This is a Bug Report

## Description

For bug reports:
* What went wrong? 
Post install for serverless fails

* What did you expect should have happened?
Post install to complete

* What was the config you used?
N/A

* What stacktrace or error message from your provider did you see?
```
> serverless@1.15.1 postinstall /usr/local/lib/node_modules/serverless
> node ./scripts/postinstall.js

/usr/local/lib/node_modules/serverless/node_modules/write-file-atomic/index.js:132
    throw err
    ^

Error: EACCES: permission denied, open '/root/.serverlessrc.3405600948'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Function.writeFileSync [as sync] (/usr/local/lib/node_modules/serverless/node_modules/write-file-atomic/index.js:117:17)
    at createConfig (/usr/local/lib/node_modules/serverless/lib/utils/config/index.js:30:19)
    at getConfig (/usr/local/lib/node_modules/serverless/lib/utils/config/index.js:44:5)
    at Object.get (/usr/local/lib/node_modules/serverless/lib/utils/config/index.js:90:18)
    at isTrackingDisabled (/usr/local/lib/node_modules/serverless/lib/utils/isTrackingDisabled.js:6:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/lib/utils/segment.js:9:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/lib/classes/Utils.js:14:17)

```

Similar or dependent issues:
* #3753
* Specifically: https://github.com/serverless/serverless/pull/3753#discussion_r120884591

## Additional Data
This is failing on circleci 2.0 where permission are apparently too strict.

* ***Serverless Framework Version you're using***: 1.15
* ***Operating System***: Debian

**Comment by arthurdelight4** [comment]
We have a docker build image that started failing in the exact same manner

**Comment by rupakg** [comment]
I can reproduce the error in a docker image build.

**Comment by rupakg** [comment]
@jtslear @abalone0204 temporary fix by doing: 

```
npm config set unsafe-perm=true
```
Investigating root cause. Thanks to @alexdebrie for temp workaround.

**Comment by brianneisler** [comment]
Looking in to this now...

**Comment by pmuens** [comment]
Nice catch! Investigating...

**Comment by pmuens** [comment]
The root cause of this problem is described here: https://stackoverflow.com/questions/25011703/write-file-in-home-directory-when-running-npm-install
