### ISSUE TITLE
 GraphQL error: Lambda services-publishService threw an Error during invokation

### ISSUE THREAD

**Issue by pgali** [serverless/serverless#3946]
# This is a (Bug Report / Feature Proposal)
 
## Description
When invoking sls deploy, last step of deploy fails. It fails because of an invocation error. Looks like sls is trying to publish to serverless platform. Wondering if there is a flag that I am unaware of that can be used to disable publishing to serverless platform or what should I do to fix this error.

For bug reports:
* What went wrong?
When I invoke sls deploy, deploy fails because of publish service failing due to an error

* What did you expect should have happened?
The call should not have failed. Any chance we can disable this call? I do not want to push
* What was the config you used?
None
* What stacktrace or error message from your provider did you see?

```
Error --------------------------------------------------

  GraphQL error: Lambda services-publishService threw an Error during invokation

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: GraphQL error: Lambda services-publishService threw an Error during invokation
    at new ApolloError (/usr/local/lib/node_modules/serverless/node_modules/apollo-client/apollo.umd.js:2075:28)
    at /usr/local/lib/node_modules/serverless/node_modules/apollo-client/apollo.umd.js:2798:33
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
From previous event:
    at fetchEndpoint.then.endpoint (/usr/local/lib/node_modules/serverless/lib/plugins/platform/platform.js:176:16)
From previous event:
    at provider.getAccountId.then.accountId (/usr/local/lib/node_modules/serverless/lib/plugins/platform/platform.js:127:51)
From previous event:
    at Platform.publishService (/usr/local/lib/node_modules/serverless/lib/plugins/platform/platform.js:126:41)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:217:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:217:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:236:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:107:33)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:94:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:32:50)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           7.2.1
     Serverless Version:     1.17.0
```

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by brianneisler** [comment]
@pgali you can avoid publishing by logging out of the serverless platform `sls logout`.

I've just opened up a PR for disabling publish on service by service basis https://github.com/serverless/serverless/pull/3950

**Comment by plfx** [comment]
Hello @pgali 

We have fixed a bug in this area. If you `sls login` once more and try deploying your service, do you still see this error?

**Comment by pmuens** [comment]
Closing since this should've been fixed in the meantime.

Feel free to re-open if this is still an issue.
