### ISSUE TITLE
Exception thrown when attempting to set a local env variable

### ISSUE THREAD

**Issue by johnhaitas** [serverless/serverless#399]
`$ serverless env set -k MY_KEY -v my_value -s local` returns the following exception

```
/path/to/serverless/node_modules/bluebird/js/main/promise.js:677
            throw e;
            ^

TypeError: Cannot read property 'length' of undefined
    at EnvSet.cliPromptSelectRegion (/path/to/serverless/lib/ServerlessPlugin.js:272:60)
    at /path/to/serverless/lib/actions/EnvSet.js:146:24
From previous event:
    at EnvSet._prompt (/path/to/serverless/lib/actions/EnvSet.js:145:10)
From previous event:
    at EnvSet.envSet (/path/to/serverless/lib/actions/EnvSet.js:110:10)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at /path/to/serverless/lib/Serverless.js:212:25
    at Array.reduce (native)
    at Serverless.actions.(anonymous function) (/path/to/serverless/lib/Serverless.js:211:25)
    at Serverless.command (/path/to/serverless/lib/Serverless.js:182:44)
    at Object.<anonymous> (/path/to/serverless/bin/serverless:13:36)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

Calling ``$ serverless env set -k MY_KEY -v my_value` and interactively selecting `local` produces the same result.

I am running e70a7c6 on the `master` branch

**Comment by visualasparagus** [comment]
This seems to occur with anything related to the `local` stage. Also `slss env list`

**Comment by thedevkit** [comment]
+1

Interestingly, specifying the region with `-r <region>` elminates the issue.

**Comment by eahefnawy** [comment]
Thanks a lot for reporting guys! It was a tiny fix :)
