### ISSUE TITLE
SNS subscription only possible in raw cloud formation markup

### ISSUE THREAD

**Issue by lohrmann** [serverless/serverless#4001]
# This is a Bug Report

## Description

- Defined lambda subscription as a property of an SNS topic (like so) in yaml format
```yaml
Properties:
    Subscription:
        Endpoint: {"Fn::GetAtt" : [ "abcLambdaFunction" , "Arn" ]}
        Protocol: "lambda"
```
- This results in the following error
`An error occurred while provisioning your stack: abcSNS - Value of property Subscription must be of type List.` 
- Changing the format to raw cloud formation works (like so)
```
Properties:
    "Subscription": [{"Endpoint": {"Fn::GetAtt" : [ "abcLambdaFunction" , "Arn" ]}, "Protocol": "lambda"}]
```
- I would have expected it to also work when providing this information in yaml format

## Additional Data

* ***Serverless Framework Version you're using***: 1.17.0
* ***Operating System***: darwin
* ***Stack Trace***:
```
ServerlessError: An error occurred while provisioning your stack: ScrapingSNS - Value of property Subscription must be of type List.
    at provider.request.then (/Users/daniel/.nvm/versions/node/v6.10.2/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:109:33)
From previous event:
    at AwsDeploy.monitorStack (/Users/daniel/.nvm/versions/node/v6.10.2/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:26:12)
    at provider.request.then (/Users/daniel/.nvm/versions/node/v6.10.2/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:88:30)
From previous event:
    at AwsDeploy.update (/Users/daniel/.nvm/versions/node/v6.10.2/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:88:8)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/Users/daniel/.nvm/versions/node/v6.10.2/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:105:12)
From previous event:
    at AwsDeploy.updateStack (/Users/daniel/.nvm/versions/node/v6.10.2/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:99:8)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/Users/daniel/.nvm/versions/node/v6.10.2/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:125:39)
From previous event:
    at Object.aws:deploy:deploy:updateStack [as hook] (/Users/daniel/.nvm/versions/node/v6.10.2/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:121:10)
    at BbPromise.reduce (/Users/daniel/.nvm/versions/node/v6.10.2/lib/node_modules/serverless/lib/classes/PluginManager.js:217:55)
From previous event:
    at PluginManager.invoke (/Users/daniel/.nvm/versions/node/v6.10.2/lib/node_modules/serverless/lib/classes/PluginManager.js:217:22)
    at PluginManager.spawn (/Users/daniel/.nvm/versions/node/v6.10.2/lib/node_modules/serverless/lib/classes/PluginManager.js:229:17)
    at AwsDeploy.BbPromise.bind.then (/Users/daniel/.nvm/versions/node/v6.10.2/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:91:48)
From previous event:
    at Object.deploy:deploy [as hook] (/Users/daniel/.nvm/versions/node/v6.10.2/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:87:10)
    at BbPromise.reduce (/Users/daniel/.nvm/versions/node/v6.10.2/lib/node_modules/serverless/lib/classes/PluginManager.js:217:55)
From previous event:
    at PluginManager.invoke (/Users/daniel/.nvm/versions/node/v6.10.2/lib/node_modules/serverless/lib/classes/PluginManager.js:217:22)
    at PluginManager.run (/Users/daniel/.nvm/versions/node/v6.10.2/lib/node_modules/serverless/lib/classes/PluginManager.js:236:17)
    at variables.populateService.then (/Users/daniel/.nvm/versions/node/v6.10.2/lib/node_modules/serverless/lib/Serverless.js:107:33)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at Serverless.run (/Users/daniel/.nvm/versions/node/v6.10.2/lib/node_modules/serverless/lib/Serverless.js:94:74)
    at serverless.init.then (/Users/daniel/.nvm/versions/node/v6.10.2/lib/node_modules/serverless/bin/serverless:32:50)
```
* ***Provider Error messages***:

**Comment by pmuens** [comment]
Hey @lohrmann thanks for opening! 👍

It looks like the `YAML` formatting is not correct. Here's the correct YML which should do the trick:

```yml
Properties:
  Subscription:
  - Endpoint:
      Fn::GetAtt:
      - abcLambdaFunction
      - Arn
    Protocol: lambda
```

Feel free to comment / Re-open if this issue still persists. 👍

**Comment by lohrmann** [comment]
Got it, thanks @pmuens ! I was basing the formatting off of [this example](https://serverless.com/framework/docs/providers/aws/guide/functions/) (section _Another example_):
```yaml
Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket"} ] ] }
```

**Comment by pmuens** [comment]
Great! Thanks for confirming @lohrmann 👍

Glad to hear that this resolved your issue!

**Comment by lohrmann** [comment]
Happy to do it — but will only get around to it this weekend.

**Comment by pmuens** [comment]
> Happy to do it

Nice! Thanks for jumping into this @lohrmann 👍

> but will only get around to it this weekend.

No pressure! Just ping us once you have something to show or have any questions 👍
