### ISSUE TITLE
serverless stuck and log issue

### ISSUE THREAD

**Issue by bebbi** [serverless/serverless#4163]
# This is a (Bug Report / Feature Proposal)
Bug

## Description
My stack has a s3 bucket and some cloudfront.

I `serverless deploy` the stack and then sync the content into the bucket using aws-cli.
Then I `serverless remove`.

First time I do it, it says

`An error occurred while provisioning your stack: WebAppS3Bucket - The bucket you tried to delete is not empty.`

Which is slightly confusing because of the earlier serverless log lines which seem to take care of this:

```
Serverless: Getting all objects in S3 bucket...
Serverless: Removing objects in S3 bucket...
```

But running the command again then gives:

`The specified bucket does not exist`

At this stage, the cloudformation stack exists but the tool is stuck with this error, whether try to deploy or remove.

For bug reports:
* What went wrong?

serverless doesn't empty buckets even if it seems to say so.

Instead, serverless gets stuck and the only solution appears to be removing the stack and all associated resources manually?

* What did you expect should have happened?

Serverless either removes objects in the buckets or tells me to do it before it can resume.
Serverless doesn't get stuck with what seems to be an invalid stack.

Finally, as discussed in #3964, have an option to force taking down the stack or something.

* What was the config you used?
Excerpts:

    ...
    provider:
      name: aws
      region: us-east-1
    resources:
      Resources:
        WebAppS3Bucket:
          ...
        WebAppS3BucketPolicy:
          Type: AWS::S3::BucketPolicy
          Properties:
            Bucket:
              Ref: WebAppS3Bucket
            PolicyDocument:
              Statement:
                - Sid: PublicReadGetObject
                  Effect: Allow
                  Principal: "*"
                  Action:
                  - s3:GetObject
                  Resource: arn:aws:s3:::${self:custom.s3Bucket}/*
        WebAppCloudFrontDistribution:

* What stacktrace or error message from your provider did you see?

```
ServerlessError: The specified bucket does not exist
    at Response.req.send (/Users/myself/Documents/work/code/mycode/my-app/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:180:20)
    at Request.<anonymous> (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at Request.RESET_RETRY_STATE (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/event_listeners.js:443:9)
    at Request.callListeners (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/sequential_executor.js:101:18)
    at Request.emit (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at Request.requestBucketRegion (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/services/s3.js:601:14)
    at Request.callListeners (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/sequential_executor.js:101:18)
    at Request.emit (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at IncomingMessage.onEnd (/Users/myself/Documents/work/code/mycode/my-app/node_modules/aws-sdk/lib/event_listeners.js:269:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
From previous event:
    at persistentRequest (/Users/myself/Documents/work/code/mycode/my-app/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:167:14)
    at doCall (/Users/myself/Documents/work/code/mycode/my-app/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:146:9)
    at BbPromise (/Users/myself/Documents/work/code/mycode/my-app/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:157:14)
From previous event:
    at persistentRequest (/Users/myself/Documents/work/code/mycode/my-app/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:144:38)
    at AwsProvider.request (/Users/myself/Documents/work/code/mycode/my-app/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:160:12)
    at AwsDeploy.getMostRecentObjects (/Users/myself/Documents/work/code/mycode/my-app/node_modules/serverless/lib/plugins/aws/deploy/lib/checkForChanges.js:33:26)
From previous event:
    at AwsDeploy.checkForChanges (/Users/myself/Documents/work/code/mycode/my-app/node_modules/serverless/lib/plugins/aws/deploy/lib/checkForChanges.js:20:8)
From previous event:
    at Object.aws:deploy:deploy:checkForChanges [as hook] (/Users/myself/Documents/work/code/mycode/my-app/node_modules/serverless/lib/plugins/aws/deploy/index.js:102:10)
    at BbPromise.reduce (/Users/myself/Documents/work/code/mycode/my-app/node_modules/serverless/lib/classes/PluginManager.js:242:55)
From previous event:
    at PluginManager.invoke (/Users/myself/Documents/work/code/mycode/my-app/node_modules/serverless/lib/classes/PluginManager.js:242:22)
    at PluginManager.spawn (/Users/myself/Documents/work/code/mycode/my-app/node_modules/serverless/lib/classes/PluginManager.js:254:17)
    at AwsDeploy.BbPromise.bind.then (/Users/myself/Documents/work/code/mycode/my-app/node_modules/serverless/lib/plugins/aws/deploy/index.js:91:48)
From previous event:
    at Object.deploy:deploy [as hook] (/Users/myself/Documents/work/code/mycode/my-app/node_modules/serverless/lib/plugins/aws/deploy/index.js:87:10)
    at BbPromise.reduce (/Users/myself/Documents/work/code/mycode/my-app/node_modules/serverless/lib/classes/PluginManager.js:242:55)
From previous event:
    at PluginManager.invoke (/Users/myself/Documents/work/code/mycode/my-app/node_modules/serverless/lib/classes/PluginManager.js:242:22)
    at PluginManager.run (/Users/myself/Documents/work/code/mycode/my-app/node_modules/serverless/lib/classes/PluginManager.js:261:17)
    at variables.populateService.then (/Users/myself/Documents/work/code/mycode/my-app/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (/Users/myself/Documents/work/code/mycode/my-app/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/Users/myself/Documents/work/code/mycode/my-app/node_modules/serverless/bin/serverless:39:50)
```

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
Possibly related:
* #3964
* #1877 (closed)

## Additional Data

* ***Serverless Framework Version you're using***:
1.20.2
* ***Operating System***:
osx
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment]
Thanks for opening @bebbi 👍

Also related to https://github.com/serverless/serverless/issues/3928

**Comment by bebbi** [comment]
@pmuens One thing that I just noticed:
- I got the `The specified bucket does not exist` again with a different deployment, this time after a simple lambda code update and no change to resources. Resources are a very simple s3 bucket and a ddb, and the only change was a new lib import and function call.

The `--force` option may be helpful here, but it's a problem if it clears our stack and its url. Because then I need to go update all dependent deploys and have downtime which is not the original automation idea..

Can there be a "soft" force remove where endpoint urls are maintained?

**Comment by pmuens** [comment]
Thanks for the update @bebbi 👍

> The --force option may be helpful here, but it's a problem if it clears our stack and its url. Because then I need to go update all dependent deploys and have downtime which is not the original automation idea..

> Can there be a "soft" force remove where endpoint urls are maintained?

🤔 that could be a feasible extension. However we need to define what resources shouldn't be affected when doing a "soft" force.

**Comment by pmuens** [comment]
Closing since this is quite a stale issue and we've published newer versions with fixes in the past.

Feel free to re-open if this issue is still around.
