### ISSUE TITLE
Cognito Trigger Configuration and Fn::GetAtt - Circular Dependency Issue

### ISSUE THREAD

**Issue by pgali** [serverless/serverless#4170]
# This is a (Bug Report / Feature Proposal)

## Description

Currently using SLS 1.19, trying to get CognitoPool event configured, but Cloud Formation throws errors when Fn::GetAtt is called as part of the environment variable setup. Its complaining about circular dependency.

When I comment out the environment variable definition, serverless deploys without any issue.

Based on #4039 this is a valid bug and work around does not work for me because this forces me to not be able to define a cognito pool and corresponding trigger events 

Can someone try to create a new pool, configure a event trigger for post confirmation and pass in the pool ID to another lambda function.

For bug reports:

What went wrong?
Fn::GetAtt throws circular dependency error.
I need the ARN name to be passed to other lambda functions.

What did you expect should have happened?
What was the config you used?
service: users

provider:
  name: aws
  runtime: java8
  memorySize: 512
  stage: dev
  region: us-east-1

  custom:
    stage: ${opt:stage, self:provider.stage}

  environment:
    AWS_STAGE: ${self:provider.custom.stage}-
    DYNAMODB_TABLE: ${self:provider.environment.AWS_STAGE}${self:service}
    USER_POOL:
       'Fn::GetAtt': [ CognitoUserPoolMyUserPool, Arn ]
  

functions:
    postconfirmation:
      name: ${self:provider.custom.stage}-postconfirmation
      handler: com.XXX.users.handlers.PostConfirmationHandler
      events:
        - cognitoUserPool:
           pool: MyUserPool
           trigger: PostConfirmation

resources:
  Resources:
    CognitoUserPoolMyUserPool:
        Type: AWS::Cognito::UserPool
        Properties:
          AdminCreateUserConfig:
            AllowAdminCreateUserOnly: true
          UserPoolName: ${self:provider.custom.stage}-mypool
          Schema:
            - AttributeDataType: String
              Mutable: true
              Name: role
What stacktrace or error message from your provider did you see?
 Error --------------------------------------------------

  The CloudFormation template is invalid: Circular dependency between resources: [PostconfirmationLambdaFunction, PostconfirmationLambdaVersiony9d6So9mzrgPdQT1h0S2XJakfA3oQ2csfG0hikKoQ, CognitoUserPoolMyUserPool, PostconfirmationLambdaPermissionCognitoUserPoolMyUserPoolTriggerSourcePostConfirmation]

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: The CloudFormation template is invalid: Circular dependency between resources: [PostconfirmationLambdaFunction, PostconfirmationLambdaVersiony9d6So9mzrgPdQT1h0S2XJakfA3oQ2csfG0hikKoQ, CognitoUserPoolMyUserPool, PostconfirmationLambdaPermissionCognitoUserPoolMyUserPoolTriggerSourcePostConfirmation]
    at provider.request.catch (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:25:13)
From previous event:
    at AwsDeploy.validateTemplate (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:20:12)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:117:39)
From previous event:
    at Object.aws:deploy:deploy:validateTemplate [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:113:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:236:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:236:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:248:17)
    at AwsDeploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:91:48)
From previous event:
    at Object.deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:87:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:236:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:236:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:255:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:39:50)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           7.2.1
     Serverless Version:     1.19.0

Similar or dependent issues:
* #4039

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment]
Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.
