### ISSUE TITLE
Using an object for requestTemplates breaks endpoint deployment

### ISSUE THREAD

**Issue by jagthedrummer** [serverless/serverless#420]
With PR #409 it looks like `requestTemplates` in `s-funtion.json` can be an object instead of a string.

I'm trying to set mine with this:

```
"requestTemplates": {
  "application/json": {"foo": "$input.params('foo')"}
}
```

and I'm getting this error when I run 'sls endpoint deploy':

```
$ sls endpoint deploy
Serverless: Deploying endpoints in "development" to the following regions: us-east-1  
Serverless: - /usr/local/lib/node_modules/serverless/node_modules/bluebird/js/main/promise.js:677
            throw e;
            ^

ServerlessError: No integration defined for method
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/ServerlessError.js:17:11)
    at /usr/local/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:105:19
From previous event:
    at EndpointDeployApiGateway._createDeployment (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:104:17)
From previous event:
    at EndpointDeployApiGateway.endpointDeployApiGateway (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:56:12)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:212:25
    at Array.reduce (native)
    at Object.actions.(anonymous function) [as endpointDeployApiGateway] (/usr/local/lib/node_modules/serverless/lib/Serverless.js:211:25)
    at /usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:373:42
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:364:18
From previous event:
    at EndpointDeploy._deployEndpointsByRegion (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:319:12)
    at EndpointDeploy.<anonymous> (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:257:26)
From previous event:
    at EndpointDeploy._processDeployment (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:251:12)
From previous event:
    at EndpointDeploy.endpointDeploy (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:126:12)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:212:25
    at Array.reduce (native)
    at Serverless.actions.(anonymous function) (/usr/local/lib/node_modules/serverless/lib/Serverless.js:211:25)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:182:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:13:36)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

If I change my config to this it works:

```
"requestTemplates": {
  "application/json": "{\"foo\": \"$input.params('foo')\"}"
}
```

**Comment by jagthedrummer** [comment]
Oops, should have mentioned that I'm on serverless v 0.0.15, which looks like it should include the PR in question, if I'm reading the commit history correctly.

**Comment by Nopik** [comment]
I think that the string need to be valid json. And `"{ \"foo\": '42' }"` isnt valid json, but `"{ \"foo\": \"42\" }"` is.

**Comment by jagthedrummer** [comment]
@Nopik my string representation works just fine. I'm trying to get the object notation to work and that is what's giving me problems.

**Comment by Nopik** [comment]
Wait, are you constantly getting that error? I've seen it happening, randomly, but wasn't able to track it yet. Do you have some steps to reproduce it reliably?

**Comment by jagthedrummer** [comment]
Yes, I'm constantly getting that error with the object notation. And constantly not getting it if I switch to string notation.

I just generated the `greetings/hello` module as shown in the docs:

```
serverless module create -m greetings -f hello
```

And then made some slight modifications to `s-function.json` to try to pass some query params.

Here's my entire config:

```
{
  "functions": {
    "hello": {
      "custom": {
        "excludePatterns": [],
        "envVars": []
      },
      "handler": "modules/greetings/hello/handler.handler",
      "timeout": 6,
      "memorySize": 1024,
      "eventSourceArn": "",
      "endpoints": [
        {
          "path": "greetings/hello",
          "method": "GET",
          "authorizationType": "none",
          "apiKeyRequired": false,
          "requestParameters": {
            "integration.request.querystring.foo": "method.request.querystring.foo"
          },
          "requestTemplates": {
            "application/json": {"foo": "$input.params('foo')"}
          },
          "responses": {
            "400": {
              "statusCode": "400"
            },
            "default": {
              "statusCode": "200",
              "responseParameters": {},
              "responseModels": {},
              "responseTemplates": {
                "application/json": ""
              }
            }
          }
        }
      ]
    }
  }
}
```

**Comment by erikerikson** [comment]
The 0.0.15 tag omits that change.  I'm not sure why.

**Comment by erikerikson** [comment]
There was a report that it was included in 0.0.16 but that was rolled back for a reason I am unaware of.

You can temporarily patch with the changes to EndpointBuildApiGateway.js shown here:
https://github.com/serverless/serverless/commit/8be8d9a8c5e3e22ef0b616dd3d316e644b9fea42

**Comment by eahefnawy** [comment]
oh sorry about delaying this guys. We haven't made a release for a while cause we've been hardcore on investigating supporting event sources. This should be available in the next release.

**Comment by jagthedrummer** [comment]
Ah-ha! Any ETA on when the next release will be?

**Comment by erikerikson** [comment]
They're making a big pushing for 1.0.0.  Holidays and whatnot created a bit of slowdown.

**Comment by kenji-siu-bitgamelabs** [comment]
Same issue here. Look forward to releasing.

**Comment by erikerikson** [comment]
@kenji-siu-bitgamelabs this should be out in modern builds

**Comment by flomotlik** [comment]
We're going to rework our template integration with the next release of serverless which should fix this issue. I'm going to close the issue for now
