### ISSUE TITLE
 Could not locate deployment bucket. Error: Access Denied

### ISSUE THREAD

**Issue by jgaerke** [serverless/serverless#4230]
# This is a Bug Report

## Description
* Could not locate deployment bucket. Error: Access Denied
* See serverless.yml config & permissions below

## Additional Data

* ***Serverless Framework Version you're using***:
1.16.1

* ***Operating System***:
Mac and/or Ubuntu

* ***Stack Trace***:
```
 Serverless Error ---------------------------------------
 
  Could not locate deployment bucket. Error: Access Denied
 
  Stack Trace --------------------------------------------
 
ServerlessError: Could not locate deployment bucket. Error: Access Denied
    at AwsPackage.BbPromise.bind.then.then.catch.err (/Users/jgaerke/.nvm/versions/node/v7.9.0/lib/node_modules/serverless/lib/plugins/aws/package/lib/generateCoreTemplate.js:40:17)
From previous event:
    at AwsPackage.generateCoreTemplate (/Users/jgaerke/.nvm/versions/node/v7.9.0/lib/node_modules/serverless/lib/plugins/aws/package/lib/generateCoreTemplate.js:39:15)
From previous event:
    at Object.package:initialize [as hook] (/Users/jgaerke/.nvm/versions/node/v7.9.0/lib/node_modules/serverless/lib/plugins/aws/package/index.js:60:10)
    at BbPromise.reduce (/Users/jgaerke/.nvm/versions/node/v7.9.0/lib/node_modules/serverless/lib/classes/PluginManager.js:261:55)
From previous event:
    at PluginManager.invoke (/Users/jgaerke/.nvm/versions/node/v7.9.0/lib/node_modules/serverless/lib/classes/PluginManager.js:261:22)
    at PluginManager.run (/Users/jgaerke/.nvm/versions/node/v7.9.0/lib/node_modules/serverless/lib/classes/PluginManager.js:292:17)
    at variables.populateService.then (/Users/jgaerke/.nvm/versions/node/v7.9.0/lib/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (/Users/jgaerke/.nvm/versions/node/v7.9.0/lib/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/Users/jgaerke/.nvm/versions/node/v7.9.0/lib/node_modules/serverless/bin/serverless:39:50)
 
```

* ***Serverless Config***:
```
service: some-service

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 60
  deploymentBucket:
    name: serverless-${opt:stage, self:provider.stage}-${self:service}-deployment

```
* ***S3 Permissions Granted To AWS User Being Used***:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "*******",
            "Effect": "Allow",
            "Action": [
                "s3:CreateBucket",
                "s3:DeleteBucket",
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:ListAllMyBuckets",
                "s3:ListBucket",
                "s3:ListBuckets",
                "s3:ListBucketVersions",
                "s3:ListObjects",
                "s3:PutObject"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```

**Comment by horike37** [comment]
Thank you for reporting this issue @jgaerke !
I tried to deploy with the provided serverless.yml, and deployed successfully on my end.

Did you already create the deploymentbucket?
You need to create that before deployment.

**Comment by jgaerke** [comment]
The deploymentBucket specified in the serverless.yml is already created.

Can you confirm that you used the permissions I've listed above?

**Comment by horike37** [comment]
@jgaerke 
You might want to try using AdministratorAccess role. If work fine, it would lack some necessary IAM permissions. As far as I see above the user permission, you would need permissions related to CloudFormation and Lambda.

If you want the minimum set of permissions, see the following issue.
https://github.com/serverless/serverless/issues/1439

**Comment by pmuens** [comment]
Thanks for jumping in @horike37 👍

Closing this for now since adding the `AdministratorAccess` role (or some setup described in #1439) should resolve the problem.

Feel free to comment / re-open if this problem is still around...

**Comment by uclaeagit** [comment]
I am getting this error, but only when I run through AWS CodeBuild. From my local machine sls deploy works fine and is able to connect to the S3 bucket. 

```
[Container] 2018/11/28 23:16:06 Running command serverless deploy --stage stage
Serverless: Packaging service...
 Serverless Error ---------------------------------------
 Could not locate deployment bucket. Error: Access Denied
```

I can run other serverless deploy jobs through CodeBuild - the only difference being that those were not using the custom deploymentBucket. I made sure all the settings and permissions on my new S3 bucket matched the settings on the old buckets created by serverless.

Could it be that AWS remembers which user created the bucket (serverless, vs. me) - even though it doesn't show that anywhere in the settings? That's the only thing I can think of.

**Comment by zoellner** [comment]
I noticed the same issue as @uclaeagit and resolved it by adding the IAM permission `s3:GetBucketLocation` for resource `arn:aws:s3:::${MyCustomDeploymentBucket}` (important: not trailing `/*`

**Comment by uclaeagit** [comment]
FWIW this is the current serverless IAM policy we use:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "cloudformation:CancelUpdateStack",
                "cloudformation:ContinueUpdateRollback",
                "cloudformation:CreateStack",
                "cloudformation:DeleteStack",
                "cloudformation:DeleteStackSet",
                "cloudformation:DescribeChangeSet",
                "cloudformation:DescribeStackEvents",
                "cloudformation:DescribeStackResource*",
                "cloudformation:DescribeStacks",
                "cloudformation:ExecuteChangeSet",
                "cloudformation:GetStackPolicy",
                "cloudformation:GetTemplate",
                "cloudformation:ListChangeSets",
                "cloudformation:ListStackResources",
                "cloudformation:UpdateStack",
                "cloudformation:ValidateTemplate",
                "iam:AttachRolePolicy",
                "iam:CreateRole",
                "iam:DeleteRole",
                "iam:DeleteRolePolicy",
                "iam:DetachRolePolicy",
                "iam:GetPolicy",
                "iam:GetRole",
                "iam:ListAttachedRolePolicies",
                "iam:ListPolicies",
                "iam:ListRolePolicies",
                "iam:ListRoles",
                "iam:PutRolePolicy",
                "iam:UpdateRole",
                "iam:PassRole",
                "lambda:AddPermission",
                "lambda:CreateAlias",
                "lambda:CreateEventSourceMapping",
                "lambda:CreateFunction",
                "lambda:DeleteAlias",
                "lambda:DeleteEventSourceMapping",
                "lambda:DeleteFunction",
                "lambda:Get*",
                "lambda:List*",
                "lambda:PublishVersion",
                "lambda:RemovePermission",
                "lambda:TagResource",
                "lambda:UntagResource",
                "lambda:Update*",
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:DeleteLogGroup",
                "logs:DeleteLogStream",
                "logs:DeleteRetentionPolicy",
                "logs:DeleteSubscriptionFilter",
                "logs:PutMetricFilter",
                "logs:PutSubscriptionFilter",
                "logs:DescribeLogGroups",
                "s3:ListBucket",
                "s3:ListObjects*",
                "s3:DeleteObject",
                "s3:DeleteObjectVersion",
                "s3:ListBucketVersions",
                "s3:CreateBucket",
                "s3:PutObject",
                "s3:GetObject",
                "s3:GetBucketLocation",
                "s3:GetObjectVersion"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by u007** [comment]
i tried to test:
```
serverless invoke --function hello --data '{"name":"Bob"}' -l
```
user is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:...

**Comment by XciA** [comment]
Why admin access is encouraged i do not know.

**Comment by manikmdu** [comment]
I agree it is not necessary to provide admin access rights. I came across this issue and it is related to                 "s3:GetBucketLocation" not enabled in my policy.

**Comment by akshaymishi** [comment]
I was facing the same issue, noticed this was happening because i was trying to deploy locally using `sls deploy` from my machine ( rather than code build or other) and since I was passing `--profile ` in the command but not in the serverless.yml provider therefore it was causing this issue.

Kindly try adding/setting profile in your serverless.yml under provider section and see if it works.
