### ISSUE TITLE
deploy function not inheriting provider config

### ISSUE THREAD

**Issue by ljovanovic** [serverless/serverless#4261]
# This is a Bug Report

## Description
When I attempt to perform deploy function in 1.22.0 we receive errors that seem to indicate our provider config is not being merged / inherited in the function definition.  Specifically, we have our vpc and role definitions within the provider portion of the serverless.yml file.  Deploying a function with no changes will result in the error ```TypeError: Cannot read property 'securityGroupIds' of undefined```.  If I duplicate our vpc config within the function definition it will accept the setting and move on to the next value it doesn't seem to inherit, role.

The specific command I am running is 
```
SLS_DEBUG=* node --stack_size=3072 --max_old_space_size=3072 ./node_modules/.bin/sls deploy function --function proxyAuth  -s dev
```

For bug reports:
* What went wrong?
Deployment of the function failed.

* What did you expect should have happened?
The function should deploy as expected.

* What was the config you used?
Relevant portions of the config are

```
provider:
  name: aws
  runtime: nodejs6.10
  vpc: ${self:custom.env.common.aws.vpc}
  role: iamRoleLambdaVpc
```

and 

```
proxyAuth:
    name: zapi-${opt:s}-proxyAuth
    handler: services/proxy/auth/handler.handler
    package:
      include:
        - services/proxy/auth/**
        - services/graphql/lib/**
```

* What stacktrace or error message from your provider did you see?
```  
Type Error ---------------------------------------------

  Cannot read property 'securityGroupIds' of undefined

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: Cannot read property 'securityGroupIds' of undefined
    at AwsDeployFunction.updateFunctionConfiguration (/Users/lj/zctv/api/node_modules/serverless/lib/plugins/aws/deployFunction/index.js:135:58)
From previous event:
    at Object.deploy:function:deploy [as hook] (/Users/lj/zctv/api/node_modules/serverless/lib/plugins/aws/deployFunction/index.js:39:10)
    at BbPromise.reduce (/Users/lj/zctv/api/node_modules/serverless/lib/classes/PluginManager.js:358:55)
From previous event:
    at PluginManager.invoke (/Users/lj/zctv/api/node_modules/serverless/lib/classes/PluginManager.js:358:22)
    at PluginManager.run (/Users/lj/zctv/api/node_modules/serverless/lib/classes/PluginManager.js:389:17)
    at variables.populateService.then (/Users/lj/zctv/api/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (/Users/lj/zctv/api/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/Users/lj/zctv/api/node_modules/serverless/bin/serverless:39:50)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           7.8.0
     Serverless Version:     1.22.0
```

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
1.22.0
* ***Operating System***:
Mac OSSierra 10.12.6
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by RafalWilinski** [comment]
It is clear to me that https://github.com/serverless/serverless/pull/4173/files introduced that regression. Working on a fix right now.
