### ISSUE TITLE
Syntax error trying to create a project

### ISSUE THREAD

**Issue by davidray** [serverless/serverless#427]
api (master)$ serverless project create
/usr/local/lib/node_modules/serverless/bin/serverless:5
let argv = require('minimist')(process.argv.slice(2));
^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

I've used JAWS previously, if that matters.

**Comment by davidray** [comment]
I figured this out - I was not using Node v4. Closing.
