### ISSUE TITLE
Deploy fails with S3 bucket error

### ISSUE THREAD

**Issue by ghsatpute** [serverless/serverless#4285]
# This is a Bug Report

## Description

* What went wrong?
When I try to deploy my serverless application via `serverless deploy` I get following error
`An error occurred: ServerlessDeploymentBucket - API: s3:CreateBucket Access Denied.`

* Configuration
This is my `serverless.yml`

```
service: xyz

provider:
  name: aws
  runtime: python2.7
  stage: dev2-gs-1
  region: us-west-2
  profile: mfa
  environment:
    DB_HOST: "hostname"
    DB_USER: "root"
    DB_PASS: "<password>"
    LOG_LEVEL: "DEBUG"

functions:
  login:
    handler: handler.login
    events:
       - http:
           path: /api/v1/login
           method: post
           cors: true
...
```
* Detailed stack trace.
```
Serverless: Invoke aws:deploy:deploy
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
....
Serverless: Operation failed!
 
  Serverless Error ---------------------------------------
 
  An error occurred: ServerlessDeploymentBucket - API: s3:CreateBucket Access Denied.
 
  Stack Trace --------------------------------------------
 
ServerlessError: An error occurred: ServerlessDeploymentBucket - API: s3:CreateBucket Access Denied.
    at provider.request.then (/usr/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:114:33)
From previous event:
    at AwsDeploy.monitorStack (/usr/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:26:12)
    at provider.request.then (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:41:29)
From previous event:
    at AwsDeploy.create (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:41:7)
From previous event:
    at AwsDeploy.BbPromise.bind.then.catch (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:71:14)
From previous event:
    at AwsDeploy.createStack (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:64:13)
From previous event:
    at Object.aws:deploy:deploy:createStack [as hook] (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:98:10)
    at BbPromise.reduce (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:360:55)
From previous event:
    at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:360:22)
    at PluginManager.spawn (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:378:17)
    at AwsDeploy.BbPromise.bind.then (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:91:48)
From previous event:
    at Object.deploy:deploy [as hook] (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:87:10)
    at BbPromise.reduce (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:360:55)
From previous event:
    at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:360:22)
    at PluginManager.run (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:391:17)
    at variables.populateService.then (/usr/lib/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (/usr/lib/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/usr/lib/node_modules/serverless/bin/serverless:39:50)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           7.8.0
     Serverless Version:     1.22.0
```

* What was the config you used?

Also, if I try to deploy the application again I get different error saying `Missing required key 'Bucket' in params`

* Detailed stacktrace 
```
Serverless: Invoke aws:deploy:deploy
 
  Serverless Error ---------------------------------------
 
  Missing required key 'Bucket' in params
 
  Stack Trace --------------------------------------------
 
ServerlessError: Missing required key 'Bucket' in params
    at Response.req.send (/usr/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:187:20)
    at Request.<anonymous> (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:35:11)
    at Request.<anonymous> (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at /usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/event_listeners.js:85:9
    at finish (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/config.js:315:7)
    at /usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/config.js:333:9
    at EnvironmentCredentials.get (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/credentials.js:126:7)
    at getAsyncCredentials (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/config.js:327:24)
    at Config.getCredentials (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/config.js:347:9)
    at Request.VALIDATE_CREDENTIALS (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/event_listeners.js:80:26)
    at Request.callListeners (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:101:18)
    at Request.emit (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at Request.runTo (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:403:15)
    at Request.send (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:367:10)
    at BbPromise (/usr/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:175:13)
    at persistentRequest (/usr/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:174:14)
    at doCall (/usr/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:153:9)
    at BbPromise (/usr/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:164:14)
From previous event:
    at persistentRequest (/usr/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:151:38)
    at AwsProvider.request (/usr/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:167:12)
    at AwsDeploy.getMostRecentObjects (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/checkForChanges.js:33:26)
From previous event:
    at AwsDeploy.checkForChanges (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/checkForChanges.js:20:8)
From previous event:
    at Object.aws:deploy:deploy:checkForChanges [as hook] (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:102:10)
    at BbPromise.reduce (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:360:55)
From previous event:
    at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:360:22)
    at PluginManager.spawn (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:378:17)
    at AwsDeploy.BbPromise.bind.then (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:91:48)
From previous event:
    at Object.deploy:deploy [as hook] (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:87:10)
    at BbPromise.reduce (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:360:55)
From previous event:
    at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:360:22)
    at PluginManager.run (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:391:17)
    at variables.populateService.then (/usr/lib/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (/usr/lib/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/usr/lib/node_modules/serverless/bin/serverless:39:50)

```
**Also, with the same profile using AWS command line, I can successfully create the S3 bucket.**

**Comment by RafalWilinski** [comment]
Thanks for reporting issue @ghsatpute.

It seems that your IAM permissions are insufficient. Are you sure that you're using correct IAM credentials? 

You can check that by running following command. If this command succeeds:
```sh
aws s3api create-bucket --bucket someuniquebucketname12323123
```

Then problem might be somewhere in Serverless framework.

**Comment by ghsatpute** [comment]
@RafalWilinski Yes. I'm able to create the bucket using the AWS CLI.

**Comment by osamakhn** [comment]
@RafalWilinski I am able to create a bucket using:
`aws s3api create-bucket --bucket foo.bar --create-bucket-configuration LocationConstraint=us-west-2`
but this seems to fail on both `sls deploy` and `sls deploy -r us-west-2`.

Please note that the region set for my `[default]` profile is `us-west-2`

**Comment by osamakhn** [comment]
This issue will be resolved IF I can set my own bucket name instead of `ServerlessDeploymentBucket` being set by serverless in the cloudformation json it generates; I'm too new to SLS to know how to do this. any help would be appreciarted

**Comment by osamakhn** [comment]
AWS CloudFormation Event Log:
<img width="1630" alt="screen shot 2017-09-20 at 14 27 43" src="https://user-images.githubusercontent.com/832250/30668798-cc5402b8-9e10-11e7-8ec3-05672b38ed85.png">

**Comment by pmuens** [comment]
@ghsatpute thanks for opening and thanks for replygin / helping @RafalWilinski and @osamakhn 👍

@osamakhn you can manipulate / overwrite all the generated CloudFormation resources. Here's the reference table which show the naming pattern we follow and ways how you can overwrite the resources:

https://serverless.com/framework/docs/providers/aws/guide/resources/#aws-cloudformation-resource-reference

**Comment by pmuens** [comment]
> @pmuens thanks for linking me there; tried a few things but the bug couldn't resolve the issues highlighted above

Thanks for getting back @osamakhn 👍. Have you setup your profile with the help of [this guide](https://serverless.com/framework/docs/providers/aws/guide/credentials/)? Serverless will use your `default` profile if you don't specify another one.

The odd thing is that you can create a bucket with the CLI, but the mgmt. with the help of the Serverless CLI fails.

**Comment by osamakhn** [comment]
Yikes! I had seen `Serverless` when its was almost *v0.1* and was using the `sls` command instead of `serverless`; as soon as I moved to the later everything seems to be working fine. Apologies!

**Comment by pmuens** [comment]
Great! Thanks for the update @osamakhn 👍

Glad to hear that everything is working again! Let us know if you face any other problems / issues!

**Comment by ghsatpute** [comment]
@pmuens @osamakhn I tried to follow the steps tried by @osamakhn but I faced the same issue. 

If this matters, I'm using a serverless project folder checked-in to Github with `serverless.yml`. I tried to create the project manually by `serverless create --template aws-python --path auth_service` and replaced my `serverless.yml` and other project files. But it's giving me the same error as before. 

Let me know if you need more information from my side.

**Comment by pmuens** [comment]
@ghsatpute thanks for getting back 👍

It looks like you deploy with a profile called `mfa`. Can you confirm that the `mfa` profile is used for deployment? Serverless will default to the AWS `default` profile if the specific profile cannot be found.

**Comment by ghsatpute** [comment]
@pmeuns yes. That profile exists in `~/.aws/credentials` file. I can deploy to S3 by giving profile name as the parameter to AWS command line.

**Comment by prumand** [comment]
I always get this error as well. It worked with a test aws-account, where I do have full admin rights. With a restricted it doesn't work.

**Comment by j2hongming** [comment]
I met the same scenario like this issue.

**Scenario**
I have a IAM user with mfa-required policy and if I use the **access key credential of this user** to deploy my service, I will encounter error
`An error occurred: ServerlessDeploymentBucket - API: s3:CreateBucket Access Denied.`

but  I can successfully use aws cli to create the S3 bucket by this credential .

**Solution**
I follow [this tutorial](https://aws.amazon.com/premiumsupport/knowledge-center/authenticate-mfa-cli/) and use the **temporary credential created by mfa** to deploy my service. Everything seems to be working fine.

**Comment by pmuens** [comment]
Closing since this issue is stale and we've released newer versions with lots of bugfixes in the past.

Feel free to re-open if this is still an issue.

**Comment by jextrevor** [comment]
I'm still having this issue with Serverless 1.41.1.

**Comment by dillonharlessNHRMC** [comment]
I am having this issue as well. I have full admin rights configured in profile called "default", I can create and list s3 bucket using aws s3api, but I can't deploy with serverless pursuant the access denied errors above.

**Comment by APWHY** [comment]
@j2hongming 's answer seemed to work for me. If you have mfa set up for your aws account you will need to use a program like awsmfa (use pip to install) to put an aws_session_token into your credentials files in ~/.aws. I was in a similar situation where I could create a bucket using the aws cli, but not with serverless' cli and this fixed my issue.

**Comment by ctd-insights** [comment]
I had the same issue when my user's IAM policy had IP whiltelist, below is example of Administrator IAM policy:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*",
            "Condition": {
                "IpAddress": {
                    "aws:SourceIp": [
                        "192.168.0.10",
                        "34.1.2.3"
                    ]
                }
            }
        }
    ]
}
```


Removing `Condition` from the IAM policy fixes the issue. (Creating bucket using aws-cli always works).

**Comment by dimkir** [comment]
I had the same issue when my user's IAM policy had IP whiltelist, below is example of Administrator IAM policy:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*",
            "Condition": {
                "IpAddress": {
                    "aws:SourceIp": [
                        "192.168.0.10",
                        "34.1.2.3"
                    ]
                }
            }
        }
    ]
}
```


Removing `Condition` from the IAM policy fixes the issue. (Creating bucket using aws-cli always works).

**Comment by ajorpheus** [comment]
In one case, the CREATE_FAILED error was being seen but there were no details around _why_ the creation was failing. Admittedly attempting to create an S3 bucket directly would have revealed the underlying issue, however our first assumption was that issue was related to permissions. 

However, the same error was being reported when executing `SLS_DEBUG=1 serverless deploy` even when `AWS_PROFILE` pointed to an admin's profile.

The underlying issue was revealed when looking at the events of the failed stack itself. With `SLS_DEBUG=1`, the output shows both the stack id of the cloudformation stack as well as the complete template body. Both of these were instrumental in troubleshooting the issue.

In case someone else comes across this, try using the following AWS CLI query to see exactly why the Cloudformation stack failed like so:

```
aws cloudformation describe-stack-events --stack-name "complete_stack_id_arn_from_serverless_debug_output" --output json --query 'sort_by(StackEvents[], &Timestamp)[*].{Status: ResourceStatus, Reason: ResourceStatusReason, Stack: StackName, TimeStamp: Timestamp}'
```

which showed proper details for the CREATE_FAILED event:

```
    {
        "Status": "CREATE_FAILED",
        "Reason": "You have attempted to create more buckets than allowed (Service: Amazon S3; Status Code: 400; Error Code: TooManyBuckets; Request ID: redacted; S3 Extended Request ID:redacted)",
        "Stack": "some-stack-name-dev",
        "TimeStamp": "2000-01-14T15:30:22.013Z"
    },
```

The detailed stack events for a given stack can also be seen on CloudFormation Console, but remember to change the filter to 'Deleted' since failed stacks are deleted and unfortunately the Console defaults to 'Active' stacks without there being a way to see All stacks irrespective of the status.
Try using this url to which should link directly to a 'Deleted' stacks view of your last chosen region: https://console.aws.amazon.com/cloudformation/home?region=eu-west-2#/stacks?filteringText=&filteringStatus=deleted

**Comment by seba-i** [comment]
`API: s3:CreateBucket Access Denied` seems to hide deeper permission issues. 

By looking at the S3 section of the cloudformation template that is created by `sls deploy` (in the `./serverless` dir) you can get an idea of what other S3 permissions might be needed.

In my case, I was creating and setting up a S3 bucket for a static website, and the Access Denied was due to the IAM role also needing (as revealed in the template above): 
- s3:PutBucketPolicy
- s3:PutBucketWebsite
- s3:PutBucketAcl

Hope this helps someone else!
