### ISSUE TITLE
Invoke local ignores package artifact

### ISSUE THREAD

**Issue by KKomarov** [serverless/serverless#4288]
# This is a Bug Report

## Description
serverless invoke local ignores package artifact and tries to run not existent files

For bug reports:
* What went wrong?
`serverless invoke local -f func1` failed
* What did you expect should have happened?
normal lambda output
* What was the config you used?
minimal config with artifacts
```
provider:
  name: aws
  stage: artifact
  region: us-east-1
  memorySize: 512

package:
  individually: true

functions:

  func1:
    handler: myfolder.handler
    timeout: 60
    runtime: nodejs4.3
    package:
      artifact: mypackage.zip
```

## Additional Data

If I manually unpacked before `invoke local` artifact it works perfectly

* ***Serverless Framework Version you're using***: tested on 1.17.0, 1.20.0, 1.22.0
* ***Operating System***: linux
* ***Stack Trace***:
```
{ Error: Cannot find module '/serverless/myfolder'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at AwsInvokeLocal.invokeLocalNodeJs (/usr/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:156:33)
    at AwsInvokeLocal.invokeLocal (/usr/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:114:19)
    at AwsInvokeLocal.tryCatcher (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5) code: 'MODULE_NOT_FOUND' }

```

**Comment by mattishaden** [comment]
Having similar problem, without packaging functions individually.

**sls invoke local -f myFunction**

> { Error: Cannot find module '/home/zzz/xxx/yyy/.webpack/service/handler'
>     at Function.Module._resolveFilename (module.js:489:15)
>     at Function.Module._load (module.js:439:25)
>     at Module.require (module.js:517:17)
>     at require (internal/module.js:11:18)
>     at AwsInvokeLocal.invokeLocalNodeJs (/home/zzz/xxx/yyy/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:173:33)
>     at AwsInvokeLocal.invokeLocal (/home/zzz/xxx/yyy/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:123:19)
>     at AwsInvokeLocal.tryCatcher (/home/zzz/xxx/yyy/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/home/zzz/xxx/yyy/node_modules/bluebird/js/release/promise.js:512:31)
>     at Promise._settlePromise (/home/zzz/xxx/yyy/node_modules/bluebird/js/release/promise.js:569:18)
>     at Promise._settlePromise0 (/home/zzz/xxx/yyy/node_modules/bluebird/js/release/promise.js:614:10)
>     at Promise._settlePromises (/home/zzz/xxx/yyy/node_modules/bluebird/js/release/promise.js:693:18)
>     at Async._drainQueue (/home/zzz/xxx/yyy/node_modules/bluebird/js/release/async.js:133:16)
>     at Async._drainQueues (/home/zzz/xxx/yyy/node_modules/bluebird/js/release/async.js:143:10)
>     at Immediate.Async.drainQueues (/home/zzz/xxx/yyy/node_modules/bluebird/js/release/async.js:17:14)
>     at runCallback (timers.js:781:20)
>     at tryOnImmediate (timers.js:743:5)
>     at processImmediate [as _immediateCallback] (timers.js:714:5) code: 'MODULE_NOT_FOUND' }

**package.json**
>    "serverless": "^1.22.0",
>    "serverless-offline": "^3.16.0",
>    "serverless-webpack": "^3.0.0",

**Comment by HyperBrain** [comment]
@mattishaden I see you use the `serverless-webpack` plugin. Can you check that you use the following constructs in your webpack config?
```js
// webpack config
const slsw = require('serverless-webpack');
...
  entry: slsw.lib.entries,
...
  output: {
    ...
    filename: '[name].js',
    ...
  }
...
```
And check that the function handler definitions are relative paths that point to your handlers in `serverless.yml`. Then it should work with sls-webpack without problems.

I think that your problem is only a configuration problem and the original problem of this issue is unrelated. If you like, we can continue this discussion at the serverless-webpack project.

**Comment by mattishaden** [comment]
Thank you @HyperBrain. Adding `entry: slsw.lib.entries,` did the trick.

**Comment by pmuens** [comment]
Thanks for jumping in @HyperBrain 👍

So this config change resolves the issue (if so we could close this)?

**Comment by mattishaden** [comment]
@KKomarov will have to answer.

**Comment by HyperBrain** [comment]
@pmuens @KKomarov I'm quite sure that the original problem here is a misconfiguration of the handlers in the `serverless.yml` - the handler entry might not point to the actual handler file which is `require()'d` by `invoke local`.

**Comment by KKomarov** [comment]
@pmuens issue is still there, I can't invoke lambda locally if it has package artifacts

**Comment by HyperBrain** [comment]
@KKomarov Ok. Thanks for the explanation. A given package is currently indeed not unzipped by invoke local and only existing handler source files are supported.
I'm not sure if it is easy to add support for a packed scenario, because some side-effects would have to be handled -> the package most likely contains its own prepackaged node modules which might be different than the ones actually existing in the root of the project, etc.

**Comment by KKomarov** [comment]
@HyperBrain What about other environments: python, java. I see it spawn a separate process for that, so it should easy to support artifact at least for them?

**Comment by HyperBrain** [comment]
@pmuens What do you think about supporting pre-packaged artifacts in invoke local. Do you have any idea how this could be achieved in an easy way?

**Comment by pmuens** [comment]
> @pmuens What do you think about supporting pre-packaged artifacts in invoke local. Do you have any idea how this could be achieved in an easy way?

Thanks for pinging @HyperBrain 👍. I like that feature, however the implementation could be a little bit more complicated and I'm not sure if that's a too common use case when using `invoke local`.

Do we get information about the priority of the `artifacts` configs (e.g. root level vs. function level and stuff) in the `invoke local` plugin? Or is this determined during packaging / deployment?

**Comment by HyperBrain** [comment]
@pmuens Yes you're right. Supporting all levels of artifact specifications might be tricky. Maybe we can narrow down the risks and efforts if we'd only support artifacts that are specified directly in a function for a first implementation.
Especially for `local invoke` this would be easier as it's a trivial check to see if a pre-compiled artifact is referenced and then just run a (yet to be defined) unpack+run variant of `invoke local`.

**Comment by pmuens** [comment]
Thanks for the comment @HyperBrain 👍

> Maybe we can narrow down the risks and efforts if we'd only support artifacts that are specified directly in a function for a first implementation.

That sounds like a good plan 👍. We could make this more complicated if we see need in the future.

**Comment by zzz6519003** [comment]
can I get it(serverless) free to run my toy project? :beer:

**Comment by kevinwright** [comment]
I already have a fix for this, it's just two lines
The problem happens at https://github.com/serverless/serverless/blob/master/lib/plugins/aws/invokeLocal/index.js#L150

and is trivially fixed by:
`const packageArtifact = this.options.functionObj.package.artifact || this.serverless.service.package.artifact;` and then using that in the call to `invokeLocalJava`

That said... I'd much prefer to factor the logic into a `this.getPackage()` method which could be used throughout the rest of the class and give us a single place to update with all current and future ways of specifying the package.

Happy to wrap it up into a PR if everyone's interested.

**Comment by HyperBrain** [comment]
Hi @kevinwright . That sounds good, but I think only for the Java case the invoke will just work if you set the artifact correctly. For the other environments, a proper unpack will be needed, because we cannot just invoke a JavaScript or Python file contained within a built zip file.

**Comment by kevinwright** [comment]
@HyperBrain Java works fine if you set a top level package.

It fails abysmally if you're perhaps mixing more than one language in the project and using `package individually` with the artefact specified on a per-function basis.

This, I believe, is still considered a "correct" way of configuring serverless... It certainly works for packaging, deployment and non-local invocation on AWS

**Comment by damarna85** [comment]
I have the same problem here. Apparently it is just looking for the artifact in the main package so whenever we use individual ones it breaks. Do you have any proper solution to this? is quite annoying.

Thanks!

**Comment by terrorhawks** [comment]
I had this issue, but set the node path to where the node_modules are located.
`NODE_PATH=./layer/nodejs/node_modules serverless invoke local -f my_function -v`

**Comment by Mannini** [comment]
It seems when you indicate the 
```
package:
  individually: true
```
you must indicate the config for webpack. I suggest use the webpack pluggin for serverless and indicate the file config something like:

```
plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true

custom:
  rootDir: "../../"
  webpack: "../../webpack.config.js"
```

**Comment by medikoo** [comment]
I've updated main description with implementation proposal. Although there are two more questions that need answering, help on that is welcome!
