### ISSUE TITLE
TypeError: Cannot read property 'securityGroupIds' of undefined

### ISSUE THREAD

**Issue by jeremydaly** [serverless/serverless#4305]
# This is a Bug Report

## Description
Receiving the following error when trying to deploy a function with a VPC defined in the `provider` section of the Serverless.yml:
```
TypeError: Cannot read property 'securityGroupIds' of undefined
    at AwsDeployFunction.updateFunctionConfiguration (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deployFunction/index.js:137:58)
```

Lines 133-139 of `/lib/plugins/aws/deployFunction/index.js` attempt to reference the `vpc` and `securityGroupIds` of the `functionObj` first. If there is no `vpc` key in the `functionObj`, Node throws an error when trying to access the `securityGroupIds` key. This should check for the existence of `vpc` first.

```javascript
if (functionObj.vpc || providerObj.vpc) {
    params.VpcConfig = {};
    params.VpcConfig.SecurityGroupIds = functionObj.vpc.securityGroupIds
        || providerObj.vpc.securityGroupIds;
    params.VpcConfig.SubnetIds = functionObj.vpc.subnetIds
        || providerObj.vpc.subnetIds;
}
```

Proposed fix:
```javascript
if (functionObj.vpc || providerObj.vpc) {
    params.VpcConfig = {};
    params.VpcConfig.SecurityGroupIds = functionObj.vpc && functionObj.vpc.securityGroupIds
        || providerObj.vpc.securityGroupIds;
    params.VpcConfig.SubnetIds = functionObj.vpc && functionObj.vpc.subnetIds
        || providerObj.vpc.subnetIds;
}
```

## Additional Data

* ***Serverless Framework Version you're using***: v1.22.0
* ***Operating System***: MacOS
* ***Stack Trace***:
```
TypeError: Cannot read property 'securityGroupIds' of undefined
    at AwsDeployFunction.updateFunctionConfiguration (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deployFunction/index.js:137:58)
From previous event:
    at Object.deploy:function:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deployFunction/index.js:39:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:358:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:358:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:389:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:39:50)
```

**Comment by jeremydaly** [comment]
Looks like this was fixed with commit e125ca1, but isn't tagged until the next release.

**Comment by RafalWilinski** [comment]
Thanks for reporting issue @jeremydaly.

Judging from your bug report, you've using version 1.22. Please run `npm i serverless -g` to get version `1.23` which fixes that problem.

**Comment by pmuens** [comment]
Closing since we've addressed and fixed this issue in the past.
