### ISSUE TITLE
"Error: Invoked function failed"

### ISSUE THREAD

**Issue by jnst** [serverless/serverless#4354]
# This is a Bug Report

## Description

I want to invoke lambda function from other lambda.
However, setting VPC will result in an error.
This will work when deleting the VPC setting and recreating.

### serverless.yml

```yml
service: sample
provider:
  name: aws
  runtime: nodejs6.10
  profile: jnst
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
        - "*"
functions:
  hello:
    handler: handler.hello
    memorySize: 128
    timeout: 10
    vpc:
      securityGroupIds:
        - sg-d48a56b1
      subnetIds:
        - subnet-85e622f2
        - subnet-447e6602
  call:
    handler: handler.call
    memorySize: 128
    timeout: 10
    vpc:
      securityGroupIds:
        - sg-d48a56b1
      subnetIds:
        - subnet-85e622f2
        - subnet-447e6602
```

### handler.js

```js
const AWS = require('aws-sdk');
const lambda = new AWS.Lambda({ apiVersion: '2015-03-31' });

module.exports.hello = (event, context, cb) => {
    cb(null, 'hello, world');
  });
};

module.exports.call = (event, context, cb) => {
  const params = {
    FunctionName: 'sample-hello',    // already deployed and exists.
    InvocationType: 'RequestResponse'
  };
  lambda.invoke(params, (err, data) => {
    cb(err, data);
  });
};
```

### Run

```bash
$ env SLS_DEBUG='*' sls invoke -f call
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Invoke invoke
{
    "errorMessage": "2017-10-05T10:14:01.321Z e28263a8-a9b5-11e7-82f5-c71766644acf Task timed out after 10.01 seconds"
}

  Error --------------------------------------------------

  Invoked function failed

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: Invoked function failed
    at AwsInvoke.log (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/lib/plugins/aws/invoke/index.js:103:31)
From previous event:
    at Object.invoke:invoke [as hook] (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/lib/plugins/aws/invoke/index.js:22:10)
    at BbPromise.reduce (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/lib/classes/PluginManager.js:360:55)
From previous event:
    at PluginManager.invoke (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/lib/classes/PluginManager.js:360:22)
    at PluginManager.run (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/lib/classes/PluginManager.js:391:17)
    at variables.populateService.then (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/bin/serverless:39:50)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.11.4
     Serverless Version:     1.23.0
```

### My Environment

```bash
$ npm version
{ sample: '0.0.1',
  npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '48',
  node: '6.11.4',
  openssl: '1.0.2l',
  uv: '1.11.0',
  v8: '5.1.281.108',
  zlib: '1.2.11' }

$ sls version
1.23.0

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29
```

**Comment by horike37** [comment]
Thank you for asking @jnst 👍 
Lambda inside VPC sometimes is very slow since Lambda creates ENI before invoking, which process takes a lot of times.
Here is more detail --> http://docs.aws.amazon.com/lambda/latest/dg/vpc.html

Your set up would need a larger value with `timeout`. 10 may be insufficient.
You might want to increase that gradually and find a fitting time 👍

**Comment by jnst** [comment]
@horike37 Thank you for your reply!
I tried set the timeout to 300 seconds. but it did not work.

```
$ env SLS_DEBUG='*' sls invoke -f call
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Invoke invoke



  Serverless Error ---------------------------------------

  Connection timed out after 120000ms

  Stack Trace --------------------------------------------

ServerlessError: Connection timed out after 120000ms
    at Response.req.send (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:187:20)
    at Request.<anonymous> (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at Request.RESET_RETRY_STATE (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/event_listeners.js:442:9)
    at Request.callListeners (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:101:18)
    at Request.emit (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at Request.<anonymous> (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/event_listeners.js:296:11)
    at Request.<anonymous> (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:683:14)
    at error (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/event_listeners.js:295:22)
    at ClientRequest.<anonymous> (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/node_modules/aws-sdk/lib/http/node.js:83:7)
    at ClientRequest.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at ClientRequest.emit (events.js:185:7)
    at TLSSocket.emitTimeout (_http_client.js:630:10)
    at TLSSocket.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket.Socket._onTimeout (net.js:338:8)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
From previous event:
    at persistentRequest (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:174:14)
    at doCall (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:153:9)
    at BbPromise (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:164:14)
From previous event:
    at persistentRequest (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:151:38)
    at AwsProvider.request (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:167:12)
    at AwsInvoke.invoke (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/lib/plugins/aws/invoke/index.js:83:8)
From previous event:
    at Object.invoke:invoke [as hook] (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/lib/plugins/aws/invoke/index.js:21:10)
    at BbPromise.reduce (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/lib/classes/PluginManager.js:360:55)
From previous event:
    at PluginManager.invoke (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/lib/classes/PluginManager.js:360:22)
    at PluginManager.run (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/lib/classes/PluginManager.js:391:17)
    at variables.populateService.then (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/Users/jnst/.nodebrew/node/v6.11.4/lib/node_modules/serverless/bin/serverless:39:50)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.11.4
     Serverless Version:     1.23.0
```

I tried logging as below, but it stopped with `lambda.invoke()` .
```
module.exports.call = (event, context, cb) => {
  console.log('----------test1----------');
  const params = {
    FunctionName: 'sample-dev-hello',
    InvocationType: 'RequestResponse'
  };
  console.log('----------test2----------');
  lambda.invoke(params, (err, data) => {
    console.log('----------test3----------');
    cb(err, data);
  });
};
```

**Comment by horike37** [comment]
Thank you for getting back @jnst 👍 

Umm, it seems that something on AWS end.
Could you test that invoking the same function on AWS management console?
If you could face the timeout error, it exactly is on AWS end. Then we can decide you might want to ask AWS supports.

**Comment by jnst** [comment]
I also tried it in the AWS Console but timed out in the same way.
It looks like a problem on the AWS side.

<img width="400" alt="AWS Console" src="https://user-images.githubusercontent.com/2821993/31230092-e14b4f1e-aa1d-11e7-9a12-9274bc4ebef9.png">


Also put the result of the state without VPC.
This is work correctly.

```yaml
functions:
  hello:
    handler: handler.hello
    memorySize: 128
    timeout: 60
  call:
    handler: handler.call
    memorySize: 128
    timeout: 60
```

```bash
$ sls remove
$ sls deploy
$ sls invoke -f hello
"hello, world"
$ sls invoke -f call
{
    "StatusCode": 200,
    "Payload": "hello, world"
}
```

I will contact AWS support.
Thank you for taking the time!

**Comment by horike37** [comment]
OK. Hopefully, your problem will be resolved 👍 
closing..
