### ISSUE TITLE
Invoke Local with zip deployment / artifact

### ISSUE THREAD

**Issue by glicht** [serverless/serverless#4405]
# This is a Bug Report 

## Description
When using "invoke local" with java zip deployment the invocation fails with java.lang.NoClassDefFoundError for classes which are included in jars in the lib dir of the zip. This can be seen for example if using a project based upon the gradle template and logic which requires accessing dynamodb. As a workaround I am using an uber/shadow jar which works fine.

For bug reports:
* What went wrong? Received java.lang.NoClassDefFoundError for classes in the lib dir of the zip deployment.
* What did you expect should have happened? Classes should be loaded fine.
* What was the config you used? Java function using a zip deployment.
* What stacktrace or error message from your provider did you see? This is from "run local". Works fine on Amazon's env.

## Additional Data

* ***Serverless Framework Version you're using***: 1.23.0
* ***Operating System***: Windows
* ***Stack Trace***: 
```
java.lang.NoClassDefFoundError: com/amazonaws/services/dynamodbv2/AmazonDynamoDBClientBuilder
        at com.test.DynamoOps.<init>(DynamoOps.java:26)
        at com.test.Handler.<init>(Handler.java:16)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)

        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        at com.serverless.InvokeBridge.getInstance(InvokeBridge.java:55)
        at com.serverless.InvokeBridge.<init>(InvokeBridge.java:30)
        at com.serverless.InvokeBridge.main(InvokeBridge.java:86)

Caused by: java.lang.ClassNotFoundException: com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder

        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)

        at java.lang.ClassLoader.loadClass(Unknown Source)

        ... 10 more
```

**Comment by dschep** [comment]
Hey folks, I've created a PR that adds support for new runtimes, layers, and artifact based projects by utilizing the [`lambci/lambda`](https://github.com/lambci/docker-lambda) docker images. Pleas check it out and test it like this:
```
npm i -g serverless/serverless#invoke-local-docker
```

the change is definitely portable to non-docker based invoke local which i'll probably do, but feel free to test it via docker now :)

**Comment by medikoo** [comment]
@glicht do you still observe it?

**Comment by medikoo** [comment]
Closing due to lack of confirmation
