### ISSUE TITLE
aws-java-maven service and local invoke

### ISSUE THREAD

**Issue by rathish** [serverless/serverless#4415]
Hi,

I am trying to invoke aws java function locally using "invoke local" command, but getting below error. Not sure invoke-bridge-1.0.jar has been packaged ?

> serverless invoke local --function hello 

Serverless: In order to get human-readable output, please implement "toString()" method of your "ApiGatewayResponse" object.
Error: Unable to access jarfile /usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/java/target/invoke-bridge-1.0.jar

and error message sometimes different as well. 

>sudo serverless invoke local --function hello -v

Serverless: In order to get human-readable output, please implement "toString()" method of your "ApiGatewayResponse" object.
Error: Unable to access jarfile /usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/java/target/invoke-bridge-1.0.jar

**Comment by rathish** [comment]
serverless/lib/plugins/aws/invokeLocal/java/  code needed mvn build to have the required jar, not sure it is expected to package the jar file along with standard build or needs custom building.

**Comment by horike37** [comment]
Thanks @rathish for reporting :+1: 
Could you share the pointer where your code is stored so that we can reproduce that ,and then improve?

**Comment by RafalWilinski** [comment]
Thanks @rathish for reporting this bug.

Do you have `maven` installed on your computer? It's required to compile JS <-> Java bridge.

**Comment by rathish** [comment]
thanks, yes I mentioned. I compiled the bridge and generated the jar file.

**Comment by RafalWilinski** [comment]
Can you share your `Serverless.yml`file? It doesn't have to be full, just function & artifact related parts.

**Comment by rathish** [comment]
it is simple function definition for validation

service: login
provider:
  name: aws
  runtime: java8
  environment:
    RDS_HOSTNAME: localhost
    RDS_DB_NAME: khs_dashboard
    RDS_USERNAME: root
    RDS_PASSWORD: root

package:
  artifact: target/login-0.1.jar

functions:
  login:
    handler: com.keystoneheathcare.dashboard.aws.lamdba.login.LoginHandler
  register:
    handler:
com.keystoneheathcare.dashboard.aws.lamdba.login.RegisterHandler
  verify:
    handler: com.keystoneheathcare.dashboard.aws.lamdba.login.VerifyHandler
  changepass:
    handler:
com.keystoneheathcare.dashboard.aws.lamdba.login.ChangePasswordHandler

**Comment by RafalWilinski** [comment]
Possible duplicate: https://github.com/serverless/serverless/issues/4405

**Comment by RafalWilinski** [comment]
🤔 I've tried to reproduce your issue on a clean setup (without maven), however, everything went fine on my end.

Commands I've used to reproduce your issue:
```bash
serverless create -t aws-java-maven
mvn package
serverless invoke local --function hello
```

First invocation was quite long because Maven was downloading all the dependencies.

My guess is that it's a permission related issue. Can you run:
```bash
ls -l /usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/java/target/invoke-bridge-1.0.jar
```

to check your permissions to this file? @rathish

**Comment by rathish** [comment]
Thanks Wilinski, I think, I have used mvn clean install command instead of
package so it didn’t build the invoke-bridge.jar file

**Comment by volphy** [comment]
It works for me but I had to 'mvn package' in ${NPM_DIR}/node_modules/serverless/lib/plugins/aws/invokeLocal/java manually.

If this is correct and expected step, it should be documented in the documentation:
https://serverless.com/framework/docs/

**Comment by RafalWilinski** [comment]
@volphy That's not a correct step, that should be done automatically by framework. It's clear for me that it's a bug and it should be fixed. Thanks for providing hints and possible cause! 💯

**Comment by volphy** [comment]
Just to verify, I have removed all globally installed NPM plugins and installed only serverless:
```
npm install serverless -g
```

Unfortunately, invoke-bridge has not been built automatically.

My environment:

- OS: MS Windows 10
- Shell: bash 4.4.12 (Cygwin x64)
- NodeJS:  6.10.3 (old LTS)
- JDK:  Oracle HotJava 1.8.0_152-b16 (x64)
- Maven: 3.3.9

**Comment by anne-nelson** [comment]
I also needed to run `mvn package` in the `${NPM_DIR}/node_modules/serverless/lib/plugins/aws/invokeLocal/java` directory to get the building java bridge step to stop hanging.

**Comment by zxkane** [comment]
The `serverless` was installed via homebrew. I already tried above workaround to package `invoke-bridge.java`, but the `invoke local` still report artifact not found error.

```bash
➜  demo git:(master) ✗ ll /usr/local/./Cellar/serverless/1.45.1/libexec/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/java/target/invoke-bridge-1.0.1.jar
-rw-r--r--  1 mengxinz  1896053708   2.0M Jun 27 10:50 /usr/local/./Cellar/serverless/1.45.1/libexec/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/java/target/invoke-bridge-1.0.1.jar
➜  demo git:(master) ✗
➜  demo git:(master) ✗
➜  demo git:(master) ✗ sls invoke local -f springCloudFunctionDemo -d "hello"

  Error --------------------------------------------------

  Artifact undefined doesn't exists, please compile it first.
```

**Comment by thecpdubguy** [comment]
Picking up on this issue as I am also running into java issues - this is sort of related but not exactly, I can open a new issue and begin looking into it if need be?

I ran the three commands
```bash
serverless create -t aws-java-maven
mvn package
serverless invoke local --function hello
```

and got the below exceptions

```bash
Serverless: In order to get human-readable output, please implement "toString()" method of your "ApiGatewayResponse" object.
java.lang.reflect.InvocationTargetException

        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)     
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.serverless.InvokeBridge.invoke(InvokeBridge.java:95)
        at com.serverless.InvokeBridge.<init>(InvokeBridge.java:39)
        at com.serverless.InvokeBridge.main(InvokeBridge.java:150)
Caused by: java.lang.NoSuchMethodError: com.amazonaws.services.lambda.runtime.LambdaLogger.log([B)V
        at com.amazonaws.services.lambda.runtime.log4j2.LambdaAppender.append(LambdaAppender.java:74)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)       
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:403)
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
        at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2091)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2005)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1876)
        at org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1421)
        at com.serverless.Handler.handleRequest(Handler.java:18)
        ... 7 more
```

for reference
OS: Windows 10
```shell

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              12.13.0
     Framework Version:         1.61.3
     Plugin Version:            3.3.0
     SDK Version:               2.3.0
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```

**Comment by amit-rgb** [comment]
Issue is still persisting with the same error :
Serverless: In order to get human-readable output, please implement "toString()" method of your "ApiGatewayResponse" object.
Error: Unable to access jarfile C:\Users\..\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\java\target\invoke-bridge-1.0.1.jar

I have followed the below steps : 
1. mvn package
2. serverless invoke local --function hello
Please help

**Comment by michellemalaski-powerschool** [comment]
I'm seeing this same issue; has there been any movement on this problem?

**Comment by thecpdubguy** [comment]
I rolled back to java8 for this. I could start to go down the path of figuring it out if I have time this weekend. Any guidance would be appreciated on where to start.

**Comment by michellemalaski-powerschool** [comment]
I'm using the example provided here: https://www.serverless.com/blog/how-to-create-a-rest-api-in-java-using-dynamodb-and-serverless/

The boilerplate command I'm using is this: 
serverless create --template aws-java-maven --name products-api -p aws-java-products-api

The command I'm using to try to run the project locally is this:
$ serverless invoke local --function hello --data '{"a":"bar"}'

And the resulting error follows:
Serverless: In order to get human-readable output, please implement "toString()" method of your "ApiGatewayResponse" object.
Error: Unable to access jarfile /usr/local/Cellar/serverless/1.71.1/libexec/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/java/target/invoke-bridge-1.0.1.jar

The jar mentioned in the error does not exist on my machine.

**Comment by yyamano** [comment]
@michellemalaski-powerschool If it's a permission issue, there is a workaround.
~~~
% cd /usr/local/Cellar/serverless/1.71.1/libexec/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/java
% sudo mkdir target
% sudo chmod 777 target
% mvn package
~~~

You might want to fix owner/group/permission of "target" and subdirectories.

**Comment by estevaodias** [comment]
Few minutes ago, I also had to mvn package my bridge manually. I`m running aws-java-gradle template on mac, without any modification.

**Comment by LucasJC** [comment]
I am on windows 10 and had this same issue. Apparently it had to do with permissions.
From what I have seen in the sources, the java bridge is built if it is not found after executing the command 'invoke local' (using mvn package).

I could fix it by going to C:\Users\Dell\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\runtimeWrappers\java and executing manually 'mvn package', which resulted in the 'invoke-bridge-1.0.1.jar' being built in the target directory.

*As an improvement:* ¿Wouldn't it be better to just provide this jar already built in the npm repo instead of packaging the java sources?

**Comment by bmccann36** [comment]
> I also needed to run `mvn package` in the `${NPM_DIR}/node_modules/serverless/lib/plugins/aws/invokeLocal/java` directory to get the building java bridge step to stop hanging.

I am using gradle for the project and had to do this to get it working. It may also have to do with which JDK and the fact that I use nvm to manage node versions. It worked on my other mac without doing anything which is why I suspect JDK or nvm may be part of the issue. So probably the root issue is permissions since thats what everyone mentions above.

**Comment by medikoo** [comment]
If you have an idea what can be done on Framework side to fix the issue (or improve error reporting), any input is welcome

**Comment by yyamano** [comment]
@medikoo How about creating a FAQ page for the issue and print the URL in the error message?
#7968 is enough for me, but it looks people are still struggling.

I have some ideas, but not quite good.

* Providing a binary jar file somewhere and installing it at installation time
  * How can we trust the binary?
  * Waste of time and disk space for non Java users
* Using sudo or equivalent command at compile time
  * Asking password surprises users because they just wanted local invocation
* Using sudo or equivalent command at installation time
  * Non Java users might like it
  * Need to determine OSes and installation options (global/local). Sounds complicated for the issue.

**Comment by kevinhooke** [comment]
> @michellemalaski-powerschool If it's a permission issue, there is a workaround.
> 
> ```
> % cd /usr/local/Cellar/serverless/1.71.1/libexec/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/java
> % sudo mkdir target
> % sudo chmod 777 target
> % mvn package
> ```
> 
> You might want to fix owner/group/permission of "target" and subdirectories.

Running mvn package manually in this dir gave me permission errors, so these steps helped to create the target dir. The jar built ok after these steps.

Running 'serverless invoke local' looks like I've now got Log4j version dependency issues:

java.lang.reflect.InvocationTargetException

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.serverless.InvokeBridge.invoke(InvokeBridge.java:95)
	at com.serverless.InvokeBridge.<init>(InvokeBridge.java:39)
	at com.serverless.InvokeBridge.main(InvokeBridge.java:150)
Caused by: java.lang.NoSuchMethodError: 'void com.amazonaws.services.lambda.runtime.LambdaLogger.log(byte[])'
	at com.amazonaws.services.lambda.runtime.log4j2.LambdaAppender.append(LambdaAppender.java:74)

**Comment by madorb** [comment]
@kevinhooke been a long time since CCSAS... funny to see we're running into the same problem with serverless :-)

**Comment by kevinhooke** [comment]
@madorb Hey Ben! It has been a long time!

**Comment by yyamano** [comment]
@madorb @kevinhooke What version of serverless do you use?
I fixed similar issue long time ago. See #5155 and #7930
