### ISSUE TITLE
AwsIotSqlVersion.replace is not a function

### ISSUE THREAD

**Issue by johnbarney** [serverless/serverless#4418]
# This is a Bug Report

## Description

For bug reports:
* Unable to set sqlVersion on iot event
* Functions create when omitting sqlVersion (however I need to specify for my query to work!)

Template snip:
```
functions:
  event:
    handler: event.handler
    timeout: 30
    environment:
      stage: ${opt:stage}
    events:
      - iot:
          name: publish_event_${opt:stage}
          description: Event
          enabled: true
          sql: SELECT (an sqly thing)
          sqlVersion: 2016-03-23
```

## Additional Data

```
  Type Error ---------------------------------------------

  AwsIotSqlVersion.replace is not a function

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: AwsIotSqlVersion.replace is not a function
    at functionObj.events.forEach.event (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/iot/index.js:6
1:43)
    at Array.forEach (native)
    at serverless.service.getAllFunctions.forEach (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/iot/
index.js:21:28)
    at Array.forEach (native)
    at AwsCompileIoTEvents.compileIoTEvents (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/iot/index.
js:16:47)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:360:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:360:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:378:17)
    at Deploy.BbPromise.bind.then.then (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:117:50)

From previous event:
    at Object.before:deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:107:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:360:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:360:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:391:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:39:50)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.11.5
     Serverless Version:     1.23.0
```

**Comment by johnbarney** [comment]
Fixed.

Yaml interprets 2016-03-23 as int. You need to put the version in quotes so Yaml reads it as a string.

Closing ticket. Hopefully somebody else finds this useful.
