### ISSUE TITLE
The logs option throws an expcetion

### ISSUE THREAD

**Issue by jonatasbaldin** [serverless/serverless#4444]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
Running `sls logs -f webhook` or `sls logs -f webhook -t` throws an exception. The logs are still listed, but I can't tail them.

* What did you expect should have happened?
I excepted the command to not thrown an exception and to tail the logs using the `-t` flag.

* What was the config you used?
```
service: serverless-telegram-bot

provider:
  name: aws
  runtime: python3.6
  profile: ckl
  environment:
    TELEGRAM_TOKEN: ${file(./serverless.env.yml):TELEGRAM_TOKEN, ''}

functions:
  webhook:
    handler: handler.webhook
    events:
      - http: POST /

plugins:
  - serverless-python-requirements
```

* What stacktrace or error message from your provider did you see?
```  
// The logs are printed, after that...

    Type Error ---------------------------------------------

  this.userStats.track is not a function

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: this.userStats.track is not a function
    at Logs.track (/Users/jonatasbaldin/.nvm/versions/node/v8.9.0/lib/node_modules/serverless/lib/plugins/logs/logs.js:59:22)
From previous event:
    at Object.after:logs:logs [as hook] (/Users/jonatasbaldin/.nvm/versions/node/v8.9.0/lib/node_modules/serverless/lib/plugins/logs/logs.js:50:53)
    at BbPromise.reduce (/Users/jonatasbaldin/.nvm/versions/node/v8.9.0/lib/node_modules/serverless/lib/classes/PluginManager.js:366:55)
From previous event:
    at PluginManager.invoke (/Users/jonatasbaldin/.nvm/versions/node/v8.9.0/lib/node_modules/serverless/lib/classes/PluginManager.js:366:22)
    at PluginManager.run (/Users/jonatasbaldin/.nvm/versions/node/v8.9.0/lib/node_modules/serverless/lib/classes/PluginManager.js:397:17)
    at variables.populateService.then (/Users/jonatasbaldin/.nvm/versions/node/v8.9.0/lib/node_modules/serverless/lib/Serverless.js:104:33)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Serverless.run (/Users/jonatasbaldin/.nvm/versions/node/v8.9.0/lib/node_modules/serverless/lib/Serverless.js:91:74)
    at serverless.init.then (/Users/jonatasbaldin/.nvm/versions/node/v8.9.0/lib/node_modules/serverless/bin/serverless:42:50)
    at <anonymous>

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.9.0
     Serverless Version:     1.24.0
```

## Additional Data
* ***Serverless Framework Version you're using***: 1.24.0
* ***Operating System***: OSX 10.1.6
* ***NodeJS***: v8.9.0
* ***Stack Trace***: Above
* ***Provider Error messages***: Above

**Comment by horike37** [comment]
Thanks @jonatasbaldin for reporting :100: 
The problem has been already resolved on #4441 PR.
Closing
