### ISSUE TITLE
Error: Invoked function failed - Python

### ISSUE THREAD

**Issue by tamisalex** [serverless/serverless#4484]
# This is a Bug Report

## Description

I'm looking to use serverless to deploy some object detection in aws lambda, but I'm having issues with invoking my function. This is a simple example that just imports numpy. I've run the hello world example no problem,but when trying the python packaging tutorial (https://serverless.com/blog/serverless-python-packaging/) which I ran in python2.7 instead I ran into this issue.

For bug reports:
* What went wrong?
I can't invoke my function, it works fine when I run it locally with python.

* What did you expect should have happened?
* What was the config you used?

> service: numpy-test
> 
> provider:
>   name: aws
>   runtime: python2.7
> 
> functions:
>   numpy:
>     handler: handler.main
> 
> plugins:
>   - serverless-python-requirements
> 
> custom:
>   pythonRequirements:
>     #dockerizePip: true
>     zip: true

* What stacktrace or error message from your provider did you see?
Stack Trace --------------------------------------------
 

> Error: Invoked function failed
>     at AwsInvoke.log (/home/atam6/.nvm/versions/node/v8.6.0/lib/node_modules/serverless/lib/plugins/aws/invoke/index.js:103:31)
> From previous event:
>     at Object.invoke:invoke [as hook] (/home/atam6/.nvm/versions/node/v8.6.0/lib/node_modules/serverless/lib/plugins/aws/invoke/index.js:22:10)
>     at BbPromise.reduce (/home/atam6/.nvm/versions/node/v8.6.0/lib/node_modules/serverless/lib/classes/PluginManager.js:366:55)
> From previous event:
>     at PluginManager.invoke (/home/atam6/.nvm/versions/node/v8.6.0/lib/node_modules/serverless/lib/classes/PluginManager.js:366:22)
>     at PluginManager.run (/home/atam6/.nvm/versions/node/v8.6.0/lib/node_modules/serverless/lib/classes/PluginManager.js:397:17)
>     at variables.populateService.then (/home/atam6/.nvm/versions/node/v8.6.0/lib/node_modules/serverless/lib/Serverless.js:104:33)
>     at runCallback (timers.js:781:20)
>     at tryOnImmediate (timers.js:743:5)
>     at processImmediate [as _immediateCallback] (timers.js:714:5)
> From previous event:
>     at Serverless.run (/home/atam6/.nvm/versions/node/v8.6.0/lib/node_modules/serverless/lib/Serverless.js:91:74)
>     at serverless.init.then (/home/atam6/.nvm/versions/node/v8.6.0/lib/node_modules/serverless/bin/serverless:42:50)
>     at <anonymous>
>  
>   Get Support --------------------------------------------
>      Docs:          docs.serverless.com
>      Bugs:          github.com/serverless/serverless/issues
>      Forums:        forum.serverless.com
>      Chat:          gitter.im/serverless/serverless
>  
>   Your Environment Information -----------------------------
>      OS:                     linux
>      Node Version:           8.6.0
>      Serverless Version:     1.24.1

Similar or dependent issues:
* #4354

## Additional Data

* ***Serverless Framework Version you're using***:
serverless@1.24.1

* ***Operating System***:
ubuntu 16.04

* ***Stack Trace***:
> (npenv) atam6@atam-pc:~/numpy-test$ serverless deploy
> Serverless: Load command run
> Serverless: Load command config
> Serverless: Load command config:credentials
> Serverless: Load command create
> Serverless: Load command install
> Serverless: Load command package
> Serverless: Load command deploy
> Serverless: Load command deploy:function
> Serverless: Load command deploy:list
> Serverless: Load command deploy:list:functions
> Serverless: Load command invoke
> Serverless: Load command invoke:local
> Serverless: Load command info
> Serverless: Load command logs
> Serverless: Load command login
> Serverless: Load command logout
> Serverless: Load command metrics
> Serverless: Load command print
> Serverless: Load command remove
> Serverless: Load command rollback
> Serverless: Load command rollback:function
> Serverless: Load command slstats
> Serverless: Load command plugin
> Serverless: Load command plugin
> Serverless: Load command plugin:install
> Serverless: Load command plugin
> Serverless: Load command plugin:uninstall
> Serverless: Load command plugin
> Serverless: Load command plugin:list
> Serverless: Load command plugin
> Serverless: Load command plugin:search
> Serverless: Load command emit
> Serverless: Load command config
> Serverless: Load command config:credentials
> Serverless: Load command rollback
> Serverless: Load command rollback:function
> Serverless: Load command requirements
> Serverless: Load command requirements:clean
> Serverless: Load command requirements:install
> Serverless: Invoke deploy
> Serverless: Invoke package
> Serverless: Invoke aws:common:validate
> Serverless: Invoke aws:common:cleanupTempDir
> Serverless: Adding Python requirements helper...
> Serverless: Installing required Python packages with python2.7...
> Serverless: Zipping required Python packages...
> Serverless: Packaging service...
> Serverless: Excluding development dependencies...
> Serverless: Removing Python requirements helper...
> Serverless: Invoke aws:package:finalize
> Serverless: Invoke aws:common:moveArtifactsToPackage
> Serverless: Invoke aws:common:validate
> Serverless: Invoke aws:deploy:deploy
> Serverless: Uploading CloudFormation file to S3...
> Serverless: Uploading artifacts...
> Serverless: Uploading service .zip file to S3 (84.34 MB)...
> Serverless: Validating template...
> Serverless: Updating Stack...
> Serverless: Checking Stack update progress...
> .........
> Serverless: Stack update finished...
> Serverless: Invoke aws:info
> Service Information
> service: numpy-test
> stage: dev
> region: us-east-1
> stack: numpy-test-dev
> api keys:
>   None
> endpoints:
>   None
> functions:
>   numpy: numpy-test-dev-numpy
> Serverless: Invoke aws:deploy:finalize
> Serverless: Removing old service versions...
> 
> (npenv) atam6@atam-pc:~/numpy-test$ sls invoke -f numpy
> Serverless: Load command run
> Serverless: Load command config
> Serverless: Load command config:credentials
> Serverless: Load command create
> Serverless: Load command install
> Serverless: Load command package
> Serverless: Load command deploy
> Serverless: Load command deploy:function
> Serverless: Load command deploy:list
> Serverless: Load command deploy:list:functions
> Serverless: Load command invoke
> Serverless: Load command invoke:local
> Serverless: Load command info
> Serverless: Load command logs
> Serverless: Load command login
> Serverless: Load command logout
> Serverless: Load command metrics
> Serverless: Load command print
> Serverless: Load command remove
> Serverless: Load command rollback
> Serverless: Load command rollback:function
> Serverless: Load command slstats
> Serverless: Load command plugin
> Serverless: Load command plugin
> Serverless: Load command plugin:install
> Serverless: Load command plugin
> Serverless: Load command plugin:uninstall
> Serverless: Load command plugin
> Serverless: Load command plugin:list
> Serverless: Load command plugin
> Serverless: Load command plugin:search
> Serverless: Load command emit
> Serverless: Load command config
> Serverless: Load command config:credentials
> Serverless: Load command rollback
> Serverless: Load command rollback:function
> Serverless: Load command requirements
> Serverless: Load command requirements:clean
> Serverless: Load command requirements:install
> Serverless: Invoke invoke
> {
>     "errorMessage": "Unable to import module 'handler'"
> }
>  
>   Error --------------------------------------------------
>  
>   Invoked function failed
>  
>      For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
> 
> 
> * ***Provider Error messages***:
> 

Handler Code

> import numpy as np
> 
> def main(event, context):
> 
> 	try:
> 		import unzip_requirements
> 	except ImportError:
> 		pass
> 	
> 	a = np.arange(15).reshape(3, 5)
> 
> 	print("Your numpy array:")
> 
> 	print(a)
> 
> 
> if __name__ == "__main__":
> 	main('', '')

**Comment by tamisalex** [comment]
Closing as I have moved on from the project that had this issue. Feel free to reopen if you want to keep it.
