### ISSUE TITLE
Unable to load module due to `finalhandler` dependency

### ISSUE THREAD

**Issue by joarleymoraes** [serverless/serverless#4493]
# This is a Bug Report

## Description

* What went wrong?
Express-based web app won't run on AWS, but it works locally using the `serverless-offline` plugin.

* What did you expect should have happened?
Expected to run with no errors on AWS Lambda environment.

* What was the config you used?

Here's  the `serverless.yml`:

```
service: testing-app

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2

functions:
  app:
    handler: server.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
```

Here's `package.json`:
```
{
  "name": "versitrax",
  "version": "1.0.0",
  "private": true,
  "main": "server.js",
  "dependencies": {
    "async": "^2.6.0",
    "bcrypt-nodejs": "0.0.3",
    "body-parser": "^1.13.1",
    "capitalize": "^1.0.0",
    "connect-flash": "^0.1.1",
    "cookie-parser": "^1.3.5",
    "dateformat": "^3.0.2",
    "ejs": "^2.3.2",
    "express": "^4.16.2",
    "express-csv": "^0.6.0",
    "express-session": "^1.11.3",
    "format-currency": "^1.0.0",
    "formidable": "^1.1.1",
    "moment": "^2.19.2",
    "morgan": "^1.6.0",
    "mysql": "^2.7.0",
    "nodemailer": "^4.4.0",
    "passport": "^0.2.2",
    "passport-local": "^1.0.0",
    "phantom-html-to-pdf": "^0.5.5",
    "serverless-http": "^1.5.2",
    "slugify": "^1.2.4"
  },
  "devDependencies": {
    "serverless-offline": "^3.16.0"
  }
}
```

* What stacktrace or error message from your provider did you see?

Here's the Lambda function logs:
```
START RequestId: 03466ae4-d11e-11e7-9f97-2f79ff0bb01d Version: $LATEST
Unable to import module 'server': Error
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/var/task/node_modules/finalhandler/index.js:14:29)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
END RequestId: 03466ae4-d11e-11e7-9f97-2f79ff0bb01d
REPORT RequestId: 03466ae4-d11e-11e7-9f97-2f79ff0bb01d	Duration: 6.27 ms	Billed Duration: 100 ms Memory Size: 1024 MB	Max Memory Used: 22 MB	
```
For feature proposals:

Similar or dependent issues:

## Additional Data

The issues seems to be related to the fact that it can't load `finalhandler`. I checked the package generated by serverless and the module is present under `node_modules`. 

Found this: https://github.com/pillarjs/finalhandler/issues/19 , but it doesn't help.

* ***Serverless Framework Version you're using***:
```
serverless -v
1.18.0
```
* ***Operating System***:
MacOS 10.12.6

* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by horike37** [comment]
Hi @joarleymoraes, thank you for reporting!
I created the same test service based on your report(I have attached [that](https://github.com/serverless/serverless/files/1506504/sls-test.zip) here) and tried to reproduce it.
However, I was not able to see `Unable to import module 'server'` error. It works fine.

What can you see if `finalhandler` will be removed?
If there is the root cause within `finalhandler`, it will work fine by removing it.

**Comment by joarleymoraes** [comment]
You can reproduce when you actually require to use the framework:

`var express  = require('express');`

I was able to reproduce using your sample project by just adding that line to `server.js`

**Comment by horike37** [comment]
@joarleymoraes 

Thank you for your response :+1: 
We need to find out where the root cause is as the first step to resolve this issue.
Does your application work fine by deploying them manually to Lambda function (without doing via Serverless Framework)? If so, there would be the root cause on AWS end. If not, the packaging system of the framework may have any bugs.

**Comment by joarleymoraes** [comment]
That's was a great tip. If manually zip my folder and upload to the Lambda function, it works.

So I guess the problem is with serverless packaging :(

Let me know if you need anything to debug

**Comment by seeden** [comment]
I have same error with latest serverless.

**Comment by AdamZaczek** [comment]
I have the exact same issue, sls offline works like a charm but sls deploy does not. I will try deploying manually to see how it works. Did you guys find a solution using serverless @seeden @joarleymoraes ?

**Comment by seeden** [comment]
I am not using serverless anymore

**Comment by AdamZaczek** [comment]
I actually just found a solution to my own issue, it had to do with lacking adnotation to target node 8.10.  Here is what helped me get the job done
```
{
  "presets": [["@babel/preset-env", { "targets": { "node": "8.10" } }]],
  "plugins": ["@babel/plugin-transform-runtime"]
}
```

**Comment by dschep** [comment]
I'm not sure why sls offline is working... but you say you're using express but I don't see [`serverless-http`](https://github.com/dougmoscrop/serverless-http) in your plugins, so I wouldn't expect it to work.
