### ISSUE TITLE
Deploy attempting to update Lambda version, failing in CFN

### ISSUE THREAD

**Issue by davekonopka** [serverless/serverless#4498]
# This is a Bug Report

## Description

After an initial successful `sls deploy` subsequent deploys of the same code are failing in CloudFormation. It looks like the CloudFormation is trying to perform an update on the existing Lambda version resource and failing as this is not supported by CloudFormation.

* What went wrong?

Deploying the same code more than once results in a CloudFormation stack update failure:

`SomeFunctionLambdaVersionuj4sqa1Q0lh2cElWvhRAoCD0WKyOlaNhFbiMXis3k - Update to resource type AWS::Lambda::Version is not supported.`

* What did you expect should have happened?

The deploy would skip version creation.

* What was the config you used?

* What stacktrace or error message from your provider did you see?

```
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - region-somefunction-nonprod
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - SomeFunctionLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - SomeFunctionLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - Custom::CWAlarm - SomeFunctionAlarms
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Version - SomeFunctionLambdaVersionuj4sqa1Q0lh2cElWvhRAoCD0WKyOlaNhFbiMXis3k
CloudFormation - UPDATE_FAILED - AWS::Lambda::Version - SomeFunctionLambdaVersionuj4sqa1Q0lh2cElWvhRAoCD0WKyOlaNhFbiMXis3k
CloudFormation - UPDATE_FAILED - Custom::CWAlarm - SomeFunctionAlarms
CloudFormation - UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - region-somefunction-nonprod
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - SomeFunctionLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - SomeFunctionLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - Custom::CWAlarm - SomeFunctionAlarms
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Version - SomeFunctionLambdaVersionuj4sqa1Q0lh2cElWvhRAoCD0WKyOlaNhFbiMXis3k
CloudFormation - UPDATE_COMPLETE - Custom::CWAlarm - SomeFunctionAlarms
CloudFormation - UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - region-somefunction-nonprod
CloudFormation - UPDATE_ROLLBACK_COMPLETE - AWS::CloudFormation::Stack - region-somefunction-nonprod
Serverless: Operation failed!
 
  Serverless Error ---------------------------------------
 
  An error occurred: SomeFunctionLambdaVersionuj4sqa1Q0lh2cElWvhRAoCD0WKyOlaNhFbiMXis3k - Update to resource type AWS::Lambda::Version is not supported..
 
  Stack Trace --------------------------------------------
 
ServerlessError: An error occurred: SomeFunctionLambdaVersionuj4sqa1Q0lh2cElWvhRAoCD0WKyOlaNhFbiMXis3k - Update to resource type AWS::Lambda::Version is not supported..
    at provider.request.then (node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:114:33)
From previous event:
    at AwsDeploy.monitorStack (node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:26:12)
    at provider.request.then (node_modules/serverless/lib/plugins/aws/lib/updateStack.js:88:30)
From previous event:
    at AwsDeploy.update (node_modules/serverless/lib/plugins/aws/lib/updateStack.js:88:8)
From previous event:
    at AwsDeploy.BbPromise.bind.then (node_modules/serverless/lib/plugins/aws/lib/updateStack.js:105:12)
From previous event:
    at AwsDeploy.updateStack (node_modules/serverless/lib/plugins/aws/lib/updateStack.js:99:8)
From previous event:
    at AwsDeploy.BbPromise.bind.then (node_modules/serverless/lib/plugins/aws/deploy/index.js:125:39)
From previous event:
    at Object.aws:deploy:deploy:updateStack [as hook] (node_modules/serverless/lib/plugins/aws/deploy/index.js:121:10)
    at BbPromise.reduce (node_modules/serverless/lib/classes/PluginManager.js:366:55)
From previous event:
    at PluginManager.invoke (node_modules/serverless/lib/classes/PluginManager.js:366:22)
    at PluginManager.spawn (node_modules/serverless/lib/classes/PluginManager.js:384:17)
    at AwsDeploy.BbPromise.bind.then (node_modules/serverless/lib/plugins/aws/deploy/index.js:91:48)
From previous event:
    at Object.deploy:deploy [as hook] (node_modules/serverless/lib/plugins/aws/deploy/index.js:87:10)
    at BbPromise.reduce (node_modules/serverless/lib/classes/PluginManager.js:366:55)
From previous event:
    at PluginManager.invoke (node_modules/serverless/lib/classes/PluginManager.js:366:22)
    at PluginManager.run (node_modules/serverless/lib/classes/PluginManager.js:397:17)
    at variables.populateService.then (node_modules/serverless/lib/Serverless.js:104:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (node_modules/serverless/lib/Serverless.js:91:74)
    at serverless.init.then (node_modules/serverless/bin/serverless:42:50)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           6.11.4
     Serverless Version:     1.24.1
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.24.1
* ***Operating System***: Amazon Linux

**Comment by horike37** [comment]
Thanks you for reporting @davekonopka :+1: 
Could you share the serverless.yml file you are using so that we can take a look at?

**Comment by davekonopka** [comment]
It seems like it may have been an issue with something in the artifact `.serverless` directory. I'm no longer experiencing this. Thanks!
