### ISSUE TITLE
Module .path not found for WebPack

### ISSUE THREAD

**Issue by QAnders** [serverless/serverless#4538]
# This is a Bug Report

## Description
Running `sls invoke` for a project using WebPack throws a "Module not found" exception.

```
Serverless: Bundling with Webpack...
Time: 682ms
         Asset     Size  Chunks             Chunk Names
    handler.js   8.3 kB       0  [emitted]  handler
handler.js.map  2.46 kB       0  [emitted]  handler
   [0] ./handler.js 5.73 kB {0} [built] [failed] [1 error]

ERROR in ./handler.js
Module build failed: Error: Cannot find module './path'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/babel-traverse/lib/index.js:10:13)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/babel-template/lib/index.js:69:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/babel-helpers/lib/helpers.js:5:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/babel-helpers/lib/index.js:12:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/babel-core/lib/transformation/file/index.js:30:21)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/babel-core/lib/api/node.js:6:13)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/babel-core/index.js:1:80)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/babel-loader/lib/index.js:3:13)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at loadLoader (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/webpack/lib/NormalModule.js:182:3)
    at NormalModule.build (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/webpack/lib/NormalModule.js:275:15)
    at Compilation.buildModule (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/webpack/lib/Compilation.js:151:10)
    at moduleFactory.create (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/webpack/lib/Compilation.js:456:10)
    at factory (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/webpack/lib/NormalModuleFactory.js:241:5)
    at applyPluginsAsyncWaterfall (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/webpack/lib/NormalModuleFactory.js:94:13)
    at /mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/tapable/lib/Tapable.js:268:11
    at NormalModuleFactory.params.normalModuleFactory.plugin (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/webpack/lib/CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/tapable/lib/Tapable.js:272:13)
    at resolver (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/webpack/lib/NormalModuleFactory.js:69:10)
    at process.nextTick (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/webpack/lib/NormalModuleFactory.js:194:7)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

  Error --------------------------------------------------

  Webpack compilation error, see above

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.9.1
     Serverless Version:     1.24.1
```

**Comment by HyperBrain** [comment]
Hi @QAnders ,
can you open an issue in the `serverless-webpack` project and post the function definitions, the provider section from your `serverless.yml` and your webpack config there additionally to the stack trace .. and the exact command you ran from the command line. It must be something with the configuration, because your webpack compile already failed and it even did not get through to the invoke step.
With this information I might be able to help you out there.

**Comment by QAnders** [comment]
https://github.com/serverless-heaven/serverless-webpack/issues/296
