### ISSUE TITLE
how to run a single test?

### ISSUE THREAD

**Issue by tommedema** [serverless/serverless#4584]
I would like to contribute to issue #4545 but cannot manage to run a single test file: `uploadArtifacts.test.js`. I've tried the following:

```
$ npm run test-bare -- lib/plugins/aws/deploy/lib/uploadArtifacts.test.js
$ npm run test -- lib/plugins/aws/deploy/lib/uploadArtifacts.test.js
$ npm run test -- --require=sinon-bluebird lib/plugins/aws/deploy/lib/uploadArtifacts.test.js
```

And they all result in these errors:

```
  uploadArtifacts
    #uploadArtifacts()
      1) should run promise chain in order
    #uploadCloudFormationFile()
      2) "before each" hook for "should upload the CloudFormation file to the S3 bucket"
    #uploadZipFile()
      3) "before each" hook for "should throw for null artifact paths"
    #uploadFunctions()
      4) should upload the service artifact file to the S3 bucket
      5) should upload the function .zip files to the S3 bucket
      6) should upload single function artifact and service artifact
      7) should log artifact size


  0 passing (34ms)
  7 failing

  1) uploadArtifacts #uploadArtifacts() should run promise chain in order:
     TypeError: sinon.stub(...).resolves is not a function
      at Context.it (lib/plugins/aws/deploy/lib/uploadArtifacts.test.js:63:54)

  2) uploadArtifacts #uploadCloudFormationFile() "before each" hook for "should upload the CloudFormation file to the S3 bucket":
     TypeError: sinon.stub(...).resolves is not a function
      at Context.beforeEach (lib/plugins/aws/deploy/lib/uploadArtifacts.test.js:89:10)

  3) uploadArtifacts #uploadZipFile() "before each" hook for "should throw for null artifact paths":
     TypeError: sinon.stub(...).resolves is not a function
      at Context.beforeEach (lib/plugins/aws/deploy/lib/uploadArtifacts.test.js:158:10)

  4) uploadArtifacts #uploadFunctions() should upload the service artifact file to the S3 bucket:
     TypeError: sinon.stub(...).resolves is not a function
      at Context.it (lib/plugins/aws/deploy/lib/uploadArtifacts.test.js:235:43)

  5) uploadArtifacts #uploadFunctions() should upload the function .zip files to the S3 bucket:
     TypeError: sinon.stub(...).resolves is not a function
      at Context.it (lib/plugins/aws/deploy/lib/uploadArtifacts.test.js:260:43)

  6) uploadArtifacts #uploadFunctions() should upload single function artifact and service artifact:
     TypeError: sinon.stub(...).resolves is not a function
      at Context.it (lib/plugins/aws/deploy/lib/uploadArtifacts.test.js:288:43)

  7) uploadArtifacts #uploadFunctions() should log artifact size:
     TypeError: Attempted to wrap statSync which is already wrapped
      at checkWrappedMethod (node_modules/sinon/lib/sinon/util/core.js:81:29)
      at Object.wrapMethod (node_modules/sinon/lib/sinon/util/core.js:129:21)
      at Object.stub (node_modules/sinon/lib/sinon/stub.js:67:26)
      at Context.it (lib/plugins/aws/deploy/lib/uploadArtifacts.test.js:306:13)
  --------------
  Error: Stack Trace for original
      at Object.wrapMethod (node_modules/sinon/lib/sinon/util/core.js:154:34)
      at Object.stub (node_modules/sinon/lib/sinon/stub.js:67:26)
      at Context.it (lib/plugins/aws/deploy/lib/uploadArtifacts.test.js:232:13)



/Users/tommedema/Drive/projects/forks/serverless/node_modules/mkdirp/index.js:92
                if (!stat.isDirectory()) throw err0;
                          ^

TypeError: stat.isDirectory is not a function
    at Function.sync (/Users/tommedema/Drive/projects/forks/serverless/node_modules/mkdirp/index.js:92:27)
    at process.<anonymous> (/Users/tommedema/Drive/projects/forks/serverless/node_modules/istanbul/lib/command/common/run-with-cover.js:237:28)
    at Object.onceWrapper (events.js:254:19)
    at process.emit (events.js:159:13)
    at process.exit (internal/process.js:147:15)
    at done (/Users/tommedema/Drive/projects/forks/serverless/node_modules/mocha/bin/_mocha:501:15)
    at afterWrite (_stream_writable.js:455:3)
    at _combinedTickCallback (internal/process/next_tick.js:144:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

Yet when I run `npm test`, almost all tests pass (1466), and 1 is pending.

I'm probably missing something obvious. But looking at `bin/test`, the above seems to be valid.

**Comment by HyperBrain** [comment]
It's quite easy to run a single test:
`node node_modules/mocha/bin/mocha lib/plugins/aws/deploy/lib/uploadArtifacts.test.js bin/test --require=sinon-bluebird`

The important thing is not to miss bin/test together with the test file, because it's the bootstrapper that sets some important stuff.

**Comment by tommedema** [comment]
Thanks. I'll give this a try.
