### ISSUE TITLE
PhantomJS from Windows deployment

### ISSUE THREAD

**Issue by CBox** [serverless/serverless#4617]
I'm looking to include a Linux version of a package into my deployment package so that the package will run on Lambda as serverless is currently including the windows version of the package so the function is not executing.

I'm trying to use PhantomJS and I'm getting this error:
```
2017-12-30T11:49:44.295Z	85f51b07-ed57-11e7-b402-ddfb526dbb8d	Error: spawn /var/task/node_modules/phantomjs-prebuilt/lib/phantom\bin\phantomjs.exe ENOENT
at exports._errnoException (util.js:1018:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
at onErrorNT (internal/child_process.js:367:16)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

## Additional Data
I'm using Serverless 1.18.0
OS: Win 7
Node Version: 6.10

**Comment by pmuens** [comment]
Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.
