### ISSUE TITLE
Region is required for 'local' stage

### ISSUE THREAD

**Issue by c-knowles** [serverless/serverless#468]
Using the latest version 0.0.15, the docs for Env Set/List say the region is not required for the "local" stage. However, these commands produce a stack trace if used without a region:

```
➜  sls env list -s local
/Users/cknowles/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/node_modules/bluebird/js/main/promise.js:677
            throw e;
            ^

TypeError: Cannot read property 'length' of undefined
    at EnvList.cliPromptSelectRegion (/Users/cknowles/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/ServerlessPlugin.js:274:52)
    at /Users/cknowles/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/EnvList.js:119:28
From previous event:
    at EnvList._prompt (/Users/cknowles/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/EnvList.js:118:12)
From previous event:
    at EnvList.envList (/Users/cknowles/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/actions/EnvList.js:100:12)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at /Users/cknowles/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/Serverless.js:212:25
    at Array.reduce (native)
    at Serverless.actions.(anonymous function) (/Users/cknowles/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/Serverless.js:211:25)
    at Serverless.command (/Users/cknowles/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/lib/Serverless.js:182:44)
    at Object.<anonymous> (/Users/cknowles/.nvm/versions/node/v4.2.3/lib/node_modules/serverless/bin/serverless:13:36)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

 Completing the region with any string seems to work ok:
```
➜  sls env list -s local -r blah
Serverless: ENV vars for stage local:  
Serverless: ------------------------------  
Serverless: local  
Serverless: ------------------------------  
```

**Comment by JohnBloom** [comment]
This took me a while to figure out. Thanks for the workaround! I hope this can get fixed.
