### ISSUE TITLE
Next.js & Serverless - Errors once deployed to AWS

### ISSUE THREAD

**Issue by Vadorequest** [serverless/serverless#4772]
# This is a (Bug Report)

## Description

I'm building a Hello World application using Serverless and Next.js. My development environment works fine but I'm having troubles with the deployed code on AWS Lambda.

This is not an issue with the `serverless` CLI itself.

You can test against this repository and follow the getting started part, it will work. (local)
But when deploying to aws and visiting the endpoint, it will fail with `{"message": "Internal server error"}`, and the logs show `Unable to import module 'lambdas/server': Error` which is rather cryptic and unhelpful. The development environment seems to work fine, I probably missed some webpack config or something.

https://github.com/Vadorequest/serverless-with-next

I don't know how to debug this and I'm rather stuck right now. The `lambdas/server` probably refers to my lambda in `lambdas/server.js`, but I don't know what's happening for it not to be found.

---

At first, I had the following error:

```
Unable to import module 'lambdas/server': Error
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/task/lambdas/server.js:98:18)
    at __webpack_require__ (/var/task/lambdas/server.js:20:30)
    at Object.<anonymous> (/var/task/lambdas/server.js:73:1)
    at __webpack_require__ (/var/task/lambdas/server.js:20:30)
    at /var/task/lambdas/server.js:63:18
    at Object.<anonymous> (/var/task/lambdas/server.js:66:10)
```

But then, I added `webpackIncludeModules` to my `serverless.yml` file and the stacktrace isn't shown anymore, even though the error persists.

```yml
custom:
  webpackIncludeModules: true
```

---
## Additional Data

* ***Serverless Framework Version you're using***: 1.26.0
* ***Operating System***: MacOS X 10.13.3 (17D47)

**Comment by Vadorequest** [comment]
Previous error was fixed by using node `6.10.3` instead of `8.x`.

I updated the repo a few minutes ago, and I'm still working on fixing Next on AWS, ran into new issues. See https://github.com/zeit/next.js/issues/3903

**Comment by Vadorequest** [comment]
I fixed most of the issues and I have now a Next.js application running at https://bcwl62lv2e.execute-api.us-east-1.amazonaws.com/dev/ (I said running, not pretty, images are broken & all)

I still have a few issues though. Only the root path is handled by Next.js, but sub paths should also be handled by Next.js as follow:

- https://bcwl62lv2e.execute-api.us-east-1.amazonaws.com/dev/ (next.js)
- https://bcwl62lv2e.execute-api.us-east-1.amazonaws.com/dev/oops404 (next.js)
- https://bcwl62lv2e.execute-api.us-east-1.amazonaws.com/dev/status (next.js)
- https://bcwl62lv2e.execute-api.us-east-1.amazonaws.com/dev/whatever/nested (next.js)

(in my development mode, this works fine, all paths are handled by Next.js, I actually don't know how to make some of them handled by other Lambdas, but that's another issue for later)

Here is the browser console error: 

`https://bcwl62lv2e.execute-api.us-east-1.amazonaws.com/_next/59de0360-2226-486a-aa6b-3e6c4640fffc/page/index.js net::ERR_ABORTED`

The URL is wrong, it should be `https://bcwl62lv2e.execute-api.us-east-1.amazonaws.com/dev/_next/59de0360-2226-486a-aa6b-3e6c4640fffc/page/index.js` (the `dev` part is missing)
        
When I go to `https://bcwl62lv2e.execute-api.us-east-1.amazonaws.com/dev/_next/59de0360-2226-486a-aa6b-3e6c4640fffc/page/index.js` manually, I get the following: `Error: INVALID_BUILD_ID`
        
        ```
        Error: INVALID_BUILD_ID
        at Server._callee12$ (/var/task/node_modules/next/dist/server/index.js:632:29)
        at tryCatch (/var/task/node_modules/regenerator-runtime/runtime.js:62:40)
        at GeneratorFunctionPrototype.invoke [as _invoke] (/var/task/node_modules/regenerator-runtime/runtime.js:296:22)
        at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/var/task/node_modules/regenerator-runtime/runtime.js:114:21)
        at step (/var/task/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
        at /var/task/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
        at Promise.F (/var/task/node_modules/core-js/library/modules/_export.js:35:28)
        at Object.<anonymous> (/var/task/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
        at Object._nextBuildIdPagePathJs [as fn] (/var/task/node_modules/next/dist/server/index.js:714:27)
        at Router._callee$ (/var/task/node_modules/next/dist/server/router.js:81:60)
        ```

It's hard to debug this mix of Next.js + Serverless + Serverless express, development env and AWS env behave differently... Quite hard to debug. Any help appreciated, been stuck for 4 days on this implementation, fixing bugs after bugs. 😄

**Comment by Vadorequest** [comment]
Using a custom domain fixed the path issue, but the handler still isn't called for other routes.

https://swn.dev.vadorequest.fr/
