### ISSUE TITLE
Error running function locally for aws-scala-sbt

### ISSUE THREAD

**Issue by thunderkid** [serverless/serverless#4789]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
Using the aws-scala-sbt template, I'm getting `Error: spawn mvn ENOENT` when invoking locally.
* What did you expect should have happened?
It should have run and returned the same response it does when I invoke the deployed version.  I've checked running other serverless templates locally (eg aws-nodejs-typescript), and they work fine.
* What was the config you used?
Fresh configuration created with `serverless create --template aws-scala-sbt`
* What stacktrace or error message from your provider did you see?
```
PS C:\Users\thunderkid\Documents\ServerlessLab\pus2> serverless invoke local -f hello
Serverless: Building Java bridge, first invocation might take a bit longer.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn mvn ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

```

## Additional Data
I'm trying to test the example template provided with `aws-scala-sbt`. My exact steps from the powershell prompt are:

```
mkdir pus2
cd pus2
serverless create --template aws-scala-sbt
sbt assembly
serverless invoke local -f hello     ***** this does not work. and gives the error shown above.

```
However, deploying to aws and then testing the deployed function works fine:
```
serverless deploy -v
serverless invoke -f hello -l                     ****** this works.


```

* ***Serverless Framework Version you're using***: 1.26.1
* ***Operating System***: Windows 10 build 1709/ java 1.8.0_161/ sbt 1.0.0
* ***Stack Trace***: 
```
      throw er; // Unhandled 'error' event
      ^

Error: spawn mvn ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

```

* ***Provider Error messages***: See above

**Comment by Saandji** [comment]
same problem with simple java Lambda

**Comment by svardhan12** [comment]
facing the same issue.

**Comment by bhaskarbalusani** [comment]
Facing the same issue. 
Root cause: spawn did not handle .bat or .cmd files.
Changes i made to resolve this issue ->
https://github.com/serverless/serverless/blob/master/lib/plugins/aws/invokeLocal/index.js#L233

Here spawn method not able to detect "mvn" as a command, When you give an argument to set shell as true like this 
const mvn = spawn('mvn', [
          'package',
          '-f',
          path.join(javaBridgePath, 'pom.xml'),
        ]);
        ], { shell: true });
It will open the cmd.exe terminal to execute the child process. There it will be able to detect .cmd and .bat files. 
I made changes in my branch https://github.com/serverless/serverless/compare/master...bhaskarbalusani:master

Please suggest me, how can i merge these changes

**Comment by dschep** [comment]
It seems you're all running on Windows. Is that correct?

**Comment by pgrzesik** [comment]
Closing due to inactivity for over 2 years
