### ISSUE TITLE
Serverless deploy fails, when being built from master

### ISSUE THREAD

**Issue by SmaranNA** [serverless/serverless#4848]
# This is a (Bug Report)

##  I'm installing serverless from master branch using sudo npm install -g "github:serverless/serverless#master". Now the deployment fails for the following sequence of commands.

* What went wrong: Serverless deploy fails
* What did you expect should have happened: Serverless deploy to be completed
* What was the config you used: AWS credentials and stage is provided as environment variables for the commands.
* What stacktrace or error message from your provider did you see: See attached
* Same config works fine in 1.26.0 version.
[serverless_error.zip](https://github.com/serverless/serverless/files/1840658/serverless_error.zip)

## Additional Data

* ***Serverless Framework Version: master***:
* ***Operating System: Mac OS 10.13.3***:
* ***Provider Error messages: See attached ***:

**Comment by bsdkurt** [comment]
I am also seeing this issue. Adding this
```yaml
package:
  individually: true
```
worked for me as a work-around. You can also go back to March 15th code just before the breakage with this:
```npm -g install serverless/serverless#5487ad80933e5b260592fa703963bf04a51e8814```

**Comment by bsdkurt** [comment]
@franciscocpg @HyperBrain I'm pretty sure PR https://github.com/serverless/serverless/pull/4677 broke simple `sls deploy` for aws. For example:

```yaml
service: my-express-application

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http: GET /
      - http: GET /pets
      - http: POST /pets
      - http: GET /param/{Id}
```
`sls deploy` has the following error:

```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
 
  Error --------------------------------------------------
 
  ENOENT: no such file or directory, stat 'my-express-application.zip'
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
```
With `SLS_DEBUG=* sls deploy`

```
Serverless: Uploading artifacts...
 
  Error --------------------------------------------------
 
  ENOENT: no such file or directory, stat 'my-express-application.zip'
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: ENOENT: no such file or directory, stat 'my-express-application.zip'
    at Error (native)
    at Object.fs.statSync (fs.js:1009:11)
    at BbPromise.map (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/uploadArtifacts.js:107:24)
From previous event:
    at AwsDeploy.uploadFunctions (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/uploadArtifacts.js:106:22)
From previous event:
    at AwsDeploy.uploadArtifacts (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/uploadArtifacts.js:19:8)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:119:39)
From previous event:
    at Object.aws:deploy:deploy:uploadArtifacts [as hook] (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:115:10)
    at BbPromise.reduce (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.spawn (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:390:17)
    at AwsDeploy.BbPromise.bind.then (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:101:48)
From previous event:
    at Object.deploy:deploy [as hook] (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:97:10)
    at BbPromise.reduce (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.run (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:403:17)
    at variables.populateService.then (/usr/lib/node_modules/serverless/lib/Serverless.js:102:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (/usr/lib/node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (/usr/lib/node_modules/serverless/bin/serverless:42:50)
```

While just before that PR merge deploy succeeds:
`npm -g install serverless/serverless#5487ad80933e5b260592fa703963bf04a51e8814`

**Comment by franciscocpg** [comment]
Thanks for reporting this.
I've already found the issue and I'm going to open a PR in a few minutes with the fix.

**Comment by franciscocpg** [comment]
@SmaranNA @bsdkurt 
Could you give a try using https://github.com/serverless/serverless/pull/4861?

**Comment by bsdkurt** [comment]
@franciscocpg Thanks for the quick response!
