### ISSUE TITLE
`serverless invoke local` returns exit status 0 when the handler code throws error

### ISSUE THREAD

**Issue by fwang** [serverless/serverless#4852]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
`sls invoke local -f exist` exits with status 0 when invoke fails due to error in the handler code. 

Note, the exit status is 1 (correct behaviour) when invoke fails before reaching the handler code.
`sls invoke local -f notExist` 

* What did you expect should have happened?
Exits with status 1.

* What was the config you used?

* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***: 1.24.1
* ***Operating System***: macOS 10.13 / Ubuntu 16.04
* ***Stack Trace***:
```
ReferenceError: awefpohi is not defined
    at Object.<anonymous> (/Users/frank/Sites/Test/handler.js:3:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at AwsInvokeLocal.invokeLocalNodeJs (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:251:33)
    at AwsInvokeLocal.invokeLocal (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:125:19)
    at AwsInvokeLocal.tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
```
* ***Provider Error messages***:

**Comment by HyperBrain** [comment]
Hi @fwang , nice catch. I agree that errors in the handler itself should not be catched unconditionally and should be converted to a `1` exit code to let them check in automated ways.

**Comment by GuruRAM** [comment]
If it's still relevant I would like to fix it. If the handler couldn't be loaded an exception would be thrown instead of:
`process.exit(0);`
in invokeLocalNodeJs

**Comment by HyperBrain** [comment]
@GuruRAM Appreciate your help 👍 . Please open a PR then we'll review it.

**Comment by GuruRAM** [comment]
Hi @fwang, yes if the handler's initialization code throws an exception or the handler.js doesn't exist the exit status should be 1.
> when the handler does not exist, the exit status is 1; and

The current master has the following behavior:
- if the handler (handler.js) doesn't exist, the exit status is 0
- if the function notExist (in your case) is not defined (in the yml file) the exit status is 1 because sls isn't loading the handler file since the function is not defined.

**Comment by GuruRAM** [comment]
@fwang This case is covered by unit tests the error code is 1 as expected. The problem with the exit code 0 occurs only during the handler's loading logic since the catch block call process.exit(0) if an exception occurs.

**Comment by Shaun1** [comment]
It appears that `serverless invoke local` still has this behavior. It would be helpful for automation purposes if an exception within a function caused `serverless invoke local` to return a non-zero exit code. Can we consider reopening this ticket?

**Comment by dschep** [comment]
@Shaun1 yeah, I don' think this should've been closed.

**Comment by Shaun1** [comment]
@dschep is anyone taking on this bug? If not I will see if I have some time this afternoon to take a look.

**Comment by GuruRAM** [comment]
@Shaun1 I'm not going to fix it this weekend, so I guess you are free to go.

**Comment by dschep** [comment]
I thinks @shortjared is planning to look at it.

**Comment by Shaun1** [comment]
@dschep @shortjared I didn't have time to come up with a good overall fix for the issue but I was able to narrow down to where the issue lies. Something like this works, at least for the python invoker 

https://github.com/serverless/serverless/compare/master...Shaun1:master

I think the principle will be the same for other languages as well: the `exitCode` of the resolved invoker promise should be what the overall process exits with.

**Comment by dschep** [comment]
Thanks @Shaun1, yeah it looks like it'l have to be implemented per language.

**Comment by edmret** [comment]
does anyone is having the same issue using `serverless invoke test` ?, I'm having issues with this on AWS code deploy, beacuase it does not exits before call the deploy command.

**Comment by dsmileyephe** [comment]
Has this been resolved?

**Comment by pirmax** [comment]
What about this issue?

**Comment by stefanks** [comment]
Can confirm this is still not fixed!

**Comment by kirbo** [comment]
Any updates on this? My `pre-push` hook is not working, because the tests "pass" every time, no matter if any of the tests fail. Always exit code 0, which doesn't prevent my husky pre-push hook to stop pushing in case tests fail.

**Comment by marekpiotrowski** [comment]
Hmm...tried to re-produce it with some minimal lambda (master branch):
```
'use strict';

module.exports.hello = async event => {
  throw new Error("Bump.");
  return {
    statusCode: 200,
    body: JSON.stringify(
      {
        message: 'Go Serverless v1.0! Your function executed successfully!',
        input: event,
      },
      null,
      2
    ),
  };

  // Use this code if you don't use the http event with the LAMBDA-PROXY integration
  // return { message: 'Go Serverless v1.0! Your function executed successfully!', event };
};
```
```
$ ../bin/serverless.js invoke local -f hello
...
$ echo $?
$ 1
```

So, it looks fine for ```sls invoke local```. 

Correct me if I'm wrong here, but ```sls invoke test``` is part of this plugin: https://github.com/nordcloud/serverless-mocha-plugin. Shouldn't an issue be reported there instead?

**Comment by GertSchepens** [comment]
To me the bug occurs on compiler failure for invoke local

```
gert@Kusanagi:~/backend$ sls  invoke local --function analyse --path event.json && echo status $?
Serverless: Running "serverless" installed locally (in service node_modules)
...
NameError: name 'poop' is not defined

status 0
```
