### ISSUE TITLE
How to load java in a Node JS runtime lambda

### ISSUE THREAD

**Issue by warjohn123** [serverless/serverless#4869]
## Description

For bug reports:
* What went wrong?
I have a lambda function that is running in Node js. Then I tried to plug this library: https://github.com/nikku/node-xsd-schema-validator to the application. When i deploy the function, it then returns this error

spawn javac ENOENT
at exports._errnoException (util.js:1018:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
at onErrorNT (internal/child_process.js:367:16)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
at process._tickDomainCallback (internal/process/next_tick.js:128:9)

which I believe that JAVA is not loaded. Is it possible to load JAVA even though my runtime in the provider is node js?

* What did you expect should have happened?
The plugin should work properly

* What was the config you used?
provider:
  name: aws
  runtime: nodejs6.10

* What stacktrace or error message from your provider did you see?

spawn javac ENOENT
at exports._errnoException (util.js:1018:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
at onErrorNT (internal/child_process.js:367:16)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
at process._tickDomainCallback (internal/process/next_tick.js:128:9)

## Additional Data

* ***Serverless Framework Version you're using***: 1.20.2

**Comment by shatgupt** [comment]
This is not a Serverless issue. The AWS Lambda Nodejs runtime doesn't have `javac`. Even the Java runtime doesn't have `javac` but only `java`.

**Comment by HyperBrain** [comment]
@warjohn123 Does @shatgupt 's comment answer your question? As he pointed out, you do not have Java available in a Node based lambda. You either should use the lambda Java runtime or Node-only code.

**Comment by neoadventist** [comment]
@warjohn123 did you ever solve this? I would like to run a java command via node and am figuring out how to load in java via a layer or such.
