### ISSUE TITLE
ServerlessError: Could not locate deployment bucket. Error: Access Denied

### ISSUE THREAD

**Issue by praveenmenon** [serverless/serverless#4883]
For bug reports:
* What went wrong?
   Could not locate deployment bucket. Error: Access Denied
* What did you expect should have happened?
   I have created the bucket in AWS and was able to deploy. This issue started recently. 
* What was the config you used?
  I have given full access to cloud formation and S3 to the role
* What stacktrace or error message from your provider did you see?
   ServerlessError: Could not locate deployment bucket. Error: Access Denied
    at BbPromise.resolve.then.then.catch.err (/Users/praveen/Documents/workspace/alexa-app-server/examples/apps/Goodnight-Kiddo/node_modules/serverless/lib/plugins/aws/deploy/lib/existsDeploymentBucket.js:26:15)

This is my policy
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "iam:PassRole",
                "cloudwatch:*",
                "s3:*",
                "logs:*",
                "lambda:*",
                "cloudformation:*",
                "dynamodb:*"
            ],
            "Resource": "*"
        }
    ]
}

**Comment by HyperBrain** [comment]
Can you try to execute the deployment with `--verbose` or `SLS_DEBUG="*" serverless deploy ...` to get more insights, what bucket is accessed exactly in your case?

**Comment by kumudt** [comment]
Getting the same error.
Running with SLS_DEBUG="*" gave this output.
```
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
 
  Serverless Error ---------------------------------------
 
  Could not locate deployment bucket. Error: Access Denied
 
  Stack Trace --------------------------------------------
 
ServerlessError: Could not locate deployment bucket. Error: Access Denied
    at BbPromise.resolve.then.then.catch.err (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/existsDeploymentBucket.js:26:15)
From previous event:
    at AwsDeploy.existsDeploymentBucket (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/existsDeploymentBucket.js:25:13)
    at AwsDeploy.BbPromise.bind.then.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:81:25)
From previous event:
    at Object.before:deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:78:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:403:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:102:33)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:42:50)
    at <anonymous>

```

**Comment by chasdevs** [comment]
Also getting this when I specify an existing bucket.

**Comment by naingyelin** [comment]
Had into the same problem where I have multiple AWS credentials in my environment so I had to be very explicit with which profile I was deploying. I am using powershell so I just set my environment variable as below, it is referenced by the AWS javascript SDK and the deployment bucket was found.

```
$env:AWS_PROFILE = "Development"
serverless deploy

**Comment by TimWeBill** [comment]
Try sls remove, then sls deploy again.
