### ISSUE TITLE
  Cannot read property 'package' of undefined - "SLS_DEBUG=*" environment variable.

### ISSUE THREAD

**Issue by Thukyd** [serverless/serverless#4950]
# This is a (Bug Report / Feature Proposal)

## Description
I amtrying to use serverless in combination with typescript for an AlexaSkill.  Serverless and typescript are both quite new for me. Right now I can deploy my code but when I try to test it throws this "package" error. 

- 1st.  Where do I put this "SLS_DEBUG=*" envioremtn variable in? The logs would be helpful for sure
- 2nd What does that error mean in general. Is that connected to the package.json?   

```


PS C:\GoogleDrive\03_Codes\Alexa\AlexaSkills_ASK-CLI\browserkiosk\lambda\custom> serverless invoke local -f browserkiosk  -p ./testdata/deepSpecificPicture.json

  Type Error ---------------------------------------------

  Cannot read property 'package' of undefined

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           9.9.0
     Serverless Version:     1.27.0

```
## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by HyperBrain** [comment]
Hi @Thukyd , thanks for reporting 👍 .

Can you provide more information about your configuration and run the invoke local command with `SLS_DEBUG="*" serverless invoke local ... --verbose`?

**Comment by Thukyd** [comment]
Unfortunately this error appears (code bellow). It roughly translates: "The name "SLS_DEBUG = *" was not used as the name of a cmdlet, function, script file, or recognized executable program. Check the spelling of the name, or if the path is correct" 
I'm using VS Code and the Windows Powershell inside.



```
PS C:\GoogleDrive\03_Codes\Alexa\AlexaSkills_ASK-CLI\browserkiosk\lambda\custom> SLS_DEBUG=* serverless invoke local -f browserkiosk  -p ./testdata/deepSpecificPicture.json
SLS_DEBUG=* : Die Benennung "SLS_DEBUG=*" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines
ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern
enthalten), und wiederholen Sie den Vorgang.
In Zeile:1 Zeichen:1
+ SLS_DEBUG=* serverless invoke local -f browserkiosk  -p ./testdata/de ...
+ ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (SLS_DEBUG=*:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by HyperBrain** [comment]
Ok. SLS_DEBUG is in fact an environment variable. you can try to set it to `*` before executing the serverless command.

**Comment by Thukyd** [comment]
:(
unfortunately the same result.

**Comment by HyperBrain** [comment]
Just read some PowerShell docs. Maybe this works:
```
cmd /c "set `"SLS_DEBUG=*`" & serverless invoke local --verbose ..."
```

**Comment by Thukyd** [comment]
Yes, it finally worked. Thanks for the guidance! 

So, there is an error inside the serverless plugin for typescript (see the logs at the bottom). As a side information, the combination of serverless and node.js worked fine. But the addition of typescript doesn't. I might have set up things wrong?

In my package.json i specified following dependencies (and they are installed as well):
```
  "dependencies": {
    "ask-sdk": "^2.0.1"
  },
  "devDependencies": {
    "@types/node": "^10.0.2",
    "serverless-offline": "^3.20.3",
    "serverless-plugin-typescript": "^1.1.5"
  },
```

In my serverless.yml i have put this for the typescript extension: 
```
# [...]
plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  exclude:
  include:
    - src/**/*
# [...]
```

Log for serverless
```
  Type Error ---------------------------------------------

  Cannot read property 'package' of undefined

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: Cannot read property 'package' of undefined
    at TypeScriptPlugin.prepare (C:\GoogleDrive\03_Codes\Alexa\AlexaSkills_ASK-CLI\browserkiosk\lambda\custom\node_modules\serverless-plugin-typescript\dist\src\index.js:70:29)
    at TypeScriptPlugin.<anonymous> (C:\GoogleDrive\03_Codes\Alexa\AlexaSkills_ASK-CLI\browserkiosk\lambda\custom\node_modules\serverless-plugin-typescript\dist\src\index.js:104:18)
    at Generator.next (<anonymous>)
    at C:\GoogleDrive\03_Codes\Alexa\AlexaSkills_ASK-CLI\browserkiosk\lambda\custom\node_modules\serverless-plugin-typescript\dist\src\index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\GoogleDrive\03_Codes\Alexa\AlexaSkills_ASK-CLI\browserkiosk\lambda\custom\node_modules\serverless-plugin-typescript\dist\src\index.js:3:12)
    at TypeScriptPlugin.compileTs (C:\GoogleDrive\03_Codes\Alexa\AlexaSkills_ASK-CLI\browserkiosk\lambda\custom\node_modules\serverless-plugin-typescript\dist\src\index.js:103:16)
    at TypeScriptPlugin.<anonymous> (C:\GoogleDrive\03_Codes\Alexa\AlexaSkills_ASK-CLI\browserkiosk\lambda\custom\node_modules\serverless-plugin-typescript\dist\src\index.js:41:48)
    at Generator.next (<anonymous>)
    at C:\GoogleDrive\03_Codes\Alexa\AlexaSkills_ASK-CLI\browserkiosk\lambda\custom\node_modules\serverless-plugin-typescript\dist\src\index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\GoogleDrive\03_Codes\Alexa\AlexaSkills_ASK-CLI\browserkiosk\lambda\custom\node_modules\serverless-plugin-typescript\dist\src\index.js:3:12)
    at Object.before:invoke:local:invoke [as hook] (C:\GoogleDrive\03_Codes\Alexa\AlexaSkills_ASK-CLI\browserkiosk\lambda\custom\node_modules\serverless-plugin-typescript\dist\src\index.js:40:49)
    at BbPromise.reduce (C:\Users\jpteb\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (C:\Users\jpteb\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:372:22)    at PluginManager.run (C:\Users\jpteb\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:403:17)
    at variables.populateService.then (C:\Users\jpteb\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:102:33)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
    at process.topLevelDomainCallback (domain.js:101:23)
From previous event:
    at Serverless.run (C:\Users\jpteb\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:89:74)
    at serverless.init.then (C:\Users\jpteb\AppData\Roaming\npm\node_modules\serverless\bin\serverless:42:50)
    at <anonymous>

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           9.9.0
     Serverless Version:     1.27.0
```

**Comment by maplion** [comment]
I'm trying to test the serverless graphql example here: https://serverless.com/blog/make-serverless-graphql-api-using-lambda-dynamodb/ and I got it to work in AWS, but when I invoke it locally, I get "Cannot read property 'query' of undefined" because the event object is null in `event.queryStringParameters.query`  Is there a way to test this locally using `sls invoke local`?
