### ISSUE TITLE
ServerlessError: Access Denied but no errors on CloudFormation events

### ISSUE THREAD

**Issue by elifarley** [serverless/serverless#4981]
# This is a Bug Report

## Description

* What went wrong?
I get an error message when trying to deploy (`SLS_DEBUG=* serverless deploy -v`):
```
  Serverless Error ---------------------------------------

  Access Denied
```
* What did you expect should have happened?
No errors should have appeared

* What was the config you used?
serverless.yml:
```yaml
provider:
  name: aws
  runtime: java8

package:
  artifact: target/mayday-default-SNAPSHOT.jar

functions:
  hello:
    handler: mayd.main.Handler
```
* What stacktrace or error message from your provider did you see?
```
ServerlessError: Access Denied
    at BbPromise.fromCallback.catch.err (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:262:11)
From previous event:
    at persistentRequest (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:250:13)
    at doCall (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:206:9)
    at BbPromise (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:219:14)
From previous event:
    at persistentRequest (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:204:38)
    at Object.request.requestQueue.add [as promiseGenerator] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:240:49)
    at Queue._dequeue (/usr/local/lib/node_modules/serverless/node_modules/promise-queue/lib/index.js:153:30)
    at /usr/local/lib/node_modules/serverless/node_modules/promise-queue/lib/index.js:109:18
From previous event:
    at Queue.add (/usr/local/lib/node_modules/serverless/node_modules/promise-queue/lib/index.js:94:16)
    at AwsProvider.request (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:240:39)
    at AwsDeploy.getMostRecentObjects (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/checkForChanges.js:33:26)
From previous event:
    at AwsDeploy.checkForChanges (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/checkForChanges.js:20:8)
From previous event:
    at Object.aws:deploy:deploy:checkForChanges [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:112:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:390:17)
    at AwsDeploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:101:48)
From previous event:
    at Object.deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:97:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:403:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:102:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:42:50)
```
Similar or dependent issues:
* --

## Additional Data

* ***Serverless Framework Version you're using***: 1.27.2
* ***Operating System***: Linux
* ***Stack Trace***: See above
* ***Provider Error messages***:
* Policy in effect:
```JSON
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "lambda:CreateFunction",
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:DeleteSubnet",
                "states:DeleteStateMachine",
                "iam:CreateRole",
                "ec2:AttachInternetGateway",
                "cloudformation:CreateChangeSet",
                "iam:PutRolePolicy",
                "dynamodb:DeleteTable",
                "cloudformation:ContinueUpdateRollback",
                "ec2:DeleteRouteTable",
                "dynamodb:DescribeTable",
                "ec2:CreateInternetGateway",
                "cloudformation:UpdateStack",
                "ec2:DeleteInternetGateway",
                "cloudformation:List*",
                "s3:HeadBucket",
                "cloudformation:ExecuteChangeSet",
                "iam:GetRole",
                "lambda:ListFunctions",
                "lambda:GetEventSourceMapping",
                "ec2:CreateTags",
                "ec2:CreateRouteTable",
                "kinesis:CreateStream",
                "iam:DeleteRole",
                "ec2:DetachInternetGateway",
                "dynamodb:CreateTable",
                "kinesis:DeleteStream",
                "cloudformation:DeleteStack",
                "lambda:ListEventSourceMappings",
                "ec2:DeleteVpc",
                "lambda:DeleteEventSourceMapping",
                "ec2:CreateSubnet",
                "cloudformation:ValidateTemplate",
                "ec2:DeleteNetworkAclEntry",
                "cloudformation:CreateUploadBucket",
                "cloudformation:CancelUpdateStack",
                "ec2:CreateVpc",
                "cloudformation:UpdateTerminationProtection",
                "lambda:GetAccountSettings",
                "lambda:CreateEventSourceMapping",
                "cloudformation:EstimateTemplateCost",
                "ec2:CreateSecurityGroup",
                "iam:DeleteRolePolicy",
                "ec2:CreateNetworkAcl",
                "ec2:ModifyVpcAttribute",
                "ec2:DeleteNetworkAcl",
                "states:CreateStateMachine",
                "lambda:UpdateEventSourceMapping",
                "lambda:UpdateFunctionConfiguration",
                "kinesis:DescribeStream",
                "cloudformation:Describe*",
                "cloudformation:PreviewStackUpdate",
                "ec2:Describe*",
                "s3:ListAllMyBuckets",
                "cloudformation:CreateStack",
                "ec2:DeleteSecurityGroup",
                "ec2:CreateNetworkAclEntry",
                "cloudformation:Get*"
            ],
            "Resource": "*"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "s3:CreateBucket",
                "apigateway:GET"
            ],
            "Resource": [
                "arn:aws:apigateway:*::/restapis",
                "arn:aws:s3:::*"
            ]
        },
        {
            "Sid": "VisualEditor2",
            "Effect": "Allow",
            "Action": [
                "s3:DeleteObjectTagging",
                "apigateway:*",
                "s3:DeleteObjectVersion",
                "s3:GetObjectVersionTagging",
                "s3:ReplicateTags",
                "s3:RestoreObject",
                "s3:PutObjectVersionTagging",
                "s3:DeleteObjectVersionTagging",
                "s3:ListMultipartUploadParts",
                "s3:ReplicateObject",
                "s3:GetObjectVersionTorrent",
                "s3:PutObject",
                "s3:GetObjectAcl",
                "s3:GetObject",
                "s3:GetObjectTorrent",
                "s3:AbortMultipartUpload",
                "s3:GetObjectVersionAcl",
                "s3:GetObjectTagging",
                "s3:PutObjectTagging",
                "s3:GetObjectVersionForReplication",
                "s3:DeleteObject",
                "s3:ReplicateDelete",
                "s3:GetObjectVersion"
            ],
            "Resource": [
                "arn:aws:apigateway:*::/restapis/GATEWAY_ID/*",
                "arn:aws:s3:::*/*"
            ]
        },
        {
            "Sid": "VisualEditor3",
            "Effect": "Allow",
            "Action": "lambda:*",
            "Resource": "arn:aws:lambda:*:*:function:${project}*"
        },
        {
            "Sid": "VisualEditor4",
            "Effect": "Allow",
            "Action": [
                "lambda:CreateFunction",
                "lambda:List*",
                "lambda:Update*",
                "lambda:Get*"
            ],
            "Resource": "arn:aws:lambda:*:*:function:${project}*"
        }
    ]
}
```

**Comment by etgrieco** [comment]
Having a very similar issue where I have to deeply investigate my problem -- I am using an identical policy group for two Lambda services, but one service is working fine while the other is running into a vague access denied message.

**Comment by taschmidt** [comment]
I had the same problem, I tracked it down to this [line](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/lib/checkForChanges.js#L33). And according to the [docs](https://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html), it needs the **s3:ListBucket** permission.

The got past it for me.

**Comment by teddis** [comment]
I have the same problem deploying a 2nd serverless template. I get access denied. Looking at my template, it does appear to include "S3:ListBucket" permission already, so I'm stumped.

**Comment by etgrieco** [comment]
@teddis Are you by any chance deploying to an existing S3 `deploymentBucket`? Or specifying some other already existing-resource in your second template? Something I have found is that when I 'create' resources with `serverless`, I get different access results than if I manually create my target resources myself (buckets, apigateways, etc.) and then deploy to those targeted resources as specified in `serverless.yml`.

**Comment by teddis** [comment]
@etgrieco Thanks, yes, I've been deploying to existing buckets, not expecting serverless would create that for me. See my other post from yesterday: https://github.com/awslabs/serverless-image-handler/issues/80. Temporarily I'm trying to use the old template from November that referenced an older serverless build, hoping that works temporarily.

**Comment by pmuens** [comment]
Thanks for opening and looking into that @elifarley 👍

I'll close this for now since there's little we can do right now. However there's also https://github.com/serverless/serverless/issues/1439 which also contains helpful information.

**Comment by markstos** [comment]
I was rather disappointed to find that adding `--verbose` gave no more information about why access was denied.

**Comment by markstos** [comment]
My problem was easily pinpointed by using `SLS_DEBUG=1 serverless deploy`. That should really be documented in `serverless --help` if not implemented directly with `serverless --debug`.

**Comment by Kulasangar** [comment]
> I had the same problem, I tracked it down to this [line](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/lib/checkForChanges.js#L33). And according to the [docs](https://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html), it needs the **s3:ListBucket** permission.
> 
> The got past it for me.

adding the ListBucket, and PutObject permissions worked for me

**Comment by joeyparis** [comment]
> After adding more permissions to the policy, it worked, but I'll have to perform some kind of binary search in order to find out which permissions are really needed.
> 
> Maybe the code could track each action performed on AWS and list all needed permissions associated with those actions, saving it as a policy file.
> 
> Example:
> 
> ```shell
> serverless deploy --save-policy-to "my-bare-minimum-permissions.json"
> ```

I actually just found this generator. It wasn't perfect and I had to adjust a permission or two but it seemed to mostly get the job done! https://github.com/dancrumb/generator-serverless-policy
