### ISSUE TITLE
Create Template from Path doesn't place boilerplate in working directory

### ISSUE THREAD

**Issue by imaginaryCorn** [serverless/serverless#5003]
# This is a Bug Report

## Description
* What went wrong?
I have started creating my own templates to aid our developers in deploying to AWS Lambda, just so I can add a few extra files and other helpers. But I was presented with an error when trying to create from template using `--template-path` without a path specified.
* What did you expect should have happened?
I should be able to create a boilerplate in the current working directory; the same way that we can with the inbuilt templates using `--template`. 

I ran this using `--name` on my custom template as well, but this creates a new directory of that name in my working directory. This happens even though a path was not specified. 
* What was the config you used?
None, this is pre-deployment.
* What stacktrace or error message from your provider did you see?
```
SLS_DEBUG=* sls create --template-path ~/.serverless/templates/nodejs-6.10-drone                                                                                        14:26:33
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Invoke create
Serverless: Generating boilerplate...

  Type Error ---------------------------------------------

  Path must be a string. Received undefined

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at Create.create (/Users/adoak/.nvm/versions/node/v6.10.0/lib/node_modules/serverless/lib/plugins/create/create.js:129:53)
From previous event:
    at Object.create:create [as hook] (/Users/adoak/.nvm/versions/node/v6.10.0/lib/node_modules/serverless/lib/plugins/create/create.js:96:10)
    at BbPromise.reduce (/Users/adoak/.nvm/versions/node/v6.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/Users/adoak/.nvm/versions/node/v6.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.run (/Users/adoak/.nvm/versions/node/v6.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:403:17)
    at variables.populateService.then (/Users/adoak/.nvm/versions/node/v6.10.0/lib/node_modules/serverless/lib/Serverless.js:102:33)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Serverless.run (/Users/adoak/.nvm/versions/node/v6.10.0/lib/node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (/Users/adoak/.nvm/versions/node/v6.10.0/lib/node_modules/serverless/bin/serverless:42:50)
    at /Users/adoak/.nvm/versions/node/v6.10.0/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/adoak/.nvm/versions/node/v6.10.0/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at initializeErrorReporter.then (/Users/adoak/.nvm/versions/node/v6.10.0/lib/node_modules/serverless/bin/serverless:42:28)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at __dirname (/Users/adoak/.nvm/versions/node/v6.10.0/lib/node_modules/serverless/bin/serverless:28:46)
    at Object.<anonymous> (/Users/adoak/.nvm/versions/node/v6.10.0/lib/node_modules/serverless/bin/serverless:46:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.10.0
     Serverless Version:     1.27.3
```

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***: 1.27.3
* ***Operating System***: MacOS 10.13.4

**Comment by metdockal** [comment]
Did you try this `sls create --template-path ~/.serverless/templates/nodejs-6.10-drone --path node-drone`?
