### ISSUE TITLE
After npm+sls update I get EACCESS or EAGAIN - before that everything was ok

### ISSUE THREAD

**Issue by bence-takacs** [serverless/serverless#5017]
# This is a (Bug Report)

## Description

For bug reports:
* What went wrong?
After an npm +sls update I get  EAGAIN 
And no additional details (see below)
* What did you expect should have happened?
Everything should work as it did before
Or at least I see detailed error messages when using `SLS_DEBUG=true`
* What was the config you used?
```
service: dashboard-test 

provider:
  name: aws
  runtime: nodejs8.10 
  stage: dev
  profile: AMS
  region: eu-west-1
  cfnRole: arn:aws:iam::myCfnrole

plugins:
  - serverless-offline
  #  - serverless-single-page-app-plugin

functions:
  ipsum:
    handler: handler.hello
    events:
      - http:
          method: get
          path: /
```

* What stacktrace or error message from your provider did you see?
Serverless: Recoverable error occured (connect EAGAIN 223.255.255.255:443 - Local (0.0.0.0:63757)), 

## Additional Data

* ***Serverless Framework Version you're using***: 1.27.3
* ***Operating System***: Ubuntu subsystem on Windows 10
* ***Stack Trace***: 
```
$ SLS_DEBUG=true && sls deploy -v
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Recoverable error occured (connect EAGAIN 223.255.255.255:443 - Local (0.0.0.0:63757)), sleeping 5 seconds. Try 1 of 4
Serverless: Recoverable error occured (connect EAGAIN 223.255.255.255:443 - Local (0.0.0.0:63789)), sleeping 5 seconds. Try 2 of 4
Serverless: Recoverable error occured (connect EAGAIN 223.255.255.255:443 - Local (0.0.0.0:63800)), sleeping 5 seconds. Try 3 of 4
Serverless: Recoverable error occured (connect EAGAIN 223.255.255.255:443 - Local (0.0.0.0:63824)), sleeping 5 seconds. Try 4 of 4

  Serverless Error ---------------------------------------

  ServerlessError: connect EAGAIN 223.255.255.255:443 - Local (0.0.0.0:63855)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           10.2.1
     Serverless Version:     1.27.3
```

* ***Provider Error messages***:
Serverless: Recoverable error occured (connect EAGAIN 223.255.255.255:443 - Local (0.0.0.0:63757)), sleeping 5 seconds. Try 1 of 4
Serverless: Recoverable error occured (connect EAGAIN 223.255.255.255:443 - Local (0.0.0.0:63789)), sleeping 5 seconds. Try 2 of 4
Serverless: Recoverable error occured (connect EAGAIN 223.255.255.255:443 - Local (0.0.0.0:63800)), sleeping 5 seconds. Try 3 of 4
Serverless: Recoverable error occured (connect EAGAIN 223.255.255.255:443 - Local (0.0.0.0:63824)), sleeping 5 seconds. Try 4 of 4

**Comment by bence-takacs** [comment]
After reinstalling nodejs + npm and setting up the proxy with its cert I get the same error again:

```
$ npm config set proxy $http_proxy
$ npm config set https-proxy $https_proxy
$ npm config set cafile $cafile
$ SLS_DEBUG=* && sls deploy -v
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Recoverable error occured (connect EAGAIN 223.255.255.255:443 - Local (0.0.0.0:56485)), sleeping 5 seconds. Try 1 of 4
Serverless: Recoverable error occured (connect EAGAIN 223.255.255.255:443 - Local (0.0.0.0:56737)), sleeping 5 seconds. Try 2 of 4
Serverless: Recoverable error occured (connect EAGAIN 223.255.255.255:443 - Local (0.0.0.0:56834)), sleeping 5 seconds. Try 3 of 4
Serverless: Recoverable error occured (connect EAGAIN 223.255.255.255:443 - Local (0.0.0.0:56880)), sleeping 5 seconds. Try 4 of 4

  Serverless Error ---------------------------------------

  ServerlessError: connect EAGAIN 223.255.255.255:443 - Local (0.0.0.0:57044)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           10.3.0
     Serverless Version:     1.27.3
```

So this is more like a npm & proxy issue despite everything is set up correctly.

**Comment by bence-takacs** [comment]
#3508

**Comment by bence-takacs** [comment]
Npm works: can download and install packages

Aws cli also works:
```
> aws iam get-role --profile AMS --role-name myrole
{
    "Role": {
        "AssumeRolePolicyDocument": {
            "Version": "2012-10-17",
            ....
```

I also moved from WSL to native Win 10 and freshly installed NPM and SLS
but the SLS cli still gives me 'ETIMEDOUT' even though I also set the followings:
```
set http_proxy=http://proxy.mycompany.com:80
set https_proxy=%http_proxy%
npm config set proxy=%http_proxy%
npm config set https-proxy=%https_proxy%
set cafile=path/to/proxy-cert
npm config set cafile=%cafile%
```

ERROR:
```
>set SLS_DEBUG=* && sls deploy -v
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: Recoverable error occured (connect ETIMEDOUT 223.255.255.255:443), sleeping 5 seconds. Try 1 of 4
Serverless: Recoverable error occured (connect ETIMEDOUT 223.255.255.255:443), sleeping 5 seconds. Try 2 of 4
Serverless: Recoverable error occured (connect ETIMEDOUT 223.255.255.255:443), sleeping 5 seconds. Try 3 of 4
Serverless: Recoverable error occured (connect ETIMEDOUT 223.255.255.255:443), sleeping 5 seconds. Try 4 of 4

  Serverless Error ---------------------------------------

  ServerlessError: connect ETIMEDOUT 223.255.255.255:443

  Stack Trace --------------------------------------------

ServerlessError: ServerlessError: connect ETIMEDOUT 223.255.255.255:443
    at AwsDeploy.BbPromise.bind.then.catch (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\lib\createStack.js:90:15)
From previous event:
    at AwsDeploy.createStack (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\lib\createStack.js:80:13)
From previous event:
    at Object.aws:deploy:deploy:createStack [as hook] (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\index.js:108:10)
    at BbPromise.reduce (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:372:22)
    at PluginManager.spawn (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:390:17)
    at AwsDeploy.BbPromise.bind.then (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\index.js:101:48)
From previous event:
    at Object.deploy:deploy [as hook] (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\index.js:97:10)
    at BbPromise.reduce (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:372:22)
    at PluginManager.run (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:403:17)
    at variables.populateService.then (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:102:33)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:89:74)
    at serverless.init.then (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\bin\serverless:42:50)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           10.3.0
     Serverless Version:     1.27.3
```

So everything else works, and the issue is still persist both on native win 10 and WSL terminal

I made up a simple project:

handlers.js:
-----------
```
'use strict';

module.exports.hello = (event, context, callback) => {
  const response = {
    statusCode: 200,
    body: JSON.stringify({
      message: '---Go Serverless v1.0! Your function executed successfully!',
      input: event,
    }),
  };

  callback(null, response);

};
```

serverless.yml:
---------------
```
service: dashboard-test 

provider:
  name: aws
  runtime: nodejs8.10 
  stage: dev
  profile: AMS
  region: eu-west-1
  cfnRole: arn:aws:iam::myCfnrole

functions:
  ipsum:
    handler: handler.hello
    events:
      - http:
          method: get
          path: /
```

**Comment by bence-takacs** [comment]
I've put some debug logging inside awsProvider.js 


In the constructor it gets the proxy and the cert also, but when starting the request  (https://github.com/serverless/serverless/blob/master/lib/plugins/aws/provider/awsProvider.js#L202) theese are the parameters it gets

**console.log(params):**

`{ StackName: 'dashboard-test-dev' }`

**console.log(AWS.config):**

```
Config {
  credentials:
   SharedIniFileCredentials {
     expired: false,
     expireTime: null,
     accessKeyId: '...',
     sessionToken:
      '...',
     filename: undefined,
     profile: 'default',
     disableAssumeRole: true,
     preferStaticCredentials: false },
  credentialProvider:
   CredentialProviderChain {
     providers: [ [Function], [Function], [Function], [Function] ] },
  region: undefined,
  logger: null,
  apiVersions: {},
  apiVersion: null,
  endpoint: undefined,
  httpOptions:
   { timeout: 10,
     agent:
      Agent {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] } },
  maxRetries: undefined,
  maxRedirects: 10,
  paramValidation: true,
  sslEnabled: true,
  s3ForcePathStyle: false,
  s3BucketEndpoint: false,
  s3DisableBodySigning: true,
  computeChecksums: true,
  convertResponseTypes: true,
  correctClockSkew: false,
  customUserAgent: null,
  dynamoDbCrc32: true,
  systemClockOffset: 0,
  signatureVersion: null,
  signatureCache: true,
  retryDelayOptions: {},
  useAccelerateEndpoint: false }
```

**...while `AWS.config.httpOptions.agent` should contain the actual proxy settings - according to my understanding**

**Comment by bence-takacs** [comment]
Any ideas regarding the issue?

**Anything I could help in resolving the issue?
If you tell me where should I put some debug lines, I will then post the output.**

I also tried without company proxy and it works...
But I cannot do that at work

**Comment by bence-takacs** [comment]
Maybe this is the solution:
https://github.com/serverless/serverless/issues/3256

**Comment by pmuens** [comment]
Thanks for opening @bence-takacs 👍

Closing this in favor of #3256.
