### ISSUE TITLE
Error when deploying with a freshly installed npm+sls

### ISSUE THREAD

**Issue by bence-takacs** [serverless/serverless#5023]
# This is a (Bug Report)

## Description
On a freshly installed Npm+Sls I cannot deploy a simple project which worked before

For bug reports:
* What went wrong?
`set SLS_DEBUG=* && sls deploy -v` 
caused this:
```
Error: UNKNOWN: unknown error, stat 'C:\Users\me\git\sls-test\src\node_modules\.bin\build-optimizer'
    at Package.getFileContentAndStat (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\plugins\package\lib\zipService.js:106:10)
```
* What did you expect should have happened?
Deployment without issues
* What was the config you used?
```
service: dashboard-test 

provider:
  name: aws
  runtime: nodejs8.10 
  stage: dev
  profile: AMS
  region: eu-west-1
  cfnRole: arn:aws:iam::myrole

functions:
  ipsum:
    handler: handler.hello
    events:
      - http:
          method: get
          path: /
```
* What stacktrace or error message from your provider did you see?
See below

Similar or dependent issues:
* #3915

## Additional Data

* ***Serverless Framework Version you're using***:
1.27.3 (with npm: 10.3.0)
* ***Operating System***:
Win 10
* ***Stack Trace***:
```
set SLS_DEBUG=* && sls deploy -v
...
Serverless: Excluding development dependencies...

  Error --------------------------------------------------

  UNKNOWN: unknown error, stat 'C:\Users\me\git\sls-test\src\node_modules\.bin\build-optimizer'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: UNKNOWN: unknown error, stat 'C:\Users\me\git\sls-test\src\node_modules\.bin\build-optimizer'
    at Package.getFileContentAndStat (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\plugins\package\lib\zipService.js:106:10)
    at Array.map (<anonymous>)
    at WriteStream.output.on (C:\Users\me\AppData\Roaming\npm\node_modules\serverless\lib\plugins\package\lib\zipService.js:83:29)
    at WriteStream.emit (events.js:182:13)
    at WriteStream.EventEmitter.emit (domain.js:442:20)
    at C:\Users\me\AppData\Roaming\npm\node_modules\serverless\node_modules\graceful-fs\graceful-fs.js:214:14
    at C:\Users\me\AppData\Roaming\npm\node_modules\serverless\node_modules\graceful-fs\graceful-fs.js:241:16
    at FSReqWrap.oncomplete (fs.js:169:20)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           10.3.0
     Serverless Version:     1.27.3
```

* ***Provider Error messages***:

**Comment by bence-takacs** [comment]
It seems it was an issue with libraries left in .serverless dir
After removing the whole directory everything became fine
