### ISSUE TITLE
Operation not permitted, scandir attr

### ISSUE THREAD

**Issue by daneholmberg** [serverless/serverless#5031]
Today after updating windows I started getting “Error: EPERM: operation not permitted, scandir ‘C:\Users\Dane\Documents\fv-api-lambda\lambdas\attr’” error. I’ve tried reinstalling serverless, reinstall node, and have searched all over the web to fix this.

Serverless: v1.27.3
npm: v6.1.0
node: v8.11.2
Windows 10 pro version 1803
OS build 17132.81

Full stack trace
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command requirements
Serverless: Load command requirements:clean
Serverless: Load command requirements:install
Serverless: Load command encrypt
Serverless: Load command decrypt
Serverless: Load command prune
Serverless: Load command create_domain
Serverless: Load command delete_domain
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Installing required Python packages with python3.6…
Serverless: Docker Image: lambci/lambda:build-python3.6
Serverless: Linking required Python packages…
Serverless: Packaging service…
Serverless: Excluding development dependencies…

Error --------------------------------------------------

EPERM: operation not permitted, scandir ‘C:\Users\Dane\Documents\fv-api-lambda\lambdas\attr’

 For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
Stack Trace --------------------------------------------

Error: EPERM: operation not permitted, scandir ‘C:\Users\Dane\Documents\fv-api-lambda\lambdas\attr’
at Package.resolveFilePathsAll (C:\Users\Dane\AppData\Roaming\npm\node_modules\serverless\lib\plugins\package\lib\packageService.js:113:48)
at Package.packageAll (C:\Users\Dane\AppData\Roaming\npm\node_modules\serverless\lib\plugins\package\lib\packageService.js:67:17)
at BbPromise.all.then (C:\Users\Dane\AppData\Roaming\npm\node_modules\serverless\lib\plugins\package\lib\packageService.js:58:21)
From previous event:
at Package.packageService (C:\Users\Dane\AppData\Roaming\npm\node_modules\serverless\lib\plugins\package\lib\packageService.js:56:43)
From previous event:
at Object.package:createDeploymentArtifacts [as hook] (C:\Users\Dane\AppData\Roaming\npm\node_modules\serverless\lib\plugins\package\package.js:67:10)
at BbPromise.reduce (C:\Users\Dane\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:372:55)
From previous event:
at PluginManager.invoke (C:\Users\Dane\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:372:22)
at PluginManager.spawn (C:\Users\Dane\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:390:17)
at Deploy.BbPromise.bind.then.then (C:\Users\Dane\AppData\Roaming\npm\node_modules\serverless\lib\plugins\deploy\deploy.js:123:50)
From previous event:
at Object.before:deploy:deploy [as hook] (C:\Users\Dane\AppData\Roaming\npm\node_modules\serverless\lib\plugins\deploy\deploy.js:113:10)
at BbPromise.reduce (C:\Users\Dane\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:372:55)
From previous event:
at PluginManager.invoke (C:\Users\Dane\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:372:22)
at PluginManager.run (C:\Users\Dane\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:403:17)
at variables.populateService.then (C:\Users\Dane\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:102:33)
at runCallback (timers.js:810:20)
at tryOnImmediate (timers.js:768:5)
at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
at Serverless.run (C:\Users\Dane\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:89:74)
at serverless.init.then (C:\Users\Dane\AppData\Roaming\npm\node_modules\serverless\bin\serverless:42:50)
at

**Comment by mattmeye** [comment]
@daneholmberg Have you found a solution in the meantime?

**Comment by daneholmberg** [comment]
@mattmeye I added dockerSsh: true under custom: pythonRequirements and it worked for some reason, and now I am getting the same error again.

**Comment by daneholmberg** [comment]
@mattmeye I just reset my whole pc back to factory and reinstalled everything and got the same error.

**Comment by mattmeye** [comment]
@daneholmberg i tried https://github.com/intelygenz/serverless, but got the same error too - very confusing

**Comment by daneholmberg** [comment]
After installing python-serverless-requirements I'm getting Error: Unable to find good bind path format.

**Comment by mattmeye** [comment]
@daneholmberg I could not wait anymore. I installed a Linux VM and continued to work with it. Nevertheless, I hope that a solution will be found soon.

**Comment by pgrzesik** [comment]
Closing due to inactivity for over 3 years
