### ISSUE TITLE
Python invoke local Error

### ISSUE THREAD

**Issue by dannybrown2** [serverless/serverless#5038]
Getting the following error when running `sls invoke local -f my_function_name`

Also now errors when running my scripts locally without serverless - seems to have to do with this part of all the handlers.
```
try:
    import unzip_requirements
```
Error is:

```
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/invoke.py", line 60, in <module>

    module = import_module(args.handler_path.replace('/', '.'))
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/my_username/Desktop/code/ETL/etl/handlers/my_function_name.py", line 4, in <module>
    import unzip_requirements
  File "/Users/my_username/Desktop/code/ETL/etl/unzip_requirements.py", line 19, in <module>
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 756, in __init__

    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: '/var/task/.requirements.zip'
```

I've had the same config setup for the last 6 months with no errors. Accidentally keyboard interrupted during an `sls deploy` last night after making a small change to a handler and this error has now popped up.

I'm using `serverless-python-requirements` to package the deployment, and running / deploying from a virtual environment.

**Comment by dschep** [comment]
Hi @dannybrown2 you're missing the exception handler after the try:
```python
try:
  import unzip_requirements
except ImportError:
  pass
```
