### ISSUE TITLE
--profile and AWS_PROFILE do not read .aws/config file

### ISSUE THREAD

**Issue by AlacrossWW** [serverless/serverless#5039]
# This is a (Feature Proposal)

## Description
The serverless framework does not currently follow the AWS cli "--profile" functionality. We use a multi-account environment with sts:Assumerole and do not have IAM users on our accounts.

--profile should be able to read the config (not credentials) file in the same way the aws cli does

For feature proposals:
We, as well as many others, use a multi-account environment without individual IAM accounts on each account. IAM roles are used. In this case, the serverless framework will not currently work as it does not read the config file.

I am happy to help contribute if somebody can point me in the right direction

Thanks,
Anthony

**Comment by mconigliaro** [comment]
Yup, if you follow AWS's [Named Profiles](https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html) doc, Serverless won't be able to find any of your profiles:

```
Error --------------------------------------------------

  Profile foo does not exist

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
```

The fix was to move everything to my `~/.aws/credentials` file.

**Comment by robsonalves** [comment]
> Yup, if you follow AWS's [Named Profiles](https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html) doc, Serverless won't be able to find any of your profiles:
> 
> ```
> Error --------------------------------------------------
> 
>   Profile foo does not exist
> 
>      For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
> ```
> 
> The fix was to move everything to my `~/.aws/credentials` file.

That Works!

**Comment by dschep** [comment]
You can also try setting the `AWS_SDK_LOAD_CONFIG=true` env var to make the aws sdk load named profiles from `~/.aws/config`

**Comment by mconigliaro** [comment]
Setting `AWS_SDK_LOAD_CONFIG` worked for me. Here's the pertinent documentation for the JavaScript SDK: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-region.html#setting-region-config-file

**Comment by atz** [comment]
This is a bug inasmuch as it represents a breaking departure from AWS configs that are well established and documented.  Serverless doesn't dictate what syntax and functionality is valid in those files; Amazon does.  In particular, those files have to be reused by AWS CLI, terraform, etc.  When those tools are working with a given a config and Serverless is erroring "profile doesn't exist", *at best* that error message is mistaken.  (The profile does exist in the `config` file.)

Problem is here:
https://github.com/serverless/serverless/blob/master/lib/plugins/aws/provider/awsProvider.js#L93-L97

**Comment by alexreg** [comment]
Any update on this lately? I take it both `--profile` and `AWS_PROFILE` still aren't supported?

**Comment by dschep** [comment]
@alexreg does the `AWS_SDK_LOAD_CONFIG` env var not work for you?

**Comment by alexreg** [comment]
@dschep Will try later. Is this documented anywhere though? I don't see it.

**Comment by mungojam** [comment]
`AWS_SDK_LOAD_CONFIG=true` doesn't solve it for me. I've found that it solves it for terraform, but not for this at the moment.

**Comment by mungojam** [comment]
In my case it may be due to [lack of support for credential_process](https://github.com/serverless/serverless/issues/4838)

**Comment by danielesalvatore** [comment]
@mconigliaro I'm experiencing the same problem right now. I noticed that explicitly setting the profile in the command to start serverless as `AWS_SDK_LOAD_CONFIG=true AWS_PROFILE=my-profile` works

**Comment by dasariramacharan** [comment]
below link helped me clear the issue.. make sure your files are like in the below 

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

**Comment by tijoer** [comment]
This bug still exists.

**Comment by scalp42** [comment]
Same issue here:

```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Deploying additional stacks...
Serverless: Writing template for additional stack permanent...

  Error --------------------------------------------------

  Error: Profile bridge does not exist
      at Object.addProfileCredentials (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:108:15)
      at AwsProvider.getCredentials (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:896:12)
      at AwsProvider.request (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:732:48)
      at AdditionalStacksPlugin.describeStack (/usr/local/lib/node_modules/serverless-plugin-additional-stacks/index.js:323:26)
      at /usr/local/lib/node_modules/serverless-plugin-additional-stacks/index.js:281:33
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.13.0
     Framework Version:         2.4.0
     Plugin Version:            4.0.4
     SDK Version:               2.3.2
```

Config is valid:

```
[profile bridge]
  24 include_profile = anthony
  25 credential_process = sh -c 'aws-vault exec bridge --mfa-token=$(ykman oath code -s anthony@bridge) --duration=1h
     --json 2> $(tty)'
  26 ; credential_process = env AWS_SDK_LOAD_CONFIG=0 aws-vault --prompt=osascript exec --region us-west-2 --duration=1h bridge --json
     n
```
