### ISSUE TITLE
Running sls invoke local --function=preSignUp deletes working directory

### ISSUE THREAD

**Issue by brendan-lovepop** [serverless/serverless#5046]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
Running `sls invoke local --function=preSignUp` deletes the entire working directory
* What did you expect should have happened?
The working directory is not deleted
* What was the config you used?
```
service:auth-service 

plugins:
  - serverless-webpack

custom:
  webpack:
    packager: yarn
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2

functions:
  preSignUp:
    handler: preSignUp.handler
```

```
/* eslint-disable */
const webpack = require("webpack");
const slsw = require("serverless-webpack");
const nodeExternals = require("webpack-node-externals");

module.exports = {
  context: __dirname + "/src",
  target: 'node',
  entry: slsw.lib.entries,
  optimization:{
    minimize: false
  },
  output: {
    libraryTarget: 'commonjs2',
    path: __dirname,
    filename: "[name].js"
  },
  externals:[nodeExternals()],
  module: {
    rules: [{
      test: /\.js$/,
      enforce: "pre",
      exclude: [/node_modules/, /vendor/],
      loader: "eslint-loader",
      options: {
        formatter: require("eslint-friendly-formatter")
      }
    },{
      test: /\.js$/,
      exclude: [/node_modules/, /vendor/],
      loader: "babel-loader"
    }
   ]
  }
};
```
* What stacktrace or error message from your provider did you see?
```
SLS_DEBUG=* sls invoke local --function=preSignUp
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command webpack
Serverless: Invoke invoke:local
Serverless: Invoke webpack:validate
Serverless: Invoke webpack:compile
Serverless: Bundling with Webpack...

  Error --------------------------------------------------

  Cannot find module './node/NodeTemplatePlugin'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: Cannot find module './node/NodeTemplatePlugin'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at WebpackOptionsApply.process (/Users/brendanbuono/src/authentication-cognito-lambdas/node_modules/webpack/lib/WebpackOptionsApply.js:112:27)
    at webpack (/Users/brendanbuono/src/authentication-cognito-lambdas/node_modules/webpack/lib/webpack.js:42:48)
    at ServerlessWebpack.compile (/Users/brendanbuono/src/authentication-cognito-lambdas/node_modules/serverless-webpack/lib/compile.js:11:22)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:390:17)
    at ServerlessWebpack.BbPromise.bind.then.then (/Users/brendanbuono/src/authentication-cognito-lambdas/node_modules/serverless-webpack/index.js:122:92)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
    at process.topLevelDomainCallback (domain.js:101:23)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           9.9.0
     Serverless Version:     1.27.3
```
For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***:
1.27.3
* ***Operating System***:
macOS 10.13.4
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment]
Closing since this seems to be related to the `serverless-webpack` plugin. Please open up an issue in the plugins repository.
