### ISSUE TITLE
Assumed role not found when defined in ~/.aws/config

### ISSUE THREAD

**Issue by roboweaver** [serverless/serverless#5048]
# This is a Bug report 

## Description
When using assumed roles that are defined in ~/.aws/config, sls doesn't find the role passed in via the --aws-profile argument.

For bug reports:
* What went wrong?
Running the command failed with error that the profile doesn't exist.

* What did you expect should have happened?
Command should have executed.

* What was the config you used?
~/.aws/config
```
[profile wf-web]
source_profile = cloud-admin
role_arn = arn:aws:iam::xxxxxxxxx:role/admin
```
* What stacktrace or error message from your provider did you see?

~/.aws/credentials
```
[cloud-admin]
aws_access_key_id = xxxxxx
aws_secret_access_key =  xxxxxxxx
aws_session_token = xxxxxxxxx
aws_security_token = xxxxxxxxx
```

Similar or dependent issues:
None found

## Additional Data

* ***Serverless Framework Version you're using***:  1.27.3
* ***Operating System***: Mac OSX 10.13.5
* ***Stack Trace***:
```
  Stack Trace --------------------------------------------
 
Error: Profile wf-web does not exist
    at Object.addProfileCredentials (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:86:15)
    at AwsProvider.getCredentials (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:312:12)
    at AwsProvider.request (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:199:30)
    at AwsDeploy.create (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:39:26)
From previous event:
    at AwsDeploy.BbPromise.bind.then.catch (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:87:14)
From previous event:
    at AwsDeploy.createStack (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:80:13)
From previous event:
    at Object.aws:deploy:deploy:createStack [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:108:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:390:17)
    at AwsDeploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:101:48)
From previous event:
    at Object.deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:97:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:403:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:102:33)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:42:50)

```
* ***Provider Error messages***:
```
  Error --------------------------------------------------
 
  Profile wf-web does not exist

```

Workaround is to copy the config section for the profile into ~/.aws/credentials, removing the word "profile" from the section header as:
```
[wf-web]
source_profile = cloud-admin
role_arn = arn:aws:iam::xxxxxxxxx:role/admin

```

Note: we are using the gimme-aws-creds project at https://github.com/Nike-Inc/gimme-aws-creds

See forum thread https://forum.serverless.com/t/problem-with-using-assumed-roles-to-deploy/4729 for more info

**Comment by singhabahu** [comment]
@roboweaver did you find a solution for this?, I have the same issue and I'm also using the MFA with this. AWS cli seems to be working fine. 

~/.aws/config
```
[default]
region = us-east-2

[profile PowerUser]
source_profile = default
region = us-east-1
role_arn = arn:aws:iam::xxxxxxxxxxxx:role/PowerUser
mfa_serial = arn:aws:iam::xxxxxxxxxxxx:mfa/user@company.com
```
~/.aws/credentials
```
[default]
aws_access_key_id=***********************
aws_secret_access_key=***************************

[PowerUser]
source_profile = default
role_arn = arn:aws:iam::xxxxxxxxxxxx:role/PowerUser
mfa_serial = arn:aws:iam::xxxxxxxxxxxx:mfa/user@company.com
```

Error I'm getting is bit different. 
```
Serverless: Packaging service...
Serverless: Excluding development dependencies...

 Serverless Error ---------------------------------------

 ServerlessError: AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://bit.ly/aws-creds-setup>.

 Get Support --------------------------------------------
    Docs:          docs.serverless.com
    Bugs:          github.com/serverless/serverless/issues
    Issues:        forum.serverless.com

 Your Environment Information -----------------------------
    OS:                     win32
    Node Version:           10.0.0
    Serverless Version:     1.28.0
```

**Comment by andresmijares** [comment]
were you able to solve this? @singhabahu none workarounds are working for me

**Comment by singhabahu** [comment]
Yeah @andresmijares, Please look into [3833](https://github.com/serverless/serverless/issues/3833) and [assume-role](https://github.com/remind101/assume-role) repo.  It can work with both assume role and MFA.

**Comment by andresmijares** [comment]
@singhabahu could you pls tell me how you are doing it? I'm doing [this](https://github.com/serverless/serverless/issues/3833#issuecomment-411023823) and not working at all, I would appreciate it

**Comment by singhabahu** [comment]
@andresmijares I was able to recreate the issue you're having. If I remove `assume-role.exe PowerUser | Invoke-Expression` I get the same error in Windows. Since you're using `eval $(assume-role name)` it won't be a problem. So try using `sls deploy` without ` --aws-profile name`

**Comment by andresmijares** [comment]
sadly still the issue remains :( @singhabahu thanks anyway man!

**Comment by JmeG** [comment]
Seems to work okay without adding those values to your credentials file if you add this to your local system level env variables.

AWS_SDK_LOAD_CONFIG=1

**Comment by EmiiKhaos** [comment]
Neither copying to ~/.aws/credentials nor `AWS_SDK_LOAD_CONFIG=1` works when using `role_arn` with `credentials_source` set to EC2 instance metadata:

```
[foo-internal]
credential_source = Ec2InstanceMetadata

[foo-dev]
role_arn = arn:aws:iam::ACCOUNTID:role/service-role/ci-cd-prod-gitlab-runner
credential_source = Ec2InstanceMetadata
```
```
{ profile: 'pixelart-dev' } SharedIniFileCredentials {
  expired: false,
  expireTime: null,
  accessKeyId: undefined,
  sessionToken: undefined,
  refreshCallbacks: [],
  filename: undefined,
  profile: 'pixelart-dev',
  disableAssumeRole: false,
  preferStaticCredentials: false,
  tokenCodeFn: null } {}
 
  Error --------------------------------------------------
 
  Profile pixelart-dev does not exist
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: Profile pixelart-dev does not exist
    at Object.addProfileCredentials (/builds/piximizer/piximizer/renditions/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:86:15)
    at Object.addEnvironmentProfile (/builds/piximizer/piximizer/renditions/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:100:12)
    at AwsProvider.getCredentials (/builds/piximizer/piximizer/renditions/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:306:10)
    at AwsProvider.request (/builds/piximizer/piximizer/renditions/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:197:30)
    at Variables.getValueFromCf (/builds/piximizer/piximizer/renditions/node_modules/serverless/lib/classes/Variables.js:657:8)
    at Variables.getValueFromSource (/builds/piximizer/piximizer/renditions/node_modules/serverless/lib/classes/Variables.js:494:20)
    at Variables.splitAndGet (/builds/piximizer/piximizer/renditions/node_modules/serverless/lib/classes/Variables.js:367:17)
    at _.map (/builds/piximizer/piximizer/renditions/node_modules/serverless/lib/classes/Variables.js:304:43)
    at arrayMap (/builds/piximizer/piximizer/renditions/node_modules/lodash/lodash.js:639:23)
    at Function.map (/builds/piximizer/piximizer/renditions/node_modules/lodash/lodash.js:9556:14)
    at Variables.populateMatches (/builds/piximizer/piximizer/renditions/node_modules/serverless/lib/classes/Variables.js:304:14)
    at Variables.populateValue (/builds/piximizer/piximizer/renditions/node_modules/serverless/lib/classes/Variables.js:335:30)
    at _.map.variable (/builds/piximizer/piximizer/renditions/node_modules/serverless/lib/classes/Variables.js:223:24)
    at arrayMap (/builds/piximizer/piximizer/renditions/node_modules/lodash/lodash.js:639:23)
    at Function.map (/builds/piximizer/piximizer/renditions/node_modules/lodash/lodash.js:9556:14)
    at Variables.populateVariables (/builds/piximizer/piximizer/renditions/node_modules/serverless/lib/classes/Variables.js:222:14)
    at Variables.populateObjectImpl (/builds/piximizer/piximizer/renditions/node_modules/serverless/lib/classes/Variables.js:251:30)
    at assignProperties.then (/builds/piximizer/piximizer/renditions/node_modules/serverless/lib/classes/Variables.js:256:24)
From previous event:
    at Variables.populateObjectImpl (/builds/piximizer/piximizer/renditions/node_modules/serverless/lib/classes/Variables.js:256:8)
    at prepopulateService.then (/builds/piximizer/piximizer/renditions/node_modules/serverless/lib/classes/Variables.js:135:26)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at initialCall (/builds/piximizer/piximizer/renditions/node_modules/serverless/lib/classes/Variables.js:135:10)
    at Variables.initialCall (/builds/piximizer/piximizer/renditions/node_modules/serverless/lib/classes/Variables.js:66:12)
    at Variables.populateService (/builds/piximizer/piximizer/renditions/node_modules/serverless/lib/classes/Variables.js:133:17)
    at Serverless.run (/builds/piximizer/piximizer/renditions/node_modules/serverless/lib/Serverless.js:111:27)
    at serverless.init.then (/builds/piximizer/piximizer/renditions/node_modules/serverless/bin/serverless:43:50)
    at <anonymous>
 ```

**Comment by EmiiKhaos** [comment]
Ok, found it: https://github.com/aws/aws-sdk-js/issues/1916 it's currently not supported in the SDK. That's a bummer, had the same with the Go SDK. They are adding features on the CLI, but hardly any SDK supports those new features :(

**Comment by brianneisler** [comment]
Believe support for this was added in #5432

**Comment by huksley** [comment]
Still having problems in 1.36.3 with assume role
- [x] Using AWS_SDK_LOAD_CONFIG=1 does not work
- [x] Copy-pasting role_arn, source_profile to ~/.aws/credentials results in serverless binary crash (outputs nothing at all)

**Comment by hojatbay** [comment]
still not working for me. Tried both config and credentials files and no lucks. 
~/.aws/config file:

[profile production]
role_arn = arn:aws:iam::50459568343:role/cross-account-role
region = us-east-1
credential_source = EcsContainer

running `aws s3 ls --profile production` succeeds
running `serverless deploy --aws-profile production --stage prod` fails: `profile production does not exist`!

**Comment by bweigel** [comment]
@hojatbay the problem is not a serverless one. It lies upstream, in the aws javascript sdk. Using `credential_source` is not implemented in the aws-js-sdk (only in boto3) at the moment. There is an open feature request however: https://github.com/aws/aws-sdk-js/issues/1916.

**Comment by bweigel** [comment]
@hojatbay the aws cli is implemented in python and uses boto3/botocore. This feature exists in botocore and thus it works for the aws cli.

**Comment by atheken** [comment]
It appears that a patch was provided to solve this issue, but not documented in this thread if you set this env var for your serverless run, it should use the correct profile.

`AWS_SDK_LOAD_CONFIG=true`

**Comment by ut0mt8** [comment]
Well for me I have to set
`AWS_SHARED_CREDENTIALS_FILE=/home/xx/.aws/credentials` 
for sls to work with assume role (without the handly go tool).

**Comment by soulnix** [comment]
Hi, not working for me.
trying export 
`AWS_SDK_LOAD_CONFIG=true
AWS_SHARED_CREDENTIALS_FILE="/home/max/.aws/credentials"  `
Environment
```
     Operating System:          linux
     Node Version:              12.13.0
     Framework Version:         1.58.0
     Plugin Version:            3.2.4
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```
Error
```
  Serverless Error ---------------------------------------
 
  Could not locate deployment bucket. Error: AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://slss.io/aws-creds-setup>.
```
But bucket exists, I have been tried run sls with profile key in the provider section also try cli prefix and environment variable
