### ISSUE TITLE
Conflict with .pyre file

### ISSUE THREAD

**Issue by jasonkuhrt** [serverless/serverless#5059]
When I use [`pyre`](https://pyre-check.org/) it breaks `serverless deploy`
```
❯ sls deploy --stage dev
Serverless: Generating requirements.txt from Pipfile...
Serverless: Installing requirements of requirements.txt in .serverless...
Serverless: Packaging service...
Serverless: Excluding development dependencies...

  Error --------------------------------------------------

  Unknown system error -102: Unknown system error -102, open '/Users/jasonkuhrt/projects/dialogue/unresponsive/.pyre/server/server.sock'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.11.1
     Serverless Version:     1.27.2
```

**Comment by jasonkuhrt** [comment]
```
❯ SLS_DEBUG=* sls deploy -s dev
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command invoke
Serverless: Load command invoke:stepf
Serverless: Load command requirements
Serverless: Load command requirements:clean
Serverless: Load command requirements:install
Serverless: Load command runWithEnvironment
Serverless: WARNING: Plugin ServerlessDeployEnvironment uses deprecated hook before:deploy:createDeploymentArtifacts,
                     use package:createDeploymentArtifacts hook instead
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Generating requirements.txt from Pipfile...
Serverless: Installing requirements of requirements.txt in .serverless...
Serverless: Packaging service...
Serverless: Excluding development dependencies...

  Error --------------------------------------------------

  Unknown system error -102: Unknown system error -102, open '/Users/jasonkuhrt/projects/dialogue/unresponsive/.pyre/server/server.sock'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: Unknown system error -102: Unknown system error -102, open '/Users/jasonkuhrt/projects/dialogue/unresponsive/.pyre/server/server.sock'
    at Package.getFileContent (/Users/jasonkuhrt/.nvm/versions/node/v8.11.1/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:116:15)
    at Package.getFileContentAndStat (/Users/jasonkuhrt/.nvm/versions/node/v8.11.1/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:105:12)
    at Array.map (<anonymous>)
    at WriteStream.output.on (/Users/jasonkuhrt/.nvm/versions/node/v8.11.1/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:83:29)
    at emitOne (events.js:116:13)
    at WriteStream.emit (events.js:211:7)
    at /Users/jasonkuhrt/.nvm/versions/node/v8.11.1/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:214:14
    at /Users/jasonkuhrt/.nvm/versions/node/v8.11.1/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:241:16
    at FSReqWrap.oncomplete (fs.js:135:15)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.11.1
     Serverless Version:     1.27.2
```

**Comment by jasonkuhrt** [comment]
Work around:

```yaml
package:
  exclude:
    - .pyre/**
```

https://serverless.com/framework/docs/providers/aws/guide/packaging/

**Comment by pmuens** [comment]
Thanks for opening @jasonkuhrt 👍

Yes, it looks like excluding seems like the best solution to this problem. Closing this for now since your workaround seems to work fine.
