### ISSUE TITLE
throw exit 1 on deployment errors

### ISSUE THREAD

**Issue by Wolfie010** [serverless/serverless#5061]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong?
sls deploy --stage did not throw exit status 1 on failed deployment
* What did you expect should have happened?
sls deploy should throw exit status 1 if a issue occurs

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
if serverless has a deployment error, whether it is permissions issue or just a plain error exit 1 should be thrown.

## Additional Data

* ***Serverless Framework Version you're using***:
1.27.3
* ***Operating System***:
mac os high sierra

**Comment by pmuens** [comment]
Closing since this issue is quite stale and we haven't got enough information. Feel free to re-open ince you have more information to share.

**Comment by jeanlescure** [comment]
I'm having same issue reported. To provide more information:

- **Serverless Framework Version you're using:**
    1.27.3
- **Operating Systems:**
    mac os high sierra
    alpine linux

The `sls deploy` command failed since the IAM user referenced from the AWS_ACCESS_KEY did not have the necessary permissions to validate CloudFormation templates, thus it outputted the following error:

```
Unhandled rejection Error: The CloudFormation template is invalid: User: arn:aws:iam::xxx:user/xxx-user is not authorized to perform: cloudformation:ValidateTemplate
```

Yet the process exited with code `0` and this in turn caused the automated deployment I was testing to incorrectly report that the deployment was successful.

![Example of incorrect deployment status](http://stelligent.com/wp-content/uploads/2016/04/codepipeline_codecommit-1.jpg)

**Comment by evheniy** [comment]
Exit 0.
CI doesn't see any problems.

Unhandled rejection ServerlessError: An error occurred: TableName - CloudFormation cannot update a stack when a custom-named resource requires replacing. Rename Table and update the stack again..
    at provider.request.then.data (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:121:33)
    at tryCatcher (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)

**Comment by bcouetil** [comment]
Same problem here, can someone reopen this ? @pmuens ?

**Comment by oligirling** [comment]
Also got the same issue when adding sls deploy to travis script.

```
sls deploy --stage integration
Unhandled rejection ServerlessError: AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://slss.io/aws-creds-setup>.
at serverless.getProvider.request.then.catch.err (/home/travis/build/demo/sls_location_api/node_modules/serverless/lib/classes/Variables.js:802:35)
at tryCatcher (/home/travis/build/demo/sls_location_api/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/home/travis/build/demo/sls_location_api/node_modules/bluebird/js/release/promise.js:517:31)
313    at Promise._settlePromise (/home/travis/build/demo/sls_location_api/node_modules/bluebird/js/release/promise.js:574:18)
at Promise._settlePromise0 (/home/travis/build/demo/sls_location_api/node_modules/bluebird/js/release/promise.js:619:10)
at Promise._settlePromises (/home/travis/build/demo/sls_location_api/node_modules/bluebird/js/release/promise.js:695:18)
at _drainQueueStep (/home/travis/build/demo/sls_location_api/node_modules/bluebird/js/release/async.js:138:12)
at _drainQueue (/home/travis/build/demo/sls_location_api/node_modules/bluebird/js/release/async.js:131:9)
at Async._drainQueues (/home/travis/build/demo/sls_location_api/node_modules/bluebird/js/release/async.js:147:5)
at Immediate.Async.drainQueues [as _onImmediate] (/home/travis/build/demo/sls_location_api/node_modules/bluebird/js/release/async.js:17:14)
at runCallback (timers.js:705:18)
at tryOnImmediate (timers.js:676:5)
at processImmediate (timers.js:658:5)
 at process.topLevelDomainCallback (domain.js:120:23)

The command "sls deploy --stage integration" exited with 0
```

**Comment by ahmedsaab** [comment]
Please reopen this issue.

**Comment by dougmoscrop** [comment]
I think the changes made here: https://github.com/serverless/serverless/commit/c8709af12e8cb4b239c450eca7f72147a1a4af72 may help

I just tested with serverless 1.50 and I get an exit code of 1 when I e.g. have no credentials as @oligirling showed above

**Comment by ahmedsaab** [comment]
Updating from 1.49 to 1.50 fixed the issue for me. Also I was getting some permissions failure for AWS resources so I guess this fix is not only for the no credentials error. Thanks!

**Comment by nolanding** [comment]
Exited with code 1
Failing while deploying on following command - Error: `python3.8 -m pip install -t path -r path --cache-dir path`.
Not getting what is a possible error.

**Comment by zommerfelds** [comment]
Same here.

```
[!] Invalid configuration encountered
  at 'functions.contact': unrecognized property 'custom'
```

Still, `npx sls deploy` exists happily and CI can't know that the command failed.
