### ISSUE TITLE
Cannot find module './lib/createStack'

### ISSUE THREAD

**Issue by bence-takacs** [serverless/serverless#5091]
# This is a (Bug Report)

## Description

For bug reports:
* What went wrong?
```
 export SLS_DEBUG="*" && sls deploy -v
...
Error --------------------------------------------------

  Cannot find module './lib/createStack'
```
* What did you expect should have happened?
deploy continues without error
* What was the config you used?
Is that important in that case?
* What stacktrace or error message from your provider did you see?
```
Error: Cannot find module './lib/createStack'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:16:21)
```

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***:
1.27.3
* ***Operating System***:
Windows Subsystem for Linux (Win 10)
* ***Stack Trace***:

```
Serverless: Load command config:credentials

  Error --------------------------------------------------

  Cannot find module './lib/createStack'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: Cannot find module './lib/createStack'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:16:21)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at plugins.forEach (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:90:24)
    at Array.forEach (<anonymous>)
    at PluginManager.loadPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:88:13)
    at PluginManager.loadCorePlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:129:10)
    at PluginManager.loadAllPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:83:10)
    at service.load.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:67:28)
From previous event:
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at /usr/local/lib/node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:46:4)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:240:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:564:3)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           10.5.0
     Serverless Version:     1.27.3
```

* ***Provider Error messages***:

**Comment by pmuens** [comment]
Thanks for opening @bence-takacs 👍

I'll close this issue for now since it's quite stale and we've fixed a couple of bugs. Please update and try the new version of the Serverless Framework. Feel free to re-open if you still see this problem.
