### ISSUE TITLE
Bug with "non-existent" profile when using different AWS and Serverless profile names

### ISSUE THREAD

**Issue by sjl2** [serverless/serverless#5098]
# This is a Bug Report

### What went wrong?

We have a lambda function deployed to picasso. It has multiple profiles: `staging` and `production`. However, these functions are deployed to two different, respective AWS profiles: `old_staging` and `old_production`. Thus, when we deploy, we run:
```
serverless deploy --profile staging --aws-profile old_staging
serverless deploy --profile production --aws-profile old_production
```
When trying to deploy our lambda function via Serverless 1.27.3 we got the error:
```
  Error --------------------------------------------------

  Profile staging does not exist

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: Profile staging does not exist
    at Object.addProfileCredentials (/my/app/path/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:87:15)
    at AwsProvider.getCredentials (/my/app/path/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:307:12)
    at AwsProvider.request (/my/app/path/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:200:30)
    at AwsDeploy.create (/my/app/path/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:39:26)
```

Thus, I was unable to deploy our lambda function, despite having all of the correct credentials set-up under my `~/.aws` credentials.

### Resolution
**HOWEVER**, we realized that when I added a completely irrelevant AWS Profile credentials to my credentials file called `staging` and `production` to match the name of the Serverless profile it worked with no errors. When `console.log`ing around, we realized that multiple calls to [`addProfileCredentials`](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/provider/awsProvider.js#L75) were being made, at least one with the serverless profile instead of the AWS profile. Because we have a different name, the command would fail when it wasn't present.

We have not been able to pinpoint exactly in the code what's requiring an AWS Profile to exist with the same name as the serverless profile, but we think this is probably a bug. It doesn't seem like it should be necessary to have the serverless profile match the AWS Profile name or an arbitrary one on the system. In our case, it has required us to add a bogus profile to my `~/.aws` file to build.

### Similar or dependent issues
* [#5039](https://github.com/serverless/serverless/issues/5039)?

## Additional Data

* ***Serverless Framework Version you're using***: 1.27.3
* ***Operating System***: Mac OS X El Capitan 10.11.6
* ***Stack Trace***:
```
  Error --------------------------------------------------

  Profile staging does not exist

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: Profile staging does not exist
    at Object.addProfileCredentials (/my/app/path/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:87:15)
    at AwsProvider.getCredentials (/my/app/path/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:307:12)
    at AwsProvider.request (/my/app/path/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:200:30)
    at AwsDeploy.create (/my/app/path/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:39:26)
```
* ***Provider Error messages***: N/A

**Comment by sjl2** [comment]
@dmlittle @robinjoseph08

**Comment by ssteo** [comment]
I confirm this bug still exist and serverless doesn't read from .aws/credentials. I'm using:

```
serverless 1.35.0
node 11.4.0
Darwin MUCN0315.gs24.com 17.7.0 Darwin Kernel Version 17.7.0: Fri Nov  2 20:43:16 PDT 2018; root:xnu-4570.71.17~1/RELEASE_X86_64 x86_64
```

**Comment by dschep** [comment]
Hey folks, I didn' trealize tehre was also a `--profile` option. The only place I can find that is the `sls config credentials` subcommand.

Furthermore, what behavior are you expecting when you specify 2 profiles when deploying?

**Comment by ssteo** [comment]
In my case, I've only specified the profile once under serverless.yml provider, sls complained about unable to find the profile name. Also, tried just using `--profile aws_profile_name` and removed profile field in serverless.yml and sls also complained the same.

**Comment by dschep** [comment]
I still don't follow why you're using the `--profile` option. AFAIK the ways of setting the AWS profile at deploy time are:
 * the `profile` key in the `provider` section of `serverless.yml`
 * the `AWS_PROFILE` env var
 * the `--aws-profile` CLI option

**Comment by ssteo** [comment]
Ok, ignore about my attempt using `--aws-profile`. I've tried using:
- the profile key in the provider section of serverless.yml
- the AWS_PROFILE env var

Both doesn't work as well. `sls deploy` gives me ` Profile my_aws_profile_name does not exist` even though it exists in `~/.aws/credentials`

**Comment by dschep** [comment]
Could you share your project(or censored version there of) that exhibits this behavior? I've just tested with the `AWS_PROFILE` env var, `--aws-profile` CLI option and the `profile` config file option and all worked as expected.

**Comment by ssteo** [comment]
It only works when I did the following:
- Remove `profile: devawsaccount` from serverless.yml
- Manually run `export AWS_ACCESS_KEY_ID=AKIAxxx`
- Manually run `export AWS_SECRET_ACCESS_KEY=xxxx`
- `sls deploy`

**Comment by ssteo** [comment]
And the verbose stack trace

```
Serverless: Creating Stack...

  Error --------------------------------------------------

  Profile devawsaccount does not exist

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: Profile devawsaccount does not exist
    at Object.addProfileCredentials (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:96:15)
    at AwsProvider.getCredentials (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:323:12)
    at AwsProvider.request (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:209:30)
    at createDeployment.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:39:61)
From previous event:
    at AwsDeploy.create (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:39:36)
From previous event:
    at AwsDeploy.BbPromise.bind.then.catch (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:88:14)
From previous event:
    at AwsDeploy.createStack (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:81:13)
From previous event:
    at Object.aws:deploy:deploy:createStack [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:102:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:391:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:391:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:409:17)
    at AwsDeploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:95:48)
From previous event:
    at Object.deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:91:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:391:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:391:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:422:17)
    at variables.populateService.then.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:157:33)
    at processImmediate (timers.js:632:19)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:44:28)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
```

**Comment by ssteo** [comment]
It seems the problem is somewhere in the AWS provider plugin `/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js`

Let me know if any further info. I can provide to help with the issue.

**Comment by dschep** [comment]
Aha! Finally recreated the issue. The config option names in `~/.aws/credentials` must be lowercase. IE:
```ini
[default]
aws_access_key_id = AKIAxxx
aws_secret_access_key = xxxx

[devawsaccount]
aws_access_key_id = AKIAxxxx
aws_secret_access_key = xxxxx
```

**Comment by ssteo** [comment]
Cool, good to know. Will you push a fix out soon or..? Meanwhile I'll switch to lowercase, hopefully my other stuff doesn't break ;-)

**Comment by dschep** [comment]
Glad it works. There's no fix to push tho, it's a requirement of the `aws-sdk` (that's what's being used to load the config file)
