### ISSUE TITLE
sls 1.28.0 - Lambda with spread in object literal throws "unexpected token" error on deploy

### ISSUE THREAD

**Issue by heylookalive** [serverless/serverless#5128]
# This is a Bug Report

## Description

When deploying a Lambda function which uses the  Node 8.10 runtime and certain syntax Serverless is throwing a "Syntax error" response.

The code that is causing a problem is:
`const args = { ...argDefaults, ...event };`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Spread_in_object_literals

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***: 1.28.0
* ***Operating System***: Mac OS
* ***Stack Trace***:
  Stack Trace --------------------------------------------
 
SyntaxError: /Users/xxxx/Sitesxxxx/src/lambda/appsync/elasticSearchListDataSource.js: Unexpected token (134:17) while parsing file: /Users/xxxx/Sitesxxxx/src/lambda/appsync/elasticSearchListDataSource.js
SyntaxError: /Users/xxxx/Sitesxxxx/src/lambda/appsync/elasticSearchListDataSource.js: Unexpected token (134:17)
  132 |     page: null
  133 |   };
> 134 |   const args = { ...argDefaults, ...event };
      |                  ^
  135 | 
  136 |   // Validate our args, do this at the mapping template level too (so the req
  137 |   // never hits the Lambda. But still, this keeps things robust.
    at Parser.pp$5.raise (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseIdentifier (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:4332:10)
    at Parser.pp$3.parsePropertyName (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:4156:96)
    at Parser.pp$3.parseObj (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:4045:12)
    at Parser.pp$3.parseExprAtom (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:3719:19)
    at Parser.pp$3.parseExprSubscripts (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$1.parseVar (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:2340:24)
    at Parser.pp$1.parseVarStatement (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:2169:8)
    at Parser.pp$1.parseStatement (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:1861:19)
    at Parser.pp$1.parseBlockBody (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseBlock (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:2247:8)
    at Parser.pp$3.parseFunctionBody (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:4235:22)
    at Parser.pp$3.parseArrowExpression (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:4190:8)
    at Parser.pp$3.parseAsyncArrowFromCallExpression (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:3590:15)
    at Parser.pp$3.parseSubscripts (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:3540:21)
    at Parser.pp$3.parseExprSubscripts (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:3504:15)
    at Parser.pp$3.parseMaybeUnary (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseMaybeAssign (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:3367:23)
    at Parser.pp$3.parseExpression (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:3306:19)
    at Parser.pp$1.parseStatement (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:1906:19)
    at Parser.pp$1.parseBlockBody (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:1673:17)
    at parse (/Users/xxxx/Sitesxxxx/node_modules/babylon/lib/index.js:7305:37)
    at File.parse (/Users/xxxx/Sitesxxxx/node_modules/babel-core/lib/transformation/file/index.js:485:15)
    at File.parseCode (/Users/xxxx/Sitesxxxx/node_modules/babel-core/lib/transformation/file/index.js:570:20)
    at /Users/xxxx/Sitesxxxx/node_modules/babel-core/lib/transformation/pipeline.js:49:12
    at File.wrap (/Users/xxxx/Sitesxxxx/node_modules/babel-core/lib/transformation/file/index.js:532:16)
    at Pipeline.transform (/Users/xxxx/Sitesxxxx/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
    at Babelify._flush (/Users/xxxx/Sitesxxxx/node_modules/babelify/index.js:26:24)
    at Babelify.prefinish (_stream_transform.js:141:10)
    at Babelify.emit (events.js:182:13)
    at Babelify.EventEmitter.emit (domain.js:442:20)
    at prefinish (_stream_writable.js:630:14)
    at finishMaybe (_stream_writable.js:638:5)
    at endWritable (_stream_writable.js:649:3)
    at Babelify.Writable.end (_stream_writable.js:589:5)
    at DuplexWrapper.<anonymous> (/Users/xxxx/Sitesxxxx/node_modules/duplexer2/index.js:29:14)
    at Object.onceWrapper (events.js:273:13)
    at DuplexWrapper.emit (events.js:187:15)
    at DuplexWrapper.EventEmitter.emit (domain.js:442:20)
    at finishMaybe (/Users/xxxx/Sitesxxxx/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at endWritable (/Users/xxxx/Sitesxxxx/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at DuplexWrapper.Writable.end (/Users/xxxx/Sitesxxxx/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DestroyableTransform.onend (/Users/xxxx/Sitesxxxx/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:273:13)
    at DestroyableTransform.emit (events.js:187:15)
    at DestroyableTransform.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (/Users/xxxx/Sitesxxxx/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:408:17)
    at Deploy.BbPromise.bind.then.then (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:123:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:113:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:421:17)
    at variables.populateService.then.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:163:33)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:150:8)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:42:50)

**Comment by pmuens** [comment]
Hey @heylookalive thanks for opening 👍

🤔 that's definitely odd and should work. Could you provide your `serverless.yml` so that we can look into it?

Thanks!

**Comment by pmuens** [comment]
Closing since this issue is quite stale and there was no additional information provided. Feel free to re-open once more information is available.

**Comment by ffxsam** [comment]
@pmuens Could you please re-open? This is still an issue.

The `aws-nodejs-ecma-script` surprisingly doesn't come with the proper config to allow object spread.. which is odd, especially since we're now using Node.js 12.x which supports object spread natively.
