### ISSUE TITLE
Exclude patterns in a template

### ISSUE THREAD

**Issue by AniAko** [serverless/serverless#518]
when I run `sls dash deploy` I get the following error:
```
Serverless: Deploying functions in "development" to the following regions: us-east-1  
Serverless: ------------------------  
Serverless: Failed to deploy the following functions in "development" to the following regions:  
Serverless: us-east-1 ------------------------  
Serverless:   RestAPI-nodejs/login/authenticate: excludePatterns.some is not a function
```

My template is as follows:
```
{
  "commonCodeExcludePatterns": ["test/", "package.json", "README.md", ".git", ".gitignore"]
}
```

and used in the s-function.json:
```
{
  "name": "authenticate",
  "handler": "login/authenticate/handler.handler",
  "timeout": 6,
  "memorySize": 1024,
  "custom": {
    "excludePatterns": "$${commonCodeExcludePatterns}",
    "envVars": []
  },
  "endpoints": [
    {
      "path": "authenticate",
      "method": "POST",
      "authorizationType": "none",
      "apiKeyRequired": false,
      "requestParameters": {},
      "requestTemplates": "$${apiGatewayRequestTemplate}",
      "responses": "$${apiGatewayEndpointResponses}"
    }
  ]
}
```

Here is the stack trace from the --debug flag:
```
 serverless:lib.node_modules.serverless.lib.actions.FunctionDeploy TypeError: excludePatterns.some is not a function
    at wrench.copyDirSyncRecursive.exclude.prefix (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/lib/actions/CodePackageLambdaNodeJs.js:164:36)
    at isMatch (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/node_modules/wrench/lib/wrench.js:179:20)
    at isFileIncluded (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/node_modules/wrench/lib/wrench.js:189:17)
    at Object.exports.copyDirSyncRecursive (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/node_modules/wrench/lib/wrench.js:261:22)
    at Packager._createDistFolder (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/lib/actions/CodePackageLambdaNodeJs.js:151:14)
From previous event:
    at Packager.package (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/lib/actions/CodePackageLambdaNodeJs.js:73:10)
    at CodePackageLambdaNodejs.codePackageLambdaNodejs (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/lib/actions/CodePackageLambdaNodeJs.js:50:30)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
From previous event:
    at /home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/lib/Serverless.js:182:25
    at Array.reduce (native)
    at Serverless._execute (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/lib/Serverless.js:181:26)
    at Object.actions.(anonymous function) [as codePackageLambdaNodejs] (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/lib/Serverless.js:384:20)
    at /home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:283:40
From previous event:
    at /home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:266:31
    at replenish (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/node_modules/async/lib/async.js:191:21)
    at /home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/node_modules/async/lib/async.js:208:15
    at Object.async.eachLimit (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/node_modules/async/lib/async.js:168:12)
    at /home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:262:15
From previous event:
    at FunctionDeploy._deployCodeByRegion (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:255:14)
    at FunctionDeploy.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:238:24)
From previous event:
    at FunctionDeploy._processDeployment (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:235:10)
From previous event:
    at FunctionDeploy.functionDeploy (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:108:10)
From previous event:
    at /home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/lib/Serverless.js:182:25
    at Array.reduce (native)
    at Serverless._execute (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/lib/Serverless.js:181:26)
    at Object.actions.(anonymous function) [as functionDeploy] (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/lib/Serverless.js:384:20)
    at BbPromise.then._this.S.actions.endpointDeploy.options.stage (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/lib/actions/DashDeploy.js:284:32)
From previous event:
    at DashDeploy._deploy (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/lib/actions/DashDeploy.js:279:14)
From previous event:
    at DashDeploy.dashDeploy (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/lib/actions/DashDeploy.js:132:10)
From previous event:
    at /home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/lib/Serverless.js:157:29
    at Array.reduce (native)
    at /home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/lib/Serverless.js:156:30
    at processImmediate [as _immediateCallback] (timers.js:374:17)
From previous event:
    at Serverless._execute (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/lib/Serverless.js:154:10)
    at Serverless.actions.(anonymous function) (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/lib/Serverless.js:384:20)
    at Serverless.command (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/lib/Serverless.js:353:38)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/serverless/bin/serverless:16:12)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3 +129ms
```

**Comment by flomotlik** [comment]
Which version of Serverless is this running against? Are you setting the some variable somewhere? I will close this issue for now, if you can provide more info we'll repoen.
