### ISSUE TITLE
Invalid string length when using 1.3

### ISSUE THREAD

**Issue by 25564** [serverless/serverless#5214]
# This is a Bug Report

## Description
Receiving this error in 1.3 when deploying some of our larger services (by FileSize). Currently the Largest of the services is 16mb. Downgrading to 1.29.2 does not display this error and deploys as expected.

## Additional Data

* ***Operating System***:
OS:                     linux
Node Version:           5.12.0

* ***Stack Trace***:
```
Invalid string length

RangeError: Invalid string length
    at String.replace (native)
    at RegExp.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/core-js/modules/_fix-re-wks.js:22:46)
    at String.replace (/usr/local/lib/node_modules/serverless/node_modules/core-js/modules/es6.regexp.replace.js:9:12)
    at replaceall (/usr/local/lib/node_modules/serverless/node_modules/replaceall/replaceall.min.js:5:67)
    at Variables.populateVariable (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:382:18)
    at Variables.renderMatches (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:317:21)
    at /usr/local/lib/node_modules/serverless/lib/classes/Variables.js:337:29
From previous event:
    at Variables.populateValue (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:337:8)
    at /usr/local/lib/node_modules/serverless/lib/classes/Variables.js:223:24
    at arrayMap (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:639:23)
    at Function.map (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:9554:14)
    at Variables.populateVariables (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:222:14)
    at Variables.populateObjectImpl (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:251:30)
From previous event:
    at Variables.populateObjectImpl (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:256:8)
    at /usr/local/lib/node_modules/serverless/lib/classes/Variables.js:135:26
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/classes/Variables.js:135:10
    at Variables.initialCall (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:66:12)
    at Variables.populateService (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:133:17)
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:111:27)
    at /usr/local/lib/node_modules/serverless/bin/serverless:43:50
    at run (/usr/local/lib/node_modules/serverless/node_modules/core-js/modules/es6.promise.js:75:22)
    at /usr/local/lib/node_modules/serverless/node_modules/core-js/modules/es6.promise.js:92:30
    at flush (/usr/local/lib/node_modules/serverless/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by kyledgreen** [comment]
I'm encountering this too.

**Comment by frankyjuang** [comment]
same here

**Comment by exoego** [comment]
If I understand correctly, this is an upstream (nodejs) issue, therefore cannot be addressed in serverless.

There is *a hard limit* in JavaScript string length on JS engine V8 in nodejs.
Upgrading nodejs to v9.4 or later increase the limit and may lower the risk.

https://github.com/nodejs/help/issues/1061#issuecomment-356714457
>There is a limit for max string length in JavaScript. V8 has recently increased this limit:
>
>Node.js 8.9.4 (V8 6.1): 268 435 440 UTF-16 code units
>Node.js 9.4.0 (V8 6.2): 1 073 741 799 UTF-16 code units

**Comment by orsinijose** [comment]
I recently dealt with the same `Invalid string length` issue, using the following versions of sls and node:
```
     OS: mac.
     Node Version:           11.6.0
     Serverless Version:     1.30.1
```
It's pretty much related to the size of my serverless.yml file. Oddly, it all seems to work by using different versions of sls and node (this time running from a docker container I have for testing purposes):

```
bash-4.4# node --version
v8.11.4
bash-4.4# sls version
1.32.0
```

So might this be related to serverless version, since recent reports indicate this works for 1.32+ onwards.
