### ISSUE TITLE
Invalid string length after upgrading to 1.30.0

### ISSUE THREAD

**Issue by DeX3** [serverless/serverless#5234]
# This is a Bug Report
This might be related to #5214 - although a different version is mentioned there (this maybe a typo in that issue).

For me, this happens since upgrading serverless to `1.30.0` (tested fine with `1.29.0`). 

Detailed log after setting `SLS_DEBUG="*"`:
```
RangeError: Invalid string length
    at String.replace (<anonymous>)
    at replaceall (/Users/romande/projects/prs/prs-medoca-pet-profile/api/node_modules/replaceall/replaceall.min.js:5:67)
    at Variables.populateVariable (/Users/romande/projects/prs/prs-medoca-pet-profile/api/node_modules/serverless/lib/classes/Variables.js:382:18)
    at Variables.renderMatches (/Users/romande/projects/prs/prs-medoca-pet-profile/api/node_modules/serverless/lib/classes/Variables.js:317:21)
    at BbPromise.all.then.results (/Users/romande/projects/prs/prs-medoca-pet-profile/api/node_modules/serverless/lib/classes/Variables.js:337:29)
From previous event:
    at Variables.populateValue (/Users/romande/projects/prs/prs-medoca-pet-profile/api/node_modules/serverless/lib/classes/Variables.js:337:8)
    at _.map.variable (/Users/romande/projects/prs/prs-medoca-pet-profile/api/node_modules/serverless/lib/classes/Variables.js:223:24)
    at arrayMap (/Users/romande/projects/prs/prs-medoca-pet-profile/api/node_modules/lodash/lodash.js:639:23)
    at Function.map (/Users/romande/projects/prs/prs-medoca-pet-profile/api/node_modules/lodash/lodash.js:9554:14)
    at Variables.populateVariables (/Users/romande/projects/prs/prs-medoca-pet-profile/api/node_modules/serverless/lib/classes/Variables.js:222:14)
    at Variables.populateObjectImpl (/Users/romande/projects/prs/prs-medoca-pet-profile/api/node_modules/serverless/lib/classes/Variables.js:251:30)
From previous event:
    at Variables.populateObjectImpl (/Users/romande/projects/prs/prs-medoca-pet-profile/api/node_modules/serverless/lib/classes/Variables.js:256:8)
    at prepopulateService.then (/Users/romande/projects/prs/prs-medoca-pet-profile/api/node_modules/serverless/lib/classes/Variables.js:135:26)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at initialCall (/Users/romande/projects/prs/prs-medoca-pet-profile/api/node_modules/serverless/lib/classes/Variables.js:135:10)
    at Variables.initialCall (/Users/romande/projects/prs/prs-medoca-pet-profile/api/node_modules/serverless/lib/classes/Variables.js:66:12)
    at Variables.populateService (/Users/romande/projects/prs/prs-medoca-pet-profile/api/node_modules/serverless/lib/classes/Variables.js:133:17)
    at Serverless.run (/Users/romande/projects/prs/prs-medoca-pet-profile/api/node_modules/serverless/lib/Serverless.js:111:27)
    at serverless.init.then (/Users/romande/projects/prs/prs-medoca-pet-profile/api/node_modules/serverless/bin/serverless:43:50)
    at <anonymous>

```

Similar or dependent issues:
* #5214

## Additional Data

* ***Serverless Framework Version you're using***: 1.30.0
* ***Operating System***: Mac OS High Sierra 10.13.5
* ***Node Version***: v8.9.1

**Comment by exoego** [comment]
I think this issue is cannot be addressed in servereless.
Please refer https://github.com/serverless/serverless/issues/5214#issuecomment-455748993

**Comment by exoego** [comment]
@DeX3 
Could you kindly provide a minimum reproducible example of serverless.yml?
If it is provied, it help us to identity some changes in serverless that broats huge string to cause error.

**Comment by DeX3** [comment]
I'm afraid I'm not able to reproduce it anymore :/

**Comment by eahefnawy** [comment]
Thanks @DeX3 ... Might be a hiccup. Will close the issue, and feel free to reopen if you face it again
