### ISSUE TITLE
Receiving error on serverless create commnad

### ISSUE THREAD

**Issue by sohamnavadiya** [serverless/serverless#5239]
```
root@moonmail:~# serverless create --template aws-nodejs --path my-service
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

ServerlessError: Command not found.  Enter "serverless help" to see all available commands.
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/Error.js:17:11)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:360:31)
    at /usr/local/lib/node_modules/serverless/bin/serverless:19:16
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)

```

**Comment by pmuens** [comment]
Hey @sohamnavadiya thanks for opening 👍

I'm closing this issue since we've fixed a couple of bugs in the past and there are newever versions of Serverless available which ship with those bugfixes. Please also ensure that you've correctly installed serverless by running `npm install --global serverless`.
