### ISSUE TITLE
"RangeError: Maximum call stack size exceeded" in the step: "Excluding development dependencies"

### ISSUE THREAD

**Issue by mechanical-turk** [serverless/serverless#5241]
# This is a (Bug Report / Feature Proposal)
Bug Report
## Description
Serverless framework, combined with yarn workspaces get stuck at `Excluding development dependencies` after attempting to deploy.
After taking about 10 minutes, this error is printed on the screen: `RangeError: Maximum call stack size exceeded`

For bug reports:
* What went wrong?
The deploy failed via `RangeError: Maximum call stack size exceeded`
* What did you expect should have happened?
The dev dependencies would be excluded normally and it would just deploy.
* What was the config you used?
```
frameworkVersion: '>=1.21.0 <2.0.0'
service: 'matterapp'

# Custom variables
# ===================================================================
custom:
  stage: ${opt:stage, 'dev'}
  environment: ${file(./serverless.env.yml):${self:custom.stage}}
  sns: ${self:custom.stage}-events-trigger
  sqs_events: ${self:custom.stage}-events.fifo
  sqs_communication: ${self:custom.stage}-communication

  # Plugin: serverless-offline
  serverless-offline:
    port: 3001

# The `provider` block defines where your service will be deployed
# ===================================================================
provider:
  name: aws
  runtime: nodejs8.10
  endpointType: REGIONAL
  stage: ${self:custom.stage}
  region: ${self:custom.environment.REGION, env:REGION}
  profile: ${self:custom.environment.PROFILE, env:PROFILE}
  environment:
    NODE_ENV: ${self:custom.environment.NODE_ENV, opt:NODE_ENV}
    IS_SEND_EMAILS: ${self:custom.environment.IS_SEND_EMAILS}
    IS_PREVIEW_EMAILS: ${self:custom.environment.IS_PREVIEW_EMAILS}
    DEBUG: sls:*
    GRAPHQL_URI: https://api.matterapp.com
    REGION: ${self:provider.region}
    SENTRY_DSN: https://e9b76bb9f70c49cc9ae55b4175b66426@sentry.io/1245112
    SQS_EVENTS_QUEUE_NAME: ${self:custom.sqs_events}
    SQS_COMMUNICATION_QUEUE_NAME: ${self:custom.sqs_communication}
  timeout: ${env:TIMEOUT, '300'}
  memorySize: ${env:MEMORY_SIZE, '256'}
  versionFunctions: true
  iamRoleStatements:
    - Effect: 'Allow'
      Action: 'secretsmanager:GetSecretValue'
      Resource:
        - 'arn:aws:secretsmanager:*:*:secret:test/google_api-*'
        - 'arn:aws:secretsmanager:*:*:secret:test/db-*'
        - 'arn:aws:secretsmanager:*:*:secret:prod/postmark_api-*'
        - 'arn:aws:secretsmanager:*:*:secret:prod/google_api-*'
        - 'arn:aws:secretsmanager:*:*:secret:prod/db-*'
        - 'arn:aws:secretsmanager:*:*:secret:prod/intercom-*'
        - 'arn:aws:secretsmanager:*:*:secret:prod/aws-*'
        - 'arn:aws:secretsmanager:*:*:secret:prod/cloudinary-*'
        - 'arn:aws:secretsmanager:*:*:secret:prod/fullcontact-*'
        - 'arn:aws:secretsmanager:*:*:secret:prod/sentry-*'
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
        - 'lambda:InvokeAsync'
      Resource: '*'
    - Effect: 'Allow'
      Action:
        - sqs:DeleteMessage
        - sqs:ReceiveMessage
      Resource: arn:aws:sqs:*:*:*

# The `Functions` you want to deploy
# ===================================================================
functions:
  sendEmail:
    handler: src/handlers/communication.sendEmail
    events:
      - http:
          path: api/communication/send-email
          method: post
          integration: lambda

  enrichEmailByEntityId:
    handler: src/handlers/emailEnrichments.enrichEmailByEntityId
    events:
      - http:
          path: api/email-enrichments/enrich-email-by-entity-id
          method: post
          integration: lambda

  enrichAllContactEmails:
    handler: src/handlers/emailEnrichments.enrichAllContactEmails
    events:
      - schedule: cron(0/5 * * * ? *)

  storeAllPhotosOnCDN:
    handler: src/handlers/emailEnrichments.storeAllPhotosOnCDN
    events:
      - schedule: cron(0/5 * * * ? *)

  importContacts:
    handler: src/handlers/contacts.importContacts
    events:
      - http:
          path: api/import-contacts
          method: post
          integration: lambda
          documentation:
            summary: "Import Google Contacts"
            description: "Import Google Contacts for a given connected_account_id"

  importGoogleCalendarAttendees:
    handler: src/handlers/contacts.importGoogleCalendarAttendees
    events:
      - schedule: cron(0/5 * * * ? *)

  computePeerRecommendations:
    handler: src/handlers/peerRecommendations.computePeerRecommendations
    events:
      - schedule: cron(0/8 * * * ? *)
      - http:
          path: api/compute-peer-recommendations
          method: post
          integration: lambda

  computeLeaderboards:
    handler: src/handlers/leaderboards.computeLeaderboards
    events:
      - schedule: cron(0 4 ? * MON *)

  feedbackReminders:
    handler: src/handlers/reminders.sendFeedbackReminders
    events:
      - schedule: cron(0 14 * * ? *)

  intercom:
    handler: src/handlers/intercom.sendEventToIntercom
    timeout: 300
    events:
      - schedule: cron(0/3 * * * ? *)
      - sns: ${self:custom.sns}

  report:
    handler: src/handlers/reports.handler
    events:
      - schedule: cron(0 15 * * ? *)
      - http:
          path: api/report
          method: get
          integration: lambda

# Plugins & Packages
# ===================================================================
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-include-dependencies

package:
  exclude:
    - .circleci/**
    - .git
    - coverage/**
    - node_modules/@types
    - node_modules/**/*.d.ts
    - node_modules/**/*.log
    - node_modules/**/*.html
    - node_modules/**/*.txt
    - node_modules/**/*.md
    - node_modules/**/LICENSE
    - node_modules/**/license
  include:
    - tslib
```
* What stacktrace or error message from your provider did you see?
```
RangeError: Maximum call stack size exceeded
    at module.exports (/Users/keremkazan/.config/yarn/global/node_modules/array-union/index.js:5:29)
    at /Users/keremkazan/.config/yarn/global/node_modules/globby/index.js:70:21
From previous event:
    at Package.resolveFilePathsAll (/Users/keremkazan/.config/yarn/global/node_modules/serverless/lib/plugins/package/lib/packageService.js:117:48)
    at Package.packageAll (/Users/keremkazan/.config/yarn/global/node_modules/serverless/lib/plugins/package/lib/packageService.js:71:17)
    at BbPromise.all.then (/Users/keremkazan/.config/yarn/global/node_modules/serverless/lib/plugins/package/lib/packageService.js:62:21)
From previous event:
    at Package.packageService (/Users/keremkazan/.config/yarn/global/node_modules/serverless/lib/plugins/package/lib/packageService.js:60:43)
From previous event:
    at Object.package:createDeploymentArtifacts [as hook] (/Users/keremkazan/.config/yarn/global/node_modules/serverless/lib/plugins/package/package.js:67:10)
    at BbPromise.reduce (/Users/keremkazan/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/Users/keremkazan/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.spawn (/Users/keremkazan/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:408:17)
    at Deploy.BbPromise.bind.then.then (/Users/keremkazan/.config/yarn/global/node_modules/serverless/lib/plugins/deploy/deploy.js:123:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/Users/keremkazan/.config/yarn/global/node_modules/serverless/lib/plugins/deploy/deploy.js:113:10)
    at BbPromise.reduce (/Users/keremkazan/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/Users/keremkazan/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.run (/Users/keremkazan/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:421:17)
    at variables.populateService.then.then (/Users/keremkazan/.config/yarn/global/node_modules/serverless/lib/Serverless.js:157:33)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (/Users/keremkazan/.config/yarn/global/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/Users/keremkazan/.config/yarn/global/node_modules/serverless/bin/serverless:43:50)
```
For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***:
1.30.1
* ***Operating System***:
Mac OS 10.12.6 
* ***Stack Trace***:

* ***Provider Error messages***:

**Comment by jorgenfroland** [comment]
@daviddelucca Thanks! That worked for me as well. I had installed the latest version 1.52. After installing 1.51 deploy worked well.

**Comment by atomkirk** [comment]
definitely introduced in `1.52` but probably a different error since this issue is so old. Here's my stack trace:

```
      at WriteStream (/Users/adamkirk/.dotfiles/config/config.symlink/yarn/global/node_modules/serverless/node_modules/jsonfile/node_modules/graceful-fs/graceful-fs.js:218:29)
      at WriteStream (/Users/adamkirk/.dotfiles/config/config.symlink/yarn/global/node_modules/serverless/node_modules/jsonfile/node_modules/graceful-fs/graceful-fs.js:218:29)
      at WriteStream (/Users/adamkirk/.dotfiles/config/config.symlink/yarn/global/node_modules/serverless/node_modules/jsonfile/node_modules/graceful-fs/graceful-fs.js:218:29)
      at WriteStream (/Users/adamkirk/.dotfiles/config/config.symlink/yarn/global/node_modules/serverless/node_modules/jsonfile/node_modules/graceful-fs/graceful-fs.js:218:29)
      at WriteStream (/Users/adamkirk/.dotfiles/config/config.symlink/yarn/global/node_modules/serverless/node_modules/jsonfile/node_modules/graceful-fs/graceful-fs.js:218:29)
      at WriteStream (/Users/adamkirk/.dotfiles/config/config.symlink/yarn/global/node_modules/serverless/node_modules/jsonfile/node_modules/graceful-fs/graceful-fs.js:218:29)
      at WriteStream (/Users/adamkirk/.dotfiles/config/config.symlink/yarn/global/node_modules/serverless/node_modules/jsonfile/node_modules/graceful-fs/graceful-fs.js:218:29)
      at WriteStream (/Users/adamkirk/.dotfiles/config/config.symlink/yarn/global/node_modules/serverless/node_modules/jsonfile/node_modules/graceful-fs/graceful-fs.js:218:29)
      at new WriteStream (/Users/adamkirk/.dotfiles/config/config.symlink/yarn/global/node_modules/serverless/node_modules/jsonfile/node_modules/graceful-fs/graceful-fs.js:218:29)
      at Object.createWriteStream (/Users/adamkirk/.dotfiles/config/config.symlink/yarn/global/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:306:12)
      at Package.zipFiles (/Users/adamkirk/.dotfiles/config/config.symlink/yarn/global/node_modules/serverless/lib/plugins/package/lib/zipService.js:80:23)
      at resolveFilePathsAll.then.filePaths (/Users/adamkirk/.dotfiles/config/config.symlink/yarn/global/node_modules/serverless/lib/plugins/package/lib/packageService.js:120:12)
      at tryCatcher (/Users/adamkirk/.dotfiles/config/config.symlink/yarn/global/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/adamkirk/.dotfiles/config/config.symlink/yarn/global/node_modules/bluebird/js/release/promise.js:517:31)
      at Promise._settlePromise (/Users/adamkirk/.dotfiles/config/config.symlink/yarn/global/node_modules/bluebird/js/release/promise.js:574:18)
      at Promise._settlePromise0 (/Users/adamkirk/.dotfiles/config/config.symlink/yarn/global/node_modules/bluebird/js/release/promise.js:619:10)
      at Promise._settlePromises (/Users/adamkirk/.dotfiles/config/config.symlink/yarn/global/node_modules/bluebird/js/release/promise.js:699:18)
      at _drainQueueStep (/Users/adamkirk/.dotfiles/config/config.symlink/yarn/global/node_modules/bluebird/js/release/async.js:138:12)
      at _drainQueue (/Users/adamkirk/.dotfiles/config/config.symlink/yarn/global/node_modules/bluebird/js/release/async.js:131:9)
      at Async._drainQueues (/Users/adamkirk/.dotfiles/config/config.symlink/yarn/global/node_modules/bluebird/js/release/async.js:147:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/Users/adamkirk/.dotfiles/config/config.symlink/yarn/global/node_modules/bluebird/js/release/async.js:17:14)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
```

**Comment by schellack** [comment]
I'm seeing this too. Downgrading from 1.52 to 1.51 fixed the issue. Can't even see the error because the stack trace is too long. Here's a snippet:

>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at new ReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:195:28)
>       at Object.createReadStream (/Users/username/work/report-service/node_modules/graceful-fs/graceful-fs.js:237:12)
>       at copyFile (/Users/username/work/report-service/node_modules/fs-extra/lib/copy/ncp.js:98:25)
>       at /Users/username/work/report-service/node_modules/fs-extra/lib/copy/ncp.js:82:9
>       at /Users/username/work/report-service/node_modules/fs-extra/lib/copy/ncp.js:208:43
>       at /Users/username/work/report-service/node_modules/graceful-fs/polyfills.js:282:31
>       at callback (/usr/local/lib/node_modules/serverless/node_modules/graceful-fs/polyfills.js:295:20)
>       at FSReqWrap.oncomplete (fs.js:153:21)
