### ISSUE TITLE
Deploying new serverless project from template openwhisk-java-maven fails

### ISSUE THREAD

**Issue by j-mastr** [serverless/serverless#5261]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
I created a new serverless project using the openwhisk-java-maven template. Trying to deploy it resulted in the Serverless Error "Function handler (com.example.FunctionApp) does not exist."

* What did you expect should have happened?
That the functions are deployed.

* What was the config you used?
The OpenWhisk CLI is configured properly, `sls info` returns all correct information, the serverless.yml is expanded by `ignore_certs: true` in the provider section, everything else is exactly like in the template.

* What stacktrace or error message from your provider did you see?
Following returns the deploy command with debugging enabled:
```
$ SLS_DEBUG=* sls deploy
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Packaging service...
Serverless: Compiling Functions...

  Serverless Error ---------------------------------------

  Function handler (com.example.FunctionApp) does not exist.

  Stack Trace --------------------------------------------

ServerlessError: Function handler (com.example.FunctionApp) does not exist.
    at Java.generateActionPackage (C:\Users\D067709\Documents\Projects\test-service\node_modules\serverless-openwhisk\compile\functions\runtimes\base.js:77:13)
    at Java.exec (C:\Users\D067709\Documents\Projects\test-service\node_modules\serverless-openwhisk\compile\functions\runtimes\base.js:27:17)
    at Runtimes.exec (C:\Users\D067709\Documents\Projects\test-service\node_modules\serverless-openwhisk\compile\functions\runtimes\index.js:29:49)
    at OpenWhiskCompileFunctions.compileFunction (C:\Users\D067709\Documents\Projects\test-service\node_modules\serverless-openwhisk\compile\functions\index.js:96:26)
    at functionPromises.serverless.service.getAllFunctions.map (C:\Users\D067709\Documents\Projects\test-service\node_modules\serverless-openwhisk\compile\functions\index.js:152:28)
    at Array.map (<anonymous>)
    at OpenWhiskCompileFunctions.compileFunctions (C:\Users\D067709\Documents\Projects\test-service\node_modules\serverless-openwhisk\compile\functions\index.js:133:72)
    at BbPromise.reduce (C:\Users\D067709\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (C:\Users\D067709\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:390:22)
    at PluginManager.spawn (C:\Users\D067709\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:408:17)
    at Deploy.BbPromise.bind.then.then (C:\Users\D067709\AppData\Roaming\npm\node_modules\serverless\lib\plugins\deploy\deploy.js:123:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (C:\Users\D067709\AppData\Roaming\npm\node_modules\serverless\lib\plugins\deploy\deploy.js:113:10)
    at BbPromise.reduce (C:\Users\D067709\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (C:\Users\D067709\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:390:22)
    at PluginManager.run (C:\Users\D067709\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:421:17)
    at variables.populateService.then.then (C:\Users\D067709\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:157:33)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Serverless.run (C:\Users\D067709\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:144:8)
    at serverless.init.then (C:\Users\D067709\AppData\Roaming\npm\node_modules\serverless\bin\serverless:43:50)
    at <anonymous>

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           8.9.4
     Serverless Version:     1.30.1
```

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* --

## Additional Data
I would suggest to adopt this template to the hints given in the [serverless-openwhisk README](https://github.com/serverless/serverless-openwhisk#writing-functions---java).

* ***Serverless Framework Version you're using***: 1.30.1
* ***Operating System***: win32
* ***Stack Trace***:
```
ServerlessError: Function handler (com.example.FunctionApp) does not exist.
    at Java.generateActionPackage (C:\Users\D067709\Documents\Projects\test-service\node_modules\serverless-openwhisk\compile\functions\runtimes\base.js:77:13)
    at Java.exec (C:\Users\D067709\Documents\Projects\test-service\node_modules\serverless-openwhisk\compile\functions\runtimes\base.js:27:17)
    at Runtimes.exec (C:\Users\D067709\Documents\Projects\test-service\node_modules\serverless-openwhisk\compile\functions\runtimes\index.js:29:49)
    at OpenWhiskCompileFunctions.compileFunction (C:\Users\D067709\Documents\Projects\test-service\node_modules\serverless-openwhisk\compile\functions\index.js:96:26)
    at functionPromises.serverless.service.getAllFunctions.map (C:\Users\D067709\Documents\Projects\test-service\node_modules\serverless-openwhisk\compile\functions\index.js:152:28)
    at Array.map (<anonymous>)
    at OpenWhiskCompileFunctions.compileFunctions (C:\Users\D067709\Documents\Projects\test-service\node_modules\serverless-openwhisk\compile\functions\index.js:133:72)
    at BbPromise.reduce (C:\Users\D067709\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (C:\Users\D067709\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:390:22)
    at PluginManager.spawn (C:\Users\D067709\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:408:17)
    at Deploy.BbPromise.bind.then.then (C:\Users\D067709\AppData\Roaming\npm\node_modules\serverless\lib\plugins\deploy\deploy.js:123:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (C:\Users\D067709\AppData\Roaming\npm\node_modules\serverless\lib\plugins\deploy\deploy.js:113:10)
    at BbPromise.reduce (C:\Users\D067709\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (C:\Users\D067709\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:390:22)
    at PluginManager.run (C:\Users\D067709\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:421:17)
    at variables.populateService.then.then (C:\Users\D067709\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:157:33)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Serverless.run (C:\Users\D067709\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:144:8)
    at serverless.init.then (C:\Users\D067709\AppData\Roaming\npm\node_modules\serverless\bin\serverless:43:50)
    at <anonymous>
```
* ***Provider Error messages***: --

**Comment by medikoo** [comment]
Those templates were updated numerous times since this issue was opened, so I assume that problem was solved and closing it.
If you feel it's not the case, please comment
