### ISSUE TITLE
npm install: Error [ERR_STREAM_WRITE_AFTER_END]: write after end

### ISSUE THREAD

**Issue by dlidstrom** [serverless/serverless#5277]
# This is a Bug Report

## Description

There was an error when running `sls i -g serverless`

## Additional Data

I'm using MacOS 10.13.6.
Node: v10.0.0.0
npm: 6.0.1

This is what happened:

```
daniel@Daniels-MacBook-Pro
(master)[~/programming/Words]: sls --version
1.27.3


   ╭───────────────────────────────────────╮
   │                                       │
   │   Update available 1.27.3 → 1.28.0    │
   │   Run npm i -g serverless to update   │
   │                                       │
   ╰───────────────────────────────────────╯

daniel@Daniels-MacBook-Pro
(master)[~/programming/Words]: npm i -g serverless
events.js:167░░░░░░⸩ ⠧ extract:content-type: sill extract vary@1.1.2
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:243:12)
    at PassThrough.Writable.write (_stream_writable.js:292:5)
    at PassThrough.Writable.end (_stream_writable.js:592:10)
    at ReadEntry.entry.on (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at ReadEntry.emit (events.js:187:15)
    at ReadEntry.emit (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at Unzip.emit (events.js:182:13)
    at Unzip.emit (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at Unzip.write (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:99:17)
    at Unzip.write (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
Emitted 'error' event at:
    at writeAfterEnd (_stream_writable.js:245:10)
    at PassThrough.Writable.write (_stream_writable.js:292:5)
    [... lines matching original stack trace ...]
    at Unzip.write (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
events.js:167░░░░░░⸩ ⠼ extract:@serverless/platform-sdk: sill extract on-finished@2.3.0
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:243:12)
    at PassThrough.Writable.write (_stream_writable.js:292:5)
    at PassThrough.Writable.end (_stream_writable.js:592:10)
    at ReadEntry.entry.on (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at ReadEntry.emit (events.js:187:15)
    at ReadEntry.emit (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at Unzip.emit (events.js:182:13)
    at Unzip.emit (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at Unzip.write (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:99:17)
    at Unzip.write (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
Emitted 'error' event at:
    at writeAfterEnd (_stream_writable.js:245:10)
    at PassThrough.Writable.write (_stream_writable.js:292:5)
    [... lines matching original stack trace ...]
    at Unzip.write (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
events.js:167░░░░░░⸩ ⠼ extract:express: sill extract on-finished@2.3.0
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:243:12)
    at PassThrough.Writable.write (_stream_writable.js:292:5)
    at PassThrough.Writable.end (_stream_writable.js:592:10)
    at ReadEntry.entry.on (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at ReadEntry.emit (events.js:187:15)
    at ReadEntry.emit (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at Unzip.emit (events.js:182:13)
    at Unzip.emit (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at Unzip.write (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:99:17)
    at Unzip.write (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
Emitted 'error' event at:
    at writeAfterEnd (_stream_writable.js:245:10)
    at PassThrough.Writable.write (_stream_writable.js:292:5)
    [... lines matching original stack trace ...]
    at Unzip.write (/Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
/Users/daniel/.nvm/versions/node/v10.0.0/bin/serverless -> /Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/serverless/bin/serverless
/Users/daniel/.nvm/versions/node/v10.0.0/bin/slss -> /Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/serverless/bin/serverless
/Users/daniel/.nvm/versions/node/v10.0.0/bin/sls -> /Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/serverless/bin/serverless

> serverless@1.30.3 postinstall /Users/daniel/.nvm/versions/node/v10.0.0/lib/node_modules/serverless
> node ./scripts/postinstall.js

+ serverless@1.30.3
added 60 packages from 87 contributors, removed 19 packages and updated 29 packages in 15.999s
daniel@Daniels-MacBook-Pro
(master)[~/programming/Words]: sls --version
1.30.3
daniel@Daniels-MacBook-Pro
(master)[~/programming/Words]:
```

At this point I'm not sure sls works as expected. Is there any action I should take to ensure it works?
It was also surprising that the upgrade wasn't `1.27.3 → 1.28.0` as it said initially, but actually `1.27.3 → 1.30.3`.
Thanks!

**Comment by pmuens** [comment]
Closing since this seems to be related to `npm`. Please open up an issue in the `npm` repository.
