### ISSUE TITLE
Windows 10 Serverless errors when requirements.txt used

### ISSUE THREAD

**Issue by jonleonATX** [serverless/serverless#5319]
# This is a Bug Report

## Description
  serverless works great when a requirements.txt document isn't required.
  I've deployed simple functions to verify it works on my machine.

* What went wrong?

  If I can get past the first error, the second pops up. I sometimes have to manually remove the .serverless directory to get moving again.

  FIRST: 
EPERM: operation not permitted, mkdir 'C:\Users\Home-PC\code\marketanalysis\lambda_breakout\breakouts\.serverless'

  and

  SECOND: 
Could not open requirements file: [Errno 22] Invalid argument: 'C\\:\\\\Users\\\\Home-PC\\\\code\\\\marketanalysis\\\\lambda_breakout\\\\breakouts\\\\.serverless\\\\requirements\\\\requirements.txt'

  I get the same errors whether I run as an administrator or not.

* What did you expect should have happened?

  Expected it should be able to make the directories and open the files like it does when requirements.txt isn't required

* What was the config you used?

  Using Powershell as administrator (I'm the only on my Win 10 Surface Pro) I used the following:
  insalled with:
  choco install nodejs -y
  npm install -g serverless

  requirements.txt has three modules: pandas, ta, and requests

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           10.10.0
     Serverless Version:     1.32.0
     npm version 6.4.1

* What stacktrace or error message from your provider did you see?

FIRST ERROR - use this to ge the full trace: cmd /c "set `"SLS_DEBUG=*`" & serverless deploy -v"

Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command requirements
Serverless: Load command requirements:clean
Serverless: Load command requirements:install
Serverless: Load command requirements:cleanCache
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir

Error --------------------------------------------------

  EPERM: operation not permitted, mkdir 'C:\Users\Home-PC\code\marketanalysis\lambda_breakout\breakouts\.serverless'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: EPERM: operation not permitted, mkdir 'C:\Users\Home-PC\code\marketanalysis\lambda_breakout\breakouts\.serverless'
    at Object.mkdirSync (fs.js:731:3)
    at Object.mkdirsSync (C:\Users\Home-PC\AppData\Roaming\npm\node_modules\serverless\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:22:9)
    at writeFileSync (C:\Users\Home-PC\AppData\Roaming\npm\node_modules\serverless\lib\utils\fs\writeFileSync.js:11:7)
    at Utils.writeFileSync (C:\Users\Home-PC\AppData\Roaming\npm\node_modules\serverless\lib\classes\Utils.js:43:12)
    at AwsPackage.generateCoreTemplate (C:\Users\Home-PC\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\package\lib\generateCoreTemplate.js:84:27)
From previous event:
    at Object.package:initialize [as hook] (C:\Users\Home-PC\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\package\index.js:60:10)
    at BbPromise.reduce (C:\Users\Home-PC\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (C:\Users\Home-PC\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:390:22)
    at PluginManager.spawn (C:\Users\Home-PC\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:408:17)
    at Deploy.BbPromise.bind.then.then (C:\Users\Home-PC\AppData\Roaming\npm\node_modules\serverless\lib\plugins\deploy\deploy.js:123:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (C:\Users\Home-PC\AppData\Roaming\npm\node_modules\serverless\lib\plugins\deploy\deploy.js:113:10)
    at BbPromise.reduce (C:\Users\Home-PC\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (C:\Users\Home-PC\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:390:22)
    at PluginManager.run (C:\Users\Home-PC\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:421:17)
    at variables.populateService.then.then (C:\Users\Home-PC\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:157:33)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (C:\Users\Home-PC\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:144:8)
    at serverless.init.then (C:\Users\Home-PC\AppData\Roaming\npm\node_modules\serverless\bin\serverless:43:50)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           10.10.0
     Serverless Version:     1.32.0

SECOND ERROR - use this to ge the full trace: cmd /c "set `"SLS_DEBUG=*`" & serverless deploy -v"

Serverless: Generated requirements from C:\Users\Home-PC\code\marketanalysis\lambda_breakout\breakouts\requirements.txt in C:\Users\Home-PC\code\marketanalysis\lambda_breakout\breakouts\.serverless\requirements.txt...
Serverless: Installing requirements from C:\Users\Home-PC\code\marketanalysis\lambda_breakout\breakouts\.serverless\requirements\requirements.txt ...

 Error --------------------------------------------------

 Could not open requirements file: [Errno 22] Invalid argument: 'C\\:\\\\Users\\\\Home-PC\\\\code\\\\marketanalysis\\\\lambda_breakout\\\\breakouts\\\\.serverless\\\\requirements\\\\requirements.txt'

    For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

 Get Support --------------------------------------------
    Docs:          docs.serverless.com
    Bugs:          github.com/serverless/serverless/issues
    Issues:        forum.serverless.com

 Your Environment Information -----------------------------
    OS:                     win32
    Node Version:           10.10.0
    Serverless Version:     1.32.0

**Comment by ariel-frischer** [comment]
I'm running into the same issue with nodejs 12.19.0

**Comment by pgrzesik** [comment]
Hello @ariel-frischer, are you experiencing the same issue while using https://github.com/UnitedIncome/serverless-python-requirements/ ? I believe the best bet would be to report an Issue in the repository of that plugin, as it seems to be tied directly to the plugin vs the Framework itself.

**Comment by ariel-frischer** [comment]
@pgrzesik Sorry I did not specify I'm actually not using python, I was trying to run a serverless express application inside a lambda function using docker image. This `mkdir` error is the similarity, I have a hunch this is due to aws using a readonly file system.

**Comment by pgrzesik** [comment]
No worries @ariel-frischer :+1: In that case I believe it's a totally separate issue - if you'd like you could report it with details so we can take a closer look at it :100:

**Comment by medikoo** [comment]
I'm closing this issue as it feels specific to `serverless-python-requirements` plugin, and such issues should be reported at its repositoru
