### ISSUE TITLE
ServerlessError: Forbidden

### ISSUE THREAD

**Issue by wutianchen** [serverless/serverless#5338]
I get this error when trying to run

`sls deploy`

which gives me little information what's going wrong
```
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy

  Serverless Error ---------------------------------------

  ServerlessError: Forbidden

  Stack Trace --------------------------------------------

ServerlessError: ServerlessError: Forbidden
    at AwsDeploy.BbPromise.bind.then.catch (/home/ec2-user/.nvm/versions/node/v8.12.0/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:90:15)
From previous event:
    at AwsDeploy.createStack (/home/ec2-user/.nvm/versions/node/v8.12.0/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:81:13)
From previous event:
    at Object.aws:deploy:deploy:createStack [as hook] (/home/ec2-user/.nvm/versions/node/v8.12.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:102:10)
    at BbPromise.reduce (/home/ec2-user/.nvm/versions/node/v8.12.0/lib/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/home/ec2-user/.nvm/versions/node/v8.12.0/lib/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.spawn (/home/ec2-user/.nvm/versions/node/v8.12.0/lib/node_modules/serverless/lib/classes/PluginManager.js:408:17)
    at AwsDeploy.BbPromise.bind.then (/home/ec2-user/.nvm/versions/node/v8.12.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:95:48)
From previous event:
    at Object.deploy:deploy [as hook] (/home/ec2-user/.nvm/versions/node/v8.12.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:91:10)
    at BbPromise.reduce (/home/ec2-user/.nvm/versions/node/v8.12.0/lib/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/home/ec2-user/.nvm/versions/node/v8.12.0/lib/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.run (/home/ec2-user/.nvm/versions/node/v8.12.0/lib/node_modules/serverless/lib/classes/PluginManager.js:421:17)
    at variables.populateService.then.then (/home/ec2-user/.nvm/versions/node/v8.12.0/lib/node_modules/serverless/lib/Serverless.js:157:33)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Serverless.run (/home/ec2-user/.nvm/versions/node/v8.12.0/lib/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/home/ec2-user/.nvm/versions/node/v8.12.0/lib/node_modules/serverless/bin/serverless:43:50)
    at <anonymous>

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.12.0
     Serverless Version:     1.32.0

```

**Comment by pmuens** [comment]
Hey @wutianchen thanks for opening 👍

Could you provide more information about the application your're working on (e.g. share the `serverless.yml` file)? Thanks!

**Comment by pmuens** [comment]
Thanks again for opening @wutianchen 👍

Seems like this issue is stale, so I'll close this for now. Feel free to re-open once you have more information on how to reproduce it.
