### ISSUE TITLE
Changing Order of API Keys between Deployments Fails

### ISSUE THREAD

**Issue by BrandonE** [serverless/serverless#5339]
# This is a Bug Report

## Description

For bug reports:
* What went wrong? I am creating a series of API keys for my Serverless project. The last time I deployed, I added a key (which I will refer to as `API_KEY_1`), which successfully deployed. Then, I added a key (which I will refer to as `API_KEY_2`), which I placed in the list prior to `API_KEY_1` to make it so that the actual key names are in alphabetical order. This resulted in the error below. After flipping the API keys such that `API_KEY_1` was listed prior to `API_KEY_2`, the deployment succeeded.
* What did you expect should have happened? The creation of the API keys should be idempotent based on key name regardless of the list order.
* What was the config you used?

```
provider:
    name: aws
    runtime: nodejs8.10
    ...
    apiKeys:
        - API_KEY_2
        - API_KEY_1
```

* What stacktrace or error message from your provider did you see? `ApiGatewayApiKey2 - API_KEY_1_NAME already exists in stack arn:aws:cloudformation:us-east-1:ACCOUNT_NUMBER:stack/STACK_NAME/UUID.`

## Additional Data

* ***Serverless Framework Version you're using***: 1.32.0
* ***Operating System***: Docker for Mac: `FROM lambci/lambda:build-nodejs8.10`
* ***Stack Trace***:

```
ServerlessError: An error occurred: ApiGatewayApiKey2 - API_KEY_1_NAME already exists in stack arn:aws:cloudformation:us-east-1:ACCOUNT_NUMBER:stack/STACK_NAME/UUID.
    at provider.request.then (/expert-api/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:112:33)
From previous event:
    at AwsDeploy.monitorStack (/expert-api/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:26:12)
    at provider.request.then (/expert-api/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:95:30)
From previous event:
    at AwsDeploy.update (/expert-api/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:95:8)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/expert-api/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:112:12)
From previous event:
    at AwsDeploy.updateStack (/expert-api/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:106:8)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/expert-api/node_modules/serverless/lib/plugins/aws/deploy/index.js:129:39)
From previous event:
    at Object.aws:deploy:deploy:updateStack [as hook] (/expert-api/node_modules/serverless/lib/plugins/aws/deploy/index.js:125:10)
    at BbPromise.reduce (/expert-api/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/expert-api/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.spawn (/expert-api/node_modules/serverless/lib/classes/PluginManager.js:408:17)
    at AwsDeploy.BbPromise.bind.then (/expert-api/node_modules/serverless/lib/plugins/aws/deploy/index.js:95:48)
From previous event:
    at Object.deploy:deploy [as hook] (/expert-api/node_modules/serverless/lib/plugins/aws/deploy/index.js:91:10)
    at BbPromise.reduce (/expert-api/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/expert-api/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.run (/expert-api/node_modules/serverless/lib/classes/PluginManager.js:421:17)
    at variables.populateService.then.then (/expert-api/node_modules/serverless/lib/Serverless.js:157:33)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Serverless.run (/expert-api/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/expert-api/node_modules/serverless/bin/serverless:43:50)
    at <anonymous>
```

* ***Provider Error messages***: `ApiGatewayApiKey2 - API_KEY_1_NAME already exists in stack arn:aws:cloudformation:us-east-1:ACCOUNT_NUMBER:stack/STACK_NAME/UUID.`

**Comment by mike-suggitt** [comment]
+1 For this. The logical IDs created by serverless are based on the order and usage plan of a key and so if moving a key the CF stack sees a conflict. My use case is:

2 usage plans - one "open", the other "restricted". The logical IDs of keys placed in open are e.g. `ApiGatewayUsagePlanOpen1` and `ApiGatewayUsagePlanOpen2` etc but with names and values of their own. If i change the order as above, or move those keys into the "restricted" usage plan. Then CF has a tantrum as it can't link the resources. 

The only workaround i've found to date is to delete, deploy, then re-add

**Comment by jlgouwyapizr** [comment]
2 years after ... same shit. Nobody cares ?

**Comment by medikoo** [comment]
I've added implementation fix proposal in issue description. PR's welcome!

**Comment by toboid** [comment]
Hi @medikoo thanks for the proposal, I've been looking into this issue and would be pleased to work on a fix.

From my experiments this is a breaking change as changing the logical key (which would happen if make the logic deterministic) will cause issues with API keys that already exist in AWS (changing the logical id causes CF to try to re-create the key, which fails because a key with that physical name already exists). In a sense this is similar to the existing issue that occurs when the order is changed, as this is also changes the logical id. 

How would you feel about going with the proposed change to make logical names deterministic, but providing an option to override the logical name. It would still be a breaking change, but the override would provide an escape hatch for those with existing keys deployed. I think `logicalId` property would only be applicable in deterministic mode.

Example:

```yaml
provider:
  name: aws
  apiGateway:
    apiKeyResourceNamingMethod: deterministic
    apiKeys:
      - name: myThirdKey
        logicalId: ApiGatewayApiKey2 # ApiGatewayApiKey1 has been removed, so this key's position has been changed but we can override
    usagePlan:
      throttle:
        burstLimit: 1
        rateLimit: 5
```

**Comment by medikoo** [comment]
> How would you feel about going with the proposed change to make logical names deterministic, but providing an option to override the logical name. 

That sounds good. but I think providing a logical name should not be mandatory to ensure deterministic ordering.
In this case to avoid breaking change we can introduce it behind a flag as proposed in main description. WDYT?

**Comment by toboid** [comment]
yes totally agree it shouldn't be mandatory. I was thinking of it as an optional property. The reason for suggesting is that for those of us that already have AWS api keys created using sls, without it we still won't have a way to remove API keys from our serverless.yaml without affecting keys that occur after it. 

For example, if today I have the following in my serverless.yaml

```yaml
provider:
  name: aws
  apiGateway:
    apiKeys:
      - name: first-key
      - name: second-key
    usagePlan:
      throttle:
        burstLimit: 1
        rateLimit: 5

```
and I want to remove `first-key`. Today this isn't possible because it changes the logical id of `second-key` and will fail when deploying.

If we introduce deterministic logical ids (behind the `provider.apiGateway.apiKeyResourceNamingMethod` flag as proposed), I still won't have a way forward - if switch to deterministic mode, the logical id for my key `second-key` will be changed and I won't be able to deploy. 

I'm not attached to the idea of allowing the logical id to be overridden. But for my own case (and I assume others that have encountered this issue), it would be useful to have a path forward that doesn't involve having to delete existing API keys and re-create them. 
Does that make sense? If you have any other suggestions of how to achieve this i'd be happy to investigate

**Comment by toboid** [comment]
That sounds good, thanks for coming back quickly @medikoo. I can work on that and make a PR

**Comment by medikoo** [comment]
@toboid That'll be great. Thank you!

**Comment by iwb-cedricdenis** [comment]
Hello is there an update on this ? Even with latest serverless 4 version it is still impossible to do a trivial task consisting in removing an api key :x 
@czubocha maybe ?

**Comment by toboid** [comment]
Hey, i'm no longer working in this area and as such not facing this issue. If you could un-assign me that would be appreciated. If someone else who is currently facing this problem wants to pick it up, I do think the above discussed solution could be option to unblock you whilst maintaining backwards compatibility for other users
