### ISSUE TITLE
Module Initialisation Error

### ISSUE THREAD

**Issue by MrShakes** [serverless/serverless#5346]
# This is a Bug Report

## Description

I have already looked at issue #3176 that has been closed for suggestions however it doesn't provide a solution, I'm trying to use `pdfmake` to create a pdf, code works perfectly locally and code works fine in Lambda before adding the library at which point I get module initialisation error, I can't see where(what line) exactly in the module failed.
I'm thinking it may have to do with accessing `/tmp` folder however I can't say for sure due to the lack of detailed logs.

Code:

```
import * as PdfPrinter from 'pdfmake/src/printer';

const fonts = {
     Roboto: {
      	normal: '/tmp/Roboto-Regular.ttf',
      	bold: '/tmp/Roboto-Medium.ttf',
      	italics: '/tmp/Roboto-Italic.ttf',
      	bolditalics: '/tmp/Roboto-MediumItalic.ttf'
      }
 };
      
  let printer = new PdfPrinter(fonts);

  var dd = {
    content: [
		'First paragraph',
		'Another paragraph, this time a little bit longer to make sure, this line will be divided into at 
      least two lines'
    ]	
  }

  let pdfDoc = printer.createPdfKitDocument(dd);
  let chunks = [];
  let result;

  pdfDoc.on('readable', function () {
      let chunk;
      	 while ((chunk = pdfDoc.read(9007199254740991)) !== null) {
      	    chunks.push(chunk);
          }
   });

  pdfDoc.on('end', function () {
      result = Buffer.concat(chunks);
      console.log(result); 		
  });
       
  pdfDoc.end();
```

For bug reports:
* What went wrong?
Module initialisation error
* What did you expect should have happened?
Module should have initialised successfully
* What was the config you used?
* What stacktrace or error message from your provider did you see?
`module initialization error: Error`

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #3176

## Additional Data

* ***Serverless Framework Version you're using***:
1.32.0
* ***Operating System***:
Lambda Node 8.10
* ***Stack Trace***:
`module initialization error: Error`
* ***Provider Error messages***:
`module initialization error: Error`

**Comment by MrShakes** [comment]
**Update**

Invoking locally gives the error below, when I run `ls node_modules/unicode-properties/data.trie` I can get the file, seems to be an error from where serverless is calling from

```
Serverless: INVOKING INVOKE
{
    "errno": -2,
    "code": "ENOENT",
    "syscall": "open",
    "path": "node_modules/unicode-properties/data.trie"
}
 
  Error --------------------------------------------------
 
  Exception encountered when loading /Users/ola/Desktop/Awork/gl-pdf/.webpack/service/index
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: Exception encountered when loading /Users/ola/Desktop/Awork/gl-pdf/.webpack/service/index
    at AwsInvokeLocal.invokeLocalNodeJs (/Users/ola/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:272:13)
    at AwsInvokeLocal.invokeLocal (/Users/ola/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:125:19)
From previous event:
    at Object.invoke:local:invoke [as hook] (/Users/ola/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:26:10)
    at BbPromise.reduce (/Users/ola/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/Users/ola/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.run (/Users/ola/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:421:17)
    at variables.populateService.then.then (/Users/ola/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/lib/Serverless.js:157:33)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Serverless.run (/Users/ola/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/Users/ola/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/bin/serverless:43:50)
    at <anonymous>

```

**Comment by Susan123456789** [comment]
Did you find a solution for this problem?  I am facing something similar.  Thanks.

**Comment by tobiastornros** [comment]
Trying to run pdfmake with serverless-offline but also stuck on the unicode-properties error.



`Error: ENOENT: no such file or directory, open '/Users/x/api/.webpack/service/get/pdf/data.trie'
    at Object.openSync (fs.js:457:3)
    at Object.fs.openSync (pkg/prelude/bootstrap.js:487:32)
    at Object.readFileSync (fs.js:359:35)
    at Object.fs.readFileSync (pkg/prelude/bootstrap.js:683:36)
    at Module.../../unicode-properties/unicode-properties.es.js (/Users/x/api/.webpack/service/get/pdf/webpack:/Users/x/api/node_modules/unicode-properties/unicode-properties.es.js:137:30)`
