### ISSUE TITLE
deploy succeeded but fail to getting API info

### ISSUE THREAD

**Issue by tainguyen206** [serverless/serverless#5367]
# This is a Bug Report

## Description
* What went wrong?
We use an assume role to deploy lambda and api gateway (specified under cfnRole). 
When running sls deploy, everything seems to work until the "Invoke aws:info" step. It shows:

`User: arn:aws:iam::123456789:user/my_acount is not authorized to perform: apigateway:GET on resource: arn:aws:apigateway:us-east-2::/apikeys`

I assume that is where serverless try to get information about the deployed service, along with its endpoints and API keys. But it looks like instead of using the specified role, it uses my user to get API keys.

* What did you expect should have happened?
service is deployed and API endpoints and keys returned without error.

* What stacktrace or error message from your provider did you see?

```
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (961 B)...
Serverless: Uploading service .zip file to S3 (47.19 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.........................................................................................................................
Serverless: Stack update finished...
Serverless: Invoke aws:info

  Serverless Error ---------------------------------------

  User: arn:aws:iam::1234567890:user/my_user_account is not authorized to perform: apigateway:GET on resource: arn:aws:apigateway:us-east-2::/apikeys

  Stack Trace --------------------------------------------

ServerlessError: User: arn:aws:iam::1234567890:user/my_user_account is not authorized to perform: apigateway:GET on resource: arn:aws:apigateway:us-east-2::/apikeys
    at BbPromise.fromCallback.catch.err (C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\provider\awsProvider.js:270:11)
From previous event:
    at persistentRequest (C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\provider\awsProvider.js:253:13)
    at doCall (C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\provider\awsProvider.js:205:9)
    at BbPromise (C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\provider\awsProvider.js:222:14)
From previous event:
    at persistentRequest (C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\provider\awsProvider.js:203:38)
    at Object.request.requestQueue.add [as promiseGenerator] (C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\provider\awsProvider.js:243:49)
    at Queue._dequeue (C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\node_modules\promise-queue\lib\index.js:153:30)
    at C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\node_modules\promise-queue\lib\index.js:109:18
From previous event:
    at Queue.add (C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\node_modules\promise-queue\lib\index.js:94:16)
    at AwsProvider.request (C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\provider\awsProvider.js:243:39)
    at AwsInfo.getApiKeyValues (C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\info\getApiKeyValues.js:15:28)
From previous event:
    at Object.aws:info:gatherData [as hook] (C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\info\index.js:57:10)
    at BbPromise.reduce (C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:390:22)
    at PluginManager.spawn (C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:408:17)
    at AwsInfo.BbPromise.bind.then (C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\info\index.js:49:48)
From previous event:
    at Object.deploy:deploy [as hook] (C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\info\index.js:45:10)
    at BbPromise.reduce (C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:390:22)
    at PluginManager.run (C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:421:17)
    at variables.populateService.then.then (C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:157:33)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Serverless.run (C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:144:8)
    at serverless.init.then (C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\bin\serverless:43:50)
    at <anonymous>

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           8.12.0
     Serverless Version:     1.32.0
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.32.0
* ***Operating System***: Windows 10
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by lucasnp** [comment]
I got help from a colleague and finally got it to work by adding the following permission to my deployment policy stack:

```
- Sid: ApiGwEvents
  Effect: Allow
  Action:
    - apigateway:GET
  Resource:
    - !Sub 'arn:${AWS::Partition}:apigateway:${AWS::Region}::/apikeys'
```

**Comment by pmuens** [comment]
Thanks for opening and following up @tainguyen206 👍

Closing this since it seems like you were able to fix this. Feel free to re-open if this problem pops up again.
