### ISSUE TITLE
`npm i -g serverless` fails on node 10

### ISSUE THREAD

**Issue by erikerikson** [serverless/serverless#5371]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

The `npm i -g serverless` command fails repeatedly in travisci with node 10.

See stack below or [the build failure](https://travis-ci.org/Nordstrom/serverless-artillery/jobs/430775581#L467).

You can see that it [succeeds with other versions of node](https://travis-ci.org/Nordstrom/serverless-artillery/builds/430775577?utm_source=github_status&utm_medium=notification).

* What did you expect should have happened?

Successful installation

* What was the config you used?

N/A

* What stacktrace or error message from your provider did you see?

Rel
```
error /home/travis/build/Nordstrom/serverless-artillery/node_modules/serverless: Command failed.
Exit code: 1
Command: node ./scripts/postinstall.js
Arguments: 
Directory: /home/travis/build/Nordstrom/serverless-artillery/node_modules/serverless
Output:
[tabtab] Adding source line to load /home/travis/build/Nordstrom/serverless-artillery/node_modules/tabtab/.completions/serverless.bash
in /home/travis/.bashrc
[tabtab] Adding source line to load /home/travis/build/Nordstrom/serverless-artillery/node_modules/tabtab/.completions/sls.bash
in /home/travis/.bashrc
events.js:167
      throw er; // Unhandled 'error' event
      ^
Error: socket hang up
    at createHangUpError (_http_client.js:322:15)
    at TLSSocket.socketOnEnd (_http_client.js:425:23)
    at TLSSocket.emit (events.js:187:15)
    at TLSSocket.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at TLSSocket.socketOnEnd (_http_client.js:425:9)
    at TLSSocket.emit (events.js:187:15)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Similar or dependent issues:
* https://github.com/serverless/serverless/issues/5133
* https://github.com/serverless/serverless/issues/5138

## Additional Data

* ***Serverless Framework Version you're using***: latest published (currently 1.32.0)
* ***Operating System***: Ubuntu 14.04.5 LTS
* ***Stack Trace***: see above
* ***Provider Error messages***: N/A

**Comment by erikerikson** [comment]
investigating fixes in newly linked issues.

**Comment by erikerikson** [comment]
Resolved by running `yarn upgrade` to use updated version of `serverless`
