### ISSUE TITLE
Multi-stage resource deploy failure

### ISSUE THREAD

**Issue by madmod** [serverless/serverless#538]
This an edge case but I thought I would bring it to your attention anyway as it might result in broken deployments. While deploying resources for both my development and beta stages simultaneously I noticed that the `s-resources-cf-development-useast1.json` file had variables from my beta deployment in it. This resulted in a failed deployment of my development stage as it was trying to recreate beta stage resources. Luckily the first thing to be created was an S3 bucket which has a unique name and caused it to rollback. If other resources such as IAM roles or CloudFormation distributions were updated the error could cause latent security issues or downtime and result in difficult to find issues in other stages. I only noticed the issue when looking at the diff of my `_meta` folder. I think that a good short term patch would be a simple lock file that allows deploying of only one stage at a time.

**Comment by madmod** [comment]
Some additional background to this issue is that this is my first time deploying after modifying my CloudFormation settings in `s-project.json`. For clarity the sequence of events follows.
1. Modify `s-project.json` and edit the CloudFormation stack template.
2. Deploy production with `sls resources deploy`
4. Production deployment completes successfully and configurations are correct
3. Begin deploying beta stage
4. Seconds after starting to deploy beta stage and before it finishes, begin deploying development stage
5. Beta stage deploy completes successfully and configurations are correct
6. Development stage deploy fails because it tried to re-create an S3 bucket with the same name as beta's
7. Attempting to re-deploy the development stage results in the same failure and it still has the incorrect values in its `_meta/resources` JSON file.

When does the configuration in `_meta/resources` update and why is it still failing to deploy?

**Comment by madmod** [comment]
Also it is possible that I may have deployed development before beta. I'm not sure which I started first, however they were both started within 5 seconds of each other.

**Comment by madmod** [comment]
This may be an unrelated issue but upon deploying development the second time I did get a strange error from serverless regarding the failure, although the list of events in the AWS Console CloudFormation events view is identical. Ignore my use of the incorrect command line argument `--env`.

```
john@dakine ~/Development/Daffinity/portalsync/serverless (master●)$ sls resources deploy --env development
Serverless: Which stage are you deploying to:
    1) beta
  > 2) development
    3) production
Serverless: Deploying resources to stage "development" in region "us-east-1" via Cloudformation (~3 minutes)...
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^

ServerlessError: ServerlessError: An error occurred while provisioning your cloudformation: undefined
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/ServerlessError.js:17:11)
    at /usr/local/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:265:19
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:260:17
From previous event:
    at ResourcesDeploy._deployResources (/usr/local/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:172:10)
From previous event:
    at ResourcesDeploy.resourcesDeploy (/usr/local/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:79:10)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:157:29
    at Array.reduce (native)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:156:30
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:154:10)
    at Serverless.actions.(anonymous function) (/usr/local/lib/node_modules/serverless/lib/Serverless.js:384:20)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:353:38)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:16:12)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3
****
```

Output from my third attempt for comparison:
```
john@dakine ~/Development/Daffinity/portalsync/serverless (master●)$ sls resources deploy --env development
Serverless: Which stage are you deploying to:
    1) beta
  > 2) development
    3) production
Serverless: Deploying resources to stage "development" in region "us-east-1" via Cloudformation (~3 minutes)...
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^

ServerlessError: ServerlessError: An error occurred while provisioning your cloudformation: The following resource(s) failed to update: [StaticAssetsBucket].
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/ServerlessError.js:17:11)
    at /usr/local/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:265:19
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:260:17
From previous event:
    at ResourcesDeploy._deployResources (/usr/local/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:172:10)
From previous event:
    at ResourcesDeploy.resourcesDeploy (/usr/local/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:79:10)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:157:29
    at Array.reduce (native)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:156:30
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:154:10)
    at Serverless.actions.(anonymous function) (/usr/local/lib/node_modules/serverless/lib/Serverless.js:384:20)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:353:38)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:16:12)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

**Comment by madmod** [comment]
Please disregard all of this, the issue was that I forgot to add the variables back into my template after copying and pasting it. :laughing:
