### ISSUE TITLE
Serverless destroyed my entire project

### ISSUE THREAD

**Issue by faun** [serverless/serverless#5417]
# This is a Bug Report

For feature proposals:

* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

* If there is additional config how would it look

## Description

For bug reports:

* What went wrong?

Serverless destroyed the entire project folder when running `SLS_DEBUG=* serverless deploy`

* What did you expect should have happened?

Anything but that. How about a confirmation before deleting *any* file one my machine?

* What was the config you used?

I don't have the configuration any more. Serverless deleted it.

* What stacktrace or error message from your provider did you see?

```
$ SLS_DEBUG=* serverless deploy
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command webpack
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke webpack:validate
Serverless:
WARNING: Entry for renderProxy@undefined could not be retrieved.
Please check your service config if you want to use lib.entries.
Serverless: Invoke webpack:compile
Serverless: Bundling with Webpack...

  Error --------------------------------------------------

  Cannot find module './webworker/WebWorkerTemplatePlugin'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: Cannot find module './webworker/WebWorkerTemplatePlugin'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at WebpackOptionsApply.process (/Users/faun/src/github.com/percy/cloudflare-workers/node_modules/webpack/lib/WebpackOptionsApply.js:111:36)
    at webpack (/Users/faun/src/github.com/percy/cloudflare-workers/node_modules/webpack/lib/webpack.js:53:48)
    at ServerlessWebpack.compile (/Users/faun/src/github.com/percy/cloudflare-workers/node_modules/serverless-webpack/lib/compile.js:11:22)
From previous event:
    at PluginManager.invoke (/Users/faun/n/lib/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.spawn (/Users/faun/n/lib/node_modules/serverless/lib/classes/PluginManager.js:408:17)
    at ServerlessWebpack.BbPromise.bind.then.then (/Users/faun/src/github.com/percy/cloudflare-workers/node_modules/serverless-webpack/index.js:101:51)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.11.3
     Serverless Version:     1.32.0

shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
...
Additional messages about no access to the current directory
```

Similar or dependent issues:

* None

## Additional Data

* ***Serverless Framework Version you're using***:

1.32.0

* ***Operating System***:

macOS 10.13.6

* ***Stack Trace***:

See above.

* ***Provider Error messages***:

I didn't get that far.

**Comment by faun** [comment]
Unfortunately, I can’t remember the version of the plugin. I’m going to close this now, since I’m sparse on details.
