### ISSUE TITLE
Serverless exits 0 after failing to upload service zip file

### ISSUE THREAD

**Issue by ahawkins** [serverless/serverless#5431]
# This is a Bug Report

## Description

See this console log:

```
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (17.45 MB)...
Serverless: Recoverable error occurred (write EPIPE), sleeping for 5 seconds. Try 1 of 4
git:feature/teams* >> echo $status
0
git:feature/teams* >> sls version
1.32.0
git:feature/teams* >>
```

It seems the "recoverable" error was improperly recovered from. Serverless should exit non-zero if the deploy does not complete.

## Additional Data

* ***Serverless Framework Version you're using***: 1.32.0
* ***Operating System***: MacOS 10.14

**Comment by ste23droid** [comment]
Hi there,
I just had the same problem. In your project source folder you should find a hidden directory called ".serverless". Delete that folder and try again with "serverless deploy", it should now work.

**Comment by pmuens** [comment]
Closing since this is a rather old issue. In the meantime we've published many different releases which should address this issue.

Feel free to re-open if this is still a problem.

**Comment by IvanBernatovic** [comment]
I have the same exact issue on the latest version. However, I'm using WSL. The output is the same (EPIPE error, exit status 0) but the version output is:
```
Framework Core: 1.50.0
Plugin: 1.3.8
SDK: 2.1.0
```

**Comment by IllyaVolkov111** [comment]
Hello! I have the same problem

`Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service sls-scheduler-service.zip file to S3 (56.72 MB)...
Serverless: Recoverable error occurred (write EPIPE), sleeping for ~4 seconds. Try 1 of 4

Framework Core: 1.67.0
Plugin: 3.6.1
SDK: 2.3.0
Components: 2.22.3`

**Comment by gvorster** [comment]
I have it too:

```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service googlenews.zip file to S3 (5.22 KB)...
Serverless: Uploading service commonLibs.zip file to S3 (29.22 MB)...
Serverless: Recoverable error occurred (write EPIPE), sleeping for ~5 seconds. Try 1 of 4
```

```
$ sls version
Framework Core: 1.67.3
Plugin: 3.6.6
SDK: 2.3.0
Components: 2.29.1

```

**Comment by TechNyquist** [comment]
Same problem here.
It hints for a retry that doesn't occur and we are suddenly back to bash in a pair of minutes.

```
[...]
Serverless: Safeguards Summary: 3 passed, 4 warnings, 0 errors
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service ft-bolus.zip file to S3 (9.77 MB)...
Serverless: Recoverable error occurred (write EPIPE), sleeping for ~5 seconds. Try 1 of 4
[root@localhost]# sls version
Framework Core: 1.67.0
Plugin: 3.6.1
SDK: 2.3.0
Components: 2.22.3
[root@localhost]# 
```

Sidenote: because of COVID-19 lockdown I'm smart-working from home. My internet connection performance is far from the office's one. The project is the very same, and we had no issues like this at the office. I've read of a guy who was experiencing the same through mobile connection, so I'd argue that this problem might be related to slow connections.

**Comment by dev-afzy** [comment]
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
`Serverless: Uploading artifacts...
`Serverless: Uploading service sqs-triggers-demo.zip file to S3 (15.13 MB)...
Serverless: Recoverable error occurred (write EPIPE), sleeping for ~7 seconds. Try 1 of 4``

**Comment by asrarbca** [comment]
Same issue here.
```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service chart-json.zip file to S3 (8.65 MB)...
Serverless: Recoverable error occurred (write EPIPE), sleeping for ~6 seconds. Try 1 of 4
```

```
Framework Core: 1.73.1
Plugin: 3.6.13
SDK: 2.3.1
Components: 2.30.16
```

**Comment by asrarbca** [comment]
I was able to resolve the issue by reducing the size of the zip file. I did so by removing aws-sdk from the package.json file. I didn't need that in package.json because apparently aws-sdk is  automatically included in AWS lambdas.

Hopefully this helps someone.

**Comment by asrarbca** [comment]
In case anyone else reads this I was able to resolve the issue. This was a network error, not an issue with AWS or serverless.

In my case, I was using a work computer which has McAfee installed, I had to disable the McAfee MCP module. After disabling it, everything worked as expected.

**Comment by mathieubrunpicard** [comment]
Same issue here 

```
Serverless: Recoverable error occurred (write EPIPE), sleeping for ~6 seconds. Try 1 of 4
```

```
Framework Core: 1.72.0
Plugin: 3.6.13
SDK: 2.3.1
Components: 2.30.13
```

I had no issue deploying from the same computer and same network yesterday though !

**Comment by Kieranshb** [comment]
Hi I am running into the same issue

`Serverless: Recoverable error occurred (write EPIPE), sleeping for ~6 seconds. Try 1 of 4`

```
Framework Core: 1.60.5
Plugin: 3.8.4
SDK: 2.3.2
Components Core: 1.1.2
Components CLI: 1.5.2
```
I have tried other versions as well with the same result. 

```
Framework Core: 2.28.6
Plugin: 4.4.3
SDK: 2.3.2
Components: 3.7.2
```
Does anyone have any ideas?

**Comment by pgrzesik** [comment]
It looks like an issue with internet connection during upload - does it happen all the time or only for specific projects while using specific connection @Kieranshb ?

**Comment by Kieranshb** [comment]
The only time it has worked in the last week has when I created an empty project and did the deploy. Once I install an npm package it gives me the above issue. I am able to manually deploy to S3 buckets. I have been using my home network but I did try and use my phone as a hotspot but I ran into the same problem as well.

**Comment by danb235** [comment]
I suspect it is due to a macOS upgrade.  What version of macOS are you running?

**Comment by Kieranshb** [comment]
Thanks for the help! I am currently running Big Sur 11.4. It had been an issue on the previous version. I upgraded thinking that the pending update was causing my problem. @danb235 do you know if this issue has been reported for 11.3.1 and 11.3?

**Comment by danb235** [comment]
We noticed this issue after a macOS upgrade from `11.3` to `11.4`.  So far it is not clear exactly what in that upgrade caused this (for instance did that upgrade affect other tooling such as node, sls or brew?).  If we figure out a solution I'll post back here.  In the meantime we are holding off on upgrades and the affected dev is using a backup laptop to get unblocked.

**Comment by Kieranshb** [comment]
Thanks for the heads up!

**Comment by antanasbrazenas** [comment]
Why is this closed? It's clearly an open issue, and until there are clear instructions to people stuck on MacOS (even if they don't require fixes to serverless.com framework itself) it should remain open. Many of your users will be in the same boat. Otherwise, update your supported versions and indicate clearly that serverless.com does not work with and does not support the latest MacOS versions.

**Comment by pgrzesik** [comment]
Hello @antanasbrazenas - it was closed really long time ago and the original issue was related to an outdated version of the Framework. I'm happy to reopen, but first, could someone please report a reproducible case? Ideally if it includes sample `serverless.yml`, output of failing command with `SLS_DEBUG=*` env var set for verbosity and output of running `serverless --version`. It would be much appreciated :bow:

**Comment by jerommar** [comment]
Hello @pgrzesik -
I'm able to reproduce that issue on mac os 11.4 with very simple serverless.yml

`
service: testsls

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221


functions:
  hello:
    handler: handler.hello
`

This is my version of serverless:
`sls --version
Framework Core: 2.51.0
Plugin: 5.4.3
SDK: 4.2.3
Components: 3.13.3`

And here is the output of the command with debug:
`sls deploy
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.51.0")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service testsls.zip file to S3 (3.86 MB)...
Serverless: Recoverable error occurred (Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
----------------------------------------------------------------------------------------------------), sleeping for ~5 seconds. Try 1 of 4`

As soon as the zip to be uploaded is bigger than 1mb, i'm facing that error. On version 2.49, it was exiting after the error, on 2.51 it's getting stuck on that error message forever. I tried multiple version of node: same issue. 

Sometimes i'm getting small variation of that error: 
`Serverless: Recoverable error occurred (TimeoutError: socket hang up
    at connResetException (internal/errors.js:628:14)
    at TLSSocket.socketOnEnd (_http_client.js:499:23)
    at TLSSocket.emit (events.js:387:35)
    at TLSSocket.emit (domain.js:470:12)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
----------------------------------------------------------------------------------------------------), sleeping for ~6 seconds. Try 1 of 4
`
But the behaviour is exactly the same, it's getting stuck there.

**Comment by pgrzesik** [comment]
Thanks @ahawkins, I'm going to re-open the issue and will try to get access to Mac with 11.4 to try to reproduce it

**Comment by mnapoli** [comment]
Hey everyone, I'm running macOS 11.4 and I'm not able to reproduce it.

I've tried with a project uploading a 17MB file (well over 1MB), no issue.

It may be related to something a bit more specific than just the macOS version (else I would expect that a lot more people would report the problem). Sorry I can't help more than that. Could it be related to a VPN, HTTP proxy, or anything of the sort?

**Comment by Kieranshb** [comment]
Thanks @mnapoli , I upgraded my computer to macOS 11.5.0, and that seemed to fix it for me. There must have been some strange security stuff that went on there. At the very least, if people are still encountering this issue, try and upgrade!

**Comment by mnapoli** [comment]
OK thank you for the update, let's close this for now then. If anyone is still stuck and has more details, let's reopen!

**Comment by TechNyquist** [comment]
Sorry guys, I'm opting to open this again as the issue has nothing to do with macOS. I'm on Windows and had same problem.

Real issue is the network. A laggy connection is required to reproduce this.

Please make up some stupid-simple new project and put there some dependencies to give it weight, or use some project you already have (just make sure there is a bunch of content to upload). Connect your PC through smartphone tethering, possibly 3G or slower, and try again. If I'm not wrong you'll see it happen.

My **very same project** worked at office (fast Internet) and failed at home (slow Internet).

**Comment by mahesh-kedari** [comment]
Observing same issue. 
`sls --version
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.72.1 (local)
Plugin: 5.5.4
SDK: 4.3.0
Components: 3.18.2
`
MacOS version - 12.2.1
Tried `sls deploy` on 100mbps speed network. So looks like network is not causing this problem.

**Comment by TechNyquist** [comment]
Ok so I guess this is not directly related to network speed. Maybe it's something else.
What about latency?

**Comment by tessiselated** [comment]
We're seeing this as an intermittent issue (which makes it a lot harder to debug) in Github Actions (so less likely to be speed)

Serverless version 3.34.0
