### ISSUE TITLE
Handler exception stack traces when using `invoke local` are useless

### ISSUE THREAD

**Issue by hdodov** [serverless/serverless#5438]
# This is a Feature Proposal

## Description

When you use `sls invoke local` and something bad happens in your handler function, you get:
```
Exception encountered when loading C:\Users\USER\Desktop\project\handler

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
```

However, after setting `SLS_DEBUG` to `*`, I simply get a bunch of other information that helps me in no way to debug the code.

For example, I have a handler that works perfectly fine with `invoke local`. If I add `foobar()`, at the top of the file and run `sls invoke local`, I expect to see something like:
```
Uncaught ReferenceError: foobar is not defined
```
Instead, I get:
```
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Invoke invoke:local
Serverless: INVOKING INVOKE
{}

  Error --------------------------------------------------

  Exception encountered when loading C:\Users\USER\Desktop\handler

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: Exception encountered when loading C:\Users\USER\Desktop\handler
    at AwsInvokeLocal.invokeLocalNodeJs (C:\Users\USER\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:272:13)
    at AwsInvokeLocal.invokeLocal (C:\Users\USER\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:125:19)
From previous event:
    at Object.invoke:local:invoke [as hook] (C:\Users\USER\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:26:10)
    at BbPromise.reduce (C:\Users\USER\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (C:\Users\USER\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:390:22)
    at PluginManager.run (C:\Users\USER\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:421:17)
    at variables.populateService.then.then (C:\Users\USER\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:157:33)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Serverless.run (C:\Users\USER\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:144:8)
    at serverless.init.then (C:\Users\USER\AppData\Roaming\npm\node_modules\serverless\bin\serverless:43:50)
    at <anonymous>

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           8.11.3
     Serverless Version:     1.32.0
```
Which helps me in no way.

This is bad, because whenever I have a syntax error that I missed, I have to comment out my code little by little until at some point it stops breaking and I can localize the problem.

It would be awesome if we could get a bit more useful information when using `invoke local`. We get that an exception occurred, but a bit more information about the exception would be great.

**Comment by arvindnarang** [comment]
Hey ! Did you get any help or solution you'd like to share with others .. I have ran into same problem

**Comment by hdodov** [comment]
Nope. Sadly, you have to do it the hard way...

**Comment by dschep** [comment]
What runtime are you using, @hdodov?

**Comment by tsdorsey** [comment]
I am also using node (8.10) and this bit me too. The issue has to do with formatting the error. Here is the line where the error is caught and then is supposed to be printed. 

https://github.com/serverless/serverless/blob/8c53de83bf62a4e1f66821e0321abb996880b5bd/lib/plugins/aws/invokeLocal/index.js#L312

What ends up being output is right here:
> Serverless: INVOKING INVOKE
> {}  <-- this is the JSON.stringified error 🙈 
> 
>   Error --------------------------------------------------

If in the `invokeLocal/index.js` file you add a simple `console.log(error);` you get the error with call stack printed to the screen.

I don't know WHY this happens but I now just toss a `console.error(error);` in there anytime I run into it.

**Comment by pmuens** [comment]
Closing this since it was implemented via https://github.com/serverless/serverless/pull/5835.
