### ISSUE TITLE
Cannot local invoke python WSGI app

### ISSUE THREAD

**Issue by revmischa** [serverless/serverless#5475]
```
(pcc) [pcc] sls invoke local -p invoke/get_swagger.json -f app                                                                             
Traceback (most recent call last):
  File "/Users/cyber/.config/yarn/global/node_modules/serverless/lib/plugins/aws/invokeLocal/invoke.py", line 60, in <module>

    module = import_module(args.handler_path.replace('/', '.'))
  File "/Users/cyber/.virtualenvs/pcc/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wsgi'

(pcc) [pcc] pip install wsgi                                                                                                               
Collecting wsgi
  Could not find a version that satisfies the requirement wsgi (from versions: )
No matching distribution found for wsgi
```

**Comment by dschep** [comment]
Are you using the `serverless-wsgi` plugin?

**Comment by dschep** [comment]
@logandk, does `serverless-wsgi` work with `sls invoke local`?

**Comment by logandk** [comment]
@dschep Appears that it doesn't at the moment. During deployment, `wsgi.py` gets added to the zip archive, so we'll probably need to do something else for local function invocations, such as modifying `PYTHONPATH`. I'll look into it. Although not quite the same, `sls wsgi serve` is the closest thing until we have `sls invoke local` working.

**Comment by dschep** [comment]
Thanks for the feedback @logandk! Would this maybe work:
```
curl -O https://raw.githubusercontent.com/logandk/serverless-wsgi/master/wsgi.py
sls invoke local -p invoke/get_swagger.json -f app
```

**Comment by dschep** [comment]
Awesome. Good work @logandk 👍
