### ISSUE TITLE
'module install': ServerlessError: Command not found.

### ISSUE THREAD

**Issue by pranspach** [serverless/serverless#549]
I'm trying to run `sls module install https://github.com/eahefnawy/awsm-slack-webhook` from the root of my project directory. Serverless help doesn't mention an install action for module. What are the accurate installation procedures for modules? I'm on serverless 0.2.1
```
/Users/patrickranspach/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^

ServerlessError: Command not found.  Enter "serverless help" to see all available commands.
    at new ServerlessError (/Users/patrickranspach/.npm-packages/lib/node_modules/serverless/lib/ServerlessError.js:17:11)
    at Serverless.command (/Users/patrickranspach/.npm-packages/lib/node_modules/serverless/lib/Serverless.js:318:31)
    at Object.<anonymous> (/Users/patrickranspach/.npm-packages/lib/node_modules/serverless/bin/serverless:16:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

**Comment by shortjared** [comment]
The module install has been pulled out for the time being has been pulled out for the time being until things settle down and the new Serverless module structure is defined.
