### ISSUE TITLE
TravisCI's async test randomly fail 

### ISSUE THREAD

**Issue by exoego** [serverless/serverless#5533]
# This is a Bug Report

## Description

* What went wrong?
TravisCI's Async test randomly fail on multiple Pull Reques due to timeout.
https://travis-ci.org/serverless/serverless/jobs/433968798#L6846
https://travis-ci.org/serverless/serverless/jobs/460342754#L6803
https://travis-ci.org/serverless/serverless/jobs/461000739#L6803
https://travis-ci.org/serverless/serverless/jobs/461008020#L6173

* What did you expect should have happened?
Test should be robust, so that contributors don't get confused by fragile test. 

* What was the config you used?
N/A

* What stacktrace or error message from your provider did you see?
```
    Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/travis/build/serverless/serverless/lib/plugins/aws/provider/awsProvider.test.js)
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:694:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:638:18)
      at Promise._resolveCallback (node_modules/bluebird/js/release/promise.js:432:57)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:524:17)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:694:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:638:18)
      at Promise._resolveCallback (node_modules/bluebird/js/release/promise.js:454:14)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:524:17)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:694:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:638:18)
      at PromiseArray._resolve (node_modules/bluebird/js/release/promise_array.js:126:19)
      at PromiseArray._promiseFulfilled (node_modules/bluebird/js/release/promise_array.js:144:14)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:574:26)
      at Promise._fulfillPromises (node_modules/bluebird/js/release/promise.js:669:14)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:695:18)
      at _drainQueueStep (node_modules/bluebird/js/release/async.js:138:12)
      at _drainQueue (node_modules/bluebird/js/release/async.js:131:9)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:147:5)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:17:14)
```

**Comment by luanmuniz** [comment]
Is increase the timeout an acceptable solution?

**Comment by dhuang612** [comment]
I would like to take this on

**Comment by dhuang612** [comment]
created PR #6881

**Comment by dhuang612** [comment]
Hi,
created PR #6888 
Please let me know if anything else needs to be changed!

**Comment by dhuang612** [comment]
This can be closed, no additional work needs to be completed.

**Comment by medikoo** [comment]
I believe that with test setup improvements that were implemented in last months, this issue was fixed.

I'm closing it, still if you feel there are still some not addressed issues, please comment.
