### ISSUE TITLE
layerObject.allowedAccounts.map is not a function

### ISSUE THREAD

**Issue by gary-tsai-zocdoc** [serverless/serverless#5616]
# This is a Bug Report

## Description

* What went wrong?
Unable to perform ```sls package``` for lambda layers when ```allowedAccounts:``` is used in serverless.yml.  I can perform ```sls package``` when ```allowedAccounts:``` is removed in serverless.yml.
* What did you expect should have happened?
Package the for layers for Lambda
* What stacktrace or error message from your provider did you see?
layerObject.allowedAccounts.map is not a function

* serverless.yml
```service: layer_section

provider:
  name: aws
  environment:
    NODE_PATH: "./:/opt/node_modules"

package:
  exclude:
    - aws_sdk_layer/**

layers:
  octokit_Module:
    path: octokit_layer
    allowedAccounts: "*"
    description: "Contains octokit and AWS SDK modules"
```

## Additional Data

* ***Serverless Framework Version you're using***:
serverless: 1.35.1
node: 11.5.0
* ***Operating System***:
Mac Mojave 

* ***Stack Trace***:
```
TypeError: layerObject.allowedAccounts.map is not a function
    at AwsCompileLayers.compileLayer (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/layers/index.js:58:35)
    at BbPromise.each.layerName (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/layers/index.js:88:25)
From previous event:
    at AwsCompileLayers.compileLayers (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/layers/index.js:86:22)
From previous event:
    at Object.package:compileLayers [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/layers/index.js:19:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:391:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:391:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:422:17)
    at variables.populateService.then.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:157:33)
    at processImmediate (timers.js:632:19)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:44:28)
```
* ***Provider Error messages***:

**Comment by dschep** [comment]
That's because `allowedAccounts` must be an array of strings, not a single string. To fix your issue, use:
```yaml

provider:
  name: aws
  environment:
    NODE_PATH: "./:/opt/node_modules"

package:
  exclude:
    - aws_sdk_layer/**

layers:
  octokit_Module:
    path: octokit_layer
    allowedAccounts:
      - "*"
    description: "Contains octokit and AWS SDK modules"
```
