### ISSUE TITLE
Error: Error: spawnSync docker ENOENT

### ISSUE THREAD

**Issue by moha0902** [serverless/serverless#5663]
# This is a Bug Report

## Description

* What went wrong?
Not able to deploy vanila https://github.com/softprops/serverless-aws-rust-multi 
* What did you expect should have happened?
It to be deployed
* What was the config you used?
* What stacktrace or error message from your provider did you see?

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
➜  casemagic SLS_DEBUG=* npx serverless deploy
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command dynamodb
Serverless: Load command dynamodb:migrate
Serverless: Load command dynamodb:seed
Serverless: Load command dynamodb:start
Serverless: Load command dynamodb:noStart
Serverless: Load command dynamodb:remove
Serverless: Load command dynamodb:install
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Building native Rust hello func...
Serverless: Dockerized Rust build encountered an error: Error: spawnSync docker ENOENT null.
 
  Error --------------------------------------------------
 
  Error: spawnSync docker ENOENT
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: Error: spawnSync docker ENOENT
    at functions.forEach.funcName (/Users/mohammedyounusraza/devo/rust/lambda/casemagic/node_modules/serverless-rust/index.js:106:15)
    at Array.forEach (<anonymous>)
    at RustPlugin.build (/Users/mohammedyounusraza/devo/rust/lambda/casemagic/node_modules/serverless-rust/index.js:90:22)
    at BbPromise.reduce (/Users/mohammedyounusraza/devo/rust/lambda/casemagic/node_modules/serverless/lib/classes/PluginManager.js:391:55)
From previous event:
    at PluginManager.invoke (/Users/mohammedyounusraza/devo/rust/lambda/casemagic/node_modules/serverless/lib/classes/PluginManager.js:391:22)
    at PluginManager.spawn (/Users/mohammedyounusraza/devo/rust/lambda/casemagic/node_modules/serverless/lib/classes/PluginManager.js:409:17)
    at Deploy.BbPromise.bind.then (/Users/mohammedyounusraza/devo/rust/lambda/casemagic/node_modules/serverless/lib/plugins/deploy/deploy.js:117:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/Users/mohammedyounusraza/devo/rust/lambda/casemagic/node_modules/serverless/lib/plugins/deploy/deploy.js:107:10)
    at BbPromise.reduce (/Users/mohammedyounusraza/devo/rust/lambda/casemagic/node_modules/serverless/lib/classes/PluginManager.js:391:55)
From previous event:
    at PluginManager.invoke (/Users/mohammedyounusraza/devo/rust/lambda/casemagic/node_modules/serverless/lib/classes/PluginManager.js:391:22)
    at PluginManager.run (/Users/mohammedyounusraza/devo/rust/lambda/casemagic/node_modules/serverless/lib/classes/PluginManager.js:422:17)
    at variables.populateService.then.then (/Users/mohammedyounusraza/devo/rust/lambda/casemagic/node_modules/serverless/lib/Serverless.js:157:33)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (/Users/mohammedyounusraza/devo/rust/lambda/casemagic/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/Users/mohammedyounusraza/devo/rust/lambda/casemagic/node_modules/serverless/bin/serverless:44:28)
    at run (/Users/mohammedyounusraza/devo/rust/lambda/casemagic/node_modules/core-js/modules/es6.promise.js:75:22)
    at /Users/mohammedyounusraza/devo/rust/lambda/casemagic/node_modules/core-js/modules/es6.promise.js:92:30
    at flush (/Users/mohammedyounusraza/devo/rust/lambda/casemagic/node_modules/core-js/modules/_microtask.js:18:9)
    at process._tickCallback (internal/process/next_tick.js:172:11)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           10.0.0
     Serverless Version:     1.35.0

**Comment by dschep** [comment]
This is because that project uses [`serverless-rust`](https://github.com/softprops/serverless-rust/) which depends on docker. @softprops, you might want to add info about the docker requirement in the READMEs of these repos 😉

**Comment by JimLynchCodes** [comment]
ah dang, actually I am still getting this error when I try to invoke it locally `sls invoke local -f hello`

```
error[E0599]: no function or associated item named `as_ptr` found for struct `std::sync::Arc<_>` in the current scope
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-task-0.3.21/src/waker_ref.rs:58:20
   |
58 |     let ptr = Arc::as_ptr(wake).cast::<()>();
   |                    ^^^^^^ function or associated item not found in `std::sync::Arc<_>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `futures-task`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
Serverless: Rust build encountered an error: undefined 1.
 
  Error --------------------------------------------------
 
  Error: 
      at /Users/jlynch/Git-Projects/mongo-contact-form-handler-crab-lamb/node_modules/serverless-rust/index.js:289:15
      at Array.forEach (<anonymous>)
      at RustPlugin.build (/Users/jlynch/Git-Projects/mongo-contact-form-handler-crab-lamb/node_modules/serverless-rust/index.js:269:22)
      at /Users/jlynch/Git-Projects/mongo-contact-form-handler-crab-lamb/node_modules/serverless/lib/classes/PluginManager.js:476:55
      at tryCatcher (/Users/jlynch/Git-Projects/mongo-contact-form-handler-crab-lamb/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/Users/jlynch/Git-Projects/mongo-contact-form-handler-crab-lamb/node_modules/bluebird/js/release/reduce.js:168:18)
      at Object.gotAccum (/Users/jlynch/Git-Projects/mongo-contact-form-handler-crab-lamb/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (/Users/jlynch/Git-Projects/mongo-contact-form-handler-crab-lamb/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/jlynch/Git-Projects/mongo-contact-form-handler-crab-lamb/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/jlynch/Git-Projects/mongo-contact-form-handler-crab-lamb/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/Users/jlynch/Git-Projects/mongo-contact-form-handler-crab-lamb/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/Users/jlynch/Git-Projects/mongo-contact-form-handler-crab-lamb/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/Users/jlynch/Git-Projects/mongo-contact-form-handler-crab-lamb/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/Users/jlynch/Git-Projects/mongo-contact-form-handler-crab-lamb/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/Users/jlynch/Git-Projects/mongo-contact-form-handler-crab-lamb/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/Users/jlynch/Git-Projects/mongo-contact-form-handler-crab-lamb/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:464:21)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.18.2
     Framework Version:         1.74.1
     Plugin Version:            3.6.15
     SDK Version:               2.3.1
     Components Version:        2.31.10
    ```
