### ISSUE TITLE
Bug: Rollback fails due to timestamp parsing error

### ISSUE THREAD

**Issue by ldani7492** [serverless/serverless#5664]
# This is a Bug Report

## Description

* What went wrong?
Receiving _Range Error: Invalid time value_ when trying to rollback (with correct timestamp).
E.g. _sls rollback -t 1546961025152_

* What did you expect should have happened?
Rollback should have been successful
Looks like since this.options.timestamp is a string, the wrong constructor of Date is called, and it's expecting a date string.
I was able to make this work by changing line 68 of _serverless\lib\plugins\aws\rollback\index.js_ to

      const date = new Date(Number(this.options.timestamp));

* What was the config you used?
Any, including the aws-java-gradle template

* What stacktrace or error message from your provider did you see?
  
Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.35.1
* ***Operating System***: Windows 10 Enterprise (10.0.17134)
* ***Stack Trace***:

      RangeError: Invalid time value
          at Date.toISOString (<anonymous>)
          at provider.request.then (C:\Users\<username>\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\rollback\index.js:69:65)
      From previous event:
          at AwsRollback.setStackToUpdate (C:\Users\<username>\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\rollback\index.js:59:8)
      From previous event:
          at Object.rollback:rollback [as hook] (C:\Users\<username>\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\rollback\index.js:40:12)
          at BbPromise.reduce (C:\Users\<username>\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:391:55)
      From previous event:
          at PluginManager.invoke (C:\Users\<username>\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:391:22)
          at PluginManager.run (C:\Users\<username>\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:422:17)
          at variables.populateService.then.then (C:\Users\<username>\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:157:33)
          at runCallback (timers.js:705:18)
          at tryOnImmediate (timers.js:676:5)
          at processImmediate (timers.js:658:5)
          at process.topLevelDomainCallback (domain.js:120:23)
      From previous event:
          at Serverless.run (C:\Users\<username>\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:144:8)
          at serverless.init.then (C:\Users\<username>\AppData\Roaming\npm\node_modules\serverless\bin\serverless:44:28)

* ***Provider Error messages***:

**Comment by luanmuniz** [comment]
@ldani7492 Can you check if the PR i've just created fix your issue?

**Comment by ldani7492** [comment]
@luanmuniz it does, thank you
