### ISSUE TITLE
Debug Node AWS Lambda Function with serverless offline causes Error

### ISSUE THREAD

**Issue by ManuelMos** [serverless/serverless#5734]
# This is a Bug Report

## Description

* My Environment:  **Windows 10, node.js 10.15.0, sls 1.36.1.**

I try to debug my nodejs lambda function with serverless offline. 

Running 
`node --inspect node_modules/.bin/serverless offline`

causes:

basedir=(dirname "(echo “$0” | sed -e ‘s,\,/,g’)")
^^^^^^^
SyntaxError: missing ) after argument list
at new Script (vm.js:79:7)
at createScript (vm.js:251:10)
at Object.runInThisContext (vm.js:303:10)
at Module._compile (internal/modules/cjs/loader.js:657:28)
at Object.Module._extensions…js (internal/modules/cjs/loader.js:700:10)
at Module.load (internal/modules/cjs/loader.js:599:32)
at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
at Function.Module._load (internal/modules/cjs/loader.js:530:3)
at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
at startup (internal/bootstrap/node.js:283:19)

Same when i try to run it in intellij:
![image](https://user-images.githubusercontent.com/21379297/51538512-c357b480-1e51-11e9-92f5-6478ebf177e7.png)

**Comment by pmuens** [comment]
Hey @ManuelMos thanks for opening 👍

Could you re-open this issue in the `serverless-offline` plugin repo since it's a plugin specific error? Thanks!

**Comment by jp928** [comment]
same here. Is there any solution?
