### ISSUE TITLE
Maximum Call Stack Size Exceeded

### ISSUE THREAD

**Issue by carlevans719** [serverless/serverless#5766]
# This is a Bug Report

## Description

* What went wrong? **when running `serverless deploy` I got a RangeError for maximum call stack size exceeded**
* What did you expect should have happened? **The functions should have deployed**
* What was the config you used? **see below**
* What stacktrace or error message from your provider did you see? **see below**

## Config
```
AWS_ACCOUNT_ID: "0123456789"
SCHEDULED_FUNCTIONS: false
DOMAIN_NAME: app.subdomain.domain.tld
CERT_NAME: "*.subdomain.domain.tld"
DB_USERNAME: user_name
DB_PASSWORD: redacted
DB_NAME: dbname
DB_HOST: name.region.rds.amazonaws.com
FCM_SERVER_KEY: redacted
```

## Stack Trace
```
$ SLS_DEBUG=* serverless deploy function -f deleteCategory -s dev
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command create_domain
Serverless: Load command delete_domain
 
  Range Error --------------------------------------------
 
  Maximum call stack size exceeded
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
RangeError: Maximum call stack size exceeded
    at Object (<anonymous>)
    at baseGetTag (/home/carl/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/node_modules/lodash/lodash.js:3073:51)
    at Function.isFunction (/home/carl/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/node_modules/lodash/lodash.js:11654:17)
    at Variables.getProperties (/home/carl/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/lib/classes/Variables.js:197:10)


===================== MANY, MANY LINES REMOVED =====================


    at Variables.getProperties (/home/carl/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/lib/classes/Variables.js:200:11)
    at Variables.populateObjectImpl (/home/carl/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/lib/classes/Variables.js:250:25)
    at assignProperties.then (/home/carl/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/lib/classes/Variables.js:256:24)
From previous event:
    at Variables.populateObjectImpl (/home/carl/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/lib/classes/Variables.js:256:8)
    at prepopulateService.then (/home/carl/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/lib/classes/Variables.js:135:26)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at initialCall (/home/carl/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/lib/classes/Variables.js:135:10)
    at Variables.initialCall (/home/carl/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/lib/classes/Variables.js:66:12)
    at Variables.populateService (/home/carl/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/lib/classes/Variables.js:133:17)
    at Serverless.run (/home/carl/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/lib/Serverless.js:90:27)
    at serverless.init.then (/home/carl/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/bin/serverless:43:28)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           10.15.1
     Serverless Version:     1.36.3

```

Similar or dependent issues:
* #5241 - same error but cause appears different

## Additional Data

* ***Serverless Framework Version you're using***: 1.36.3
* ***Operating System***: linux - ubuntu 18.10
* ***Stack Trace***: see above
* ***Provider Error messages***: none

I've tried running the deployment with node version 8.15.0, 6.16.0 and 10.15.1 with a fresh installation of serverless & project dependencies each time.

**Comment by dschep** [comment]
I don't understand your config. could you share your `serverless.yml`?

**Comment by odgiv** [comment]
I have the same problem. Have you found a solution?
