### ISSUE TITLE
TypeError: Cannot read property 'Type' of null

### ISSUE THREAD

**Issue by 3ammari** [serverless/serverless#5804]
# This is a Bug Report

## Description

* What went wrong?
`sls deploy` fails to with type error
* What did you expect should have happened?
deployment should happen successfully 
* What was the config you used?

```


service: rating-service

provider:
  name: aws
  runtime: go1.x
  versionFunctions: false
# you can overwrite defaults here
  stage: DevRatingStack
  region: us-east-2
  memorySize: 512
  timeout: 10

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  driverGivingTripRate:
    handler: bin/driverGivingTripRate
    events:
      - sqs: 
          arn: 
            Fn::GetAtt:
              - "DriverGivingRatingQueue"
              - "Arn"
          batchSize: 10


resources:          
  Resources:
    RatingServiceDeadLetterQueue:
      Type: 'AWS::SQS::QUEUE'
    DriverGivingRatingQueue:
      Type: 'AWS::SQS::QUEUE'
      Properties:
        RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "RatingServiceDeadLetterQueue"
            - "Arn"
        maxReceiveCount: 3
    UserGivingRatingQueue:
      Type: 'AWS::SQS::QUEUE'
      Properties:
        RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "RatingServiceDeadLetterQueue"
            - "Arn"
        maxReceiveCount: 3
    DriverGivingRatingTopic:
      Type: 'AWS::SNS::Topic'
      Properties:
        DisplayName: 'DriverGivingTripRating'
        TopicName: ${self:service}-${self:provider.stage}-DriverGivingRatingTopic-topic
        Subscription:
        - Endpoint:
            Fn::GetAtt:
              - "DriverGivingRatingQueue"
              - "Arn"
          Protocol: "sqs"
    UserGivingRatingTopic:
      Type: 'AWS::SNS::Topic'
      Properties:
        DisplayName: 'UserGivingTripRating'
        TopicName: ${self:service}-${self:provider.stage}-UserGivingRatingTopic-topic
        Subscription:
        - Endpoint:
            Fn::GetAtt:
              - "UserGivingRatingQueue"
              - "Arn"
          Protocol: "sqs"
    UserRatingUpdateTopic:
      Type: 'AWS::SNS::Topic'
      Properties:
        DisplayName: 'UserRatingUpdateTopic'
        TopicName: ${self:service}-${self:provider.stage}-UserRatingUpdateTopic-topic
    DriverRatingUpdateTopic:
      Type: 'AWS::SNS::Topic'
      Properties:
        DisplayName: 'DriverRatingUpdateTopic'
        TopicName: ${self:service}-${self:provider.stage}-DriverRatingUpdateTopic-topic
    ProdQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Id:
          Fn::Join:
            - ''
            - - ProdQueuePolicy
              - Fn::Ref: '${self:provider.stage}'                  
        Statement:
          - Sid: 
            Fn::Join:
              - '-'
              - - 'Allow-SendMessage-To-Queues-From-SNS-Topics'
                - Fn::Ref: '${self:provider.stage}'
            Effect: Allow
            Principal: "*"
            Action:
              - sqs:SendMessage
            Resource: "*"
            Condition:
              ArnEquals:
                aws:SourceArn:
                  - Fn::Ref: DriverGivingRatingTopic
                  - Fn::Ref: UserGivingRatingTopic
                  - Fn::Ref: UserRatingUpdateTopic
                  - Fn::Ref: DriverRatingUpdateTopic
      Queues:
        - Fn::Ref: UserGivingRatingQueue
        - Fn::Ref: DriverGivingRatingQueue    
Outputs:
    DriverGivingRatingQueue:
      Value: 
        Fn::Ref: "DriverGivingRatingQueue"
      Export: 
        Name: 
          Fn::Join :
            - ':'
            - - ${self:service}-${self:provider.stage}
              - "DriverGivingRatingQueue"
    UserGivingRatingQueue:
      Value: 
        Fn::Ref: 'UserGivingRatingQueue'
      Export: 
        Name: 
          Fn::Join :
            - ':'
            - - ${self:service}-${self:provider.stage}
              - 'UserGivingRatingQueue'
    DriverGivingRatingTopic:
      Value:
        Fn::Ref: 'DriverGivingRatingTopic'
      Export: 
        Name: 
          Fn::Join :
            - ':'
            - - ${self:service}-${self:provider.stage}
              - 'DriverGivingRatingTopic'
    UserGivingRatingTopic:
      Value: 
        Fn::Ref: 'UserGivingRatingTopic'
      Export: 
        Name: 
          Fn::Join :
            - ':'
            - - ${self:service}-${self:provider.stage}
              - 'UserGivingRatingTopic'
    UserRatingUpdateTopic:
      Value: 
        Fn::Ref: 'UserRatingUpdateTopic'
      Export: 
        Name: 
          Fn::Join :
            - ':'
            - -  ${self:service}-${self:provider.stage}
              - 'UserRatingUpdateTopic'
    DriverRatingUpdateTopic:
      Value: 
        Fn::Ref: 'DriverRatingUpdateTopic'
      Export: 
        Name: 
          Fn::Join :
            - ':'
            - -  ${self:service}-${self:provider.stage}
              - 'DriverRatingUpdateTopic'

```
* What stacktrace or error message from your provider did you see?
```
TypeError: Cannot read property 'Type' of null
    at _.forEach (/usr/lib/node_modules/serverless/lib/plugins/aws/lib/normalizeFiles.js:11:17)
    at /usr/lib/node_modules/serverless/node_modules/lodash/lodash.js:4911:15
    at baseForOwn (/usr/lib/node_modules/serverless/node_modules/lodash/lodash.js:2996:24)
    at /usr/lib/node_modules/serverless/node_modules/lodash/lodash.js:4880:18
    at Function.forEach (/usr/lib/node_modules/serverless/node_modules/lodash/lodash.js:9344:14)
    at Object.normalizeCloudFormationTemplate (/usr/lib/node_modules/serverless/lib/plugins/aws/lib/normalizeFiles.js:10:7)
    at AwsDeploy.checkIfDeploymentIsNecessary (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/checkForChanges.js:85:45)
From previous event:
    at AwsDeploy.checkForChanges (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/checkForChanges.js:22:8)
From previous event:
    at Object.aws:deploy:deploy:checkForChanges [as hook] (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:106:10)
    at BbPromise.reduce (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.spawn (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:408:17)
    at AwsDeploy.BbPromise.bind.then (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:95:48)
From previous event:
    at Object.deploy:deploy [as hook] (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:91:10)
    at BbPromise.reduce (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.run (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:421:17)
    at variables.populateService.then.then (/usr/lib/node_modules/serverless/lib/Serverless.js:157:33)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Serverless.run (/usr/lib/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/usr/lib/node_modules/serverless/bin/serverless:43:50)
    at <anonymous>
```

## Additional Data

* ***Serverless Framework Version you're using***:
1.32
* ***Operating System***:
Ubuntu 18.04
* ***Stack Trace***:

* ***Provider Error messages***:

**Comment by 3ammari** [comment]
Apologies , file wasn't indented correctly
