### ISSUE TITLE
Getting `socket hang up` error on deploying to azure

### ISSUE THREAD

**Issue by jagzviruz** [serverless/serverless#5818]
# This is a Bug Report

## Description

* What went wrong?
When I tried to deploy a sample snippet to an Azure function, it fails at the uploading function step with the error message : `socket hang up`

* What did you expect should have happened?
It should have created the function.

* What was the config you used?

* What stacktrace or error message from your provider did you see?
```
Serverless: Uploading function: graphql

  Error --------------------------------------------------

  socket hang up

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

```

## Additional Data
```
Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           10.15.1
     Serverless Version:     1.37.1
```
```
Serverless: Uploading function: graphql

  Error --------------------------------------------------

  socket hang up

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at TLSSocket.socketOnEnd (_http_client.js:426:23)
    at TLSSocket.emit (events.js:194:15)
    at TLSSocket.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:400:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:431:17)
    at variables.populateService.then.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:114:33)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:101:6)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:43:28)
    at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
    at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at initializeErrorReporter.then (/usr/local/lib/node_modules/serverless/bin/serverless:43:6)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at /usr/local/lib/node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:67:4)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

**Comment by jagzviruz** [comment]
And this is the content of `~/.serverlessrc`

```
{
  "userId": null,
  "frameworkId": "6e414a90-2bd2-11e9-8db4-8384aabca189",
  "trackingDisabled": false,
  "meta": {
    "created_at": 1549651840,
    "updated_at": null
  }
}
```

**Comment by pmuens** [comment]
Hey @jagzviruz thanks for opening 👍

Looks like it's a plugin specific bug. Could you open up the issue in the azure functions plugin repository?

Thanks!

**Comment by mohammedzamakhan** [comment]
I don't think its a azure functions plugin repository issue! I think its to do with the node version, it doesn't throws this error with node v9.1.0 but fails with v10 and above
