### ISSUE TITLE
Unable to create using private repo as template

### ISSUE THREAD

**Issue by ZebraFlesh** [serverless/serverless#5837]
# This is a Bug Report

## Description

* What went wrong?
When attempting to `serverless create --template-url=https://x-access-token:my-token@github.com/my-org/some-private-repo --name unicorns-are-awesome` , I get the error `Basic authentication must be done with auth option`

* What did you expect should have happened?
The template should have been used to create a new service with the specified name.

* What was the config you used?
None -- this is just a create command. For the access token, I: 
  * created a Github personal access token
  * granted the `repo` OAuth scope to the token 
  * enabled SSO for the token 
 
* What stacktrace or error message from your provider did you see?
Stacktrace:
```
Error: Basic authentication must be done with auth option
    at normalizeArguments (C:\ProgramData\nvm\v10.15.0\node_modules\serverless\node_modules\got\index.js:205:10)
    at Function.got.stream (C:\ProgramData\nvm\v10.15.0\node_modules\serverless\node_modules\got\index.js:321:38)
    at module.exports (C:\ProgramData\nvm\v10.15.0\node_modules\serverless\node_modules\download\index.js:55:21)
    at Object.downloadTemplateFromRepo (C:\ProgramData\nvm\v10.15.0\node_modules\serverless\lib\utils\downloadTemplateFromRepo.js:208:10)
    at Create.create (C:\ProgramData\nvm\v10.15.0\node_modules\serverless\lib\plugins\create\create.js:116:23)
From previous event:
    at Object.create:create [as hook] (C:\ProgramData\nvm\v10.15.0\node_modules\serverless\lib\plugins\create\create.js:106:10)
    at BbPromise.reduce (C:\ProgramData\nvm\v10.15.0\node_modules\serverless\lib\classes\PluginManager.js:400:55)
From previous event:
    at PluginManager.invoke (C:\ProgramData\nvm\v10.15.0\node_modules\serverless\lib\classes\PluginManager.js:400:22)
    at PluginManager.run (C:\ProgramData\nvm\v10.15.0\node_modules\serverless\lib\classes\PluginManager.js:431:17)
    at variables.populateService.then.then (C:\ProgramData\nvm\v10.15.0\node_modules\serverless\lib\Serverless.js:114:33)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Serverless.run (C:\ProgramData\nvm\v10.15.0\node_modules\serverless\lib\Serverless.js:101:6)
    at serverless.init.then (C:\ProgramData\nvm\v10.15.0\node_modules\serverless\bin\serverless:43:28)
    at C:\ProgramData\nvm\v10.15.0\node_modules\serverless\node_modules\graceful-fs\graceful-fs.js:111:16
    at C:\ProgramData\nvm\v10.15.0\node_modules\serverless\node_modules\graceful-fs\graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at initializeErrorReporter.then (C:\ProgramData\nvm\v10.15.0\node_modules\serverless\bin\serverless:43:6)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at C:\ProgramData\nvm\v10.15.0\node_modules\serverless\bin\serverless:28:46
    at Object.<anonymous> (C:\ProgramData\nvm\v10.15.0\node_modules\serverless\bin\serverless:67:4)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

Similar or dependent issues:
* #5715

## Additional Data

* ***Serverless Framework Version you're using***: 1.37.1
* ***Operating System***: Windows 10
* ***Stack Trace***: See above
* ***Provider Error messages***: N/A

**Comment by eahefnawy** [comment]
@ZebraFlesh that makes sense as we don't support private repos since we're making direct http downloads of the zip file.

I'm tagging this as a feature request and would love feedback from the community.

**Comment by ZebraFlesh** [comment]
@eahefnawy If you look at PR #5715, Enable download template from a private github repo using personal access token (which has been merged), this looks like it's a feature which is already supposed to work, but is broken. Therefore a bug classification seems more accurate.

**Comment by ZebraFlesh** [comment]
Any movement on this item? It's still broken, but still claimed as working because #4566 is closed

**Comment by rguerra712** [comment]
This is still broken in 1.59.3, any progress on this?
