### ISSUE TITLE
invoke local docker does not set environment variables configured in serverless.yml

### ISSUE THREAD

**Issue by endeepak** [serverless/serverless#5945]
# This is a Bug Report

## Description

* What went wrong?
`sls invoke local --docker` does not pass environment variables configured in `serverless.yml` to the docker container running lambda

* What did you expect should have happened?
Environment variables configured in `serverless.yml` should be available for lambda function running in the docker container

* What was the config you used?

`serverless.yml`
```yml
service: env-var-bug

provider:
  name: aws
  runtime: python2.7
  environment:
    SOME_ENV_VAR: some-value

functions:
  hello:
    handler: handler.hello
```

`handler.py`
```py
import os

def hello(event, context):
    return os.environ['SOME_ENV_VAR']
```

* What stacktrace or error message from your provider did you see?

```
➜  env-var-bug sls invoke local -f hello
"some-value"
➜  env-var-bug sls invoke local -f hello --docker
Serverless: Building Docker image...
START RequestId: d3116be1-e3f9-402b-a460-468115ddd24e Version: $LATEST

'SOME_ENV_VAR': KeyError
Traceback (most recent call last):
  File "/var/task/handler.py", line 5, in hello
    return os.environ['SOME_ENV_VAR']
  File "/usr/lib64/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'SOME_ENV_VAR'

END RequestId: d3116be1-e3f9-402b-a460-468115ddd24e
REPORT RequestId: d3116be1-e3f9-402b-a460-468115ddd24e Duration: 7 ms Billed Duration: 100 ms Memory Size: 1536 MB Max Memory Used: 14 MB


{"stackTrace": [["/var/task/handler.py", 5, "hello", "return os.environ['SOME_ENV_VAR']"], ["/usr/lib64/python2.7/UserDict.py", 40, "__getitem__", "raise KeyError(key)"]], "errorType": "KeyError", "errorMessage": "'SOME_ENV_VAR'"}


  Error --------------------------------------------------

  1

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           10.11.0
     Serverless Version:     1.39.1
```

Similar or dependent issues:
* #5863

## Additional Data

* ***Serverless Framework Version you're using***:  1.39.1
* ***Operating System***:  mac OSX High Sierra
* ***Stack Trace***: Provided Above
* ***Provider Error messages***: Provided Above

**Comment by endeepak** [comment]
Same issue occurs when environment variables are passed as command line argument as well 
```
sls invoke local -f hello -e SOME_ENV_VAR=foo --docker
```
