### ISSUE TITLE
Issues using the MySQL NPM module (PROTOCOL_INCORRECT_PACKET_SEQUENCE)

### ISSUE THREAD

**Issue by ukon1990** [serverless/serverless#5946]
# This is a Bug Report

## Description
* What went wrong? 
The problem that I am having is that the nodejs mysql library works just fine, while using sls offline, but when I deploy I get the following error message from mysql: PROTOCOL_INCORRECT_PACKET_SEQUENCE

* What did you expect should have happened?
I would expect it to behave the same while deployed and locally.

* What was the config you used?
Mostly default.
* What stacktrace or error message from your provider did you see?
Just this error message from the mysql module: PROTOCOL_INCORRECT_PACKET_SEQUENCE

Similar or dependent issues:
I could not find any, that were not from 2015.

## Additional Data

NPM dependencies:
```
  "dependencies": {
    "mysql": "^2.16.0",
    "promise-throttle": "^1.0.0",
    "request": "^2.88.0",
    "request-promise": "^4.2.4",
    "zlib": "^1.0.5"
  },
  "devDependencies": {
    "@types/aws-lambda": "8.10.23",
    "@types/node": "^11.11.3",
    "serverless-offline": "^4.9.2",
    "serverless-webpack": "^5.2.0",
    "source-map-support": "^0.5.11",
    "ts-loader": "^5.3.3",
    "typescript": "^3.3.3333",
    "webpack": "^4.29.6"
  },
```

This is the class I use to handle database requests.
```.ts
import * as mysql from 'mysql';
import {DATABASE_CREDENTIALS} from '../secrets';
import {Connection, MysqlError} from 'mysql';

export class DatabaseUtil {
  connection: Connection;

  constructor() {
    this.connection = mysql.createConnection(DATABASE_CREDENTIALS);
  }

  query(query: string): Promise<any> {
    return new Promise<any>((resolve, reject) => {
      this.connection.query(query, (error: MysqlError, rows: any[]) => {
        this.connection.end();

        if (error) {
          reject({error: error, query: query});
          return;
        }

        resolve(rows);
      });
    });
  }
}

```

This is a part of the serverless.yml file:
```.yml
service:
  name: wah-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 720
  timeout: 900

functions:
  auctions:
    handler: controllers/auction.handler
    events:
      - http:
          method: post
          path: auction
          cors:
            origin: '*'

  items:
    handler: controllers/item.handler
    events:
      - http:
          method: any
          path: item
          cors:
            origin: '*'

      - http:
          method: any
          path: item/{id}
          cors:
            origin: '*'
```

* ***Serverless Framework Version you're using***: v1.39.1
* ***Operating System***: MacOS Mojave
* ***Stack Trace***:
```
Received packet in the wrong sequence.
at u._parsePacket (/var/task/controllers/webpack:/node_modules/mysql/lib/protocol/Protocol.js:270:1)
at u._onPacket [as write] (/var/task/controllers/webpack:/node_modules/mysql/lib/protocol/Parser.js:76:1)
at u.write (/var/task/controllers/webpack:/node_modules/mysql/lib/protocol/Protocol.js:38:1)
at Socket.write (/var/task/controllers/webpack:/node_modules/mysql/lib/Connection.js:91:1)
at Socket.apply (/var/task/controllers/webpack:/node_modules/mysql/lib/Connection.js:502:1)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at addChunk (_stream_readable.js:263:12)
at readableAddChunk (_stream_readable.js:250:11)
at Socket.Readable.push (_stream_readable.js:208:10)
at TCP.onread (net.js:607:20)
--------------------
at u._enqueue (/var/task/controllers/webpack:/node_modules/mysql/lib/protocol/Protocol.js:144:1)
at u._enqueue [as handshake] (/var/task/controllers/webpack:/node_modules/mysql/lib/protocol/Protocol.js:51:1)
at handshake [as connect] (/var/task/controllers/webpack:/node_modules/mysql/lib/Connection.js:118:1)
at connect (/var/task/controllers/webpack:/utils/database.util.ts:14:23)
at new Promise (<anonymous>)
at n.query (/var/task/controllers/webpack:/utils/database.util.ts:13:12)
at E.query (/var/task/controllers/webpack:/handlers/item.handler.ts:20:8)
at Generator.next (<anonymous>)
at item (/var/task/controllers/webpack:/utils/item.util.ts:19:12)
at new Promise (<anonymous>)
at item (/var/task/controllers/webpack:/utils/item.util.ts:19:12)
at E.callback [as getById] (/var/task/controllers/webpack:/handlers/item.handler.ts:17:41)
at Function.getById [as byId] (/var/task/controllers/webpack:/controllers/item.ts:21:27)
at byId (/var/task/controllers/webpack:/controllers/item.ts:8:20)
at invoke (/var/runtime/node_modules/awslambda/index.js:288:20)
at InvokeManager.start (/var/runtime/node_modules/awslambda/index.js:151:9)
at Object.awslambda.waitForInvoke (/var/runtime/node_modules/awslambda/index.js:499:52)
```
* ***Provider Error messages***: PROTOCOL_INCORRECT_PACKET_SEQUENCE

**Comment by ukon1990** [comment]
This is caused by webpack... So I am closing this issue.

If anyone else experiences the same.
Add the following in your webpack config exports:

optimization: {
        minimize: false
    }

**Comment by kshetline** [comment]
I recently ran into this issue myself, and discovered as well that minification was the problem. Minification can still be used, however, if `mangle` is set to `false`. I'd love to find out specifically what problems mysql has with minification, but unfortunately that project is closed to reporting issues, unless you are a contributor to the project.
