### ISSUE TITLE
AWS::ApiGateway::ApiKey and AWS::ApiGateway::UsagePlan depend on non-existing ApiGatewayDeployment resource

### ISSUE THREAD

**Issue by hsz** [serverless/serverless#5967]
# This is a Bug Report

## Description

* What went wrong?

When I have specified `provider.apiKeys` property, there are new resources created: `ApiGatewayApiKey1`, `ApiGatewayUsagePlan`.

Both depend on `ApiGatewayDeployment1553698403948` resource which is also created, but during deployment to AWS, it is not described in the Outputs, but the `ServiceEndpoint` is exposed instead (ref: https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/apiGateway/lib/deployment.js#L25)

Meanwhile `ApiGatewayApiKey1`, `ApiGatewayUsagePlan` located in the `Resources` still depend on the `ApiGatewayDeployment` which is not present in the CF template sent to S3 (as on the screenshot with diff):

![image](https://user-images.githubusercontent.com/108333/55132659-6a432000-5123-11e9-8c99-a706edc6c07e.png)

_left side: local cloudformation-template-update-stack.json; right side: CF from S3_

At the end, CloufFormation validate-template command fails with following error:

> An error occurred (ValidationError) when calling the ValidateTemplate operation: Template format error: Unresolved resource dependencies [ApiGatewayDeployment1553698403948] in the Resources block of the template

* What did you expect should have happened?

`ApiGatewayApiKey1`, `ApiGatewayUsagePlan` should depend on the existing resource.

* What was the config you used?

`provider.apiKeys` specified with `test` item.

* What stacktrace or error message from your provider did you see?

```
Error: The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [ApiGatewayDeployment1553698403948] in the Resources block of the template
    at provider.request.catch (/home/hsz/Projects/xxx/xxx-api/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:24:13)
From previous event:
    at AwsDeploy.validateTemplate (/home/hsz/Projects/xxx/xxx-api/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:19:12)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/home/hsz/Projects/xxx/xxx-api/node_modules/serverless/lib/plugins/aws/deploy/index.js:119:39)
From previous event:
    at Object.aws:deploy:deploy:validateTemplate [as hook] (/home/hsz/Projects/xxx/xxx-api/node_modules/serverless/lib/plugins/aws/deploy/index.js:115:10)
    at BbPromise.reduce (/home/hsz/Projects/xxx/xxx-api/node_modules/serverless/lib/classes/PluginManager.js:408:55)
From previous event:
    at PluginManager.invoke (/home/hsz/Projects/xxx/xxx-api/node_modules/serverless/lib/classes/PluginManager.js:408:22)
    at PluginManager.spawn (/home/hsz/Projects/xxx/xxx-api/node_modules/serverless/lib/classes/PluginManager.js:426:17)
    at AwsDeploy.BbPromise.bind.then (/home/hsz/Projects/xxx/xxx-api/node_modules/serverless/lib/plugins/aws/deploy/index.js:93:48)
From previous event:
    at Object.deploy:deploy [as hook] (/home/hsz/Projects/xxx/xxx-api/node_modules/serverless/lib/plugins/aws/deploy/index.js:89:10)
    at BbPromise.reduce (/home/hsz/Projects/xxx/xxx-api/node_modules/serverless/lib/classes/PluginManager.js:408:55)
From previous event:
    at PluginManager.invoke (/home/hsz/Projects/xxx/xxx-api/node_modules/serverless/lib/classes/PluginManager.js:408:22)
    at PluginManager.run (/home/hsz/Projects/xxx/xxx-api/node_modules/serverless/lib/classes/PluginManager.js:439:17)
    at variables.populateService.then (/home/hsz/Projects/xxx/xxx-api/node_modules/serverless/lib/Serverless.js:106:33)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Serverless.run (/home/hsz/Projects/xxx/xxx-api/node_modules/serverless/lib/Serverless.js:93:6)
    at serverless.init.then (/home/hsz/Projects/xxx/xxx-api/node_modules/serverless/bin/serverless:43:28)
    at /home/hsz/Projects/xxx/xxx-api/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/hsz/Projects/xxx/xxx-api/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at initializeErrorReporter.then (/home/hsz/Projects/xxx/xxx-api/node_modules/serverless/bin/serverless:43:6)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at /home/hsz/Projects/xxx/xxx-api/node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (/home/hsz/Projects/xxx/xxx-api/node_modules/serverless/bin/serverless:67:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at findNodeScript.then.existing (/home/hsz/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
    at <anonymous>
```

Similar or dependent issues:
* none

## Additional Data

* ***Serverless Framework Version you're using***: 1.39.1
* ***Operating System***: Ubuntu
* ***Stack Trace***: -
* ***Provider Error messages***: -

**Comment by hsz** [comment]
It appeared that this problem is caused by the `serverless-aws-alias` plugin:

https://github.com/HyperBrain/serverless-aws-alias/blob/master/lib/stackops/apiGateway.js#L172
