### ISSUE TITLE
Don't Enforce Project Bucket Naming Convention

### ISSUE THREAD

**Issue by erikerikson** [serverless/serverless#602]
I changed the projectBucket value in ~/_meta/variables/s-variables-common.js to the name of the bucket we will be using for our project.  It is a valid and existing bucket (but as reported below does not contain a region in its name).  Serverless should not have an opinion about what name I use for my bucket.

I issued the following command (note that I forgot the '-c' that I usually use) and get the error that follows it.

/.../project $sls stage create -s test -r us-west-2
Serverless: Creating stage "test"...  
Serverless: Creating region "us-west-2" in stage "test"...  
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^

ServerlessError: Project bucket does not contain a valid project region in its bucket name (us-east-1, us-west-2, eu-west-1, ap-northeast-1)
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/ServerlessError.js:17:11)
    at S3.sSetProjectBucketConfig (/usr/local/lib/node_modules/serverless/lib/utils/aws/S3.js:38:16)
    at S3.sCreateBucket (/usr/local/lib/node_modules/serverless/lib/utils/aws/S3.js:61:8)
    at RegionCreate._createProjectBucket (/usr/local/lib/node_modules/serverless/lib/actions/RegionCreate.js:195:24)
From previous event:
    at RegionCreate.regionCreate (/usr/local/lib/node_modules/serverless/lib/actions/RegionCreate.js:89:10)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:182:25
    at Array.reduce (native)
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:181:26)
    at Object.actions.(anonymous function) [as regionCreate] (/usr/local/lib/node_modules/serverless/lib/Serverless.js:382:20)
    at StageCreate._createRegion (/usr/local/lib/node_modules/serverless/lib/actions/StageCreate.js:220:30)
From previous event:
    at StageCreate.stageCreate (/usr/local/lib/node_modules/serverless/lib/actions/StageCreate.js:88:10)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:157:29
    at Array.reduce (native)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:156:30
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:154:10)
    at Serverless.actions.(anonymous function) (/usr/local/lib/node_modules/serverless/lib/Serverless.js:382:20)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:351:38)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:16:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

**Comment by ac360** [comment]
We do this because we need to know what region the bucket is in.  We could add more config to define which region the bucket is in...  but we have a lot of config already :(  Not sure what to do here.

**Comment by erikerikson** [comment]
...because buckets are created in regions that makes sense.

Would it maybe make more sense or just be less painful to have a project "home region" (as opposed to a "bucket region" config item) where all unique project related artifacts would be stored?  Is the plan instead that there would be region specific buckets for a cross-region project into which all resources would be replicated?  I'd think not as I believe that the purpose of the bucket is only deployment sourcing and history.

The problem for our teams is that we don't control bucket creation, those buckets are created for us according to a naming standard.

On that subject, we have a pain point in the lack of separation of bucket creation and bucket folder creation/population.  (we're doing the latter manually but this doesn't scale well)  Once the bucket is created for us, we have rights to do whatever we like inside of the bucket.  As such, if those two phases could be separated, it'd be nice to have (although not necessary).  I could try and PR it but it wouldn't be a priority.

p.s. better title, thanks

**Comment by brentax** [comment]
I'll add a +1 to @erikerikson's point above. I am starting a Serverless project using an existing AWS account with my company. We already have well established IAM roles and policies as well as S3 buckets. As a result, I am starting the project with the `-c true` option and deploying it later.

- Start project using `-c true` option
- `sls resources deploy` to set everything up
- `sls function deploy` - this one fails with a "The specified key does not exist." error

After running deploy again with `--debug`, I realized it was trying to download from S3 `.../envVars/.env` which wasn't there, because I hadn't deployed yet. It doesn't seem right for deployment to depend on the same thing already being deployed.

I was able to workaround by manually uploading the `.env` file, but it took me a while to figure out the actual problem.

**Comment by ac360** [comment]
I think the answer here is we keep the name convention default, but you can use whatever name you would like as long as you have a `HOME_REGION` set.

**Comment by eahefnawy** [comment]
I've made a tiny push to implement this fix. Just like @ac360 described, it'll first check if there's a `projectBucketRegion` variable set, if not we'll get the region from the default bucket name.

However, I think part of @erikerikson requirements is to have complete control over the bucket name, so this should include not prefixing the `serverless` keyword to bucket names by default, not just the region. Not sure what to do there, but I think what @erikerikson really needs is the ability to type **the exact** bucket name on `sls project create` (not just the domain name)

**Comment by erikerikson** [comment]
@eahefnawy is correct.  we have a bucket name that is preset by an external team.  we do not have the power to allow a prefix of "serverless".  I don't mind substituting my bucket's name in the config files at all but it would be a little more discoverable for others with my circumstance if the bucket was let auto-created and specified.

**Comment by eahefnawy** [comment]
@erikerikson thanks a lot for your feedback. Starting in v0.5, you'll be able to specify the exact bucket name (not the domain) when you create a project.

Closing...

**Comment by erikerikson** [comment]
Thanks @eahefnawy!
