### ISSUE TITLE
Docker args not working properly.

### ISSUE THREAD

**Issue by Frikitrok** [serverless/serverless#6083]
# This is a Bug Report

## Description

* What went wrong?

"sls invoke local --function --docker --docker-arg "-e AWS_ACCESS_KEY_ID=***" --docker-arg "-e AWS_SECRET_ACCESS_KEY=***" returning error 'dockerArgOption.split is not a function'

* What did you expect should have happened?

Should proper execute lambci container with docker args passed.

* What was the config you used?

sls invoke local --function --docker --docker-arg "-e AWS_ACCESS_KEY_ID=***" --docker-arg "-e AWS_SECRET_ACCESS_KEY=***"

* What stacktrace or error message from your provider did you see?

Type Error ---------------------------------------------
 
  dockerArgOption.split is not a function
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
TypeError: dockerArgOption.split is not a function
    at _.flatMap (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:370:42)
    at arrayMap (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:639:23)
    at map (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:9556:14)
    at Function.flatMap (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:9259:26)
    at AwsInvokeLocal.getDockerArgsFromOptions (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:369:37)
    at BbPromise (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:353:46)
    at BbPromise.all.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:344:28)
From previous event:
    at serverless.pluginManager.spawn.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:344:10)
From previous event:
    at AwsInvokeLocal.invokeLocalDocker (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:337:59)
    at AwsInvokeLocal.invokeLocal (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:151:19)
From previous event:
    at Object.invoke:local:invoke [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:34:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:408:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:408:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:439:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:109:33)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:96:6)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:43:28)
    at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
    at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
From previous event:
    at initializeErrorReporter.then (/usr/local/lib/node_modules/serverless/bin/serverless:43:6)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at /usr/local/lib/node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:65:4)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
1.41.1
* ***Operating System***:
linux
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by KaiqueBressi** [comment]
The same problem happened to me i resolved using an equal, instead of: `docker-arg "myarg=arg"` i used `docker-arg="myarg=arg"` and everything worked fine

**Comment by KaiqueBressi** [comment]
@pmuens I discovered the root of this problem, the dependency `mimist` is causing this, when you use the following args: 

`serverless invoke local --function myFunction --docker --docker-arg "--myarg arg"` 

The result of `options` object is:

`{ 
    function: 'myFunction',
    docker: true,
    'docker-arg': true,
    'myarg arg': true
}`

The `"` should be escaped and `docker-arg` should contain the `--myarg arg` but this is not what is happening. I tried to check `minimist` and open a PR to fix this but the project is not maintaned anymore. 

I recommend to use `yargs-parser`, it works just like `minimist` but it's still maintaned and does not have the problem with escaped arguments.

**Comment by marcinczeczko** [comment]
Any update on this ? It's essential to provide docker params e.g. with the docker network to establish communication with other AWS services on docker (e.g. dynamodb)

**Comment by voroninman** [comment]
I'm seeing the same problem but for version 1.77.1.

**Comment by voroninman** [comment]
`--docker-arg="--network foo"` works for me.
