### ISSUE TITLE
Proxy issue

### ISSUE THREAD

**Issue by abk-code** [serverless/serverless#6109]
# This is a Bug Report

## Description

* What went wrong?
serverless deploy failed due to proxy issue.
* What did you expect should have happened?
Should have deployed the lambda.

* What was the config you used?
`service: data-ingestion

frameworkVersion: ">=1.34.0"

custom:
  pythonRequirements:
    layer: true
    slim: true
    dockerizePip: true`

* What stacktrace or error message from your provider did you see?
`
  Stack Trace --------------------------------------------

Error:   Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:1056)'))': /simple/certifi/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:1056)'))': /simple/certifi/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:1056)'))': /simple/certifi/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:1056)'))': /simple/certifi/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:1056)'))': /simple/certifi/
  Could not find a version that satisfies the requirement certifi==2019.3.9 (from -r /var/task/requirements.txt (line 1)) (from versions: )
No matching distribution found for certifi==2019.3.9 (from -r /var/task/requirements.txt (line 1))

    at filterCommands.forEach (/Users/eqr671/node_modules/serverless-python-requirements/lib/pip.js:303:13)
    at Array.forEach (<anonymous>)
    at installRequirements (/Users/eqr671/node_modules/serverless-python-requirements/lib/pip.js:290:28)
    at installRequirementsIfNeeded (/Users/eqr671/node_modules/serverless-python-requirements/lib/pip.js:515:3)
    at ServerlessPythonRequirements.installAllRequirements (/Users/eqr671/node_modules/serverless-python-requirements/lib/pip.js:594:29)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:408:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:426:17)
    at Deploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:122:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:107:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:408:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:408:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:439:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:109:33)
    at processImmediate (timers.js:637:19)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:96:6)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:43:28)
    at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
    at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.args [as oncomplete] (fs.js:146:20)
From previous event:
    at initializeErrorReporter.then (/usr/local/lib/node_modules/serverless/bin/serverless:43:6)
    at processImmediate (timers.js:637:19)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at /usr/local/lib/node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:65:4)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:797:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)
    at startMainThreadExecution (internal/bootstrap/node.js:439:3)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     OS:                     darwin
     Node Version:           11.9.0
     Serverless Version:     1.41.1
`
Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***: 1.41.1
* ***Operating System***: darwin
* ***Stack Trace***: 
* ***Provider Error messages***:

**Comment by ycp424c** [comment]
i got the same problem, gotta switch network hundred  times a day -.-
