### ISSUE TITLE
Serverless fail to install globally at postinstall script: Cannot find module 'combined-stream'

### ISSUE THREAD

**Issue by rafaelff** [serverless/serverless#6159]
## Description

* What went wrong?
Tried to install serverless globally inside a Docker container but it failed at the postinstall script.
* What did you expect should have happened?
Expected serverless to install without errors.
* What was the config you used?
None, just executed `npm install -g serverless`
* What stacktrace or error message from your provider did you see?
```
npm info lifecycle serverless@1.43.0~postinstall: serverless@1.43.0

serverless@1.43.0 postinstall /usr/local/lib/node_modules/serverless
node ./scripts/postinstall.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'combined-stream'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/form-data/lib/form_data.js:1:84)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/superagent/lib/node/index.js:9:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
npm info lifecycle serverless@1.43.0~postinstall: Failed to exec postinstall script

```

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.43.0
* ***Operating System***:
docker container `from node:8.1.3`
running inside a windows 10 x64 machine
dell inspiron 7580

* ***Stack Trace***:

When running `npm install -g serverless`

```
npm info lifecycle serverless@1.43.0~postinstall: serverless@1.43.0

serverless@1.43.0 postinstall /usr/local/lib/node_modules/serverless
node ./scripts/postinstall.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'combined-stream'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/form-data/lib/form_data.js:1:84)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/superagent/lib/node/index.js:9:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
npm info lifecycle serverless@1.43.0~postinstall: Failed to exec postinstall script
```

When running `npm install -g serverless@1.41.1`

```
npm info lifecycle serverless@1.41.1~postinstall: serverless@1.41.1

serverless@1.41.1 postinstall /usr/local/lib/node_modules/serverless
node ./scripts/postinstall.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'combined-stream'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/form-data/lib/form_data.js:1:84)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/superagent/lib/node/index.js:9:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
npm info lifecycle serverless@1.41.1~postinstall: Failed to exec postinstall script

```

* ***Provider Error messages***:

**Comment by gabyquiles** [comment]
I was having the same problem. At the end, what I did was to install it locally (npm install serverless) and run `export PATH=$PATH:<project_folder>/node_modules/.bin`. For me it doesn't matter where to install it. I'm using the docker as a way to group multiple steps to build a lambda.
