### ISSUE TITLE
Excluding development dependencies fails on symlink in gotest.tools

### ISSUE THREAD

**Issue by MatthewY-Circle** [serverless/serverless#6220]
# This is a Bug Report

## Description

* What went wrong?
Attempting to `serverless package` a golang project with the gotest.tools package fails when trying to exclude the gotest.tools package as a dev dependency
* What did you expect should have happened?
Package should succeed
* What was the config you used?
`(export SLS_DEBUG=* && serverless package)`
* What stacktrace or error message from your provider did you see?
```
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
 
  Error --------------------------------------------------
 
  ENOENT: no such file or directory, open '/Users/matthew/scratch/symlink-iss/vendor/gotest.tools/fs/testdata/copy-test-with-symlink/a/b/2'
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: ENOENT: no such file or directory, open '/Users/matthew/scratch/symlink-iss/vendor/gotest.tools/fs/testdata/copy-test-with-symlink/a/b/2'
    at Package.getFileContent (/usr/local/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:130:15)
    at Package.getFileContentAndStat (/usr/local/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:119:12)
    at Array.map (<anonymous>)
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:91:29)
    at WriteStream.emit (events.js:200:13)
    at WriteStream.EventEmitter.emit (domain.js:471:20)
    at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:231:14
    at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:258:16
    at FSReqCallback.oncomplete (fs.js:137:23)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     OS:                     darwin
     Node Version:           12.3.1
     Serverless Version:     1.44.1
```

```
service: svc

frameworkVersion: "=1.44.1"

provider:
  name: aws
  runtime: go1.x
  profile: ex-dev
  region: us-west-2

functions:
  return-api-gateway:
    handler: exhad
    events:
      - http: post path/
```

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.44.1
* ***Operating System***: OSX Mavericks
* ***Stack Trace***:
```
Error: ENOENT: no such file or directory, open '/Users/matthew/scratch/symlink-iss/vendor/gotest.tools/fs/testdata/copy-test-with-symlink/a/b/2'
    at Package.getFileContent (/usr/local/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:130:15)
    at Package.getFileContentAndStat (/usr/local/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:119:12)
    at Array.map (<anonymous>)
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:91:29)
    at WriteStream.emit (events.js:200:13)
    at WriteStream.EventEmitter.emit (domain.js:471:20)
    at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:231:14
    at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:258:16
    at FSReqCallback.oncomplete (fs.js:137:23)
```
* ***Provider Error messages***:
N/A
* ***gopkg.toml***:
```
[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.9.0"
```

**Comment by MatthewY-Circle** [comment]
Symlink handling seems to be an issue, but I realized that this can be easily solved with a `package` `exclude`.

**Comment by sshaw** [comment]
Having same issue in  1.51.0:


```
Serverless: Excluding development dependencies...

  Error --------------------------------------------------

  ENOENT: no such file or directory, open '/Users/sshaw/code/js/amaaaaazing-app/.#app.js'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           10.15.3
     Serverless Version:     1.51.0 
```


This lockfile was created by emacs:

```
lrwxr-xr-x    1 sshaw  staff    24B Oct  2 21:20 .#app.js@ -> sshaw@sshaws-MBP-2.18452
```

`sshaw@sshaws-MBP-2.18452` does not exist, it's the "lock value". 

My `serverless.yml` contains: 

```yml
package:
  include:
    - lambda.js
    - app.js
    - package.json
    - package-lock.json
```

But appears that it's not respected.
