### ISSUE TITLE
Getting error while running at local

### ISSUE THREAD

**Issue by amanagrawal9** [serverless/serverless#6227]
I am getting this error while running at local. Can anyone please help?

`$ env-cmd .env serverless offline start
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command create_domain
Serverless: Load command delete_domain
Serverless: Load command webpack
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Invoke offline:start

  Error --------------------------------------------------

  Command failed: git write-tree

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: Command failed: git write-tree

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at PluginManager.invoke (C:\Users\Aman\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:446:22)
    at PluginManager.run (C:\Users\Aman\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:477:17)
    at variables.populateService.then (C:\Users\Aman\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:110:33)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Serverless.run (C:\Users\Aman\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:97:6)
    at serverless.init.then (C:\Users\Aman\AppData\Roaming\npm\node_modules\serverless\bin\serverless:43:28)
    at C:\Users\Aman\AppData\Roaming\npm\node_modules\serverless\node_modules\graceful-fs\graceful-fs.js:111:16
    at C:\Users\Aman\AppData\Roaming\npm\node_modules\serverless\node_modules\graceful-fs\graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at initializeErrorReporter.then (C:\Users\Aman\AppData\Roaming\npm\node_modules\serverless\bin\serverless:43:6)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at C:\Users\Aman\AppData\Roaming\npm\node_modules\serverless\bin\serverless:28:46
    at Object.<anonymous> (C:\Users\Aman\AppData\Roaming\npm\node_modules\serverless\bin\serverless:65:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     OS:                     win32
     Node Version:           8.11.1
     Serverless Version:     1.44.1

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by atz** [comment]
You lost some formatting in the post there.

For me, similar failure occurs during `serverless package` or `serverless install`:
- `Command failed: git write-tree`
- `Command failed: git rev-parse --short HEAD`

The stack trace suggests a plugin of some kind is involved.  In our case, the error seems to be from `serverless-plugin-git-variables`, as ticketed [here](https://github.com/jacob-meacham/serverless-plugin-git-variables/issues/25).  

@amanagrawal9 Are you using the same plugin?
  
```
  Your Environment Information ---------------------------
     OS:                     darwin
     Node Version:           10.15.1
     Serverless Version:     1.40.0
```

**Comment by amanagrawal9** [comment]
Thanks for replying, @atz .

Yes I am using the same plugin serverless-plugin-git-variables

**Comment by amanagrawal9** [comment]
@atz how can we resolve it??

**Comment by atz** [comment]
@amanagrawal9 Looks like version 3.3.2 may help address this bug:
https://github.com/jacob-meacham/serverless-plugin-git-variables/pull/27

**Comment by pgrzesik** [comment]
Closing due to inactivity for over 2 years

**Comment by dineshbabu853** [comment]
@pgrzesik  Im facing the same error while trying to delpy using `sls deploy` command

Error Details:


 Error ---------------------------------------------------

  Error: npm.cmd ls -prod -json -depth=1 failed with code 1
      at ChildProcess.<anonymous> (C:\services\retail-service-platform\onboarding-service\node_modules\serverless-webpack\lib\utils.js:91:16)
      at ChildProcess.emit (node:events:513:28)
      at ChildProcess.emit (node:domain:489:12)
      at maybeClose (node:internal/child_process:1093:16)
      at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              16.17.1
     Framework Version:         2.72.3 (local)
     Plugin Version:            5.5.4
     SDK Version:               4.3.2
     Components Version:        3.18.2
