### ISSUE TITLE
Getting error while deploying node functions to azure functions

### ISSUE THREAD

**Issue by satvikkumar92** [serverless/serverless#6229]
# This is a Bug Report

## Description

* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

  Stack Trace --------------------------------------------
 
Error: queryA ESERVFAIL bb-fun-test-back.scm.azurewebsites.net
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:213:19)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:446:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:477:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:110:33)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:97:6)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:43:28)
    at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
    at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at initializeErrorReporter.then (/usr/local/lib/node_modules/serverless/bin/serverless:43:6)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at /usr/local/lib/node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:65:4)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     OS:                     darwin
     Node Version:           8.15.0
     Serverless Version:     1.44.1
 

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by tschellenbach** [comment]
Different error, same problem

Serverless: Creating function app: chatbot-tutorial

  Error --------------------------------------------------

  Long running operation failed with error: "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.".

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: Long running operation failed with error: "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.".
    at PollingState.getCloudError (/Users/thierry/workspace/chatbot-tutorial/node_modules/ms-rest-azure/lib/pollingState.js:127:17)
    at /Users/thierry/workspace/chatbot-tutorial/node_modules/ms-rest-azure/lib/azureServiceClient.js:156:38
    at /Users/thierry/workspace/chatbot-tutorial/node_modules/ms-rest-azure/node_modules/async/dist/async.js:958:16
    at next (/Users/thierry/workspace/chatbot-tutorial/node_modules/ms-rest-azure/node_modules/async/dist/async.js:5211:18)
    at /Users/thierry/workspace/chatbot-tutorial/node_modules/ms-rest-azure/lib/azureServiceClient.js:129:20
    at /Users/thierry/workspace/chatbot-tutorial/node_modules/ms-rest-azure/lib/azureServiceClient.js:183:5
    at /Users/thierry/workspace/chatbot-tutorial/node_modules/ms-rest-azure/lib/azureServiceClient.js:321:12
    at retryCallback (/Users/thierry/workspace/chatbot-tutorial/node_modules/ms-rest/lib/filters/systemErrorRetryPolicyFilter.js:89:9)
    at retryCallback (/Users/thierry/workspace/chatbot-tutorial/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:140:9)
    at /Users/thierry/workspace/chatbot-tutorial/node_modules/ms-rest/lib/filters/rpRegistrationFilter.js:59:14
    at handleRedirect (/Users/thierry/workspace/chatbot-tutorial/node_modules/ms-rest/lib/filters/redirectFilter.js:39:9)
    at /Users/thierry/workspace/chatbot-tutorial/node_modules/ms-rest/lib/filters/formDataFilter.js:23:14
    at Request._callback (/Users/thierry/workspace/chatbot-tutorial/node_modules/ms-rest/lib/requestPipeline.js:125:16)
    at Request.self.callback (/Users/thierry/workspace/chatbot-tutorial/node_modules/request/request.js:185:22)
    at Request.emit (events.js:203:13)
    at Request.EventEmitter.emit (domain.js:471:20)
    at Request.<anonymous> (/Users/thierry/workspace/chatbot-tutorial/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:208:15)
    at Request.EventEmitter.emit (domain.js:471:20)
    at IncomingMessage.<anonymous> (/Users/thierry/workspace/chatbot-tutorial/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:291:20)
    at IncomingMessage.emit (events.js:208:15)
    at IncomingMessage.EventEmitter.emit (domain.js:471:20)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
From previous event:
    at PluginManager.invoke (/Users/thierry/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:464:22)
    at PluginManager.run (/Users/thierry/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:496:17)
    at /Users/thierry/.config/yarn/global/node_modules/serverless/lib/Serverless.js:116:33
    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:126:23)
From previous event:
    at Serverless.run (/Users/thierry/.config/yarn/global/node_modules/serverless/lib/Serverless.js:103:74)
    at /Users/thierry/.config/yarn/global/node_modules/serverless/bin/serverless.js:44:32
    at /Users/thierry/.config/yarn/global/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/thierry/.config/yarn/global/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.oncomplete (fs.js:153:23)
From previous event:
    at /Users/thierry/.config/yarn/global/node_modules/serverless/bin/serverless.js:44:10
    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:126:23)
From previous event:
    at /Users/thierry/.config/yarn/global/node_modules/serverless/bin/serverless.js:30:6
    at Object.<anonymous> (/Users/thierry/.config/yarn/global/node_modules/serverless/bin/serverless.js:71:7)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
    at internal/main/run_main_module.js:17:11

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     OS:                     darwin
     Node Version:           12.6.0
     Serverless Version:     1.47.0

**Comment by tschellenbach** [comment]
Haven't been able to work around this, is Azure known to be broken with serverless?
