### ISSUE TITLE
Post Install script fails with unexpected token with version 1.45.1 (works with 1.44.1)

### ISSUE THREAD

**Issue by bamapookie** [serverless/serverless#6257]
# This is a Bug Report

## Description

* What went wrong?
npm install serverless failed with the following error:

```
> serverless@1.45.1 postinstall /var/lib/jenkins/workspace/udformation_feature_load-testing/node_modules/serverless
> node ./scripts/postinstall.js

/var/lib/jenkins/workspace/udformation_feature_load-testing/node_modules/serverless/lib/classes/Service.js:53
    ]).then((args) => that.loadServiceFileParam(...args));
                                                ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/lib/jenkins/workspace/udformation_feature_load-testing/node_modules/serverless/lib/Serverless.js:14:17)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/lib/jenkins/workspace/udformation_feature_load-testing/node_modules/serverless/scripts/postinstall.js:7:20)
    at Module._compile (module.js:410:26)
```
* What did you expect should have happened?
Successful installation
* What was the config you used?
serverless.yml:
```
service: partner-creation-lambda

provider:
  name: aws
  runtime: nodejs6.10

functions:
  createPartner:
    handler: handler.createPartner
```
* What stacktrace or error message from your provider did you see?
Included in what went wrong section

## Additional Data

npm ERR! Linux 4.4.0-1083-aws
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "aws-sdk" "uuid" "serverless"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! serverless@1.45.1 postinstall: `node ./scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serverless@1.45.1 postinstall script 'node ./scripts/postinstall.js'.

[npm-debug.log](https://github.com/serverless/serverless/files/3290906/npm-debug.log)

**Comment by medikoo** [comment]
@bamapookie with v1.44.0 we dropped support for Node v4. Is there any specific reason you're stuck to it?

Upgrade at least to v6, and all will work fine

**Comment by bamapookie** [comment]
Not tied to it.  Just need to get ops to update Jenkins. :)

Thanks.
