### ISSUE TITLE
Error when invoking azure function

### ISSUE THREAD

**Issue by callmekatootie** [serverless/serverless#6264]
# This is a Bug Report

## Description

* What went wrong?
I tried to follow the quick start for azure. [Reference](https://serverless.com/framework/docs/providers/azure/guide/quick-start/). I was able to deploy the service successfully. However, when I tried to invoke the function using `serverless invoke -f hello`, I received an error:

```
Serverless: Logging in to Azure
 
  Error --------------------------------------------------
 
  [object Object]
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: [object Object]
    at module.exports.logError (/redacted/azure-services/node_modules/serverless/lib/classes/Error.js:92:11)
    at initializeErrorReporter.then.catch.e (/redacted/azure-services/node_modules/serverless/bin/serverless:64:3)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at /redacted/azure-services/node_modules/serverless/bin/serverless:62:9
    at Object.<anonymous> (/redacted/azure-services/node_modules/serverless/bin/serverless:65:4)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```
* What did you expect should have happened?
The function should have been invoked without errors
* What was the config you used?
I followed the quick start guide. [Reference](https://serverless.com/framework/docs/providers/azure/guide/quick-start/)
* What stacktrace or error message from your provider did you see?
Please see above

## Additional Data

* ***Serverless Framework Version you're using***:
1.45.1
* ***Operating System***:
Linux (Ubuntu 18.04)
* ***Stack Trace***:
Attached
* ***Provider Error messages***:
I debugged and the `[object Object]` turned out to be:

```
{
    "Message": "An error has occurred.",
    "ExceptionMessage": "Runtime keys are stored on blob storage. This API doesn't support this configuration. Please change Environment variable AzureWebJobsSecretStorageType value to 'Files'. For more info, visit https://aka.ms/funcsecrets",
    "ExceptionType": "System.InvalidOperationException",
    "StackTrace": "   at Kudu.Core.Functions.FunctionManager.<GetKeyObjectFromFile>d__9`1.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Functions\\FunctionManager.cs:line 141\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Kudu.Core.Functions.FunctionManager.<GetMasterKeyAsync>d__11.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Functions\\FunctionManager.cs:line 213\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Kudu.Services.Functions.FunctionController.<GetMasterKey>d__11.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Services\\Functions\\FunctionController.cs:line 121"
}
```

I understand that the error is asking me to set an environment variable, but looks like either the documentation or the code needs and update here.

**Comment by pmuens** [comment]
Hey @callmekatootie thanks for opening :+1:

It looks like this is related to the Azure provider plugin. Could you open up an issue in the plugins repository? Thanks!

**Comment by callmekatootie** [comment]
@pmuens Do you mean `serverless-azure-functions` plugin?

**Comment by callmekatootie** [comment]
nvm found the relevant issue: https://github.com/serverless/serverless-azure-functions/issues/128
