### ISSUE TITLE
AWS Lambda Handler Severless Invoke local : Class Not found

### ISSUE THREAD

**Issue by Raizencorp** [serverless/serverless#6277]
Hey Guys,

So I've been struggling on this since two weeks now ....

So i'm trying to make my handler encrypt some file and return me a string, the encrypt function just return a base64 string the one i want:

`public class Handler implements RequestHandler<Map<String, String>, String>{

	@Override
	public String handleRequest(Map<String, String> input, Context context) {
    	context.getLogger().log("Input: " + input);
    	
    	Response rep = new Response(input);
    	
    	String output = "File: " ;
    	String temp = rep.getType();
    	
    	if(temp.equals("pdf")) {
    		
    		output += Encrypt.encryptPDF(rep.getFile(), rep.getUserPwd(), rep.getOwnerPwd());
    	}
    	if(temp.equals("xlsx")) {
    		output += Encrypt.encryptXLSX(rep.getFile(), rep.getPassword(), rep.getFilename());
    	}
    	if(temp.equals("zip")) {
    		output += "OK";
    	}
    	
    	return output;
	}
}`

Here is my description of the handler on serverless.yml:

`functions:
  encrypt:
    handler: com.spinifexit.file.security.aws.Handler::handleRequest
`

And My issue when i try to invoke it on local:

`sls invoke local --function encrypt

Serverless: In order to get human-readable output, please implement "toString()" method of your "ApiGatewayResponse" object.

java.lang.ClassNotFoundException: com.spinifexit.file.security.aws.Handler

        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at com.serverless.InvokeBridge.getInstance(InvokeBridge.java:69)
        at com.serverless.InvokeBridge.<init>(InvokeBridge.java:37)
        at com.serverless.InvokeBridge.main(InvokeBridge.java:150)`

For now i'm not passing data yet but i already tryed with some still the same.

My Environment:
 -AWS Java SDK lambda    v1.11.546
 -AWS lambda java core    v1.2.0
 -JDK                                  v1.8.0_211

Thanks :)

**Comment by Raizencorp** [comment]
So with this pom.xml it fix the issue
`
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.serverless</groupId>
  <artifactId>demo</artifactId>
  <version>1.0.0</version>
  <packaging>jar</packaging>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.6.0</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
          <encoding>UTF-8</encoding>
          <forceJavacCompilerUse>true</forceJavacCompilerUse>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.0.0</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.amazonaws</groupId>
        <artifactId>aws-java-sdk-bom</artifactId>
        <version>1.11.577</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-lambda-java-events</artifactId>
      <version>1.3.0</version>
    </dependency>
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-lambda-java-core</artifactId>
      <version>1.1.0</version>
    </dependency>
  </dependencies>
</project>
`
But now i'm getting a 
`java.lang.SecurityException: Invalid signature file digest for Manifest main attributes

        at sun.security.util.SignatureFileVerifier.processImpl(Unknown Source)
        at sun.security.util.SignatureFileVerifier.process(Unknown Source)
        at java.util.jar.JarVerifier.processEntry(Unknown Source)
        at java.util.jar.JarVerifier.update(Unknown Source)
        at java.util.jar.JarFile.initializeVerifier(Unknown Source)
        at java.util.jar.JarFile.ensureInitialization(Unknown Source)
        at java.util.jar.JavaUtilJarAccessImpl.ensureInitialization(Unknown Source)
        at sun.misc.URLClassPath$JarLoader$2.getManifest(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at com.serverless.InvokeBridge.getInstance(InvokeBridge.java:69)
        at com.serverless.InvokeBridge.<init>(InvokeBridge.java:37)
        at com.serverless.InvokeBridge.main(InvokeBridge.java:150)`

**Comment by yyamano** [comment]
@Raizencorp I guess you need to exclude META-INF/*.{SF,DSA,RSA}. 

See http://zhentao-li.blogspot.com/2012/06/maven-shade-plugin-invalid-signature.html and https://maven.apache.org/plugins/maven-shade-plugin/examples/includes-excludes.html for more details.
