### ISSUE TITLE
Invoke local with Docker Toolbox throws an error

### ISSUE THREAD

**Issue by alexon1234** [serverless/serverless#6316]
# This is a Bug Report

## Description

- What went wrong?

When running `sls invoke local -f hello` in Windows 10 Home. It throws:
`docker: Error response from daemon: invalid mode: /var/task.`

- What is the reason? 

This error happen because the function `invokeLocalDocker()` takes the artifacth path 
```
const artifactPath = 'C:\\Users\\XXX\\Directory\\Project\\.serverless\\invokeLocal\\artifact'
```

and calls 
```
 const dockerArgs = _.concat([
            'run', '--rm', '-v', `${artifactPath}:/var/task`,
          ], envVarsDockerArgs, dockerArgsFromOptions, [
            imageName, handler, JSON.stringify(this.options.data),
          ]);
```
But in Docker Toolbox the path should be like:
```
const artifactPath = '//c/Users/XXX/Directory/Project/.serverless/invokeLocal/artifact'
```

## Additional Data

- **_Serverless Framework Version you're using_**:  1.46.0
- **_Operating System_**: win32
- **_Stack Trace_**:
- **_Provider Error messages_**:
```
docker: Error response from daemon: invalid mode: /var/task.
See 'docker run --help'.


  Error --------------------------------------------------

  125

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: 125
    at module.exports.logError (C:\Users\alexd\AppData\Roaming\npm\node_modules\serverless\lib\classes\Error.js:92:11)
    at initializeErrorReporter.then.catch.e (C:\Users\alexd\AppData\Roaming\npm\node_modules\serverless\bin\serverless:64:3)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at C:\Users\alexd\AppData\Roaming\npm\node_modules\serverless\bin\serverless:62:9
    at Object.<anonymous> (C:\Users\alexd\AppData\Roaming\npm\node_modules\serverless\bin\serverless:65:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     OS:                     win32
     Node Version:           8.11.2
     Serverless Version:     1.46.0
```

**Comment by alexon1234** [comment]
We could use a bash command like this `docker-machine ls | grep -q virtualbox1234 && echo $? || echo "Docker ToolBox not found";` to determine if is using virtualbox, so it needs the other path. But I need to still check it

**Comment by symbiotech** [comment]
@alexon1234 how can one avoid this error until this bug is fixed?

**Comment by alexon1234** [comment]
You can avoid this problem by using [Docker Desktop Edge version](https://docs.docker.com/docker-for-windows/edge-release-notes/).

This version allow users of Windows Home 10 be able to use Docker Desktop with WSL2 https://docs.docker.com/docker-for-windows/wsl-tech-preview/
