### ISSUE TITLE
Error deploying serverless - Error: ENOTEMPTY: directory not empty

### ISSUE THREAD

**Issue by Nilesh-TDSystems** [serverless/serverless#6348]
Error: ENOTEMPTY: directory not empty, rmdir 'E:\GitProjects\Hydra\1.5\HydraServices\services\PrinterService\.webpack\service'
    at Object.rmdirSync (fs.js:679:3)
    at rmkidsSync (E:\GitProjects\Hydra\1.5\HydraServices\services\PrinterService\node_modules\serverless-webpack\node_modules\fs-extra\lib\remove\rimraf.js:304:27)
    at rmdirSync (E:\GitProjects\Hydra\1.5\HydraServices\services\PrinterService\node_modules\serverless-webpack\node_modules\fs-extra\lib\remove\rimraf.js:281:7)
    at rimrafSync (E:\GitProjects\Hydra\1.5\HydraServices\services\PrinterService\node_modules\serverless-webpack\node_modules\fs-extra\lib\remove\rimraf.js:252:7)
    at options.readdirSync.forEach.f (E:\GitProjects\Hydra\1.5\HydraServices\services\PrinterService\node_modules\serverless-webpack\node_modules\fs-extra\lib\remove\rimraf.js:291:39)
    at Array.forEach (<anonymous>)
    at rmkidsSync (E:\GitProjects\Hydra\1.5\HydraServices\services\PrinterService\node_modules\serverless-webpack\node_modules\fs-extra\lib\remove\rimraf.js:291:26)
    at rmdirSync (E:\GitProjects\Hydra\1.5\HydraServices\services\PrinterService\node_modules\serverless-webpack\node_modules\fs-extra\lib\remove\rimraf.js:281:7)
    at Object.rimrafSync (E:\GitProjects\Hydra\1.5\HydraServices\services\PrinterService\node_modules\serverless-webpack\node_modules\fs-extra\lib\remove\rimraf.js:252:7)
    at ServerlessWebpack.cleanup (E:\GitProjects\Hydra\1.5\HydraServices\services\PrinterService\node_modules\serverless-webpack\lib\cleanup.js:14:13)
From previous event:
    at PluginManager.invoke (C:\Users\matkarin\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:446:22)
    at PluginManager.spawn (C:\Users\matkarin\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:464:17)
    at Deploy.BbPromise.bind.then (C:\Users\matkarin\AppData\Roaming\npm\node_modules\serverless\lib\plugins\deploy\deploy.js:122:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (C:\Users\matkarin\AppData\Roaming\npm\node_modules\serverless\lib\plugins\deploy\deploy.js:107:10)
    at BbPromise.reduce (C:\Users\matkarin\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:446:55)
From previous event:
    at PluginManager.invoke (C:\Users\matkarin\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:446:22)
    at PluginManager.run (C:\Users\matkarin\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:477:17)
    at variables.populateService.then (C:\Users\matkarin\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:112:33)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Serverless.run (C:\Users\matkarin\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:99:6)
    at serverless.init.then (C:\Users\matkarin\AppData\Roaming\npm\node_modules\serverless\bin\serverless:43:28)
    at C:\Users\matkarin\AppData\Roaming\npm\node_modules\serverless\node_modules\graceful-fs\graceful-fs.js:111:16
    at C:\Users\matkarin\AppData\Roaming\npm\node_modules\serverless\node_modules\graceful-fs\graceful-fs.js:45:10
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
From previous event:
    at initializeErrorReporter.then (C:\Users\matkarin\AppData\Roaming\npm\node_modules\serverless\bin\serverless:43:6)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at C:\Users\matkarin\AppData\Roaming\npm\node_modules\serverless\bin\serverless:28:46
    at Object.<anonymous> (C:\Users\matkarin\AppData\Roaming\npm\node_modules\serverless\bin\serverless:65:4)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     OS:                     win32
     Node Version:           10.15.3
     Serverless Version:     1.45.1

**Comment by medikoo** [comment]
@Nilesh-TDSystems By stack trace this looks as issue of [serverless-webpack](https://github.com/serverless-heaven/serverless-webpack) please post a bug report there
