### ISSUE TITLE
TypeError: Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by tnkteja** [serverless/serverless#6384]
I changed the serverless.yml file and ran the `sls offline --env local --apiKey` as a `npm script` and I get this following error. The sls command should have smoothly run the serveless and got me the instance.

## Additional Data
- **_Serverless Framework Version you're using_**: 1.46.1
- **_Operating System_**: win32
- **_Stack Trace_**:
  Type Error ---------------------------------------------

  Cannot read property 'toUpperCase' of undefined

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: Cannot read property 'toUpperCase' of undefined
    at fun.events.forEach.event (C:\Users\nktejat\service-zoho-quickbooks folder\service-zoho-quickbooks\node_modules\serverless-offline\src\index.js:485:40)
    at Array.forEach (<anonymous>)
    at Object.keys.forEach.key (C:\Users\nktejat\service-zoho-quickbooks folder\service-zoho-quickbooks\node_modules\serverless-offline\src\index.js:468:18)
    at Array.forEach (<anonymous>)
    at Offline._createRoutes (C:\Users\nktejat\service-zoho-quickbooks folder\service-zoho-quickbooks\node_modules\serverless-offline\src\index.js:432:41)
    at Offline._buildServer (C:\Users\nktejat\service-zoho-quickbooks folder\service-zoho-quickbooks\node_modules\serverless-offline\src\index.js:248:10)
    at Offline.start (C:\Users\nktejat\service-zoho-quickbooks folder\service-zoho-quickbooks\node_modules\serverless-offline\src\index.js:176:33)
    at Offline.startWithExplicitEnd (C:\Users\nktejat\service-zoho-quickbooks folder\service-zoho-quickbooks\node_modules\serverless-offline\src\index.js:188:17)
    at BbPromise.reduce (C:\Users\nktejat\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:448:55)
From previous event:
    at PluginManager.invoke (C:\Users\nktejat\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:448:22)
    at PluginManager.run (C:\Users\nktejat\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:479:17)
    at variables.populateService.then (C:\Users\nktejat\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:112:33)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
From previous event:
    at Serverless.run (C:\Users\nktejat\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:99:6)
    at serverless.init.then (C:\Users\nktejat\AppData\Roaming\npm\node_modules\serverless\bin\serverless:43:28)
    at C:\Users\nktejat\AppData\Roaming\npm\node_modules\serverless\node_modules\graceful-fs\graceful-fs.js:111:16
    at C:\Users\nktejat\AppData\Roaming\npm\node_modules\serverless\node_modules\graceful-fs\graceful-fs.js:45:10
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
From previous event:
    at initializeErrorReporter.then (C:\Users\nktejat\AppData\Roaming\npm\node_modules\serverless\bin\serverless:43:6)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
From previous event:
    at C:\Users\nktejat\AppData\Roaming\npm\node_modules\serverless\bin\serverless:28:46
    at Object.<anonymous> (C:\Users\nktejat\AppData\Roaming\npm\node_modules\serverless\bin\serverless:65:4)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
- **_Provider Error messages_**:

**Comment by tnkteja** [comment]
Issue at reading from serverless offilne, will close this issue here.
