### ISSUE TITLE
Severless should ignore empty AWS session token in credentials file

### ISSUE THREAD

**Issue by forzagreen** [serverless/serverless#6391]
## Description

Serverless commands that require authentication to AWS (e.g. `sls info`, `sls deploy` ...) are returning _The security token included in the request is invalid_, even if my AWS credentials are valid.

- Configuration:
`~/.aws/credentials` file:

```ini
[myprofile]
aws_access_key_id = xxxxx
aws_secret_access_key = xxxxx
aws_session_token = 
aws_security_token = 
```
I export `AWS_PROFILE=myprofile`, and I run `sls info`
Then I get the following error:
```
  Serverless Error ---------------------------------------
 
  The security token included in the request is invalid
 
  Stack Trace --------------------------------------------
 
ServerlessError: The security token included in the request is invalid
    at promise.catch.err (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:305:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
``` 

## Wordarounds

- From `~/.aws/credentials` remove lines with `aws_security_token` and `aws_security_token`:
```ini
[myprofile]
aws_access_key_id = xxxxx
aws_secret_access_key = xxxxx
```
- or comment them:
```ini
[myprofile]
aws_access_key_id = xxxxx
aws_secret_access_key = xxxxx
; aws_session_token = 
; aws_security_token = 
```

## Proposition

I think empty session_token and security_token should be ignored. It's already the case with the AWS CLI, and AWS SDKs (e.g. boto3).

**Comment by ChrisJBurns** [comment]
What is the status of this? Do we have to wait for approval from admin for go ahead to implement or can anyone just do the implementation and submit it?
