### ISSUE TITLE
1.48.1 Permissions Error

### ISSUE THREAD

**Issue by wooderz** [serverless/serverless#6413]
Getting the following when trying to install serverless using npm install serverless -g

```
npm WARN deprecated superagent@3.8.3: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.
/usr/bin/serverless -> /usr/lib/node_modules/serverless/bin/serverless.js
/usr/bin/slss -> /usr/lib/node_modules/serverless/bin/serverless.js
/usr/bin/sls -> /usr/lib/node_modules/serverless/bin/serverless.js

> spawn-sync@1.0.15 postinstall /usr/lib/node_modules/serverless/node_modules/spawn-sync
> node postinstall


> serverless@1.48.1 postinstall /usr/lib/node_modules/serverless
> node ./scripts/postinstall.js

Error: EACCES: permission denied, open '/root/.serverlessrc.3470832792'
    at Object.openSync (fs.js:443:3)
    at Function.writeFileSync [as sync] (/usr/lib/node_modules/serverless/node_modules/write-file-atomic/index.js:212:13)
    at createConfig (/usr/lib/node_modules/serverless/lib/utils/config/index.js:38:19)
    at getConfig (/usr/lib/node_modules/serverless/lib/utils/config/index.js:52:5)
    at Object.get (/usr/lib/node_modules/serverless/lib/utils/config/index.js:99:18)
    at Object.<anonymous> (/usr/lib/node_modules/serverless/lib/utils/isTrackingDisabled.js:5:30)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/lib/node_modules/serverless/lib/utils/tracking.js:11:28)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serverless@1.48.1 postinstall: `node ./scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serverless@1.48.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-19T20_36_34_668Z-debug.log
```

If I fix to @1.48.0 I do not get this issue

**Comment by ccain-hatchworks** [comment]
I am seeing the same thing since the update

**Comment by vibhuyadav** [comment]
Same error
```
[Container] 2019/07/19 20:55:23 Running command npm install -g serverless 
npm WARN deprecated superagent@3.8.3: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released. 
/usr/local/bin/serverless -> /usr/local/lib/node_modules/serverless/bin/serverless.js 
/usr/local/bin/slss -> /usr/local/lib/node_modules/serverless/bin/serverless.js 
/usr/local/bin/sls -> /usr/local/lib/node_modules/serverless/bin/serverless.js 
 
> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/serverless/node_modules/spawn-sync 
> node postinstall 
 
 
> serverless@1.48.1 postinstall /usr/local/lib/node_modules/serverless 
> node ./scripts/postinstall.js 
 
Error: EACCES: permission denied, open '/root/.serverlessrc.1336900051' 
    at Object.fs.openSync (fs.js:646:18) 
    at Function.writeFileSync [as sync] (/usr/local/lib/node_modules/serverless/node_modules/write-file-atomic/index.js:212:13) 
    at createConfig (/usr/local/lib/node_modules/serverless/lib/utils/config/index.js:38:19) 
    at getConfig (/usr/local/lib/node_modules/serverless/lib/utils/config/index.js:52:5) 
    at Object.get (/usr/local/lib/node_modules/serverless/lib/utils/config/index.js:99:18) 
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/lib/utils/isTrackingDisabled.js:5:30) 
    at Module._compile (module.js:653:30) 
    at Object.Module._extensions..js (module.js:664:10) 
    at Module.load (module.js:566:32) 
    at tryModuleLoad (module.js:506:12) 
    at Function.Module._load (module.js:498:3) 
    at Module.require (module.js:597:17) 
    at require (internal/module.js:11:18) 
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/lib/utils/tracking.js:11:28) 
    at Module._compile (module.js:653:30) 
    at Object.Module._extensions..js (module.js:664:10) 
npm ERR! code ELIFECYCLE 
npm ERR! errno 1 
npm ERR! serverless@1.48.1 postinstall: `node ./scripts/postinstall.js` 
npm ERR! Exit status 1 
npm ERR!  
npm ERR! Failed at the serverless@1.48.1 postinstall script. 
npm ERR! This is probably not a problem with npm. There is likely additional logging output above. 
 
npm ERR! A complete log of this run can be found in: 
npm ERR!     /root/.npm/_logs/2019-07-19T20_55_50_656Z-debug.log 
 
[Container] 2019/07/19 20:55:50 Command did not exit successfully npm install -g serverless exit status 1 
[Container] 2019/07/19 20:55:50 Phase complete: INSTALL State: FAILED 
```

**Comment by medikoo** [comment]
Great thanks for reporting.

Fix is here https://github.com/serverless/serverless/pull/6415, and will be published soon
