### ISSUE TITLE
IAMRoleApiGatewayLogs role name exceeds 64 characters

### ISSUE THREAD

**Issue by ricardolpd** [serverless/serverless#6425]
# This is a Bug Report
## Description

- What went wrong? Adding logs in Apigateway causes a role to be created with a name longer than 64
- What did you expect should have happened? The role name should have a name smaller or equal to 64.
- What was the config you used? 
  logs:
    restApi:
`      format: '{ "requestId":"$context.requestId", "ip": "$context.identity.sourceIp", "httpMethod":"$context.httpMethod", "resourcePath":"$context.resourcePath", "status":"$context.status" }'`
- What stacktrace or error message from your provider did you see?
Unhandled rejection ServerlessError: An error occurred: IamRoleApiGatewayLogs - 1 validation error detected: Value 'ecomm-sdhgs-primary-oauth-server-apiGatewayLogsRole-eu-west-1-apiGatewayLogsRole' at 'roleName' failed to satisfy constraint: Member must have length less than or equal to 64 (Service: AmazonIdentityManagement; Status Code: 400; Error Code: ValidationError; Request ID: c544b706-ac65-11e9-89dd-879d24923f1f).
    at provider.request.then.data (/Users/ricardoduarte/Source/Work/emar-oauth-server/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:121:33)
    at tryCatcher (/Users/ricardoduarte/Source/Work/emar-oauth-server/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/ricardoduarte/Source/Work/emar-oauth-server/node_modules/serverless/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Users/ricardoduarte/Source/Work/emar-oauth-server/node_modules/serverless/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/Users/ricardoduarte/Source/Work/emar-oauth-server/node_modules/serverless/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/Users/ricardoduarte/Source/Work/emar-oauth-server/node_modules/serverless/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/Users/ricardoduarte/Source/Work/emar-oauth-server/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/ricardoduarte/Source/Work/emar-oauth-server/node_modules/serverless/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/ricardoduarte/Source/Work/emar-oauth-server/node_modules/serverless/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/ricardoduarte/Source/Work/emar-oauth-server/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
Similar or dependent issues:

## Additional Data

- **_Serverless Framework Version you're using_**: 1.48.2
- **_Operating System_**: MAC OS
- **_Stack Trace_**:
- **_Provider Error messages_**:

In the output stack the name of logs the apiGatewayLogsRole is added twice for some reason, but this happens after the merge of resources in the stage.js

```
"IamRoleApiGatewayLogs": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "apigateway.amazonaws.com"
                ]
              },
              "Action": [
                "sts:AssumeRole"
              ]
            }
          ]
        },
        "ManagedPolicyArns": [
          "arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"
        ],
        "Path": "/",
        "RoleName": {
          "Fn::Join": [
            "-",
            [
              "ecomm-sdhgs-primary-oauth-server",
              "apiGatewayLogsRole",
              {
                "Ref": "AWS::Region"
              },
              "apiGatewayLogsRole"
            ]
          ]
        }
      }
    }
```

**Comment by ricardolpd** [comment]
Hey guys, could anyone read the defect above and provide some guidance as to the preferred way of fixing this defect. I am more than happy to fix it.

**Comment by bpressure** [comment]
easy manually fix: add a `iamRoleStatementsName` parameter and specify a short name yourself
