### ISSUE TITLE
Bitbucket deployment of new dashboard

### ISSUE THREAD

**Issue by sebastianarena** [serverless/serverless#6433]
I'm trying to use the new free dashboard with one of my projects.
When I set the `app` and `tenant` in `serverless.yml`, and at the same time trying to use `SERVERLESS_ACCESS_TOKEN` as env variable to have the serverless CLI access the dashboard using my credentials, I get an error.

Cross-reported to platform-sdk:
https://github.com/serverless/platform-sdk/issues/78

## Additional Data

- **_Serverless Framework Version you're using_**:
`1.48.2`

- **_Stack Trace_**:
```
Unhandled rejection Error: {"errorMessage":"Page not found"}
    at _callee$ (/opt/atlassian/pipelines/agent/build/node_modules/@serverless/platform-sdk/src/utils/checkHttpResponse.js:19:9)
    at tryCatch (/opt/atlassian/pipelines/agent/build/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/opt/atlassian/pipelines/agent/build/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/opt/atlassian/pipelines/agent/build/node_modules/regenerator-runtime/runtime.js:97:21)
    at step (/opt/atlassian/pipelines/agent/build/node_modules/@serverless/platform-sdk/dist/utils/checkHttpResponse.js:7:191)
    at /opt/atlassian/pipelines/agent/build/node_modules/@serverless/platform-sdk/dist/utils/checkHttpResponse.js:7:361
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by dschep** [comment]
Could you please run `sls --version` and post the info (it contains the versions of dependency we manage too)

**Comment by dschep** [comment]
And could you retry the build with the `SLS_DEBUG` env var set to something and post the error output. Thanks

**Comment by sebastianarena** [comment]
@dschep hello! thanks for replying.
By activating the SLS_DEBUG flag I could see what was the problem.
I had defined the `app` in `serverless.yml` like so:
`app: ${file(./serverless.js):app}`
Which seems is not replacing the real value just like the rest of the YAML.
If I hardcode the value... it seems to work! I need to check some more permissions that are now required, but its not stuck any more.

**Comment by dschep** [comment]
ah! Hmm. Not sure how easy a fix that'll be. We'll have to look into it. Glad you figured out a work around 👍

**Comment by sebastianarena** [comment]
@dschep I don't think its super necessary, but would be good to document that is not available... and after a few tweaks in the IAM policy to adjust for the new framework, I could deploy succesfully and have the Dashboard up and running! Awesome! Thanks!
