### ISSUE TITLE
Cannot read property 'Type' of null

### ISSUE THREAD

**Issue by Stdev17** [serverless/serverless#6464]
## Description

I was doing a deployment with renewing aws resources. According to a simillar issue, I double-checked my ymls' indentation but there was no problem. Local test with serverless-offline is working with no glitch. I am writing lambda codes and client-side codes in a same repository. Can this be the cause of the issue?

Similar or dependent issues:

- #5804

## Additional Data

- **_Serverless Framework Version you're using_**: 1.48.3 (Enterprise Plugin: 1.3.2, Platform SDK: 2.1.0)
- **_Operating System_**: Ubuntu 18.04.2 LTS
- **_Stack Trace_**:
```
SLS_DEBUG=* sls deploy         
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command s3deploy
Serverless: Load command s3eventremove
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: 
User stats error: Request network error: { FetchError: network timeout at: https://tracking.serverlessteam.com/v1/track
    at Timeout._onTimeout (/usr/local/lib/node_modules/serverless/node_modules/node-fetch/index.js:126:13)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)
  name: 'FetchError',
  message:
   'network timeout at: https://tracking.serverlessteam.com/v1/track',
  type: 'request-timeout' }
Serverless: 
User stats error: Request network error: { FetchError: network timeout at: https://tracking.serverlessteam.com/v1/track
    at Timeout._onTimeout (/usr/local/lib/node_modules/serverless/node_modules/node-fetch/index.js:126:13)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)
  name: 'FetchError',
  message:
   'network timeout at: https://tracking.serverlessteam.com/v1/track',
  type: 'request-timeout' }
Serverless: 
User stats error: Request network error: { FetchError: network timeout at: https://tracking.serverlessteam.com/v1/track
    at Timeout._onTimeout (/usr/local/lib/node_modules/serverless/node_modules/node-fetch/index.js:126:13)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)
  name: 'FetchError',
  message:
   'network timeout at: https://tracking.serverlessteam.com/v1/track',
  type: 'request-timeout' }
Serverless: 
User stats error: Request network error: { FetchError: network timeout at: https://tracking.serverlessteam.com/v1/track
    at Timeout._onTimeout (/usr/local/lib/node_modules/serverless/node_modules/node-fetch/index.js:126:13)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)
  name: 'FetchError',
  message:
   'network timeout at: https://tracking.serverlessteam.com/v1/track',
  type: 'request-timeout' }
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 200 0.189s 0 retries] describeStacks({ StackName: 'arenatime-dev' })
Serverless: [AWS cloudformation 200 0.098s 0 retries] describeStackResource({ StackName: 'arenatime-dev',
  LogicalResourceId: 'ServerlessDeploymentBucket' })
Serverless: [AWS s3 200 0.107s 0 retries] listObjectsV2({ Bucket: 'arenatime-dev-serverlessdeploymentbucket-1b64v6ulvo8dk',
  Prefix: 'serverless/arenatime/dev' })
Serverless: [AWS s3 200 0.08s 0 retries] headObject({ Bucket: 'arenatime-dev-serverlessdeploymentbucket-1b64v6ulvo8dk',
  Key:
   'serverless/arenatime/dev/1564201717946-2019-07-27T04:28:37.946Z/compiled-cloudformation-template.json' })
Serverless: [AWS s3 200 0.079s 0 retries] headObject({ Bucket: 'arenatime-dev-serverlessdeploymentbucket-1b64v6ulvo8dk',
  Key:
   'serverless/arenatime/dev/1564201717946-2019-07-27T04:28:37.946Z/arenatime.zip' })
Unhandled rejection TypeError: Cannot read property 'Type' of null
    at _.forEach (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/normalizeFiles.js:15:17)
    at /usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:4905:15
    at baseForOwn (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:2990:24)
    at /usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:4874:18
    at Function.forEach (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:9342:14)
    at Object.normalizeCloudFormationTemplate (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/normalizeFiles.js:9:7)
    at AwsDeploy.checkIfDeploymentIsNecessary (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/checkForChanges.js:104:45)
From previous event:
    at AwsDeploy.checkForChanges (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/checkForChanges.js:22:8)
From previous event:
    at Object.aws:deploy:deploy:checkForChanges [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:104:12)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:464:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:464:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:484:17)
    at AwsDeploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:93:48)
From previous event:
    at Object.deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:89:30)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:464:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:464:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:496:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:116:33)
    at processImmediate (internal/timers.js:443:21)
    at process.topLevelDomainCallback (domain.js:136:23)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:103:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless.js:52:28)
    at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
    at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.args [as oncomplete] (fs.js:145:20)
From previous event:
    at initializeErrorReporter.then (/usr/local/lib/node_modules/serverless/bin/serverless.js:52:6)
    at processImmediate (internal/timers.js:443:21)
    at process.topLevelDomainCallback (domain.js:136:23)
From previous event:
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless.js:38:39)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11

```
- **_Provider Error messages_**:

**Comment by Stdev17** [comment]
If I change stage from dev to prod, It throws same error with different logs, like
```
...
Serverless: 
User stats error: Request network error: { FetchError: network timeout at: https://tracking.serverlessteam.com/v1/track
    at Timeout._onTimeout (/usr/local/lib/node_modules/serverless/node_modules/node-fetch/index.js:126:13)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)
  name: 'FetchError',
  message:
   'network timeout at: https://tracking.serverlessteam.com/v1/track',
  type: 'request-timeout' }
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 400 0.174s 0 retries] describeStacks({ StackName: 'arenatime-prod' })
Serverless: Creating Stack...
Serverless: [AWS cloudformation 200 0.165s 0 retries] createStack({ StackName: 'arenatime-prod',
  OnFailure: 'DELETE',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateBody:
   '{"AWSTemplateFormatVersion":"2010-09-09","Description":"The AWS CloudFormation template for this Serverless application","Resources":{"ServerlessDeploymentBucket":{"Type":"AWS::S3::Bucket","Properties":{"BucketEncryption":{"ServerSideEncryptionConfiguration":[{"ServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}}}},"Outputs":{"ServerlessDeploymentBucketName":{"Value":{"Ref":"ServerlessDeploymentBucket"}}}}',
  Tags: [ { Key: 'STAGE', Value: 'prod' }, [length]: 1 ] })
Serverless: Checking Stack create progress...
Serverless: [AWS cloudformation 200 0.094s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:ap-northeast-2:527044138162:stack/arenatime-prod/0a175db0-b134-11e9-82de-0a2d74753dac' })
...Serverless: [AWS cloudformation 200 0.098s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:ap-northeast-2:527044138162:stack/arenatime-prod/0a175db0-b134-11e9-82de-0a2d74753dac' })
Serverless: [AWS cloudformation 200 0.088s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:ap-northeast-2:527044138162:stack/arenatime-prod/0a175db0-b134-11e9-82de-0a2d74753dac' })
Serverless: [AWS cloudformation 200 0.079s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:ap-northeast-2:527044138162:stack/arenatime-prod/0a175db0-b134-11e9-82de-0a2d74753dac' })
Serverless: [AWS cloudformation 200 0.099s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:ap-northeast-2:527044138162:stack/arenatime-prod/0a175db0-b134-11e9-82de-0a2d74753dac' })
.Serverless: [AWS cloudformation 200 0.078s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:ap-northeast-2:527044138162:stack/arenatime-prod/0a175db0-b134-11e9-82de-0a2d74753dac' })
.
Serverless: Stack create finished...
Serverless: [AWS cloudformation 200 0.102s 0 retries] describeStackResource({ StackName: 'arenatime-prod',
  LogicalResourceId: 'ServerlessDeploymentBucket' })
Serverless: [AWS s3 200 0.137s 0 retries] listObjectsV2({ Bucket: 'arenatime-prod-serverlessdeploymentbucket-mxs30tgcphak',
  Prefix: 'serverless/arenatime/prod' })
Serverless: [AWS sts 200 1.26s 0 retries] getCallerIdentity({})
Serverless: Uploading CloudFormation file to S3...
Unhandled rejection TypeError: Cannot read property 'Type' of null
...
```

**Comment by Stdev17** [comment]
Yes, It was the indentation issue that serverless-offline cannot found out. Sorry for submitting a redundant one.
