### ISSUE TITLE
python based lambda with dependency on github python package failing

### ISSUE THREAD

**Issue by sjatkins** [serverless/serverless#6495]
# This is a Bug Report

## Description

- What went wrong?
- What did you expect should have happened?
- What was the config you used?
- What stacktrace or error message from your provider did you see?

Similar or dependent issues:

- #12345

## Additional Data

- **_Serverless Framework Version you're using_**:
- **_Operating System_**:
- **_Stack Trace_**:
- **_Provider Error messages_**:

**Comment by sjatkins** [comment]
I see 
      ERROR: Command errored out with exit status 1:
     command: /home/samantha/work/everoyonesocial/reporting/ve/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/samantha/work/everoyonesocial/reporting/ve/src/pythoncommon/setup.py'"'"'; __file__='"'"'/home/samantha/work/everoyonesocial/reporting/ve/src/pythoncommon/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --home=/tmp/pip-target-5od7ui6s
         cwd: /home/samantha/work/everoyonesocial/reporting/ve/src/pythoncommon/
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

It is true that python, at least python3 setup.py develop does not have a "--home" option which seems to be what this wad of code is equivalent to.  

The rest of the debug traceback looks like:

    error: option --home not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/samantha/work/everoyonesocial/reporting/ve/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/samantha/work/everoyonesocial/reporting/ve/src/pythoncommon/setup.py'"'"'; __file__='"'"'/home/samantha/work/everoyonesocial/reporting/ve/src/pythoncommon/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --home=/tmp/pip-target-5od7ui6s Check the logs for full command output.

    at filterCommands.forEach (/home/samantha/work/everoyonesocial/reporting/node_modules/serverless-python-requirements/lib/pip.js:303:13)
    at Array.forEach (<anonymous>)
    at installRequirements (/home/samantha/work/everoyonesocial/reporting/node_modules/serverless-python-requirements/lib/pip.js:290:28)
    at installRequirementsIfNeeded (/home/samantha/work/everoyonesocial/reporting/node_modules/serverless-python-requirements/lib/pip.js:515:3)
    at ServerlessPythonRequirements.installAllRequirements (/home/samantha/work/everoyonesocial/reporting/node_modules/serverless-python-requirements/lib/pip.js:594:29)
From previous event:
    at PluginManager.invoke (/home/samantha/work/.nvm/versions/node/v10.14.1/lib/node_modules/serverless/lib/classes/PluginManager.js:448:22)
    at PluginManager.spawn (/home/samantha/work/.nvm/versions/node/v10.14.1/lib/node_modules/serverless/lib/classes/PluginManager.js:466:17)
    at Deploy.BbPromise.bind.then (/home/samantha/work/.nvm/versions/node/v10.14.1/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:122:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/home/samantha/work/.nvm/versions/node/v10.14.1/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:107:10)
    at BbPromise.reduce (/home/samantha/work/.nvm/versions/node/v10.14.1/lib/node_modules/serverless/lib/classes/PluginManager.js:448:55)
From previous event:
    at PluginManager.invoke (/home/samantha/work/.nvm/versions/node/v10.14.1/lib/node_modules/serverless/lib/classes/PluginManager.js:448:22)
    at PluginManager.run (/home/samantha/work/.nvm/versions/node/v10.14.1/lib/node_modules/serverless/lib/classes/PluginManager.js:479:17)
    at variables.populateService.then (/home/samantha/work/.nvm/versions/node/v10.14.1/lib/node_modules/serverless/lib/Serverless.js:112:33)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (/home/samantha/work/.nvm/versions/node/v10.14.1/lib/node_modules/serverless/lib/Serverless.js:99:6)
    at serverless.init.then (/home/samantha/work/.nvm/versions/node/v10.14.1/lib/node_modules/serverless/bin/serverless:43:28)
    at /home/samantha/work/.nvm/versions/node/v10.14.1/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
    at /home/samantha/work/.nvm/versions/node/v10.14.1/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at initializeErrorReporter.then (/home/samantha/work/.nvm/versions/node/v10.14.1/lib/node_modules/serverless/bin/serverless:43:6)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at /home/samantha/work/.nvm/versions/node/v10.14.1/lib/node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (/home/samantha/work/.nvm/versions/node/v10.14.1/lib/node_modules/serverless/bin/serverless:65:4)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
 
My requiremensts.txt has a line for the github based project in question like

-e git+git@github.com:some_org/python-common.git@d43adf6aeed6a4e0e5040bd40ebc573bdbd522e7#egg=PythonCommon

**Comment by sjatkins** [comment]
I was sort of hoping that if I deployed while in a suitable python virtualenv that it would just figure everything out relative to that virtualenv in force at the time and zip it up.  What it really does seems a bit more complicated and as seen here, prone to some breakage.

**Comment by sjatkins** [comment]
Making sure to have no python virtualenv active I get a somewhat different error.
Error: Command "/usr/bin/python3.6 -c "import setuptools, tokenize;__file__='/home/samantha/work/everoyonesocial/reporting/src/pythoncommon/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --home=/tmp/tmp0csahrz8" failed with error code 1 in /home/samantha/work/everoyonesocial/reporting/src/pythoncommon/

**Error code 1** being not at all helpful.

**Comment by sjatkins** [comment]
One thing that does work is to put:

> package: ..
   include:
     -myvirtenv/lib/python3.6/site_packages

**Comment by sjatkins** [comment]
**SIGH** Didn't work.  Not really using the myvenv included bits all though the site-packages are there in the zip.  **STILL STUCK**

**Comment by pmuens** [comment]
Hey @sjatkins thanks for opening :+1:

Could you share your `serverless.yml` file? Which plugins are you using?
