### ISSUE TITLE
"Runtime.ImportModuleError: Error: Cannot find module"

### ISSUE THREAD

**Issue by Craigson** [serverless/serverless#6529]
# This is a Bug Report

## Description

After successfully deploying my stack using `serverless deploy`, my lambda functions fail, citing a module import error `Runtime.ImportModuleError`.

Because I need binaries built specifically for linux, the packaging and deployment takes place inside a docker container, the docker file is as follows:

```
FROM lambci/lambda:build-nodejs10.x

ENV AWS_DEFAULT_REGION XXXX

ENV SERVERLESS_ACCESS_KEY XXXXXXXXXXXXXXXX

ENV AWS_ACCESS_KEY_ID XXXXXXXXXXXX
ENV AWS_SECRET_ACCESS_KEY XXXXXXXXXXXXXXX

RUN npm install -g serverless

WORKDIR /usr/src/app

COPY . .

RUN rm -rf node_modules

RUN npm install

CMD serverless deploy
```

The lambda's stack trace is as follows:

```
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 's-fetchUserData'",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module 's-fetchUserData'",
    "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:36:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:776:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)",
    "    at Module.load (internal/modules/cjs/loader.js:653:32)",
    "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
    "    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)",
    "    at startup (internal/bootstrap/node.js:283:19)"
  ]
}
```

If I download the `.zip` file from s3 for the deployment, I can see the `s_fetchUserData.js` file in the root of the project.

Here's the file tree:

```
.
├── Dockerfile
├── NOTES.md
├── README.md
├── docker-compose.yml
├── package-lock.json
├── package.json
├── s_fetchUserData.js
├── s_generateEmail.js
├── s_processGif.js
├── s_processPhoto.js
├── s_processTimelapseVideo.js
├── s_startExecution.js
├── serverless_sdk
│   └── index.js
└── src
    ├── handlers
    │   ├── email
    │   │   ├── handler.js
    │   │   └── mira.code-workspace
    │   ├── image-processing
    │   │   ├── gif
    │   │   │   └── handler.js
    │   │   └── photo
    │   │       └── handler.js
    │   ├── start
    │   │   └── handler.js
    │   ├── test
    │   │   └── handler.js
    │   ├── timelapse
    │   │   └── handler.js
    │   ├── upload
    │   │   └── handler.js
    │   ├── user
    │   │   └── handler.js
    │   └── video
    │       └── timelapse
    │           └── handler.js
    ├── templates
    │   └── email
    │       └── content.pug
    ├── test
    │   ├── email.json
    │   ├── index.html
    │   ├── locationData.json
    │   ├── processImage.json
    │   ├── pugRenderer.js
    │   ├── timelapse.json
    │   ├── timelapseVideo.json
    │   ├── user.json
    │   └── views
    │       ├── email-bg.svg
    │       └── index.pug
    └── utils
        └── index.js

19 directories, 35 files
```

**Comment by medikoo** [comment]
If you require `s-fetchUserData.js` by using `'s-fetchUserData'` require path, then naturally it fails, as it searches for  `s-fetchUserData` package in `node_modules`.

Node.js module resolution rules, require relative paths to resolve local modules. Therefore in this case I believe require path should be `'./s-fetchUserData'`

**Comment by Craigson** [comment]
This is handled automatically by serverless, so why the sudden failure? I haven't changed any mechanisms by which modules are imported.

**Comment by medikoo** [comment]
I don't think it could be Serverless. it reports wrong require is in `UserFunction.js` module, which is not part of Serverless Framework.

**Comment by medikoo** [comment]
Also this is Node.js error, it's not in Serverless Framework layer

**Comment by Craigson** [comment]
Correct me if I'm wrong, but serverless is responsible for generating the `s-fetchUserData.js` function from the handler I designate.  In no way am I responsible for importing this module in my code, so the error has to lie in the serverless packaging process? Otherwise is it a lambda-specific issue? I just don't see how it works for one deployment, then with no changes to the file structure, a subsequent deployment fails.

**Comment by medikoo** [comment]
> but serverless is responsible for generating the s-fetchUserData.js 

I'm not aware of that file. I don't think it's generated by Serverless Framework.

**Comment by Craigson** [comment]
Serverless generates the `s_fetchUserData.js` file, the contents of which looks like this:
```
var serverlessSDK = require('./serverless_sdk/index.js')
serverlessSDK = new serverlessSDK({
tenantId: 'XXXX',
applicationName: 'XXXXXXX',
appUid: 'XXXXXXXX',
tenantUid: 'XXXXXXXXXX',
deploymentUid: '20b85b69-5414-430e-8d7d-38864e94426b',
serviceName: 'XXXXXXX',
stageName: 'dev'})
const handlerWrapperArgs = { functionName: 'XXXXXXXXXX-dev-fetchUserData', timeout: 6}
try {
  const userHandler = require('./src/handlers/user/handler.js')
  module.exports.handler = serverlessSDK.handler(userHandler.fetchUserData, handlerWrapperArgs)
} catch (error) {
  module.exports.handler = serverlessSDK.handler(() => { throw error }, handlerWrapperArgs)
}

```

Which is setup in the serverless.yml file as follows:

```
functions:
  fetchUserData:
    handler: src/handlers/user/handler.fetchUserData
```

**Comment by medikoo** [comment]
> Serverless generates the s_fetchUserData.js file

Serverless doesn't generate it, maybe it's some plugin you use.

**Comment by medikoo** [comment]
If you search the Framework source code or files tree, you'll see no trace of `s_fetchUserData`

**Comment by leinonen** [comment]
I had the same problem. I was using folders under the handlers/functions folder with an index.js file in each folder.

The require-path to the actual function code is wrong in the serverless-generated (instrumentation wrapper) code. To fix it, put your handlers directly under the functions folder: `src/handlers/user.js`

Then in your `serverless.yml`-file:
```
functions:
  fetchUserData:
    handler: src/handlers/user.fetchUserData
```

If you run `serverless package` you can verify that everything is correct. Just open the zip-file and inspect the files starting with s_, and make sure the require statement points to the correct path.

**Comment by medikoo** [comment]
@leinonen is your error exactly same (`Error: Cannot find module 's-fetchUserData'` ?)

Can you paste the output of `sls --version` ?

**Comment by leinonen** [comment]
@medikoo, well. Not exactly the same. But the `Error: Cannot find module './functions/growth.js'`
But the actual handler was located at `functions/growth/index.js`, and in serverless it was referenced as `functions/growth.someFunction` which I later changed to `functions/growth/index.someFunction` and it resolved the problem. But the function worked before adding serverless monitoring

Framework Core: 1.54.0
Plugin: 3.1.2
SDK: 2.1.2
Components Core: 1.1.1
Components CLI: 1.4.0

**Comment by medikoo** [comment]
> @medikoo, well. Not exactly the same. But the Error: Cannot find module './functions/growth.js'

Ok, that makes a difference.

While ` Cannot find module 's-fetchUserData'` is an error that indicates a problem with our internals (`s-fetchUserData` is specific to [enterprise-plugin](https://github.com/serverless/enterprise-plugin/) which is unconditionally loaded by the Framework)

Error on your side looks as error in your setup (module path doesn't refer to anything Framework specific)

**Comment by edusenior12** [comment]
> I had the same problem. I was using sub-folders under the handlers/functions folder with an index.js

Same error for me, but my issue was that I was **prefixing the path to the handler function in serverless.yml with a forward slash** (i.e. handler: **/**src/file.handler_function). Removed the slash and it worked as expected (src/file.handler_function). Incredibly annoying since it worked not too long ago with it, but happy the change was simple. Your response helped me track down the cause.
