### ISSUE TITLE
Serverless not using kms key for sse S3 deployment bucket

### ISSUE THREAD

**Issue by atonvn** [serverless/serverless#6546]
# This is a Bug Report

## Description

- What went wrong?
- What did you expect should have happened?
- What was the config you used?
- What stacktrace or error message from your provider did you see?

Similar or dependent issues:

- #12345

## Additional Data

- **_Serverless Framework Version you're using_**:
- **_Operating System_**:
- **_Stack Trace_**:
- **_Provider Error messages_**:

I am trying to use serverless in a large security concious instition. There is an overall account service control policy (SCP) in place that locks down all putobject operations with the following JSON

{
            "Sid": "RequireKMSEncryption",
            "Effect": "Deny",
            "Action": "s3:PutObject",
            "Resource": "*",
            "Condition": {
                "StringNotLikeIfExists": {
                    "s3:x-amz-server-side-encryption-aws-kms-key-id": [
                        "arn:aws:kms:*:xxxxxx:key/*"
                    ]
                }
            }
        },

So to copy a file I have to use below (nothing else works)
aws s3 cp ./somefile s3://mybucket-cloudformation --sse aws:kms --sse-kms-key-id arn:aws:kms:eu-west-1:xxx:key/xxx --region eu-west-1

I'm trying a very basic HelloWorld app with Serverless and keep getting ServerlessError: Access Denied when trying to write to Deployment bucket:

Serverless: Uploading CloudFormation file to S3...
Serverless: [AWS s3 403 0.106s 0 retries] putObject({ Body: <Buffer 7b 22 41 57 53 54 65 6d 70 6c 61 74 65 46 6f 72 6d 61 74 56 65 72 73 69 6f 6e 22 3a 22 32 30 31 30 2d 30 39 2d 30 39 22 2c 22 44 65 73 63 72 69 70 74 ... >,
  Bucket: 'mybucket-cloudformation',
  Key: 'serverless/myapp/dev/1564572959404-2019-07-31T11:35:59.404Z/compiled-cloudformation-template.json',
  ContentType: 'application/json',
  Metadata: { filesha256: 'z1PKudUca3hTSM8s22qShpku9TqeJAUPDyEsv+KUoYQ=' },
  ServerSideEncryption: 'aws:kms' })
Unhandled rejection ServerlessError: Access Denied
    at promise.catch.err (/home/ec2-user/myapp-dev-70f4dc652774ee536d26324e95f4fd36524bfa44/rest/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:316:27)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)

In the serverless.yml file I have added the following section and also tried with customer parameter and have also tried many variations

deploymentBucket: 
    name: mybucket-cloudformation
    serverSideEncryption: aws:kms
    SSEKMSKeyId: arn:aws:kms:eu-west-1:xxx:key/xxx

It looks to me like serverless does not have the ability to use kms keys when addressing the S3 deployment bucket

**Comment by dschep** [comment]
Could you try casing the key id option like so: `sseKMSKeyId` (sse in lowercase)?

**Comment by atonvn** [comment]
Yes it solved it !!

I now get a similar error where it tries to read it again later

Serverless: Validating template...
Serverless: [AWS cloudformation 400 0.445s 0 retries] validateTemplate({ TemplateURL: 'https://s3.amazonaws.com/mybucket-cloudformation/serverless/myapp-rest/dev/1565878713242-2019-08-15T14:18:33.242Z/compiled-cloudformation-template.json' })
Unhandled rejection Error: The CloudFormation template is invalid: S3 error: Unable to get the object https://s3.amazonaws.com/mybucket-cloudformation/serverless/myapp-rest/dev/1565878713242-2019-08-15T14:18:33.242Z/compiled-cloudformation-template.json

**Comment by dschep** [comment]
Does the role you're deploying with have permission to `GetItem` from the s3 bucket?

**Comment by atonvn** [comment]
How can I confirm that role I'm deploying with? I am using a hardened AMI with a IAM role attached. I run serverless as the ec2-user which then uses this attached role right? Is there a way to set this role?
I think the ec2 attached role has all S3 rights but will confirm (I can do s3 cp and S3 putobject from commandline - would expect that getItem would also be allowed)

**Comment by atonvn** [comment]
I can confirm that the ec2 attached role has the S3 getObject permission (I cannot find getItem but I assume you mean getObject right?)

**Comment by dschep** [comment]
yes, the iam role attached to ec2-user is used

**Comment by atonvn** [comment]
There is a similar SCP in place that locks down read (getObject) etc operations  - must have KMS key

**Comment by dschep** [comment]
> There is a similar SCP in place that locks down read (getObject) etc operations - must have KMS key

could the SCP block CloudFormation from using the KMS key to getObject? (since that's what's actually getting the template from S3)

**Comment by adamyodinsky** [comment]
I'm having an issue with using KMS key for the deployment bucket as well.

```yaml
provider:
  deploymentBucket:
    serverSideEncryption: "aws:kms"
    sseKMSKeyId: "alias/aws/s3" 
```
    
    
Getting in the update stack file (cloudformation-template-update-stack.json)

```json
"Resources": {
    "ServerlessDeploymentBucket": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "BucketEncryption": {
          "ServerSideEncryptionConfiguration": [
            {
              "ServerSideEncryptionByDefault": {
                "SSEAlgorithm": "AES256"
              }
            }
            ...
```

serverless --version:
```
    Framework Core: 3.27.0 (local) 3.20.0 (global)
    Plugin: 6.2.3
    SDK: 4.3.2
```

Am I missing something?
