### ISSUE TITLE
"Your identity does not match the specified user"

### ISSUE THREAD

**Issue by clovis1122** [serverless/serverless#6573]
# This is a Bug Report

## Description

- What went wrong?
I can't use the framework at all. When I first installed it and ran `serverless`, it prompted me to either log in or register. I choosed "log in" and since then I get this error everytime:

![image](https://user-images.githubusercontent.com/22270042/63477754-a5d4e280-c454-11e9-82a6-b3dd2331abe2.png)

- What did you expect should have happened?
Should be able to use the framework as normal.

- What was the config you used?
See screenshot.

- What stacktrace or error message from your provider did you see?
See screenshot.

Similar or dependent issues:

- #12345

## Additional Data

- **_Serverless Framework Version you're using_**: latest
- **_Operating System_**: Mac Os
- **_Stack Trace_**: See screenshot
- **_Provider Error messages_**: See screenshot

**Comment by dschep** [comment]
Could you email(you don't want to post it publicly 😉) me your `~/.serverlessrc` file at daniel@serverless.com so I can help debug? Then you can delete it and `serverless` should work again and you can try to log in again.

**Comment by clovis1122** [comment]
Thanks, `rm ~/.serverlessrc && serverless` did the trick.

**Comment by tomwarham** [comment]
Having this same issue, tried removing the `~/.serverlessrc` file with no luck, keeps throwing the same error as OP 

```  Error --------------------------------------------------
 
  Error: {"errorMessage":"Your identity does not match the specified user. - Please contact support and provide this identifier to reference this issue - 4VJB546VPTXR"}
      at _callee$ (/Users/tomwarham/.nvm/versions/node/v12.2.0/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/src/utils/checkHttpResponse.js:19:9)
      at tryCatch (/Users/tomwarham/.nvm/versions/node/v12.2.0/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (/Users/tomwarham/.nvm/versions/node/v12.2.0/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.<computed> [as next] (/Users/tomwarham/.nvm/versions/node/v12.2.0/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:97:21)
      at step (/Users/tomwarham/.nvm/versions/node/v12.2.0/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/dist/utils/checkHttpResponse.js:7:191)
      at /Users/tomwarham/.nvm/versions/node/v12.2.0/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/dist/utils/checkHttpResponse.js:7:361
      at processTicksAndRejections (internal/process/task_queues.js:89:5)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.2.0
     Framework Version:         1.56.1
     Plugin Version:            3.2.1
     SDK Version:               2.2.0
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0```

**Comment by amgo100** [comment]
I experienced the same issue just now. Automatically created `.serverlessrc` contained an extra dot (as I have in my email) in the username. Removing it fixed the issue.

**Comment by princepathria97** [comment]
There's a bug in setting up `.serverlessrc` with `serverless login` command. It doesn't pick the actual username of the account. It rather picks suggested username(during signup).

User-end fix:
manually edit the username in your .serverlessrc to the correct username.

**Comment by sertaco** [comment]
this explained it all. thanks

**Comment by paulschneider** [comment]
I'm also running into this today (no issues yesterday). Removing the ~/.serverlessrc and re-logging in seems to work but I'm now getting :

`Error: {"errorMessage":"Tenant not found. - Please contact support and provide this identifier to reference this issue - 5VQRXDJXJHGC"}`

Currently not able to get past this.

**Comment by JorneDelforge** [comment]
Running into the same issue. Tried deleting ~/.serverlessrc and running serverless login again, but no luck. Tried editing the ~/.serverlessrc manually, but it's unclear to me what the required manipulation would be.

`Project successfully created in 'test3' folder.
 
  Error --------------------------------------------------
 
  Error: {"errorMessage":"Your identity does not match the specified user. - Please contact support and provide this identifier to reference this issue - 5VRNCRVV98FY"}
      at _callee$ (/usr/local/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/src/utils/checkHttpResponse.js:19:9)
      at tryCatch (/usr/local/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.<computed> [as next] (/usr/local/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:97:21)
      at step (/usr/local/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/dist/utils/checkHttpResponse.js:7:191)
      at /usr/local/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/dist/utils/checkHttpResponse.js:7:361
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.`

**Comment by MickeyMcc** [comment]
Changing my username to use only lowercase letters in ~/.serverlessrc fixed this problem for me.  My github name canonically uses uppercase though.

**Comment by secretshardul** [comment]
> There's a bug in setting up `.serverlessrc` with `serverless login` command. It doesn't pick the actual username of the account. It rather picks suggested username(during signup).
> 
> User-end fix:
> manually edit the username in your .serverlessrc to the correct username.

# Fix for problem:
Tested in serverless 1.56.1  
username attribute appears in 2 places in .serverlessrc-    
```js
"dashboard": {
//.......
//.......
"username": "wrong-username", // change this
//....
},
"enterprise":{
//...
},
"username": "correct-username" // copy this to top

```

**Comment by jdcookie** [comment]
Serverless version 1.55

Similar to answer above, slightly different though.

For me, the second instance of `username` was using the part from the email address, once changed to same username in the auth section, it worked for me.

FROM
```
"users": {
    "auth0|xxx": {
      "userId": "auth0|xxx",
      "name": "example@example.app",
      "email": "example@example.app",
      "username": "user-name",
      "dashboard": {
        "refreshToken": "xxx",
        "accessToken": "xxx",
        "idToken": "xxx",
        "expiresAt": xxx,
        "username": "example",
        "accessKeys": {}
      },
      "enterprise": {
        "versionSDK": "2.2.0",
        "timeLastLogin": 1573252023
      }
    }
  }
```
TO
```
"users": {
    "auth0|xxx": {
      "userId": "auth0|xxx",
      "name": "example@example.app",
      "email": "example@example.app",
      "username": "user-name",
      "dashboard": {
        "refreshToken": "xxx",
        "accessToken": "xxx",
        "idToken": "xxx",
        "expiresAt": xxx,
        "username": "user-name",
        "accessKeys": {}
      },
      "enterprise": {
        "versionSDK": "2.2.0",
        "timeLastLogin": 1573252023
      }
    }
  }
```

**Comment by suman500bn** [comment]
I have uploaded my code to github and my colleague cloned it,made few changes and re uploaded it.Then when i pulled it back and trying to deploy i faced this issue.  

I tried to follow above solutions but i couldn't able to find any ~/.serverlessrc  in my directory.

I noticed that when app was first deployed by me there is app and org fields created in serverless.yml file.And when my colleague did it it changed to other names and owner which was causing this issue.

I tried deleting app and org at start of serverless.yml file and try to deploy it.It fixed the issue.

Though this is not a permanent solution when multiple people are working on the application.Please suggest me better solution to avoid this issue.
