### ISSUE TITLE
pnpm + serverless don't mix

### ISSUE THREAD

**Issue by armenr** [serverless/serverless#6605]
# Report

## serverless doesn't appear to play nicely with pnpm
Ran `pnpm install -g serverless`

Ran command: `serverless`

inquirer.js blows the call stack.

The following errors are logged, with the `at Function.get` line repeating 8,224 times:
```
  Range Error --------------------------------------------

  RangeError: Maximum call stack size exceeded
      at Function.get (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/serverless/1.51.0/node_modules/serverless/lib/plugins/interactiveCli/inquirer.js:22:22)
```

which eventually ended with:

```
      at ConfirmPrompt.getQuestion (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/inquirer/6.5.2/node_modules/inquirer/lib/prompts/base.js:130:13)
      at ConfirmPrompt.BasePrompt.getQuestion (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/serverless/1.51.0/node_modules/serverless/lib/plugins/interactiveCli/inquirer.js:32:32)
      at ConfirmPrompt.render (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/inquirer/6.5.2/node_modules/inquirer/lib/prompts/confirm.js:65:24)
      at ConfirmPrompt._run (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/inquirer/6.5.2/node_modules/inquirer/lib/prompts/confirm.js:54:10)
      at resolve (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/inquirer/6.5.2/node_modules/inquirer/lib/prompts/base.js:57:12)
      at new Promise (<anonymous>)
      at ConfirmPrompt.run (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/inquirer/6.5.2/node_modules/inquirer/lib/prompts/base.js:56:12)
      at defer (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/inquirer/6.5.2/node_modules/inquirer/lib/ui/prompt.js:88:27)
      at Observable._subscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/observable/defer.ts:59:15)
      at Observable._trySubscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Observable.ts:238:19)
      at Observable.subscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Observable.ts:219:14)
      at Object.subscribeToResult (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/util/subscribeToResult.ts:26:19)
      at MergeMapSubscriber._innerSub (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:148:5)
      at MergeMapSubscriber._tryNext (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:141:10)
      at MergeMapSubscriber._next (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:125:12)
      at MergeMapSubscriber.Subscriber.next (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
      at MergeMapSubscriber.notifyNext (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:162:22)
      at InnerSubscriber._next (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/InnerSubscriber.ts:17:17)
      at InnerSubscriber.Subscriber.next (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
      at Observable._subscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/util/subscribeToArray.ts:9:16)
      at Observable._trySubscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Observable.ts:238:19)
      at Observable.subscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Observable.ts:219:14)
      at Object.subscribeToResult (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/util/subscribeToResult.ts:26:19)
      at MergeMapSubscriber._innerSub (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:148:5)
      at MergeMapSubscriber._tryNext (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:141:10)
      at MergeMapSubscriber._next (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:125:12)
      at MergeMapSubscriber.Subscriber.next (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
      at MergeMapSubscriber.notifyNext (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:162:22)
      at InnerSubscriber._next (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/InnerSubscriber.ts:17:17)
      at InnerSubscriber.Subscriber.next (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
      at Observable._subscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/util/subscribeToArray.ts:9:16)
      at Observable._trySubscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Observable.ts:238:19)
      at Observable.subscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Observable.ts:219:14)
      at Object.subscribeToResult (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/util/subscribeToResult.ts:26:19)
      at MergeMapSubscriber._innerSub (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:148:5)
      at MergeMapSubscriber._tryNext (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:141:10)
      at MergeMapSubscriber._next (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:125:12)
      at MergeMapSubscriber.Subscriber.next (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
      at MergeMapSubscriber.notifyNext (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:162:22)
      at InnerSubscriber._next (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/InnerSubscriber.ts:17:17)
      at InnerSubscriber.Subscriber.next (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
      at Observable._subscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/util/subscribeToArray.ts:9:16)
      at Observable._trySubscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Observable.ts:238:19)
      at Observable.subscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Observable.ts:219:14)
      at Object.subscribeToResult (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/util/subscribeToResult.ts:26:19)
      at MergeMapSubscriber._innerSub (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:148:5)
      at MergeMapSubscriber._tryNext (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:141:10)
      at MergeMapSubscriber._next (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:125:12)
      at MergeMapSubscriber.Subscriber.next (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
      at MergeMapSubscriber.notifyNext (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:162:22)
      at InnerSubscriber._next (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/InnerSubscriber.ts:17:17)
      at InnerSubscriber.Subscriber.next (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
      at Observable._subscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/util/subscribeToArray.ts:9:16)
      at Observable._trySubscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Observable.ts:238:19)
      at Observable.subscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Observable.ts:219:14)
      at Object.subscribeToResult (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/util/subscribeToResult.ts:26:19)
      at MergeMapSubscriber._innerSub (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:148:5)
      at MergeMapSubscriber._tryNext (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:141:10)
      at MergeMapSubscriber._next (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:125:12)
      at MergeMapSubscriber.Subscriber.next (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
      at MergeMapSubscriber.notifyNext (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:162:22)
      at InnerSubscriber._next (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/InnerSubscriber.ts:17:17)
      at InnerSubscriber.Subscriber.next (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
      at Observable._subscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/util/subscribeToArray.ts:9:16)
      at Observable._trySubscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Observable.ts:238:19)
      at Observable.subscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Observable.ts:219:14)
      at Observable._subscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/observable/defer.ts:65:19)
      at Observable._trySubscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Observable.ts:238:19)
      at Observable.subscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Observable.ts:219:14)
      at Object.subscribeToResult (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/util/subscribeToResult.ts:26:19)
      at MergeMapSubscriber._innerSub (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:148:5)
      at MergeMapSubscriber._tryNext (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:141:10)
      at MergeMapSubscriber._next (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:125:12)
      at MergeMapSubscriber.Subscriber.next (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
      at Observable._subscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/util/subscribeToArray.ts:9:16)
      at Observable._trySubscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Observable.ts:238:19)
      at Observable.subscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Observable.ts:219:14)
      at MergeMapOperator.call (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:100:19)
      at Observable.subscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Observable.ts:214:25)
      at MergeMapOperator.call (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:100:19)
      at Observable.subscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Observable.ts:214:25)
      at MergeMapOperator.call (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:100:19)
      at Observable.subscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Observable.ts:214:25)
      at MergeMapOperator.call (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:100:19)
      at Observable.subscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Observable.ts:214:25)
      at MergeMapOperator.call (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:100:19)
      at Observable.subscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Observable.ts:214:25)
      at MergeMapOperator.call (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:100:19)
      at Observable.subscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Observable.ts:214:25)
      at Observable._subscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/observable/defer.ts:65:19)
      at Observable._trySubscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Observable.ts:238:19)
      at Observable.subscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Observable.ts:219:14)
      at Object.subscribeToResult (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/util/subscribeToResult.ts:26:19)
      at MergeMapSubscriber._innerSub (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:148:5)
      at MergeMapSubscriber._tryNext (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:141:10)
      at MergeMapSubscriber._next (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:125:12)
      at MergeMapSubscriber.Subscriber.next (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
      at Observable._subscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/util/subscribeToArray.ts:9:16)
      at Observable._trySubscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Observable.ts:238:19)
      at Observable.subscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Observable.ts:219:14)
      at MergeMapOperator.call (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/operators/mergeMap.ts:100:19)
      at Observable.subscribe (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/Observable.ts:214:25)
      at Observable.ConnectableObservable.connect (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/rxjs/6.5.2/node_modules/rxjs/src/internal/observable/ConnectableObservable.ts:44:10)
      at PromptUI.run (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/inquirer/6.5.2/node_modules/inquirer/lib/ui/prompt.js:38:18)
      at Object.promptModule [as prompt] (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/inquirer/6.5.2/node_modules/inquirer/lib/inquirer.js:28:22)
      at confirm (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/serverless/1.51.0/node_modules/serverless/lib/plugins/interactiveCli/utils.js:8:8)
      at Object.run (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/serverless/1.51.0/node_modules/serverless/lib/plugins/interactiveCli/initializeService.js:58:12)
      at Object.interactiveCli:initializeService [as hook] (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/serverless/1.51.0/node_modules/serverless/lib/plugins/interactiveCli/index.js:31:34)
      at BbPromise.reduce (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/serverless/1.51.0/node_modules/serverless/lib/classes/PluginManager.js:464:55)
      at tryCatcher (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/bluebird/3.5.5/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/bluebird/3.5.5/node_modules/bluebird/js/release/reduce.js:157:18)
      at Object.gotAccum (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/bluebird/3.5.5/node_modules/bluebird/js/release/reduce.js:144:25)
      at Object.tryCatcher (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/bluebird/3.5.5/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/bluebird/3.5.5/node_modules/bluebird/js/release/promise.js:517:31)
      at Promise._settlePromise (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/bluebird/3.5.5/node_modules/bluebird/js/release/promise.js:574:18)
      at Promise._settlePromiseCtx (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/bluebird/3.5.5/node_modules/bluebird/js/release/promise.js:611:10)
      at _drainQueueStep (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/bluebird/3.5.5/node_modules/bluebird/js/release/async.js:142:12)
      at _drainQueue (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/bluebird/3.5.5/node_modules/bluebird/js/release/async.js:131:9)
      at Async._drainQueues (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/bluebird/3.5.5/node_modules/bluebird/js/release/async.js:147:5)
      at Immediate.Async.drainQueues (/Users/armenr/.nvm/versions/node/v10.16.3/pnpm-global/2/node_modules/.registry.npmjs.org/bluebird/3.5.5/node_modules/bluebird/js/release/async.js:17:14)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)
```

## Additional Data
```
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.16.3
     Framework Version:         1.51.0
     Plugin Version:            1.3.9
     SDK Version:               2.1.0
```

**Comment by medikoo** [comment]
@armenr great thanks for that valuable report! This will be fixed with #6616 

Still I believe our packaging logic won't work well with dependencies referenced via symlinks.
So that probably won't fix this issue completely for you (expect crashes or process hangs when packaging or deploying)

The packaging improvements which will introduce a proper support for symlinks will be covered at #6580

**Comment by mledom** [comment]
@armenr were you able to get serverless to deploy with the way pnpm sets up packages?

**Comment by armenr** [comment]
Thanks for the kind followup, @mledom - however we had to abandon altogether.

**Comment by samchungy** [comment]
For anyone curious I managed to get this working by using

```
shamefully-hoist=true
 node-linker=hoisted
```
