### ISSUE TITLE
kubeless: TypeError: Cannot read property 'runtime-images' of undefined

### ISSUE THREAD

**Issue by zerthimon** [serverless/serverless#6617]
# This is a Bug Report

## Description
Getting this error with kubeless:
```
  Type Error ---------------------------------------------
 
  TypeError: Cannot read property 'runtime-images' of undefined
      at Config.get (/build/node_modules/serverless-kubeless/lib/config.js:56:44)
      at Object.getRuntimeDepfile (/build/node_modules/serverless-kubeless/lib/helpers.js:182:34)
      at ReadStream.<anonymous> (/build/node_modules/serverless-kubeless/deploy/kubelessDeploy.js:103:39)
      at ReadStream.emit (events.js:214:15)
      at ReadStream.EventEmitter.emit (domain.js:476:20)
      at endReadableNT (_stream_readable.js:1178:12)
      at processTicksAndRejections (internal/process/task_queues.js:77:11)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.9.1
     Framework Version:         1.51.0
     Plugin Version:            1.3.10
     SDK Version:               2.1.0
```

## Additional Data
serverless.yml:
```
service: my-service

provider:
  name: kubeless
  runtime: python2.7
  namespace: kubeless-unigram

plugins:
  - serverless-kubeless

functions:
  hello:
    handler: handler.hello
```
handler.py:
```
// handler.py
import json

def hello(request):
    body = {
        "message": "Go Serverless v1.0! Your function executed successfully!",
        "input": request.json
    }

    response = {
        "statusCode": 200,
        "body": json.dumps(body)
    }

    return response
```

kubeless works as expected:
```
~ # kubeless function deploy hello --runtime python2.7 --from-file test.py --handler test.hello
INFO[0000] Deploying function...                        
INFO[0000] Function hello submitted for deployment      
INFO[0000] Check the deployment status executing 'kubeless function ls hello' 
~ #
```
```
~ # kubeless function ls
NAME     NAMESPACE           HANDLER       RUNTIME      DEPENDENCIES    STATUS   
hello    kubeless-unigram    test.hello    python2.7                    1/1 READY
~ #
```
```
~ # kubeless function call hello --data 'Hello world!' 
Hello world!
~ #
```
```
~ # kubeless function delete hello
~ #
```
```
~ # kubeless function ls
NAME    NAMESPACE    HANDLER    RUNTIME    DEPENDENCIES    STATUS
~ #
```

**Comment by nodesocket** [comment]
I am having the same problem trying to use Kubernetes (via Kubeless). See my comment on an associated issue https://github.com/serverless/serverless-kubeless/issues/140#issuecomment-526726537.

Are you running on Amazon EKS by chance? I am, and I think that is the core of the problem.

**Comment by pmuens** [comment]
Thanks for opening @zerthimon :+1:

This seems to be related to the kubeless provider plugin (as @nodesocket pointed out). I'll close this issue for now. Feel free to continue the discussion.

**Comment by zerthimon** [comment]
@nodesocket Nope, this happens on-prem kebernetes

**Comment by nodesocket** [comment]
@zerthimon I created an issue in the Kubeless repo. Would appreciate a +1 there and you can follow along.
