### ISSUE TITLE
Serverless  behind corporate proxy

### ISSUE THREAD

**Issue by jebricker** [serverless/serverless#6632]
# This is a Bug Report

## Description
I have an issue similar to #5308 but the framework does not seem to pick up the proxy env variable.  Using a win20 client via cmd shell.

- What went wrong?
The framework does not seem to be picking up the HTTPS_PROXY environmental variable.  Below is a debug text from running the command serverless --version

- What did you expect should have happened?
I expect the command above would give me the version of serverless framework I am running.
- What was the config you used?
no config.  
- What stacktrace or error message from your provider did you see?
See below
Similar or dependent issues:

- #5308

## Additional Data

C:\RIM_API>echo %HTTPS_PROXY%
https://proxy.mycompany.com:9000

C:\RIM_API>serverless --version
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Framework Core: 1.51.0
Plugin: 1.3.9
SDK: 2.1.0

Serverless:
User stats error: Request network error: { FetchError: request to https://tracking.serverlessteam.com/v1/track failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (C:\Users\eb96409\AppData\Roaming\npm\node_modules\serverless\node_modules\node-fetch\index.js:133:11)
    at ClientRequest.emit (events.js:198:13)
    at ClientRequest.EventEmitter.emit (domain.js:448:20)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.EventEmitter.emit (domain.js:448:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'FetchError',
  message:
   'request to https://tracking.serverlessteam.com/v1/track failed, reason: read ECONNRESET',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET' }
Serverless:
User stats error: Request network error: { FetchError: request to https://tracking.serverlessteam.com/v1/track failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (C:\Users\eb96409\AppData\Roaming\npm\node_modules\serverless\node_modules\node-fetch\index.js:133:11)
    at ClientRequest.emit (events.js:198:13)
    at ClientRequest.EventEmitter.emit (domain.js:448:20)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.EventEmitter.emit (domain.js:448:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'FetchError',
  message:
   'request to https://tracking.serverlessteam.com/v1/track failed, reason: read ECONNRESET',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET' }
Serverless:
User stats error: Request network error: { FetchError: request to https://tracking.serverlessteam.com/v1/track failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (C:\Users\eb96409\AppData\Roaming\npm\node_modules\serverless\node_modules\node-fetch\index.js:133:11)
    at ClientRequest.emit (events.js:198:13)
    at ClientRequest.EventEmitter.emit (domain.js:448:20)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.EventEmitter.emit (domain.js:448:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'FetchError',
  message:
   'request to https://tracking.serverlessteam.com/v1/track failed, reason: read ECONNRESET',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET' }
Serverless:
User stats error: Request network error: { FetchError: request to https://tracking.serverlessteam.com/v1/track failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (C:\Users\eb96409\AppData\Roaming\npm\node_modules\serverless\node_modules\node-fetch\index.js:133:11)
    at ClientRequest.emit (events.js:198:13)
    at ClientRequest.EventEmitter.emit (domain.js:448:20)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.EventEmitter.emit (domain.js:448:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'FetchError',
  message:
   'request to https://tracking.serverlessteam.com/v1/track failed, reason: read ECONNRESET',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET' }
Serverless:
User stats error: Request network error: { FetchError: request to https://tracking.serverlessteam.com/v1/track failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (C:\Users\eb96409\AppData\Roaming\npm\node_modules\serverless\node_modules\node-fetch\index.js:133:11)
    at ClientRequest.emit (events.js:198:13)
    at ClientRequest.EventEmitter.emit (domain.js:448:20)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.EventEmitter.emit (domain.js:448:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'FetchError',
  message:
   'request to https://tracking.serverlessteam.com/v1/track failed, reason: read ECONNRESET',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET' }
Serverless:
User stats error: Request network error: { FetchError: request to https://tracking.serverlessteam.com/v1/track failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (C:\Users\eb96409\AppData\Roaming\npm\node_modules\serverless\node_modules\node-fetch\index.js:133:11)
    at ClientRequest.emit (events.js:198:13)
    at ClientRequest.EventEmitter.emit (domain.js:448:20)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.EventEmitter.emit (domain.js:448:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'FetchError',
  message:
   'request to https://tracking.serverlessteam.com/v1/track failed, reason: read ECONNRESET',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET' }

**Comment by jebricker** [comment]
I did an uninstall and reinstall of serverless and saw this error

```
C:\RIM_API>npm install -g serverless
npm WARN registry Unexpected warning for http://registry.npmjs.org/: Miscellaneous Warning EPROTO: request to http://registry.npmjs.org/serverless failed, reason: write EPROTO 27160:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\\ws\\deps\\openssl\\openssl\\ssl\\record\\ssl3_record.c:332:\n
npm WARN registry Using stale data from http://registry.npmjs.org/ due to a request error during revalidation.
npm WARN deprecated superagent@3.8.3: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.
```

**Comment by jebricker** [comment]
This seems to be a Windows issue with the code.  I ran the same thing in Cygwin and had no issues.
