### ISSUE TITLE
Realmjs not working after deployment in serverless framework

### ISSUE THREAD

**Issue by mithunph** [serverless/serverless#6634]
Hi, I have installed Realmjs which is working fine in local. But after deployment, it is showing error when i require(or import) that package.
Showing error in the below line
const Realm = require('realm');

Below is the full logs of error:
Unable to import module 'server': Error
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/task/node_modules/realm/lib/index.js:103:28)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/task/controllers/realmController.js:3:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

**Comment by medikoo** [comment]
Have you installed `realm` as dependency or as dev dependency? 

Note that if it's installed as dev dependency it'll be not packaged by default (so above error then is the expected outcome)

**Comment by mithunph** [comment]
Hi @medikoo,
realm is installed as dependency

**Comment by medikoo** [comment]
It's probably related that realm relies on C++ module that needs to be compiled for given environment.

@pmuens do we have any recommendations for users which want to rely on C++ Node.js modules?

**Comment by medikoo** [comment]
See also this thread: https://github.com/serverless/serverless/issues/308#issuecomment-242087480

**Comment by mithunph** [comment]
I fixed it by adding the below line in package.json
"postinstall": "chmod +x ./bin/build-realm.sh"

Added below code to build-realm.sh file
#!/usr/bin/env bash
set -e
npm install -g node-gyp
npm install -g node-pre-gyp
cd ./node_modules/realm/
node-pre-gyp install --fallback-to-build
