### ISSUE TITLE
Error handling for configuration/template files: s-project.json, s-component.json, s-module.json and s-function.json

### ISSUE THREAD

**Issue by helenaford** [serverless/serverless#664]
Any syntax errors in the configuration files (_s-project.json, s-component.json, s-module.json, s-function.json_), causes the whole project to break. The dash and function commands will produce an error (shown below) that is very generic. It would be great if this was more descriptive,  to make it more obvious the issue lies in one of these files.

I've mentioned this issue before on the gitter, and haven't come across any other reports on this, so thought I'd raise this as an issue. 

Error that is produced:

/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/main/async.js:43

        fn = function () { throw arg; };
                           ^

SyntaxError: Unexpected string
    at Object.parse (native)
    at Object.exports.readAndParseJsonSync (/usr/local/lib/node_modules/serverless/lib/utils/index.js:520:15)
    at /usr/local/lib/node_modules/serverless/lib/ServerlessModule.js:94:39
From previous event:
    at ServerlessModule.load (/usr/local/lib/node_modules/serverless/lib/ServerlessModule.js:84:25)
    at /usr/local/lib/node_modules/serverless/lib/ServerlessComponent.js:101:23
From previous event:
    at ServerlessComponent.load (/usr/local/lib/node_modules/serverless/lib/ServerlessComponent.js:90:8)
    at /usr/local/lib/node_modules/serverless/lib/ServerlessProject.js:147:28
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at ServerlessProject.load (/usr/local/lib/node_modules/serverless/lib/ServerlessProject.js:132:8)
    at ServerlessState.load (/usr/local/lib/node_modules/serverless/lib/ServerlessState.js:37:26)
    at Serverless.init (/usr/local/lib/node_modules/serverless/lib/Serverless.js:113:23)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:143:56
From previous event:
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:132:38)
    at Serverless.actions.(anonymous function) (/usr/local/lib/node_modules/serverless/lib/Serverless.js:384:20)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:353:38)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:16:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3

**Comment by eahefnawy** [comment]
@helenaford I'm afraid there's not much we can do here because JSON errors are Syntax Errors. We cannot `try/catch` Syntax Errors and make it more friendly/descriptive, which explains why the whole project fails.

But I could feel your pain, missing a comma in JSON could be frustrating! I really on Webstorm to catch those errors before they happen.

**Comment by helenaford** [comment]
@eahefnawy Ah yes, I was going to check out Webstorm. Thanks for the response! I raised it mainly so it's documented somewhere, so maybe it can help someone else - even though,  it's so obvious to me now, when I see the output log, I know what the issue is.
