### ISSUE TITLE
Can't deploy application, error message is empty.

### ISSUE THREAD

**Issue by FBosler** [serverless/serverless#6650]
# This is a Bug Report

## Description

- Tried to deploy python serverless application
- The application should have been deployed
- Linked the serverless dashboard to aws account

serverless.yml:
org: xxx
app: xxx
service: xxx

provider:
  name: aws
  runtime: python3.6
  memorySize: 1024
  timeout: 900
  stage: ${opt:stage, 'production'}
  environment:
    PROJECT: ${self:service}-${self:provider.stage}
    ENV: ${self:provider.stage}
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:*"
       Resource: 'arn:aws:s3:::xxx'
    -  Effect: "Allow"
       Action:
         - "s3:*"
       Resource: 'arn:aws:s3:::xxx'

custom:
  pythonRequirements:
    dockerizePip: non-linux

plugins:
  - serverless-python-requirements

functions:
  run:
    handler: bots/fetchfollow.main
    events:
      - schedule:
          rate: cron(30 * * * ? *)

Stacktrace:
  Error --------------------------------------------------

  Error: {"errorMessage":""}
      at _callee$ (/usr/local/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/src/utils/checkHttpResponse.js:19:9)
      at tryCatch (/usr/local/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:97:21)
      at step (/usr/local/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/dist/utils/checkHttpResponse.js:7:191)
      at /usr/local/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/dist/utils/checkHttpResponse.js:7:361
      at process._tickDomainCallback (internal/process/next_tick.js:135:7)
  From previous event:
      at PluginManager.asyncPluginInit (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:603:22)
      at pluginManager.loadConfigFile.then.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:79:35)
  From previous event:
      at Serverless.init (/usr/local/lib/node_modules/serverless/lib/Serverless.js:76:8)
      at initializeErrorReporter.then (/usr/local/lib/node_modules/serverless/bin/serverless.js:59:6)
      at runCallback (timers.js:672:20)
      at tryOnImmediate (timers.js:645:5)
      at processImmediate [as _immediateCallback] (timers.js:617:5)
  From previous event:
      at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless.js:46:39)
      at Module._compile (module.js:571:32)
      at Object.Module._extensions..js (module.js:580:10)
      at Module.load (module.js:488:32)
      at tryModuleLoad (module.js:447:12)
      at Function.Module._load (module.js:439:3)
      at Module.runMain (module.js:605:10)
      at run (bootstrap_node.js:423:7)
      at startup (bootstrap_node.js:147:9)
      at bootstrap_node.js:538:3

## Additional Data
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              7.9.0
     Framework Version:         1.51.0
     Plugin Version:            1.3.11
     SDK Version:               2.1.0

**Comment by FBosler** [comment]
serverless info fails with the same error. Seems like something is wacky with the serverless / aws connection? No Idea how to resolve this though.

**Comment by dschep** [comment]
When you say
> Linked the serverless dashboard to aws account

do you mean that you configured an ARN in the Profile on the dashboard?

**Comment by FBosler** [comment]
Yea, exactly that. I have since logged out again and deleted the configuration in the dashboard and am just running sls deploy locally which works like a charm.

**Comment by dschep** [comment]
what gh username or email(feel free to email me at daniel@serverless.com if you don't want to post your email) and org and app are you using?
