### ISSUE TITLE
TypeError: Cannot read property 'charAt' of null

### ISSUE THREAD

**Issue by chandrashekar3792** [serverless/serverless#6683]
TypeError: Cannot read property 'charAt' of null
      at params.exclude.forEach.pattern (/usr/local/lib/node_modules/serverless/lib/plugins/package/lib/packageService.js:229:19)
      at Array.forEach (<anonymous>)
      at Package.resolveFilePathsFromPatterns (/usr/local/lib/node_modules/serverless/lib/plugins/package/lib/packageService.js:228:20)
      at getExcludes.then.then.then.params (/usr/local/lib/node_modules/serverless/lib/plugins/package/lib/packageService.js:209:28)

**Comment by medikoo** [comment]
@chandrashekar3792 it's possible that you have error in your `serverless.yml` configuration which leads to this crash. Can you share it with us?

**Comment by pmuens** [comment]
Closing this since it's been almost a month and there's no update on this issue. Feel free to re-open once more information becomes available...

**Comment by medikoo** [comment]
This error happens if in `exclude` section, one of the items is not a string (so e.g. object was nested, or some other non string type).

This actually exposes problem of lack of validation. Ideally value of `excludes` should be validated and meaningful error should be thrown to the user. Having that issues as above will not be reported (I take they're result of confusion)

**Comment by medikoo** [comment]
Error reporting will be fixed with https://github.com/serverless/serverless/issues/6562
