### ISSUE TITLE
Unable to deploy function 

### ISSUE THREAD

**Issue by carolynnvu** [serverless/serverless#671]
My function works fine when I test locally, but I'm having trouble deploying.

**Works fine:**
```
sls function run component/subFolder/myFunction
```

**This doesn't work fine:**

```
sls function deploy component/subFolder/myFunction  -s myStage -r us-east-1
```

**The console shows:**
```
Serverless: Deploying functions in "myStage" to the following regions: us-east-1
Serverless: ------------------------
Serverless: Failed to deploy the following functions in "myStage" to the following regions:
Serverless: us-east-1 ------------------------
Serverless:   component/subFolder/myFunction: Cannot read property 'indexOf' of undefined
```
I only use .indexOf in one place in my code, but all my tests run fine and I've deployed in the past with no problems. So I'm not sure if this is coming from Serverless' end.

**When I try to deploy without any flags, I am asked to choose a stage, but there is nothing to choose from:**
```
Serverless: Function Deployer - Choose a stage:
```

**Comment by dijitalmunky** [comment]
Can you paste the output of the following?

```
sls function deploy component/subFolder/myFunction  -s myStage -r us-east-1 --debug
```

Often times that will help diagnose the issue.

**Comment by dijitalmunky** [comment]
Also, what version of serverless are you using?

**Comment by carolynnvu** [comment]
@dijitalmunky Sure, here's the output:

```
serverless:lib.node_modules.serverless.lib.actions.FunctionDeploy TypeError: Cannot read property 'indexOf' of undefined
    at S3.sSetProjectBucketConfig (/usr/local/lib/node_modules/serverless/lib/utils/aws/S3.js:34:19)
    at S3.sGetEnvFile (/usr/local/lib/node_modules/serverless/lib/utils/aws/S3.js:99:8)
    at Packager._createDistFolder (/usr/local/lib/node_modules/serverless/lib/actions/CodePackageLambda.js:182:23)
From previous event:
    at Packager.package (/usr/local/lib/node_modules/serverless/lib/actions/CodePackageLambda.js:73:10)
    at CodePackageLambda.codePackageLambda (/usr/local/lib/node_modules/serverless/lib/actions/CodePackageLambda.js:50:30)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:182:25
    at Array.reduce (native)
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:181:26)
    at Object.actions.(anonymous function) [as codePackageLambda] (/usr/local/lib/node_modules/serverless/lib/Serverless.js:382:20)
    at /usr/local/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:285:38
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:271:31
    at replenish (/usr/local/lib/node_modules/serverless/node_modules/async/lib/async.js:191:21)
    at /usr/local/lib/node_modules/serverless/node_modules/async/lib/async.js:208:15
    at Object.async.eachLimit (/usr/local/lib/node_modules/serverless/node_modules/async/lib/async.js:168:12)
    at /usr/local/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:267:15
From previous event:
    at FunctionDeploy._deployCodeByRegion (/usr/local/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:260:14)
    at FunctionDeploy.<anonymous> (/usr/local/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:243:24)
From previous event:
    at FunctionDeploy._processDeployment (/usr/local/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:240:10)
From previous event:
    at FunctionDeploy.functionDeploy (/usr/local/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:108:10)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:157:29
    at Array.reduce (native)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:156:30
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:154:10)
    at Serverless.actions.(anonymous function) (/usr/local/lib/node_modules/serverless/lib/Serverless.js:382:20)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:351:38)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:16:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3 +2s
```

And I am using v0.3.3.

**Comment by dijitalmunky** [comment]
Looks like serverless cannot find your s3 bucket.  Make sure your `_meta/variables/s-common-variables.json` file contains a `projectBucket` key with the name of the bucket Serverless set up for you.

Otherwise you *may* need to do an `sls project init`

**Comment by carolynnvu** [comment]
I ended doing ```sls project init```. Thanks, @dijitalmunky!
