### ISSUE TITLE
Remove Tracking

### ISSUE THREAD

**Issue by lesichkovm** [serverless/serverless#6768]
# Bug Report

User stats error: Request network error: { FetchError: network timeout at: https://tracking.serverlessteam.com/v1/track
    at Timeout._onTimeout (/usr/local/lib/node_modules/serverless/node_modules/node-fetch/index.js:126:13)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
  name: 'FetchError',
  message: 'network timeout at: https://tracking.serverlessteam.com/v1/track',
  type: 'request-timeout' }
Serverless: 
User stats error: Request network error: { FetchError: network timeout at: https://tracking.serverlessteam.com/v1/track
    at Timeout._onTimeout (/usr/local/lib/node_modules/serverless/node_modules/node-fetch/index.js:126:13)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
  name: 'FetchError',
  message: 'network timeout at: https://tracking.serverlessteam.com/v1/track',
  type: 'request-timeout' }

**Comment by medikoo** [comment]
@lesichkovm thanks for report. Those errors do not affect functionality of the framework, and since v1.53.0 are not logged with `SLS_DEBUG` anymore.

Still if you want to turn off those requests (they serve purely stats purpose, and nothing personal is collected), you can do so via `sls slstats --disable` command
