### ISSUE TITLE
endpoint already exists error when deploying

### ISSUE THREAD

**Issue by pho3nixf1re** [serverless/serverless#679]
When attempting to deploy (update) an endpoint I get an error saying that it already exists. I see no mention of how to update deployed endpoints in the documentation or in any other issues. I'm not sure what I've done wrong but it must be painfully obvious since no one else seems to be having this issue. What am I doing wrong here?

```
Serverless: Select the assets you wish to deploy:
    api/hello
      function - api/hello
      endpoint - api/hello@hello~GET

    - - - - -
  > Deploy
    Cancel


Serverless: Deploying endpoints in "dev" to the following regions: us-east-1
Serverless: Failed to deploy endpoints in "dev" to the following regions:
Serverless: us-east-1 ------------------------
Serverless:   GET - hello: Response already exists for this resource
Serverless:
Serverless: Run this again with --debug to get more error information...
```

**Comment by eahefnawy** [comment]
Could you please run with the `--debug` option and paste the results here? i.e: `sls dash deploy --debug`

It's hard to see what's going on with the code without this option :)

**Comment by pho3nixf1re** [comment]
```
Serverless: Deploying endpoints in "dev" to the following regions: us-east-1
Serverless: -   serverless:lib.utils.aws.ApiGateway "dev - us-east-1": found existing REST API on AWS API Gateway with name: chefbook-api +503ms
Serverless: -   serverless:lib.utils.aws.ApiGateway "dev - us-east-1": found existing REST API on AWS API Gateway with name: chefbook-api +312ms
Serverless: -   serverless:lib.actions.EndpointBuildApiGateway "dev - us-east-1 - /hello": found the target lambda with function name: chefbook-api-api-hello +495ms
Serverless: -   serverless:lib.actions.EndpointBuildApiGateway "dev - us-east-1 - /hello": found 2 existing Resources on API Gateway +254ms
  serverless:lib.actions.EndpointBuildApiGateway "dev - us-east-1 - /hello": ": no resources need to be created for this endpoint +1ms
Serverless: -   serverless:lib.actions.EndpointBuildApiGateway "dev - us-east-1 - /hello": created method: GET +798ms
Serverless: |   serverless:lib.actions.EndpointBuildApiGateway "dev - us-east-1 - /hello": created integration with the type: AWS +337ms
Serverless: /   serverless:lib.actions.EndpointBuildApiGateway "dev - us-east-1 - /hello": created method response +313ms
Serverless: -   serverless:lib.actions.EndpointBuildApiGateway "dev - us-east-1 - /hello": created method response +313ms
Serverless: \   serverless:lib.actions.EndpointBuildApiGateway "dev - us-east-1 - /hello": created method response +324ms
Serverless: Failed to deploy endpoints in "dev" to the following regions:
Serverless: us-east-1 ------------------------
Serverless:   GET - hello: Response already exists for this resource
  serverless:lib.actions.EndpointDeploy ServerlessError: Response already exists for this resource
    at new ServerlessError (/Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/ServerlessError.js:17:11)
    at /Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js:670:21
From previous event:
    at /Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js:668:19
From previous event:
    at Builder._createEndpointMethodResponses (/Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js:622:10)
From previous event:
    at Builder.build (/Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js:85:10)
    at EndpointBuildApiGateway.endpointBuildApiGateway (/Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js:57:22)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at /Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/Serverless.js:181:25
    at Array.reduce (native)
    at Serverless._execute (/Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/Serverless.js:180:26)
    at Object.actions.(anonymous function) [as endpointBuildApiGateway] (/Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/Serverless.js:381:20)
    at /Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/actions/EndpointDeploy.js:302:42
From previous event:
    at /Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/actions/EndpointDeploy.js:285:35
    at /Users/mturney/Workspace/chefbook-api/node_modules/serverless/node_modules/async/lib/async.js:181:20
    at iterate (/Users/mturney/Workspace/chefbook-api/node_modules/serverless/node_modules/async/lib/async.js:262:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (/Users/mturney/Workspace/chefbook-api/node_modules/serverless/node_modules/async/lib/async.js:281:9)
    at Object.async.forEachSeries.async.eachSeries (/Users/mturney/Workspace/chefbook-api/node_modules/serverless/node_modules/async/lib/async.js:214:22)
    at BbPromise.then.newEvt.options.stage (/Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/actions/EndpointDeploy.js:281:19)
From previous event:
    at /Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/actions/EndpointDeploy.js:278:18
From previous event:
    at EndpointDeploy._deployEndpointsByRegion (/Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/actions/EndpointDeploy.js:270:10)
    at EndpointDeploy.<anonymous> (/Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/actions/EndpointDeploy.js:230:24)
From previous event:
    at EndpointDeploy._processDeployment (/Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/actions/EndpointDeploy.js:227:10)
From previous event:
    at EndpointDeploy.endpointDeploy (/Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/actions/EndpointDeploy.js:113:10)
From previous event:
    at /Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/Serverless.js:181:25
    at Array.reduce (native)
    at Serverless._execute (/Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/Serverless.js:180:26)
    at Object.actions.(anonymous function) [as endpointDeploy] (/Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/Serverless.js:381:20)
    at /Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/actions/DashDeploy.js:272:34
From previous event:
    at DashDeploy._deploy (/Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/actions/DashDeploy.js:267:10)
From previous event:
    at DashDeploy.dashDeploy (/Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/actions/DashDeploy.js:137:10)
From previous event:
    at /Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/Serverless.js:156:29
    at Array.reduce (native)
    at /Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/Serverless.js:155:30
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Serverless._execute (/Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/Serverless.js:153:10)
    at Serverless.actions.(anonymous function) (/Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/Serverless.js:381:20)
    at Serverless.command (/Users/mturney/Workspace/chefbook-api/node_modules/serverless/lib/Serverless.js:350:38)
    at Object.<anonymous> (/Users/mturney/Workspace/chefbook-api/node_modules/serverless/bin/serverless:16:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3 +330ms
Serverless:
Serverless: Run this again with --debug to get more error information...
```

**Comment by eahefnawy** [comment]
and could you please paste your `s-function.js`? specially endpoint config :)

**Comment by pho3nixf1re** [comment]
```json
"endpoints": [
    {
      "path": "hello",
      "method": "GET",
      "type": "AWS",
      "authorizationType": "none",
      "apiKeyRequired": false,
      "requestParameters": {},
      "requestTemplates": {
        "application/json": ""
      },
      "responses": {
        "400": {
          "selectionPattern": "(?:.|\\n)*\\\"status\\\"\\:\\s*\\n*\\s*\\\"BadRequest\\\"(?:.|\\n)*",
          "statusCode": "400",
          "responseParameters": {},
          "responseModels": {},
          "responseTemplates": {
            "application/json": "#set($inputRoot = $input.path('$.errorMessage'))\n$inputRoot.toJSON()"
          }
        },
        "500": {
          "selectionPattern": "(?:.|\\n)*\\\"status\\\"\\:\\s*\\n*\\s*\\\"(\\w+)\\\"(?:.|\\n)*",
          "statusCode": "500",
          "responseParameters": {},
          "responseModels": {},
          "responseTemplates": {
            "application/json": "#set($inputRoot = $input.path('$.errorMessage'))\n$inputRoot.toJSON()"
          }
        },
        "200": {
          "selectionPattern": ".*(?!\\\"errorMessage\\\":).*",
          "statusCode": "200",
          "responseTemplates": {
            "application/json": ""
          }
        },
        "default": {
          "statusCode": "500",
          "responseTemplates": {
            "application/json": ""
          }
        }
      }
```

**Comment by eahefnawy** [comment]
Interesting! I think the issue is that you've defined **two** `500` responses, one of them is the default one. Could you confirm by removing the `default` response?

**Comment by pho3nixf1re** [comment]
Yup, that was it! Seems odd to me, but I'm new to all this. Thanks for stepping through this with me. Do you have thoughts about the underlying error here?

**Comment by eahefnawy** [comment]
AWS is just conflicted on which response to use for the `500` status code when working with the same resource, because you've defined two, and each resource can only have one response per status code. I'm not sure if that's required for your project, but I'd try to avoid that :smile:

Thanks for reaching out, and if you have any more issues, please let us know :blush:
