### ISSUE TITLE
The CloudFormation template is invalid: Template format error: Number of resources, 202, is greater than maximum allowed

### ISSUE THREAD

**Issue by marcosoftinova** [serverless/serverless#6803]
# Bug Report

## Description
I opened a ticket within AWS Support and they have increased our CF Stack limit to 500 resources. Even though the limit was increased, Serverless is still throwing the error in the title.

Obviously our limit is not 200 anymore but 500 instead and Serverless keeps telling that the It is still 200, why? 

How can I use Serverless with more than 200 resources now that the limit has been increased?

1. What did you do?
   sls deploy
1. What happened?
   The CloudFormation template is invalid: Template format error: Number of resources, 202, is greater than maximum allowed
1. What should've happened?
    Successfully deploy
1. What's the content of your `serverless.yml` file?
     Does not matter
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
    Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service dialog-manager.zip file to S3 (10.66 MB)...
Serverless: Validating template...
Unhandled rejection Error: The CloudFormation template is invalid: Template format error: Number of resources, 202, is greater than maximum allowed, 200
    at provider.request.catch.error (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:19:13)
    at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:695:18)
    at _drainQueueStep (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

Similar or dependent issues:

- #5999

**Comment by medikoo** [comment]
Serverless message refers to _Maximum number of resources that you can declare in your AWS CloudFormation template_, which is hard set to 200 (it's not possible to lift it even after contacting support).

I believe what you have lifted is _Maximum number of AWS CloudFormation stacks that you can create_, which indeed is possible to upgrade by contacting the support.

**Comment by marcosoftinova** [comment]
@medikoo 

Confirmed. The limit they've increased is actually Maximum number of AWS CloudFormation stacks.

Thanks for your response. I am closing the issue as It's not an issue.
