### ISSUE TITLE
Add chinese regions support pls.

### ISSUE THREAD

**Issue by ac1982** [serverless/serverless#6805]
# Feature Proposal
Would you pleaes add aws chinese regions:
cn-northwest-1 (宁夏)
cn-north-1 (北京)
## Description
```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Installing dependencies for custom CloudFormation resources...

  Error --------------------------------------------------

  Error: {"message":"Region cn-northwest-1 is not a valid AWS region."}
      at /usr/lib/node_modules/serverless/node_modules/@serverless/lib/logsCollection.js:63:11
      at Generator.throw (<anonymous>)
      at asyncGeneratorStep (/usr/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/logsCollection.js:3:103)
      at _throw (/usr/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/logsCollection.js:5:291)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
```

**Comment by medikoo** [comment]
This error comes from fact that not all regions are supported by Serverless Dashboard.

I'll leave it open as a bug, as error message is in accurate. It's not that region is invalid, it's that we do not support it, and it's what error message should express

**Comment by coodysk8er** [comment]
any update on this please?
