### ISSUE TITLE
`npm run test-ci` fails with  lib/classes/PluginManager.test.js

### ISSUE THREAD

**Issue by kdnakt** [serverless/serverless#6824]
# Bug Report

## Description

When I run `npm run test-ci` with the latest commit aba4e09c7be7e1c89b14728428f0f1a3bf9ccbbb, it fails and shows following message:

```
  105 passing (8s)
  1 failing

  1) PluginManager
       #loadAllPlugins()
         should throw an error when trying to load unknown plugin:

      AssertionError: expected [Function] to throw 'ServerlessError' but 'TypeError: Cannot read property \'realPath\' of null' was thrown
      + expected - actual

      -TypeError: Cannot read property 'realPath' of null
      +ServerlessError
      
      at Context.it (lib/classes/PluginManager.test.js:710:74)
      at process._tickCallback (internal/process/next_tick.js:61:11)



lib/classes/PluginManager.test.js failed

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serverless@1.54.0 test-isolated: `mocha-isolated`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serverless@1.54.0 test-isolated script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/akito/.npm/_logs/2019-10-12T07_00_32_589Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serverless@1.54.0 test-ci: `npm run prettier-check-updated && npm run lint-updated && npm run test-isolated`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serverless@1.54.0 test-ci script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Commit 050cb90684c03559fd484c89fb13ab380b3c263a may be related to this issue.
When I run the same command with the previous commit, 4d9006bcdf783f96ca89c4901947c7159ea64121, it gets success.

**Comment by medikoo** [comment]
@kdnakt ensure to update dependencies with `npm install` (error is like you've pulled new chamges but didn't update the dependencies)

**Comment by kdnakt** [comment]
@medikoo Thanks for your advise, I got success after running `npm install`!
