### ISSUE TITLE
`serverless package` should not attempt to follow symlinks in excluded directories

### ISSUE THREAD

**Issue by jleclanche** [serverless/serverless#6890]
Reproduce by creating a `serverless.yml` with the following included:

```yml
package:
  exclude:
    - example/
```

And then creating an `example/` dir and a broken symlink inside it, eg. `mkdir example/; ln -s /does/not/exist example/broken`.

Running `serverless package` on this will cause an ENOENT error.

```
  Error: ENOENT: no such file or directory, open '/home/adys/src/_/web/scripts/broken_symlink'
      at Package.getFileContent (/home/adys/.local/share/yarn/global/node_modules/serverless/lib/plugins/package/lib/zipService.js:134:15)
      at Package.getFileContentAndStat (/home/adys/.local/share/yarn/global/node_modules/serverless/lib/plugins/package/lib/zipService.js:123:12)
      at Array.map (<anonymous>)
      at WriteStream.<anonymous> (/home/adys/.local/share/yarn/global/node_modules/serverless/lib/plugins/package/lib/zipService.js:92:46)
      at WriteStream.emit (events.js:210:5)
      at WriteStream.EventEmitter.emit (domain.js:476:20)
      at /home/adys/.local/share/yarn/global/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:231:14
      at /home/adys/.local/share/yarn/global/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:258:16
      at FSReqCallback.oncomplete (fs.js:146:23)
```

**Comment by jleclanche** [comment]
Incidentally, excluded directories should be skipped. I have a directory under `exclude` that contains tens of millions of files and it's causing serverless to hang for hours and run OOM.

**Comment by medikoo** [comment]
This should definitely be fixed with: https://github.com/serverless/serverless/issues/6580

Still interim patch for current packaging implementation is welcome.

**Comment by jleclanche** [comment]
@medikoo Agreed, and I guess with whatever fixes that we should make sure the `exclude` directory is skipped.

**Comment by medikoo** [comment]
> I guess with whatever fixes that we should make sure the exclude directory is skipped.

Yes, there's no point to inspect excluded directories. If it happens, it's already a sign of some inefficiency

**Comment by thewizarodofoz** [comment]
@medikoo can you share an update on this please?

**Comment by medikoo** [comment]
@thewizarodofoz #6580 is on a todo list as one of the priorities, but delivery date is uncertain, and I wouldn't expect that soon.

Anyway if you can come up with a fix that patches current implementation PR is definitely welcome
