### ISSUE TITLE
Error while invoking Billing API

### ISSUE THREAD

**Issue by asnkalavara** [serverless/serverless#6915]
# Bug Report

## Description

1. What did you do? Invoke Billing API for testing
1. What happened?  TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received type undefined
1. What should've happened? Normal response without error
1. What's the content of your `serverless.yml` file?
  billing:
    # Defines an HTTP API endpoint that calls the main function in billing.js
    # - path: url path is /billing
    # - method: POST request
    handler: billing.main
    events:
      - http:
          path: billing
          method: post
          cors: true
          authorizer: aws_iam
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

at validateString (internal/validators.js:112:11)
      at Object.relative (path.js:438:5)
      at C:\Users\asnai\notes-app-api\node_modules\serverless-webpack\lib\validate.js:182:38
      at arrayMap (C:\Users\asnai\notes-app-api\node_modules\lodash\lodash.js:639:23)
      at Function.map (C:\Users\asnai\notes-app-api\node_modules\lodash\lodash.js:9554:14)
      at processConfig (C:\Users\asnai\notes-app-api\node_modules\serverless-webpack\lib\validate.js:177:37)
      at ServerlessPlugin.validate (C:\Users\asnai\notes-app-api\node_modules\serverless-webpack\lib\validate.js:229:14)
      at ServerlessPlugin.tryCatcher (C:\Users\asnai\notes-app-api\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\Users\asnai\notes-app-api\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (C:\Users\asnai\notes-app-api\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromiseCtx (C:\Users\asnai\notes-app-api\node_modules\bluebird\js\release\promise.js:641:10)
      at _drainQueueStep (C:\Users\asnai\notes-app-api\node_modules\bluebird\js\release\async.js:97:12)
      at _drainQueue (C:\Users\asnai\notes-app-api\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (C:\Users\asnai\notes-app-api\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\asnai\notes-app-api\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:131:23)

Similar or dependent issues: None

- #12345

**Comment by pmuens** [comment]
Hey @asnkalavara thanks for opening :+1:

Apparently your indentation is wrong. Here's how it should look like:

```yaml
    events:
      - http:
           path: billing
           method: post
           cors: true
           authorizer: aws_iam
```

**Comment by medikoo** [comment]
@pmuens it might be nice to improve validation of templates, so meaningful errors are thrown, which provide right hint to the users (still I take there are tens of places to address)

**Comment by asnkalavara** [comment]
Thanks @pmuens 

I double-checked the indentation at

  billing:
    # Defines an HTTP API endpoint that calls the main function in billing.js
    # - path: url path is /billing
    # - method: POST request
    handler: billing.main
    events:
      - http:
          path: billing
          method: post
          cors: true
          authorizer: aws_iam
          
But I am still getting the same error:-

\notes-app-api>serverless invoke local --function billing --path mocks/billing-event.json
Serverless: DOTENV: Loading environment variables from .env:
Serverless:      - DYANMODB_TABLE
Serverless:      - AWS_REGION
Serverless:      - AUTH0_CLIENT_ID
Serverless:      - AUTH0_CLIENT_SECRET
Serverless:      - STRIPE_SECRET_KEY
Serverless:      - SLS_DEBUG
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Invoke invoke:local
Serverless: Invoke webpack:validate

  Type Error ---------------------------------------------

  TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received type undefined
      at validateString (internal/validators.js:112:11)
      at Object.relative (path.js:438:5)
      at C:\Users\asnai\notes-app-api\node_modules\serverless-webpack\lib\validate.js:182:38
      at arrayMap (C:\Users\asnai\notes-app-api\node_modules\lodash\lodash.js:639:23)
      at Function.map (C:\Users\asnai\notes-app-api\node_modules\lodash\lodash.js:9554:14)
      at processConfig (C:\Users\asnai\notes-app-api\node_modules\serverless-webpack\lib\validate.js:177:37)
      at ServerlessPlugin.validate (C:\Users\asnai\notes-app-api\node_modules\serverless-webpack\lib\validate.js:229:14)
      at ServerlessPlugin.tryCatcher (C:\Users\asnai\notes-app-api\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\Users\asnai\notes-app-api\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (C:\Users\asnai\notes-app-api\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromiseCtx (C:\Users\asnai\notes-app-api\node_modules\bluebird\js\release\promise.js:641:10)
      at _drainQueueStep (C:\Users\asnai\notes-app-api\node_modules\bluebird\js\release\async.js:97:12)
      at _drainQueue (C:\Users\asnai\notes-app-api\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (C:\Users\asnai\notes-app-api\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\asnai\notes-app-api\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:131:23)

**Comment by asnkalavara** [comment]
@pmuens 

Thanks! I double-checked the indentation. This is okay. But still getting the error:-

\notes-app-api>serverless invoke local --function billing --path mocks/billing-event.json

Serverless: DOTENV: Loading environment variables from .env:
Serverless:      - DYANMODB_TABLE
Serverless:      - AWS_REGION
Serverless:      - AUTH0_CLIENT_ID
Serverless:      - AUTH0_CLIENT_SECRET
Serverless:      - STRIPE_SECRET_KEY
Serverless:      - SLS_DEBUG
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Invoke invoke:local
Serverless: Invoke webpack:validate

  Type Error ---------------------------------------------

  TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received type undefined
      at validateString (internal/validators.js:112:11)
      at Object.relative (path.js:438:5)
      at C:\Users\asnai\notes-app-api\node_modules\serverless-webpack\lib\validate.js:182:38
      at arrayMap (C:\Users\asnai\notes-app-api\node_modules\lodash\lodash.js:639:23)
      at Function.map (C:\Users\asnai\notes-app-api\node_modules\lodash\lodash.js:9554:14)
      at processConfig (C:\Users\asnai\notes-app-api\node_modules\serverless-webpack\lib\validate.js:177:37)
      at ServerlessPlugin.validate (C:\Users\asnai\notes-app-api\node_modules\serverless-webpack\lib\validate.js:229:14)
      at ServerlessPlugin.tryCatcher (C:\Users\asnai\notes-app-api\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\Users\asnai\notes-app-api\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (C:\Users\asnai\notes-app-api\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromiseCtx (C:\Users\asnai\notes-app-api\node_modules\bluebird\js\release\promise.js:641:10)
      at _drainQueueStep (C:\Users\asnai\notes-app-api\node_modules\bluebird\js\release\async.js:97:12)
      at _drainQueue (C:\Users\asnai\notes-app-api\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (C:\Users\asnai\notes-app-api\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\asnai\notes-app-api\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:131:23)

**Comment by asnkalavara** [comment]
Attaching serverless.yml (zipped)
[serverless.zip](https://github.com/serverless/serverless/files/3804887/serverless.zip)

**Comment by mcc9229** [comment]
> Attaching serverless.yml (zipped)
> [serverless.zip](https://github.com/serverless/serverless/files/3804887/serverless.zip)

The environment block in your serverless.yml is duplicated. Delete one and that should solve the problem. The remaining block should look like this:

# These environment variables are made available to our functions
# under process.env.
environment:
    tableName: notes
    stripeSecretKey: ${env:STRIPE_SECRET_KEY}

**Comment by mcc9229** [comment]
The environment block in your serverless.yml is duplicated. Delete one and that should solve the problem. The remaining block should look like this:

`environment:'
'     tableName: notes'
'     stripeSecretKey: ${env:STRIPE_SECRET_KEY}'

**Comment by mcc9229** [comment]
The environment block in your serverless.yml is duplicated. Delete one and that should solve the problem. The remaining block should look like this:

![2019-11-05 00_22_02-Window](https://user-images.githubusercontent.com/56990224/68183555-6487a580-ff62-11e9-8d45-348b6d5159a4.png)

**Comment by asnkalavara** [comment]
@mcc9229 

Thank you very much! You hit the nail on the spot -- the issue is resolved!!

**Comment by medikoo** [comment]
Error reporting will be fixed with https://github.com/serverless/serverless/issues/6562

**Comment by uzenith360** [comment]
> 
> 
> The environment block in your serverless.yml is duplicated. Delete one and that should solve the problem. The remaining block should look like this:
> 
> ![2019-11-05 00_22_02-Window](https://user-images.githubusercontent.com/56990224/68183555-6487a580-ff62-11e9-8d45-348b6d5159a4.png)

Worked for me too. I had to correct my indentation
