### ISSUE TITLE
Failure to run `sls login`

### ISSUE THREAD

**Issue by adamsea** [serverless/serverless#6932]
# Bug Report

## Description

1. What did you do? I am trying to use `serverless login` on an existing serverless.yml configuration to add existing functions to the serverless dashboard
2. What happened? I received the following error:
```
Erics-MacBook-Pro-2:clearview-serverless eric$ ./node_modules/.bin/serverless login --stage dev
Serverless: Logging you in via your default browser...

/Users/eric/repos/clearview-serverless/node_modules/ws/lib/WebSocket.js:719
      error = new Error('unexpected server response (' + res.statusCode + ')');
              ^
Error: unexpected server response (302)
    at ClientRequest.response (/Users/eric/repos/clearview-serverless/node_modules/ws/lib/WebSocket.js:719:15)
    at Object.onceWrapper (events.js:299:26)
    at ClientRequest.emit (events.js:209:13)
    at ClientRequest.EventEmitter.emit (domain.js:476:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
    at TLSSocket.socketOnData (_http_client.js:456:22)
    at TLSSocket.emit (events.js:209:13)
    at TLSSocket.EventEmitter.emit (domain.js:476:20)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:286:11)
    at TLSSocket.Readable.push (_stream_readable.js:220:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:182:23)
```
3. What should've happened? Based on the documentation, a browser session should have opened, prompting me to login.
4. What's the content of your `serverless.yml` file? Honestly it's pretty large - we have around 40 functions deployed through this config. Please tell me what pertinent sections you'd need to help resolve this.
5. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

```
Erics-MacBook-Pro-2:clearview-serverless eric$ SLS_DEBUG=* ./node_modules/.bin/serverless login --stage dev
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Invoke login
Serverless: Logging you in via your default browser...

/Users/eric/repos/clearview-serverless/node_modules/ws/lib/WebSocket.js:719
      error = new Error('unexpected server response (' + res.statusCode + ')');
              ^
Error: unexpected server response (302)
    at ClientRequest.response (/Users/eric/repos/clearview-serverless/node_modules/ws/lib/WebSocket.js:719:15)
    at Object.onceWrapper (events.js:299:26)
    at ClientRequest.emit (events.js:209:13)
    at ClientRequest.EventEmitter.emit (domain.js:476:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
    at TLSSocket.socketOnData (_http_client.js:456:22)
    at TLSSocket.emit (events.js:209:13)
    at TLSSocket.EventEmitter.emit (domain.js:476:20)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:286:11)
    at TLSSocket.Readable.push (_stream_readable.js:220:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:182:23)
```

**Comment by adamsea** [comment]
Just one more quick note -- I added `--stage dev` to the call because without it, I received the following errors when login tried to load my yml file:

```
ServerlessError: Trying to populate non string value into a string for variable ${opt:stage}.
```

This makes sense to me, and I don't _think_ that would impact this stage of the dashboard integration...

**Comment by dschep** [comment]
You are correct that `--stage dev` shoudn't have an impact. I'll look into this. (but to avoid that error, use `${self:provider.stage, opt:state}` instead of just `${opt:stage}` so that it works with the default stage value)

**Comment by dschep** [comment]
Are you using any of the cafile or https_proxy options, @adamsea?

**Comment by adamsea** [comment]
Hi @dschep, no neither of those are added into the config.  Also just to be clear, this is on serverless 1.48.4.

**Comment by mledom** [comment]
I'm seeing this as well:
`
Serverless: Logging you in via your default browser...
 
  Error --------------------------------------------------
 
  Error: Unexpected server response: 302
      at ClientRequest.req.on (/Users/mledom/Documents/Companies/Eletype/Code/eletypeLambda/node_modules/ws/lib/websocket.js:542:5)
      at ClientRequest.emit (events.js:189:13)
      at ClientRequest.EventEmitter.emit (domain.js:441:20)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
      at TLSSocket.socketOnData (_http_client.js:442:20)
      at TLSSocket.emit (events.js:189:13)
      at TLSSocket.EventEmitter.emit (domain.js:441:20)
      at addChunk (_stream_readable.js:284:12)
      at readableAddChunk (_stream_readable.js:265:11)
      at TLSSocket.Readable.push (_stream_readable.js:220:10)
      at TLSWrap.onStreamRead (internal/stream_base_commons.js:94:17)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.15.3
     Framework Version:         1.59.3
     Plugin Version:            3.2.5
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0

`

**Comment by justin-prather** [comment]
For anyone that is still experienceing this i was able to get around it by changing to my home directory and retrying sls login. If youre like me and dont like installing packages globally you can npx sls login

**Comment by mikhael28** [comment]
I had the exact same issue as @mledom - I was on an older version (1.8.0) and upgraded to the latest version as of today (2.11.1), and it all worked from there for me.

**Comment by CedricLeong** [comment]
I fixed this by running `sudo sls login`. If you have serverless installed globally you can just move out of your project to avoid having to pass in project specific parameters like `--stage dev`.
