### ISSUE TITLE
BadRequestError: request size did not match content length

### ISSUE THREAD

**Issue by schoenbl** [serverless/serverless#6951]
# Bug Report

## Description

1. What did you do?
I tried to update my serverless.yml to allow CORS, decided to change it back to my default configuration.
1. What happened?
I receive this error this error whenever I call an endpoint:
```
BadRequestError: request size did not match content length
    at IncomingMessage.onEnd (/Users/lukeschoenberger/Documents/Programming/news-arg/backend/node_modules/raw-body/index.js:263:12)
    at IncomingMessage.emit (events.js:203:13)
    at IncomingMessage.EventEmitter.emit (domain.js:471:20)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```
This is for a node.js express api. Regardless of which API I call, this is what I receive.
1. What should've happened?
I should receive a valid response back from the api. When I run the api with nodemon, it works perfectly.
1. What's the content of your `serverless.yml` file?
This is exactly what it looks like:
```
service: news-api # NOTE: update this with your service name


provider:
  name: aws
  runtime: nodejs10.x



functions:
  app:
    handler: app.handler
    # The `events` block defines how to trigger the http events
    events:
        - http: ANY /
        - http: 'ANY {proxy+}'

plugins:
  - serverless-offline
```
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

This is what I receive:
```
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Invoke offline:start
Serverless: Starting Offline: dev/us-east-1.
[offline] options: {
  apiKey: 'd41d8cd98f00b204e9800998ecf8427e',
  cacheInvalidationRegex: /node_modules/,
  corsAllowOrigin: [ '*' ],
  corsAllowCredentials: true,
  corsAllowHeaders: [ 'accept', 'content-type', 'x-api-key', 'authorization' ],
  corsExposedHeaders: [ 'WWW-Authenticate', 'Server-Authorization' ],
  disableCookieValidation: false,
  enforceSecureCookies: false,
  exec: '',
  hideStackTraces: false,
  host: 'localhost',
  httpsProtocol: '',
  location: '.',
  noAuth: false,
  noEnvironment: false,
  noTimeout: false,
  port: 3000,
  prefix: '/',
  preserveTrailingSlash: false,
  printOutput: false,
  providedRuntime: '',
  showDuration: false,
  stage: 'dev',
  region: 'us-east-1',
  resourceRoutes: false,
  skipCacheInvalidation: true,
  useSeparateProcesses: false,
  websocketPort: 3001,
  c: true,
  corsConfig: {
    credentials: true,
    exposedHeaders: [ 'WWW-Authenticate', 'Server-Authorization' ],
    headers: [ 'accept', 'content-type', 'x-api-key', 'authorization' ],
    origin: [ '*' ]
  }
}
[offline] funOptions {
  "funName": "app",
  "funTimeout": 30000,
  "handlerName": "handler",
  "handlerPath": "/Users/lukeschoenberger/Documents/Programming/news-arg/backend/app",
  "runtime": "nodejs10.x"
} 

[offline] app runtime nodejs10.x
Serverless: Routes for app:
Serverless: ANY /
Serverless: ANY /{proxy*}
[offline] Response Content-Type  application/json
Serverless: POST /{apiVersion}/functions/news-api-dev-app/invocations

Serverless: Offline [HTTP] listening on http://localhost:3000
Serverless: Enter "rp" to replay the last request
```

This is what comes through when I call an endpoint:
```
Serverless: ANY /teams (λ: app)
[offline] requestId: ck2ty5g850000u9ka67ildnyx
[offline] contentType: application/json
[offline] requestTemplate: 
[offline] payload: null
[offline] Loading handler... (/Users/lukeschoenberger/Documents/Programming/news-arg/backend/app)
[offline] event: {
  body: null,
  headers: {
    'Content-Type': 'application/json',
    'User-Agent': 'PostmanRuntime/7.19.0',
    Accept: '*/*',
    'Cache-Control': 'no-cache',
    'Postman-Token': '445f07e3-9d16-47fc-8ea5-63cb6a2dd61e',
    Host: 'localhost:3000',
    'Accept-Encoding': 'gzip, deflate',
    'Content-Length': '1145',
    Connection: 'keep-alive'
  },
  httpMethod: 'GET',
  multiValueHeaders: {
    'Content-Type': [ 'application/json' ],
    'User-Agent': [ 'PostmanRuntime/7.19.0' ],
    Accept: [ '*/*' ],
    'Cache-Control': [ 'no-cache' ],
    'Postman-Token': [ '445f07e3-9d16-47fc-8ea5-63cb6a2dd61e' ],
    Host: [ 'localhost:3000' ],
    'Accept-Encoding': [ 'gzip, deflate' ],
    'Content-Length': [ '1145' ],
    Connection: [ 'keep-alive' ]
  },
  multiValueQueryStringParameters: null,
  path: '/teams',
  pathParameters: { proxy: 'teams' },
  queryStringParameters: null,
  requestContext: {
    accountId: 'offlineContext_accountId',
    apiId: 'offlineContext_apiId',
    authorizer: {
      principalId: 'offlineContext_authorizer_principalId',
      claims: undefined
    },
    httpMethod: 'GET',
    identity: {
      accountId: 'offlineContext_accountId',
      apiKey: 'offlineContext_apiKey',
      caller: 'offlineContext_caller',
      cognitoAuthenticationProvider: 'offlineContext_cognitoAuthenticationProvider',
      cognitoAuthenticationType: 'offlineContext_cognitoAuthenticationType',
      cognitoIdentityId: 'offlineContext_cognitoIdentityId',
      cognitoIdentityPoolId: 'offlineContext_cognitoIdentityPoolId',
      sourceIp: '127.0.0.1',
      user: 'offlineContext_user',
      userAgent: 'PostmanRuntime/7.19.0',
      userArn: 'offlineContext_userArn'
    },
    protocol: 'HTTP/1.1',
    requestId: 'offlineContext_requestId_ck2ty5goc0001u9kafhr92bcm',
    requestTimeEpoch: 1573447726946,
    resourceId: 'offlineContext_resourceId',
    resourcePath: '/{proxy*}',
    stage: 'dev'
  },
  resource: '/{proxy*}',
  stageVariables: null,
  isOffline: true
}
[offline] _____ CALLING HANDLER _____
Server is running on Port: 4000
[offline] _____ HANDLER RESOLVED _____
[offline] Using response 'default'
[offline] _____ RESPONSE PARAMETERS PROCCESSING _____
[offline] Found 0 responseParameters for 'default' response
[offline] headers {
  'x-powered-by': [ 'Express' ],
  'content-security-policy': [ "default-src 'none'" ],
  'x-content-type-options': [ 'nosniff' ],
  'content-type': [ 'text/html; charset=utf-8' ],
  'content-length': [ '613' ]
}
[offline] requestId: ck2ty5g850000u9ka67ildnyx
BadRequestError: request size did not match content length
    at IncomingMessage.onEnd (/Users/lukeschoenberger/Documents/Programming/news-arg/backend/node_modules/raw-body/index.js:263:12)
    at IncomingMessage.emit (events.js:203:13)
    at IncomingMessage.EventEmitter.emit (domain.js:471:20)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
MongoDB database connection established!
```

Similar or dependent issues:

I haven't found a similar issue with serverless.

**Comment by medikoo** [comment]
@schoenbl this looks as problem with [serverless-offline](https://github.com/dherault/serverless-offline) and I believe should be posted there

**Comment by pmuens** [comment]
@schoenbl thanks for opening :+1:

I agree with @medikoo here. This looks related to the `serverless-offline` plugin. Could you open up an issue in the plugins repository? Thanks!

**Comment by dev-Abhaybh** [comment]
Hello every one I am also facing the same issue the code is working fine on local host but not on serverless offline. the issue I am facing is related to line
 app.use(express.json({  extended: true }));

**Comment by kubo550** [comment]
Hi,
I had the same issue.

In my case it turned out it was because the request had the header `Content-Type: application/json` 
The request was a GET with no body content.
Removing the header Content-Type helped
