### ISSUE TITLE
Unknown Error From API: certificate has expired

### ISSUE THREAD

**Issue by Avik1993** [serverless/serverless#6968]
# Bug Report
sls deploy fails with error Failed to deploy function  due to error: Unknown Error From API: certificate has expired

## Description
I am trying to deploy openwhisk function using serverless using command sls deploy.
I have already created openwhisk-nodejs template project and have a working openwhisk setup.

I can create actions in openwhisk using wsk utility and curl request to them.

But while deploying using serverless, its failing with error:
*Failed to deploy function (serverlessproject-dev-hello) due to error: Unknown Error From API: certificate has expired*

1. What did you do? Deploying openwhisk function using serverless
1. What happened? It failed with above message
1. What should've happened? Should have deployed the function
1. What's the content of your `serverless.yml` file?
```
service: serverlessproject
provider:
  name: openwhisk

functions:
  hello:
    handler: handler.main
plugins:
  - serverless-openwhisk
```
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
```
  Serverless Error ---------------------------------------
 
  ServerlessError: Failed to deploy function (serverlessproject-dev-hello) due to error: Unknown Error From API: certificate has expired
      at ow.actions.create.then.catch.err (/root/serverless/serverlessProject/node_modules/serverless-openwhisk/deploy/lib/deployFunctions.js:18:15)
      at process._tickDomainCallback (internal/process/next_tick.js:135:7)
  From previous event:
      at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:489:22)
      at getHooks.reduce.then (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:524:24)
  From previous event:
      at PluginManager.run (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:524:8)
      at variables.populateService.then (/usr/lib/node_modules/serverless/lib/Serverless.js:115:33)
      at runCallback (timers.js:672:20)
      at tryOnImmediate (timers.js:645:5)
      at processImmediate [as _immediateCallback] (timers.js:617:5)
  From previous event:
      at Serverless.run (/usr/lib/node_modules/serverless/lib/Serverless.js:102:74)
      at serverless.init.then (/usr/lib/node_modules/serverless/bin/serverless.js:72:30)
      at /usr/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
      at /root/serverless/serverlessProject/node_modules/graceful-fs/graceful-fs.js:57:14
      at /usr/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
      at FSReqWrap.oncomplete (fs.js:123:15)
  From previous event:
      at initializeErrorReporter.then (/usr/lib/node_modules/serverless/bin/serverless.js:72:8)
      at runCallback (timers.js:672:20)
      at tryOnImmediate (timers.js:645:5)
      at processImmediate [as _immediateCallback] (timers.js:617:5)
  From previous event:
      at Object.<anonymous> (/usr/lib/node_modules/serverless/bin/serverless.js:61:4)
      at Module._compile (module.js:577:32)
      at Object.Module._extensions..js (module.js:586:10)
      at Module.load (module.js:494:32)
      at tryModuleLoad (module.js:453:12)
      at Function.Module._load (module.js:445:3)
      at Module.runMain (module.js:611:10)
      at run (bootstrap_node.js:394:7)
      at startup (bootstrap_node.js:160:9)
      at bootstrap_node.js:507:3
```

Similar or dependent issues:

- #12345

**Comment by medikoo** [comment]
@Avik1993 thanks for report. I'm transferring to https://github.com/serverless/serverless-openwhisk repository

**Comment by medikoo** [comment]
> I'm transferring to https://github.com/serverless/serverless-openwhisk repository

Sorry it appears I'm unable to do that. Can you open this issue over there?

**Comment by pmuens** [comment]
Thanks for opening @Avik1993 :+1:

Can you re-open the issue in the `serverless-openwhisk` plugin repository? Thanks!
