### ISSUE TITLE
Error: Runtime nodejs12.x is not supported.

### ISSUE THREAD

**Issue by x5engine** [serverless/serverless#6998]
Error --------------------------------------------------
 
  Error: Runtime nodejs12.x is not supported.

``` 
Supported versions: {
    "nodejs": [
      {
        "version": "0.10.40"
      },
      {
        "version": "0.10.5"
      },
      {
        "version": "0.12.6"
      },
      {
        "version": "0.6.20"
      },
      {
        "version": "0.8.28"
      },
      {
        "version": "10.14.1"
      },
      {
        "version": "10.15.2"
      },
      {
        "version": "10.6.0"
      },
      {
        "version": "4.8.4"
      },
      {
        "version": "6.12.3"
      },
      {
        "version": "6.5.0"
      },
      {
        "version": "6.9.1"
      },
      {
        "version": "6.9.5"
      },
      {
        "version": "7.10.1"
      },
      {
        "version": "8.1.4"
      },
      {
        "version": "8.10.0"
      },
      {
        "version": "8.11.1"
      },
      {
        "version": "8.4.0"
      },
      {
        "version": "8.5.0"
      },
      {
        "version": "8.9.4"
      }
    ],
    "python": [
      {
        "version": "3.6"
      }
    ]
  }
      at ConfigService.getRuntime (/Users/admin/Documents/sls-az-func-rest-api/node_modules/serverless-azure-functions/lib/services/configService.js:182:19)
      at ConfigService.initializeConfig (/Users/admin/Documents/sls-az-func-rest-api/node_modules/serverless-azure-functions/lib/services/configService.js:158:48)
      at new ConfigService (/Users/admin/Documents/sls-az-func-rest-api/node_modules/serverless-azure-functions/lib/services/configService.js:32:28)
      at OfflineService.BaseService (/Users/admin/Documents/sls-az-func-rest-api/node_modules/serverless-azure-functions/lib/services/baseService.js:67:30)
      at new OfflineService (/Users/admin/Documents/sls-az-func-rest-api/node_modules/serverless-azure-functions/lib/services/offlineService.js:84:28)
      at AzureOfflinePlugin.<anonymous> (/Users/admin/Documents/sls-az-func-rest-api/node_modules/serverless-azure-functions/lib/plugins/offline/azureOfflinePlugin.js:112:42)
      at step (/Users/admin/Documents/sls-az-func-rest-api/node_modules/serverless-azure-functions/lib/plugins/offline/azureOfflinePlugin.js:45:23)
      at Object.next (/Users/admin/Documents/sls-az-func-rest-api/node_modules/serverless-azure-functions/lib/plugins/offline/azureOfflinePlugin.js:26:53)
      at /Users/admin/Documents/sls-az-func-rest-api/node_modules/serverless-azure-functions/lib/plugins/offline/azureOfflinePlugin.js:20:71
      at new Promise (<anonymous>)
      at __awaiter (/Users/admin/Documents/sls-az-func-rest-api/node_modules/serverless-azure-functions/lib/plugins/offline/azureOfflinePlugin.js:16:12)
      at AzureOfflinePlugin.azureOfflineBuild (/Users/admin/Documents/sls-az-func-rest-api/node_modules/serverless-azure-functions/lib/plugins/offline/azureOfflinePlugin.js:107:16)
      at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:489:55)
      at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:168:18)
      at Object.gotAccum (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
      at runCallback (timers.js:810:20)
      at tryOnImmediate (timers.js:768:5)
      at processImmediate [as _immediateCallback] (timers.js:745:5)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              8.12.0
     Framework Version:         1.58.0
     Plugin Version:            3.2.5
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```

**Comment by medikoo** [comment]
@x5engine I believe it belongs to [serverless-azure-functions](https://github.com/serverless/serverless-azure-functions) repository. Can you move it there?

**Comment by x5engine** [comment]
@medikoo will do okay :)
