### ISSUE TITLE
Could not find function for endpoint

### ISSUE THREAD

**Issue by vkreal** [serverless/serverless#704]
Hi,
I am vetting serverless for a project and keep on getting error below. Very first deploy works and any deploy after I keep on getting same error below. Anyone have any idea to work around or fix it?

repro steps:
1. create new project
2. create one component/function 'v1/level'
3. deploy
4. create new function 'v1/levels'
5. deploy (error happens on this step)

Note if i change step 4 to 'v1/listoflevels' error goes away.

Thanks!

Serverless: Deploying endpoints in "dev" to the following regions: us-east-1  
Serverless: \   serverless:lib.node_modules.serverless.lib.utils.aws.ApiGateway "dev - us-east-1": found existing REST API on AWS API Gateway with name: yaya-api +571ms
Serverless: Failed to deploy endpoints in "dev" to the following regions:  
Serverless: us-east-1 ------------------------  
Serverless:   GET - v1/level/{id}: Could not find function for endpoint  
  serverless:lib.node_modules.serverless.lib.actions.EndpointDeploy ServerlessError: Could not find function for endpoint
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/ServerlessError.js:17:11)
    at ServerlessEndpoint.getFunction (/usr/local/lib/node_modules/serverless/lib/ServerlessEndpoint.js:258:11)
    at Builder._validateAndPrepare (/usr/local/lib/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js:164:43)
    at Builder.build (/usr/local/lib/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js:77:20)
    at EndpointBuildApiGateway.endpointBuildApiGateway (/usr/local/lib/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js:57:22)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:181:25
    at Array.reduce (native)
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:180:26)
    at Object.actions.(anonymous function) [as endpointBuildApiGateway] (/usr/local/lib/node_modules/serverless/lib/Serverless.js:381:20)
    at /usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:302:42
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:285:35
    at /usr/local/lib/node_modules/serverless/node_modules/async/lib/async.js:181:20
    at iterate (/usr/local/lib/node_modules/serverless/node_modules/async/lib/async.js:262:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (/usr/local/lib/node_modules/serverless/node_modules/async/lib/async.js:281:9)
    at Object.async.forEachSeries.async.eachSeries (/usr/local/lib/node_modules/serverless/node_modules/async/lib/async.js:214:22)
    at BbPromise.then.newEvt.options.stage (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:281:19)

**Comment by eahefnawy** [comment]
@vkreal really sorry for the late reply, but after our huge refactoring there's a good chance this issue was resolved. Could you confirm?

**Comment by vkreal** [comment]
@eahefnawy let me get back after I get chance to play with latest. Thanks for getting back!

**Comment by flomotlik** [comment]
@vkreal I will close this issue for now. Let us know if this was fixed.
