### ISSUE TITLE
sls login fails.

### ISSUE THREAD

**Issue by ajinabraham** [serverless/serverless#7061]
# Bug Report

## Description

1. What did you do?
```
sls login
```
1. What happened?
```
$ sls login
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command requirements
Serverless: Load command requirements:clean
Serverless: Load command requirements:install
Serverless: Load command requirements:cleanCache
Serverless: Load command wsgi
Serverless: Load command wsgi:serve
Serverless: Load command wsgi:install
Serverless: Load command wsgi:clean
Serverless: Load command wsgi:command
Serverless: Load command wsgi:command:local
Serverless: Load command wsgi:exec
Serverless: Load command wsgi:exec:local
Serverless: Load command wsgi:manage
Serverless: Load command wsgi:manage:local
Serverless: Load command wsgi:flask
Serverless: Load command wsgi:flask:local
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard

  Type Error ---------------------------------------------

  TypeError: Cannot read property 'trim' of undefined
      at Variables.splitByComma (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:475:26)
      at Variables.splitAndGet (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:430:24)
      at /usr/local/lib/node_modules/serverless/lib/classes/Variables.js:371:41
      at arrayMap (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:639:23)
      at Function.map (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:9554:14)
      at Variables.populateMatches (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:371:14)
      at Variables.populateValue (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:402:30)
      at /usr/local/lib/node_modules/serverless/lib/classes/Variables.js:168:16
      at Array.map (<anonymous>)
      at /usr/local/lib/node_modules/serverless/lib/classes/Variables.js:167:48
      at Variables.disableDepedentServices (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:125:12)
      at Variables.prepopulateService (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:166:19)
      at /usr/local/lib/node_modules/serverless/lib/classes/Variables.js:195:12
      at Variables.initialCall (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:100:12)
      at Variables.populateService (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:194:17)
      at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:102:27)
      at /usr/local/lib/node_modules/serverless/bin/serverless.js:72:30
      at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
      at /Users/ajinabraham/Code/IMMUNIO/serverless-test-app-django/node_modules/serverless-wsgi/node_modules/graceful-fs/graceful-fs.js:57:14
      at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
      at FSReqCallback.oncomplete (fs.js:153:23)
  From previous event:
      at /usr/local/lib/node_modules/serverless/bin/serverless.js:72:8
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:126:23)
  From previous event:
      at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless.js:61:4)
      at Module._compile (internal/modules/cjs/loader.js:774:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
      at Module.load (internal/modules/cjs/loader.js:641:32)
      at Function.Module._load (internal/modules/cjs/loader.js:556:12)
      at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
      at internal/main/run_main_module.js:17:11

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.4.0
     Framework Version:         1.59.1
     Plugin Version:            3.2.5
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0


 Serverless Information ----------------------------------

  ############################################################################################
    # 2506: 0 of 0 promises have settled
    # 2506: 0 are taking longer than expected:
    # This can result from latent connections but may represent a cyclic variable dependency
    ##########################################################################################


 Serverless Information ----------------------------------

  ############################################################################################
    # 5010: 0 of 0 promises have settled
    # 5010: 0 are taking longer than expected:
    # This can result from latent connections but may represent a cyclic variable dependency
    ##########################################################################################


 Serverless Information ----------------------------------

  ############################################################################################
    # 7514: 0 of 0 promises have settled
    # 7514: 0 are taking longer than expected:
    # This can result from latent connections but may represent a cyclic variable dependency
    ##########################################################################################


 Serverless Information ----------------------------------

  ############################################################################################
    # 10015: 0 of 0 promises have settled
    # 10015: 0 are taking longer than expected:
    # This can result from latent connections but may represent a cyclic variable dependency
    ##########################################################################################
```
1. What should've happened?

Do login

1. What's the content of your `serverless.yml` file?
I guess this doesn't have to do anything with my serverless file.
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
```
Shown above
```

**Comment by medikoo** [comment]
@ajinabraham thanks for report. Can you share your `serverless.yml`, at least part that influences that error?

**Comment by ajinabraham** [comment]
Never mind. It indeed is an issue due to an error in serverless.yml
