### ISSUE TITLE
module initialization error: Error

### ISSUE THREAD

**Issue by hhashmi** [serverless/serverless#7074]
module initialization error: Error
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at bindings (/var/task/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/var/task/node_modules/couchbase/lib/binding.js:214:36)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/task/node_modules/couchbase/lib/couchbase.js:3:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)

**Comment by medikoo** [comment]
@hhashmi It looks as error generated in your lambda (it crashed right at initialization_ It doesn't look related to Serverless Framework

**Comment by hhashmi** [comment]
I figured it out. Issue was not related to serverless. It was due to miss match of VPC subnet.
