### ISSUE TITLE
Cannot stop server while in stopping state

### ISSUE THREAD

**Issue by juppdes** [serverless/serverless#7088]
After upgrading to version 1.59.3, , began to experience the following error:
Note: I have the callback treatment in the function.

(node:912) UnhandledPromiseRejectionWarning: Error: Cannot stop server while in stopping state
    at module.exports.internals.Server.internals.Server.stop (C:\Sistemas\ConexaoServer\node_modules\hapi\lib\server.js:383:40)
    at C:\Sistemas\ConexaoServer\node_modules\hapi\lib\promises.js:24:16
    at new Promise (<anonymous>)
    at Object.exports.wrap (C:\Sistemas\ConexaoServer\node_modules\hapi\lib\promises.js:13:12)
    at module.exports.internals.Server.internals.Server.stop (C:\Sistemas\ConexaoServer\node_modules\hapi\lib\server.js:377:25)
    at Offline.end (C:\Sistemas\ConexaoServer\node_modules\serverless-offline\src\index.js:987:17)
    at C:\Users\NoteDell15\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:489:55
    at tryCatcher (C:\Users\NoteDell15\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Users\NoteDell15\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\reduce.js:168:18)
    at Object.gotAccum (C:\Users\NoteDell15\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\reduce.js:155:25)
    at Object.tryCatcher (C:\Users\NoteDell15\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\NoteDell15\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\NoteDell15\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\NoteDell15\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\NoteDell15\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\NoteDell15\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\NoteDell15\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\NoteDell15\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues (C:\Users\NoteDell15\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:130:23)
(node:912) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

Ps.:

**Comment by pmuens** [comment]
Hey @juppdes thanks for opening :+1:

This seems to be related to a plugin (maybe `serverless-offline`?). Could you re-open this issue on the plugins repository? Thanks!
