### ISSUE TITLE
Serverless doesn't support IAM service accounts

### ISSUE THREAD

**Issue by shardulsrivastava** [serverless/serverless#7101]
# Bug Report
Serverless doesn't use aws sdk provided credentials provider to get credentials,it doesn't support AWS_WEB_IDENTITY_TOKEN_FILE and AWS_ROLE_ARN to get the temporary credentials.

## Description

1. What did you do?
I can see [here](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/lib/validate.js) that serverless only uses EC2 Metadata service for getting credentials, which may not be available when we are executing it inside of the pod in EKS and restricted the access to the credentials as mentioned here :
https://docs.aws.amazon.com/eks/latest/userguide/restrict-ec2-credential-access.html.

In case of restrictions, we will assign a service account to the pod and pod will have these two variables AWS_WEB_IDENTITY_TOKEN_FILE and AWS_ROLE_ARN which if used together with the latest aws-sdk , can be used to access AWS services.

As mentioned [here](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html), minimum supported version for service accounts in aws-sdk for Nodejs is [2.521.0](https://github.com/aws/aws-sdk-js/releases/tag/v2.521.0) 

1. What happened?
I got this error, AWS provider credentials not found.
1. What should've happened?
It should have used the AWS sdk for getting temporary credentials and use them.
1. What's the content of your `serverless.yml` file?
```yaml
org: shardulsrivastava
app: notification-api
service: notification-api
provider:
  name: aws
  stackName: serverless-notification-api
  stage: api
  region: ap-south-1
  runtime: nodejs12.x
  memorySize: 1024
functions:
  notification-api:
    name: serverless-notification-api
    handler: handler.endpoint
    events:
      - http:
          path: registration
          method: post
```
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Invoke deploy:list
 
  Serverless Error ---------------------------------------
 
  ServerlessError: AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://slss.io/aws-creds-setup>.
      at BbPromise.catch.then.identity (/var/buildkite/builds/eks-agent-1/rea/notification-api/node_modules/serverless/lib/plugins/aws/lib/validate.js:56:19)
  From previous event:
      at AwsDeployList.validate (/var/buildkite/builds/eks-agent-1/rea/notification-api/node_modules/serverless/lib/plugins/aws/lib/validate.js:48:10)
  From previous event:
      at Object.before:deploy:list:log [as hook] (/var/buildkite/builds/eks-agent-1/rea/notification-api/node_modules/serverless/lib/plugins/aws/deployList/index.js:18:60)
      at BbPromise.reduce (/var/buildkite/builds/eks-agent-1/rea/notification-api/node_modules/serverless/lib/classes/PluginManager.js:489:55)
  From previous event:
      at PluginManager.invoke (/var/buildkite/builds/eks-agent-1/rea/notification-api/node_modules/serverless/lib/classes/PluginManager.js:489:22)
      at getHooks.reduce.then (/var/buildkite/builds/eks-agent-1/rea/notification-api/node_modules/serverless/lib/classes/PluginManager.js:524:24)
  From previous event:
      at PluginManager.run (/var/buildkite/builds/eks-agent-1/rea/notification-api/node_modules/serverless/lib/classes/PluginManager.js:524:8)
      at variables.populateService.then (/var/buildkite/builds/eks-agent-1/rea/notification-api/node_modules/serverless/lib/Serverless.js:115:33)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)
  From previous event:
      at Serverless.run (/var/buildkite/builds/eks-agent-1/rea/notification-api/node_modules/serverless/lib/Serverless.js:102:74)
      at serverless.init.then (/var/buildkite/builds/eks-agent-1/rea/notification-api/node_modules/serverless/bin/serverless.js:72:30)
      at /var/buildkite/builds/eks-agent-1/rea/notification-api/node_modules/serverless/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:136:16
      at /var/buildkite/builds/eks-agent-1/rea/notification-api/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
      at /var/buildkite/builds/eks-agent-1/rea/notification-api/node_modules/graceful-fs/graceful-fs.js:57:14
      at /var/buildkite/builds/eks-agent-1/rea/notification-api/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
      at FSReqWrap.args [as oncomplete] (fs.js:140:20)
  From previous event:
      at initializeErrorReporter.then (/var/buildkite/builds/eks-agent-1/rea/notification-api/node_modules/serverless/bin/serverless.js:72:8)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)
  From previous event:
      at Object.<anonymous> (/var/buildkite/builds/eks-agent-1/rea/notification-api/node_modules/serverless/bin/serverless.js:61:4)
      at Module._compile (internal/modules/cjs/loader.js:778:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
      at Module.load (internal/modules/cjs/loader.js:653:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
      at Function.Module._load (internal/modules/cjs/loader.js:585:3)
      at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
      at startup (internal/bootstrap/node.js:283:19)
      at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              10.16.3
     Framework Version:         1.59.3
     Plugin Version:            3.2.6
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0

```
Similar or dependent issues:

- #12345

**Comment by medikoo** [comment]
@shardulsrivastava I believe it was fixed with v1.60. Please confirm

**Comment by shardulsrivastava** [comment]
@medikoo  sure will check and let you know

**Comment by shardulsrivastava** [comment]
@medikoo  i can confirm that it's working fine. however i would like to point out a scenario where it fails, 
as mentioned in the Bug Report that m trying to use it on `Pod` in `EKS`.

on this instance i have restricted instance profile for pods i.e added these commands to boot strap comands:

```bash
yum install -y iptables-services
iptables --insert FORWARD 1 --in-interface eni+ --destination 169.254.169.254/32 --jump DROP
iptables-save | tee /etc/sysconfig/iptables 
systemctl enable --now iptables
```

this way any call to `http://169.254.169.254/latest/meta-data/` won't work.

I can see that serverless checks for metadata https://github.com/serverless/serverless/blob/ee290018bba3eae95aa9951131dbe8af5ba00bf8/lib/plugins/aws/lib/validate.js#L37
 and if metadata url is not accessible , validation fails as per thie code:

```javascript
      // first check if the EC2 Metadata Service has creds before throwing error
      const ec2Credentials = new this.provider.sdk.EC2MetadataCredentials({
        httpOptions: { timeout: 5000 }, // 5 second timeout
        maxRetries: 0, // retry 0 times
      });
      return new BbPromise((resolve, reject) =>
        ec2Credentials.load(err => {
          if (err) {
            const message = [
              'AWS provider credentials not found.',
              ' Learn how to set up AWS provider credentials',
              ` in our docs here: <${chalk.green('http://slss.io/aws-creds-setup')}>.`,
            ].join('');
            userStats.track('user_awsCredentialsNotFound');
            reject(new this.serverless.classes.Error(message));
          } else {
            resolve({});
          }
        })
      );
    }
    return BbPromise.resolve();
```

Let me know your thoughts about this.

**Comment by medikoo** [comment]
@shardulsrivastava thanks for clarification. Yes, the way we try to validate AWS authentication credentials is known to be buggy. I've opened an dedicated issue for that here: https://github.com/serverless/serverless/issues/7605
