### ISSUE TITLE
Plugin install does not work for custom config file

### ISSUE THREAD

**Issue by benjaminsims** [serverless/serverless#7130]
# Bug Report

## Description

When installing plugins combined with the --config option for a custom file, the config option is ignored.

`serverless --config myconfig.yml plugin install --name serverless-stage-manager`

results in an error:

`Could not find any serverless service definition file.`

I think this is triggered here: https://github.com/serverless/serverless/blob/master/lib/plugins/plugin/lib/utils.js#L25, where 'serverless.yml' is used without taking into account the config option.

**Comment by medikoo** [comment]
Will be fixed with #7131

**Comment by jkachhia** [comment]
It seems that profile is not exists then throw error 
`serverless config credentials --provider aws --key 1234 --secret 5678 --profile custom-profile --overwrite`

>  Error: Profile dev does not exist 
      at Object.addProfileCredentials (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:100:15) 
      at AwsProvider.getCredentials (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:371:12) 
      at AwsProvider.request (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:226:48) 
      at Variables.getValueFromSsm (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:802:8) 
      at Variables.getValueFromSource (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:567:17) 
      at Variables.splitAndGet (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:436:17)

**Comment by medikoo** [comment]
@jkachhia your comment is unrelated to this issue. Not it was about `--config` option and not `config` command
