### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by ChaithraKumar123** [serverless/serverless#7174]
I really dont understand what is the possible issue ??

Serverless: Installing requirements of requirements.txt in .serverless...
Serverless: Docker Image: lambci/lambda:build-python3.7
 
  Error --------------------------------------------------
 
  Error: ERROR: Exception:
  Traceback (most recent call last):
    File "/var/lang/lib/python3.7/shutil.py", line 566, in move
      os.rename(src, real_dst)
  OSError: [Errno 18] Invalid cross-device link: '/tmp/pip-target-c8eq4is8/lib/python/scikit_learn-0.21.3.dist-info' -> '/var/task/.serverless/requirements/scikit_learn-0.21.3.dist-info'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/var/lang/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
      status = self.run(options, args)
    File "/var/lang/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 505, in run
      options.target_dir, target_temp_dir, options.upgrade
    File "/var/lang/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 563, in _handle_target_dir
      target_item_dir
    File "/var/lang/lib/python3.7/shutil.py", line 577, in move
      symlinks=True)
    File "/var/lang/lib/python3.7/shutil.py", line 324, in copytree
      os.makedirs(dst)
    File "/var/lang/lib/python3.7/os.py", line 221, in makedirs
      mkdir(name, mode)
  PermissionError: [Errno 13] Permission denied: '/var/task/.serverless/requirements/scikit_learn-0.21.3.dist-info'
  
      at installRequirements (/Users/chaithrakumar/Model_deploy/node_modules/serverless-python-requirements/lib/pip.js:146:11)
      at ServerlessPythonRequirements.installAllRequirements (/Users/chaithrakumar/Model_deploy/node_modules/serverless-python-requirements/lib/pip.js:242:5)
      at ServerlessPythonRequirements.tryCatcher (/Users/chaithrakumar/Model_deploy/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/chaithrakumar/Model_deploy/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/chaithrakumar/Model_deploy/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/Users/chaithrakumar/Model_deploy/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/Users/chaithrakumar/Model_deploy/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/Users/chaithrakumar/Model_deploy/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/Users/chaithrakumar/Model_deploy/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/Users/chaithrakumar/Model_deploy/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/Users/chaithrakumar/Model_deploy/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:445:21)
      at process.topLevelDomainCallback (domain.js:135:15)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              13.5.0
     Framework Version:         1.60.4
     Plugin Version:            3.2.6
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0

**Comment by medikoo** [comment]
I believe this belongs to https://github.com/UnitedIncome/serverless-python-requirements 

Can you post this issue over there?

**Comment by ChaithraKumar123** [comment]
just make sure all your files exists in the same directory.
Especially we you run sls deploy make sure you run that with proper permission.
just do ls -la you will get list of all hidden files. .serveless directory must be create in the same filesystem.
if its created in the root and you have other files in your user filesystem.Just try avoiding sudo.
if sls deploy (without sudo) throws error remove .serveless directory and again run the sls deploy without sudo.
The key is all your files must be in same filesystem.
This solved my error!
Hope this helps!
