### ISSUE TITLE
Serverless says UPDATE_COMPLETE_CLEANUP_IN_PROGRESS state and can not be updated but CloudFormation says UPDATE_COMPLETE

### ISSUE THREAD

**Issue by lovefamilychildrenhappiness** [serverless/serverless#7217]
# Bug Report

Serverless raises following error: 

ServerlessError: Stack:arn:aws:cloudformation:us-east-2:***:stack/myapp-dev/81820bc0-3618-11ea-a28d-0294f7a52ca2 is in UPDATE_COMPLETE_CLEANUP_IN_PROGRESS state and can not be updated.

But CloudFormation events update from UPDATE_IN_PROGRESS to UPDATE_COMPLETE. Hence, there is no error in CloudFormation "cannot be updated". 

1. What did you do?
I deploy Serverless via AWS CodeBuild Service. In my buildspec.yml, I run sls deploy:

SLS_DEBUG=1 sls deploy --verbose --stage dev --region us-east-2

1. What happened?
CodeBuild shows the following errors in its logs:

Serverless: Validating template...
Serverless: [AWS cloudformation 200 0.352s 0 retries] validateTemplate({
  TemplateURL: 'https://s3.amazonaws.com/myapp-dev-serverlessdeploymentbucket-p4rq713ykhz4/serverless/myapp/dev/1579019953414-2020-01-14T16:39:13.414Z/compiled-cloudformation-template.json'
})
Serverless: Updating Stack...
Serverless: [AWS cloudformation 400 0.059s 0 retries] updateStack({
  StackName: 'myapp-dev',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL: 'https://s3.amazonaws.com/myapp-dev-serverlessdeploymentbucket-p4rq713ykhz4/serverless/myapp/dev/1579019953414-2020-01-14T16:39:13.414Z/compiled-cloudformation-template.json',
  Tags: [ { Key: 'STAGE', Value: 'dev' }, [length]: 1 ]
})
 
  Serverless Error ---------------------------------------
 
  ServerlessError: Stack:arn:aws:cloudformation:us-east-2:***:stack/myapp-dev/81820bc0-3618-11ea-a28d-0294f7a52ca2 is in UPDATE_COMPLETE_CLEANUP_IN_PROGRESS state and can not be updated.
      at /usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:326:27
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.13.0
     Framework Version:         1.61.1
     Plugin Version:            3.2.7
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0

1. What should've happened?
It should have completed the deployment with UPDATE_COMPLETE, because when I look at the event logs in CloudFormation, it shows current status UPDATE_COMPLETE. In fact, when I run the 'retry' button on CodeDeploy, CodeDeploy re-executes the buildspec.yml again and serverless does not throw the error! It only raises that 'UPDATE_COMPLETE_CLEANUP_IN_PROGRESS' error when using git commit, and since CodeDeploy is integrated with CodeCommit in AWS CodePipeline, CodeDeploy runs and the error happens. 

1. What's the content of your `serverless.yml` file?
Exactly what content will you need from serverless.yml? It is a pretty large file..

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
The original command uses SLS_DEBUG=*

**Comment by lovefamilychildrenhappiness** [comment]
@medikoo I found the cause of the issue and it is not directly related to serverless. I had two webhooks connected to my AWS CodePipeline, so when I ran git commit, it was actually executing two CodeDeploy agents concurrently. When I removed one of the webhooks, the issue no longer persisted. Since this is not directly related to serverless, I will close the issue.
