### ISSUE TITLE
Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by cyberfox1** [serverless/serverless#7219]

**Comment by medikoo** [comment]
@cyberfox1 can you carefully fill all issue template: https://github.com/serverless/serverless/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

Given information is insufficient for us to diagnose the issue.

**Comment by btdo** [comment]
Hi, I get this error as well whenever I execute a serverless config command. Here's my environment
```
(base) baos-MacBook-Pro:hello-world-python bao$ node -v
v12.13.1
(base) baos-MacBook-Pro:hello-world-python bao$ sls -v
Framework Core: 1.71.3
Plugin: 3.6.12
SDK: 2.3.0
Components: 2.30.11
```

Here's the stacktrace 

```
 TypeError: Cannot read property 'trim' of undefined
      at Variables.splitByComma (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:484:26)
      at Variables.splitAndGet (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:438:24)
      at /usr/local/lib/node_modules/serverless/lib/classes/Variables.js:379:41
      at arrayMap (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:639:23)
      at Function.map (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:9554:14)
```

Thanks

Bao

**Comment by medikoo** [comment]
@btdo can you please open a new issue and carefully fill all answer for all template questions. Unfortunately what you provided above is not enough for me to diagnose it properly.

I'm going to close this one, as author didn't provide enough information for us to be able to process that
