### ISSUE TITLE
AWS deployment impossible: non-alphanumeric characters not fully escaped in WebSocket routes

### ISSUE THREAD

**Issue by tom-marsh** [serverless/serverless#7220]
# AWS Lambda WebSocket routes not fully escaped in CloudFormation template

## Description

When using serverless for deploying AWS Lambda functions, WebSocket routes with multiple instances of the same non-alphanumeric character result in a CloudFormation template validation error on deployment.

1. What did you do?

Added a AWS Lambda function definition to `serverless.yml` with a WebSocket route with multiple dashes, like the following:

```
myFunction:
  handler: main.handler
  events:
    - http: POST /some-api-route
    - websocket:
        route: some-api-route
```

2. What happened?

The command `sls deploy` fails with the message: `Error: The CloudFormation template is invalid: Template format error: Resource name someDashapi-routeWebsocketsRoute is non alphanumeric.`

Stack trace:

```
Error: The CloudFormation template is invalid: Template format error: Resource name someDashapi-routeWebsocketsRoute is non alphanumeric.
      at provider.request.catch.error (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:20:13)
      at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:725:18)
      at _drainQueueStep (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
      at runCallback (timers.js:794:20)
      at tryOnImmediate (timers.js:752:5)
      at processImmediate [as _immediateCallback] (timers.js:729:5)
```

This template works when running locally with the serverless offline plugin.

3. What should've happened?

The deployment should have run successfully.

4. What's the content of your `serverless.yml` file?

```
service: my-service

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-west-1
  deploymentBucket:
    name: deploymentBucket
  websocketsApiRouteSelectionExpression: $request.body.action

functions:
  myFunction:
    handler: main.handler
    events:
      - http: POST /some-api-route
      - websocket:
          route: some-api-route
```

5. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

```
  Error --------------------------------------------------
 
  Error: The CloudFormation template is invalid: Template format error: Resource name someDashapi-routeWebsocketsRoute is non alphanumeric.
      at provider.request.catch.error (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:20:13)
  From previous event:
      at AwsDeploy.validateTemplate (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:16:85)
  From previous event:
      at AwsDeploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:119:39)
  From previous event:
      at Object.aws:deploy:deploy:validateTemplate [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:115:30)
      at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:490:55)
  From previous event:
      at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:510:17)
      at AwsDeploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:93:48)
  From previous event:
      at Object.deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:89:30)
      at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:490:55)
  From previous event:
      at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at getHooks.reduce.then (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:525:24)
  From previous event:
      at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:525:8)
      at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:133:33)
      at runCallback (timers.js:794:20)
      at tryOnImmediate (timers.js:752:5)
      at processImmediate [as _immediateCallback] (timers.js:729:5)
  From previous event:
      at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:120:74)
      at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless.js:75:30)
      at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
      at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
      at FSReqWrap.oncomplete (fs.js:135:15)
  From previous event:
      at initializeErrorReporter.then (/usr/local/lib/node_modules/serverless/bin/serverless.js:75:8)
      at runCallback (timers.js:794:20)
      at tryOnImmediate (timers.js:752:5)
      at processImmediate [as _immediateCallback] (timers.js:729:5)
  From previous event:
      at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless.js:64:4)
      at Module._compile (module.js:652:30)
      at Object.Module._extensions..js (module.js:663:10)
      at Module.load (module.js:565:32)
      at tryModuleLoad (module.js:505:12)
      at Function.Module._load (module.js:497:3)
      at Function.Module.runMain (module.js:693:10)
      at startup (bootstrap_node.js:188:16)
      at bootstrap_node.js:609:3
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              8.10.0
     Framework Version:         1.60.5
     Plugin Version:            3.2.7
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```

## Suggested Potential Fix

The following code in `lib/plugins/aws/lib/naming.js` appears to be the culprit:

```
getNormalizedWebsocketsRouteKey(route) {
    return route
      .replace('$', 'S') // dollar sign
      .replace('/', 'Slash')
      .replace('-', 'Dash')
      .replace('_', 'Underscore')
      .replace('.', 'Period');
  },
```

Proposed change:

```
getNormalizedWebsocketsRouteKey(route) {
    return route
      .replace(/\$/g, 'S') // dollar sign
      .replace(/\//g, 'Slash')
      .replace(/-/g, 'Dash')
      .replace(/_/g, 'Underscore')
      .replace(/\./g, 'Period');
  },
```

Proposed unit tests (`lib/plugins/aws/lib/naming.test.js`), under the `describe('#getNormalizedWebsocketsRouteKey()')` section at line 252:

```
it('converts multiple `-` correctly', () => {
    expect(sdk.naming.getNormalizedWebsocketsRouteKey('a-longer-path')).to.equal('aDashlongerDashpath');
});

it('converts multiple `-` and `_` correctly', () => {
    expect(sdk.naming.getNormalizedWebsocketsRouteKey('a-long_er-path_still')).to.equal('aDashlongUnderscoreerDashpathUnderscorestill');
});
```

**Comment by medikoo** [comment]
@tom-marsh thanks for report.

`some-api-route` is an invalid websockets route name. See https://serverless.com/framework/docs/providers/aws/events/websocket/#websocket

Fact that it works for you with offline plugin, is lack of validation (and probably some other issues which are not self evident).

Ideally framework should pick that error upfront when validating the configuration, and report it to you meaningfully. Schema backed validation is discussed at https://github.com/serverless/serverless/issues/6562

**Comment by tom-marsh** [comment]
@medikoo thanks for your prompt response.

Could you point out where in the supplied documentation link (https://serverless.com/framework/docs/providers/aws/events/websocket/#websocket) it specifies restrictions on WebSocket custom routes?

The only restriction I can find from Amazon's documentation is https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-add-route.html, but that only says to not use routes prefixed with '$' as those routes are reserved.

**Comment by medikoo** [comment]
Serveless doesn't validate the route name (and doesn't document validation rules). It's in a scope of AWS SDK, the error you see, comes directly from AWS SDK.

**Comment by tom-marsh** [comment]
In that case, could you point out where AWS specifies valid WebSocket route names? Why is one dash valid, but not two?

The error coming from the AWS SDK shows that the WebSocket route hasn't been fully escaped: in the .yml it is "some-api-route", in the error it is "someDashapi-route" - the second dash hasn't been escaped, the reason for which is clear from the code I supplied - JavaScript's `.replace` function only replaces all occurrences if it is supplied a regex, not a string.

**Comment by medikoo** [comment]
@tom-marsh indeed normalization logic is broken as you point (sorry I missed your point in initial description).

PR that fixes that is definitely welcome!

**Comment by preshetin** [comment]
@tom-marsh would you like to make a pull request for this? If not, I could make it. Seems like all code is already posted in your initial message.

**Comment by tom-marsh** [comment]
Apologies for the delay, see above for the pull request.
