### ISSUE TITLE
security token included in the request is invalid

### ISSUE THREAD

**Issue by Aravind1729** [serverless/serverless#7267]
# Bug Report

## Description

1. What did you do?
installed serverless 1.61.3 for my project The error did not happen with 1.61.2
1. What happened?
I get the error:
Serverless Error ---------------------------------------

  The security token included in the request is invalid.

1. What should've happened?
should have started my service locally
1. What's the content of your `serverless.yml` file?
trying out the following command to start my service locally
serverless offline start --region=eu-west-1 --env=local --noAuth
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

  Serverless Error ---------------------------------------

  ServerlessError: The security token included in the request is invalid.
      at serverless.getProvider.request.then.catch.err (C:\myProjects\event-hub\node_modules\serverless\lib\classes\Variables.js:836:35)
  From previous event:
      at Variables.getValueFromSsm (C:\myProjects\event-hub\node_modules\serverless\lib\classes\Variables.js:834:13)
      at Variables.getValueFromSource (C:\myProjects\event-hub\node_modules\serverless\lib\classes\Variables.js:567:17)
      at Variables.splitAndGet (C:\myProjects\event-hub\node_modules\serverless\lib\classes\Variables.js:436:17)
      at _.map.match (C:\myProjects\event-hub\node_modules\serverless\lib\classes\Variables.js:373:41)
      at arrayMap (C:\myProjects\event-hub\node_modules\lodash\lodash.js:639:23)
      at Function.map (C:\myProjects\event-hub\node_modules\lodash\lodash.js:9554:14)
      at Variables.populateMatches (C:\myProjects\event-hub\node_modules\serverless\lib\classes\Variables.js:373:14)
      at Variables.populateValue (C:\myProjects\event-hub\node_modules\serverless\lib\classes\Variables.js:404:30)
      at _.map.variable (C:\myProjects\event-hub\node_modules\serverless\lib\classes\Variables.js:286:12)
      at arrayMap (C:\myProjects\event-hub\node_modules\lodash\lodash.js:639:23)
      at Function.map (C:\myProjects\event-hub\node_modules\lodash\lodash.js:9554:14)
      at Variables.populateVariables (C:\myProjects\event-hub\node_modules\serverless\lib\classes\Variables.js:285:14)
      at Variables.populateObjectImpl (C:\myProjects\event-hub\node_modules\serverless\lib\classes\Variables.js:318:30)
      at prepopulateService.then (C:\myProjects\event-hub\node_modules\serverless\lib\classes\Variables.js:199:16)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:120:23)
  From previous event:
      at initialCall (C:\myProjects\event-hub\node_modules\serverless\lib\classes\Variables.js:198:10)
      at Variables.initialCall (C:\myProjects\event-hub\node_modules\serverless\lib\classes\Variables.js:102:12)
      at Variables.populateService (C:\myProjects\event-hub\node_modules\serverless\lib\classes\Variables.js:196:17)
      at Serverless.run (C:\myProjects\event-hub\node_modules\serverless\lib\Serverless.js:120:27)
      at serverless.init.then (C:\myProjects\event-hub\node_modules\serverless\bin\serverless.js:75:30)
      at C:\myProjects\event-hub\node_modules\graceful-fs\graceful-fs.js:136:16
      at C:\myProjects\event-hub\node_modules\graceful-fs\graceful-fs.js:57:14
      at FSReqWrap.oncomplete (fs.js:141:20)
  From previous event:
      at initializeErrorReporter.then (C:\myProjects\event-hub\node_modules\serverless\bin\serverless.js:75:8)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:120:23)
  From previous event:
      at Object.<anonymous> (C:\myProjects\event-hub\node_modules\serverless\bin\serverless.js:64:4)
      at Module._compile (internal/modules/cjs/loader.js:689:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
      at Module.load (internal/modules/cjs/loader.js:599:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
      at Function.Module._load (internal/modules/cjs/loader.js:530:3)
      at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
      at startup (internal/bootstrap/node.js:283:19)
      at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

Similar or dependent issues:

- #12345

**Comment by medikoo** [comment]
@Aravind1729 thanks for report. It's already fixed with #7265 and will be published to npm shortly

Closing as duplicate of https://github.com/serverless/serverless/issues/7255

**Comment by 1Priyanka** [comment]
Deploying student-service to stage dev (us-west-2)

× Stack student-service-stack-dev failed to deploy (1s)
Environment: win32, node 16.14.2, framework 3.22.0 (local) 3.22.0v (global), plugin 6.2.2, SDK 4.3.2
Credentials: Local, "sls" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
The security token included in the request is invalid.







?????????????????????/
How can solve it here
