### ISSUE TITLE
v4.2: serverless project create => Error: EEXIST: file already exists, mkdir

### ISSUE THREAD

**Issue by fardelian** [serverless/serverless#731]
The starter project (`serverless project install serverless-starter`) works fine, but I'm getting a file (directory) already exists error every time I try to create a new project from scratch, both with the default random name and with a custom name.

```
$ cat /etc/issue
Ubuntu 15.10 \n \l
$ node -v
v4.3.2
$ serverless -v
0.4.2
$ serverless project create
 _______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.                                                                                                                                                        
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|                                                                                                                                                        
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|                                                                                                                                                        
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v0.4.2
`-------'

Serverless: Initializing Serverless Project...  
Serverless: Enter a name for this project:  (serverless-ejg1pi) 
Serverless: Enter a universally unique project bucket name:  (serverless-ejg1pi) 
Serverless: Enter an email to use for AWS alarms:  (me@serverless-ejg1pi.com) *redacted*
Serverless: Enter the ACCESS KEY ID for your Admin AWS IAM User:  *redacted*
Serverless: Enter the SECRET ACCESS KEY for your Admin AWS IAM User:  *redacted*
Serverless: Select a region for your project: 
  > us-east-1
    us-west-2
    eu-west-1
    ap-northeast-1
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

Error: EEXIST: file already exists, mkdir '/home/f/workspace/serverless-ejg1pi'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at /usr/local/lib/node_modules/serverless/lib/ServerlessProject.js:331:12
From previous event:
    at ServerlessProject.save (/usr/local/lib/node_modules/serverless/lib/ServerlessProject.js:327:12)
    at ServerlessState.save (/usr/local/lib/node_modules/serverless/lib/ServerlessState.js:52:26)
    at /usr/local/lib/node_modules/serverless/lib/actions/ProjectInit.js:387:32
From previous event:
    at ProjectInit._scaffold (/usr/local/lib/node_modules/serverless/lib/actions/ProjectInit.js:351:27)
From previous event:
    at ProjectInit.projectInit (/usr/local/lib/node_modules/serverless/lib/actions/ProjectInit.js:118:10)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:181:25
    at Array.reduce (native)
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:180:26)
    at Object.actions.(anonymous function) [as projectInit] (/usr/local/lib/node_modules/serverless/lib/Serverless.js:381:20)
    at ProjectCreate.createProject (/usr/local/lib/node_modules/serverless/lib/actions/ProjectCreate.js:95:29)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:156:29
    at Array.reduce (native)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:155:30
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:153:10)
    at Serverless.actions.(anonymous function) (/usr/local/lib/node_modules/serverless/lib/Serverless.js:381:20)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:350:38)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:16:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3

```

**Comment by fardelian** [comment]
[As suggested by egnsh93 in the Gitter chatroom:](https://gitter.im/serverless/serverless?at=56d9bd34ddfe3d431627b21a)
> Another option if you want to create a project inside that directory (so long as there are no pre-existing files in there), you could run project init.

A work-around for this issue is to create an empty directory and run `serverless project init`. This worked for me with serverless v0.4.2.

**Comment by fardelian** [comment]
It appears that serverless project init creates the project directory, contrary to what the documentation says.

Code:
(the AWS key error was expected since I just put in `a` and `b` to pass the validation)
```
f@f-desktop:~/workspace$ mkdir serverless-test-2
f@f-desktop:~/workspace$ cd serverless-test-2
f@f-desktop:~/workspace/serverless-test-2$ serverless project init
 _______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v0.4.2
`-------'

Serverless: Initializing Serverless Project...  
Serverless: Enter a name for this project:  (serverless-vye5sm) 
Serverless: Enter a universally unique project bucket name:  (serverless-vye5sm) 
Serverless: Enter an email to use for AWS alarms:  (me@serverless-vye5sm.com) 
Serverless: Enter the ACCESS KEY ID for your Admin AWS IAM User:  a
Serverless: Enter the SECRET ACCESS KEY for your Admin AWS IAM User:  b
Serverless: Select a region for your project: 
  > us-east-1
    us-west-2
    eu-west-1
    ap-northeast-1
Serverless: Creating stage "dev"...  
Serverless: Creating region "us-east-1" in stage "dev"...  
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

ServerlessError: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/ServerlessError.js:17:11)
    at /usr/local/lib/node_modules/serverless/lib/utils/aws/S3.js:87:17
    at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:680:18)
    at Async._drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:126:16)
    at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
f@f-desktop:~/workspace/serverless-test-2$ ls -al
total 12
drwxrwxr-x 3 f f 4096 mar  7 16:47 .
drwxrwxr-x 7 f f 4096 mar  7 16:47 ..
drwxrwxr-x 3 f f 4096 mar  7 16:47 serverless-vye5sm
f@f-desktop:~/workspace/serverless-test-2$ ls -al serverless-vye5sm/
total 96
drwxrwxr-x 3 f f 4096 mar  7 16:47 .
drwxrwxr-x 3 f f 4096 mar  7 16:47 ..
-rw-rw-r-- 1 f f   78 mar  7 16:47 admin.env
-rw-rw-r-- 1 f f   94 mar  7 16:47 .env
-rw-rw-r-- 1 f f  625 mar  7 16:47 .gitignore
drwxrwxr-x 4 f f 4096 mar  7 16:47 _meta
-rw-rw-r-- 1 f f  289 mar  7 16:47 package.json
-rw-rw-r-- 1 f f   18 mar  7 16:47 README.md
-rw-rw-r-- 1 f f  229 mar  7 16:47 s-project.json
-rw-rw-r-- 1 f f 1527 mar  7 16:47 s-resources-cf.json
f@f-desktop:~/workspace/serverless-test-2$ cat s-project.json 
{
  "name": "serverless-vye5sm",
  "version": "0.0.1",
  "profile": "serverless-v0.4.2",
  "location": "https://github.com/...",
  "author": "",
  "description": "A Slick New Serverless Project",
  "custom": {},
  "plugins": []
}f@f-desktop:~/workspace/serverless-test-2/serverless-vye5sm$ 
```

I was in `~/workspace/serverless-test-2` and I ran `serverless project init` which created the directory with the name of the project (the project name above was randomly generated, but the same happens if I specify the name of the current directory as project name, I already tried that).

[Documentation:](http://docs.serverless.com/docs/project-install)

>**Must be run within a Serverless Project.** Initializes a new Serverless project. It's useful when you `git clone` a Serverless project, and want to reconstruct the `_meta` folder and set up the project on AWS. It takes the following options:
>[..]
>After you `git clone` a Serverless Project and `cd` inside the root directory of the project. You can run `serverless project init` to reconstruct the gitignored `_meta` folder and set up your project on your own AWS account.

A work-around for this problem in v0.4.2 is to go in some temporary directory, run `serverless project init` and give it the name of our cloned project, then move the contents of the newly created directory into our cloned project directory.

**Comment by flomotlik** [comment]
Hi @fardelian, we're working on a change in V1 of the framework to remove the project concept and simply allow you to create a service. We will fix this with those upcoming changes. I will close this issue for now as it will be fixed in upcoming versions.
