### ISSUE TITLE
YAML Block Scalar causes JSON syntax error

### ISSUE THREAD

**Issue by IslandUsurper** [serverless/serverless#7312]
# Bug Report

## Description

1. What did you do?
I wanted to make a multiline description for a `schedule` event.
1. What happened?
Serverless translated it to bad JSON, instead of turning into the string it should be.
1. What should've happened?
YAMLs rules for multiline strings are complex (https://yaml-multiline.info/), and if converting to JSON, it should be output according to the YAML spec so that newlines and quotes are handled correctly.
1. What's the content of your `serverless.yml` file?
```yaml
functions:
  notifier:
    handler: back-in-stock.notifier
    events:
      - schedule:
          name: inventory-watcher
          description: >
              Looks for subscribed products to see if they are in
              stock yet, sending a notification if it has been.
          rate: rate(15 minutes)
          enabled: true
```
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

```
 SyntaxError: Unexpected token 
   in JSON at position 374
      at JSON.parse (<anonymous>)
      at functionObj.events.forEach.event (/nix/store/qbvb4l2wghcvcnnbxf37max6n5zqb4g4-node_serverless-1.60.4/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/schedule/index.js:145:41)
      at Array.forEach (<anonymous>)
      at serverless.service.getAllFunctions.forEach.functionName (/nix/store/qbvb4l2wghcvcnnbxf37max6n5zqb4g4-node_serverless-1.60.4/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/schedule/index.js:34:28)
      at Array.forEach (<anonymous>)
      at AwsCompileScheduledEvents.compileScheduledEvents (/nix/store/qbvb4l2wghcvcnnbxf37max6n5zqb4g4-node_serverless-1.60.4/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/schedule/index.js:29:47)
      at BbPromise.reduce (/nix/store/qbvb4l2wghcvcnnbxf37max6n5zqb4g4-node_serverless-1.60.4/lib/node_modules/serverless/lib/classes/PluginManager.js:490:55)
      at tryCatcher (/nix/store/qbvb4l2wghcvcnnbxf37max6n5zqb4g4-node_serverless-1.60.4/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/nix/store/qbvb4l2wghcvcnnbxf37max6n5zqb4g4-node_serverless-1.60.4/lib/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:168:18)
      at Object.gotAccum (/nix/store/qbvb4l2wghcvcnnbxf37max6n5zqb4g4-node_serverless-1.60.4/lib/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (/nix/store/qbvb4l2wghcvcnnbxf37max6n5zqb4g4-node_serverless-1.60.4/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/nix/store/qbvb4l2wghcvcnnbxf37max6n5zqb4g4-node_serverless-1.60.4/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/nix/store/qbvb4l2wghcvcnnbxf37max6n5zqb4g4-node_serverless-1.60.4/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/nix/store/qbvb4l2wghcvcnnbxf37max6n5zqb4g4-node_serverless-1.60.4/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/nix/store/qbvb4l2wghcvcnnbxf37max6n5zqb4g4-node_serverless-1.60.4/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/nix/store/qbvb4l2wghcvcnnbxf37max6n5zqb4g4-node_serverless-1.60.4/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/nix/store/qbvb4l2wghcvcnnbxf37max6n5zqb4g4-node_serverless-1.60.4/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/nix/store/qbvb4l2wghcvcnnbxf37max6n5zqb4g4-node_serverless-1.60.4/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/nix/store/qbvb4l2wghcvcnnbxf37max6n5zqb4g4-node_serverless-1.60.4/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)
```

**Comment by medikoo** [comment]
@IslandUsurper thanks for report. To parse config we rely on  `js-yaml` YAML parser -> https://github.com/nodeca/js-yaml#js-yaml---yaml-12-parser--writer-for-javascript

If you feel that parser doesn't comply to YAML spec, best would be to report an issue at its repository.

**Comment by zhaobao** [comment]
@IslandUsurper Do you solve this problem? we also encounter the same one

**Comment by IslandUsurper** [comment]
@zhaobao, I used the workaround to have the whole description on one line, like any other YAML value:

```yaml
          description: Looks for subscribed products to see if they are in stock yet, sending a notification if it has been.
```
