### ISSUE TITLE
Invoke local fails if function path contains '.'

### ISSUE THREAD

**Issue by thejuan** [serverless/serverless#7330]
# Bug Report

## Description

We output our typescript build to .build directory.
Our functions reference this directory i.e. `handler: .build/handler.doSomething`
invoke splits on '.' and doesn't get our paths correct.
Would be good if it split out the file portion before splitting on '.'

**Comment by yyylksdy** [comment]
i cannot reproduce this bug. my build directory called edge. and i changed to .edge and it did deploy well.

**Comment by arbbakbenny** [comment]
Didn't test deployment but local function invocation indeed does not work if handler is refenced in folder which begins with dot. Basically given a folder structure
<pre>
projectRoot
|- .build/handler.js
|- serverless.yml
</pre>
where `serverless.yml` has following reference
<pre>
functions:
  hello:
    handler: .build/handler.hello
</pre>
trying to execute `serverless invoke local -f hello` on Windows 10 results with error 
<pre>
$ serverless invoke local -f hello
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Invoke invoke:local
Error: Cannot find module 'D:\aws\issue'
Require stack:
- C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js
- C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\lib\plugins\index.js
- C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js
- C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js
- C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\lib\utils\autocomplete.js
- C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\bin\serverless.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at AwsInvokeLocal.invokeLocalNodeJs (C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:667:33)
    at AwsInvokeLocal.invokeLocal (C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:178:19)
    at AwsInvokeLocal.tryCatcher (C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:130:23) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\{USER}\\AppData\\Roaming\\npm\\node_modules\\serverless\\lib\\plugins\\aws\\invokeLocal\\index.js',
    'C:\\Users\\{USER}\\AppData\\Roaming\\npm\\node_modules\\serverless\\lib\\plugins\\index.js',
    'C:\\Users\\{USER}\\AppData\\Roaming\\npm\\node_modules\\serverless\\lib\\classes\\PluginManager.js',
    'C:\\Users\\{USER}\\AppData\\Roaming\\npm\\node_modules\\serverless\\lib\\Serverless.js',
    'C:\\Users\\{USER}\\AppData\\Roaming\\npm\\node_modules\\serverless\\lib\\utils\\autocomplete.js',
    'C:\\Users\\{USER}\\AppData\\Roaming\\npm\\node_modules\\serverless\\bin\\serverless.js'
  ]
}

  Error --------------------------------------------------

  Error: Exception encountered when loading D:\aws\issue
      at AwsInvokeLocal.invokeLocalNodeJs (C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:672:13)
      at AwsInvokeLocal.invokeLocal (C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:178:19)
  From previous event:
      at Object.invoke:local:invoke [as hook] (C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:39:57)
      at C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:490:55
  From previous event:
      at PluginManager.invoke (C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:490:22)
      at C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:525:24
  From previous event:
      at PluginManager.run (C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:525:8)
      at C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:133:33
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:130:23)
  From previous event:
      at Serverless.run (C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:120:74)
      at C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\bin\serverless.js:75:30
      at C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\node_modules\graceful-fs\graceful-fs.js:136:16
      at C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\node_modules\graceful-fs\graceful-fs.js:57:14
      at FSReqCallback.oncomplete (fs.js:146:23)
  From previous event:
      at C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\bin\serverless.js:75:8
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:130:23)
  From previous event:
      at Object.<anonymous> (C:\Users\{USER}\AppData\Roaming\npm\node_modules\serverless\bin\serverless.js:64:4)
      at Module._compile (internal/modules/cjs/loader.js:955:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
      at Module.load (internal/modules/cjs/loader.js:811:32)
      at Function.Module._load (internal/modules/cjs/loader.js:723:14)
      at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
      at internal/main/run_main_module.js:17:11
</pre>
