### ISSUE TITLE
Layer Version Retain Option packages errors out with Export in resource

### ISSUE THREAD

**Issue by AnthonyWC** [serverless/serverless#7353]
# Bug Report

## Description

Try to have a Resource/Export with Layer and Retain: true would resolve in error (https://serverless.com/blog/publish-aws-lambda-layers-serverless-framework/) during deployment (but not in package).

```
Framework Core: 1.63.0
Plugin: 3.3.0
SDK: 2.3.0
Components Core: 1.1.2
Components CLI: 1.4.0
```
also tested w/ 1.61.3

1. What did you do?
Deploy without `retain: true` would succeed

1. What happened?
Deploy with `retain: true` would get:
```
Serverless: Validating template...

  Error --------------------------------------------------

  Error: The CloudFormation template is invalid: Unresolved resource dependencies [SrecommonLambdaLayer] in the Outputs block of the template
      at provider.request.catch.error (/node/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:20:13)
      at tryCatcher (/node/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/node/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/node/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/node/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/node/node_modules/bluebird/js/release/promise.js:725:18)
      at _drainQueueStep (/node/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/node/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/node/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/node/node_modules/bluebird/js/release/async.js:15:14)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)
```
1. What should've happened?

Deploy should succeed.

1. What's the content of your `serverless.yml` file?
```
service: sre-common-layer

provider:
  name: aws
  region: ${opt:region, 'us-west-2'}
  stage: ${opt:stage, 'dev'}

layers:
  srecommon:
    path: layer
    compatibleRuntimes: nodejs10.x
    retain: true

resources:
  Outputs:
    srecommonExport:
      Value:
        Ref: SrecommonLambdaLayer
      Export:
        Name: SrecommonLambdaLayer
```

Note: comparing context without and with retain:true in .serverless directory after package:

without option (works); grep for layer name:
```
cloudformation-template-update-stack.json:59:    "SrecommonLambdaLayer": {
cloudformation-template-update-stack.json:79:    "SrecommonLambdaLayerQualifiedArn": {
cloudformation-template-update-stack.json:82:        "Ref": "SrecommonLambdaLayer"
cloudformation-template-update-stack.json:87:        "Ref": "SrecommonLambdaLayer"
cloudformation-template-update-stack.json:90:        "Name": "SrecommonLambdaLayer"
serverless-state.json:76:          "SrecommonLambdaLayer": {
serverless-state.json:96:          "SrecommonLambdaLayerQualifiedArn": {
serverless-state.json:99:              "Ref": "SrecommonLambdaLayer"
serverless-state.json:104:              "Ref": "SrecommonLambdaLayer"
serverless-state.json:107:              "Name": "SrecommonLambdaLayer"
serverless-state.json:189:            "Ref": "SrecommonLambdaLayer"
serverless-state.json:192:            "Name": "SrecommonLambdaLayer"
```

with option (fails):
```
cloudformation-template-update-stack.json:59:    "SrecommonLambdaLayer72b91de74837ad1cde18556962c2c3ffa1e8b15a": {
cloudformation-template-update-stack.json:80:    "SrecommonLambdaLayerQualifiedArn": {
cloudformation-template-update-stack.json:83:        "Ref": "SrecommonLambdaLayer72b91de74837ad1cde18556962c2c3ffa1e8b15a"
cloudformation-template-update-stack.json:88:        "Ref": "SrecommonLambdaLayer"
cloudformation-template-update-stack.json:91:        "Name": "SrecommonLambdaLayer"
serverless-state.json:76:          "SrecommonLambdaLayer72b91de74837ad1cde18556962c2c3ffa1e8b15a": {
serverless-state.json:97:          "SrecommonLambdaLayerQualifiedArn": {
serverless-state.json:100:              "Ref": "SrecommonLambdaLayer72b91de74837ad1cde18556962c2c3ffa1e8b15a"
serverless-state.json:105:              "Ref": "SrecommonLambdaLayer"
serverless-state.json:108:              "Name": "SrecommonLambdaLayer"
serverless-state.json:190:            "Ref": "SrecommonLambdaLayer"
serverless-state.json:193:            "Name": "SrecommonLambdaLayer"
```
See attached zip
[fail.zip](https://github.com/serverless/serverless/files/4216169/fail.zip)
[work.zip](https://github.com/serverless/serverless/files/4216171/work.zip)

Similar or dependent issues:

- #6769 
- #6943

**Comment by AnthonyWC** [comment]
Guessing based on the cloudformation template it looks like with option, it has inconsistent naming with it would sometimes reference the name without the random number.

**Comment by medikoo** [comment]
@AnthonyWC thanks for reporting that. PR with a fix is welcome!

**Comment by thkapasi** [comment]
Hi

When `retain: true` is set there, in `lib/plugins/aws/package/compile/layers/index.js` line 69

```
      if (layerObject.retain) {
        layerLogicalId = `${layerLogicalId}${sha}`;
        newLayer.DeletionPolicy = 'Retain';
      }
```

appends a random id to the cloudformation resource name for the lambda layer thus breaking other cfn references to it.

As a workaround, set `retain: false`

and in the CFN Resources section add:

```
layers:
  YOURLAYER:
    retain: false 
...

resources:
  Resources: 
    YOURLAYERLambdaLayer:
      UpdateReplacePolicy: Retain
```

works and tested with 1.71.3

**Comment by medikoo** [comment]
Closing, as it's not really a bug, but fact that a different resource id is created when `retain: true` is set, and that made user configuration mismatching.

It's more a design issue, and if there's any idea on how to improve we're open to discuss it.
