### ISSUE TITLE
sls deploy fails when unrelated file is locked

### ISSUE THREAD

**Issue by BryanCrotaz** [serverless/serverless#7380]
# Bug Report

## Description

Using Visual Studio 2019 with a c# project generated by `sls create`

`sls deploy` when VS2019 is not running works nicely. When VS2019 has the solution open I get
```
  Error: EBUSY: resource busy or locked, scandir 'C:\projects\led-monitor\.vs\aws-csharp\v16\Server\sqlite3\db.lock'
      at Package.resolveFilePathsFunction (c:\Users\Einstein\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\plugins\package\lib\packageService.js:213:8)
      at Package.packageFunction (c:\Users\Einstein\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\plugins\package\lib\packageService.js:168:17)
      at c:\Users\Einstein\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\plugins\package\lib\packageService.js:77:21
      at arrayMap (c:\Users\Einstein\AppData\Local\Yarn\Data\global\node_modules\lodash\lodash.js:639:23)
      at Function.map (c:\Users\Einstein\AppData\Local\Yarn\Data\global\node_modules\lodash\lodash.js:9554:14)
      at Package.packageService (c:\Users\Einstein\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\plugins\package\lib\packageService.js:66:29)
  From previous event:
      at Object.package:createDeploymentArtifacts [as hook] (c:\Users\Einstein\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\plugins\package\package.js:58:71)
      at c:\Users\Einstein\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\classes\PluginManager.js:490:55
  From previous event:
      at PluginManager.invoke (c:\Users\Einstein\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\classes\PluginManager.js:490:22)
      at PluginManager.spawn (c:\Users\Einstein\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\classes\PluginManager.js:510:17)
      at Deploy.<anonymous> (c:\Users\Einstein\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\plugins\deploy\deploy.js:115:50)
  From previous event:
      at Object.before:deploy:deploy [as hook] (c:\Users\Einstein\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\plugins\deploy\deploy.js:100:30)
      at c:\Users\Einstein\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\classes\PluginManager.js:490:55
  From previous event:
      at PluginManager.invoke (c:\Users\Einstein\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\classes\PluginManager.js:490:22)
      at c:\Users\Einstein\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\classes\PluginManager.js:525:24
  From previous event:
      at PluginManager.run (c:\Users\Einstein\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\classes\PluginManager.js:525:8)
      at c:\Users\Einstein\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\Serverless.js:133:33
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:131:23)
  From previous event:
      at Serverless.run (c:\Users\Einstein\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\Serverless.js:120:74)
      at c:\Users\Einstein\AppData\Local\Yarn\Data\global\node_modules\serverless\bin\serverless.js:75:30
      at c:\Users\Einstein\AppData\Local\Yarn\Data\global\node_modules\serverless\node_modules\fs-extra\node_modules\graceful-fs\graceful-fs.js:136:16
      at c:\Users\Einstein\AppData\Local\Yarn\Data\global\node_modules\serverless\node_modules\graceful-fs\graceful-fs.js:136:16
      at c:\Users\Einstein\AppData\Local\Yarn\Data\global\node_modules\serverless\node_modules\graceful-fs\graceful-fs.js:57:14
      at FSReqCallback.oncomplete (fs.js:157:23)
  From previous event:
      at c:\Users\Einstein\AppData\Local\Yarn\Data\global\node_modules\serverless\bin\serverless.js:75:8
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:131:23)
  From previous event:
      at Object.<anonymous> (c:\Users\Einstein\AppData\Local\Yarn\Data\global\node_modules\serverless\bin\serverless.js:64:4)
      at Module._compile (internal/modules/cjs/loader.js:945:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
      at Module.load (internal/modules/cjs/loader.js:798:32)
      at Function.Module._load (internal/modules/cjs/loader.js:711:12)
      at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
      at internal/main/run_main_module.js:17:11
```

serverless.yml
```
service: my-monitor

provider:
  name: aws
  runtime: dotnetcore2.1

package:
  individually: true
  exclude: 
    - ./.vs

functions:
  auth:
    handler: AuthApi::Api.AuthHandlers::Authorize

  hello:
    handler: AuthApi::Api.UserHandlers::Hello
    events:
      - http:
          path: hello/world
          method: get
          cors: true

    package:
      artifact: bin/release/netcoreapp2.1/hello.zip
```

**Comment by medikoo** [comment]
I think you're exclude rule should be:

```yaml
  exclude: 
    - .vs/**
```

Having that, I believe there should be no attempt to package files in `.vs` folder

**Comment by BryanCrotaz** [comment]
Made that change:
```
package:
  individually: true
  exclude: 
    - .vs/**
```
Same error occurs

**Comment by medikoo** [comment]
@BryanCrotaz thanks for checking. Indeed it could be the case, as we imply excludes manually after running glob (which crashes in your case), here: https://github.com/serverless/serverless/blob/8518000d4fbf3a6cf0a6e2f81bd6421e017a1b5f/lib/plugins/package/lib/packageService.js#L262-L267

It'll definitely will be fixed with https://github.com/serverless/serverless/issues/6580 still that won't be delivered soon, therefore a patch that addresses this problem specifically is welcome

**Comment by BryanCrotaz** [comment]
Where should I start looking in the codebase for a suitable place to introduce the excludes?

**Comment by medikoo** [comment]
> Where should I start looking in the codebase for a suitable place to introduce the excludes?

I pointed the problematic part in above comment. Technically excludes are handled after we receive list of all files via glob

**Comment by BryanCrotaz** [comment]
But as you say, that's way too late. Where should the excludes be processed earlier in the chain? Is there a plugin that's scanning for locked files for example?

**Comment by medikoo** [comment]
> But as you say, that's way too late. Where should the excludes be processed earlier in the chain

That needs to be inspected. Ideally glob invocation already should take into account, but I believe there was some reasons why it's not done that way (to be investigated why).

**Comment by BryanCrotaz** [comment]
What's the temporary workaround? Don't try and deploy while VS running?
