### ISSUE TITLE
No file matches include / exclude patterns error on deploying serverless application

### ISSUE THREAD

**Issue by jyotsana-arora** [serverless/serverless#7397]
# Bug Report

## Description

When I am deploying(sls deploy) my serverless application using nodejs with layers, I got the error.
No file matches include / exclude patterns

1. What did you do?
Deploying a serverless application with layers using nodejs

1. What happened?
Serverless Error ---------------------------------------
 
  No file matches include / exclude patterns

1. What should've happened?
Application will successfully deployed.

1. What's the content of your `serverless.yml` file?
functions:
  api:
    handler: src/server.handler
    layers:
      - { Ref: NodemodulesLambdaLayer }
    events:
      - http:
          path: /{proxy+}
          method: ANY

layers:
  nodemodules:
    name: ${self:service}-${self:provider.stage}-nodemodules
    path: .build-node-modules

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
Serverless Error ---------------------------------------
 
  ServerlessError: No file matches include / exclude patterns
      at /home/jyotsana/VSCodeProjects/AiMedia/ToolsetProxy/TIG-704/toolset-proxy/api/node_modules/serverless/lib/plugins/package/lib/packageService.js:273:13
  From previous event:
      at /home/jyotsana/VSCodeProjects/AiMedia/ToolsetProxy/TIG-704/toolset-proxy/api/node_modules/graceful-fs/graceful-fs.js:115:16
      at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
  From previous event:
      at Package.resolveFilePathsLayer (/home/jyotsana/VSCodeProjects/AiMedia/ToolsetProxy/TIG-704/toolset-proxy/api/node_modules/serverless/lib/plugins/package/lib/packageService.js:226:8)
      at Package.packageLayer (/home/jyotsana/VSCodeProjects/AiMedia/ToolsetProxy/TIG-704/toolset-proxy/api/node_modules/serverless/lib/plugins/package/lib/packageService.js:181:17)
      at /home/jyotsana/VSCodeProjects/AiMedia/ToolsetProxy/TIG-704/toolset-proxy/api/node_modules/serverless/lib/plugins/package/lib/packageService.js:90:21
      at arrayMap (/home/jyotsana/VSCodeProjects/AiMedia/ToolsetProxy/TIG-704/toolset-proxy/api/node_modules/lodash/lodash.js:639:23)
      at Function.map (/home/jyotsana/VSCodeProjects/AiMedia/ToolsetProxy/TIG-704/toolset-proxy/api/node_modules/lodash/lodash.js:9554:14)
      at Package.packageService (/home/jyotsana/VSCodeProjects/AiMedia/ToolsetProxy/TIG-704/toolset-proxy/api/node_modules/serverless/lib/plugins/package/lib/packageService.js:84:9)
  From previous event:
      at Object.package:createDeploymentArtifacts [as hook] (/home/jyotsana/VSCodeProjects/AiMedia/ToolsetProxy/TIG-704/toolset-proxy/api/node_modules/serverless/lib/plugins/package/package.js:58:71)
      at /home/jyotsana/VSCodeProjects/AiMedia/ToolsetProxy/TIG-704/toolset-proxy/api/node_modules/serverless/lib/classes/PluginManager.js:490:55
  From previous event:
      at PluginManager.invoke (/home/jyotsana/VSCodeProjects/AiMedia/ToolsetProxy/TIG-704/toolset-proxy/api/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at /home/jyotsana/VSCodeProjects/AiMedia/ToolsetProxy/TIG-704/toolset-proxy/api/node_modules/serverless/lib/classes/PluginManager.js:525:24
  From previous event:
      at PluginManager.run (/home/jyotsana/VSCodeProjects/AiMedia/ToolsetProxy/TIG-704/toolset-proxy/api/node_modules/serverless/lib/classes/PluginManager.js:525:8)
      at /home/jyotsana/VSCodeProjects/AiMedia/ToolsetProxy/TIG-704/toolset-proxy/api/node_modules/serverless/lib/Serverless.js:133:33
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:131:23)
  From previous event:
      at Serverless.run (/home/jyotsana/VSCodeProjects/AiMedia/ToolsetProxy/TIG-704/toolset-proxy/api/node_modules/serverless/lib/Serverless.js:120:74)
      at /home/jyotsana/VSCodeProjects/AiMedia/ToolsetProxy/TIG-704/toolset-proxy/api/node_modules/serverless/bin/serverless.js:75:30
      at /home/jyotsana/VSCodeProjects/AiMedia/ToolsetProxy/TIG-704/toolset-proxy/api/node_modules/graceful-fs/graceful-fs.js:136:16
      at /home/jyotsana/VSCodeProjects/AiMedia/ToolsetProxy/TIG-704/toolset-proxy/api/node_modules/graceful-fs/graceful-fs.js:57:14
      at FSReqCallback.oncomplete (fs.js:146:23)
  From previous event:
      at /home/jyotsana/VSCodeProjects/AiMedia/ToolsetProxy/TIG-704/toolset-proxy/api/node_modules/serverless/bin/serverless.js:75:8
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:131:23)
  From previous event:
      at Object.<anonymous> (/home/jyotsana/VSCodeProjects/AiMedia/ToolsetProxy/TIG-704/toolset-proxy/api/node_modules/serverless/bin/serverless.js:64:4)
      at Module._compile (internal/modules/cjs/loader.js:956:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
      at Module.load (internal/modules/cjs/loader.js:812:32)
      at Function.Module._load (internal/modules/cjs/loader.js:724:14)
      at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
      at internal/main/run_main_module.js:17:11

Similar or dependent issues:
https://github.com/serverless/serverless/issues/5892

**Comment by jyotsana-arora** [comment]
I resolved it by removing the plugin
`serverless-plugin-typescript`
from the serverless.yml file.

**Comment by stevematdavies** [comment]
I have this same issue, with layers, and if I remove the layers all is fine but with layers, it fails with the same error. It appears to be a long-running issue with little solution. Too many of the layers tutorials focus on deploying new layers with the serverless file and not on existing layers which is what I need

**Comment by rob-bar** [comment]
How can a plugin block this layers behaviour? Must be an issue with the plugin then? 
When I remove the plugin it works fine.
