### ISSUE TITLE
Can't deploy to AWS China regions

### ISSUE THREAD

**Issue by bnusunny** [serverless/serverless#7480]
# Bug Report

## Description

1. What did you do?
create an simple lambda function using aws-nodejs sample. 
Deploy the application using sls deploy.

1. What happened?

Received error saying security token is invalid. I did have IAM admin AK/SK configured for AWS China regions. 

```bash
8c85909aaff7:serverless-aws-nodejs sunhua$ aws sts get-caller-identity --profile china --region cn-northwest-1
{
    "Account": "xxxxxxxxxxxxx",
    "UserId": "AIDAOUZ3VMBZOM4GMPZ7E",
    "Arn": "arn:aws-cn:iam::xxxxxxxxxxxxx:user/admin"
}
8c85909aaff7:serverless-aws-nodejs sunhua$ sls deploy --profile china --region cn-northwest-1
Serverless: Packaging service...
Serverless: Excluding development dependencies...

  Serverless Error ---------------------------------------

  The security token included in the request is invalid.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.16.1
     Framework Version:         1.66.0
     Plugin Version:            3.5.0
     SDK Version:               2.3.0
     Components Version:        2.22.3


```
1. What should've happened?

The deploy should succeed. 

1. What's the content of your `serverless.yml` file?

```

service: projects

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: cn-northwest-1
  endpointType: REGIONAL

functions:
  hello:
    handler: handler.hello


```

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 403 1.528s 0 retries] describeStacks({ StackName: 'projects-dev' })

  Serverless Error ---------------------------------------

  ServerlessError: The security token included in the request is invalid.
      at /Users/sunhua/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:331:27
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.16.1
     Framework Version:         1.66.0
     Plugin Version:            3.5.0
     SDK Version:               2.3.0
     Components Version:        2.22.3
```

**Comment by medikoo** [comment]
@bnusunny thanks for report. Such error happens if security token as provided in AWS credentials is outdated. Are you sure your credentials configuration is up to date?

**Comment by bnusunny** [comment]
@medikoo Yes, I'm sure my credential is up to date. As you can see the following tests. I can use aws cli to get back my sts identity, and immediately after that, I do the deploy, it fails. 

```bash

8c85909aaff7:serverless-aws-nodejs sunhua$ aws sts get-caller-identity --profile china --region cn-northwest-1
{
    "Account": "xxxxxxxxxxxxx",
    "UserId": "AIDAOUZ3VMBZOM4GMPZ7E",
    "Arn": "arn:aws-cn:iam::xxxxxxxxxxxxx:user/admin"
}
8c85909aaff7:serverless-aws-nodejs sunhua$ sls deploy --profile china --region cn-northwest-1
Serverless: Packaging service...
Serverless: Excluding development dependencies...

  Serverless Error ---------------------------------------

  The security token included in the request is invalid.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.16.1
     Framework Version:         1.66.0
     Plugin Version:            3.5.0
     SDK Version:               2.3.0
     Components Version:        2.22.3



```

**Comment by medikoo** [comment]
Thanks @bnusunny for futher clarifications. It's probably an issue with hardcoded AWS partition (`:aws:` token) sowewhere.

We'll try to look into it shortly. Otherwise if anyone has quick idea where's the source of a problem PR with a fix is welcome!

**Comment by drexler** [comment]
@bnusunny  i see you deploying with `sls deploy --profile china --region cn-northwest-1`

does the following work for you?: 
`sls deploy --aws-profile china --region cn-northwest-1`

**Comment by bnusunny** [comment]
It works! Thanks for pointing out my mistake. 

Closing this issue.

**Comment by huangyanxiong01** [comment]
thanks
