### ISSUE TITLE
Dockerfile layer path invalid

### ISSUE THREAD

**Issue by stevebaldwinelectroneum** [serverless/serverless#7489]
# Bug Report

`serverless -v`

```
Framework Core: 1.66.0
Plugin: 3.5.0
SDK: 2.3.0
Components: 2.22.3
```

When running serverless on windows, the path in the Dockerfile is incorrect for the layer being used.

```
FROM lambci/lambda:provided
ADD --chown=sbx_user1051:495 .serverless\layers\php-73\20 /opt
```

instead of 

```
FROM lambci/lambda:provided
ADD --chown=sbx_user1051:495 .serverless/layers/php-73/20 /opt
```

## Description

1. What did you do?

Ran `serverless invoke local --docker -f function --data '{"name": "test" }'`

1. What happened?

```
Serverless: Writing Dockerfile...
Serverless: Building Docker image...
Sending build context to Docker daemon   88.6MB
Step 1/2 : FROM lambci/lambda:provided
 ---> 1aa9e9fecf65
Step 2/2 : ADD --chown=sbx_user1051:495 .serverless\layers\php-73\20 /opt
ADD failed: stat /var/lib/docker/tmp/docker-builder840273559/.serverlesslayersphp-7320: no such file
```

1. What should've happened?

```
Serverless: Building Docker image...
START RequestId: 6613c8ad-0d3a-1eef-9a77-1d9e3e697b1d Version: $LATEST
END RequestId: 6613c8ad-0d3a-1eef-9a77-1d9e3e697b1d
REPORT RequestId: 6613c8ad-0d3a-1eef-9a77-1d9e3e697b1d  Init Duration: 180.39 ms        
...
```

1. What's the content of your `serverless.yml` file?

```yaml
service: app

provider:
    name: aws
    region: us-west-1
    runtime: provided

plugins:
    - ./vendor/bref/bref

functions:
    function:
        handler: index.php
        description: ''
        layers:
            - ${bref:layer.php-73}

# Exclude files from deployment
package:
    exclude:
        - 'tests/**'
```

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

```
$ serverless invoke local --docker -f function --data '{"name": "test" }'
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Invoke invoke:local
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Writing Dockerfile...
Serverless: Building Docker image...
Sending build context to Docker daemon  88.45MB
Step 1/2 : FROM lambci/lambda:provided
 ---> 1aa9e9fecf65
Step 2/2 : ADD --chown=sbx_user1051:495 .serverless\\layers\\php-73\\20 /opt
ADD failed: stat /var/lib/docker/tmp/docker-builder468290826/.serverless\layers\php-73\20: no such file or directory

  Error --------------------------------------------------

  Error: Failed to build docker image (exit code 1})
      at spawnExt.then (C:\Users\Steve\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:386:23)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by stevebaldwinelectroneum** [comment]
I fixed this replacing the following line in ./plugins/index.js:330

```js
dockerFileContent += `\nADD --chown=sbx_user1051:495 ${layerPath} /opt`;
```

with 

```js
dockerFileContent += `\nADD --chown=sbx_user1051:495 ${os.platform() === 'win32' ? layerPath.replace(/\\/g, '/') : layerPath} /opt`;
```

**Comment by ronaldour** [comment]
Also got the same issue. The above approach seems good to me 👍

**Comment by medikoo** [comment]
@stevebaldwinelectroneum great thanks for reporting. PR with a fix is definitely welcome

**Comment by fmihal** [comment]
@medikoo If this issue is still relevant I could make a PR since it seems as a straightforward solution?
