### ISSUE TITLE
Cannot redeploy a Lambda if removing deploymentBucket.name

### ISSUE THREAD

**Issue by koterpillar** [serverless/serverless#7497]
# Bug Report

## Description

I have a Lambda function deployed with the following in `serverless.yml`:

```yaml
provider:
  name: aws
  # ...
  deploymentBucket:
    name: old-bucket-name
# ...
```

I would like to move away from that bucket to one that's generated by Serverless. Furthermore, I want to add custom tags to the new bucket. To do that, I changed the `serverless.yml` file to:

```yaml
provider:
  name: aws
  # ...
  deploymentBucket:
    tags:
      one: foo
      two: bar
# ...
```

When deploying now, I get an error:

```
Resource ServerlessDeploymentBucket does not exist for stack [redacted]
```

With `SLS_DEBUG=*`:

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: WARNING: Function api has timeout of 300 seconds, however, it's attached to API Gateway so it's automatically limited to 30 seconds.
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 200 0.303s 0 retries] describeStacks({ StackName: 'redacted' })
Serverless: [AWS cloudformation 400 0.216s 0 retries] describeStackResource({
  StackName: 'redacted',
  LogicalResourceId: 'ServerlessDeploymentBucket'
})

  Serverless Error ---------------------------------------

  ServerlessError: Resource ServerlessDeploymentBucket does not exist for stack [redacted]
      at /path/redacted/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:331:27
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              13.11.0
     Framework Version:         1.67.0
     Plugin Version:            3.5.0
     SDK Version:               2.3.0
     Components Version:        2.22.3
```

**Comment by medikoo** [comment]
@koterpillar thanks for report.

This bucket is vital for a deployment, the setting you removed purely allows to set custom name for this bucket (which anyway has to exist). So when you removed it. It was assumed that your service was deployed with bucket of default name, while it wasn't the case.

If you prefer Serverless to generate default name for the bucket, the only way to switch is to remove service and deploy it again with new setting.

**Comment by koterpillar** [comment]
Thank you for the explanation.

If my understanding is correct, the generated CFN stack only includes the bucket when the name is omitted. If the bucket name is specified, the stack is created but doesn't include the bucket.

Thus, at the point where the error occurred:
* The stack doesn't include the bucket.
* The configuration implies that a bucket must be created.

So it should be possible for Serverless to conclude that the stack must be first changed to create the bucket, instead of crashing.

Is this a reasonable change?

**Comment by medikoo** [comment]
@koterpillar I looked into it closer, and situation is more complex.

If you do not rely on external deployment bucket, then Framework on initial stack creation, first creates the stack just with a bucket, then uploads needed artifacts (e.g. function archives, or updated CF template to use), and then issues proper stack update, and then updates the stack with full resources configuration.

In situation where you first relied on a external deployment bucket and then you removed it, we're in a lock, as Framework needs a bucket to first upload needed artifacts to issue a valid stack update. Still at this point bucket doesn't exist, and t have bucket accessible it'll have to issue a stack update, but again for that, needs to ensure needed artifacts in a bucket to maintain already deployed resources intact. 

There's probably some way to recover but with current design it's a bit tricky.  Probably going following path could work:
- Retrieve current version of stack template from AWS
- Update it on spot just with bucket resources
- Deploy it
- Follow as usual (upload artifacts, pursue full update)

I still wonder, whether it would work if previously used external bucket would be removed or affected.in some destructive way.
URL references in current version of a template would not change, but they may list no longer accessibl url's. Question would having them not being changed will make AWS ignoring fact they're not valid (?) If that's the case, then above should be safe way to go. PR is welcome

**Comment by koterpillar** [comment]
Thank you for looking into it, I see how this is tricky now. For our use case it might be better to just recreate the affected functions.
