### ISSUE TITLE
Can't log in to serverless with command

### ISSUE THREAD

**Issue by Risto-Stevcev** [serverless/serverless#7511]
# Bug Report

## Description

1. What did you do?
I created a new serverless project for NodeJS with AWS lambda. I initially skipped the step to add an account to see the dashboards. I added the auth for serverless to AWS and deployed, and it successfully shows up as a lambda in AWS.

Then I tried adding the account by running `serverless` again. I ran into this error:

1. What happened?
```
You are not logged in or you do not have a Serverless account.

Serverless: Do you want to login or register? login
If your browser does not open automatically, please open it &  open the URL below to log in:
https://serverlessinc.auth0.com/authorize?audience=https%3A%2F%2Fserverlessinc.auth0.com%2Fuserinfo&response_type=code&client_id=YAHOG8papb1tkrLttNVoVOSs4YLOjrNj&redirect_uri=https%3A%2F%2Fdashboard.serverless.com%2Fcallback%3FtransactionId%3DnYs0LK8heFp88DBtXiCJ5&scope=openid%20email_verified%20email%20profile%20name%20offline_access
 
  Error --------------------------------------------------
 
  Error: spawn /home/risto/.serverless/bin/xdg-open ENOENT
      at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
      at onErrorNT (internal/child_process.js:456:16)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.13.1
     Framework Version:         1.67.0 (standalone)
     Plugin Version:            3.5.0
     SDK Version:               2.3.0
     Components Version:        2.22.3
```
Note that `xdg-open [some url]` works fine if I run it normally and it opens my browser.

So I manually copied the link to the browser, logged in, and it just brought me back to
https://dashboard.serverless.com/tenants/risto/onboarding

So I click "serverless framework/existing project", and tells me to run `serverless login`, which ends up with the same thing as above so I'm just going in circles

1. What should've happened?
I think it should've opened the link, I log in, and then I'm logged in and it shows my project

1. What's the content of your `serverless.yml` file?

```yaml
service: avcado

org: risto
app: avcado

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
```

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Invoke login
Serverless: Logging you in via your default browser...
If your browser does not open automatically, please open it &  open the URL below to log in:
https://serverlessinc.auth0.com/authorize?audience=https%3A%2F%2Fserverlessinc.auth0.com%2Fuserinfo&response_type=code&client_id=YAHOG8papb1tkrLttNVoVOSs4YLOjrNj&redirect_uri=https%3A%2F%2Fdashboard.serverless.com%2Fcallback%3FtransactionId%3DMcfFLooC2numDdwg4XB2N&scope=openid%20email_verified%20email%20profile%20name%20offline_access
 
  Error --------------------------------------------------
 
  Error: spawn /home/risto/.serverless/bin/xdg-open ENOENT
      at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
      at onErrorNT (internal/child_process.js:456:16)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.13.1
     Framework Version:         1.67.0 (standalone)
     Plugin Version:            3.5.0
     SDK Version:               2.3.0
     Components Version:        2.22.3
```

**Comment by Risto-Stevcev** [comment]
UPDATE:
I had installed this using the CLI method:
```
curl -o- -L https://slss.io/install | bash
```

I didn't notice there was an `npm` binary. So I uninstalled serverless with `serverless uninstall`, and then I installed the npm version with `yarn global add serverless`. Everything worked with `serverless login` and the CLI said that I successfully logged in.

- I deployed, the deployment shows up on the site.
- I tried accessing the dashboard but it logged me out and said there was an error logging me in. After a few attempts I managed to log in again.
- It still shows the onboarding page when I log in by default

**Comment by fernando-mc** [comment]
Hi @Risto-Stevcev, sorry that you're experiencing this. As a temporary workaround, you can create an access token in the dashboard and set it as SERVERLESS_ACCESS_KEY in your local environment. That might unblock you as we look into this. You can create one of these under the top right menu under "Person Access Keys".

**Comment by medikoo** [comment]
Issue is result of following:
- Login internally uses [opn](https://www.npmjs.com/package/opn) which on Linux may fallback to it's local [`xdg-open`](https://github.com/sindresorhus/open/blob/15caf1c276f1251c9cf8c9cebd40c5ec0681a8c9/index.js#L54)
- In standalone, the `opn`'s local `xdg-open` is not bundled and even it would be bundled it won't be accessible for `child_process.spawn`. Also `path.join(__dirname, ...)` are patched to point to path of standalone (hence in error above we see `/home/risto/.serverless/bin/xdg-open ENOENT`)
- Open browser logic we use, is configured to [mute any exceptions with which `opn` may result](https://github.com/serverless/platform-sdk/blob/1c9f7ebd93cdbb4e07f3625e2b57be186823068b/src/login/openBrowser.js#L24), so technically we should not observe crash here. Still there's a known [bug in `opn`](https://github.com/sindresorhus/open/issues/144) which anyway leaks spawn exceptions into the air (so they end as _uncaught_ exceptions)

---

This would be fixed once we upgrade to `opn` v7, as we can see they confirm on access to locally bundled `xdg-open` -> https://github.com/sindresorhus/open/blob/v7.0.3/index.js#L113-L122

Still on grounds of v1 we cannot upgrade without breaking support for Node.js v6.

Hopefully soon we'd be able to upgrade to v2, and then we'll ensure to use latest version of `opn` (`open` in this case)

**Comment by crisecheverria** [comment]
> UPDATE:
> I had installed this using the CLI method:
> 
> ```
> curl -o- -L https://slss.io/install | bash
> ```
> 
> I didn't notice there was an `npm` binary. So I uninstalled serverless with `serverless uninstall`, and then I installed the npm version with `yarn global add serverless`. Everything worked with `serverless login` and the CLI said that I successfully logged in.
> 
> * I deployed, the deployment shows up on the site.
> * I tried accessing the dashboard but it logged me out and said there was an error logging me in. After a few attempts I managed to log in again.
> * It still shows the onboarding page when I log in by default

Worked for me after RE-installing serverless.
Also, I'm able to see the dashboard.
