### ISSUE TITLE
Default stage is not set fo rAWS provider

### ISSUE THREAD

**Issue by pmyjavec** [serverless/serverless#7524]
# Bug Report

## Description

1. What did you do?
 
I removed the `stage: xxx` parameter from my AWS provider block so I could use the same provider configuration for multiple stages.

1. What happened?

My deploy started to fail because sls was no longer interpolating the stage value and many variable look-ups would fail. 

The command I was using was:

`npx serverless deploy --stage staging`

1. What should've happened?

The  [documentation](https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/) for the AWS provider states that it should use `opt.stage` by default and `dev` if `opt.stage` isn't set.

`stage: ${opt:stage, 'dev'} # Set the default stage used. Default is dev`

I actually had to add the following line to my configuration so serverless would behave correctly:

```
 stage: ${opt:stage}
```

1. What's the content of your `serverless.yml` file?

```
---
service: test
provider:
  name: aws
  timeout: 60
  runtime: python3.7
  region: us-west-2
  #stage: ${opt:stage}
  iamRoleStatements:
    - Effect: Allow
      Action: "ssm:GetParameter"
      Resource:
        - arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/XX/XX/${self:custom.stage}/faker/*
custom:
  stage: ${self:opt.stage, self:provider.stage}
  staging:
    fakerProvisionTopicName: fakerProvision-${self:custom.stage}
  pythonRequirements:
    usePipenv: true

functions:
  collector:
    handler: handler.main
    events:
      - schedule: cron(0/10 * * * ? *)
    environment:
      ENVIRONMENT: ${self:custom.stage}

plugins:
  - serverless-pseudo-parameters
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
    - __pycache__/**
    - .venv/**

resources:
  Resources:
    examsFound:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.${self:custom.stage}.fakerProvisionTopicName}
```

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command requirements
Serverless: Load command requirements:clean
Serverless: Load command requirements:install
Serverless: Load command requirements:cleanCache
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list

 Serverless Warning --------------------------------------

  A valid service attribute to satisfy the declaration 'self:custom.dev.fakerProvisionTopicName' could not be found.

Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Generating requirements.txt from Pipfile...
Serverless: Parsed requirements.txt from Pipfile in /home/xxx/projects/faker-collector/.serverless/requirements.txt...
Serverless: Using static cache of requirements found at /home/xxx/.cache/serverless-python-requirements/00e1828b9f52c64496fb409c2e0c31516d978b6bc2a452a45836d29a76b36a99_slspyc ...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: [AWS sts 200 5.072s 0 retries] assumeRole({ RoleArn: 'arn:aws:iam::1234567890:role/admin',
  RoleSessionName: 'aws-sdk-js-1585640710679' })
Serverless: Injecting required Python packages to package...
Serverless: Invoke aws:package:finalize
AWS Pseudo Parameters
Skipping automatic replacement of regions with account region!
AWS Pseudo Parameter: Resources::IamRoleLambdaExecution::Properties::Policies::0::PolicyDocument::Statement::2::Resource::0 Replaced AWS::Region with ${AWS::Region}
AWS Pseudo Parameter: Resources::IamRoleLambdaExecution::Properties::Policies::0::PolicyDocument::Statement::2::Resource::0 Replaced AWS::AccountId with ${AWS::AccountId}
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 400 0.817s 0 retries] describeStacks({ StackName: 'test-staging' })
Serverless: Creating Stack...
Serverless: [AWS cloudformation 200 0.672s 0 retries] createStack({ StackName: 'test-staging',
  OnFailure: 'DELETE',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateBody:
   '{"AWSTemplateFormatVersion":"2010-09-09","Description":"The AWS CloudFormation template for this Serverless application","Resources":{"ServerlessDeploymentBucket":{"Type":"AWS::S3::Bucket","Properties":{"BucketEncryption":{"ServerSideEncryptionConfiguration":[{"ServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}}},"ServerlessDeploymentBucketPolicy":{"Type":"AWS::S3::BucketPolicy","Properties":{"Bucket":{"Ref":"ServerlessDeploymentBucket"},"PolicyDocument":{"Statement":[{"Action":"s3:*","Effect":"Deny","Principal":"*","Resource":[{"Fn::Join":["",["arn:",{"Ref":"AWS::Partition"},":s3:::",{"Ref":"ServerlessDeploymentBucket"},"/*"]]}],"Condition":{"Bool":{"aws:SecureTransport":false}}}]}}}},"Outputs":{"ServerlessDeploymentBucketName":{"Value":{"Ref":"ServerlessDeploymentBucket"}}}}',
  Tags: [ { Key: 'STAGE', Value: 'staging' }, [length]: 1 ] })
Serverless: Checking Stack create progress...
Serverless: [AWS cloudformation 200 0.564s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:us-west-2:1234567890:stack/test-staging/96299aa0-7323-11ea-90c4-02371db12724' })
...Serverless: [AWS cloudformation 200 0.551s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:us-west-2:1234567890:stack/test-staging/96299aa0-7323-11ea-90c4-02371db12724' })
Serverless: [AWS cloudformation 200 0.55s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:us-west-2:1234567890:stack/test-staging/96299aa0-7323-11ea-90c4-02371db12724' })
Serverless: [AWS cloudformation 200 0.591s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:us-west-2:1234567890:stack/test-staging/96299aa0-7323-11ea-90c4-02371db12724' })
^[[A^[[A^[[A^[[A^[[A^[[AServerless: [AWS cloudformation 200 0.528s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:us-west-2:1234567890:stack/test-staging/96299aa0-7323-11ea-90c4-02371db12724' })
k....Serverless: [AWS cloudformation 200 0.522s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:us-west-2:1234567890:stack/test-staging/96299aa0-7323-11ea-90c4-02371db12724' })
.
Serverless: Stack create finished...
Serverless: [AWS cloudformation 200 0.562s 0 retries] describeStackResource({ StackName: 'test-staging',
  LogicalResourceId: 'ServerlessDeploymentBucket' })
Serverless: [AWS s3 200 0.814s 0 retries] listObjectsV2({ Bucket: 'test-staging-serverlessdeploymentbucket-3mgvjrc9xod3',
  Prefix: 'serverless/test/staging' })
Serverless: [AWS lambda 404 0.613s 0 retries] getFunction({ FunctionName: 'test-staging-collector' })
Serverless: [AWS sts 200 0.701s 0 retries] getCallerIdentity({})
Serverless: Uploading CloudFormation file to S3...
Serverless: [AWS s3 200 0.555s 0 retries] putObject({ Body:
   <Buffer 7b 22 41 57 53 54 65 6d 70 6c 61 74 65 46 6f 72 6d 61 74 56 65 72 73 69 6f 6e 22 3a 22 32 30 31 30 2d 30 39 2d 30 39 22 2c 22 44 65 73 63 72 69 70 74 ... >,
  Bucket: 'test-staging-serverlessdeploymentbucket-3mgvjrc9xod3',
  Key:
   'serverless/test/staging/1585640725479-2020-03-31T07:45:25.479Z/compiled-cloudformation-template.json',
  ContentType: 'application/json',
  Metadata:
   { filesha256: 'P3yMglMpN0TElUTruXRbCk8W4nPvbX/nh1/ABmIlK10=' } })
Serverless: Uploading artifacts...
Serverless: Uploading service test.zip file to S3 (8.88 MB)...
Serverless: [AWS s3 200 0.621s 0 retries] createMultipartUpload({ Bucket: 'test-staging-serverlessdeploymentbucket-3mgvjrc9xod3',
  Key:
   'serverless/test/staging/1585640725479-2020-03-31T07:45:25.479Z/test.zip',
  ContentType: 'application/zip',
  Metadata:
   { filesha256: 'r8NydRJsK7WJ+iPtNCmWTL9LXjsCPgflfgpElMUMavI=' } })
Serverless: [AWS s3 200 2.149s 0 retries] uploadPart({ Body:
   <Buffer 89 f0 b0 bb 7d 2f c3 a2 55 ac 6b b1 23 65 81 ef ca bd f0 75 ad 2e 23 d0 b1 a8 b6 48 c5 7a 71 19 32 f5 31 68 64 f6 2f 91 41 0a cc 14 6c 8e 0c 98 36 63 ... >,
  ContentLength: 4066831,
  PartNumber: 2,
  Bucket: 'test-staging-serverlessdeploymentbucket-3mgvjrc9xod3',
  Key:
   'serverless/test/staging/1585640725479-2020-03-31T07:45:25.479Z/test.zip',
  UploadId:
   'LocrNwUoOY8aFSy1Ou5PQSZ7ZrOc94DMG0eTYPFaNvChJVDtAhMOuXMRNwv6hTeH854nrVY9sXmRoC8YSV_fT3TTpcflS9cMTEZwPVYJHt59dM4l.Q3mBOttfW9jBX2LKsk1.5nrd1n8wyTKKtlCSYsICzvIfRITLnSDZ_iXFTw-' })
Serverless: [AWS s3 200 2.189s 0 retries] uploadPart({ Body:
   <Buffer 50 4b 03 04 0a 00 00 00 08 00 00 00 21 00 6c b2 b6 24 df 00 00 00 14 02 00 00 14 00 00 00 2e 63 69 72 63 6c 65 63 69 2f 63 6f 6e 66 69 67 2e 79 6d 6c ... >,
  ContentLength: 5242880,
  PartNumber: 1,
  Bucket: 'test-staging-serverlessdeploymentbucket-3mgvjrc9xod3',
  Key:
   'serverless/test/staging/1585640725479-2020-03-31T07:45:25.479Z/test.zip',
  UploadId:
   'LocrNwUoOY8aFSy1Ou5PQSZ7ZrOc94DMG0eTYPFaNvChJVDtAhMOuXMRNwv6hTeH854nrVY9sXmRoC8YSV_fT3TTpcflS9cMTEZwPVYJHt59dM4l.Q3mBOttfW9jBX2LKsk1.5nrd1n8wyTKKtlCSYsICzvIfRITLnSDZ_iXFTw-' })
Serverless: [AWS s3 200 0.587s 0 retries] completeMultipartUpload({ MultipartUpload:
   { Parts:
      [ { ETag: '"9d3ac39001587fd2bf715552f760f107"', PartNumber: 1 },
        { ETag: '"6d484f1353438d5e5a530c44d49f7158"', PartNumber: 2 },
        [length]: 2 ] },
  Bucket: 'test-staging-serverlessdeploymentbucket-3mgvjrc9xod3',
  Key:
   'serverless/test/staging/1585640725479-2020-03-31T07:45:25.479Z/test.zip',
  UploadId:
   'LocrNwUoOY8aFSy1Ou5PQSZ7ZrOc94DMG0eTYPFaNvChJVDtAhMOuXMRNwv6hTeH854nrVY9sXmRoC8YSV_fT3TTpcflS9cMTEZwPVYJHt59dM4l.Q3mBOttfW9jBX2LKsk1.5nrd1n8wyTKKtlCSYsICzvIfRITLnSDZ_iXFTw-' })
Serverless: Validating template...
Serverless: [AWS cloudformation 200 1.441s 0 retries] validateTemplate({ TemplateURL:
   'https://s3.amazonaws.com/test-staging-serverlessdeploymentbucket-3mgvjrc9xod3/serverless/test/staging/1585640725479-2020-03-31T07:45:25.479Z/compiled-cloudformation-template.json' })
Serverless: Updating Stack...
Serverless: [AWS cloudformation 200 1.163s 0 retries] updateStack({ StackName: 'test-staging',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL:
   'https://s3.amazonaws.com/test-staging-serverlessdeploymentbucket-3mgvjrc9xod3/serverless/test/staging/1585640725479-2020-03-31T07:45:25.479Z/compiled-cloudformation-template.json',
  Tags: [ { Key: 'STAGE', Value: 'staging' }, [length]: 1 ] })
Serverless: Checking Stack update progress...
Serverless: [AWS cloudformation 200 0.559s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:us-west-2:1234567890:stack/test-staging/96299aa0-7323-11ea-90c4-02371db12724' })
....
Serverless: Operation failed!
Serverless: View the full error output: https://us-west-2.console.aws.amazon.com/cloudformation/home?region=us-west-2#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-west-2%3A1234567890%3Astack%2Ftest-staging%2F96299aa0-7323-11ea-90c4-02371db12724

  Serverless Error ---------------------------------------

  ServerlessError: An error occurred: cookiesFound - Value of property TopicName must be of type String.
      at provider.request.then.data (/home/xxx/projects/faker-collector/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:125:33)
  From previous event:
      at AwsDeploy.monitorStack (/home/xxx/projects/faker-collector/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:28:12)
      at provider.request.then.cfData (/home/xxx/projects/faker-collector/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:107:28)
  From previous event:
      at AwsDeploy.update (/home/xxx/projects/faker-collector/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:107:8)
  From previous event:
      at AwsDeploy.BbPromise.bind.then (/home/xxx/projects/faker-collector/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:121:35)
  From previous event:
      at AwsDeploy.updateStack (/home/xxx/projects/faker-collector/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:117:33)
  From previous event:
      at AwsDeploy.BbPromise.bind.then (/home/xxx/projects/faker-collector/node_modules/serverless/lib/plugins/aws/deploy/index.js:127:39)
  From previous event:
      at Object.aws:deploy:deploy:updateStack [as hook] (/home/xxx/projects/faker-collector/node_modules/serverless/lib/plugins/aws/deploy/index.js:123:30)
      at BbPromise.reduce (/home/xxx/projects/faker-collector/node_modules/serverless/lib/classes/PluginManager.js:490:55)
  From previous event:
      at PluginManager.invoke (/home/xxx/projects/faker-collector/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at PluginManager.spawn (/home/xxx/projects/faker-collector/node_modules/serverless/lib/classes/PluginManager.js:510:17)
      at AwsDeploy.BbPromise.bind.then (/home/xxx/projects/faker-collector/node_modules/serverless/lib/plugins/aws/deploy/index.js:93:48)
  From previous event:
      at Object.deploy:deploy [as hook] (/home/xxx/projects/faker-collector/node_modules/serverless/lib/plugins/aws/deploy/index.js:89:30)
      at BbPromise.reduce (/home/xxx/projects/faker-collector/node_modules/serverless/lib/classes/PluginManager.js:490:55)
  From previous event:
      at PluginManager.invoke (/home/xxx/projects/faker-collector/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at getHooks.reduce.then (/home/xxx/projects/faker-collector/node_modules/serverless/lib/classes/PluginManager.js:525:24)
  From previous event:
      at PluginManager.run (/home/xxx/projects/faker-collector/node_modules/serverless/lib/classes/PluginManager.js:525:8)
      at variables.populateService.then (/home/xxx/projects/faker-collector/node_modules/serverless/lib/Serverless.js:133:33)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)
  From previous event:
      at Serverless.run (/home/xxx/projects/faker-collector/node_modules/serverless/lib/Serverless.js:120:74)
      at serverless.init.then (/home/xxx/projects/faker-collector/node_modules/serverless/bin/serverless.js:75:30)
      at /home/xxx/projects/faker-collector/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:136:16
      at /home/xxx/projects/faker-collector/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:57:14
      at FSReqWrap.args [as oncomplete] (fs.js:140:20)
  From previous event:
      at initializeErrorReporter.then (/home/xxx/projects/faker-collector/node_modules/serverless/bin/serverless.js:75:8)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)
  From previous event:
      at Object.<anonymous> (/home/xxx/projects/faker-collector/node_modules/serverless/bin/serverless.js:64:4)
      at Module._compile (internal/modules/cjs/loader.js:778:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
      at Module.load (internal/modules/cjs/loader.js:653:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
      at Function.Module._load (internal/modules/cjs/loader.js:585:3)
      at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
      at findNodeScript.then.existing (/nix/store/45mx90g4wia9x0a6hikw79x2djhmj6n5-nodejs-10.17.0/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              10.17.0
     Framework Version:         1.64.0
     Plugin Version:            3.4.0
     SDK Version:               2.3.0
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```

**Comment by medikoo** [comment]
@pmyjavec thanks for report. In serverless framework `provider.stage` is defintely optional, you can easily confirm that by deploying a simple services (with no plugins involved).

It might be that one of plugins you rely on, resolves stage internally as `provider.stage` instead of `provider.getStage()`, hence you observe the issue.

Note that issues with plugins should be reported to plugin repositories and not here.

If you 're sure that's a problem in the Framework itself, please prepare a minimal test case which does not involve any plugins, that exposes the error.

**Comment by pmyjavec** [comment]
@medikoo thanks, so are you suggesting that it might be better to rely on opt.stage?

**Comment by medikoo** [comment]
Please as ask at https://forum.serverless.com/ or https://www.serverless.com/slack

I'm going to close this as this issue tracker is purely for bug reports (not influenced by plugins) and feature proposals.
