### ISSUE TITLE
Similar function name issue 

### ISSUE THREAD

**Issue by ajagnanan** [serverless/serverless#755]
I stumbled on this issue today.

v0.4.2

Steps to reproduce:

- 2 functions with names: application, application_id
- run: `sls endpoint deploy application`
- Error: ` GET - applications: Could not find function for endpoint` 

Possible location of failure: ServerlessEndpoint.js - getFunction()

```
Serverless:   GET - applications: Could not find function for endpoint
  serverless:lib.node_modules.serverless.lib.actions.EndpointDeploy ServerlessError: Could not find function for endpoint
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/ServerlessError.js:17:11)
    at ServerlessEndpoint.getFunction (/usr/local/lib/node_modules/serverless/lib/ServerlessEndpoint.js:257:11)
    at Builder._validateAndPrepare (/usr/local/lib/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js:164:43)
    at Builder.build (/usr/local/lib/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js:77:20)
    at EndpointBuildApiGateway.endpointBuildApiGateway (/usr/local/lib/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js:57:22)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:181:25
    at Array.reduce (native)
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:180:26)
    at Object.actions.(anonymous function) [as endpointBuildApiGateway] (/usr/local/lib/node_modules/serverless/lib/Serverless.js:381:20)
    at /usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:302:42
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:285:35
    at /usr/local/lib/node_modules/serverless/node_modules/async/lib/async.js:181:20
    at iterate (/usr/local/lib/node_modules/serverless/node_modules/async/lib/async.js:262:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (/usr/local/lib/node_modules/serverless/node_modules/async/lib/async.js:281:9)
    at Object.async.forEachSeries.async.eachSeries (/usr/local/lib/node_modules/serverless/node_modules/async/lib/async.js:214:22)
    at BbPromise.then.newEvt.options.stage (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:281:19)
    at /usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:278:18
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:354:18)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:278:18
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:354:18)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:598:12)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
From previous event:
    at EndpointDeploy._deployEndpointsByRegion (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:270:10)
    at EndpointDeploy.<anonymous> (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:230:24)
From previous event:
    at EndpointDeploy._processDeployment (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:227:10)
From previous event:
    at EndpointDeploy.endpointDeploy (/usr/local/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:113:10)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:156:29
    at Array.reduce (native)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:155:30
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:153:10)
    at Serverless.actions.(anonymous function) (/usr/local/lib/node_modules/serverless/lib/Serverless.js:381:20)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:350:38)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:16:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3 +71ms
Serverless:
```

**Comment by ajagnanan** [comment]
Ok, did some more testing, if you use a template variable as the path e.g.` "path": "$${pathName}"`, that's when this issue happens. Seems related to #681...

**Comment by flomotlik** [comment]
Hi @ajagnanan we're going to reimplement this in the future in a way that this issue can't happen any more. I'm going to close this issue for now.
