### ISSUE TITLE
SLS no longer working after update to 1.67.2

### ISSUE THREAD

**Issue by tobilg** [serverless/serverless#7555]
# Bug Report
After updating to 1.67.2 (from 1.67.0), I see the following error:

```bash
$ sls --version                                                                                                       
/usr/local/lib/node_modules/serverless/node_modules/serverless-tencent-tools/sdk/debug/lib/wshub-client/index.js:88
var __spreadArrays =
^^^

SyntaxError: Unexpected token var
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

## Description

See above. Removing Serverless and reinstalling doesn't help either.

1. What did you do?
Update to version 1.67.2
1. What happened?
Serverless is no longer working
1. What should've happened?
Serverless works like before

**Comment by Jorer** [comment]
Last working version now seems to be `1.64.1` due to this fragile dependency.

**Comment by tobilg** [comment]
@Jorer Doesn't work for me either, also 1.67.0 which I had before if I reinstall it now. I suspect there's a bug in `serverless-tencent-tools` and SLS is using a non-pinned version of this dependency. Investigating now...

**Comment by tobilg** [comment]
cc @medikoo

**Comment by tobilg** [comment]
https://www.npmjs.com/package/serverless-tencent-tools was updated one hour ago.

**Comment by fablanglet** [comment]
I got this issue with serverless@1.67.2

```javascript
/usr/local/lib/node_modules/serverless/node_modules/serverless-tencent-tools/sdk/debug/lib/wshub-client/index.js:88
var __spreadArrays =
^^^

SyntaxError: Unexpected token var
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

**Comment by tobilg** [comment]
Grepping the `package-lock.json` from v1.67.2, it seems like it's references via `@serverless/tencent-platform-client`

```bash
$ cat package-lock.json | grep -in -C 20 serverless-tencent-tools
434-      "requires": {
435-        "@serverless/component-metrics": "^1.0.8",
436-        "@serverless/core": "^1.0.0",
437-        "graphlib": "^2.1.7",
438-        "traverse": "^0.6.6"
439-      }
440-    },
441-    "@serverless/tencent-platform-client": {
442-      "version": "0.25.10",
443-      "resolved": "https://registry.npmjs.org/@serverless/tencent-platform-client/-/tencent-platform-client-0.25.10.tgz",
444-      "integrity": "sha512-HdifFh+2PNndRcaeXnrNoqdH7hiozlNH7Rk5enaTCSqAhD5YynJTiEOZMqWmo6eQRTOQJ30/xen8YJetGzMDPg==",
445-      "requires": {
446-        "adm-zip": "^0.4.13",
447-        "axios": "^0.19.2",
448-        "dotenv": "^8.2.0",
449-        "https-proxy-agent": "^5.0.0",
450-        "isomorphic-ws": "^4.0.1",
451-        "js-yaml": "^3.13.1",
452-        "jwt-decode": "^2.2.0",
453-        "querystring": "^0.2.0",
454:        "serverless-tencent-tools": "^1.0.13",
455-        "traverse": "^0.6.6",
456-        "urlencode": "^1.1.0",
457-        "ws": "^7.2.1"
458-      },
459-      "dependencies": {
460-        "debug": {
461-          "version": "4.1.1",
462-          "resolved": "https://registry.npmjs.org/debug/-/debug-4.1.1.tgz",
463-          "integrity": "sha512-pYAIzeRo8J6KPEaJ0VWOh5Pzkbw/RetuzehGM7QRRX5he4fPHx2rdKMB256ehJCkX+XRQm16eZLqLNS8RSZXZw==",
464-          "requires": {
465-            "ms": "^2.1.1"
466-          }
467-        },
468-        "https-proxy-agent": {
469-          "version": "5.0.0",
470-          "resolved": "https://registry.npmjs.org/https-proxy-agent/-/https-proxy-agent-5.0.0.tgz",
471-          "integrity": "sha512-EkYm5BcKUGiduxzSt3Eppko+PiNWNEpa4ySk9vTC6wDsQJW9rHSa+UhGNJoRYp7bz6Ht1eaRIa6QaJqO5rCFbA==",
472-          "requires": {
473-            "agent-base": "6",
474-            "debug": "4"
--
--
5233-      "dependencies": {
5234-        "@serverless/cli": {
5235-          "version": "1.4.0",
5236-          "resolved": "https://registry.npmjs.org/@serverless/cli/-/cli-1.4.0.tgz",
5237-          "integrity": "sha512-YqlCiYmRFeGksw6XJaXbigIDlktc7OfRuVpyPB7IZgkCJ9mUlBmvyWdwqJEQdkUz0xPTGsd4Jd/XSrwyiw1Brg==",
5238-          "requires": {
5239-            "@serverless/core": "^1.0.0",
5240-            "@serverless/template": "^1.1.0",
5241-            "ansi-escapes": "^4.2.0",
5242-            "chalk": "^2.4.2",
5243-            "chokidar": "^3.0.2",
5244-            "dotenv": "^8.0.0",
5245-            "figures": "^3.0.0",
5246-            "minimist": "^1.2.0",
5247-            "prettyoutput": "^1.2.0",
5248-            "strip-ansi": "^5.2.0"
5249-          }
5250-        }
5251-      }
5252-    },
5253:    "serverless-tencent-tools": {
5254-      "version": "1.0.13",
--
5254-      "version": "1.0.13",
5255:      "resolved": "https://registry.npmjs.org/serverless-tencent-tools/-/serverless-tencent-tools-1.0.13.tgz",
5256-      "integrity": "sha512-m78hr6bvjHeBEfLtp4Ju8XsZopSG7lGJIe02pn6zkdbtmLYwhwCdcNirCWF2veZY4FQLwEPonGv6wX9snXCTNQ==",
5257-      "requires": {
5258-        "@tencent-sdk/capi": "^0.2.15-alpha.0",
5259-        "dijkstrajs": "^1.0.1",
5260-        "dot-qs": "0.2.0",
5261-        "duplexify": "^4.1.1",
5262-        "end-of-stream": "^1.4.4",
5263-        "https-proxy-agent": "^5.0.0",
5264-        "socket.io-client": "^2.3.0",
5265-        "socket.io-stream": "^0.9.1",
5266-        "winston": "^3.2.1"
5267-      },
5268-      "dependencies": {
5269-        "debug": {
5270-          "version": "4.1.1",
5271-          "resolved": "https://registry.npmjs.org/debug/-/debug-4.1.1.tgz",
5272-          "integrity": "sha512-pYAIzeRo8J6KPEaJ0VWOh5Pzkbw/RetuzehGM7QRRX5he4fPHx2rdKMB256ehJCkX+XRQm16eZLqLNS8RSZXZw==",
5273-          "requires": {
5274-            "ms": "^2.1.1"
5275-          }
```

**Comment by MehranJanfeshan** [comment]
I am getting the same error, seems the latest version has problem.
```
/usr/lib/node_modules/serverless/node_modules/serverless-tencent-tools/sdk/debug/lib/wshub-client/index.js:87
   }
   ^
 SyntaxError: Unexpected token '}'
     at Module._compile (internal/modules/cjs/loader.js:891:18)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
     at Module.load (internal/modules/cjs/loader.js:811:32)
     at Function.Module._load (internal/modules/cjs/loader.js:723:14)
     at Module.require (internal/modules/cjs/loader.js:848:19)
     at require (internal/modules/cjs/helpers.js:74:18)
     at Object.<anonymous> (/usr/lib/node_modules/serverless/node_modules/serverless-tencent-tools/sdk/debug/lib/client.js:1:30)
     at Module._compile (internal/modules/cjs/loader.js:955:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
     at Module.load (internal/modules/cjs/loader.js:811:32)
```

**Comment by dallinwright** [comment]
Temporary fix is to downgrade to 1.64.1, or manually apply the git patch from the other linked issue to that module.

**Comment by MrJibus** [comment]
Same here too. First time using serverless, i am glad that i am not the only one ^^. 

Downgraded to 1.64.1 like the previous comment suggest did the trick, thanks !

**Comment by tobilg** [comment]
@dallinwright I can confirm `1.64.1` is working:

```bash
$ sls --version                                              
Framework Core: 1.64.1
Plugin: 3.6.6
SDK: 2.3.0
Components Core: 1.1.2
Components CLI: 1.4.0
```

**Comment by bartmachielsen** [comment]
It got it also working by not installing serverless global but in the local node_modules and calling `../node_modules/serverless/bin/serverless deploy --stage=prod;`

**Comment by medikoo** [comment]
@tobilg great thanks for reporting. I'm on that, fix will be issued shortly

**Comment by fablanglet** [comment]
I reported an issue here: https://github.com/serverless-tencent/serverless-tencent-tools/issues/16

**Comment by tobilg** [comment]
@medikoo Thanks for the fast response. I assume there will be a new version published accordingly?

**Comment by tanlin2013** [comment]
I got the same. rolling back to older version could solve the issue temperately.

**Comment by medikoo** [comment]
@tobilg v1.67.3 was just published
