### ISSUE TITLE
Cryptic error on corrupted lambda zip file

### ISSUE THREAD

**Issue by pimlie** [serverless/serverless#7560]
# Bug Report

## Description

1. What did you do?

While testing my config I apparently hit CTRL+C at just the 'right' time.

1. What happened?

The zip file of one of my lambdas became corrupted, causing a cryptic Corrupted zip error which wasnt clear that it was related to one of the lambda zips.

1. What should've happened?

As serverless writes/appends to the lambda zips, we probably cant fully prevent them from getting corrupted in edge cases. But when this happens we should display a clear error message so we know which zip is causing the problem and needs to be rebuild

1. What's the content of your `serverless.yml` file?
n.a.

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
```
  Error: Corrupted zip: can't find end of central directory
      at ZipEntries.readEndOfCentral (/var/project/node_modules/jszip/lib/zipEntries.js:171:23)
      at ZipEntries.load (/var/project/node_modules/jszip/lib/zipEntries.js:256:14)
      at /var/project/node_modules/jszip/lib/load.js:48:20
  From previous event:
      at PluginManager.invoke (/var/project/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at PluginManager.spawn (/var/project/node_modules/serverless/lib/classes/PluginManager.js:510:17)
      at Deploy.<anonymous> (/var/project/node_modules/serverless/lib/plugins/deploy/deploy.js:115:50)
  From previous event:
      at Object.before:deploy:deploy [as hook] (/var/project/node_modules/serverless/lib/plugins/deploy/deploy.js:100:30)
      at /var/project/node_modules/serverless/lib/classes/PluginManager.js:490:55
  From previous event:
      at PluginManager.invoke (/var/project/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at /var/project/node_modules/serverless/lib/classes/PluginManager.js:525:24
  From previous event:
      at PluginManager.run (/var/project/node_modules/serverless/lib/classes/PluginManager.js:525:8)
      at /var/project/node_modules/serverless/lib/Serverless.js:133:33
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:131:23)
  From previous event:
      at Serverless.run (/var/project/node_modules/serverless/lib/Serverless.js:120:74)
      at /var/project/node_modules/serverless/bin/serverless.js:82:30
      at /var/project/node_modules/graceful-fs/graceful-fs.js:136:16
      at /var/project/node_modules/graceful-fs/graceful-fs.js:57:14
      at FSReqCallback.oncomplete (fs.js:146:23)
  From previous event:
      at /var/project/node_modules/serverless/bin/serverless.js:82:8
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:131:23)
  From previous event:
      at Object.<anonymous> (/var/project/node_modules/serverless/bin/serverless.js:71:4)
      at Module._compile (internal/modules/cjs/loader.js:956:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
      at Module.load (internal/modules/cjs/loader.js:812:32)
      at Function.Module._load (internal/modules/cjs/loader.js:724:14)
      at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
      at internal/main/run_main_module.js:17:11
```

Similar or dependent issues:

**Comment by medikoo** [comment]
@pimlie Thanks for report. Still it looks that this error is produced in scope of one of the external plugins you use and not in the Framework itself (note `jszip` is not used in Framework logic)

Please coin which plugin is responsible that, and report this issue at given plugin repository

**Comment by pimlie** [comment]
@medikoo Thanks for the reply, the error was caused by `@serverless/enterprise-plugin`. Didn't realize that that plugin has a different repository, sorry. Could you maybe move this issue to that repo?
