### ISSUE TITLE
Problem deploying knative service

### ISSUE THREAD

**Issue by odellus** [serverless/serverless#7582]
# Bug Report

## Description

1. What did you do?
I installed serverless through the normal route of using `npm install`. I'm running knative using microk8s on Ubuntu 18.04 through standard `microk8s enable knative`. My only ~/.kube/config is what I get from `kubectl config view > ~/.kube/config`. Everything is super minimal here.
2. What happened?
I followed the steps to configure knative/k8s to communicate with serverless as well as set env variables for docker hub.
3. What should've happened?
`SLS_DEBUG=* serverless deploy` would have deployed my service to knative.
4. What's the content of your `serverless.yml` file?
```yaml
service: my-service

provider:
  name: knative
  # optional Docker Hub credentials you need if you're using local Dockerfiles as function handlers
  docker:
    username: ${env:DOCKER_HUB_USERNAME}
    password: ${env:DOCKER_HUB_PASSWORD}

functions:
  hello:
    handler: hello-world.dockerfile
    context: ./code

plugins:
  - serverless-knative

```
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
```bash
SLS_DEBUG=* serverless deploy
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command dev
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Building Docker image "odellus/my-service-hello:1586942913377"...
Serverless: Pushing "odellus/my-service-hello:1586942913377" to Container Registry...
Serverless: Deploying Kubernetes namespace "sls-my-service-dev"...
 
  Type Error ---------------------------------------------
 
  TypeError: Cannot read property 'body' of undefined
      at KubernetesNamespace.default (/home/thomas/code/knative-serverless/my-service/node_modules/@serverless/kubernetes-namespace/serverless.js:22:40)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  From previous event:
      at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at /usr/lib/node_modules/serverless/lib/classes/PluginManager.js:525:24
  From previous event:
      at PluginManager.run (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:525:8)
      at /usr/lib/node_modules/serverless/lib/Serverless.js:133:33
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Serverless.run (/usr/lib/node_modules/serverless/lib/Serverless.js:120:74)
      at /usr/lib/node_modules/serverless/bin/serverless.js:82:30
      at /usr/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:136:16
      at /usr/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:57:14
      at FSReqCallback.oncomplete (fs.js:155:23)
  From previous event:
      at /usr/lib/node_modules/serverless/bin/serverless.js:82:8
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Object.<anonymous> (/usr/lib/node_modules/serverless/bin/serverless.js:71:4)
      at Module._compile (internal/modules/cjs/loader.js:1156:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
      at Module.load (internal/modules/cjs/loader.js:1000:32)
      at Function.Module._load (internal/modules/cjs/loader.js:899:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
      at internal/main/run_main_module.js:18:47
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.16.2
     Framework Version:         1.67.3
     Plugin Version:            3.6.6
     SDK Version:               2.3.0
     Components Version:        2.29.1

```
Similar or dependent issues:

- ???

**Comment by odellus** [comment]
I tried to upload with `kubectl apply --file service.yaml` using microk8s and it didn't work. Looks like my DNS is misconfigured. Since it's a microk8s dns issue I'm closing. :+1:

**Comment by zhaogaiwen** [comment]
how can you fixed the problem?i have the same issue
