### ISSUE TITLE
Serverless deploy fails attaching the lambda layers 

### ISSUE THREAD

**Issue by boopathykpm** [serverless/serverless#7594]
Serverless deploy is getting failed after enabling the cache for the node modules,  

when trying to deploy getting the below error, same is not happening when code build cache is disabled

```
ERROR in /codebuild/output/src401492264/src/src/api/nextbestaction.ts
[tsl] ERROR in /codebuild/output/src401492264/src/src/api/nextbestaction.ts(40,10)
      TS2742: The inferred type of 'router' cannot be named without a reference to '../../../../../local-cache/custom/ece6a99d81ee033034768cd0386afeb08988d587012316c712d0e8523080cbc5/node_modules/dhxds-lambda-layers/dist'. This is likely not portable. A type annotation is necessary.
  Error --------------------------------------------------
  Error: Webpack compilation error, see above
      at _.forEach.compileStats (/codebuild/local-cache/custom/ece6a99d81ee033034768cd0386afeb08988d587012316c712d0e8523080cbc5/node_modules/serverless-webpack/lib/compile.js:38:19)
      at arrayEach (/codebuild/local-cache/custom/ece6a99d81ee033034768cd0386afeb08988d587012316c712d0e8523080cbc5/node_modules/lodash/lodash.js:516:11)
      at Function.forEach (/codebuild/local-cache/custom/ece6a99d81ee033034768cd0386afeb08988d587012316c712d0e8523080cbc5/node_modules/lodash/lodash.js:9342:14)
      at BbPromise.fromCallback.then.stats (/codebuild/local-cache/custom/ece6a99d81ee033034768cd0386afeb08988d587012316c712d0e8523080cbc5/node_modules/serverless-webpack/lib/compile.js:31:11)
      at finalCallback (/codebuild/local-cache/custom/ece6a99d81ee033034768cd0386afeb08988d587012316c712d0e8523080cbc5/node_modules/webpack/lib/Compiler.js:257:39)
      at hooks.done.callAsync.err (/codebuild/local-cache/custom/ece6a99d81ee033034768cd0386afeb08988d587012316c712d0e8523080cbc5/node_modules/webpack/lib/Compiler.js:273:13)
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/codebuild/local-cache/custom/ece6a99d81ee033034768cd0386afeb08988d587012316c712d0e8523080cbc5/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (/codebuild/local-cache/custom/ece6a99d81ee033034768cd0386afeb08988d587012316c712d0e8523080cbc5/node_modules/tapable/lib/Hook.js:154:20)
      at onCompiled (/codebuild/local-cache/custom/ece6a99d81ee033034768cd0386afeb08988d587012316c712d0e8523080cbc5/node_modules/webpack/lib/Compiler.js:271:21)
      at hooks.afterCompile.callAsync.err (/codebuild/local-cache/custom/ece6a99d81ee033034768cd0386afeb08988d587012316c712d0e8523080cbc5/node_modules/webpack/lib/Compiler.js:681:15)
      at _err0 (eval at create (/codebuild/local-cache/custom/ece6a99d81ee033034768cd0386afeb08988d587012316c712d0e8523080cbc5/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
      at /codebuild/local-cache/custom/ece6a99d81ee033034768cd0386afeb08988d587012316c712d0e8523080cbc5/node_modules/ts-loader/dist/after-compile.js:28:9
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/codebuild/local-cache/custom/ece6a99d81ee033034768cd0386afeb08988d587012316c712d0e8523080cbc5/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
      at AsyncSeriesHook.lazyCompileHook (/codebuild/local-cache/custom/ece6a99d81ee033034768cd0386afeb08988d587012316c712d0e8523080cbc5/node_modules/tapable/lib/Hook.js:154:20)
      at compilation.seal.err (/codebuild/local-cache/custom/ece6a99d81ee033034768cd0386afeb08988d587012316c712d0e8523080cbc5/node_modules/webpack/lib/Compiler.js:678:31)
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/codebuild/local-cache/custom/ece6a99d81ee033034768cd0386afeb08988d587012316c712d0e8523080cbc5/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (/codebuild/local-cache/custom/ece6a99d81ee033034768cd0386afeb08988d587012316c712d0e8523080cbc5/node_modules/tapable/lib/Hook.js:154:20)
      at hooks.optimizeAssets.callAsync.err (/codebuild/local-cache/custom/ece6a99d81ee033034768cd0386afeb08988d587012316c712d0e8523080cbc5/node_modules/webpack/lib/Compilation.js:1423:35)
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/codebuild/local-cache/custom/ece6a99d81ee033034768cd0386afeb08988d587012316c712d0e8523080cbc5/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (/codebuild/local-cache/custom/ece6a99d81ee033034768cd0386afeb08988d587012316c712d0e8523080cbc5/node_modules/tapable/lib/Hook.js:154:20)
      at hooks.optimizeChunkAssets.callAsync.err (/codebuild/local-cache/custom/ece6a99d81ee033034768cd0386afeb08988d587012316c712d0e8523080cbc5/node_modules/webpack/lib/Compilation.js:1414:32)
      at _err0 (eval at create (/codebuild/local-cache/custom/ece6a99d81ee033034768cd0386afeb08988d587012316c712d0e8523080cbc5/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
      at taskRunner.run (/codebuild/local-cache/custom/ece6a99d81ee033034768cd0386afeb08988d587012316c712d0e8523080cbc5/node_modules/terser-webpack-plugin/dist/index.js:321:9)
      at step (/codebuild/local-cache/custom/ece6a99d81ee033034768cd0386afeb08988d587012316c712d0e8523080cbc5/node_modules/terser-webpack-plugin/dist/TaskRunner.js:87:9)
      at done (/codebuild/local-cache/custom/ece6a99d81ee033034768cd0386afeb08988d587012316c712d0e8523080cbc5/node_modules/terser-webpack-plugin/dist/TaskRunner.js:98:30)
  From previous event:
      at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:510:17)
      at ServerlessWebpack.BbPromise.bind.then.then (/codebuild/local-cache/custom/ece6a99d81ee033034768cd0386afeb08988d587012316c712d0e8523080cbc5/node_modules/serverless-webpack/index.js:101:51)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)
   Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
   Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              10.19.0
     Framework Version:         1.67.3
     Plugin Version:            3.6.6
     SDK Version:               2.3.0
     Components Version:        2.29.3
 


```

**Comment by medikoo** [comment]
@boopathykpm This doesn't look framework related. Please post at https://github.com/serverless-heaven/serverless-webpack

**Comment by boopathykpm** [comment]
@medikoo Thanks for the redirection, sure I will create the ticket there and close this one.
