### ISSUE TITLE
cafile is not used during the aws-sdk call

### ISSUE THREAD

**Issue by jgroom33** [serverless/serverless#7608]
# Bug Report

## Description

1. What did you do?
    `SLS_DEBUG="*" cafile=/etc/ssl/certs/zscaler.pem serverless deploy`
1. What happened?
```
platform-sdk fetching: GET https://api.serverless.com/core/meta
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Installing dependencies for custom CloudFormation resources...
Serverless: Invoke aws:package:finalize
Serverless: [AWS sts undefined 2.851s 3 retries] getCallerIdentity({})
Serverless: Recoverable error occurred (unable to get local issuer certificate), sleeping for ~6 seconds. Try 1 of 4
Serverless: [AWS sts undefined 2.632s 3 retries] getCallerIdentity({})
Serverless: Recoverable error occurred (unable to get local issuer certificate), sleeping for ~5 seconds. Try 2 of 4
Serverless: [AWS sts undefined 2.925s 3 retries] getCallerIdentity({})
Serverless: Recoverable error occurred (unable to get local issuer certificate), sleeping for ~4 seconds. Try 3 of 4
Serverless: [AWS sts undefined 2.749s 3 retries] getCallerIdentity({})
Serverless: Recoverable error occurred (unable to get local issuer certificate), sleeping for ~5 seconds. Try 4 of 4
Serverless: [AWS sts undefined 2.864s 3 retries] getCallerIdentity({})
 
 Serverless Error ---------------------------------------
 
 ServerlessError: unable to get local issuer certificate
   at /home/jgroom/.nvm/versions/node/v13.12.0/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:331:27
   at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
1. What should've happened?
Deployed

Additionally, a `aws sts get-caller-identity` via cli works (using the cert):

```
aws sts get-caller-identity 
{
    "UserId": "xxxxxx",
    "Account": "xxxxx",
    "Arn": "arn:aws:iam::xxxxxx:user/user"
}
```

Similar or dependent issues:

- #6637

**Comment by medikoo** [comment]
@jgroom33 Thanks for report. 

When using `aws-sdk` directly, as e.g. in this simple script: https://github.com/medikoo/test-aws-sdk/blob/1a9f018cb571ffc21c47f22de1026443508b8db9/lambda/invoke.js#L5-L9
Will `cafile` be used automatically if needed, or is there additional manual setup needed for that?

**Comment by jgroom33** [comment]
yes, that works.

```bash
~/src/ami-launcher/ui$ node foo.js bar
{
  StatusCode: 200,
  ExecutedVersion: '$LATEST',
.......
}
```

The workaround I'm currently using is to allow the CI platform to perform the `serverless deploy`

**Comment by medikoo** [comment]
@jgroom33 Technically in that case it should also work in a Framework out of a box (as under the hook we just do AWS SDK calls).

Do you have a glimpse of idea why it doesn't?

**Comment by jgroom33** [comment]
i'm attributing the behavior to: `zscaler sucks`

if i don't specify the cafile during the deploy command, serverless rejects the cert.

The workaround my organization implemented was to add a zscaler bypass for api.serverless.com

**Comment by medikoo** [comment]
@jgroom33 did you reopened this issue intentionally? If so please provide some feedback

**Comment by jgroom33** [comment]
I reopened because my org would like to see if there is a root cause.  I'm going to do some more tests

**Comment by medikoo** [comment]
Ok, let us know.
