### ISSUE TITLE
Fetch Error during CICD

### ISSUE THREAD

**Issue by yeyeric** [serverless/serverless#7615]
Everything was working fine until now. Even earlier today all my deployments with my CICD went well for many weeks. Nothing changes in my CICD for the past weeks, just updating a very basic line of code in python.

In my CICD (gitlab), here is the error I get, always at the same place:
This is the content of the SLS-DEBUG

line raising the problem:
 $ sls plugin install -n serverless-python-requirements --stage $CI_COMMIT_REF_NAME --url $CI_ENVIRONMENT_URL

```
Serverless: Load command interactiveCli
 Serverless: Load command config
 Serverless: Load command config:credentials
 Serverless: Load command config:tabcompletion
 Serverless: Load command config:tabcompletion:install
 Serverless: Load command config:tabcompletion:uninstall
 Serverless: Load command create
 Serverless: Load command install
 Serverless: Load command package
 Serverless: Load command deploy
 Serverless: Load command deploy:function
 Serverless: Load command deploy:list
 Serverless: Load command deploy:list:functions
 Serverless: Load command invoke
 Serverless: Load command invoke:local
 Serverless: Load command info
 Serverless: Load command logs
 Serverless: Load command metrics
 Serverless: Load command print
 Serverless: Load command remove
 Serverless: Load command rollback
 Serverless: Load command rollback:function
 Serverless: Load command slstats
 Serverless: Load command plugin
 Serverless: Load command plugin
 Serverless: Load command plugin:install
 Serverless: Load command plugin
 Serverless: Load command plugin:uninstall
 Serverless: Load command plugin
 Serverless: Load command plugin:list
 Serverless: Load command plugin
 Serverless: Load command plugin:search
 Serverless: Load command config
 Serverless: Load command config:credentials
 Serverless: Load command rollback
 Serverless: Load command rollback:function
 Serverless: Load command upgrade
 Serverless: Load command uninstall
 Serverless: Load command login
 Serverless: Load command logout
 Serverless: Load command generate-event
 Serverless: Load command test
 Serverless: Load command dashboard
 Serverless: Load command output
 Serverless: Load command output:get
 Serverless: Load command output:list
 Serverless: Load command param
 Serverless: Load command param:get
 Serverless: Load command param:list
 Serverless: Load command dev
 Serverless: Invoke plugin:install
  
   Fetch Error --------------------------------------------
  
   FetchError: invalid json response body at https://raw.githubusercontent.com/serverless/plugins/master/plugins.json reason: Unexpected token : in JSON at position 3
       at /usr/lib/node_modules/serverless/node_modules/node-fetch/lib/body.js:48:31
       at processTicksAndRejections (internal/process/task_queues.js:97:5)
   From previous event:
       at PluginInstall.install (/usr/lib/node_modules/serverless/lib/plugins/plugin/install/install.js:53:8)
   From previous event:
       at Object.plugin:install:install [as hook] (/usr/lib/node_modules/serverless/lib/plugins/plugin/install/install.js:41:12)
       at /usr/lib/node_modules/serverless/lib/classes/PluginManager.js:490:55
   From previous event:
       at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:490:22)
       at /usr/lib/node_modules/serverless/lib/classes/PluginManager.js:525:24
   From previous event:
       at PluginManager.run (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:525:8)
       at /usr/lib/node_modules/serverless/lib/Serverless.js:133:33
       at processImmediate (internal/timers.js:456:21)
       at process.topLevelDomainCallback (domain.js:137:15)
   From previous event:
       at Serverless.run (/usr/lib/node_modules/serverless/lib/Serverless.js:120:74)
       at /usr/lib/node_modules/serverless/bin/serverless.js:82:30
       at /usr/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:136:16
       at /usr/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:57:14
       at FSReqCallback.oncomplete (fs.js:155:23)
   From previous event:
       at /usr/lib/node_modules/serverless/bin/serverless.js:82:8
       at processImmediate (internal/timers.js:456:21)
       at process.topLevelDomainCallback (domain.js:137:15)
   From previous event:
       at Object.<anonymous> (/usr/lib/node_modules/serverless/bin/serverless.js:71:4)
       at Module._compile (internal/modules/cjs/loader.js:1156:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
       at Module.load (internal/modules/cjs/loader.js:1000:32)
       at Function.Module._load (internal/modules/cjs/loader.js:899:14)
       at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
       at internal/main/run_main_module.js:18:47
  
   Get Support --------------------------------------------
      Docs:          docs.serverless.com
      Bugs:          github.com/serverless/serverless/issues
      Issues:        forum.serverless.com
  
   Your Environment Information ---------------------------
      Operating System:          linux
      Node Version:              12.16.2
      Framework Version:         1.68.0
      Plugin Version:            3.6.6
      SDK Version:               2.3.0
      Components Version:        2.30.1
```

Any idea ? I'm 100% this worked 3hours ago, but doesn't work anymore.

**Comment by medikoo** [comment]
@yeyeric GitHub was down and still is recovering, I'm pretty sure it's caused by that
https://www.githubstatus.com/

Check again once situation will come back to normal

**Comment by yeyeric** [comment]
due to githab as mentionned by @medikoo
