### ISSUE TITLE
Possible bug in sharing httpapi between services

### ISSUE THREAD

**Issue by dotorg-hala** [serverless/serverless#7642]
### Bug Report

I am trying to create a central httpApi that all my services can use referencing the documentation: [Reusing httpApi in Different Services](https://www.serverless.com/framework/docs/providers/aws/events/http-api#reusing-http-api-in-different-services). When the httpApi is created externally, I follow the instructions to add the ID to my provider:

```
provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'local'}
  log: ${opt:log, 'info'}
  region: us-west-2
  stackName: ${self:service}-${self:provider.stage}
  httpApi:
    id: [API ID from aws console ex: lptjfv2lx5]
```

When I run sls deploy I get the following error:
```
Serverless Error ---------------------------------------
  ServerlessError: Cannot setup access logs for externally confugured HTTP API
```

I tried adding this section to my provider:
```
  logs:
    httpApi: false
```
but I still get the same error. I've tried asking in slack, in the forum and on stackoverflow but no feedback. 

The documentation states that when reusing HTTP API in different services, 

> extending HTTP API with CORS or access logs settings is not supported.

I would expect that it would warn but not error and block deploy when reusing httpApi, or it would give me the option to not create access logs for httpAPI.

I've been trying to get this working for a week now. Please advise. 

SLS_DEBUG output:

```
Serverless Error ---------------------------------------
 
  ServerlessError: Cannot setup access logs for externally confugured HTTP API
      at HttpApiEvents.<anonymous> (/Users/hala/.nvm/versions/node/v13.3.0/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/httpApi/index.js:233:17)
      at HttpApiEvents.memoized (/Users/hala/.nvm/versions/node/v13.3.0/lib/node_modules/serverless/node_modules/memoizee/lib/configure-map.js:81:23)
      at Object.package:compileEvents [as hook] (/Users/hala/.nvm/versions/node/v13.3.0/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/httpApi/index.js:40:14)
      at /Users/hala/.nvm/versions/node/v13.3.0/lib/node_modules/serverless/lib/classes/PluginManager.js:490:55
  From previous event:
      at PluginManager.invoke (/Users/hala/.nvm/versions/node/v13.3.0/lib/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at PluginManager.spawn (/Users/hala/.nvm/versions/node/v13.3.0/lib/node_modules/serverless/lib/classes/PluginManager.js:510:17)
      at Deploy.<anonymous> (/Users/hala/.nvm/versions/node/v13.3.0/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:115:50)
  From previous event:
      at Object.before:deploy:deploy [as hook] (/Users/hala/.nvm/versions/node/v13.3.0/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:100:30)
      at /Users/hala/.nvm/versions/node/v13.3.0/lib/node_modules/serverless/lib/classes/PluginManager.js:490:55
  From previous event:
      at PluginManager.invoke (/Users/hala/.nvm/versions/node/v13.3.0/lib/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at /Users/hala/.nvm/versions/node/v13.3.0/lib/node_modules/serverless/lib/classes/PluginManager.js:525:24
  From previous event:
      at PluginManager.run (/Users/hala/.nvm/versions/node/v13.3.0/lib/node_modules/serverless/lib/classes/PluginManager.js:525:8)
      at /Users/hala/.nvm/versions/node/v13.3.0/lib/node_modules/serverless/lib/Serverless.js:133:33
      at processImmediate (internal/timers.js:444:21)
      at process.topLevelDomainCallback (domain.js:134:15)
  From previous event:
      at Serverless.run (/Users/hala/.nvm/versions/node/v13.3.0/lib/node_modules/serverless/lib/Serverless.js:120:74)
      at /Users/hala/.nvm/versions/node/v13.3.0/lib/node_modules/serverless/bin/serverless.js:82:30
      at /Users/hala/.nvm/versions/node/v13.3.0/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:144:16
      at /Users/hala/.nvm/versions/node/v13.3.0/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:61:14
      at FSReqCallback.oncomplete (fs.js:152:23)
  From previous event:
      at /Users/hala/.nvm/versions/node/v13.3.0/lib/node_modules/serverless/bin/serverless.js:82:8
      at processImmediate (internal/timers.js:444:21)
      at process.topLevelDomainCallback (domain.js:134:15)
  From previous event:
      at Object.<anonymous> (/Users/hala/.nvm/versions/node/v13.3.0/lib/node_modules/serverless/bin/serverless.js:71:4)
      at Module._compile (internal/modules/cjs/loader.js:1128:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
      at Module.load (internal/modules/cjs/loader.js:983:32)
      at Function.Module._load (internal/modules/cjs/loader.js:891:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
      at internal/main/run_main_module.js:17:47
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              13.3.0
     Framework Version:         1.68.0
     Plugin Version:            3.6.8
     SDK Version:               2.3.0
     Components Version:        2.30.2

```

**Comment by medikoo** [comment]
@dotorg-hala Logging is expected to be set at same place at which you create HTTP API.

There's no support to turn logging on externally configured HTTP API, as that'll be error-prone (imagine two different services deployed interchangeably one turning logs on, and other turning them off for same HTTP API).

Therefore if you've created HTTP API manually in a console, then also in a console setup logging on a stage which you created

**Comment by dotorg-hala** [comment]
thanks @medikoo for getting back to me so quickly. I'm not trying to add access logging to my externally created httpapi in my service, I'm just trying to reuse an externally created httpApi in my service by following the documentation and adding to my Provider section:

```
httpApi:
    id: [API ID from aws console ex: lptjfv2lx5]
```

But when I try to do this, I get the error:
```
Serverless Error ---------------------------------------
  ServerlessError: Cannot setup access logs for externally confugured HTTP API
```

At this point, I am unable to use externally created httpapi in my services. Are there any additional configurations I need to add to my services serverless.yml file that I'm missing to be able to use the externally created httpApi?

**Comment by medikoo** [comment]
@dotorg-hala sorry I misunderstood you initially.

Still, I cannot reproduce the error.

`Cannot setup access logs for externally confugured HTTP API` error happens only if both `provider.httpApi.id` and `provider.logs.httpApi` are set. You can confirm on that here: https://github.com/serverless/serverless/blob/b6e54f06e26bffcb69360ad89edb9d07d78c624f/lib/plugins/aws/package/compile/events/httpApi/index.js#L230-L237

Also you can confirm by deploying following service, that there's no issue in deploying endpoints to shared HTTP API service: https://github.com/medikoo/test-serverless/blob/http-api-shared/serverless.yml

**Comment by dotorg-hala** [comment]
@medikoo Thanks to your sample app, I think I figured out what is happening. Your app works great. I started with it and then began to bring it to parity with my app by adding things to your serverless.yml file until I triggered the error. The reason I'm getting the error and your app is not, is because I have my app linked to a a service in the Serverless Framework dashboard. I'm not sure about the internals of it, but as soon as I linked your app to a service in my dashboard, the error was triggered:

```
org: <myOrg>
app: test-http-api
service: test-http-api-shared
```

If I were to guess, it's because the dashboard provides great monitoring but likely also enables logging behind the scenes that I can't control therefore triggering a True in `provider.logs.httpApi`.

**Comment by medikoo** [comment]
@dotorg-hala great thanks for claryfication. Indeed there's a bug in `@serverless/enterprise-plugin` repository. I'm transferring this issue there
