### ISSUE TITLE
Unable to deploy lambda service with EventBridge pattern trying to match null value

### ISSUE THREAD

**Issue by shihrer** [serverless/serverless#7649]
# Bug Report

## Description

1. What did you do?
I attempted to create an event pattern matching a `null` value on a property.
1. What happened?
Received an error on `sls deploy` stating null values are not allowed
1. What should've happened?
Should've deployed with an event rule matching on null
1. What's the content of your `serverless.yml` file?

```
service:
  name: subscriptions-service

plugins:
  - serverless-dotenv-plugin
  - serverless-submittable-service-dashboard
  - serverless-iam-roles-per-function
  - serverless-offline

custom:
  # Plugins
  serverless-offline:
    httpPort: ${env:npm_package_config_port}
  # Service
  stage: ${opt:stage, "dev"}
  env: ${opt:env, self:custom.stage}
  configFile: serverless.${self:custom.env}.yml

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${self:custom.stage}
  region: us-east-1
  cfnRole: ${file(${self:custom.configFile}):cfnRole}
  logs:
    restApi: true
  tracing:
    apiGateway: true
    lambda: true
  # Functions
  vpc: ${file(${self:custom.configFile}):vpc}
  environment:
    JWT_SIGNING_KEY: ${file(${self:custom.configFile}):jwtSigningKey}
    EVENT_BUS: ${file(${self:custom.configFile}):eventBus}
    MSSQL_CONNECTION_STRING: ${file(${self:custom.configFile}):msSqlConnectionString}
    ENDPOINT_SECRET: ${file(${self:custom.configFile}):endpointSecret}
    STRIPE_API_KEY: ${file(${self:custom.configFile}):stripeApiKey}
  memorySize: 256
  timeout: 30 # Max for gateway
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'events:PutEvents'
      Resource: 'arn:aws:events:us-east-1:*:*'

functions:
  subscriptionWebhook:
    handler: src/handlers/webhookHandler.webhookHandler
    events:
      - http:
          method: POST
          path: /subscription/events
          cors: true
  cancelEventHandler:
    handler: src/handlers/pastDueCancelEventHandler.pastDueCancelEventHandler
    events:
      - eventBridge:
          eventBus: ${file(${self:custom.configFile}):eventBus}
          pattern:
            source:
              - 'Stripe'
            detail-type:
              - 'customer.subscription.deleted'
            detail:
              data:
                object:
                  cancel_at_period_end:
                    - false
              request:
                - null
```

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

```
❯ npm run deploy

> subscriptions-service@0.0.0 deploy /Users/michaelshihrer/Projects/subscriptions-service
> npx serverless deploy --verbose

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: DOTENV: Loading environment variables from .env:
Serverless: 	 - ENDPOINT_SECRET
Serverless: 	 - MSSQL_CONNECTION_STRING
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command dev

 Serverless Warning --------------------------------------

  A valid file to satisfy the declaration 'file(serverless.dev.yml):cfnRole' could not be found.

Serverless: [AWS ssm 200 0.493s 0 retries] getParameter({ Name: '/submittable-serverless/dev/jwtSigningKey',
  WithDecryption: true })
Serverless: [AWS ssm 200 0.487s 0 retries] getParameter({ Name: '/subscriptions-service/dev/stripeApiSecret',
  WithDecryption: true })
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Installing dependencies for custom CloudFormation resources...
Serverless: Installing dependencies for custom CloudFormation resources...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 200 0.555s 0 retries] describeStacks({ StackName: 'subscriptions-service-dev' })
Serverless: [AWS cloudformation 200 0.479s 0 retries] describeStackResource({ StackName: 'subscriptions-service-dev',
  LogicalResourceId: 'ServerlessDeploymentBucket' })
Serverless: [AWS s3 200 0.491s 0 retries] listObjectsV2({ Bucket:
   'subscriptions-service-de-serverlessdeploymentbuck-swfgifhzurg8',
  Prefix: 'serverless/subscriptions-service/dev' })
Serverless: [AWS s3 200 0.449s 0 retries] headObject({ Bucket:
   'subscriptions-service-de-serverlessdeploymentbuck-swfgifhzurg8',
  Key:
   'serverless/subscriptions-service/dev/1588304344161-2020-05-01T03:39:04.161Z/subscriptions-service.zip' })
Serverless: [AWS s3 200 0.466s 0 retries] headObject({ Bucket:
   'subscriptions-service-de-serverlessdeploymentbuck-swfgifhzurg8',
  Key:
   'serverless/subscriptions-service/dev/1588304344161-2020-05-01T03:39:04.161Z/custom-resources.zip' })
Serverless: [AWS s3 200 0.469s 0 retries] headObject({ Bucket:
   'subscriptions-service-de-serverlessdeploymentbuck-swfgifhzurg8',
  Key:
   'serverless/subscriptions-service/dev/1588304344161-2020-05-01T03:39:04.161Z/compiled-cloudformation-template.json' })
Serverless: [AWS lambda 200 0.608s 0 retries] getFunction({ FunctionName: 'subscriptions-service-dev-subscriptionWebhook' })
Serverless: [AWS lambda 404 0.34s 0 retries] getFunction({ FunctionName: 'subscriptions-service-dev-cancelEventHandler' })
Serverless: [AWS sts 200 0.458s 0 retries] getCallerIdentity({})
Serverless: Uploading CloudFormation file to S3...
Serverless: [AWS s3 200 0.904s 0 retries] putObject({ Body:
   <Buffer 7b 22 41 57 53 54 65 6d 70 6c 61 74 65 46 6f 72 6d 61 74 56 65 72 73 69 6f 6e 22 3a 22 32 30 31 30 2d 30 39 2d 30 39 22 2c 22 44 65 73 63 72 69 70 74 ... >,
  Bucket:
   'subscriptions-service-de-serverlessdeploymentbuck-swfgifhzurg8',
  Key:
   'serverless/subscriptions-service/dev/1588305248789-2020-05-01T03:54:08.789Z/compiled-cloudformation-template.json',
  ContentType: 'application/json',
  Metadata:
   { filesha256: 'I1VizLawQOBhjuo/4gM4fehhFNO/1Zjc8FBGHuo30+8=' } })
Serverless: Uploading artifacts...
Serverless: Uploading service subscriptions-service.zip file to S3 (16.98 MB)...
Serverless: [AWS s3 200 0.551s 0 retries] createMultipartUpload({ Bucket:
   'subscriptions-service-de-serverlessdeploymentbuck-swfgifhzurg8',
  Key:
   'serverless/subscriptions-service/dev/1588305248789-2020-05-01T03:54:08.789Z/subscriptions-service.zip',
  ContentType: 'application/zip',
  Metadata:
   { filesha256: 'rMTqOZYjY7v7xahGivmetvwWJN0GKcv0yyz8IGKC6TE=' } })
Serverless: [AWS s3 200 7.234s 0 retries] uploadPart({ Body:
   <Buffer 7d 9f 10 ee 0c 20 48 bb 65 93 ff 01 50 4b 07 08 b6 ee 4e e7 3a 20 00 00 43 60 00 00 50 4b 03 04 14 00 08 00 08 00 00 00 21 00 00 00 00 00 00 00 00 00 ... >,
  ContentLength: 2072070,
  PartNumber: 4,
  Bucket:
   'subscriptions-service-de-serverlessdeploymentbuck-swfgifhzurg8',
  Key:
   'serverless/subscriptions-service/dev/1588305248789-2020-05-01T03:54:08.789Z/subscriptions-service.zip',
  UploadId:
   'jGVO7UVmNdXjCRc0arb2YlxCDgMCqUr522EHCbFguDsoKf1iEEAdbD.d.li7o0e61c4DKb9.4tUUwUpgdfyMfV.Ci2chUY7vG66hTHfYvllZN5vNhbrRBqiPzXsqbseO' })
Serverless: [AWS s3 200 15.028s 0 retries] uploadPart({ Body:
   <Buffer ca b0 98 92 fa 93 47 e1 c8 9f d1 fe 6a 9c 38 6f ea 26 ab 86 39 7a 09 1b 46 06 90 29 15 bc 87 50 b0 38 e1 25 94 ef e6 c9 f1 47 68 7f be 0b 91 8f 50 67 ... >,
  ContentLength: 5242880,
  PartNumber: 3,
  Bucket:
   'subscriptions-service-de-serverlessdeploymentbuck-swfgifhzurg8',
  Key:
   'serverless/subscriptions-service/dev/1588305248789-2020-05-01T03:54:08.789Z/subscriptions-service.zip',
  UploadId:
   'jGVO7UVmNdXjCRc0arb2YlxCDgMCqUr522EHCbFguDsoKf1iEEAdbD.d.li7o0e61c4DKb9.4tUUwUpgdfyMfV.Ci2chUY7vG66hTHfYvllZN5vNhbrRBqiPzXsqbseO' })
Serverless: [AWS s3 200 15.306s 0 retries] uploadPart({ Body:
   <Buffer 70 f8 f6 11 6a 2f b9 17 73 3a dc 66 ba d7 7c bc 67 5c 92 1b 1a 07 39 c7 18 7e db c1 22 11 07 d6 59 2a 9a ba bf 17 9a f5 95 96 a6 09 74 10 98 a6 ee cd ... >,
  ContentLength: 5242880,
  PartNumber: 2,
  Bucket:
   'subscriptions-service-de-serverlessdeploymentbuck-swfgifhzurg8',
  Key:
   'serverless/subscriptions-service/dev/1588305248789-2020-05-01T03:54:08.789Z/subscriptions-service.zip',
  UploadId:
   'jGVO7UVmNdXjCRc0arb2YlxCDgMCqUr522EHCbFguDsoKf1iEEAdbD.d.li7o0e61c4DKb9.4tUUwUpgdfyMfV.Ci2chUY7vG66hTHfYvllZN5vNhbrRBqiPzXsqbseO' })
Serverless: [AWS s3 200 15.543s 0 retries] uploadPart({ Body:
   <Buffer 50 4b 03 04 14 00 08 00 08 00 00 00 21 00 00 00 00 00 00 00 00 00 00 00 00 00 04 00 00 00 2e 65 6e 76 2d 8e 41 6b 83 30 18 40 ef fe 8a c0 0e bd 94 32 ... >,
  ContentLength: 5242880,
  PartNumber: 1,
  Bucket:
   'subscriptions-service-de-serverlessdeploymentbuck-swfgifhzurg8',
  Key:
   'serverless/subscriptions-service/dev/1588305248789-2020-05-01T03:54:08.789Z/subscriptions-service.zip',
  UploadId:
   'jGVO7UVmNdXjCRc0arb2YlxCDgMCqUr522EHCbFguDsoKf1iEEAdbD.d.li7o0e61c4DKb9.4tUUwUpgdfyMfV.Ci2chUY7vG66hTHfYvllZN5vNhbrRBqiPzXsqbseO' })
Serverless: [AWS s3 200 0.818s 0 retries] completeMultipartUpload({ MultipartUpload:
   { Parts:
      [ { ETag: '"6c08cb8766189e3d2d119f3641eb55db"', PartNumber: 1 },
        { ETag: '"9b79b61defe58a6ed00a4fdae57d7ac2"', PartNumber: 2 },
        { ETag: '"829dea2ae8cc33c76434aa23a70f9764"', PartNumber: 3 },
        { ETag: '"b004b4b68350cdf747c1110f5790ce80"', PartNumber: 4 },
        [length]: 4 ] },
  Bucket:
   'subscriptions-service-de-serverlessdeploymentbuck-swfgifhzurg8',
  Key:
   'serverless/subscriptions-service/dev/1588305248789-2020-05-01T03:54:08.789Z/subscriptions-service.zip',
  UploadId:
   'jGVO7UVmNdXjCRc0arb2YlxCDgMCqUr522EHCbFguDsoKf1iEEAdbD.d.li7o0e61c4DKb9.4tUUwUpgdfyMfV.Ci2chUY7vG66hTHfYvllZN5vNhbrRBqiPzXsqbseO' })
Serverless: Uploading custom CloudFormation resources...
Serverless: [AWS s3 200 0.504s 0 retries] createMultipartUpload({ Bucket:
   'subscriptions-service-de-serverlessdeploymentbuck-swfgifhzurg8',
  Key:
   'serverless/subscriptions-service/dev/1588305248789-2020-05-01T03:54:08.789Z/custom-resources.zip',
  ContentType: 'application/zip',
  Metadata:
   { filesha256: 'Im9ioOjsM5ybo4nDdl9DGmi/sm/ow10v0P6xta7a2GQ=' } })
Serverless: [AWS s3 200 6.378s 0 retries] uploadPart({ Body:
   <Buffer cb 8f ba 33 c8 a4 ed b7 a4 0d 2c b5 97 73 78 d8 44 b0 c8 02 7e 4c b8 af 24 c4 51 41 41 8f d4 f1 3c 72 ee 9c e8 a1 df c3 ad 2a 7f 89 96 ce 64 7f 79 95 ... >,
  ContentLength: 1540671,
  PartNumber: 2,
  Bucket:
   'subscriptions-service-de-serverlessdeploymentbuck-swfgifhzurg8',
  Key:
   'serverless/subscriptions-service/dev/1588305248789-2020-05-01T03:54:08.789Z/custom-resources.zip',
  UploadId:
   '6s3kDeuVsXpixK6noiKmb0CdfkZbCm1HdlbXEAnv4RiKFggdR2QVt2qFOk360iQqku62g1JpwkcKToB7kWIbh.FOD_CuVzVL.z_28Yhoa45bmZr4T1gK462fOn0baaWC' })
Serverless: [AWS s3 200 8.855s 0 retries] uploadPart({ Body:
   <Buffer 50 4b 03 04 14 00 08 00 08 00 e5 96 89 50 00 00 00 00 00 00 00 00 00 00 00 00 09 00 00 00 52 45 41 44 4d 45 2e 6d 64 8d cd c1 09 80 30 0c 46 e1 7b a7 ... >,
  ContentLength: 5242880,
  PartNumber: 1,
  Bucket:
   'subscriptions-service-de-serverlessdeploymentbuck-swfgifhzurg8',
  Key:
   'serverless/subscriptions-service/dev/1588305248789-2020-05-01T03:54:08.789Z/custom-resources.zip',
  UploadId:
   '6s3kDeuVsXpixK6noiKmb0CdfkZbCm1HdlbXEAnv4RiKFggdR2QVt2qFOk360iQqku62g1JpwkcKToB7kWIbh.FOD_CuVzVL.z_28Yhoa45bmZr4T1gK462fOn0baaWC' })
Serverless: [AWS s3 200 0.536s 0 retries] completeMultipartUpload({ MultipartUpload:
   { Parts:
      [ { ETag: '"8cb5a224410b02b9464f630b42909539"', PartNumber: 1 },
        { ETag: '"f96cd41d90817211f9c6ad6d61c8d19f"', PartNumber: 2 },
        [length]: 2 ] },
  Bucket:
   'subscriptions-service-de-serverlessdeploymentbuck-swfgifhzurg8',
  Key:
   'serverless/subscriptions-service/dev/1588305248789-2020-05-01T03:54:08.789Z/custom-resources.zip',
  UploadId:
   '6s3kDeuVsXpixK6noiKmb0CdfkZbCm1HdlbXEAnv4RiKFggdR2QVt2qFOk360iQqku62g1JpwkcKToB7kWIbh.FOD_CuVzVL.z_28Yhoa45bmZr4T1gK462fOn0baaWC' })
Serverless: Validating template...
Serverless: [AWS cloudformation 400 0.816s 0 retries] validateTemplate({ TemplateURL:
   'https://s3.amazonaws.com/subscriptions-service-de-serverlessdeploymentbuck-swfgifhzurg8/serverless/subscriptions-service/dev/1588305248789-2020-05-01T03:54:08.789Z/compiled-cloudformation-template.json' })

  Error --------------------------------------------------

  Error: The CloudFormation template is invalid: [/Resources/CancelEventHandlerCustomEventBridge1/Type/EventBridgeConfig/Pattern/detail/request/0] 'null' values are not allowed in templates
      at provider.request.catch.error (/Users/michaelshihrer/Projects/subscriptions-service/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:20:13)
  From previous event:
      at AwsDeploy.validateTemplate (/Users/michaelshihrer/Projects/subscriptions-service/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:16:85)
  From previous event:
      at AwsDeploy.BbPromise.bind.then (/Users/michaelshihrer/Projects/subscriptions-service/node_modules/serverless/lib/plugins/aws/deploy/index.js:119:39)
  From previous event:
      at Object.aws:deploy:deploy:validateTemplate [as hook] (/Users/michaelshihrer/Projects/subscriptions-service/node_modules/serverless/lib/plugins/aws/deploy/index.js:115:30)
      at BbPromise.reduce (/Users/michaelshihrer/Projects/subscriptions-service/node_modules/serverless/lib/classes/PluginManager.js:490:55)
  From previous event:
      at PluginManager.invoke (/Users/michaelshihrer/Projects/subscriptions-service/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at PluginManager.spawn (/Users/michaelshihrer/Projects/subscriptions-service/node_modules/serverless/lib/classes/PluginManager.js:510:17)
      at AwsDeploy.BbPromise.bind.then (/Users/michaelshihrer/Projects/subscriptions-service/node_modules/serverless/lib/plugins/aws/deploy/index.js:93:48)
  From previous event:
      at Object.deploy:deploy [as hook] (/Users/michaelshihrer/Projects/subscriptions-service/node_modules/serverless/lib/plugins/aws/deploy/index.js:89:30)
      at BbPromise.reduce (/Users/michaelshihrer/Projects/subscriptions-service/node_modules/serverless/lib/classes/PluginManager.js:490:55)
  From previous event:
      at PluginManager.invoke (/Users/michaelshihrer/Projects/subscriptions-service/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at getHooks.reduce.then (/Users/michaelshihrer/Projects/subscriptions-service/node_modules/serverless/lib/classes/PluginManager.js:525:24)
  From previous event:
      at PluginManager.run (/Users/michaelshihrer/Projects/subscriptions-service/node_modules/serverless/lib/classes/PluginManager.js:525:8)
      at variables.populateService.then (/Users/michaelshihrer/Projects/subscriptions-service/node_modules/serverless/lib/Serverless.js:133:33)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)
  From previous event:
      at Serverless.run (/Users/michaelshihrer/Projects/subscriptions-service/node_modules/serverless/lib/Serverless.js:120:74)
      at serverless.init.then (/Users/michaelshihrer/Projects/subscriptions-service/node_modules/serverless/bin/serverless.js:82:30)
      at /Users/michaelshihrer/Projects/subscriptions-service/node_modules/graceful-fs/graceful-fs.js:136:16
      at /Users/michaelshihrer/Projects/subscriptions-service/node_modules/graceful-fs/graceful-fs.js:57:14
      at FSReqWrap.args [as oncomplete] (fs.js:140:20)
  From previous event:
      at initializeErrorReporter.then (/Users/michaelshihrer/Projects/subscriptions-service/node_modules/serverless/bin/serverless.js:82:8)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)
  From previous event:
      at Object.<anonymous> (/Users/michaelshihrer/Projects/subscriptions-service/node_modules/serverless/bin/serverless.js:71:4)
      at Module._compile (internal/modules/cjs/loader.js:778:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
      at Module.load (internal/modules/cjs/loader.js:653:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
      at Function.Module._load (internal/modules/cjs/loader.js:585:3)
      at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
      at findNodeScript.then.existing (/Users/michaelshihrer/.config/nvm/10.17.0/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.17.0
     Framework Version:         1.67.0
     Plugin Version:            3.6.5
     SDK Version:               2.3.0
     Components Version:        2.28.0

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! subscriptions-service@0.0.0 deploy: `npx serverless deploy --verbose`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the subscriptions-service@0.0.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/michaelshihrer/.npm/_logs/2020-05-01T03_54_41_030Z-debug.log
```

I'm trying to determine if this is a bug and whether or not it's serverless or AWS.  I looked at the file `cloudformation-template-update-stack.json` and the pattern looks ok to me:

```

          "Pattern": {
            "source": [
              "Stripe"
            ],
            "detail-type": [
              "customer.subscription.deleted"
            ],
            "detail": {
              "data": {
                "object": {
                  "cancel_at_period_end": [
                    false
                  ]
                }
              },
              "request": [
                null
              ]
            }
          }
```

We are supposed to be able to match on `null` values according to: https://docs.aws.amazon.com/eventbridge/latest/userguide/eventbridge-event-patterns-null-and-empty-strings.html

**Comment by shihrer** [comment]
Looking at the repo, I'm guessing this isn't a problem with serverless.

https://github.com/serverless/serverless/blob/a4342239ea46e6c4b3951a23464a8f93e8daab16/lib/plugins/aws/deploy/lib/validateTemplate.js

Looks like it's just a wrapper for calling: https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_ValidateTemplate.html

So I'm not sure why they would throw an error with something that's supposed to work.  Is it possible to skip the validation step on deploy?

**Comment by medikoo** [comment]
@shihrer error reported in log seems to indicate invalid variable reference, and doesn't seem to relate to EventBridge pattern setting.

Inspect your configuration, otherwise please minimize the test case (no plugins involved, no variable references). So issue is exposed without interference.

**Comment by shihrer** [comment]
@medikoo what I did was remove the null pattern from the config and the error went away.  We were able to get in contact with AWS support and they confirmed to us that CloudFormation doesn't support the null value.  I'll go ahead and close this since it's not related to Serverless.  Thanks for your response, though!

**Comment by ivanmartos** [comment]
@shihrer Did AWS suggest how to achieve the `null` in EventBridge rule deployed via CloudFormation?

**Comment by pgrzesik** [comment]
@jefftham Did you check if it's possible to specify it via CloudFormation?
