### ISSUE TITLE
Deploying lambda function using serverless ver. 1.69.0 (standalone)

### ISSUE THREAD

**Issue by gus-hallaq** [serverless/serverless#7675]
# Bug Report

## Description

1. What did you do? 
Developing lambda function to connect to postgres to execute a query.

1. What happened? 
Using serverless-offline it's working, but when I tried to execute serverless deploy I got an error message: TypeError: ctx.sls.service.package.include.push is not a function

1. What should've happened? 
Deploy the lambda function.

1. What's the content of your `serverless.yml` file?
service: coffeeapi
org: gushallaq
app: coffee_with_me

custom:
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, env:NODE_ENV}

provider:
  name: aws
  runtime: nodejs12.x
  region: ${self:custom.region}
  stage: ${self:custom.stage}

plugins:
  - serverless-offline

package:
  include: "*"

functions:
  coffees:
    handler: index.coffees
    events:
      - http:
          path: coffees
          method: GET
          cors: true

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
Guss-MBP:CoffeeAPI-JS gushallaq$ serverless deploy 
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
platform-sdk fetching: POST https://api.serverless.com/core/tenants/gushallaq/applications/coffee_with_me/profileValue
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
platform-sdk fetching: GET https://api.serverless.com/core/tenants/gushallaq/applications/coffee_with_me
 
  Type Error ---------------------------------------------
 
  TypeError: ctx.sls.service.package.include.push is not a function
      at /snapshot/serverless/node_modules/@serverless/enterprise-plugin/lib/wrap.js:381:39
      at Generator.next (<anonymous>)
      at asyncGeneratorStep (/snapshot/serverless/node_modules/@serverless/enterprise-plugin/lib/wrap.js:8:103)
      at _next (/snapshot/serverless/node_modules/@serverless/enterprise-plugin/lib/wrap.js:10:194)
      at /snapshot/serverless/node_modules/@serverless/enterprise-plugin/lib/wrap.js:10:364
      at new Promise (<anonymous>)
      at /snapshot/serverless/node_modules/@serverless/enterprise-plugin/lib/wrap.js:10:97
      at wrap (/snapshot/serverless/node_modules/@serverless/enterprise-plugin/lib/wrap.js:387:17)
      at ServerlessEnterprisePlugin.<anonymous> (/snapshot/serverless/node_modules/@serverless/enterprise-plugin/lib/plugin.js:446:17)
      at Generator.next (<anonymous>)
      at asyncGeneratorStep (/snapshot/serverless/node_modules/@serverless/enterprise-plugin/lib/plugin.js:3:103)
      at _next (/snapshot/serverless/node_modules/@serverless/enterprise-plugin/lib/plugin.js:5:194)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  From previous event:
      at PluginManager.invoke (/snapshot/serverless/lib/classes/PluginManager.js:490:22)
      at PluginManager.spawn (/snapshot/serverless/lib/classes/PluginManager.js:510:17)
      at Deploy.<anonymous> (/snapshot/serverless/lib/plugins/deploy/deploy.js:115:50)
  From previous event:
      at Object.before:deploy:deploy [as hook] (/snapshot/serverless/lib/plugins/deploy/deploy.js:100:30)
      at /snapshot/serverless/lib/classes/PluginManager.js:490:55
  From previous event:
      at PluginManager.invoke (/snapshot/serverless/lib/classes/PluginManager.js:490:22)
      at /snapshot/serverless/lib/classes/PluginManager.js:525:24
  From previous event:
      at PluginManager.run (/snapshot/serverless/lib/classes/PluginManager.js:525:8)
      at /snapshot/serverless/lib/Serverless.js:133:33
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Serverless.run (/snapshot/serverless/lib/Serverless.js:120:74)
      at /snapshot/serverless/bin/serverless.js:82:30
      at /snapshot/serverless/node_modules/graceful-fs/graceful-fs.js:152:16
      at /snapshot/serverless/node_modules/graceful-fs/graceful-fs.js:69:14
      at FSReqCallback.oncomplete (fs.js:154:23)
  From previous event:
      at /snapshot/serverless/bin/serverless.js:82:8
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Object.<anonymous> (/snapshot/serverless/bin/serverless.js:71:4)
      at Module._compile (pkg/prelude/bootstrap.js:1320:22)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
      at Module.load (internal/modules/cjs/loader.js:1000:32)
      at Function.Module._load (internal/modules/cjs/loader.js:899:14)
      at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12)
      at internal/main/run_main_module.js:18:47
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.16.1
     Framework Version:         1.69.0 (standalone)
     Plugin Version:            3.6.8
     SDK Version:               2.3.0
     Components Version:        2.30.2
 
Similar or dependent issues:

- #12345

**Comment by medikoo** [comment]
@gus-hallaq Value at `package.include` should be an array. Problem is that you've configured a string.

Error on our side, is that we're not signalling this error properly. Still that will soon change with https://github.com/serverless/serverless/issues/6562

**Comment by gus-hallaq** [comment]
Hi Medikoo,

I will check that `package.include`,
I have tried now to remove the `serverless-offline` from serverless.yml, and everything works as it should.

I don't know if that is a bug, or we always need to remove that plugin before we deploy.

**Comment by gus-hallaq** [comment]
Hi Medikoo,

You are right about `package.include`, it's working now even with that plugin. :)
