### ISSUE TITLE
Serverless systematically crashes after updating to the last version

### ISSUE THREAD

**Issue by ludobonnet** [serverless/serverless#7718]
After updating to the last version, all commands return the same error. 

Environnement :
MacOS : 10.15.4
Node : 13.2.0
Serverless : 1.70.1

<details>
<summary><b><code>serverless -v</code> output</b></summary>

```
Error: No valid exports main found for '/usr/local/lib/node_modules/serverless/node_modules/uuid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:611:9)
    at applyExports (internal/modules/cjs/loader.js:492:14)
    at resolveExports (internal/modules/cjs/loader.js:541:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:643:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:941:27)
    at Function.Module._load (internal/modules/cjs/loader.js:847:27)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/lib/utils/config/initialSetup.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/lib/utils/config/index.js:12:22)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/lib/Serverless.js:12:23)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/lib/utils/autocomplete.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless.js:42:22)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:67:12)
    at internal/main/run_main_module.js:17:47
```

</details>

**Comment by medikoo** [comment]
@ludobonnet thanks for reporting. Still, we're unable to reproduce that, also all our tests and integration tests pass without issues.

How did you install new version?

**Comment by ludobonnet** [comment]
in a very classic way: npm install -g serverless

**Comment by ludobonnet** [comment]
This is a problem with this version of node. If I change with nvm the version to 12 it works ...

**Comment by medikoo** [comment]
What is your version of npm? Note that Node.js v13 is technically dead, it's either v14 or v12 you should be relying on now.

It's also most likely is some problem with your setup, as if it'll be the real issue on our side. we'd receive many reports, and this issue would quickly become crowded.

**Comment by medikoo** [comment]
See: https://github.com/uuidjs/uuid/issues/440

**Comment by entozoon** [comment]
Can confirm failure with node v13.6.0 and it's npm version - but if you [install nvm](https://github.com/coreybutler/nvm-windows) it's all fine with:
```bash
nvm install 12.16.3
nvm use 12.16.3 
```

**Comment by medikoo** [comment]
It affects all Node.js v13 versions below v13.7.0

To me it feels as bug on Node.js side in mentioned versions, and I'm not sure is it worth to downgrade `uuid` just for the sake of supporting Node.js `v13.0.0 - v13.6.0`
