### ISSUE TITLE
SQS FIFO Queue MaxiumumRetryAttempts not supported error

### ISSUE THREAD

**Issue by oscarmrom** [serverless/serverless#7762]
Trying to set MaximumRetryAttempts for an SQS FIFO Queue I get an error that says: 

```
MaxiumumRetryAttempts isn't supported for this event source type. (Service: AWSLambda; Status Code: 400; Error Code: InvalidParameterValueException; 
```

I noticed that in the error output `Maximum` is misspelled as `MaxiUmum`. I double checked my serverless.yml and the CloudFormation template it generates to see if the typo was there; it was not. 

I posted this question in the Serverless slack: https://serverless-contrib.slack.com/archives/CA4QT5VU3/p1589956251138100?thread_ts=1589905716.131700&cid=CA4QT5VU3

@garethmcc responded with the following: 

> It is possible there is a bug related to the implementation of this with FIFO queues in the open source framework, especially since fifo queue support as an event trigger is actually very new.

I have two serverless.yml configs one for the queue and one for the Lambda that subscribes to the Queue.

SQS FIFO Queue Config:

<details>
<summary><code>sqs/serverless.yml</code></summary>

```yaml
service: sqs
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

resources:
  Resources:
    SqsQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "queue.fifo"
        ContentBasedDeduplication: true
        FifoQueue: true
        VisibilityTimeout: 5400
  Outputs:
    SqsQueueArn:
      Description: The ARN for the SQS Queue
      Value:
        "Fn::GetAtt":
          - SqsQueue
          - Arn
```
</details>

Lambda Subscriber to Queue Config:
<details>
<summary><code>subscriber/serverless.yml</code></summary>

```yaml
service: subscriber

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  subscriber:
    handler: handler.handler
    timeout: 900
    events:
      - sqs:
          arn: ${cf:sqs-${opt:stage}.SqsQueueArn}
          batchSize: 2
          maximumRetryAttempts: 2
```
</details>

<details>
<summary><b><code>SLS_DEBUG=* serverless deploy -s test</code> output</b></summary>

```
bash-3.2$ SLS_DEBUG=* serverless deploy -s test
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command deploy
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
Serverless: [AWS cloudformation 200 0.253s 0 retries] describeStacks({ StackName: 'sqs-test' })
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 400 0.223s 0 retries] describeStacks({ StackName: 'subscriber-test' })
Serverless: Creating Stack...
Serverless: [AWS cloudformation 200 0.359s 0 retries] createStack({
  StackName: 'subscriber-test',
  OnFailure: 'DELETE',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateBody: '{"AWSTemplateFormatVersion":"2010-09-09","Description":"The AWS CloudFormation template for this Serverless application","Resources":{"ServerlessDeploymentBucket":{"Type":"AWS::S3::Bucket","Properties":{"BucketEncryption":{"ServerSideEncryptionConfiguration":[{"ServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}}},"ServerlessDeploymentBucketPolicy":{"Type":"AWS::S3::BucketPolicy","Properties":{"Bucket":{"Ref":"ServerlessDeploymentBucket"},"PolicyDocument":{"Statement":[{"Action":"s3:*","Effect":"Deny","Principal":"*","Resource":[{"Fn::Join":["",["arn:",{"Ref":"AWS::Partition"},":s3:::",{"Ref":"ServerlessDeploymentBucket"},"/*"]]}],"Condition":{"Bool":{"aws:SecureTransport":false}}}]}}}},"Outputs":{"ServerlessDeploymentBucketName":{"Value":{"Ref":"ServerlessDeploymentBucket"}}}}',
  Tags: [ { Key: 'STAGE', Value: 'test' }, [length]: 1 ]
})
Serverless: Checking Stack create progress...
Serverless: [AWS cloudformation 200 0.23s 0 retries] describeStackEvents({
  StackName: 'masked'
})
...Serverless: [AWS cloudformation 200 0.23s 0 retries] describeStackEvents({
  StackName: 'masked'
})
Serverless: [AWS cloudformation 200 0.207s 0 retries] describeStackEvents({
  StackName: 'masked'
})
Serverless: [AWS cloudformation 200 0.529s 0 retries] describeStackEvents({
  StackName: 'masked'
})
Serverless: [AWS cloudformation 200 0.248s 0 retries] describeStackEvents({
  StackName: 'masked'
})
.Serverless: [AWS cloudformation 200 0.217s 0 retries] describeStackEvents({
  StackName: 'masked'
})
.Serverless: [AWS cloudformation 200 0.213s 0 retries] describeStackEvents({
  StackName: 'masked'
})
...
Serverless: Stack create finished...
Serverless: [AWS cloudformation 200 0.243s 0 retries] describeStackResource({
  StackName: 'subscriber-test',
  LogicalResourceId: 'ServerlessDeploymentBucket'
})
Serverless: [AWS s3 200 0.434s 0 retries] listObjectsV2({
  Bucket: 'subscriber-test-masked',
  Prefix: 'serverless/subscriber/test'
})
Serverless: [AWS lambda 404 0.283s 0 retries] getFunction({ FunctionName: 'subscriber-test-subscriber' })
Serverless: [AWS sts 200 0.23s 0 retries] getCallerIdentity({})
Serverless: Uploading CloudFormation file to S3...
Serverless: [AWS s3 200 0.312s 0 retries] putObject({
  Body: <Buffer 7b 22 41 57 53 54 65 6d 70 6c 61 74 65 46 6f 72 6d 61 74 56 65 72 73 69 6f 6e 22 3a 22 32 30 31 30 2d 30 39 2d 30 39 22 2c 22 44 65 73 63 72 69 70 74 ... 3082 more bytes>,
  Bucket: 'subscriber-test-masked',
  Key: 'masked',
  ContentType: 'application/json',
  Metadata: { filesha256: masked }
})
Serverless: Uploading artifacts...
Serverless: Uploading service subscriber.zip file to S3 (8.88 MB)...
Serverless: [AWS s3 200 0.232s 0 retries] createMultipartUpload({
  Bucket: 'subscriber-test-masked',
  Key: 'masked',
  ContentType: 'application/zip',
  Metadata: { filesha256: 'masked' }
})
Serverless: [AWS s3 200 10.185s 0 retries] uploadPart({
  Body: <Buffer b8 3d 26 da 21 65 cd d8 7d a6 9d 0e 7d fd 59 83 97 5f bd 7e d3 0d cc 3c 8c df 8b c0 72 c7 f5 15 e6 9f fa f4 04 f7 4e a7 88 e2 a2 c7 a9 3b cf 03 7a 38 ... 4063987 more bytes>,
  ContentLength: 4064037,
  PartNumber: 2,
  Bucket: 'subscriber-test-masked',
  Key: 'masked',
  UploadId: masked
})
Serverless: [AWS s3 200 11.165s 0 retries] uploadPart({
  Body: <Buffer 50 4b 03 04 14 00 08 00 08 00 00 00 21 00 00 00 00 00 00 00 00 00 00 00 00 00 16 00 00 00 6e 6f 64 65 5f 6d 6f 64 75 6c 65 73 2f 2e 62 69 6e 2f 75 75 ... 5242830 more bytes>,
  ContentLength: 5242880,
  PartNumber: 1,
  Bucket: 'subscriber-test-masked',
  Key: 'masked',
  UploadId: masked
})
Serverless: [AWS s3 200 0.364s 0 retries] completeMultipartUpload({
  MultipartUpload: {
    Parts: [
      { ETag: '"masked"', PartNumber: 1 },
      { ETag: '"masked"', PartNumber: 2 },
      [length]: 2
    ]
  },
  Bucket: 'subscriber-test-masked',
  Key: 'masked',
  UploadId: masked
})
Serverless: Validating template...
Serverless: [AWS cloudformation 200 0.461s 0 retries] validateTemplate({
  TemplateURL: 'masked'
})
Serverless: Updating Stack...
Serverless: [AWS cloudformation 200 0.535s 0 retries] updateStack({
  StackName: 'subscriber-test',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL: 'masked',
  Tags: [ { Key: 'STAGE', Value: 'test' }, [length]: 1 ]
})
Serverless: Checking Stack update progress...
Serverless: [AWS cloudformation 200 0.274s 0 retries] describeStackEvents({
  StackName: 'masked'
})
.....Serverless: [AWS cloudformation 200 0.249s 0 retries] describeStackEvents({
  StackName: 'masked'
})
.Serverless: [AWS cloudformation 200 0.222s 0 retries] describeStackEvents({
  StackName: 'masked'
})
Serverless: [AWS cloudformation 200 0.268s 0 retries] describeStackEvents({
  StackName: 'masked'
})
..Serverless: [AWS cloudformation 200 0.285s 0 retries] describeStackEvents({
  StackName: 'masked'
})
......
Serverless: Operation failed!
Serverless: View the full error output: masked

  Serverless Error ---------------------------------------

  ServerlessError: An error occurred: SubscriberEventSourceMappingSQSQueuefifo - MaxiumumRetryAttempts isn't supported for this event source type. (Service: AWSLambda; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: e3b7d310-8d28-4008-a510-31431f17a6d5).
      at masked/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:125:33
  From previous event:
      at AwsDeploy.monitorStack (masked/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:28:12)
      at masked/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:107:28
  From previous event:
      at AwsDeploy.update (masked/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:107:8)
  From previous event:
      at AwsDeploy.<anonymous> (masked/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:121:35)
  From previous event:
      at AwsDeploy.updateStack (masked/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:117:33)
  From previous event:
      at AwsDeploy.<anonymous> (masked/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:127:39)
  From previous event:
      at Object.aws:deploy:deploy:updateStack [as hook] (masked/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:123:30)
      at masked/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/lib/classes/PluginManager.js:490:55
  From previous event:
      at PluginManager.invoke (masked/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at PluginManager.spawn (masked/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/lib/classes/PluginManager.js:510:17)
      at AwsDeploy.<anonymous> (masked/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:93:48)
  From previous event:
      at Object.deploy:deploy [as hook] (masked/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:89:30)
      at masked/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/lib/classes/PluginManager.js:490:55
  From previous event:
      at PluginManager.invoke (masked/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at masked/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/lib/classes/PluginManager.js:525:24
  From previous event:
      at PluginManager.run (masked/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/lib/classes/PluginManager.js:525:8)
      at masked/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/lib/Serverless.js:133:33
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Serverless.run (masked/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/lib/Serverless.js:120:74)
      at masked/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/bin/serverless.js:80:26
      at masked/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:144:16
      at masked/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:61:14
      at FSReqCallback.oncomplete (fs.js:154:23)
  From previous event:
      at Object.<anonymous> (masked/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/bin/serverless.js:80:4)
      at Module._compile (internal/modules/cjs/loader.js:1158:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
      at Module.load (internal/modules/cjs/loader.js:1002:32)
      at Function.Module._load (internal/modules/cjs/loader.js:901:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
      at internal/main/run_main_module.js:18:47

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.16.1
     Framework Version:         1.70.1
     Plugin Version:            3.6.11
     SDK Version:               2.3.0
     Components Version:        2.30.10
```

</details>

<b>Installed version</b>

```
Framework Core: 1.70.1
Plugin: 3.6.11
SDK: 2.3.0
Components: 2.30.10
```

**Comment by medikoo** [comment]
@oscarmrom the error you see is originated by AWS service. Framework just propagates `maximumRetryAttempts` to `MaximumRetryAttempts` setting.

I would contact AWS about it, to confirm whether really this setting is not supported on SQS streams. Typo in error message suggests there might be an issue on AWS side.

If it appers that it's not support, then issue on Framework side is that it tries to support it, and workaround for you is just to remove `maximumRetryAttempts` from config

**Comment by oscarmrom** [comment]
Got it. I'll reach out to AWS and confirm whether or not this functionality is supported for FIFO queues.

**Comment by rainmirror1** [comment]
I've got the same issue on my Linux machine, though on my Mac everything is fine.

Installed version on Linux:
```Framework Core: 1.70.0 (standalone)
Plugin: 3.6.11
SDK: 2.3.0
Components: 2.30.10```

Installed version on MacOS:
```1.49.0 (Enterprise Plugin: 1.3.8, Platform SDK: 2.1.0)```

**Comment by oscarmrom** [comment]
@rainmirror1, not sure how you're getting it to work or if it's just not throwing an error for it on your Mac. I was running this on MacOS and getting the error. 

This is what AWS said, @medikoo:

```The configuration parameter MaximumRetryAttempts is only supported for Kinesis Streams

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html#cfn-lambda-eventsourcemapping-maximumretryattempts
```

Which now makes sense why there is a parenthesis with "Streams" in the docs. That wasn't clear to me at first.

**Comment by IikkaWinter** [comment]
I can confirm that deployments worked on my local Mac but I got the same error when deploying from CodePipeline. I think @oscarmrom found the culprit here (MaximumRetryAttempts not supported by SQS) hence the document should also be updated: https://www.serverless.com/framework/docs/providers/aws/events/sqs/

**Comment by oscarmrom** [comment]
Ah, are you deploying this locally or to AWS when you don't experience any error, @IikkaWinter?

**Comment by IikkaWinter** [comment]
> Ah, are you deploying this locally or to AWS when you don't experience any error, @IikkaWinter?

To AWS. Sorry for the confusing sentence. So deployment **from** mac to AWS didn't fail.

**Comment by medikoo** [comment]
> The configuration parameter MaximumRetryAttempts is only supported for Kinesis Streams

Thanks for info. In that case there's a bug. We should not document and try to support `maximumRetryAttempts` for SQS streams.

PR's welcome1

**Comment by mnapoli** [comment]
> Which now makes sense why there is a parenthesis with "Streams" in the docs. That wasn't clear to me at first.

@oscarmrom oh that's a good point! I came to the same conclusion but via a different documentation: https://github.com/serverless/serverless/pull/7620#issuecomment-641104677

I sent a pull request to the AWS docs to make this clearer: https://github.com/awsdocs/aws-cloudformation-user-guide/pull/715
