### ISSUE TITLE
v0.5 - Region null error on endpoint deploy

### ISSUE THREAD

**Issue by jordanmack** [serverless/serverless#777]
The error `ServerlessError: Region null doesnt exist in stage dev!` is received from the command line when the region (-r) has not been specified.

This error was received on a brand new test project created with v0.5:

```
username@ubuntu:~/Desktop/sls-test4$ sls endpoint deploy
/home/username/Desktop/serverless/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

ServerlessError: Region null doesnt exist in stage dev!
    at new ServerlessError (/home/username/Desktop/serverless/lib/Error.js:17:11)
    at Project.getRegion (/home/username/Desktop/serverless/lib/Project.js:246:15)
    at EndpointDeployApiGateway.endpointDeployApiGateway (/home/username/Desktop/serverless/lib/actions/EndpointDeployApiGateway.js:57:46)

```

```
username@ubuntu:~/Desktop/sls-test4$ sls dash summary
...
Serverless: 1 stages ------------------------------  
Serverless:     |_ dev (1 regions)  
Serverless:         |_ us-east-1  

Serverless: 1 functions --------------------------  
Serverless:     |_ helloworld (1 endpoints - 0 events)  
Serverless:             |_ GET helloworld (endpoint)  

Serverless: SUMMARY -------------------------------  
Serverless: stages     : 1  
Serverless: regions    : 1  
Serverless: functions  : 1  
Serverless: endpoints  : 1  
Serverless: events     : 0  
```

**Comment by HyperBrain** [comment]
Checked the implementation. `options.region` is used without validation when retrieving the accountId (EndpointDeployApiGateway:_line 57_). The available regions are evaluated one line below.
I would expect that the available regions are evaluated first.
