### ISSUE TITLE
Serverless bug above 1.70.0

### ISSUE THREAD

**Issue by Pi-George** [serverless/serverless#7777]
```
/usr/lib/node_modules/serverless/node_modules/uuid/dist/rng.js:15
return _crypto.default.randomFillSync(rnds8);
^
TypeError: _crypto.default.randomFillSync is not a function
at rng (/usr/lib/node_modules/serverless/node_modules/uuid/dist/rng.js:15:26)
at Object.v1 (/usr/lib/node_modules/serverless/node_modules/uuid/dist/v1.js:36:70)
at Object.generateFrameworkId (/usr/lib/node_modules/serverless/lib/utils/config/initialSetup.js:33:15)
at createConfig (/usr/lib/node_modules/serverless/lib/utils/config/index.js:46:31)
at getConfig (/usr/lib/node_modules/serverless/lib/utils/config/index.js:72:5)
at Object.get (/usr/lib/node_modules/serverless/lib/utils/config/index.js:117:18)
at Object.<anonymous> (/usr/lib/node_modules/serverless/lib/utils/isTrackingDisabled.js:5:75)
```

Our pipeline has been hitting this error every time, it happens on a regular `serverless invoke` execution. We've locked down our version to 1.70.0 to avoid the issue.

**Comment by medikoo** [comment]
@Pi-George What version of Node.js are you using?

**Comment by Pi-George** [comment]
Our pipeline uses: `curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash - && sudo apt-get install -y nodejs`

By the way, the versions I specified in the original issue are wrong, I'm checking the actual versions it's broken with now

**Comment by Pi-George** [comment]
Yeah, pipeline is working fine now that I've downgraded to 1.70.0. Sorry for jumping the gun and making this issue before I was 100% sure of the cause.

**Comment by Pi-George** [comment]
I'll close this since you've made a PR to fix this
