### ISSUE TITLE
can't deploy httpApi to af-south-1

### ISSUE THREAD

**Issue by ilanc** [serverless/serverless#7815]
I am able to deploy lambdas to the new africa region `af-south-1` - however I cannot deploy lambdas that use the new [httpApi](https://www.serverless.com/blog/aws-http-api-support/) endpoints.

NB I'm aware of #7796  - this issue is different - I'm not attempting to use the Serverless Framework - just the serverless deployment tool.

The error I get is:
```sh
Must be one of [WEBSOCKET] (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException; Request ID: a23bd953-cff3-4702-ba2e-f0491bb5162d).
```

Does this mean that af-south-1 doesn't support httpApi lambdas? and if so - any idea whom I take it up with at AWS? / can you work any magic with your connections to AWS ;)

I asked about this on the forum without any luck. NB I got a different error at the time:
- https://forum.serverless.com/t/deploy-to-af-south-1-region/11268

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: http-api-hello-js-za

provider:
  name: aws
  runtime: nodejs12.x
  region: af-south-1
  stage: prod

functions:
  hello:
    handler: hello.get
    events:
      - httpApi:
          method: GET
          path: /hello
```

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 200 0.31s 0 retries] describeStacks({ StackName: 'http-api-hello-js-za-prod' })
Serverless: [AWS cloudformation 200 0.07s 0 retries] describeStackResource({
  StackName: 'http-api-hello-js-za-prod',
  LogicalResourceId: 'ServerlessDeploymentBucket'
})
Serverless: [AWS s3 200 0.332s 0 retries] listObjectsV2({
  Bucket: 'http-api-hello-js-za-pro-serverlessdeploymentbuck-a1v5ylpazoqy',
  Prefix: 'serverless/http-api-hello-js-za/prod'
})
Serverless: [AWS s3 200 0.263s 0 retries] headObject({
  Bucket: 'http-api-hello-js-za-pro-serverlessdeploymentbuck-a1v5ylpazoqy',
  Key: 'serverless/http-api-hello-js-za/prod/1591277704230-2020-06-04T13:35:04.230Z/compiled-cloudformation-template.json'
})
Serverless: [AWS s3 200 0.29s 0 retries] headObject({
  Bucket: 'http-api-hello-js-za-pro-serverlessdeploymentbuck-a1v5ylpazoqy',
  Key: 'serverless/http-api-hello-js-za/prod/1591277704230-2020-06-04T13:35:04.230Z/http-api-hello-js-za.zip'
})
Serverless: [AWS lambda 200 0.314s 0 retries] getFunction({ FunctionName: 'http-api-hello-js-za-prod-hello' })
Serverless: [AWS sts 200 1.356s 0 retries] getCallerIdentity({})
Serverless: Uploading CloudFormation file to S3...
Serverless: [AWS s3 200 0.091s 0 retries] putObject({
  Body: <Buffer 7b 22 41 57 53 54 65 6d 70 6c 61 74 65 46 6f 72 6d 61 74 56 65 72 73 69 6f 6e 22 3a 22 32 30 31 30 2d 30 39 2d 30 39 22 2c 22 44 65 73 63 72 69 70 74 ... 3890 more bytes>,
  Bucket: 'http-api-hello-js-za-pro-serverlessdeploymentbuck-a1v5ylpazoqy',
  Key: 'serverless/http-api-hello-js-za/prod/1591278936807-2020-06-04T13:55:36.807Z/compiled-cloudformation-template.json',
  ContentType: 'application/json',
  Metadata: { filesha256: 'RO6KNUNydqht6Th8wxoR48c6OJeBJUfsiZZRGuwLkpU=' }
})
Serverless: Uploading artifacts...
Serverless: Uploading service http-api-hello-js-za.zip file to S3 (348 B)...
Serverless: [AWS s3 200 0.042s 0 retries] putObject({
  Body: <Buffer 50 4b 03 04 14 00 08 00 08 00 00 00 21 00 00 00 00 00 00 00 00 00 00 00 00 00 08 00 00 00 68 65 6c 6c 6f 2e 6a 73 85 51 b1 6e 83 40 0c dd ef 2b 9e b2 ... 298 more bytes>,
  Bucket: 'http-api-hello-js-za-pro-serverlessdeploymentbuck-a1v5ylpazoqy',
  Key: 'serverless/http-api-hello-js-za/prod/1591278936807-2020-06-04T13:55:36.807Z/http-api-hello-js-za.zip',
  ContentType: 'application/zip',
  Metadata: { filesha256: 'jGdSdStSXP2SdAYsCuF7hRyhLLQ5wKGwFm0c4EGnVZw=' }
})
Serverless: Validating template...
Serverless: [AWS cloudformation 200 1.155s 0 retries] validateTemplate({
  TemplateURL: 'https://s3.amazonaws.com/http-api-hello-js-za-pro-serverlessdeploymentbuck-a1v5ylpazoqy/serverless/http-api-hello-js-za/prod/1591278936807-2020-06-04T13:55:36.807Z/compiled-cloudformation-template.json'
})
Serverless: Updating Stack...
Serverless: [AWS cloudformation 200 1.219s 0 retries] updateStack({
  StackName: 'http-api-hello-js-za-prod',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL: 'https://s3.amazonaws.com/http-api-hello-js-za-pro-serverlessdeploymentbuck-a1v5ylpazoqy/serverless/http-api-hello-js-za/prod/1591278936807-2020-06-04T13:55:36.807Z/compiled-cloudformation-template.json',
  Tags: [ { Key: 'STAGE', Value: 'prod' }, [length]: 1 ]
})
Serverless: Checking Stack update progress...
Serverless: [AWS cloudformation 200 0.122s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:af-south-1:366730223589:stack/http-api-hello-js-za-prod/de237750-a667-11ea-b0ab-0eeef44aae90'
})
.Serverless: [AWS cloudformation 200 0.091s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:af-south-1:366730223589:stack/http-api-hello-js-za-prod/de237750-a667-11ea-b0ab-0eeef44aae90'
})
Serverless: [AWS cloudformation 200 0.125s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:af-south-1:366730223589:stack/http-api-hello-js-za-prod/de237750-a667-11ea-b0ab-0eeef44aae90'
})
Serverless: [AWS cloudformation 200 0.124s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:af-south-1:366730223589:stack/http-api-hello-js-za-prod/de237750-a667-11ea-b0ab-0eeef44aae90'
})
Serverless: [AWS cloudformation 200 0.088s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:af-south-1:366730223589:stack/http-api-hello-js-za-prod/de237750-a667-11ea-b0ab-0eeef44aae90'
})
.....
Serverless: Operation failed!
Serverless: View the full error output: https://af-south-1.console.aws.amazon.com/cloudformation/home?region=af-south-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aaf-south-1%3A366730223589%3Astack%2Fhttp-api-hello-js-za-prod%2Fde237750-a667-11ea-b0ab-0eeef44aae90
 
  Serverless Error ---------------------------------------
 
  ServerlessError: An error occurred: HttpApi - Invalid protocol specified. Must be one of [WEBSOCKET] (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException; Request ID: a23bd953-cff3-4702-ba2e-f0491bb5162d).
      at /home/ilan/.nvm/versions/node/v14.1.0/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:125:33
  From previous event:
      at AwsDeploy.monitorStack (/home/ilan/.nvm/versions/node/v14.1.0/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:28:12)
      at /home/ilan/.nvm/versions/node/v14.1.0/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:115:28
  From previous event:
      at AwsDeploy.update (/home/ilan/.nvm/versions/node/v14.1.0/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:115:8)
  From previous event:
      at AwsDeploy.<anonymous> (/home/ilan/.nvm/versions/node/v14.1.0/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:129:35)
  From previous event:
      at AwsDeploy.updateStack (/home/ilan/.nvm/versions/node/v14.1.0/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:125:33)
  From previous event:
      at AwsDeploy.<anonymous> (/home/ilan/.nvm/versions/node/v14.1.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:127:39)
  From previous event:
      at Object.aws:deploy:deploy:updateStack [as hook] (/home/ilan/.nvm/versions/node/v14.1.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:123:30)
      at /home/ilan/.nvm/versions/node/v14.1.0/lib/node_modules/serverless/lib/classes/PluginManager.js:490:55
  From previous event:
      at PluginManager.invoke (/home/ilan/.nvm/versions/node/v14.1.0/lib/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at PluginManager.spawn (/home/ilan/.nvm/versions/node/v14.1.0/lib/node_modules/serverless/lib/classes/PluginManager.js:510:17)
      at AwsDeploy.<anonymous> (/home/ilan/.nvm/versions/node/v14.1.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:93:48)
  From previous event:
      at Object.deploy:deploy [as hook] (/home/ilan/.nvm/versions/node/v14.1.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:89:30)
      at /home/ilan/.nvm/versions/node/v14.1.0/lib/node_modules/serverless/lib/classes/PluginManager.js:490:55
  From previous event:
      at PluginManager.invoke (/home/ilan/.nvm/versions/node/v14.1.0/lib/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at /home/ilan/.nvm/versions/node/v14.1.0/lib/node_modules/serverless/lib/classes/PluginManager.js:525:24
  From previous event:
      at PluginManager.run (/home/ilan/.nvm/versions/node/v14.1.0/lib/node_modules/serverless/lib/classes/PluginManager.js:525:8)
      at /home/ilan/.nvm/versions/node/v14.1.0/lib/node_modules/serverless/lib/Serverless.js:133:33
  From previous event:
      at Serverless.run (/home/ilan/.nvm/versions/node/v14.1.0/lib/node_modules/serverless/lib/Serverless.js:120:74)
      at /home/ilan/.nvm/versions/node/v14.1.0/lib/node_modules/serverless/bin/serverless.js:80:26
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Object.<anonymous> (/home/ilan/.nvm/versions/node/v14.1.0/lib/node_modules/serverless/bin/serverless.js:80:4)
      at Module._compile (internal/modules/cjs/loader.js:1176:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
      at Module.load (internal/modules/cjs/loader.js:1040:32)
      at Function.Module._load (internal/modules/cjs/loader.js:929:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
      at internal/main/run_main_module.js:17:47
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.1.0
     Framework Version:         1.72.0
     Plugin Version:            3.6.13
     SDK Version:               2.3.1
     Components Version:        2.30.12
```

</details>

<b>Installed version</b>

```
Framework Core: 1.72.0
Plugin: 3.6.13
SDK: 2.3.1
Components: 2.30.12
```

**Comment by medikoo** [comment]
@ilanc This error surfaces from AWS, which states that only Websocket API is supported.
It might be that for some reason HTTP API's are not available yet in `af-south-1` region. Have you confirmed that?

**Comment by ilanc** [comment]
Does serverless have any channels through which to ask questions of aws? My only option is to raise a support ticket with them. In the past this has simply resulted in me being charged money to say that they are not going to fix the problem

**Comment by ilanc** [comment]
But given that it's not a Sls prob I'll close the ticket. Just wanted to eliminate aws finger pointing at sls

**Comment by medikoo** [comment]
Firstly you need to confirm with AWS directly that HTTP API is supported in given region (they have support and forums).

For Framework related issues please use forums https://forum.serverless.com/ or slack https://www.serverless.com/slack

**Comment by ilanc** [comment]
btw it looks like AWS has fixed this - I can now deploy to af-south-1 - hooray!
