### ISSUE TITLE
Using intrinsic functions at authorizer.type will throw TypeError: http.authorizer.type.toUpperCase is not a function

### ISSUE THREAD

**Issue by Carpuller** [serverless/serverless#7853]
When using intrinsic functions, such as `!If` in Lambda function authorizer.type, it throws `TypeError: http.authorizer.type.toUpperCase is not a function`. The framework doesn't check if type is a string before calling toUpperCase at https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/apiGateway/lib/method/authorization.js#L25.

<details>
<summary><code>serverless.yml</code></summary>

```yaml

functions:
  hello:
    events:
      - http:
          path: /
          method: get
          authorizer:
            type: !If [
              SomeCondition,
              CUSTOM,
              NONE,
            ]
            authorizerId: !If [
              SomeCondition,
              !Ref SomeAuthorizer,
              !Ref AWS::NoValue,
            ]
```

</details>

<details>
<summary><b><code>REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
Type Error ---------------------------------------------                                                                                                                                                   [0/1647]

  TypeError: http.authorizer.type.toUpperCase is not a function
      at AwsCompileApigEvents.getMethodAuthorization (~/hello/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/authorization.js:25:32)
      at validated.events.forEach.event (~/hello/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.js:57:14)
      at Array.forEach (<anonymous>)
      at AwsCompileApigEvents.compileMethods (~/hello/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.js:10:27)
  From previous event:
      at Object.package:compileEvents [as hook] (~/hello/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/index.js:63:12)
      at BbPromise.reduce (~/hello/node_modules/serverless/lib/classes/PluginManager.js:490:55)
  From previous event:
      at PluginManager.invoke (~/hello/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at PluginManager.spawn (~/hello/node_modules/serverless/lib/classes/PluginManager.js:510:17)
      at Deploy.BbPromise.bind.then (~/hello/node_modules/serverless/lib/plugins/deploy/deploy.js:115:50)
  From previous event:
      at Object.before:deploy:deploy [as hook] (~/hello/node_modules/serverless/lib/plugins/deploy/deploy.js:100:30)
      at BbPromise.reduce (~/hello/node_modules/serverless/lib/classes/PluginManager.js:490:55)
  From previous event:
      at PluginManager.invoke (~/hello/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at getHooks.reduce.then (~/hello/node_modules/serverless/lib/classes/PluginManager.js:525:24)
  From previous event:
      at PluginManager.run (~/hello/node_modules/serverless/lib/classes/PluginManager.js:525:8)
      at variables.populateService.then (~/hello/node_modules/serverless/lib/Serverless.js:133:33)
  From previous event:
      at Serverless.run (~/hello/node_modules/serverless/lib/Serverless.js:120:74)
      at serverless.init.then (~/hello/node_modules/serverless/bin/serverless.js:80:26)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)
  From previous event:
      at Object.<anonymous> (~/hello/node_modules/serverless/bin/serverless.js:80:4)
      at Module._compile (internal/modules/cjs/loader.js:778:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
      at Module.load (internal/modules/cjs/loader.js:653:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
      at Function.Module._load (internal/modules/cjs/loader.js:585:3)
      at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
      at startup (internal/bootstrap/node.js:283:19)
      at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

</details>

<b>Installed version</b>

```
$ sls --version
Framework Core: 1.72.0
Plugin: 3.6.13
SDK: 2.3.1
Components: 2.30.12
```

**Comment by medikoo** [comment]
@carpusherw `authorizer.type` is expected to be a _string_. We do not support there CF instructions.

Such errors will propagated with more meaningful messages once we have https://github.com/serverless/serverless/issues/6562 in (with full validation for `http` event).

If you ask to support CF instructions there. Then it may require a further thought, and is not as trivial to address.
Packing of a service (generation of CF template) is normally an _offline_ operation, that doesn't require requests to external resources, while with CF instructions we may be forced to resolve them with help of AWS SDK

**Comment by carpusherw** [comment]
Thank you @medikoo for you reply. I intention is not to resolve the intrinsic functions when generating CF template when offline, but to leave the intrinsic functions as it is in the template and let CF to resolve in when updating the stack online. You may notice in my posted serverless.yml, I also uses intrinsic functions in authorizerId, and which is left as it is like this in `cloudformation-template-update-stack.json`.

```json
"AuthorizerId": {
  "Fn::If": [
    "IsNotPRStage",
    {
      "Ref": "APIAuthorizer"
    },
    {
      "Ref": "AWS::NoValue"
    }
  ]
},
```

**Comment by medikoo** [comment]
@carpusherw at this point for packaging `autorizer.type` needs to be in resolved form, as it influences other template generation logic. It's not jut the value that we pass blindly to CF template.

**Comment by carpusherw** [comment]
Hi @medikoo , my real need behind this is to config authorization type base on some conditions. Is it true that currently Serverless Framework doesn't support this? What do you think if I close this case and create another feature request to support it?

**Comment by medikoo** [comment]
> if I close this case and create another feature request to support it?

I think we may keep this issue for that. I've updated the labels, and renamed title. It needs now some spec on how to implement it without sacrificing any currently working features
