### ISSUE TITLE
v0.5 - apiGatewayApi defined in s-variables-[stage].json ignored (possible variables resolution bug?)

### ISSUE THREAD

**Issue by erikerikson** [serverless/serverless#791]
If apiGatewayApi is defined in s-variables-[stage].json rather than s-variables-[stage]-[region].json, SLS reports that it doesn't find the API and errors out.

Although an API will have a different ID in each region, it is valid for APIs in different regions to have the same name.  Previously SLS was identifying APIs by their ID but it switched over to using the name of the API.  As such, it should be possible to define the cross-region name of the API.

Workaround: move apiGatewayApi to s-variables-[stage]-[region].json

**Comment by erikerikson** [comment]
This also occurs if the apiGatewayApi variable is defined in s-variables-common.json rather than s-variables-[stage]-[region].json.

**Comment by erikerikson** [comment]
To be more explicit about reproduction, I am running the command:
`sls endpoint deploy -s [stage] -r [region]`

When I do so, the `apiGatewayApi` variable is defined in `s-variables-common.json` or `s-variables-[stage].json`

I end up getting an error that most probably wouldn't get because the credentials I am using don't have the rights to create an API Gateway instance despite full modification rights on the existing API.  Regardless, our naming convention must be followed and the generated name would be rejected.

The full (misleading) error is:
```
Serverless: / /src/serverless/node_modules/bluebird/js/release/async.js:48
        fn = function () { throw arg; };
                           ^

AccessDeniedException: User: arn:aws:sts::[accountId]:assumed-role/[ROLE]/[UID] is not authorized to perform: apigateway:POST on resource: arn:aws:apigateway:[region]::/restapis
    at Object.extractError (/src/serverless/node_modules/aws-sdk/lib/protocol/json.js:43:27)
    at Request.extractError (/src/serverless/node_modules/aws-sdk/lib/protocol/rest_json.js:37:8)
    at Request.callListeners (/src/serverless/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/src/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/src/serverless/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/src/serverless/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/src/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /src/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/src/serverless/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/src/serverless/node_modules/aws-sdk/lib/request.js:598:12)
    at Request.callListeners (/src/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/src/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/src/serverless/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/src/serverless/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/src/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /src/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/src/serverless/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/src/serverless/node_modules/aws-sdk/lib/request.js:598:12)
    at Request.callListeners (/src/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/src/serverless/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at IncomingMessage.onEnd (/src/serverless/node_modules/aws-sdk/lib/event_listeners.js:209:11)
    at emitNone (events.js:72:20)
From previous event:
    at ServerlessProviderAws.request (/src/serverless/lib/ProviderAws.js:65:14)
    at /src/serverless/lib/actions/EndpointDeployApiGateway.js:236:33
From previous event:
    at EndpointDeployApiGateway._findOrCreateRestApi (/src/serverless/lib/actions/EndpointDeployApiGateway.js:225:10)
    at EndpointDeployApiGateway._processRegionDeployment (/src/serverless/lib/actions/EndpointDeployApiGateway.js:120:20)
    at EndpointDeployApiGateway.<anonymous> (/src/serverless/lib/actions/EndpointDeployApiGateway.js:94:24)
From previous event:
    at EndpointDeployApiGateway._processDeployment (/src/serverless/lib/actions/EndpointDeployApiGateway.js:91:10)
From previous event:
    at EndpointDeployApiGateway.endpointDeployApiGateway (/src/serverless/lib/actions/EndpointDeployApiGateway.js:55:10)
From previous event:
    at /src/serverless/lib/Serverless.js:207:25
    at Array.reduce (native)
    at Serverless._execute (/src/serverless/lib/Serverless.js:206:26)
    at Object.actions.(anonymous function) [as endpointDeployApiGateway] (/src/serverless/lib/Serverless.js:425:20)
    at EndpointDeploy._processDeployment (/src/serverless/lib/actions/EndpointDeploy.js:212:24)
From previous event:
    at EndpointDeploy.endpointDeploy (/src/serverless/lib/actions/EndpointDeploy.js:101:12)
From previous event:
    at /src/serverless/lib/Serverless.js:182:31
    at Array.reduce (native)
    at /src/serverless/lib/Serverless.js:181:32
From previous event:
    at Serverless._execute (/src/serverless/lib/Serverless.js:179:12)
    at Serverless.actions.(anonymous function) (/src/serverless/lib/Serverless.js:425:20)
    at Serverless.command (/src/serverless/lib/Serverless.js:394:38)
    at /src/serverless/bin/serverless:19:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Object.<anonymous> (/src/serverless/bin/serverless:18:4)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

**Comment by eahefnawy** [comment]
@erikerikson so if I understand this correctly, it should work if we just try to load the APIG name from stage/common variables too? cause you're right, the error is misleading!

**Comment by erikerikson** [comment]
@eahefnawy My understanding is that there is effectively an inheritance of values:
```
->common
    |->[stage]
        |-> [stage]-[region]
```
A value defined in common applies to all stages and regions.
A value defined in a stage file applies to all regions within that stage.
Values within a stage-region file apply only to that region within the stage.

The protocol is to load the common values, then the stage values (overwriting any already loaded and also duplicated values), and finally loading the region values (again overriding duplicates).

This would allow me to define the apiGatewayApi variable (or any other) in s-variables-common.json or s-variables-[stage].json and have the value be usable in the endpoints deploy (or any other command).

This is similar to s-templates.json in a sense, except that instead of using the directory structure based hierarchy, there's a shallow common > stage > stage-region hierarchy.

**Comment by flomotlik** [comment]
As we're currently rethinking stage/region and variables we can discuss it there
