### ISSUE TITLE
http error, when i use serverless deploy

### ISSUE THREAD

**Issue by zhaogaiwen** [serverless/serverless#7916]
this is my serverless.yml

service: my-knative-java
provider:
  name: knative
  docker:
    username: zhaogaiwen
    password: zhao19901013

functions:
  hello:
    handler: hello-world.dockerfile
    context: ./code
plugins:
  - serverless-knative

this is the exception:

Serverless: Deploying Kubernetes namespace "sls-aws-java-maven-dev"...
Serverless: Deploying Knative service for function "aws-java-maven-hello"...
 
  Http Error ---------------------------------------------
 
  HttpError: HTTP request failed
      at Request.localVarRequest [as _callback] (/home/ec2-user/zgw/aws-java-maven/node_modules/@kubernetes/client-node/dist/gen/api/customObjectsApi.js:254:40)
      at Request.self.callback (/home/ec2-user/zgw/aws-java-maven/node_modules/request/request.js:185:22)
      at Request.emit (events.js:198:13)
      at Request.EventEmitter.emit (domain.js:448:20)
      at Request.<anonymous> (/home/ec2-user/zgw/aws-java-maven/node_modules/request/request.js:1154:10)
      at Request.emit (events.js:198:13)
      at Request.EventEmitter.emit (domain.js:448:20)
      at IncomingMessage.<anonymous> (/home/ec2-user/zgw/aws-java-maven/node_modules/request/request.js:1076:12)
      at Object.onceWrapper (events.js:286:20)
      at IncomingMessage.emit (events.js:203:15)
      at IncomingMessage.EventEmitter.emit (domain.js:448:20)
      at endReadableNT (_stream_readable.js:1145:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by medikoo** [comment]
Please report at `serverless-knative` repository
