### ISSUE TITLE
Serverless plugin installation failures

### ISSUE THREAD

**Issue by seasuresh** [serverless/serverless#7923]
We suddenly noticed the following error on our serverless deployment build script, this was working until yesterday and there were no changes. Any idea why we get this error please? We execute python script on docker to install serverless plugins before we execute `sls deploy` command

```
  Error: Cannot find module 'lodash/fp'
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
      at Function.Module._load (internal/modules/cjs/loader.js:591:27)
      at Module.require (internal/modules/cjs/loader.js:723:19)
      at require (internal/modules/cjs/helpers.js:14:16)
      at Object.<anonymous> (/tmp/build/put/jar-repository/node_modules/serverless-plugin-canary-deployments/serverless-plugin-canary-deployments.js:1:11)
```

  ```
   Operating System:       linux
   Node Version:              11.15.0
   Framework Version:    1.74.1
   Plugin Version:            3.6.14
   SDK Version:               2.3.1
   Components Version:        2.31.7
```

**Comment by medikoo** [comment]
@seasuresh Please report at `serverless-plugin-canary-deployments`

**Comment by seasuresh** [comment]
> @seasuresh Please report at `serverless-plugin-canary-deployments`

@medikoo  Thanks! I reported here but not sure if this is the right place. Can you confirm?
https://github.com/davidgf/serverless-plugin-canary-deployments/issues/88
