### ISSUE TITLE
Use AWS region “invoke local” in serverless.yml, ~/.aws/config or env. variable

### ISSUE THREAD

**Issue by FrcMoya** [serverless/serverless#7929]
Hi!!

I am facing with a little issue using Serverless framework. I have a serverless.yml file with a region configured (eu-west-1). I am testing the lambda code (python 3.8) locally using sls invoke local -f <service_name>. The lambda uses the boto3 library to access to the ssm service where I store some secrets (database credentials, for example). The problem is that the “invoke local” function doesn’t seem to use neither the region in the serverless.yaml nor the region in the ~/.aws/config file (boto3 uses this configuration file by default or an environment variable called AWS_DEFAULT_REGION). I know I can use the "invoke local -r " and it works properly but IMO it should use the region configured in the serverless.yml file or the region in the aws config file.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: inventory-lambdas

provider:
    name: aws
    runtime: python3.8
    memorySize: 128
    environment:
        ENV1: ****
        ENV2: ****

stage: dev
region: eu-west-1

functions:
    Inventory:
        handler: Inventory.lambda_handler
        name: Inventory
        timeout: 60
        role: ****
        environment:
            ENV3: ****
            ENV4: ****
        layers:
            - ****
            - ****
```

</details>

<details>
<summary><b><code>sls invoke local -f Inventory</code> output</b></summary>

```
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/invoke.py", line 86, in <module>

    result = handler(input['event'], context)
  File "Inventory.py", line 29, in lambda_handler
    WithDecryption=True
  File "/home/frcmoya/.local/lib/python3.6/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/frcmoya/.local/lib/python3.6/site-packages/botocore/client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ParameterNotFound: An error occurred (ParameterNotFound) when calling the GetParameter operation:
```

</details>

<b>Installed version</b>

```
Operating System:          linux
Node Version:              8.10.0
Framework Version:         1.74.1
Plugin Version:            3.6.15
SDK Version:               2.3.1
Components Version:        2.31.12
```

**Comment by medikoo** [comment]
@FrcMoya this should rather be a bug report. Can you update the description using bug template? We need answers for all questions as listed there

**Comment by FrcMoya** [comment]
@medikoo changed the description to the bug template

**Comment by FrcMoya** [comment]
I've tried the command `sls invoke -f <function_name> -q <alias_name>` with the region in the serverless.yml file and it also fail (I have a lambda deployed in AWS that I want to invoke). Serverless doesn't use the region key in the serverless.yml for the invoke command and all its subcommands.

**Comment by medikoo** [comment]
@FrcMoya it'll be nice to have a full output (with `SLS_DEBUG=*` flag). 

Why do you assume that `botocore.errorfactory.ParameterNotFound: An error occurred (ParameterNotFound) when calling the GetParameter operation` error signals missing env variable?

**Comment by FrcMoya** [comment]
@medikoo On the one hand this is the output with the flag `SLS_DEBUG=*`
<details>
<summary><code>Output with SLS_DEBUG=*</code></summary>

```Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
Serverless: Invoke invoke:local
{'client_region': 'us-east-1', 'client_config': <botocore.config.Config object at 0x7f885d1677f0>, 'has_streaming_input': False, 'auth_type': None}

Traceback (most recent call last):
  File "/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/invoke.py", line 86, in <module>

    result = handler(input['event'], context)
  File "./src/Inventory/Inventory.py", line 29, in lambda_handler
    WithDecryption=True
  File "/home/frcmoya/.local/lib/python3.6/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/frcmoya/.local/lib/python3.6/site-packages/botocore/client.py", line 627, in _make_api_call

    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ParameterNotFound: An error occurred (ParameterNotFound) when calling the GetParameter operation:
```
</details>

On the other, I put some logs in the botocore library in order to see the region used in the API call and it takes 'us-east-1' (I think this is the default region for Serverless, doesn't it?) Of course there is no parameter in any US region because my parameters are in eu-west-1, so the boto3 API call fails. Here is the output (is the last part of the previous output):

```
{'client_region': 'us-east-1', 'client_config': <botocore.config.Config object at 0x7f885d1677f0>, 'has_streaming_input': False, 'auth_type': None}

Traceback (most recent call last):
  File "/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/invoke.py", line 86, in <module>

    result = handler(input['event'], context)
  File "./src/Inventory/Inventory.py", line 29, in lambda_handler
    WithDecryption=True
  File "/home/frcmoya/.local/lib/python3.6/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/frcmoya/.local/lib/python3.6/site-packages/botocore/client.py", line 627, in _make_api_call

    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ParameterNotFound: An error occurred (ParameterNotFound) when calling the GetParameter operation: 
```

**Comment by medikoo** [comment]
@FrcMoya there's an error in your `serverless.yml`, region is a `provider` property (not top level). See https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/

**Comment by FrcMoya** [comment]
Ouch! That was the problem, I forgot the tabs... Thank you so much!!
