### ISSUE TITLE
v0.5 customRole not templatizable

### ISSUE THREAD

**Issue by erikerikson** [serverless/serverless#794]
Starting condition:
s-templates
```
{
    ...
    "customRoleTemplate": "[VALID_ROLE_ARN]"
    ...
}
```
s-function
```
{
    ...
    "customRole": "$${customRoleTemplate}"
    ...
}
```
Execute: `sls function deploy`

Expected: deployment using the custom role

Observed:
```
Serverless: ------------------------  
Serverless: Failed to deploy the following functions in "[STAGE]" to the following regions:  
Serverless: us-west-2 ------------------------  
Serverless:   [FUNCTION]: 1 validation error detected: Value '$${customRoleTemplate}' at 'role' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:aws:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+  
  serverless:lib.actions.FunctionDeploy ValidationException: 1 validation error detected: Value '$${customRoleTemplate}' at 'role' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:aws:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+
    at Object.extractError (/src/serverless/node_modules/aws-sdk/lib/protocol/json.js:43:27)
    at Request.extractError (/src/serverless/node_modules/aws-sdk/lib/protocol/rest_json.js:37:8)
    at Request.callListeners (/src/serverless/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/src/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/src/serverless/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/src/serverless/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/src/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /src/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/src/serverless/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/src/serverless/node_modules/aws-sdk/lib/request.js:598:12)
    at Request.callListeners (/src/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/src/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/src/serverless/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/src/serverless/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/src/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /src/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
From previous event:
    at /src/serverless/lib/ProviderAws.js:73:14
    at doCall (/src/serverless/lib/utils/index.js:271:9)
    at /src/serverless/lib/utils/index.js:282:14
From previous event:
    at Object.module.exports.persistentRequest (/src/serverless/lib/utils/index.js:269:12)
    at ServerlessProviderAws.request (/src/serverless/lib/ProviderAws.js:72:19)
    at /src/serverless/lib/actions/CodeDeployLambda.js:196:30
From previous event:
    at Deployer._provision (/src/serverless/lib/actions/CodeDeployLambda.js:170:10)
From previous event:
    at Deployer.deploy (/src/serverless/lib/actions/CodeDeployLambda.js:72:10)
    at CodeDeployLambda.codeDeployLambda (/src/serverless/lib/actions/CodeDeployLambda.js:48:23)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at /src/serverless/lib/Serverless.js:221:25
    at Array.reduce (native)
    at Serverless._execute (/src/serverless/lib/Serverless.js:220:26)
    at Object.actions.(anonymous function) [as codeDeployLambda] (/src/serverless/lib/Serverless.js:415:20)
    at FunctionDeploy.<anonymous> (/src/serverless/lib/actions/FunctionDeploy.js:298:42)
From previous event:
    at /src/serverless/lib/actions/FunctionDeploy.js:287:18
From previous event:
    at /src/serverless/lib/actions/FunctionDeploy.js:274:31
    at /src/serverless/node_modules/async/lib/async.js:181:20
    at replenish (/src/serverless/node_modules/async/lib/async.js:319:21)
    at /src/serverless/node_modules/async/lib/async.js:330:15
    at Object.async.forEachLimit.async.eachLimit (/src/serverless/node_modules/async/lib/async.js:220:35)
    at /src/serverless/lib/actions/FunctionDeploy.js:272:15
From previous event:
    at FunctionDeploy._deployCodeByRegion (/src/serverless/lib/actions/FunctionDeploy.js:265:14)
    at FunctionDeploy.<anonymous> (/src/serverless/lib/actions/FunctionDeploy.js:248:24)
From previous event:
    at FunctionDeploy._processDeployment (/src/serverless/lib/actions/FunctionDeploy.js:245:10)
From previous event:
    at FunctionDeploy.functionDeploy (/src/serverless/lib/actions/FunctionDeploy.js:114:10)
From previous event:
    at /src/serverless/lib/Serverless.js:196:29
    at Array.reduce (native)
    at /src/serverless/lib/Serverless.js:195:30
From previous event:
    at Serverless._execute (/src/serverless/lib/Serverless.js:193:10)
    at Serverless.actions.(anonymous function) (/src/serverless/lib/Serverless.js:415:20)
    at Serverless.command (/src/serverless/lib/Serverless.js:384:38)
    at /src/serverless/bin/serverless:19:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Object.<anonymous> (/src/serverless/bin/serverless:18:4)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3 +80ms
```

**Comment by erikerikson** [comment]
In my opinion, this one is not even close to optional for v0.5.
Workaround consists of hard coding the customRole value for every s-function

**Comment by erikerikson** [comment]
This issue is resolved by PR https://github.com/serverless/serverless/pull/795

**Comment by erikerikson** [comment]
This issue is resolved more thoroughly by PR https://github.com/serverless/serverless/pull/784

**Comment by ac360** [comment]
Merged.  Thanks @erikerikson!
