### ISSUE TITLE
Version 1.76.0 crashes right away

### ISSUE THREAD

**Issue by boyvanduuren** [serverless/serverless#7974]
Any serverless command results in a crash right away:

```
$ sls deploy
internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module '../scripts/serverless'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/bvanduuren/.nvm/versions/node/v11.15.0/lib/node_modules/serverless/bin/serverless.js:41:1)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)

$ sls package
<same stack trace>

$ sls version
<same stack trace>

$ sls help
<same stack trace>
```

<details>
<summary><code>serverless.yml</code></summary>

I won't provide a serverless.yaml, as even running `sls version` fails.

</details>

<details>
<summary><b><code>sls version</code> output</b></summary>

```
internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module '../scripts/serverless'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/bvanduuren/.nvm/versions/node/v11.15.0/lib/node_modules/serverless/bin/serverless.js:41:1)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
```

</details>

<b>Installed version</b>

```
i think you can guess this one ;-) but it is 1.76.0
```

**Comment by davesheldon** [comment]
Came here to post the same issue.

**Comment by medikoo** [comment]
Great thanks for reporting! Fixed with https://github.com/serverless/serverless/commit/a687e9190d861f11ec1fc9a194335b3012b246b9 New release is being published

**Comment by medikoo** [comment]
Related to: https://github.com/serverless/serverless/issues/7975

**Comment by medikoo** [comment]
v1.76.1 is published
