### ISSUE TITLE
using serverless.ts throws "Error: Could not find any serverless service definition file."

### ISSUE THREAD

**Issue by mtin79** [serverless/serverless#7989]
1. Created a new serverless app with the template "aws-nodejs-typescript".
2. Customized serverless.ts according to app, org, stage, region, etc.
3. When i try to deploy the app it throws the error:

```
Error: Could not find any serverless service definition file.
    at /Users/mtin79/.nvm/versions/node/v12.18.3/lib/node_modules/serverless/node_modules/@serverless/lib/deployment/getServerlessFilePath.js:45:9
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/mtin79/.nvm/versions/node/v12.18.3/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/deployment/getServerlessFilePath.js:15:103)
    at _next (/Users/mtin79/.nvm/versions/node/v12.18.3/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/deployment/getServerlessFilePath.js:17:194)
 
  Error --------------------------------------------------
```

**Comment by medikoo** [comment]
@mtin79 thanks for reporting. TS type for  service config is not yet supported by dashboard (it'll work unless you have `app` and `org` configured)
