### ISSUE TITLE
Large number of variables throws errors when generating resources/s-resources-cf-stage-region.json

### ISSUE THREAD

**Issue by edclement** [serverless/serverless#801]
Each of my stage/regions has a large number of variables all related to a number of dynamo tables/indexes that need to the max read/write capacity set (it differs from stage/region to help control costs). As an example, our `s-variables-dev1-useast1.json` variables file might look like:
```
{
    "AppendToTableName": "-dev",

    "variable01" : 101,
    "variable02" : 102,
    "variable03" : 103,
    "variable04" : 104,
    "variable05" : 105,
    "variable06" : 106,
    "variable07" : 107,
    "variable08" : 108,
    "variable09" : 109,
    "variable10" : 110,
    "variable11" : 111,
    "variable12" : 112,
    "variable13" : 113,
    "variable14" : 114,
    "variable15" : 115,
    "variable16" : 116,
    "variable17" : 117,
    "variable18" : 118,
    "variable19" : 119,
    "variable20" : 120,
    "variable21" : 121,
    "variable22" : 122,
    "variable23" : 123,
    "variable24" : 124,
    "variable25" : 125,
    "variable26" : 126,
    "variable27" : 127,
    "variable28" : 128,
    "variable29" : 129,
    "variable30" : 130
}
```

We've noticed two issues arise in when a large number of variables are used:
* Having a large number of variables that are numbers causes the generation of the `s-resources-cf-stage-region.json` file to fail. This is the stack trace we get:
```
C:\nodejs4\node_modules\serverless\node_modules\bluebird\js\release\async.js:49                               
        fn = function () { throw arg; };                                                                      
                           ^                                                                                  
                                                                                                              
TypeError: b.replace is not a function                                                                        
    at replaceall (C:\nodejs4\node_modules\serverless\node_modules\replaceall\replaceall.min.js:5:43)         
    at C:\nodejs4\node_modules\serverless\lib\utils\index.js:607:17                                           
    at Array.forEach (native)                                                                                 
    at Object.<anonymous> (C:\nodejs4\node_modules\serverless\lib\utils\index.js:587:34)                      
    at walker (C:\nodejs4\node_modules\serverless\node_modules\traverse\index.js:190:22)                      
    at C:\nodejs4\node_modules\serverless\node_modules\traverse\index.js:208:29                               
    at Array.forEach (native)                                                                                 
    at forEach (C:\nodejs4\node_modules\serverless\node_modules\traverse\index.js:298:31)                     
    at walker (C:\nodejs4\node_modules\serverless\node_modules\traverse\index.js:203:13)                      
    at C:\nodejs4\node_modules\serverless\node_modules\traverse\index.js:208:29                               
    at Array.forEach (native)                                                                                 
    at forEach (C:\nodejs4\node_modules\serverless\node_modules\traverse\index.js:298:31)                     
    at walker (C:\nodejs4\node_modules\serverless\node_modules\traverse\index.js:203:13)                      
    at C:\nodejs4\node_modules\serverless\node_modules\traverse\index.js:208:29                               
    at Array.forEach (native)                                                                                 
    at forEach (C:\nodejs4\node_modules\serverless\node_modules\traverse\index.js:298:31)                     
    at walker (C:\nodejs4\node_modules\serverless\node_modules\traverse\index.js:203:13)                      
    at C:\nodejs4\node_modules\serverless\node_modules\traverse\index.js:208:29                               
    at Array.forEach (native)                                                                                 
    at forEach (C:\nodejs4\node_modules\serverless\node_modules\traverse\index.js:298:31)                     
    at walker (C:\nodejs4\node_modules\serverless\node_modules\traverse\index.js:203:13)                      
    at C:\nodejs4\node_modules\serverless\node_modules\traverse\index.js:208:29                               
From previous event:                                                                                          
    at ServerlessProject.getResources (C:\nodejs4\node_modules\serverless\lib\ServerlessProject.js:230:8)     
    at ServerlessState.getResources (C:\nodejs4\node_modules\serverless\lib\ServerlessState.js:151:25)        
    at ResourcesDeploy._deployResources (C:\nodejs4\node_modules\serverless\lib\actions\ResourcesDeploy.js:159
:28)                                                                                                          
From previous event:                                                                                          
    at ResourcesDeploy.resourcesDeploy (C:\nodejs4\node_modules\serverless\lib\actions\ResourcesDeploy.js:79:1
0)                                                                                                            
From previous event:                                                                                          
    at C:\nodejs4\node_modules\serverless\lib\Serverless.js:156:29                                            
    at Array.reduce (native)                                                                                  
    at C:\nodejs4\node_modules\serverless\lib\Serverless.js:155:30                                            
    at processImmediate [as _immediateCallback] (timers.js:383:17)                                            
From previous event:                                                                                          
    at Serverless._execute (C:\nodejs4\node_modules\serverless\lib\Serverless.js:153:10)                      
    at Serverless.actions.(anonymous function) (C:\nodejs4\node_modules\serverless\lib\Serverless.js:381:20)  
    at Serverless.command (C:\nodejs4\node_modules\serverless\lib\Serverless.js:350:38)                       
    at Object.<anonymous> (C:\nodejs4\node_modules\serverless\bin\serverless:16:12)                           
    at Module._compile (module.js:435:26)                                                                     
    at Object.Module._extensions..js (module.js:442:10)                                                       
    at Module.load (module.js:356:32)                                                                         
    at Function.Module._load (module.js:311:12)                                                               
    at Function.Module.runMain (module.js:467:10)                                                             
    at startup (node.js:136:18)                                                                               
    at node.js:963:3                                                                                          
```
**...If we wrap all of the numeric variables in double quotes (this making them strings) we don't see this issue**
* ~~With large numbers of variables, not every variable will actually get replaced in the generated `s-resources-cf-stage-region.json` file. Usually the last variable in the file is left as `${some_variable}`. No errors are thrown and no warnings for missing variables are produced in the console. I have a feeling it (like above) has something to do with how promises are being resolved (just a wild guess though).~~

**EDIT** - the above issue was my mistake, That last variable in my resources-cf was `{$var}` instead of `${var}`. The first issue I describe related to numeric variables is still a problem though.

**Comment by ac360** [comment]
@eahefnawy I believe the numeric issue may have been fixed in another PR.  Can't remember and don't see it referenced unfortunately..
