### ISSUE TITLE
Invoking function on aws-fsharp template results to JsonSerializerException

### ISSUE THREAD

**Issue by jukkhop** [serverless/serverless#8070]
Following the [Hello World tutorial](https://github.com/slang25/serverless/blob/master/docs/providers/aws/examples/hello-world/fsharp/README.md) on `aws-fsharp` and executing the `hello` function results to error:

`Error converting the Lambda event JSON payload to type AwsDotnetFsharp.Request: Deserialization of reference types without parameterless constructor is not supported. Type 'AwsDotnetFsharp.Request'`

I have been able to work around this by reverting the changes in #7914 and using 

```
[<assembly:LambdaSerializer(typeof<Amazon.Lambda.Serialization.Json.JsonSerializer>)>]
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: serverless-fsharp-test

provider:
  name: aws
  runtime: dotnetcore3.1
  stage: dev
  region: eu-west-1

package:
  artifact: bin/Release/netcoreapp3.1/deploy-package.zip

functions:
  hello:
    handler: FsharpHandlers::AwsDotnetFsharp.Handler::hello

```

</details>

<details>
<summary><b><code>serverless invoke --function hello --data "{}"</code> output</b></summary>

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
Serverless: Invoke invoke
Serverless: [AWS lambda 200 0.673s 0 retries] invoke({
  FunctionName: 'serverless-fsharp-test-dev-hello',
  InvocationType: 'RequestResponse',
  LogType: 'None',
  Payload: '***SensitiveInformation***'
})
{
    "errorType": "JsonSerializerException",
    "errorMessage": "Error converting the Lambda event JSON payload to type AwsDotnetFsharp.Request: Deserialization of reference types without parameterless constructor is not supported. Type 'AwsDotnetFsharp.Request'",
    "stackTrace": [
        "at Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer.Deserialize[T](Stream requestStream)",
        "at lambda_method(Closure , Stream , Stream , LambdaContextInternal )"
    ],
    "cause": {
        "errorType": "NotSupportedException",
        "errorMessage": "Deserialization of reference types without parameterless constructor is not supported. Type 'AwsDotnetFsharp.Request'",
        "stackTrace": [
            "at System.Text.Json.ThrowHelper.ThrowNotSupportedException_DeserializeCreateObjectDelegateIsNull(Type invalidType)",
            "at System.Text.Json.JsonSerializer.HandleStartObject(JsonSerializerOptions options, ReadStack& state)",
            "at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)",
            "at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)",
            "at System.Text.Json.JsonSerializer.ParseCore(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)",
            "at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonSerializerOptions options)",
            "at Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer.Deserialize[T](Stream requestStream)"
        ]
    }
}

  Error --------------------------------------------------

  Error: Invoked function failed
      at AwsInvoke.log (/Users/jukka/.nvm/versions/node/v12.16.2/lib/node_modules/serverless/lib/plugins/aws/invoke/index.js:105:31)
  From previous event:
      at Object.invoke:invoke [as hook] (/Users/jukka/.nvm/versions/node/v12.16.2/lib/node_modules/serverless/lib/plugins/aws/invoke/index.js:23:12)
      at /Users/jukka/.nvm/versions/node/v12.16.2/lib/node_modules/serverless/lib/classes/PluginManager.js:483:55
  From previous event:
      at PluginManager.invoke (/Users/jukka/.nvm/versions/node/v12.16.2/lib/node_modules/serverless/lib/classes/PluginManager.js:483:22)
      at /Users/jukka/.nvm/versions/node/v12.16.2/lib/node_modules/serverless/lib/classes/PluginManager.js:518:24
  From previous event:
      at PluginManager.run (/Users/jukka/.nvm/versions/node/v12.16.2/lib/node_modules/serverless/lib/classes/PluginManager.js:518:8)
      at /Users/jukka/.nvm/versions/node/v12.16.2/lib/node_modules/serverless/lib/Serverless.js:136:33
  From previous event:
      at Serverless.run (/Users/jukka/.nvm/versions/node/v12.16.2/lib/node_modules/serverless/lib/Serverless.js:123:74)
      at /Users/jukka/.nvm/versions/node/v12.16.2/lib/node_modules/serverless/scripts/serverless.js:54:26
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Object.<anonymous> (/Users/jukka/.nvm/versions/node/v12.16.2/lib/node_modules/serverless/scripts/serverless.js:54:4)
      at Module._compile (internal/modules/cjs/loader.js:1156:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
      at Module.load (internal/modules/cjs/loader.js:1000:32)
      at Function.Module._load (internal/modules/cjs/loader.js:899:14)
      at Module.require (internal/modules/cjs/loader.js:1042:19)
      at require (internal/modules/cjs/helpers.js:77:18)
      at Object.<anonymous> (/Users/jukka/.nvm/versions/node/v12.16.2/lib/node_modules/serverless/bin/serverless.js:41:1)
      at Module._compile (internal/modules/cjs/loader.js:1156:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
      at Module.load (internal/modules/cjs/loader.js:1000:32)
      at Function.Module._load (internal/modules/cjs/loader.js:899:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
      at internal/main/run_main_module.js:18:47

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.16.2
     Framework Version:         1.78.1
     Plugin Version:            3.7.0
     SDK Version:               2.3.1
     Components Version:        2.34.1

```

</details>

<b>Installed version</b>

```
Framework Core: 1.78.1
Plugin: 3.7.0
SDK: 2.3.1
Components: 2.34.1
```

**Comment by medikoo** [comment]
@mattsonlyattack do you know what could cause an error for @jukkhop ? It seems related to change you've proposed

**Comment by mattsonlyattack** [comment]
@medikoo it seems System.Text.Json has a bit different behavior than Newtonsoft? An alternative is to add [<CLIMutable>] to the Request record to fix the parameterless ctor error. This is a better fix than reverting to Newtonsoft. Thoughts?

**Comment by medikoo** [comment]
@mattsonlyattack I'm unfortunately not familiar with .NET, so best if you find out best solution with @jukkhop
