### ISSUE TITLE
Do not bundle 'aws-sdk' with custom resource lambda

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8094]
### Use case description

No need to bundle, as `aws-sdk` is provided in lambdas by AWS unconditionally

### Proposed solution

1. Remove `package.json` at https://github.com/serverless/serverless/tree/f091c07992a414f2534c9de80caf76faf2744367/lib/plugins/aws/customResources/resources
2. Remove npm installation step here: https://github.com/serverless/serverless/blob/f091c07992a414f2534c9de80caf76faf2744367/lib/plugins/aws/customResources/generateZip.js#L24-L27

**Comment by sedat** [comment]
Hello @medikoo , can I take this?

**Comment by medikoo** [comment]
@sedat definitely! Thank you

**Comment by sedat** [comment]
@medikoo when running integration tests I'm getting timeout errors on a few test cases like Event Bridge and Cognito pool. Are these normal? I used the keys of a new AWS account.

**Comment by medikoo** [comment]
> @medikoo when running integration tests I'm getting timeout errors on a few test cases like Event Bridge and Cognito pool. Are these normal? 

What exactly puts testing to stall? I believe you have a detailed logs flushed, when error happens, this should give an idea, where's the issue.

Still, that's not typical, we do not observe timeouts usually

**Comment by sedat** [comment]
For example;

``` 1) AWS - S3 Integration Test
       "before all" hook in "AWS - S3 Integration Test":
     Error: Timeout of 600000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/sedat-dev/contributions/serverless/tests/integration-all/s3/tests.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)



Error: Test ended with unfinished async jobs
`node node_modules/.bin/_mocha tests/integration-all/s3/tests.js` Exited with code 1

tests/integration-all/s3/tests.js failed```

**Comment by medikoo** [comment]
@sedat that's really wierd, can you run test as:

```
LOG_LEVEL=debug npx mocha tests/integration-all/s3/tests.js
```

And see, where exactly it gets stuck

**Comment by sedat** [comment]
Here is the error stack @medikoo 
```
AWS - S3 Integration Test
2020-08-19T16:32:53.213Z ● mocha AWS - S3 Integration Test   
Temporary path: /tmp/tmpdirs-serverless/31d5/182ff49f6deff26b
Creating S3 buckets...
2020-08-19T16:32:53.227Z ● aws [1] 'S3' createBucket [ { Bucket: 'integ-test-57749599-s3-existing-simple' } ]2020-08-19T16:32:53.259Z ● aws [2] 'S3' createBucket [ { Bucket: 'integ-test-57749599-s3-existing-complex' } ]
2020-08-19T16:32:54.458Z ● aws [1] { Location: '/integ-test-57749599-s3-existing-simple' }
2020-08-19T16:32:54.536Z ● aws [2] { Location: '/integ-test-57749599-s3-existing-complex' }
Deploying "integ-test-57749599-dev" service...
2020-08-19T16:32:54.537Z ● child-process-ext:spawn [1] run /home/sedat-dev/contributions/serverless/bin/serverless.js with [ 'deploy', [length]: 1 ]
2020-08-19T16:32:55.971Z ● child-process-ext:spawn:std:out [1] Serverless: Packaging service...\n
2020-08-19T16:32:55.971Z ● child-process-ext:spawn:std:out [1] Serverless: Excluding development dependencies...\n
2020-08-19T16:32:56.020Z ● child-process-ext:spawn:std:out [1] Serverless: Installing dependencies for custom CloudFormation resources...\n2020-08-19T16:32:57.097Z ● child-process-ext:spawn:std:out [1] Serverless: Creating Stack...\n
2020-08-19T16:32:58.111Z ● child-process-ext:spawn:std:out [1] Serverless: Checking Stack create progress...\n
2020-08-19T16:33:03.903Z ● child-process-ext:spawn:std:out [1] ...
2020-08-19T16:33:26.774Z ● child-process-ext:spawn:std:out [1] .
2020-08-19T16:33:33.530Z ● child-process-ext:spawn:std:out [1] ..
2020-08-19T16:33:33.531Z ● child-process-ext:spawn:std:out [1] ..\nServerless: Stack create finished...\n
2020-08-19T16:35:46.585Z ● child-process-ext:spawn:std:out [1] Serverless: Recoverable error occurred (connect ETIMEDOUT 100.25.113.183:443), sleeping for ~6 seconds. Try 1 of 4\n
2020-08-19T16:35:46.585Z ● child-process-ext:spawn:std:out [1] Serverless: Recoverable error occurred (connect ETIMEDOUT 100.25.113.183:443), sleeping for ~4 seconds. Try 1 of 4\n
```

**Comment by medikoo** [comment]
@sedat that looks wierd, can you run same with `SLS_DEBUG=*` ? Also ensure that you're up to date with master, that depenencies of `serverless` are up to date.

**Comment by sedat** [comment]
Did a clean install and it worked, strange. Any tips on how to test my changes? @medikoo

**Comment by medikoo** [comment]
> Did a clean install and it worked, strange. Any tips on how to test my changes?

if integration tests pass, it means it works :)

**Comment by sedat** [comment]
Even with a new clone without changes, these two test cases are failing @medikoo 
```
1) AwsInvokeLocal
       #invokeLocalRuby
         context.remainingTimeInMillis
           should become lower over time:
     SyntaxError: Unexpected token / in JSON at position 0
  SyntaxError: Unexpected token / in JSON at position 0
      at JSON.parse (<anonymous>)
      at /home/sedat-dev/contributions/serverless/lib/plugins/aws/invokeLocal/index.test.js:1039:41
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:15:14)      
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Context.<anonymous> (lib/plugins/aws/invokeLocal/index.test.js:1036:95)
      at processTicksAndRejections (internal/process/task_queues.js:79:11)

  2) AwsInvokeLocal
       #invokeLocalRuby
         calling a class method
           should execute:
     SyntaxError: Unexpected token / in JSON at position 0
  SyntaxError: Unexpected token / in JSON at position 0
      at JSON.parse (<anonymous>)
      at /home/sedat-dev/contributions/serverless/lib/plugins/aws/invokeLocal/index.test.js:1061:35
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:15:14)      
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Context.<anonymous> (lib/plugins/aws/invokeLocal/index.test.js:1058:12)
      at processTicksAndRejections (internal/process/task_queues.js:79:11)



 Notice: Some tests were skipped due to following environment issues:

 - AwsInvokeLocal: #invokeLocalPython: context.remainingTimeInMillis: should become lower over time (in: lib/plugins/aws/invokeLocal/index.test.js)

   Python runtime is not installed
```

**Comment by medikoo** [comment]
> Even with a new clone without changes, these two test cases are failing @medikoo

It's because you probably don't have Ruby in your environment. Tests should be configured to skip and warn if it's the case, but for some reasons those two do not follow that.

You may propose PR that neatly skips those tests in case of those errors (e.g. see how Python tests are skipped on your side), but you can also ignore it (as that's not in scope of this issue)

**Comment by sedat** [comment]
Hey, @medikoo just opened a PR for this issue.
