### ISSUE TITLE
v0.5 - Can't deploy functions

### ISSUE THREAD

**Issue by michaelorionmcmanus** [serverless/serverless#813]
In `lib/actions/CodeDeployLambda.js` in the method `_validateAndPrepare` the class instance doesn't have a `S` property, which causes calls to members of `S` to fail:

``` 
    /**
     * Validate And Prepare
     */

    _validateAndPrepare() {

      let _this = this;
      // TODO: Validate Options

      // Instantiate Classes
      _this.aws      = _this.S.getProvider(); // No _this.S makes method go boom
      _this.project  = _this.S.getProject();
      _this.function = _this.S.getProject().getFunction( _this.evt.options.name );
      _this.functionPopulated = _this.function.toObjectPopulated({ stage: _this.evt.options.stage, region: _this.evt.options.region });

      // Set default function name
      _this.functionName = _this.function.getDeployedName({
        stage: _this.evt.options.stage,
        region: _this.evt.options.region
      });

      return BbPromise.resolve();
    }
```

**Comment by michaelorionmcmanus** [comment]
@ac360 this is what I was referring to in chat re: the `Deployer` instance issue. I'll provide simple fix in a followup PR but not sure if the intent is to indeed have `S` on the instance?

**Comment by ianserlin** [comment]
I'm also getting a similar error related to running "sls function logs" within a function's directory, even on this PR branch:

```
TypeError: Cannot read property 'getDeployedName' of undefined
    at FunctionLogs._validateAndPrepare (/Users/ian/code/other/serverless-michaelorionmcmanus/lib/actions/FunctionLogs.js:126:39)
From previous event:
    at FunctionLogs.functionLogs (/Users/ian/code/other/serverless-michaelorionmcmanus/lib/actions/FunctionLogs.js:95:10)
From previous event:
    at /Users/ian/code/other/serverless-michaelorionmcmanus/lib/Serverless.js:181:31
    at Array.reduce (native)
    at /Users/ian/code/other/serverless-michaelorionmcmanus/lib/Serverless.js:180:32
From previous event:
    at Serverless._execute (/Users/ian/code/other/serverless-michaelorionmcmanus/lib/Serverless.js:178:12)
    at Serverless.actions.(anonymous function) (/Users/ian/code/other/serverless-michaelorionmcmanus/lib/Serverless.js:423:20)
    at Serverless.command (/Users/ian/code/other/serverless-michaelorionmcmanus/lib/Serverless.js:392:38)
    at /Users/ian/code/other/serverless-michaelorionmcmanus/bin/serverless:19:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Object.<anonymous> (/Users/ian/code/other/serverless-michaelorionmcmanus/bin/serverless:18:4)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```
