### ISSUE TITLE
APIGateway request schema naming for application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by jack1902** [serverless/serverless#8191]
When i run `serverless deploy --stage dev` i get the following output:

```
  Error: The CloudFormation template is invalid: Template format error: Resource name ApiGatewayMethodResetstagingPostApplicationX Www Form UrlencodedModel is non alphanumeric.
```

I am not sure how to get around this since i want the `validator` for the defined request schema. I had a look at the `serverless-aws-documentation` and `serverless-reqvalidator-plugin` but they seemed heavy weight when i have what i would have thought to have been a simple setup. If i change the content-type from `application/x-www-form-urlencoded` to `application/works` then it works, but that won't match the `content-type` coming in on the request and then defeats the purpose of the validator

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: bug-report
frameworkVersion: ">=1.0.0 <2.0.0"

provider:
  name: aws
  runtime: python3.8
  region: eu-west-1

functions:
  example:
    handler: function.handler
    events:
      - http:
          path: example
          method: post
          cors: true
          integration: lambda
          request:
            schema:
              # This bit blows up, how can i set the content-type to this without it blowing up?
              'application/x-www-form-urlencoded': ${file(serverless/url_encoded_schema.json)}
```

</details>

<details>
<summary><code>serverless/url_encoded_schema.json</code></summary>

```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Standard event wrapper for the Events API",
    "description": "Adapted from auto-generated content",
    "type": "object",
    "additionalProperties": true,
    "required": [
        "token",
        "team_id",
        "api_app_id",
        "event",
        "type",
        "event_id",
        "event_time",
        "authed_users"
    ],
    "properties": {
        "token": {
            "title": "A verification token to validate the event originated from Slack",
            "type": "string"
        },
        "team_id": {
            "title": "The unique identifier of the workspace where the event occurred",
            "type": "string"
        },
        "api_app_id": {
            "title": "The unique identifier your installed Slack application.",
            "description": " Use this to distinguish which app the event belongs to if you use multiple apps with the same Request URL.",
            "type": "string"
        },
        "event": {
            "title": "The actual event, an object, that happened. You'll find the most variance in properties beneath this node.",
            "type": "object",
            "additionalProperties": true,
            "required": [
                "type",
                "event_ts"
            ],
            "properties": {
                "type": {
                    "title": "The specific name of the event",
                    "type": "string"
                },
                "event_ts": {
                    "title": "When the event was dispatched",
                    "type": "string"
                }
            }
        },
        "type": {
            "title": "Indicates which kind of event dispatch this is, usually `event_callback`",
            "type": "string"
        },
        "event_id": {
            "title": "A unique identifier for this specific event, globally unique across all workspaces.",
            "type": "string"
        },
        "event_time": {
            "title": "The epoch timestamp in seconds indicating when this event was dispatched.",
            "type": "integer"
        },
        "authed_users": {
            "title": "An array of string-based User IDs. Each member of the collection represents a user that has installed your application/bot and indicates the described event would be visible to those users.",
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
                "type": "string"
            }
        }
    }
  }
```
</details>

<details>
<summary><b><code>yarn sls deploy --stage dev</code> output</b></summary>

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 200 0.172s 0 retries] describeStacks({ StackName: 'bug-report-jack' })
Serverless: [AWS cloudformation 200 0.124s 0 retries] describeStackResource({
  StackName: 'bug-report-jack',
  LogicalResourceId: 'ServerlessDeploymentBucket'
})
Serverless: [AWS s3 200 0.14s 0 retries] listObjectsV2({
  Bucket: 'bug-report-jack-serverlessdeploymentbucket-7uw8z7g9ydw8',
  Prefix: 'serverless/bug-report/jack'
})
Serverless: [AWS s3 200 0.125s 0 retries] headObject({
  Bucket: 'bug-report-jack-serverlessdeploymentbucket-7uw8z7g9ydw8',
  Key: 'serverless/bug-report/jack/1599476075329-2020-09-07T10:54:35.329Z/compiled-cloudformation-template.json'
})
Serverless: [AWS s3 200 0.129s 0 retries] headObject({
  Bucket: 'bug-report-jack-serverlessdeploymentbucket-7uw8z7g9ydw8',
  Key: 'serverless/bug-report/jack/1599476075329-2020-09-07T10:54:35.329Z/bug-report.zip'
})
Serverless: [AWS lambda 404 0.155s 0 retries] getFunction({ FunctionName: 'bug-report-jack-example' })
Serverless: [AWS sts 200 0.368s 0 retries] getCallerIdentity({})
Serverless: Uploading CloudFormation file to S3...
Serverless: [AWS s3 200 0.192s 0 retries] putObject({
  Body: <Buffer 7b 22 41 57 53 54 65 6d 70 6c 61 74 65 46 6f 72 6d 61 74 56 65 72 73 69 6f 6e 22 3a 22 32 30 31 30 2d 30 39 2d 30 39 22 2c 22 44 65 73 63 72 69 70 74 ... 13498 more bytes>,
  Bucket: 'bug-report-jack-serverlessdeploymentbucket-7uw8z7g9ydw8',
  Key: 'serverless/bug-report/jack/1599477561490-2020-09-07T11:19:21.490Z/compiled-cloudformation-template.json',
  ContentType: 'application/json',
  Metadata: { filesha256: 'hQFc1Ky6Cgzl/CGnzXZWWaTdeIjEsztd22X11ypXs38=' }
})
Serverless: Uploading artifacts...
Serverless: Uploading service bug-report.zip file to S3 (116.65 KB)...
Serverless: [AWS s3 200 0.273s 0 retries] putObject({
  Body: <Buffer 50 4b 03 04 14 00 08 00 08 00 00 00 21 00 00 00 00 00 00 00 00 00 00 00 00 00 0b 00 00 00 66 75 6e 63 74 69 6f 6e 2e 70 79 cb cc 2d c8 2f 2a 51 28 4a ... 119397 more bytes>,
  Bucket: 'bug-report-jack-serverlessdeploymentbucket-7uw8z7g9ydw8',
  Key: 'serverless/bug-report/jack/1599477561490-2020-09-07T11:19:21.490Z/bug-report.zip',
  ContentType: 'application/zip',
  Metadata: { filesha256: 'ao6KjOg2EWiJ1zyiKoovI/hNIbgubcT+bcUnmoMHdX0=' }
})
Serverless: Validating template...
Serverless: [AWS cloudformation 400 0.728s 0 retries] validateTemplate({
  TemplateURL: 'https://s3.amazonaws.com/bug-report-jack-serverlessdeploymentbucket-7uw8z7g9ydw8/serverless/bug-report/jack/1599477561490-2020-09-07T11:19:21.490Z/compiled-cloudformation-template.json'
})

  Error --------------------------------------------------

  Error: The CloudFormation template is invalid: Template format error: Resource name ApiGatewayMethodExamplePostApplicationX Www Form UrlencodedModel is non alphanumeric.
      at /Users/USER/work/git/temp/serverless-aws-documentation/new/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:20:13
  From previous event:
      at AwsDeploy.validateTemplate (/Users/USER/work/git/temp/serverless-aws-documentation/new/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:16:85)
  From previous event:
      at AwsDeploy.<anonymous> (/Users/USER/work/git/temp/serverless-aws-documentation/new/node_modules/serverless/lib/plugins/aws/deploy/index.js:119:39)
  From previous event:
      at Object.aws:deploy:deploy:validateTemplate [as hook] (/Users/USER/work/git/temp/serverless-aws-documentation/new/node_modules/serverless/lib/plugins/aws/deploy/index.js:115:30)
      at /Users/USER/work/git/temp/serverless-aws-documentation/new/node_modules/serverless/lib/classes/PluginManager.js:498:55
  From previous event:
      at PluginManager.invoke (/Users/USER/work/git/temp/serverless-aws-documentation/new/node_modules/serverless/lib/classes/PluginManager.js:498:22)
      at PluginManager.spawn (/Users/USER/work/git/temp/serverless-aws-documentation/new/node_modules/serverless/lib/classes/PluginManager.js:518:17)
      at AwsDeploy.<anonymous> (/Users/USER/work/git/temp/serverless-aws-documentation/new/node_modules/serverless/lib/plugins/aws/deploy/index.js:93:48)
  From previous event:
      at Object.deploy:deploy [as hook] (/Users/USER/work/git/temp/serverless-aws-documentation/new/node_modules/serverless/lib/plugins/aws/deploy/index.js:89:30)
      at /Users/USER/work/git/temp/serverless-aws-documentation/new/node_modules/serverless/lib/classes/PluginManager.js:498:55
  From previous event:
      at PluginManager.invoke (/Users/USER/work/git/temp/serverless-aws-documentation/new/node_modules/serverless/lib/classes/PluginManager.js:498:22)
      at /Users/USER/work/git/temp/serverless-aws-documentation/new/node_modules/serverless/lib/classes/PluginManager.js:533:24
  From previous event:
      at PluginManager.run (/Users/USER/work/git/temp/serverless-aws-documentation/new/node_modules/serverless/lib/classes/PluginManager.js:533:8)
      at /Users/USER/work/git/temp/serverless-aws-documentation/new/node_modules/serverless/lib/Serverless.js:162:33
  From previous event:
      at Serverless.run (/Users/USER/work/git/temp/serverless-aws-documentation/new/node_modules/serverless/lib/Serverless.js:149:74)
      at /Users/USER/work/git/temp/serverless-aws-documentation/new/node_modules/serverless/scripts/serverless.js:58:26
      at processImmediate (internal/timers.js:461:21)
  From previous event:
      at Object.<anonymous> (/Users/USER/work/git/temp/serverless-aws-documentation/new/node_modules/serverless/scripts/serverless.js:58:4)
      at Module._compile (internal/modules/cjs/loader.js:1075:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
      at Module.load (internal/modules/cjs/loader.js:940:32)
      at Function.Module._load (internal/modules/cjs/loader.js:781:14)
      at Module.require (internal/modules/cjs/loader.js:964:19)
      at require (internal/modules/cjs/helpers.js:88:18)
      at Object.<anonymous> (/Users/USER/work/git/temp/serverless-aws-documentation/new/node_modules/serverless/bin/serverless.js:41:1)
      at Module._compile (internal/modules/cjs/loader.js:1075:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
      at Module.load (internal/modules/cjs/loader.js:940:32)
      at Function.Module._load (internal/modules/cjs/loader.js:781:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
      at internal/main/run_main_module.js:17:47

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.9.0
     Framework Version:         1.82.0 (local)
     Plugin Version:            3.8.3
     SDK Version:               2.3.1
     Components Version:        2.34.9
```

</details>

<b>Installed version</b>

```
Framework Core: 1.82.0 (local)
Plugin: 3.8.3
SDK: 2.3.1
Components: 2.34.9
```

**Comment by medikoo** [comment]
@jack1902 can you please check if you have same error when not relying on any plugins? Note that plugin related errors should be reported at plugin repositories not here

**Comment by jack1902** [comment]
@medikoo you want me to just run `bare-metal` serverless? since the plugins i have are not related to the issue. I mentioned i "could" use those other plugins but when i run serverless without them as per the `serverless.yml` above, i get the `alpha-numeric` constraint from CloudFormation.

Since i want to set a `schema` on the `request` for a content-type of `application/x-www-form-urlencoded` i couldn't, as serverless uses this to create a `validator`. If i used `application/json` it seems fine. I think it comes down to the `content-type` being used to create a validator within the stack by serverless itself, NOT a plugin. If it was an object which i could pass in names then it wouldn't be an issue.

Happy to run without the plugins, as i have done that and i still had the same error. 

Also see https://www.serverless.com/framework/docs/providers/aws/events/apigateway/#lambda-proxy-integration `#
Request Schema Validators` the example given is of `application/json` but using `application/x-www-form-urlencoded` throws up errors

**Comment by medikoo** [comment]
> @medikoo you want me to just run bare-metal serverless? 

We need a test case that reproduces the problem, and doesn't involve any plugins (ideally configuration should be minimal just to reproduce the issue).

> Happy to run without the plugins, as i have done that and i still had the same error.

Can you update content of `serverless.yml` in main description, so it reflects used config.

**Comment by jack1902** [comment]
@medikoo ok the `serverless.yml` is now down to the bare minimum required, i can supply the contents of the `serverless` directory if required but the error doesn't complain about an invalid template

**Comment by medikoo** [comment]
@jack1902 I miss content of ${file(serverless/url_encoded_schema.json)}` ? Can you put this inline, or provide a content of this file?

Same with `${file(serverless/200_template.vm)}`

If you feel that some parts of a config are irrelevant and do not influence the test case, can you also clear them up?

**Comment by jack1902** [comment]
@medikoo i've dropped the `serverless.yml` to the bare minimum and i have added the contents of the request file (its for slack, from their json event page)

**Comment by medikoo** [comment]
@jack1902 great thanks for cleaning up the test case. Indeed there's bug, for some reason it was not noticed so far, but function that generates the model name doesn't handle `-` as expected:

https://github.com/serverless/serverless/blob/5096534a80e211b947e59d7283cfdfdd1711e7ea/lib/plugins/aws/lib/naming.js#L287-L291

`_.startCase` replaces `-` with whitespace.

PR with a fix is welcome!

**Comment by colemujadzic** [comment]
I wanted to see if y'all might be alright with me taking this on, but I'm totally fine if you want to see the resolution through @jack1902! 🙂

**Comment by medikoo** [comment]
@colemujadzic I think you can go for it. Fix would be very welcome :)

**Comment by jack1902** [comment]
@colemujadzic go for it, seems like an easy fix but I'm not familiar with the codebase of serverless so not 100% sure if there are any hidden traps

**Comment by colemujadzic** [comment]
@medikoo @jack1902 Thanks! I'll take a look and follow up if I have any questions

**Comment by jack1902** [comment]
@colemujadzic @medikoo thanks for the fast turnaround!

Managed to deploy the schema!

**Comment by colemujadzic** [comment]
@jack1902 glad to hear that!
