### ISSUE TITLE
TypeError: Cannot read property 'fetch' of undefined with serverless@2.1.0

### ISSUE THREAD

**Issue by puzanov** [serverless/serverless#8260]
After updating to serverless@2.1.0 sls deploy failind with error publishing to the Dashboard, but AWS deploy goes OK. 

Here are the last lines of the sls deploy output with SLS_DEBUG=*

```
Serverless: Publishing service to the Serverless Dashboard...
Serverless: [AWS sts 200 0.732s 0 retries] getCallerIdentity({})
Serverless: [AWS cloudformation 200 0.779s 0 retries] describeStacks({ StackName: 'serverless-webhooks-dev' })
Serverless: Publishing service to the Serverless Dashboard...
Serverless: [AWS sts 200 0.75s 0 retries] getCallerIdentity({})
Serverless: [AWS cloudformation 200 1.336s 0 retries] describeStacks({ StackName: 'serverless-webhooks-dev' })
TypeError: Cannot read property 'fetch' of undefined
    at parseDeploymentData (/home/puzanov/.nvm/versions/node/v12.16.3/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/deployment/parse.js:159:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at /home/puzanov/.nvm/versions/node/v12.16.3/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/errorHandler.js:20:24
 
  Type Error ---------------------------------------------
 
  TypeError: Cannot read property 'fetch' of undefined
      at parseDeploymentData (/home/puzanov/.nvm/versions/node/v12.16.3/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/deployment/parse.js:159:65)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at module.exports (/home/puzanov/.nvm/versions/node/v12.16.3/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/deployment/save.js:14:22)
      at ServerlessEnterprisePlugin.<anonymous> (/home/puzanov/.nvm/versions/node/v12.16.3/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/plugin.js:446:13)
  From previous event:
      at PluginManager.invoke (/home/puzanov/.nvm/versions/node/v12.16.3/lib/node_modules/serverless/lib/classes/PluginManager.js:498:22)
      at /home/puzanov/.nvm/versions/node/v12.16.3/lib/node_modules/serverless/lib/classes/PluginManager.js:533:24
  From previous event:
      at PluginManager.run (/home/puzanov/.nvm/versions/node/v12.16.3/lib/node_modules/serverless/lib/classes/PluginManager.js:533:8)
      at /home/puzanov/.nvm/versions/node/v12.16.3/lib/node_modules/serverless/lib/Serverless.js:168:33
  From previous event:
      at Serverless.run (/home/puzanov/.nvm/versions/node/v12.16.3/lib/node_modules/serverless/lib/Serverless.js:155:74)
      at /home/puzanov/.nvm/versions/node/v12.16.3/lib/node_modules/serverless/scripts/serverless.js:50:26
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Object.<anonymous> (/home/puzanov/.nvm/versions/node/v12.16.3/lib/node_modules/serverless/scripts/serverless.js:50:4)
      at Module._compile (internal/modules/cjs/loader.js:1133:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
      at Module.load (internal/modules/cjs/loader.js:977:32)
      at Function.Module._load (internal/modules/cjs/loader.js:877:14)
      at Module.require (internal/modules/cjs/loader.js:1019:19)
      at require (internal/modules/cjs/helpers.js:77:18)
      at Object.<anonymous> (/home/puzanov/.nvm/versions/node/v12.16.3/lib/node_modules/serverless/bin/serverless.js:47:1)
      at Module._compile (internal/modules/cjs/loader.js:1133:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
      at Module.load (internal/modules/cjs/loader.js:977:32)
      at Function.Module._load (internal/modules/cjs/loader.js:877:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
      at internal/main/run_main_module.js:18:47
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.16.3
     Framework Version:         2.1.0
     Plugin Version:            4.0.3
     SDK Version:               2.3.2
     Components Version:        3.1.3
```

Seems that the problem with parsing git output with simple-git package here @serverless/enterprise-plugin/lib/deployment/parse.js:159:65 `if (originRemote) vcs.originUrl = originRemote.refs.fetch;`

```
npm -g list simple-git
/home/puzanov/.nvm/versions/node/v12.16.3/lib
└─┬ serverless@2.1.0
  └─┬ @serverless/enterprise-plugin@4.0.3
    └── simple-git@2.20.1 
```

**Comment by puzanov** [comment]
Probably this is related https://github.com/steveukx/git-js/issues/512

**Comment by jimfang** [comment]
TypeError: Cannot read property 'Fn::ImportValue' of undefined
      at C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:188:22
      at Array.map (<anonymous>)
      at C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:187:53
      at tryCatcher (C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\util.js:16:23)
      at Function.Promise.attempt.Promise.try (C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\method.js:39:29)     
      at AwsInvokeLocal.loadEnvVars (C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:154:25)
      at AwsInvokeLocal.tryCatcher (C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:547:31)      
      at Promise._settlePromise (C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:456:21)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              12.18.3
     Framework Version:         1.81.0
     Plugin Version:            3.8.4
     SDK Version:               2.3.2
     Components Version:        2.34.9

**Comment by jimfang** [comment]
Downgraded to version 1.80.0, and it works fine.

command: " serverless invoke local --function ..."
