### ISSUE TITLE
v0.5 - Can not load custom plugin in plugins folder

### ISSUE THREAD

**Issue by neaghfoz** [serverless/serverless#828]
I'm try to create a new plugin using ```sls plugin create```, then plugin boilerplate generated in the **project_root/plugins/myPlugin**.

But when run ```sls``` command in the project root folder, it throw exception:

```
/Users/peyton/GithubProjects/serverless/node_modules/bluebird/js/release/async.js:48
        fn = function () { throw arg; };
                           ^

TypeError: PluginClass.getName is not a function
    at Serverless._loadPlugins (/Users/peyton/GithubProjects/serverless/lib/Serverless.js:298:40)
    at Serverless.loadProjectPlugins (/Users/peyton/GithubProjects/serverless/lib/Serverless.js:240:10)
    at /Users/peyton/GithubProjects/serverless/lib/Serverless.js:77:41
From previous event:
    at Serverless.init (/Users/peyton/GithubProjects/serverless/lib/Serverless.js:73:25)
    at Object.<anonymous> (/Users/peyton/GithubProjects/serverless/bin/serverless:17:12)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

**Comment by dherault** [comment]
Just install it as a npm package, then add `"your-plugin-name"` to the `plugins` array of your `s-projet.json` file.

You can follow the instructions for another package [here](https://github.com/dherault/serverless-offline).

**Comment by ac360** [comment]
@neaghfoz Could you try now please?  I just pushed a fix.

**Comment by neaghfoz** [comment]
@ac360 Still not work, same exception of ```TypeError: PluginClass.getName is not a function```

**Comment by ac360** [comment]
@neaghfoz Ok, just pushed more fixes.  Some clean-up of the plugin template is still needed.  But it should be working again.

**Comment by ac360** [comment]
Thanks @neaghfoz
