### ISSUE TITLE
AWS Pseudoparameters in IAM roles are not substituted

### ISSUE THREAD

**Issue by ayan-usgs** [serverless/serverless#8312]
My understanding is that since version 2.3.0, AWS pseudoparameters have been natively supported. While I've found that to be indeed the case for the most part, I've noticed that pseudoparameters are not correctly handled when part of a role ARN. Using the a pseudoparameter results in this error from CloudFormation:

`1 validation error detected: Value 'arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.amazonaws.com/AWSServiceRoleForECS' at 'role' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:(aws[a-zA-Z-]*)?:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+ (Service: AWSLambdaInternal; Status Code: 400`

This seems to result from the string not being placed in a `Fn::Sub` block.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: my-hello-world-lambda

provider:
  name: aws
  region: 'us-west-2'
  stage: 'DEV'
  runtime: python3.8
  memorySize: 128
  deploymentBucket:
    name: my-bucket-20200930

functions:
  theAnswer:
    handler: hello.handler
    role: arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.amazonaws.com/AWSServiceRoleForECS  # this could be any role, I picked an AWS managed one because of its ubiquity

package:
  exclude:
    - node_modules/**
    - package.json
    - package-lock.json

```

</details>

<details>
<summary><b><code> ./node_modules/serverless/bin/serverless.js deploy</code> output</b></summary>

```
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.4.0")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: [AWS s3 200 0.737s 0 retries] getBucketLocation({ Bucket: 'my-bucket-20200930' })
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 400 0.741s 0 retries] describeStacks({ StackName: 'my-hello-world-lambda-DEV' })
Serverless: [AWS s3 200 0.574s 0 retries] listObjectsV2({
  Bucket: 'my-bucket-20200930',
  Prefix: 'serverless/my-hello-world-lambda/DEV'
})
Serverless: [AWS s3 200 0.546s 0 retries] headObject({
  Bucket: 'my-bucket-20200930',
  Key: 'serverless/my-hello-world-lambda/DEV/1601497067728-2020-09-30T20:17:47.728Z/my-hello-world-lambda.zip'
})
Serverless: [AWS s3 200 0.543s 0 retries] headObject({
  Bucket: 'my-bucket-20200930',
  Key: 'serverless/my-hello-world-lambda/DEV/1601497067728-2020-09-30T20:17:47.728Z/compiled-cloudformation-template.json'
})
Serverless: [AWS lambda 404 0.68s 0 retries] getFunction({ FunctionName: 'my-hello-world-lambda-DEV-theAnswer' })
Serverless: [AWS sts 200 0.715s 0 retries] getCallerIdentity({})
Serverless: Uploading CloudFormation file to S3...
Serverless: [AWS s3 200 0.583s 0 retries] putObject({
  Body: <Buffer 7b 22 41 57 53 54 65 6d 70 6c 61 74 65 46 6f 72 6d 61 74 56 65 72 73 69 6f 6e 22 3a 22 32 30 31 30 2d 30 39 2d 30 39 22 2c 22 44 65 73 63 72 69 70 74 ... 1204 more bytes>,
  Bucket: 'my-bucket-20200930',
  Key: 'serverless/my-hello-world-lambda/DEV/1601497223561-2020-09-30T20:20:23.561Z/compiled-cloudformation-template.json',
  ContentType: 'application/json',
  Metadata: { filesha256: 'UV4Az4zBQQtYtkLp2V5g6kleMn28FM5vJLZQdG8O0m4=' }
})
Serverless: Uploading artifacts...
Serverless: Uploading service my-hello-world-lambda.zip file to S3 (3.91 KB)...
Serverless: [AWS s3 200 0.611s 0 retries] putObject({
  Body: <Buffer 50 4b 03 04 14 00 08 00 08 00 00 00 21 00 00 00 00 00 00 00 00 00 00 00 00 00 10 00 00 00 2e 69 64 65 61 2f 2e 67 69 74 69 67 6e 6f 72 65 5d 8c 41 0a ... 3957 more bytes>,
  Bucket: 'my-bucket-20200930',
  Key: 'serverless/my-hello-world-lambda/DEV/1601497223561-2020-09-30T20:20:23.561Z/my-hello-world-lambda.zip',
  ContentType: 'application/zip',
  Metadata: { filesha256: '11HEv2y2O5fUILj6qOL9fOsjl9rFNCTAwEnH2svnTN8=' }
})
Serverless: Validating template...
Serverless: [AWS cloudformation 200 0.933s 0 retries] validateTemplate({
  TemplateURL: 'https://s3.amazonaws.com/my-bucket-20200930/serverless/my-hello-world-lambda/DEV/1601497223561-2020-09-30T20:20:23.561Z/compiled-cloudformation-template.json'
})
Serverless: Creating Stack...
Serverless: [AWS cloudformation 200 1.265s 0 retries] createStack({
  StackName: 'my-hello-world-lambda-DEV',
  OnFailure: 'DELETE',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL: 'https://s3.amazonaws.com/my-bucket-20200930/serverless/my-hello-world-lambda/DEV/1601497223561-2020-09-30T20:20:23.561Z/compiled-cloudformation-template.json',
  Tags: [ { Key: 'STAGE', Value: 'DEV' }, [length]: 1 ]
})
Serverless: Checking Stack create progress...
Serverless: [AWS cloudformation 200 0.665s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-west-2:REDACTED:stack/my-hello-world-lambda-DEV/62caf420-035a-11eb-8d9f-060e5bac23b7'
})
....Serverless: [AWS cloudformation 200 0.63s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-west-2:REDACTED:stack/my-hello-world-lambda-DEV/62caf420-035a-11eb-8d9f-060e5bac23b7'
})
.Serverless: [AWS cloudformation 200 0.679s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-west-2:REDACTED:stack/my-hello-world-lambda-DEV/62caf420-035a-11eb-8d9f-060e5bac23b7'
})
Serverless: [AWS cloudformation 200 0.73s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-west-2:REDACTED:stack/my-hello-world-lambda-DEV/62caf420-035a-11eb-8d9f-060e5bac23b7'
})
Serverless: [AWS cloudformation 200 0.734s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-west-2:REDACTED:stack/my-hello-world-lambda-DEV/62caf420-035a-11eb-8d9f-060e5bac23b7'
})
Serverless: [AWS cloudformation 200 0.712s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-west-2:REDACTED:stack/my-hello-world-lambda-DEV/62caf420-035a-11eb-8d9f-060e5bac23b7'
})
Serverless: [AWS cloudformation 200 0.742s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-west-2:REDACTED:stack/my-hello-world-lambda-DEV/62caf420-035a-11eb-8d9f-060e5bac23b7'
})
....
Serverless: Stack create finished...
Serverless: Invoke aws:info
Serverless: [AWS cloudformation 400 0.56s 0 retries] describeStacks({ StackName: 'my-hello-world-lambda-DEV' })
 
  Serverless Error ---------------------------------------
 
  ServerlessError: Stack with id my-hello-world-lambda-DEV does not exist
      at /home/ayan/git/hello-world-lambda/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:844:27
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.18.4
     Framework Version:         2.4.0 (local)
     Plugin Version:            4.0.4
     SDK Version:               2.3.2
     Components Version:        3.2.1
 

```

</details>

<b>Installed version</b>

```
Framework Core: 2.4.0 (local)
Plugin: 4.0.4
SDK: 2.3.2
Components: 3.2.1

```

**Comment by medikoo** [comment]
> This seems to result from the string not being placed in a Fn::Sub block.

Framework doesn't do that. If you want to use AWS pseudo parameters, then values needs to be configured through `Fn::Sub` blocks

**Comment by ayan-usgs** [comment]
Okay.
