### ISSUE TITLE
Serverless deploy fails to update function with new layer when code size is close to limit

### ISSUE THREAD

**Issue by zoellner** [serverless/serverless#8313]
Can't add layer to function that is close to 256MB code limit.

I've been trying for a few hours to reduce the size of my code (excluding dev dependencies doesn't really work and pruning before packaging doesn't work either since the plugins need to be present during packaging, but that's a separate issue).

I eventually realized that I could manually update the lambda code from the generated zip file, then manually add the layer, (they're each only about 10 MB zipped, less than 50 MB unzipped). 

However, the `serverless deploy` function failed in all combinations.
I'm assuming that it is trying to add the layer first (which brings the total size over the limit) and would then replace the function code. 
What would need to be done in this case is to replace the function code first, then add the layer.

<details>
<summary><code>serverless.yml</code></summary>
Not able to provide serverless.yml since it involves custom layers and a before/after serverless.yml.
Certainly possible to create an example but the description above does explain the issue. 

```yaml
# ⚠️⚠️ REPLACE THIS COMMENT WITH FULL serverless.yml CONTENT
```

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
sls deploy

ServerlessError: An error occurred: JobQueueHandlerLambdaFunction - Function code combined with layers exceeds the maximum allowed size of 262144000 bytes. The actual size is 276238556 bytes. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: ae3a3604-cf01-431e-8561-4df1e9c03d16; Proxy: null).
```

</details>

<b>Installed version</b>

```
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.13.0
     Framework Version:         2.0.0
     Plugin Version:            4.0.2
     SDK Version:               2.3.2
     Components Version:        3.1.2
```

**Comment by zoellner** [comment]
Below is the (somewhat anonymized) output of the deploy command.

I think what would be needed to reproduce is to create a repo with a function that is say 240MB unpacked

Then add a layer to that function that is 100MB and at the same time reduce the function code to 100MB. 

It should in theory deploy since the combined size of the new function is only 200MB but it won't since adding the 100MB layer to the existing 240MB function doesn't work. 


```
> reponame@0.3.5 deploy:stream /codebuild/output/src621147758/src
> cd ./deployment/stream && SLS_DEBUG=* sls deploy --verbose --stage $(echo $STAGE) --profile cross-account

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command prune
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: [AWS ssm 200 0.076s 0 retries] getParameter({ Name: '/dev/param1', WithDecryption: false })
Serverless: [AWS ssm 200 0.129s 0 retries] getParameter({ Name: '/dev/param2', WithDecryption: false })
Serverless: [AWS ssm 200 0.055s 0 retries] getParameter({ Name: '/dev/param2', WithDecryption: false })
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: [AWS s3 200 0.044s 0 retries] getBucketLocation({ Bucket: 'abc-sls-12345' })
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 200 0.067s 0 retries] describeStacks({ StackName: 'stackname' })
Serverless: [AWS s3 200 0.092s 0 retries] listObjectsV2({
  Bucket: 'abc-sls-12345',
  Prefix: 'serverless/abc-repo/dev'
})
Serverless: [AWS s3 200 0.026s 0 retries] headObject({
  Bucket: 'abc-sls-12345',
  Key: 'serverless/abc-repo/dev/1601501213125-2020-09-30T21:26:53.125Z/compiled-cloudformation-template.json'
})
Serverless: [AWS lambda 200 0.052s 0 retries] getFunction({ FunctionName: 'stackname-StreamFunction' })
Serverless: [AWS s3 200 0.22s 0 retries] headObject({
  Bucket: 'abc-sls-12345',
  Key: 'serverless/abc-repo/dev/1601501213125-2020-09-30T21:26:53.125Z/abc-repo.zip'
})
Serverless: [AWS sts 200 0.023s 0 retries] getCallerIdentity({})
Serverless: Uploading CloudFormation file to S3...
Serverless: [AWS s3 200 0.038s 0 retries] putObject({
  Body: <Buffer 7b 22 41 57 53 54 65 6d 70 6c 61 74 65 46 6f 72 6d 61 74 56 65 72 73 69 6f 6e 22 3a 22 32 30 31 30 2d 30 39 2d 30 39 22 2c 22 44 65 73 63 72 69 70 74 ... 5696 more bytes>,
  Bucket: 'abc-sls-12345',
  Key: 'serverless/abc-repo/dev/1601503250714-2020-09-30T22:00:50.714Z/compiled-cloudformation-template.json',
  ContentType: 'application/json',
  Metadata: { filesha256: 'rW/IQIoVKlyOcoLYHQPK0juHmD0843NJGpjv4gmDNr0=' },
  ServerSideEncryption: 'AES256'
})
Serverless: Uploading artifacts...
Serverless: Uploading service abc-repo.zip file to S3 (2.09 MB)...
Serverless: [AWS s3 200 0.09s 0 retries] putObject({
  Body: <Buffer 50 4b 03 04 14 00 08 00 08 00 00 00 21 00 00 00 00 00 00 00 00 00 00 00 00 00 1d 00 00 00 64 65 70 6c 6f 79 6d 65 6e 74 2f 64 79 6e 61 6d 6f 64 62 2d ... 2190828 more bytes>,
  Bucket: 'abc-sls-12345',
  Key: 'serverless/abc-repo/dev/1601503250714-2020-09-30T22:00:50.714Z/abc-repo.zip',
  ContentType: 'application/zip',
  Metadata: { filesha256: 'TJ84vN73bT96/E6korneqLsfVw7UvuxX1rslxdmd3uY=' },
  ServerSideEncryption: 'AES256'
})
Serverless: Validating template...
Serverless: [AWS cloudformation 200 0.177s 0 retries] validateTemplate({
  TemplateURL: 'https://s3.amazonaws.com/abc-sls-12345/serverless/abc-repo/dev/1601503250714-2020-09-30T22:00:50.714Z/compiled-cloudformation-template.json'
})
Serverless: Updating Stack...
Serverless: [AWS cloudformation 200 0.407s 0 retries] updateStack({
  StackName: 'stackname',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL: 'https://s3.amazonaws.com/abc-sls-12345/serverless/abc-repo/dev/1601503250714-2020-09-30T22:00:50.714Z/compiled-cloudformation-template.json',
  Tags: [ { Key: 'STAGE', Value: 'dev' }, [length]: 1 ]
})
Serverless: Checking Stack update progress...
Serverless: [AWS cloudformation 200 0.1s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:12345:stack/stackname/dc626f10-247a-11ea-bd1c-0a39c55408a8'
})
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - stackname
Serverless: [AWS cloudformation 200 0.2s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:12345:stack/stackname/dc626f10-247a-11ea-bd1c-0a39c55408a8'
})
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - StreamFunctionLambdaFunction
CloudFormation - UPDATE_FAILED - AWS::Lambda::Function - StreamFunctionLambdaFunction
CloudFormation - UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - stackname
Serverless: [AWS cloudformation 200 0.079s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:12345:stack/stackname/dc626f10-247a-11ea-bd1c-0a39c55408a8'
})
Serverless: [AWS cloudformation 200 0.091s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:12345:stack/stackname/dc626f10-247a-11ea-bd1c-0a39c55408a8'
})
Serverless: [AWS cloudformation 200 0.108s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:12345:stack/stackname/dc626f10-247a-11ea-bd1c-0a39c55408a8'
})
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - StreamFunctionLambdaFunction
Serverless: [AWS cloudformation 200 0.077s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:12345:stack/stackname/dc626f10-247a-11ea-bd1c-0a39c55408a8'
})
CloudFormation - UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - stackname
CloudFormation - UPDATE_ROLLBACK_COMPLETE - AWS::CloudFormation::Stack - stackname
Serverless: Operation failed!
Serverless: View the full error output: https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3A12345%3Astack%2Fstackname%2Fdc626f30-247a-11ea-bd1c-0a39c55408a8
 
  Serverless Error ---------------------------------------
 
  ServerlessError: An error occurred: StreamFunctionLambdaFunction - Function code combined with layers exceeds the maximum allowed size of 262144000 bytes. The actual size is 276238556 bytes. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 201b4aa1-710f-4291-a27a-a02e82873ea5; Proxy: null).
      at /usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:94:23
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at /usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:27:12
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.16.1
     Framework Version:         2.0.0
     Plugin Version:            4.0.4
     SDK Version:               2.3.2
     Components Version:        3.2.1
 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reponame@0.3.5 deploy:stream: `cd ./deployment/stream && SLS_DEBUG=* sls deploy --verbose --stage $(echo $STAGE) --profile cross-account`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the reponame@0.3.5 deploy:stream script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-30T22_01_22_690Z-debug.log
npm run deploy:stream exited with code 1
```

**Comment by medikoo** [comment]
@zoellner  thanks for log. I see now it's a CloudFormation update error, and I think we can't do much about that.

Note that we issue one CloudFormation template _update_ operation, and it's decided on AWS side in which order template updates are processed.

I believe you need to contact AWS support about your case

**Comment by zoellner** [comment]
Thank you
