### ISSUE TITLE
No recognition of absolute artifact paths - e.g. breaks single function deployment

### ISSUE THREAD

**Issue by rib** [serverless/serverless#8325]
The [documentation for package artifacts](https://www.serverless.com/framework/docs/providers/aws/guide/packaging/) doesn't explicitly state that absolute paths for artifacts are disallowed but they may break the ability to relocate a service and currently this code in `lib/plugins/package/lib/packageService.js` assumes a relative path:

```javascript
packageFunction(functionName) {
    const functionObject = this.serverless.service.getFunction(functionName);
    const funcPackageConfig = functionObject.package || {};

    // use the artifact in function config if provided
    if (funcPackageConfig.artifact) {
      const filePath = path.join(this.serverless.config.servicePath, funcPackageConfig.artifact);
      console.log("filePath: join(" + this.serverless.config.servicePath + "," + funcPackageConfig.artifact + ")" ); // DEBUG
      functionObject.package.artifact = filePath;
      return BbPromise.resolve(filePath);
    }
```

I recently found that I was unable to deploy individual lambda functions (i.e. using `deploy -f function`) due to the `serverless-rust` plugin setting an absolute artifact path.

Although `serverless-rust` needs to be fixed (see https://github.com/softprops/serverless-rust/issues/82) it would be good if the serverless framework documentation explicitly stated this constraint and it would be helpful for catching this easy mistake if the serverless framework also explicitly checked that these paths are relative and generated a clear error if an absolute path is ever set.

I originally thought I was hitting issue #6752 but since it looks like the more common cause for that issue comes from the `serverless-python-requirements` I'm filing this separate issue.

Here's a copy of the investigation I originally did under #6752 that lead me to finding the above cause in my case...

This is how it's failing for me

```bash
Serverless: Invoke package:function
Serverless: Packaging function: workoutdb...

  Error --------------------------------------------------

  Error: ENOENT: no such file or directory, open '/home/rib/src/realfit-rest-apis/home/rib/src/realfit-rest-apis/target/lambda/release/workoutdb.zip'
      at Object.openSync (fs.js:443:3)
      at Object.readFileSync (fs.js:343:35)
      at AwsDeployFunction.deployFunction (/home/rib/src/realfit-rest-apis/node_modules/serverless/lib/plugins/aws/deployFunction/index.js:229:21)
      at AwsDeployFunction.BbPromise.bind.then (/home/rib/src/realfit-rest-apis/node_modules/serverless/lib/plugins/aws/deployFunction/index.js:36:27)
  From previous event:
      at Object.deploy:function:deploy [as hook] (/home/rib/src/realfit-rest-apis/node_modules/serverless/lib/plugins/aws/deployFunction/index.js:34:12)
  From previous event:
      at PluginManager.invoke (/home/rib/src/realfit-rest-apis/node_modules/serverless/lib/classes/PluginManager.js:498:22)
      at PluginManager.spawn (/home/rib/src/realfit-rest-apis/node_modules/serverless/lib/classes/PluginManager.js:518:17)
      at BbPromise.try (/home/rib/src/realfit-rest-apis/node_modules/serverless/lib/plugins/deploy/deploy.js:112:50)
  From previous event:
      at Object.before:deploy:deploy [as hook] (/home/rib/src/realfit-rest-apis/node_modules/serverless/lib/plugins/deploy/deploy.js:102:22)
      at BbPromise.reduce (/home/rib/src/realfit-rest-apis/node_modules/serverless/lib/classes/PluginManager.js:498:55)
  From previous event:
      at PluginManager.invoke (/home/rib/src/realfit-rest-apis/node_modules/serverless/lib/classes/PluginManager.js:498:22)
      at getHooks.reduce.then (/home/rib/src/realfit-rest-apis/node_modules/serverless/lib/classes/PluginManager.js:533:24)
  From previous event:
      at PluginManager.run (/home/rib/src/realfit-rest-apis/node_modules/serverless/lib/classes/PluginManager.js:533:8)
      at variables.populateService.then (/home/rib/src/realfit-rest-apis/node_modules/serverless/lib/Serverless.js:162:33)
  From previous event:
      at Serverless.run (/home/rib/src/realfit-rest-apis/node_modules/serverless/lib/Serverless.js:149:74)
      at serverless.init.then.then (/home/rib/src/realfit-rest-apis/node_modules/serverless/scripts/serverless.js:58:26)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)
  From previous event:
      at Object.<anonymous> (/home/rib/src/realfit-rest-apis/node_modules/serverless/scripts/serverless.js:58:4)
      at Module._compile (internal/modules/cjs/loader.js:778:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
      at Module.load (internal/modules/cjs/loader.js:653:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
      at Function.Module._load (internal/modules/cjs/loader.js:585:3)
      at Module.require (internal/modules/cjs/loader.js:692:17)
      at require (internal/modules/cjs/helpers.js:25:18)
      at Object.<anonymous> (/home/rib/src/realfit-rest-apis/node_modules/serverless/bin/serverless.js:41:1)
      at Module._compile (internal/modules/cjs/loader.js:778:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
      at Module.load (internal/modules/cjs/loader.js:653:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
      at Function.Module._load (internal/modules/cjs/loader.js:585:3)
      at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
      at findNodeScript.then.existing (/home/rib/.node_modules/lib/node_modules/npx/node_modules/libnpx/index.js:268:14)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              10.21.0
     Framework Version:         1.83.0 (local)
     Plugin Version:            3.8.4
     SDK Version:               2.3.2
     Components Version:        2.34.9
```

my serverless plugins:
plugins:
  - serverless-rust
  - serverless-domain-manager

There is clearly something up with how the path for this file is built:

`/home/rib/src/realfit-rest-apis/home/rib/src/realfit-rest-apis/target/lambda/release/workoutdb.zip` since it contains a duplication of the `/home/rib/src/realfit-rest-apis` path

This is the relvant code in `plugins/aws/deployFunction/index.js` getting the path, right before the failure:
```javascript
deployFunction() {
    const artifactFileName = this.provider.naming.getFunctionArtifactName(this.options.function);
    let artifactFilePath =
      this.serverless.service.package.artifact || path.join(this.packagePath, artifactFileName);

    // check if an artifact is used in function package level
    const functionObject = this.serverless.service.getFunction(this.options.function);
    if (_.get(functionObject, 'package.artifact')) {
      artifactFilePath = functionObject.package.artifact;
      console.log("Test: " + artifactFilePath); // DEBUG
    }

    const data = fs.readFileSync(artifactFilePath);
```

And with the above debugging I see the path comes from this `_.get(functionObject, 'package.artifact')` case.

This sounds related to ovunccetin's workaround except I'm not using the `serverless-python-requirements` plugin as far as i know (can it be pulled in as a dependency somehow?)

Checking in `serverless-rust/index.js` I see:
```javascript
      // If all went well, we should now have find a packaged compiled binary under `target/lambda/release`.
      //
      // The AWS "provided" lambda runtime requires executables to be named
      // "bootstrap" -- https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html
      //
      // To avoid artifact naming conflicts when we potentially have more than one function
      // we leverage the ability to declare a package artifact directly
      // see https://serverless.com/framework/docs/providers/aws/guide/packaging/
      // for more information
      const artifactPath = path.join(
        this.srcPath,
        `target/lambda/${"dev" === profile ? "debug" : "release"}`,
        `${binary}.zip`
      );
      console.log("AP: " + artifactPath); // DEBUG
      func.package = func.package || {};
      func.package.artifact = artifactPath;
```

And can see that `serverless-rust` is setting an absolute path to the artifact which seems a bit risky, since I can easily imagine other parts of serverless might be expecting that to be a relative path and that's how I probably get the error above.

Blindly grepping I found this in `lib/plugins/package/lib/packageService.js`

```javascript
packageFunction(functionName) {
    const functionObject = this.serverless.service.getFunction(functionName);
    const funcPackageConfig = functionObject.package || {};

    // use the artifact in function config if provided
    if (funcPackageConfig.artifact) {
      const filePath = path.join(this.serverless.config.servicePath, funcPackageConfig.artifact);
      console.log("filePath: join(" + this.serverless.config.servicePath + "," + funcPackageConfig.artifact + ")" ); // DEBUG
      functionObject.package.artifact = filePath;
      return BbPromise.resolve(filePath);
    }
```
And see that filePath is made from joining `/home/rib/src/realfit-rest-apis` and `/home/rib/src/realfit-rest-apis/target/lambda/release/workoutdb.zip`, resulting in `/home/rib/src/realfit-rest-apis/home/rib/src/realfit-rest-apis/target/lambda/release/workoutdb.zip`

So although serverless-rust could potentially be changed to set a relative artifact path, I guess the fix in this case is that `packageFunction` should consider the possibility that the artifact path is already an absolute path and in that case it shouldn't concatenate with the servicePath.

Using this code instead:
```javascript
    // use the artifact in function config if provided
    if (funcPackageConfig.artifact) {
      const filePath = path.isAbsolute(funcPackageConfig.artifact) ?
            funcPackageConfig.artifact :
            path.join(this.serverless.config.servicePath, funcPackageConfig.artifact);
      console.log("filePath: join(" + this.serverless.config.servicePath + "," + funcPackageConfig.artifact + ")" );
      functionObject.package.artifact = filePath;
      return BbPromise.resolve(filePath);
    }
```

fixed the issue for me and let me deploy a single function again - yay!

<b>Installed version</b>

```
Framework Core: 1.83.0 (local)
Plugin: 3.8.4
SDK: 2.3.2
Components: 2.34.9
```

**Comment by rib** [comment]
Just to connect it with this issue - this was a PR I originally made to make serverless accept absolute artifact paths: https://github.com/serverless/serverless/pull/8315

I can see an argument for and against supporting absolute paths, but it sounds like the oppinion might be that serverless shouldn't support them and that PR can probably be closed.

**Comment by medikoo** [comment]
While it's hard to justify using an absolute paths, I think it's totally fine if Framework accepts them (it should either throw or respect them, while currently it concatenates it to some invalid path, and that's a clear bug).

Let me review the PR

**Comment by rib** [comment]
I think one of the reasons why absolute paths seem somewhat reasonable for artifacts is that they already support addressing global S3 bucket resources which sets a precedent for pointing at fixed-address resources outside of your service repo.

Your recommended PR change looked good to me, thanks, and I re-pushed the PR based on using `path.resolve`

**Comment by vaunus** [comment]
+1 as I have come across a need for this feature as well.

**Comment by medikoo** [comment]
@vaunus can you help finalizing https://github.com/serverless/serverless/pull/8315 ? There's not much really left
