### ISSUE TITLE
2.10.0 breaks externally acquired cloudwatch log events in lambda deployments

### ISSUE THREAD

**Issue by Jaystified** [serverless/serverless#8480]
I am unable to deploy lambdas triggered by cloudwatch logs since upgrading to 2.10.0 , when the list of events is determined in an external file.
(Placing the event in the yaml file directly works around the issue, but my use case requires getting a list of logs dynamically from aws)
The below example works on 2.9.0 .

<details>
<summary><code>serverless.yml</code></summary>

```yaml
---
service: eventstest
provider:
  name: aws
  runtime: nodejs12.x
functions:
  hello:
    handler: handler.hello
    events: "${file(external.js):events}"
```

</details>
<details>
<summary><code>external.js</code></summary>

```js
module.exports.events = async (serverless) => {
    const events = [
        { 
            "cloudwatchLog": {
              "logGroup": "/aws/lambda/some-other-function",
              "filter": "?\"SPECIALSTRING\""
            }
        }
    ];
    return events;
}
```

</details>

<details>
<summary><b><code>$ SLS_DEBUG=* node ../node_modules/serverless/bin/serverless.js package --stage development</code> output</b></summary>

```
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.10.0")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
 
  Type Error ---------------------------------------------
 
  TypeError: events.some is not a function
      at workdir/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/index.js:217:42
      at Array.some (<anonymous>)
      at new AwsCompileApigEvents (workdir/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/index.js:216:56)
      at PluginManager.addPlugin (workdir/node_modules/serverless/lib/classes/PluginManager.js:94:28)
      at workdir/node_modules/serverless/lib/classes/PluginManager.js:129:31
      at Array.forEach (<anonymous>)
      at PluginManager.loadAllPlugins (workdir/node_modules/serverless/lib/classes/PluginManager.js:129:8)
      at workdir/node_modules/serverless/lib/Serverless.js:90:39
      at processImmediate (internal/timers.js:461:21)
  From previous event:
      at workdir/node_modules/serverless/lib/Serverless.js:88:12
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.19.0
     Framework Version:         2.10.0 (local)
     Plugin Version:            4.1.1
     SDK Version:               2.3.2
     Components Version:        3.3.0
```

</details>

<b>Installed version</b>

```
Framework Core: 2.10.0 (local)
Plugin: 4.1.1
SDK: 2.3.2
Components: 3.3.0
```

**Comment by medikoo** [comment]
@Jaystified great thanks for reporting. Will be fixed with #8482
