### ISSUE TITLE
Python, AWS, Lambda - No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by TMorville** [serverless/serverless#8498]
I have followed this [official Serverless guide](https://www.serverless.com/blog/serverless-python-packaging) on how to deploy a serverless function on AWS Lambda. 

This results in a error that can be summarised as `No module named 'numpy.core._multiarray_umath'`. This error pertains to a OSx build of Numpy being run a Linux machine on AWS ([see this issue](https://github.com/numpy/numpy/issues/12977)). However, this should not happen as the `dockerizePip: non-linux` parameter is set.

There are two differences from the guide: 
1. I use `runtime: python3.8` which corresponds to the python version installed in the virtual environment. Numpy is `numpy==1.19.4`.  
2. I install the serverless-python-requirements using `sls plugin install -n serverless-python-requirements`. If I dont do this, serverless will complain that the plugin is missing. 

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: numpy-test

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8

functions:
  numpy:
    handler: handler.main
```

</details>

<details>
<summary><b><code>FULL COMMAND OUTPUT</code></b></summary>

```
serverless invoke -f numpy --log

Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.11.1")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command requirements
Serverless: Load command requirements:clean
Serverless: Load command requirements:install
Serverless: Load command requirements:cleanCache
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Invoke invoke
Serverless: [AWS lambda 200 1.047s 0 retries] invoke({
  FunctionName: 'numpy-test-dev-numpy',
  InvocationType: 'RequestResponse',
  LogType: 'Tail',
  Payload: '***SensitiveInformation***'
})
{
    "errorMessage": "Unable to import module 'handler': \n\nIMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!\n\nImporting the numpy C-extensions failed. This error can happen for\nmany reasons, often due to issues with your setup or how NumPy was\ninstalled.\n\nWe have compiled some common reasons and troubleshooting tips at:\n\n    https://numpy.org/devdocs/user/troubleshooting-importerror.html\n\nPlease note and check the following:\n\n  * The Python version is: Python3.8 from \"/var/lang/bin/python3.8\"\n  * The NumPy version is: \"1.19.4\"\n\nand make sure that they are the versions you expect.\nPlease carefully study the documentation linked above for further help.\n\nOriginal error was: No module named 'numpy.core._multiarray_umath'\n",
    "errorType": "Runtime.ImportModuleError"
}
--------------------------------------------------------------------
START RequestId: 02f1e697-5abd-423a-aa36-d780dbbeb87f Version: $LATEST
[ERROR] Runtime.ImportModuleError: Unable to import module 'handler':

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "/var/lang/bin/python3.8"
  * The NumPy version is: "1.19.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
END RequestId: 02f1e697-5abd-423a-aa36-d780dbbeb87f
REPORT RequestId: 02f1e697-5abd-423a-aa36-d780dbbeb87f	Duration: 1.92 ms	Billed Duration: 100 ms	Memory Size: 1024 MB	Max Memory Used: 53 MB	Init Duration: 146.71 ms



  Error --------------------------------------------------

  Error: Invoked function failed
      at AwsInvoke.log (/usr/local/Cellar/serverless/2.11.1/libexec/lib/node_modules/serverless/lib/plugins/aws/invoke/index.js:105:31)
  From previous event:
      at Object.invoke:invoke [as hook] (/usr/local/Cellar/serverless/2.11.1/libexec/lib/node_modules/serverless/lib/plugins/aws/invoke/index.js:23:12)
      at /usr/local/Cellar/serverless/2.11.1/libexec/lib/node_modules/serverless/lib/classes/PluginManager.js:510:55
  From previous event:
      at PluginManager.invoke (/usr/local/Cellar/serverless/2.11.1/libexec/lib/node_modules/serverless/lib/classes/PluginManager.js:510:22)
      at /usr/local/Cellar/serverless/2.11.1/libexec/lib/node_modules/serverless/lib/classes/PluginManager.js:545:24
  From previous event:
      at PluginManager.run (/usr/local/Cellar/serverless/2.11.1/libexec/lib/node_modules/serverless/lib/classes/PluginManager.js:545:8)
      at /usr/local/Cellar/serverless/2.11.1/libexec/lib/node_modules/serverless/lib/Serverless.js:170:33
      at processImmediate (node:internal/timers:463:21)
  From previous event:
      at Serverless.run (/usr/local/Cellar/serverless/2.11.1/libexec/lib/node_modules/serverless/lib/Serverless.js:157:74)
      at /usr/local/Cellar/serverless/2.11.1/libexec/lib/node_modules/serverless/scripts/serverless.js:50:26

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              15.2.0
     Framework Version:         2.11.1
     Plugin Version:            4.1.2
     SDK Version:               2.3.2
     Components Version:        3.3.0
```

</details>

<b>Installed version</b>

```
Framework Core: 2.11.1
Plugin: 4.1.2
SDK: 2.3.2
Components: 3.3.0
```

Additional information:

Serverless was installed with `brew install serverless` and docker is version `19.03.13`.

**Comment by TMorville** [comment]
Just solved this. 

The error was solved by doing the following:

1. Remove all cached packags in `/Library/Caches/serverless-python-requirements/`
2. Remove existing docker image `lambci/lambda        build-python3.8`

then running `sls deploy` worked beautifully.
