### ISSUE TITLE
Vague error when missing `provider.apiGateway.restApiRootResourceId` (with ``provider.apiGateway.restApiId` being configured)

### ISSUE THREAD

**Issue by steveperkinsi3** [serverless/serverless#8515]
The [Serverless documentation for using a shared API Gateway across stacks](https://www.serverless.com/framework/docs/providers/aws/events/apigateway/#easiest-and-cicd-friendly-example-of-using-shared-api-gateway-and-api-resources) shows that referencing a shared API Gateway is now as simple as setting `provider.apiGateway.restApiId` to the gateway's ID.

I have yet to successfully deploy a Serverless template using the described syntax. In every case CloudFormation validation fails with the error "The CloudFormation template is invalid: Template error: instance of Fn::GetAtt references undefined resource MyApiGatewayName" -- in fact, the same error CloudFormation throws with old versions of Serverless/AWS CLI as well (and the same error you get if you build a similar CloudFormation template without Serverless, SAM, or AWS CLI).

I've tried updating Serverless, updating AWS CLI v1, and updating AWS CLI v2, testing after each change. The same error persists.

The Serverless template below defines a simple API Gateway endpoint and hardcodes an existing API Gateway ID. Just like the documentation examples, I do have a stack set up to export the API Gateway's ID so it can be imported for use as `provider.apiGateway.restApiId`, but I get the same error regardless of whether I use `ImportValue` or hardcode the ID. To make this issue report simpler, the ID has been hardcoded.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: shared-api-gateway-bug

provider:
  name: aws
  runtime: python3.7
  region: ${opt:region, "us-east-2"}
  versionFunctions: false

  apiGateway:
    restApiId: ivrcdpj7y2 # Fn::ImportValue here results in the same error

functions:
   bugWebService:
    handler: handler.handler
    events:
      - http:
          path: /willneverbedeployed
          method: get

# The rest is just here to make the test package faster, since the full package is uploaded to AWS before CloudFormation validation throws the error
package:
  individually: false
  exclude:
    - env
    - node_modules
    - package*.json
    - "*.md"
    - "*.yml"
    - "__pycache__"
```

</details>

<details>
<summary><b><code>sls deploy --stage dev --profile MyProfile --aws-profile MyProfile</code> output</b></summary>

```
(node:2604) ExperimentalWarning: The dns.promises API is experimental
(node:2604) ExperimentalWarning: The fs.promises API is experimental
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.11.1")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 400 0.164s 0 retries] describeStacks({ StackName: 'shared-api-gateway-bug-dev' })
Serverless: Creating Stack...
Serverless: [AWS cloudformation 200 0.304s 0 retries] createStack({ StackName: 'shared-api-gateway-bug-dev',
  OnFailure: 'DELETE',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateBody:
   '{"AWSTemplateFormatVersion":"2010-09-09","Description":"The AWS CloudFormation template for this Serverless application","Resources":{"ServerlessDeploymentBucket":{"Type":"AWS::S3::Bucket","Properties":{"BucketEncryption":{"ServerSideEncryptionConfiguration":[{"ServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}}},"ServerlessDeploymentBucketPolicy":{"Type":"AWS::S3::BucketPolicy","Properties":{"Bucket":{"Ref":"ServerlessDeploymentBucket"},"PolicyDocument":{"Statement":[{"Action":"s3:*","Effect":"Deny","Principal":"*","Resource":[{"Fn::Join":["",["arn:",{"Ref":"AWS::Partition"},":s3:::",{"Ref":"ServerlessDeploymentBucket"},"/*"]]}],"Condition":{"Bool":{"aws:SecureTransport":false}}}]}}}},"Outputs":{"ServerlessDeploymentBucketName":{"Value":{"Ref":"ServerlessDeploymentBucket"}}}}',
  Tags: [ { Key: 'STAGE', Value: 'dev' }, [length]: 1 ] })
Serverless: Checking Stack create progress...
Serverless: [AWS cloudformation 200 0.115s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:us-east-2:184140869662:stack/shared-api-gateway-bug-dev/efc40d70-28ef-11eb-90c9-0204748462f4' })
...Serverless: [AWS cloudformation 200 0.128s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:us-east-2:184140869662:stack/shared-api-gateway-bug-dev/efc40d70-28ef-11eb-90c9-0204748462f4' })
Serverless: [AWS cloudformation 200 0.11s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:us-east-2:184140869662:stack/shared-api-gateway-bug-dev/efc40d70-28ef-11eb-90c9-0204748462f4' })
Serverless: [AWS cloudformation 200 0.11s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:us-east-2:184140869662:stack/shared-api-gateway-bug-dev/efc40d70-28ef-11eb-90c9-0204748462f4' })
Serverless: [AWS cloudformation 200 0.119s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:us-east-2:184140869662:stack/shared-api-gateway-bug-dev/efc40d70-28ef-11eb-90c9-0204748462f4' })
.Serverless: [AWS cloudformation 200 0.13s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:us-east-2:184140869662:stack/shared-api-gateway-bug-dev/efc40d70-28ef-11eb-90c9-0204748462f4' })
....
Serverless: Stack create finished...
Serverless: [AWS cloudformation 200 0.114s 0 retries] describeStackResource({ StackName: 'shared-api-gateway-bug-dev',
  LogicalResourceId: 'ServerlessDeploymentBucket' })
Serverless: [AWS s3 200 0.161s 0 retries] listObjectsV2({ Bucket:
   'shared-api-gateway-bug-d-serverlessdeploymentbuck-1pel5wj7j3i0o',
  Prefix: 'serverless/shared-api-gateway-bug/dev' })
Serverless: [AWS lambda 404 0.152s 0 retries] getFunction({ FunctionName: 'shared-api-gateway-bug-dev-bugWebService' })
Serverless: [AWS sts 200 0.161s 0 retries] getCallerIdentity({})
Serverless: Uploading CloudFormation file to S3...
Serverless: [AWS s3 200 0.12s 0 retries] putObject({ Body:
   <Buffer 7b 22 41 57 53 54 65 6d 70 6c 61 74 65 46 6f 72 6d 61 74 56 65 72 73 69 6f 6e 22 3a 22 32 30 31 30 2d 30 39 2d 30 39 22 2c 22 44 65 73 63 72 69 70 74 ... >,
  Bucket:
   'shared-api-gateway-bug-d-serverlessdeploymentbuck-1pel5wj7j3i0o',
  Key:
   'serverless/shared-api-gateway-bug/dev/1605629654043-2020-11-17T16:14:14.043Z/compiled-cloudformation-template.json',
  ContentType: 'application/json',
  Metadata:
   { filesha256: '3U+sIvxlc58xy60JGNhWsY8/ASBpyZ/NS/dHby3JJIY=' } })
Serverless: Uploading artifacts...
Serverless: Uploading service shared-api-gateway-bug.zip file to S3 (5.66 KB)...
Serverless: [AWS s3 200 0.163s 0 retries] putObject({ Body:
   <Buffer 50 4b 03 04 14 00 08 00 00 00 00 00 21 00 00 00 00 00 00 00 00 00 00 00 00 00 0b 00 00 00 5f 5f 69 6e 69 74 5f 5f 2e 70 79 50 4b 07 08 00 00 00 00 00 ... >,
  Bucket:
   'shared-api-gateway-bug-d-serverlessdeploymentbuck-1pel5wj7j3i0o',
  Key:
   'serverless/shared-api-gateway-bug/dev/1605629654043-2020-11-17T16:14:14.043Z/shared-api-gateway-bug.zip',
  ContentType: 'application/zip',
  Metadata:
   { filesha256: 'BKRDpmNEUi4KkfKeG8laCXhZETz8u59IXR0Z0Ps89zI=' } })
Serverless: Validating template...
Serverless: [AWS cloudformation 400 0.368s 0 retries] validateTemplate({ TemplateURL:
   'https://s3.amazonaws.com/shared-api-gateway-bug-d-serverlessdeploymentbuck-1pel5wj7j3i0o/serverless/shared-api-gateway-bug/dev/1605629654043-2020-11-17T16:14:14.043Z/compiled-cloudformation-template.json' })
 
  Error --------------------------------------------------

  Error: The CloudFormation template is invalid: Template error: instance of Fn::GetAtt references undefined resource MyApiGatewayName
      at provider.request.catch.error (C:\Users\xx\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\lib\validateTemplate.js:20:13)
  From previous event:
      at AwsDeploy.validateTemplate (C:\Users\xx\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\lib\validateTemplate.js:16:85)
  From previous event:
      at AwsDeploy.BbPromise.bind.then (C:\Users\xx\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\index.js:119:39)
  From previous event:
      at Object.aws:deploy:deploy:validateTemplate [as hook] (C:\Users\xx\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\index.js:115:30)
      at BbPromise.reduce (C:\Users\xx\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:510:55)
  From previous event:
      at PluginManager.invoke (C:\Users\xx\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:510:22)
      at PluginManager.spawn (C:\Users\xx\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:530:17)
      at AwsDeploy.BbPromise.bind.then (C:\Users\xx\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\index.js:93:48)
  From previous event:
      at Object.deploy:deploy [as hook] (C:\Users\xx\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\index.js:89:30)
      at BbPromise.reduce (C:\Users\xx\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:510:55)
  From previous event:
      at PluginManager.invoke (C:\Users\xx\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:510:22)
      at getHooks.reduce.then (C:\Users\xx\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:545:24)
  From previous event:
      at PluginManager.run (C:\Users\xx\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:545:8)
      at variables.populateService.then (C:\Users\xx\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:170:33)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:120:23)
  From previous event:
      at Serverless.run (C:\Users\xx\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:157:74)
      at serverless.init.then.then (C:\Users\xx\AppData\Roaming\npm\node_modules\serverless\scripts\serverless.js:50:26)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              10.14.2
     Framework Version:         2.11.1
     Plugin Version:            4.1.2
     SDK Version:               2.3.2
     Components Version:        3.3.0
```

</details>

<b>Installed version</b>

```
(node:12492) ExperimentalWarning: The dns.promises API is experimental
(node:12492) ExperimentalWarning: The fs.promises API is experimental
Framework Core: 2.11.1
Plugin: 4.1.2
SDK: 2.3.2
Components: 3.3.0
```
<b>Installed AWS CLI version</b>
```
aws-cli/2.1.1 Python/3.7.7 Windows/10 exe/AMD64
```

**Comment by medikoo** [comment]
@steveperkinsi3 this the error that surfaces from AWS after template validation, and is the result of missing  `restApiRootResourceId` which is not configured in your service (while indicated as mandatory by the docs).

Error on our side, is that we do not validate it cleanly, and present user with vague message.

It'll be great to internally validate that with `restApiId` also `restApiRootResourceId` is provided. PR that brings that is welcome!

**Comment by steveperkinsi3** [comment]
@medikoo thank you for taking a look at this issue. A little further up in the linked documentation it says:

> You can define more than one path resource, but by default, Serverless will generate them from the root resource. restApiRootResourceId is optional if a path resource isn't required for the root (/).

This is why I thought `restApiRootResourceId` was not needed. However, I can try to find the place where `restApiId` is validated and get a PR going for validating `restApiRootResourceId` at the same point, maybe with a failure message like "restApiRootResourceId is required when restApiId is provided".

**Comment by medikoo** [comment]
@steveperkinsi3 thanks for note. Maybe it's optional if you define the root resource in capacity of the service (?) Still then benefits of using shared API seems controversial, as every other service will need to attach to this root resource somehow.

It'll be good to investigate it, and eventually throw error message only for cases which are invalid per AWS rules.

**Comment by steveperkinsi3** [comment]
@medikoo you're right, when I include `restApiRootResourceId` (in another template with real web services), this error is thrown instead:
```
An error occurred: ApiGatewayResourceUser - Another resource with the same parent already has this name: user (Service: AmazonApiGateway; Status Code: 409; Error Code: ConflictException; Request ID: 38619493-43fe-4e77-8174-5cc0a62701a0; Proxy: null)
```

Most of the endpoints in all of my Serverless templates start with `/customer/{customerId}/location/{locationId}`. As you said, the current functionality of a shared API Gateway is rather pointless if a) all endpoints defined in a given Serverless template must be 100% unique across all Serverless templates referencing the shared API Gateway, and b) the root resource ID must be re-defined in every Serverless template. And c) we have to re-define every endpoint path in `provider.apiGateway.restApiResources` or the resulting deployment behavior with an existing API Gateway is quite unexpected.

Over the weekend I tried to find a reasonable solution to this but failed.

**Comment by medikoo** [comment]
I believe current state is that root resource should be defined with the API. Having that you can create few services that extend this API. Still  what may not be possible is to use same url prefixes across different services (e.g. `/foo/bar` in one and `/foo/other` in other service), but it's totally doable to have `/foo` in one service and `/bar` in other.

This goes down how verbose APIGateway configuration is on CloudFormation level.

Note that HTTP API is free of such limitations, it has way improved design, and feature-wise I think it's mostly on par with API Gateway now.

**Comment by steveperkinsi3** [comment]
I agree, V2 is a huge improvement over the older API Gateway. Earlier this year I started a project using HTTP API instead of REST API and it was great (and cheaper!) but I ran into roadblocks where it didn't support for authorizers for "normal" cases (custom/lambda authorizer, Cognito authorizer) well. It seems like the only reasonable path forward is to give it another shot and see if those limitations have been fixed.

I suppose a kind of crummy alternative for API is to read the Serverless file to find desired endpoint paths use the AWS CLI/API to add them one by one. I haven't tried it but I know API Gateway does support multiple endpoints with the same prefix (e.g. `/foo/boo/bar` and `/foo/zoo/zar`). The limitation seems to be CloudFormation's management of them.

**Comment by sdas13** [comment]
Hi @medikoo 
Can I work on this issue if it's still relevant?

**Comment by medikoo** [comment]
@sdas13 that'll be great!

**Comment by sdas13** [comment]
@medikoo 
If `restApiRootResourceId` is present or not with `restApiId`, can be handled  in the provider
https://github.com/serverless/serverless/blob/4d4f8637d830ba9a72806fc127fe3497f7c0f23c/lib/plugins/aws/provider.js#L1745-L1754 OR 
it can be handled at the beginning in the Compile function 
https://github.com/serverless/serverless/blob/4d4f8637d830ba9a72806fc127fe3497f7c0f23c/lib/plugins/aws/package/compile/functions.js#L160

which one is ideal?

**Comment by medikoo** [comment]
@sdas13 I would handle it in `http` event context, as those setting are specific to it. This event has dedicated validation method, so I would include it there: https://github.com/serverless/serverless/blob/4d4f8637d830ba9a72806fc127fe3497f7c0f23c/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js#L41
