### ISSUE TITLE
GCP deployment handler name issue (with dot) for java functions

### ISSUE THREAD

**Issue by leo7** [serverless/serverless#8541]
I am trying to deploy an existing aws serverless stack to gcp, it is currently implemented by using java8.

I did a couple of tests by using python and it works. But I changed the handler to java class

So please advice when it is supported or any work-round for this issue?

⚠️⚠️ REPLACE WITH DESCRIPTION

<details>
<summary><code>serverless.yml</code></summary>

```yaml
n/a
```

</details>

<details>
<b>The output</b></summary>

```
Error: The "handler" property for the function "bsFileTransferInitProcessor" is invalid. Handlers should be plain strings referencing only the exported function name without characters such as "." or "/" (so e.g. "http" instead of "index.http"). Do you want to nest your functions code in a subdirectory? Google solves this by utilizing the "main" config in the projects package.json file. Please check the docs for more info.
      at /home/leo/workspace/data-receipt-station/node_modules/serverless-google-cloudfunctions/shared/validate.js:50:15
      at /home/leo/workspace/data-receipt-station/node_modules/lodash/lodash.js:4925:15
```

<b>Installed version</b>

```
Framework Core: 1.58.0
Plugin: 3.2.5
SDK: 2.2.1
Components Core: 1.1.2
Components CLI: 1.4.0

```

**Comment by medikoo** [comment]
@leo7 this tracker is purely for confirmed bug reports and feature requests.

For general support please check:
- https://forum.serverless.com/
- https://www.serverless.com/slack
- http://stackoverflow.com/questions/tagged/serverless-framework

Also note that you're using a highly outdated version of a Framework

**Comment by yyamano** [comment]
It's a serverless-google-cloudfunctions issue, not the serverless framework itself.

This validation logic was introduced by https://github.com/serverless/serverless-google-cloudfunctions/pull/72 to fix https://github.com/serverless/serverless-google-cloudfunctions/issues/59
I guess it works fine for javascript, but not for java.
