### ISSUE TITLE
ServerlessError: No file matches include / exclude patterns for Lambda Layer

### ISSUE THREAD

**Issue by corydorning53** [serverless/serverless#8576]
Getting the error `ServerlessError: No file matches include / exclude patterns` when trying to deploy a lambda layer.

First I package everything and run:
`webpack && export SLS_DEBUG=* && npx serverless package --stage dev --package ./_artifacts/serverless`

My webpack.config.js is:
```
// dependencies
const path = require('path');

// distribution directory
const dist = 'dist/nodejs/node_modules/my-lambda-layer';

module.exports = {
  entry: './src/index.js',
  mode: 'production',
  externals: 'aws-sdk', // aws-sdk is already in Lambda environment, so don't bundle it
  output: {
    filename: 'index.js',
    path: path.resolve(__dirname, dist),
    libraryTarget: 'commonjs2'
  },
  optimization: {
    minimize: false,
  },
  target: 'node'
};
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: my-lambda-layer
frameworkVersion: ^2.13.0

provider:
  name: aws
  region: us-east-2

package:
  artifact: ${opt:artifact, ''}
  
layers:
  my-lambda-layer:
    path: dist
    description: xxx
    compatibleRuntimes:
      - nodejs12.x
    retain: true
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
export SLS_DEBUG=* && npx serverless deploy --stage dev --artifact ./_artifacts/serverless/my-lambda-layer.zip

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
 
  Serverless Error ---------------------------------------
 
  ServerlessError: No file matches include / exclude patterns
      at /home/jenkins/agent/workspace/my-lambda-layer_feature_jenkins/node_modules/serverless/lib/plugins/package/lib/packageService.js:274:13
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  From previous event:
      at Package.packageService (/home/jenkins/agent/workspace/my-lambda-layer_feature_jenkins/node_modules/serverless/lib/plugins/package/lib/packageService.js:94:22)
  From previous event:
      at Object.package:createDeploymentArtifacts [as hook] (/home/jenkins/agent/workspace/my-lambda-layer_feature_jenkins/node_modules/serverless/lib/plugins/package/package.js:58:71)
  From previous event:
      at PluginManager.invoke (/home/jenkins/agent/workspace/my-lambda-layer_feature_jenkins/node_modules/serverless/lib/classes/PluginManager.js:521:22)
      at /home/jenkins/agent/workspace/my-lambda-layer_feature_jenkins/node_modules/serverless/lib/classes/PluginManager.js:556:24
  From previous event:
      at PluginManager.run (/home/jenkins/agent/workspace/my-lambda-layer_feature_jenkins/node_modules/serverless/lib/classes/PluginManager.js:556:8)
      at /home/jenkins/agent/workspace/my-lambda-layer_feature_jenkins/node_modules/serverless/lib/Serverless.js:203:33
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Serverless.run (/home/jenkins/agent/workspace/my-lambda-layer_feature_jenkins/node_modules/serverless/lib/Serverless.js:190:74)
      at /home/jenkins/agent/workspace/my-lambda-layer_feature_jenkins/node_modules/serverless/scripts/serverless.js:50:26
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.2.0
     Framework Version:         2.13.0 (local)
     Plugin Version:            4.1.2
     SDK Version:               2.3.2
     Components Version:        3.4.2
```

</details>

<b>Installed version</b>

```
Framework Core: 2.13.0 (local)
Plugin: 4.1.2
SDK: 2.3.2
Components: 3.4.2
```

**Comment by medikoo** [comment]
@corydorning53 please report at webpack plugin repository

**Comment by corydorning53** [comment]
what exactly is the issue? not sure I follow why this is a webpack issue. Thanks!

**Comment by medikoo** [comment]
@corydorning53 you're referencing `webpack.config.js` what's the point of that? Note that Framework has no built in webpack support

**Comment by corydorning53** [comment]
understood. I only included it to capture my project settings. I suppose its irrelevant. but basically all `webpack` does is packages up my lambda layer into `dist/nodejs/node_modules/secdev-aws-vault-credentials/index.js`. I then point my serverless.yml config to `layers: path: dist`. 

Sorry if including it caused confusion.

**Comment by medikoo** [comment]
@corydorning53  this tracker is purely for confirmed bug reports and feature requests.

For general support please check:
- https://forum.serverless.com/
- https://www.serverless.com/slack
- http://stackoverflow.com/questions/tagged/serverless-framework

**Comment by corydorning53** [comment]
is what I reported not a bug? I'm pointing serverless to a path and its throwing back an error about includes/excludes (which I don't even have in my serverless.yml.

Confused.

**Comment by medikoo** [comment]
> is what I reported not a bug? 

`serverless.yml` as put in description doesn't reproduce reported issue.

I've recreated it here: https://github.com/medikoo/test-serverless/tree/issue-8576 and it deploys without issues

**Comment by corydorning53** [comment]
@medikoo thanks for the due diligence and touche. Any ideas on why serverless might throw the error below? More than happy to dig into it, just looking for a jumping off point...

```
Serverless: Excluding development dependencies...
 
  Serverless Error ---------------------------------------
 
  ServerlessError: No file matches include / exclude patterns
```

**Comment by medikoo** [comment]
> @medikoo thanks for the due diligence and touche. Any ideas on why serverless might throw the error below? 

I can just refer to example you posted, and it's clear that it works without issues.

Error means that that are no files at target packaging path, e.g. if I delete the `dist` folder in test case I created, and run `sls package` I'll receive exactly the error you get (and that's the expected behavior)

Again for general aid and support please check:
- https://forum.serverless.com/
- https://www.serverless.com/slack
- http://stackoverflow.com/questions/tagged/serverless-framework

**Comment by corydorning53** [comment]
@medikoo great thanks!
