### ISSUE TITLE
0.5 Having more than one variable component fails on API Gateway deploy

### ISSUE THREAD

**Issue by mwawrusch** [serverless/serverless#859]
It seems to be impossible to deploy when the endpoint has more than one variable components in it.

```
Serverless: Deploying endpoints in "dev" to the following regions: us-east-1  
Serverless: \ /Users/mwawrusch/.nvm/versions/node/v4.2.1/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

BadRequestException: Resource with id 'null' has more than one variable component as a direct child: [{id}, {accountId}]
    at Object.extractError (/Users/mwawrusch/.nvm/versions/node/v4.2.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/protocol/json.js:43:27)
    at Request.extractError (/Users/mwawrusch/.nvm/versions/node/v4.2.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/protocol/rest_json.js:37:8)
    at Request.callListeners (/Users/mwawrusch/.nvm/versions/node/v4.2.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/mwawrusch/.nvm/versions/node/v4.2.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/mwawrusch/.nvm/versions/node/v4.2.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/Users/mwawrusch/.nvm/versions/node/v4.2.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/Users/mwawrusch/.nvm/versions/node/v4.2.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/mwawrusch/.nvm/versions/node/v4.2.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/mwawrusch/.nvm/versions/node/v4.2.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/Users/mwawrusch/.nvm/versions/node/v4.2.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:598:12)
    at Request.callListeners (/Users/mwawrusch/.nvm/versions/node/v4.2.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/mwawrusch/.nvm/versions/node/v4.2.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/mwawrusch/.nvm/versions/node/v4.2.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/Users/mwawrusch/.nvm/versions/node/v4.2.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/Users/mwawrusch/.nvm/versions/node/v4.2.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/mwawrusch/.nvm/versions/node/v4.2.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
From previous event:
    at ServerlessProviderAws.request (/Users/mwawrusch/.nvm/versions/node/v4.2.1/lib/node_modules/serverless/lib/ProviderAws.js:65:14)
    at /Users/mwawrusch/.nvm/versions/node/v4.2.1/lib/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js:387:28
    at /Users/mwawrusch/.nvm/versions/node/v4.2.1/lib/node_modules/serverless/node_modules/async/lib/async.js:181:20
    at Immediate.iterate [as _onImmediate] (/Users/mwawrusch/.nvm/versions/node/v4.2.1/lib/node_modules/serverless/node_modules/async/lib/async.js:262:13)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
Martins-MacBook-Air:api-excel2text-com mwawrusch$ 

```

from this function definition:

```
{
  "name": "a_accountid_apps_id_settings_get",
  "description" : "Retrieves the settings for a specific account and app.",
  "customName": false,
  "customRole": false,
  "handler": "handler.handler",
  "timeout": 6,
  "memorySize": 128,
  "authorizer": {},
  "custom": {
    "excludePatterns": [],
    "envVars": []
  },
  "endpoints": [
    {
      "path": "/a/{accountId}/apps/{id}/settings",
      "method": "GET",
      "type": "AWS",
      "authorizationType": "aws_iam",
      "authorizerId": false,
      "customAuthorizer": false,
      "apiKeyRequired": false,
      "requestParameters": {},
      "requestTemplates":  "$${apiRequestTemplate}",
      "responses": {
        "400": {
          "statusCode": "400"
        },
        "default": {
          "statusCode": "200",
          "responseParameters": {},
          "responseModels": {},
          "responseTemplates": {
            "application/json": ""
          }
        }
      }
    }
  ],
  "events": [],
  "vpc": {
    "securityGroupIds": [],
    "subnetIds": []
  },
  "runtime": "nodejs"
}
```

**Comment by mwawrusch** [comment]
I think I found the problem, and it might be an aws limitation. I have two endpoints: one is /a/{id} ... and the other one is /a/{accountId}/something/{someId} - the problem is at the first level, not the second one so it seems.

**Comment by mwawrusch** [comment]
As it turns out this is actually an amazon aws error. You can't have two path like this in an API Gateway project: /a/{idX} and /a/{idY} - very interesting indeed. Perhaps if possible this should be added to a FAQ / Readme somewhere, definitely a more random limitation that people don't know about.

**Comment by eahefnawy** [comment]
@mwawrusch thanks for sharing this with us. I'm sure it'll help someone facing the same issue. :blush:

**Comment by zateo** [comment]
@eahefnawy Can this limitation be removed, or is there a workaround?

**Comment by AniAko** [comment]
Ambiguous variables in URIs can't be worked around.  AWS API Gateway plays just fine across different endpoints as long as the URI path is consistent across all s-function files.

/a/{idX}
/a/{idY}/b/{idZ}

that can easily be refactored into:

/a/{idX}
/a/{idX}/b/{idZ}

it will require changes in the code, but if you resist putting anything but api handling logic in the handler.js, essentially treating it as a wrapper/adapter, your primary logic won't be affected.
