### ISSUE TITLE
Creating a new Node.js REST API with an application name at https://app.serverless.com/ does not work.

### ISSUE THREAD

**Issue by bu-ra3y** [serverless/serverless#8687]
Creating a new Node.js REST API with an application name at https://app.serverless.com/ does not work.

Repro steps (follows create-new-app process exactly):
go to https://app.serverless.com/
sign in
Create App
Select node.js REST API
enter an application name like xxxx-external-rater
select the AWS Role I already provided
install with the provided command `npm i -g serverless && serverless init sf_WB3Zmxbk`
deploy with the provided command `cd one-two-three && serverless deploy`
you will see "Waiting for deploy..." in the app at app.serverless.com ... this will never change/complete.
... hits the error message shown

<details>
<summary><code>serverless.yml</code></summary>

```yaml
org: myorg
app: xxxx-external-rater
service: xxxx-external-rater

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
```

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
Serverless: Deprecation warning: Detected ".env" files. Note that Framework now supports loading variables from those files when "useDotenv: true" is set (and that will be the default from next major release)
            More Info: https://www.serverless.com/framework/docs/deprecations/#LOAD_VARIABLES_FROM_ENV_FILES
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.16.1")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
platform-sdk fetching: POST https://api.serverless.com/core/tenants/myorg/applications/xxxx-external-rater/profileValue

  Error --------------------------------------------------

  Error: {"errorMessage":"Application not found. - Please contact support and provide this identifier to reference this issue - HWB37PW9D7RY"}
      at _callee$ (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/src/utils/checkHttpResponse.js:19:9)
      at tryCatch (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator.next (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:118:21)
      at step (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/dist/utils/checkHttpResponse.js:7:191)
      at /Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/dist/utils/checkHttpResponse.js:7:361
  From previous event:
      at PluginManager.asyncPluginInit (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/lib/classes/PluginManager.js:668:22)
      at PluginManager.loadAllPlugins (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/lib/classes/PluginManager.js:142:17)
      at /Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/lib/Serverless.js:93:39
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.18.2
     Framework Version:         2.16.1
     Plugin Version:            4.3.0
     SDK Version:               2.3.2
     Components Version:        3.4.3

```

</details>

<b>Installed version</b>

```
Serverless: Deprecation warning: Detected ".env" files. Note that Framework now supports loading variables from those files when "useDotenv: true" is set (and that will be the default from next major release)
            More Info: https://www.serverless.com/framework/docs/deprecations/#LOAD_VARIABLES_FROM_ENV_FILES
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.16.1")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
platform-sdk fetching: POST https://api.serverless.com/core/tenants/socotra/applications/sigo-external-rater/profileValue

  Error --------------------------------------------------

  Error: {"errorMessage":"Application not found. - Please contact support and provide this identifier to reference this issue - HWDQR31FK4C5"}
      at _callee$ (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/src/utils/checkHttpResponse.js:19:9)
      at tryCatch (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator.next (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:118:21)
      at step (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/dist/utils/checkHttpResponse.js:7:191)
      at /Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/dist/utils/checkHttpResponse.js:7:361
  From previous event:
      at PluginManager.asyncPluginInit (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/lib/classes/PluginManager.js:668:22)
      at PluginManager.loadAllPlugins (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/lib/classes/PluginManager.js:142:17)
      at /Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/lib/Serverless.js:93:39
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.18.2
     Framework Version:         2.16.1
     Plugin Version:            4.3.0
     SDK Version:               2.3.2
     Components Version:        3.4.3
```

**Comment by stevewillard** [comment]
Hi there. Do you mind trying again? We identified an issue, and pushed out a fix, which should resolve this. Thanks for reporting it!

**Comment by bu-ra3y** [comment]
Good stuff. Yes I'll probably try it again soon.

Will

**Comment by bu-ra3y** [comment]
Hey @stevewillard , I just tried again and failed!













Same issue described above - following the 1-2-3 setup from app.serverless.com did not make it when trying to deploy for the first time. 



<details>
<summary><code>serverless.yml</code></summary>

```yaml
org: socotra
app: protectedapi
service: protectedapi

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
```

</details>



<details>
<summary><b><code>serverless deploy</code> output</b></summary>

```
(base) will@MacBook-Pro protectedapi % serverless deploy
Serverless: Deprecation warning: Detected ".env" files. Note that Framework now supports loading variables from those files when "useDotenv: true" is set (and that will be the default from next major release)
            More Info: https://www.serverless.com/framework/docs/deprecations/#LOAD_VARIABLES_FROM_ENV_FILES
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.18.0")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
platform-sdk fetching: POST https://api.serverless.com/core/tenants/socotra/applications/protectedapi/profileValue
ignoring profile fetch error Error: {"errorMessage":"Application not found. - Please contact support and provide this identifier to reference this issue - JWRM8J6P6W82"}
    at _callee$ (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/src/utils/checkHttpResponse.js:19:9)
    at tryCatch (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:118:21)
    at step (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/dist/utils/checkHttpResponse.js:7:191)
    at /Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/dist/utils/checkHttpResponse.js:7:361
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Serverless: Deprecation warning: Starting with next major version, default value of provider.lambdaHashingVersion will be equal to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Deprecation warning: Starting with next major version, API Gateway naming will be changed from "{stage}-{service}" to "{service}-{stage}".
            Set "provider.apiGateway.shouldStartNameWithService" to "true" to adapt to the new behavior now.
            More Info: https://www.serverless.com/framework/docs/deprecations/#AWS_API_GATEWAY_NAME_STARTING_WITH_SERVICE
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
platform-sdk fetching: GET https://api.serverless.com/core/meta
platform-sdk fetching: GET https://api.serverless.com/core/tenants/socotra/applications/protectedapi

  Error --------------------------------------------------

  Error: {"errorMessage":"Application not found. - Please contact support and provide this identifier to reference this issue - JWGBVK4HBSXN"}
      at _callee$ (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/src/utils/checkHttpResponse.js:19:9)
      at tryCatch (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator.next (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:118:21)
      at step (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/dist/utils/checkHttpResponse.js:7:191)
      at /Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/dist/utils/checkHttpResponse.js:7:361
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  From previous event:
      at PluginManager.invoke (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/lib/classes/PluginManager.js:518:22)
      at /Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/lib/classes/PluginManager.js:553:24
  From previous event:
      at PluginManager.run (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/lib/classes/PluginManager.js:553:8)
      at /Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/lib/Serverless.js:203:33
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Serverless.run (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/lib/Serverless.js:190:74)
      at /Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/scripts/serverless.js:50:26

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.18.2
     Framework Version:         2.18.0
     Plugin Version:            4.4.2
     SDK Version:               2.3.2
     Components Version:        3.4.6
```

</details>



<b>Installed version</b>

```
Serverless: Deprecation warning: Detected ".env" files. Note that Framework now supports loading variables from those files when "useDotenv: true" is set (and that will be the default from next major release)
            More Info: https://www.serverless.com/framework/docs/deprecations/#LOAD_VARIABLES_FROM_ENV_FILES
Framework Core: 2.18.0
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.4.6
```

I really want this to work!

BTW, it seems that the only way to connect an app/service to app.servless.com so that you get all of the nice logs and graphs, is to start the process from app.servless.com. Is that right? Or can I start the app on the command line and then connect it to app.servless.com?

Will

**Comment by bu-ra3y** [comment]
Hmm it seems interesting that I get the same error when running `serverless --version` with debugging output turned on.  I guess the same call is being made. 

```shell
(base) will@MacBook-Pro protectedapi % serverless --version
Serverless: Deprecation warning: Detected ".env" files. Note that Framework now supports loading variables from those files when "useDotenv: true" is set (and that will be the default from next major release)
            More Info: https://www.serverless.com/framework/docs/deprecations/#LOAD_VARIABLES_FROM_ENV_FILES
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.18.0")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
platform-sdk fetching: POST https://api.serverless.com/core/tenants/socotra/applications/protectedapi/profileValue
ignoring profile fetch error Error: {"errorMessage":"Application not found. - Please contact support and provide this identifier to reference this issue - JWCDQZG1ZHCS"}
    at _callee$ (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/src/utils/checkHttpResponse.js:19:9)
    at tryCatch (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:118:21)
    at step (/Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/dist/utils/checkHttpResponse.js:7:191)
    at /Users/will/.nvm/versions/node/v12.18.2/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/dist/utils/checkHttpResponse.js:7:361
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Framework Core: 2.18.0
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.4.6
```

**Comment by rishi8094** [comment]
@bu-ra3y If you are still having the issue, I have found if create the application as an "existing-application" and provide the app and service name as in your serverless config it will deploy.

**Comment by bu-ra3y** [comment]
Rishi, thank you, that's helpful.
