### ISSUE TITLE
S3 events in Tokyo fail to deploy

### ISSUE THREAD

**Issue by c-knowles** [serverless/serverless#877]
With 0.5.0, trying to deploy an S3 event to Tokyo fails. I enabled debug and got this:

```
Serverless: Deploying events in "dev" to the following regions: ap-northeast-1  
Serverless: |   serverless:lib.actions.EventLambdaS3 Removed lambda permission with statement ID: sEvents-foo-dev +335ms
  serverless:lib.actions.EventLambdaS3 Adding lambda permission with statement ID: sEvents-foo-dev +1ms
Serverless: Failed to deploy events in "dev" to the following regions:  
Serverless: ap-northeast-1 ------------------------  
Serverless:   foo: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.  
  serverless:lib.actions.EventDeploy PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
    at Request.extractError (/Users/cknowles/bar/node_modules/aws-sdk/lib/services/s3.js:328:35)
    at Request.callListeners (/Users/cknowles/bar/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/cknowles/bar/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/cknowles/bar/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/Users/cknowles/bar/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/Users/cknowles/bar/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/cknowles/bar/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/cknowles/bar/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/Users/cknowles/bar/node_modules/aws-sdk/lib/request.js:598:12)
    at Request.callListeners (/Users/cknowles/bar/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/cknowles/bar/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/cknowles/bar/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/Users/cknowles/bar/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/Users/cknowles/bar/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/cknowles/bar/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/cknowles/bar/node_modules/aws-sdk/lib/request.js:37:9)
From previous event:
    at ServerlessProviderAws.request (/Users/cknowles/bar/node_modules/serverless/lib/ProviderAws.js:65:14)
    at /Users/cknowles/bar/node_modules/serverless/lib/actions/EventLambdaS3.js:114:28
```

I'm guessing there is somewhere defaulting to the AWS SDK default region and this is turn can lead to the bucket lookup failing. [This](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region) may be useful for this ticket.

**Comment by c-knowles** [comment]
Could potentially be an AWS issue as just tried to do the same in the console and it says the bucket needs to be in the same region but I double checked this and it is in the same region.

**Comment by eahefnawy** [comment]
@c-knowles I just tried this but I wasn't able to reproduce. I successfully deployed an S3 event in the tokyo region, and of course the lambda is in the tokyo region as well. I'm guessing it's an AWS issue for your specific case. Let us know if there's anything we can do to help :blush:

**Comment by c-knowles** [comment]
Just upgraded to 0.5.1 and still have the same issue. This project was a fresh one created with 0.5.0. Not sure if it will shed any more light on the problem but my event config is:
```
"events": [
    {
      "name": "docs",
      "type": "s3",
      "config": {
        "bucket": "foo.${stage}.${region}",
        "bucketEvents": ["s3:ObjectCreated:*"],
        "filterRules": [
          {
            "name": "prefix",
            "value": "processed/"
          }
        ]
      }
    }
  ],
```

**Comment by c-knowles** [comment]
@eahefnawy anything else I could provide to help diagnose?

**Comment by eahefnawy** [comment]
Hmmmm are you certain the bucket is in the same region? Maybe you can try a brand new bucket in that region?

Generally, I've made some enhancements for S3 events today and we'll be including it in the upcoming minor release. It may solve the issue :)

**Comment by c-knowles** [comment]
Yes, definitely sure. Output from serverless dash summary:
```
Serverless: 1 stages ------------------------------  
Serverless:     |_ dev (1 regions)  
Serverless:         |_ ap-northeast-1  
```

And from the S3 console for my bucket:
```
Region:	Tokyo
```

I will try a brand new bucket now and see what happens.

**Comment by c-knowles** [comment]
Nope, same thing I'm afraid with a new bucket just created a few minutes ago. I also tried a new function and simplifying the event config just in case that made any difference (I removed the `filterRules` and named the bucket directly without the `${stage}` and `${region}` variables).

I tried a `dash deploy` and `event deploy` with the same results. Here's the full stack trace in case it unveils anything. I can wait for the update or let me know if there is any other info you'd like.
```
Serverless: Deploying events in "dev" to the following regions: ap-northeast-1  
Serverless: |   serverless:lib.actions.EventLambdaS3 Removed lambda permission with statement ID: sEvents-bar-foo-docs-dev +345ms
  serverless:lib.actions.EventLambdaS3 Adding lambda permission with statement ID: sEvents-bar-foo-docs-dev +0ms
Serverless: Failed to deploy events in "dev" to the following regions:  
Serverless: ap-northeast-1 ------------------------  
Serverless:   docs: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.  
  serverless:lib.actions.EventDeploy PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
    at Request.extractError (/Users/cknowles/Projects/bar/node_modules/aws-sdk/lib/services/s3.js:328:35)
    at Request.callListeners (/Users/cknowles/Projects/bar/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/cknowles/Projects/bar/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/cknowles/Projects/bar/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/Users/cknowles/Projects/bar/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/Users/cknowles/Projects/bar/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/cknowles/Projects/bar/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/cknowles/Projects/bar/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/Users/cknowles/Projects/bar/node_modules/aws-sdk/lib/request.js:598:12)
    at Request.callListeners (/Users/cknowles/Projects/bar/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/cknowles/Projects/bar/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/cknowles/Projects/bar/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/Users/cknowles/Projects/bar/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/Users/cknowles/Projects/bar/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/cknowles/Projects/bar/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/cknowles/Projects/bar/node_modules/aws-sdk/lib/request.js:37:9)
From previous event:
    at ServerlessProviderAws.request (/Users/cknowles/Projects/bar/node_modules/serverless/lib/ProviderAws.js:65:14)
    at /Users/cknowles/Projects/bar/node_modules/serverless/lib/actions/EventLambdaS3.js:114:28
From previous event:
    at EventLambdaS3.eventLambdaS3 (/Users/cknowles/Projects/bar/node_modules/serverless/lib/actions/EventLambdaS3.js:85:10)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at /Users/cknowles/Projects/bar/node_modules/serverless/lib/Serverless.js:206:25
    at Array.reduce (native)
    at Serverless._execute (/Users/cknowles/Projects/bar/node_modules/serverless/lib/Serverless.js:205:26)
    at Object.actions.(anonymous function) [as eventLambdaS3] (/Users/cknowles/Projects/bar/node_modules/serverless/lib/Serverless.js:424:20)
    at /Users/cknowles/Projects/bar/node_modules/serverless/lib/actions/EventDeploy.js:246:36
    at /Users/cknowles/Projects/bar/node_modules/async/lib/async.js:181:20
    at iterate (/Users/cknowles/Projects/bar/node_modules/async/lib/async.js:262:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (/Users/cknowles/Projects/bar/node_modules/async/lib/async.js:281:9)
    at Object.async.forEachSeries.async.eachSeries (/Users/cknowles/Projects/bar/node_modules/async/lib/async.js:214:22)
    at /Users/cknowles/Projects/bar/node_modules/serverless/lib/actions/EventDeploy.js:224:15
From previous event:
    at EventDeploy._deployEventsByRegion (/Users/cknowles/Projects/bar/node_modules/serverless/lib/actions/EventDeploy.js:222:14)
    at EventDeploy.<anonymous> (/Users/cknowles/Projects/bar/node_modules/serverless/lib/actions/EventDeploy.js:204:24)
From previous event:
    at EventDeploy._processDeployment (/Users/cknowles/Projects/bar/node_modules/serverless/lib/actions/EventDeploy.js:201:10)
From previous event:
    at EventDeploy.eventDeploy (/Users/cknowles/Projects/bar/node_modules/serverless/lib/actions/EventDeploy.js:90:10)
From previous event:
    at /Users/cknowles/Projects/bar/node_modules/serverless/lib/Serverless.js:181:31
    at Array.reduce (native)
    at /Users/cknowles/Projects/bar/node_modules/serverless/lib/Serverless.js:180:32
From previous event:
    at Serverless._execute (/Users/cknowles/Projects/bar/node_modules/serverless/lib/Serverless.js:178:12)
    at Serverless.actions.(anonymous function) (/Users/cknowles/Projects/bar/node_modules/serverless/lib/Serverless.js:424:20)
    at Serverless.command (/Users/cknowles/Projects/bar/node_modules/serverless/lib/Serverless.js:393:38)
    at /Users/cknowles/Projects/bar/node_modules/serverless/bin/serverless:19:16
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at Object.<anonymous> (/Users/cknowles/Projects/bar/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3 +2s
Serverless:   
Serverless: Run this again with --debug to get more error information...
```

**Comment by c-knowles** [comment]
@eahefnawy, I got a chance today to have a look at this again. I've pulled down the latest master and using that I no longer receive the endpoint error message above. However, it says it is successful but the AWS Lambda console does not show the event source and nor does the Lambda react to the event as expected. I've gone through all the versions of the function and none of them are currently associated with any events, at least on the AWS Lambda console.

I can report separately if master is supposed to be stable or let me know if you want me to check on another branch.

**Comment by eahefnawy** [comment]
@c-knowles have you checked the lambda aliases as well? (not just versions) ... I know that an alias is supposed to point to a version, however I noticed that the AWS Console can treat them differently. So if you deployed to `dev` stage, could you click on the `dev` alias for your lambda in the AWS Console and let us know if u can see it?

**Comment by c-knowles** [comment]
@eahefnawy Ah ha! Well that is an odd AWS console behaviour. It is correctly enable for the alias but does not show on the version. Please ignore my second comment about the Lambda not reacting as expected, that was my fault.

Thanks a lot for your help. I will lookout for the next version - do you know if those changes will make their way into a patch for 0.5 or only from 0.6+?

**Comment by eahefnawy** [comment]
@c-knowles yeah I was super confused by that too! We'll push a patch release this week.

Thanks for reach out! :blush:  If you have any other issues, just ping me ;)
