### ISSUE TITLE
Exception when upgrade from 0.4.2. to 0.5.0

### ISSUE THREAD

**Issue by JamieCressey** [serverless/serverless#882]
To upgrade I have ran;

```
nvm use stable
npm update -g serverless
```

Removed all `s-component.json` files, moved the runtime setting to each `s-function.json` and ensured all my functions are uniquely named. However when I try to run any `sls` command I get:

```
/Users/Jamie/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

TypeError: Cannot read property 'getName' of undefined
    at Project.setResources (/Users/Jamie/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/lib/Project.js:196:31)
    at /Users/Jamie/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/lib/Serializer.js:135:19
From previous event:
    at Project.deserializeProject (/Users/Jamie/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/lib/Serializer.js:134:10)
    at Project.deserialize (/Users/Jamie/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/lib/Serializer.js:26:57)
    at Project.load (/Users/Jamie/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/lib/Project.js:35:19)
    at /Users/Jamie/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/lib/Serverless.js:88:35
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at Serverless.init (/Users/Jamie/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/lib/Serverless.js:80:10)
    at Object.<anonymous> (/Users/Jamie/.nvm/versions/node/v5.9.1/lib/node_modules/serverless/bin/serverless:17:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3
```

Is there something I have missed?

**Comment by jellegerbrandy** [comment]
similar issue here. My error is somewhat different.

I believe i have followed all instructions in the release notes, but even if I missed something, a more informative error message would be helpful resolving the issue.

```
/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1251:7)
    at module.exports (/home/jelle/projects_active/backfeed/protocol-service/node_modules/serverless-lambda-prune-plugin/index.js:5:26)
    at Serverless._loadPlugins (/usr/lib/node_modules/serverless/lib/Serverless.js:286:25)
    at Serverless.loadProjectPlugins (/usr/lib/node_modules/serverless/lib/Serverless.js:240:10)
    at /usr/lib/node_modules/serverless/lib/Serverless.js:77:41
From previous event:
    at Serverless.init (/usr/lib/node_modules/serverless/lib/Serverless.js:73:25)
    at Object.<anonymous> (/usr/lib/node_modules/serverless/bin/serverless:17:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3
```

**Comment by jordanmack** [comment]
@JamieCressey Could you run `sls --debug` to see if we can get some additional information?

**Comment by jordanmack** [comment]
@jellegerbrandy I think your problem might be related to the `serverless-lambda-prune-plugin`. The author may not have updated it for full compatibility with v0.5. I would recommend you try disabling it in `s-project.json` to see if that helps.

**Comment by abelsky** [comment]
I also ran into `TypeError: Cannot read property 'getName' of undefined` while upgrading from 0.3.1 to 0.5.1.
I moved **_./cloudformation/resources-cf.json_** to **_./s-resources-cf.json_**, and this resolved the issue for me.

**Comment by eahefnawy** [comment]
Could you show us your directory structure? Also please keep in mind that we've removed the nested resources functionality. Your `s-resources-cf.json` file must be in the project root. We probably forgot to mention this one in the release notes, really sorry :/

**Comment by JamieCressey** [comment]
Yep, `s-resources-cf.json` was the problem - for some reason my CF config was still within `s-project.json`!

Thanks for the help
