### ISSUE TITLE
Silent failure of Serverless deploy

### ISSUE THREAD

**Issue by dgrenner** [serverless/serverless#8839]
With large files and slow/unstable network, Serverless fails to deploy stack without causing error status code or error message.
I have only seen it when deploying to AWS CN. 

It is partially dependent on environment variable <code>AWS_CLIENT_TIMEOUT</code>, large values makes it less frequent. For the example below I have set <code>AWS_CLIENT_TIMEOUT=10</code> to make it easier to reproduce, but it still happens with default (or larger than default) values.
It does not happen if uploaded file is too small, so to test you can add any large file to the project folder (to test I used a movie file I had, about 48 MB). Smaller files (5-10 MB) also trigger this problem.

The critical part is not that the upload times out or fails, it is that there is no error code or error message. When put into a deployment pipeline it then looks like deployment worked without any problems. 

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: myproject
frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: cn-north-1

functions:
  hello:
    handler: handler.hello
```

</details>

<details>
<summary><b><code>export AWS_CLIENT_TIMEOUT=10; SLS_DEBUG=* ../../node_modules/.bin/serverless deploy</code> output</b></summary>

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 200 1.258s 0 retries] describeStacks({ StackName: 'myproject-dev' })
Serverless: [AWS cloudformation 200 1.639s 0 retries] describeStackResource({
  StackName: 'myproject-dev',
  LogicalResourceId: 'ServerlessDeploymentBucket'
})
Serverless: [AWS s3 200 1.518s 0 retries] listObjectsV2({
  Bucket: 'myproject-dev-serverlessdeploymentbucket-ayafrv4s2ty9',
  Prefix: 'serverless/myproject/dev'
})
Serverless: [AWS s3 200 1.223s 0 retries] headObject({
  Bucket: 'myproject-dev-serverlessdeploymentbucket-ayafrv4s2ty9',
  Key: 'serverless/myproject/dev/1611684988009-2021-01-26T18:16:28.009Z/compiled-cloudformation-template.json'
})
Serverless: [AWS lambda 404 1.371s 0 retries] getFunction({ FunctionName: 'myproject-dev-hello' })
Serverless: [AWS sts 200 1.387s 0 retries] getCallerIdentity({})
Serverless: Uploading CloudFormation file to S3...
Serverless: [AWS s3 200 1.279s 0 retries] putObject({
  Body: <Buffer 7b 22 41 57 53 54 65 6d 70 6c 61 74 65 46 6f 72 6d 61 74 56 65 72 73 69 6f 6e 22 3a 22 32 30 31 30 2d 30 39 2d 30 39 22 2c 22 44 65 73 63 72 69 70 74 ... 2611 more bytes>,
  Bucket: 'myproject-dev-serverlessdeploymentbucket-ayafrv4s2ty9',
  Key: 'serverless/myproject/dev/1611685045928-2021-01-26T18:17:25.928Z/compiled-cloudformation-template.json',
  ContentType: 'application/json',
  Metadata: { filesha256: '4QjwYux9cZLlJCWZp1iRQK/Gfu4YbEtHOv8nSifHZ0k=' }
})
Serverless: Uploading artifacts...
Serverless: Uploading service myproject.zip file to S3 (45.72 MB)...
Serverless: [AWS s3 200 1.293s 0 retries] createMultipartUpload({
  Bucket: 'myproject-dev-serverlessdeploymentbucket-ayafrv4s2ty9',
  Key: 'serverless/myproject/dev/1611685045928-2021-01-26T18:17:25.928Z/myproject.zip',
  ContentType: 'application/zip',
  Metadata: { filesha256: 'RO0zY/mKJWYrYklD1X8wUIIZb8gVQBngmKxkZvgXLCQ=' }
})
Serverless: [AWS s3 undefined 13.585s 3 retries] uploadPart({
  Body: <Buffer 16 cc 31 bc 27 30 70 99 b6 ee 08 09 a6 bd 18 cb aa b3 06 21 6d c8 fc 1b 2f 57 47 af e8 a4 81 7c c2 5f c9 e6 16 d2 fe 18 be 50 37 a6 b8 bb 31 35 31 59 ... 5242830 more bytes>,
  ContentLength: 5242880,
  PartNumber: 3,
  Bucket: 'myproject-dev-serverlessdeploymentbucket-ayafrv4s2ty9',
  Key: 'serverless/myproject/dev/1611685045928-2021-01-26T18:17:25.928Z/myproject.zip',
  UploadId: 'KfGGAI5wuSkg4PiNsCJOyTwB2JmOJZ3JWV87cefOpamFCvScSQfcq_whIkmhluH7zByUQofVli8MGcRNRqhEkdr6vKc7s7jkXpSSeteE7S7PrA7STI6E60W3msZnnzScGzE4ePpQIV7AGemE334Fet1OUjWDJVS9MnxhAAIi3To-'
})
Serverless: Recoverable error occurred (Connection timed out after 1000ms), sleeping for ~7 seconds. Try 1 of 4
Serverless: [AWS s3 204 1.562s 0 retries] abortMultipartUpload({
  Bucket: 'myproject-dev-serverlessdeploymentbucket-ayafrv4s2ty9',
  Key: 'serverless/myproject/dev/1611685045928-2021-01-26T18:17:25.928Z/myproject.zip',
  UploadId: 'KfGGAI5wuSkg4PiNsCJOyTwB2JmOJZ3JWV87cefOpamFCvScSQfcq_whIkmhluH7zByUQofVli8MGcRNRqhEkdr6vKc7s7jkXpSSeteE7S7PrA7STI6E60W3msZnnzScGzE4ePpQIV7AGemE334Fet1OUjWDJVS9MnxhAAIi3To-'
})
```

</details>

<b>Installed version</b>

```
Framework Core: 2.21.0 (local)
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.5.1
```

**Comment by pgrzesik** [comment]
Hello @dgrenner, thanks a lot for reporting. This is something that might've been missed previously, we'll definitely look into it. Additionally, we'd be happy to accept a PR with a potential fix for this issue :tada:

**Comment by ash47** [comment]
I still experience this bug all the time, I wouldn't have used serverless if I knew this was going to be an issue. As my stack grew larger, it would take many many retries to get it to deploy. Right now I am stuck unable to deploy changes to my stack as a result of this bug, and I am googling how to fix it, I have arrived here.

**Comment by dgrenner** [comment]
The work-around that has helped was to reduce the network time. For deployments to China we first copy files to S3 bucket in same region where we want to deploy. Then we deploy from there.

**Comment by ash47** [comment]
I just wanted to add, I solved this on my side by updating to the newest
version of nodejs.

**Comment by pgrzesik** [comment]
Thanks for sharing a potential workaround @dgrenner and @ash47 - so it seems the issue in general is caused by slow network, right?

**Comment by ash47** [comment]
Hi Piotr, I have a 100/40 connection, my connection is not slow, perhaps
it's slow on the other side?

If there are any commands or variables I can set to view the speed I'm
happy to look /share results.

Please advise.

**Comment by pgrzesik** [comment]
@ash47 Could you share the output that you're seeing on your side when you experience this bug? Maybe it's caused by something else in your case

**Comment by ash47** [comment]
I reviewed the code myself, i've tracked it as far as:
`node_modules\serverless\lib\plugins\aws\deploy\lib\uploadArtifacts.js`

There is a function called:

`async uploadZipFile(artifactFilePath) {`

It hangs on the following line:

`const response = await this.provider.request('S3', 'upload', params);`

The code in this function is actually super silly to start with, we have a bunch of redudent code and even a bunch of "TODO" code.

I got it working much more reliably by removing the use of:

`const artifactStream = fs.createReadStream(artifactFilePath);`

/\ Right above that, we actually read the entire data into memory:

`const data = fs.readFileSync(artifactFilePath);`

And then as an "optimisation" we attempt to use a readStream to read it again?!?

I killed the code dealing with the read stream and changed

`Body: artifactStream,`

to:

`Body: data,`

And removed all the references to streamError:

`if (streamError) throw streamError;`

I still need to trace where the code for the following is to figure out exactly what's hanging in it:

`const response = await this.provider.request('S3', 'upload', params);`

With regards to your request for output, is there some command or option to capture more verbose output?

**Comment by pgrzesik** [comment]
Hello @ash47, thanks for posting your findings. I don't see "a bunch of TODO code" - there are some explanations in form of comments and a "TODO" marker that logic that loads the whole file into memory should be refactored to use util for computing checksum `getHashForFilePath` - it should actually never load the whole file into memory. Anyway, I'm not sure if changing the logic as you outlined improves anything in regard to the mentioned bug? Is that what you've observed? 

As for the verbose output - yes, you can use `SLS_DEBUG=*` env var and `--verbose` flag to get more detailed output.

**Comment by neetesh1996** [comment]
Pease check below error


```
apple@Apples-MacBook-Pro be-arkihive-vendor-v1 % serverless deploy --stage dev          
Running "serverless" from node_modules

Deploying stackname to stage dev (ap-south-1)


[ LayersPlugin ]: => common
... ○ Downloading ./package.json from bucket...
... ○ ./package.json AWS profile "profile" doesn't seem to be configured.
... ○  Changes identified ! Re-installing...
... ∅ [warning] ".npmrc" file does not exists!
... ∅ [warning] "yarn.lock" file does not exists!
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
.git can't be found (see https://git.io/Jc3F9)
npm ERR! code 1
npm ERR! path /Users/apple/Desktop/arkihive/be-arkihive-vendor-v1/.serverless/layers/nodejs
npm ERR! command failed
npm ERR! command sh -c husky install

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2022-02-13T08_55_36_762Z-debug.log

✖ Stack arkihive-vendor-user failed to deploy (3s)
Environment: darwin, node 14.18.1, framework 3.2.0 (local) 3.1.1v (global), plugin 6.0.0, SDK 4.3.1
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: Command failed: npm install --production --only=prod
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
.git can't be found (see https://git.io/Jc3F9)
npm ERR! code 1
npm ERR! path /Users/apple/Desktop/arkihive/be-arkihive-vendor-v1/.serverless/layers/nodejs
npm ERR! command failed
npm ERR! command sh -c husky install

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2022-02-13T08_55_36_762Z-debug.log

    at checkExecSyncError (child_process.js:790:11)
    at execSync (child_process.js:863:15)
    at /Users/apple/Desktop/arkihive/be-arkihive-vendor-v1/node_modules/cli-progress-footer/lib/private/cli-progress-footer/disable-props.js:86:41
    at handleSubProcessSync (/Users/apple/Desktop/arkihive/be-arkihive-vendor-v1/node_modules/cli-progress-footer/lib/private/cli-progress-footer/disable-props.js:30:36)
    at childProcess.execSync (/Users/apple/Desktop/arkihive/be-arkihive-vendor-v1/node_modules/cli-progress-footer/lib/private/cli-progress-footer/disable-props.js:85:11)
    at Dependencies._callee$ (/Users/apple/Desktop/arkihive/be-arkihive-vendor-v1/node_modules/serverless-layers/lib/package/Dependencies.js:86:26)
    at tryCatch (/Users/apple/Desktop/arkihive/be-arkihive-vendor-v1/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/apple/Desktop/arkihive/be-arkihive-vendor-v1/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/Users/apple/Desktop/arkihive/be-arkihive-vendor-v1/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/Users/apple/Desktop/arkihive/be-arkihive-vendor-v1/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/apple/Desktop/arkihive/be-arkihive-vendor-v1/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /Users/apple/Desktop/arkihive/be-arkihive-vendor-v1/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Dependencies.<anonymous> (/Users/apple/Desktop/arkihive/be-arkihive-vendor-v1/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
    at Dependencies.run (/Users/apple/Desktop/arkihive/be-arkihive-vendor-v1/node_modules/serverless-layers/lib/package/Dependencies.js:102:21)
    at Dependencies._callee2$ (/Users/apple/Desktop/arkihive/be-arkihive-vendor-v1/node_modules/serverless-layers/lib/package/Dependencies.js:199:29)
    at tryCatch (/Users/apple/Desktop/arkihive/be-arkihive-vendor-v1/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/apple/Desktop/arkihive/be-arkihive-vendor-v1/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/Users/apple/Desktop/arkihive/be-arkihive-vendor-v1/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/Users/apple/Desktop/arkihive/be-arkihive-vendor-v1/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/apple/Desktop/arkihive/be-arkihive-vendor-v1/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)

3 depre
```

**Comment by pgrzesik** [comment]
Hello @neetesh1996 - this doesn't look like it's related to this original issue - in the output you've pasted there's an error that `.git` can't be found along with a link - it seems like your `husky` config might be invalid.
