### ISSUE TITLE
CREATE_FAILED error not shown in serverless output.

### ISSUE THREAD

**Issue by sblask** [serverless/serverless#8848]
We are using serverless in combination with aws-vault which we use to assume a role in a different account. The serverless stage corresponds to the account we want to deploy to. Unfortunately we still have to pass in `--stage` as accountId is not available to defer it automatically. So potentially someone can have assumed a role in account A, but passes in stage for account B. To avoid that I have the accountId in the stage config and use it for in the lambda role. So if stage doesn't match the assumed role I should get an error. However, the stack creation fails and serverless doesn't provide an error. The stack is no longer there once it's finished, but checking while serverless is running, I saw there is a CREATE_FAILED event with:

```
Cross-account pass role is not allowed. (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException
```

But serverless doesn't show the error even when I use `--verbose`

<details>
<summary><code>serverless.yml</code></summary>

```yaml
custom:
  env: ${file(env/${self:provider.stage}.yml)}

provider:
  name: aws
  runtime: python3.7
  region: ${self:custom.env.region}
  stage: ${opt:stage}
  role: arn:aws:iam::111111111111:role/rta-execution-role # wrong accountId to trigger the problem
```

</details>

<details>
<summary><b><code>SLS_DEBUG=* sls deploy --stage preview --verbose</code> output</b></summary>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^1.83.2")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command prune
Serverless: Load command requirements
Serverless: Load command requirements:clean
Serverless: Load command requirements:install
Serverless: Load command requirements:cleanCache
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
Serverless: [AWS cloudformation 200 0.405s 0 retries] describeStacks({ StackName: 'aws-environment-outputs' })
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Generated requirements from /Users/sebastian/Clones/rta/requirements-lambda.txt in /Users/sebastian/Clones/rta/.serverless/requirements.txt...
Serverless: Using static cache of requirements found at /Users/sebastian/Library/Caches/serverless-python-requirements/e0be04c1f4791a02113fa396030edfd8_slspyc ...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Injecting required Python packages to package...
Serverless: Invoke aws:package:finalize
AWS Pseudo Parameters
Skipping automatic replacement of regions with account region!
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: [AWS s3 200 0.221s 0 retries] getBucketLocation({ Bucket: 'serverless.preview.montoux.net' })
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 400 0.21s 0 retries] describeStacks({ StackName: 'rta-preview' })
Serverless: [AWS s3 200 0.534s 0 retries] listObjectsV2({
  Bucket: 'serverless.preview.montoux.net',
  Prefix: 'serverless/rta/preview'
})
Serverless: [AWS s3 200 0.209s 0 retries] headObject({
  Bucket: 'serverless.preview.montoux.net',
  Key: 'serverless/rta/preview/1611873724564-2021-01-28T22:42:04.564Z/compiled-cloudformation-template.json'
})
Serverless: [AWS s3 200 0.221s 0 retries] headObject({
  Bucket: 'serverless.preview.montoux.net',
  Key: 'serverless/rta/preview/1611873724564-2021-01-28T22:42:04.564Z/query.zip'
})
Serverless: [AWS lambda 404 2.57s 0 retries] getFunction({ FunctionName: 'rta-preview-query' })
Serverless: [AWS sts 200 1.03s 0 retries] getCallerIdentity({})
Serverless: Uploading CloudFormation file to S3...
Serverless: [AWS s3 200 0.23s 0 retries] putObject({
  Body: <Buffer 7b 22 41 57 53 54 65 6d 70 6c 61 74 65 46 6f 72 6d 61 74 56 65 72 73 69 6f 6e 22 3a 22 32 30 31 30 2d 30 39 2d 30 39 22 2c 22 44 65 73 63 72 69 70 74 ... 1277 more bytes>,
  Bucket: 'serverless.preview.montoux.net',
  Key: 'serverless/rta/preview/1611874675727-2021-01-28T22:57:55.727Z/compiled-cloudformation-template.json',
  ContentType: 'application/json',
  Metadata: { filesha256: '386diQ612VKUETQye2VXa2EvrOKanIETmQ8NLyKZhgQ=' }
})
Serverless: Uploading artifacts...
Serverless: Uploading service query.zip file to S3 (47.64 MB)...
Serverless: [AWS s3 200 0.259s 0 retries] createMultipartUpload({
  Bucket: 'serverless.preview.montoux.net',
  Key: 'serverless/rta/preview/1611874675727-2021-01-28T22:57:55.727Z/query.zip',
  ContentType: 'application/zip',
  Metadata: { filesha256: 'yXGPfFfMOMx+AoPm5W6c9Xtz+5zsxaDFYQBqMpyNtoI=' }
})
Serverless: [AWS s3 200 6.924s 0 retries] uploadPart({
  Body: <Buffer 50 4b 03 04 0a 00 00 00 08 00 00 00 21 00 0a 02 a4 45 f3 01 00 00 d8 03 00 00 0e 00 00 00 2e 67 69 74 6c 61 62 2d 63 69 2e 79 6d 6c a5 52 dd 6f da 30 ... 5242830 more bytes>,
  ContentLength: 5242880,
  PartNumber: 1,
  Bucket: 'serverless.preview.montoux.net',
  Key: 'serverless/rta/preview/1611874675727-2021-01-28T22:57:55.727Z/query.zip',
  UploadId: 'YljBkSL5F2F2RHf4ucrXrkX9v22GRXqBG9egVDx6lCxFq9Gtijih65E8QZmE_1G3KJHPEae2Us1F4ccs6HpTPQkdM0wz2tmj4HicVDr4MtZwTIzHQxaB9ukTxSxuMk2Rk5B87u8jSUn4StSDJaPlkLN.iqHTnD1YuMSkEzsoGEs-'
})
Serverless: [AWS s3 200 7.13s 0 retries] uploadPart({
  Body: <Buffer 69 27 d0 e4 aa 34 87 fa a2 fe ff 44 50 5f a4 cf df 2e fd 8a c9 ff 11 b0 b1 d4 fa 5d a7 07 81 22 7a fd ae 19 5e 37 d7 ef 9a 13 12 a1 7e 17 7f 37 ea 77 ... 5242830 more bytes>,
  ContentLength: 5242880,
  PartNumber: 3,
  Bucket: 'serverless.preview.montoux.net',
  Key: 'serverless/rta/preview/1611874675727-2021-01-28T22:57:55.727Z/query.zip',
  UploadId: 'YljBkSL5F2F2RHf4ucrXrkX9v22GRXqBG9egVDx6lCxFq9Gtijih65E8QZmE_1G3KJHPEae2Us1F4ccs6HpTPQkdM0wz2tmj4HicVDr4MtZwTIzHQxaB9ukTxSxuMk2Rk5B87u8jSUn4StSDJaPlkLN.iqHTnD1YuMSkEzsoGEs-'
})
Serverless: [AWS s3 200 7.853s 0 retries] uploadPart({
  Body: <Buffer df c9 fe fe cf 71 ef ef 6d fe e9 ee 69 26 ff 94 de 94 58 af 45 89 ab eb 3f b0 be 33 93 1f 3b 50 fb 5e e7 c7 06 b2 f8 0a 1f e7 e3 0b b2 c7 d7 d8 16 1f ... 5242830 more bytes>,
  ContentLength: 5242880,
  PartNumber: 2,
  Bucket: 'serverless.preview.montoux.net',
  Key: 'serverless/rta/preview/1611874675727-2021-01-28T22:57:55.727Z/query.zip',
  UploadId: 'YljBkSL5F2F2RHf4ucrXrkX9v22GRXqBG9egVDx6lCxFq9Gtijih65E8QZmE_1G3KJHPEae2Us1F4ccs6HpTPQkdM0wz2tmj4HicVDr4MtZwTIzHQxaB9ukTxSxuMk2Rk5B87u8jSUn4StSDJaPlkLN.iqHTnD1YuMSkEzsoGEs-'
})
Serverless: [AWS s3 200 6.654s 0 retries] uploadPart({
  Body: <Buffer cf 26 e8 86 b3 6e 0a 8c 5e 81 e2 d0 21 32 3a f5 d6 32 8d f4 34 14 4e 56 fc a5 dd 0b 1a 69 21 14 9d 58 f1 67 24 29 87 e2 85 83 94 64 1a 14 f9 50 dc ce ... 5242830 more bytes>,
  ContentLength: 5242880,
  PartNumber: 5,
  Bucket: 'serverless.preview.montoux.net',
  Key: 'serverless/rta/preview/1611874675727-2021-01-28T22:57:55.727Z/query.zip',
  UploadId: 'YljBkSL5F2F2RHf4ucrXrkX9v22GRXqBG9egVDx6lCxFq9Gtijih65E8QZmE_1G3KJHPEae2Us1F4ccs6HpTPQkdM0wz2tmj4HicVDr4MtZwTIzHQxaB9ukTxSxuMk2Rk5B87u8jSUn4StSDJaPlkLN.iqHTnD1YuMSkEzsoGEs-'
})
Serverless: [AWS s3 200 9.152s 0 retries] uploadPart({
  Body: <Buffer 27 73 83 f7 19 2a 48 18 13 0b 30 ed e2 44 16 29 c8 64 91 62 c6 b2 3e 1b cd e8 87 70 7e 80 ad dc 9e c4 34 d7 a3 df 60 72 49 c7 32 ad d7 b1 62 72 15 1b ... 5242830 more bytes>,
  ContentLength: 5242880,
  PartNumber: 4,
  Bucket: 'serverless.preview.montoux.net',
  Key: 'serverless/rta/preview/1611874675727-2021-01-28T22:57:55.727Z/query.zip',
  UploadId: 'YljBkSL5F2F2RHf4ucrXrkX9v22GRXqBG9egVDx6lCxFq9Gtijih65E8QZmE_1G3KJHPEae2Us1F4ccs6HpTPQkdM0wz2tmj4HicVDr4MtZwTIzHQxaB9ukTxSxuMk2Rk5B87u8jSUn4StSDJaPlkLN.iqHTnD1YuMSkEzsoGEs-'
})
Serverless: [AWS s3 200 8.389s 0 retries] uploadPart({
  Body: <Buffer 39 57 cb 93 66 ca 6b 42 bd 2e 37 2e 60 c0 6f 04 b3 90 c6 2c 54 60 c0 ef 70 cc c2 28 dc 3f bf 53 1b 66 37 4d 6e 99 e3 d6 9d 2c f4 0a 4e 6c 59 69 32 fa ... 5242830 more bytes>,
  ContentLength: 5242880,
  PartNumber: 7,
  Bucket: 'serverless.preview.montoux.net',
  Key: 'serverless/rta/preview/1611874675727-2021-01-28T22:57:55.727Z/query.zip',
  UploadId: 'YljBkSL5F2F2RHf4ucrXrkX9v22GRXqBG9egVDx6lCxFq9Gtijih65E8QZmE_1G3KJHPEae2Us1F4ccs6HpTPQkdM0wz2tmj4HicVDr4MtZwTIzHQxaB9ukTxSxuMk2Rk5B87u8jSUn4StSDJaPlkLN.iqHTnD1YuMSkEzsoGEs-'
})
Serverless: [AWS s3 200 10.169s 0 retries] uploadPart({
  Body: <Buffer f5 08 e4 c7 fb 87 5d 73 23 81 7e 1c 11 f4 d9 37 e9 db 6e ba e3 49 bb 5b 73 a7 bd e5 8e 39 23 e4 75 32 fe f9 ef 43 e4 7b 26 b8 6f c5 14 79 5e a1 f6 0f ... 5242830 more bytes>,
  ContentLength: 5242880,
  PartNumber: 6,
  Bucket: 'serverless.preview.montoux.net',
  Key: 'serverless/rta/preview/1611874675727-2021-01-28T22:57:55.727Z/query.zip',
  UploadId: 'YljBkSL5F2F2RHf4ucrXrkX9v22GRXqBG9egVDx6lCxFq9Gtijih65E8QZmE_1G3KJHPEae2Us1F4ccs6HpTPQkdM0wz2tmj4HicVDr4MtZwTIzHQxaB9ukTxSxuMk2Rk5B87u8jSUn4StSDJaPlkLN.iqHTnD1YuMSkEzsoGEs-'
})
Serverless: [AWS s3 200 4.594s 0 retries] uploadPart({
  Body: <Buffer 76 a6 2d b7 ff 70 39 ca ec 8a ee bc fd a6 7e 8e e0 2e 56 a6 a1 3f f6 8e d6 41 06 0c 8d 76 79 27 11 41 39 48 af ea c3 5f 2f a6 2d ba a6 d5 5b 47 14 86 ... 2770285 more bytes>,
  ContentLength: 2770335,
  PartNumber: 10,
  Bucket: 'serverless.preview.montoux.net',
  Key: 'serverless/rta/preview/1611874675727-2021-01-28T22:57:55.727Z/query.zip',
  UploadId: 'YljBkSL5F2F2RHf4ucrXrkX9v22GRXqBG9egVDx6lCxFq9Gtijih65E8QZmE_1G3KJHPEae2Us1F4ccs6HpTPQkdM0wz2tmj4HicVDr4MtZwTIzHQxaB9ukTxSxuMk2Rk5B87u8jSUn4StSDJaPlkLN.iqHTnD1YuMSkEzsoGEs-'
})
Serverless: [AWS s3 200 6.621s 0 retries] uploadPart({
  Body: <Buffer 4f c3 ec f6 74 57 55 d7 d5 55 d5 bd 33 2d d5 03 c3 e5 4d 44 31 4b 5a 20 e9 49 f6 c3 46 2e 5e 03 fc 81 7b bb fd 0f a9 e7 ed d6 ba e1 bd 8a 42 da c4 5e ... 5242830 more bytes>,
  ContentLength: 5242880,
  PartNumber: 9,
  Bucket: 'serverless.preview.montoux.net',
  Key: 'serverless/rta/preview/1611874675727-2021-01-28T22:57:55.727Z/query.zip',
  UploadId: 'YljBkSL5F2F2RHf4ucrXrkX9v22GRXqBG9egVDx6lCxFq9Gtijih65E8QZmE_1G3KJHPEae2Us1F4ccs6HpTPQkdM0wz2tmj4HicVDr4MtZwTIzHQxaB9ukTxSxuMk2Rk5B87u8jSUn4StSDJaPlkLN.iqHTnD1YuMSkEzsoGEs-'
})
Serverless: [AWS s3 200 9.882s 0 retries] uploadPart({
  Body: <Buffer 16 c1 9f a2 3d 0f 1e 27 79 8a 5c 14 1c 7c 4b e8 c1 7a ff 2d 61 84 98 73 30 0f e7 22 c8 03 ed bf 6a 60 78 a8 ee bf 22 3c 92 b5 e7 c1 3b 0f 9a 8b 82 ea ... 5242830 more bytes>,
  ContentLength: 5242880,
  PartNumber: 8,
  Bucket: 'serverless.preview.montoux.net',
  Key: 'serverless/rta/preview/1611874675727-2021-01-28T22:57:55.727Z/query.zip',
  UploadId: 'YljBkSL5F2F2RHf4ucrXrkX9v22GRXqBG9egVDx6lCxFq9Gtijih65E8QZmE_1G3KJHPEae2Us1F4ccs6HpTPQkdM0wz2tmj4HicVDr4MtZwTIzHQxaB9ukTxSxuMk2Rk5B87u8jSUn4StSDJaPlkLN.iqHTnD1YuMSkEzsoGEs-'
})
Serverless: [AWS s3 200 0.35s 0 retries] completeMultipartUpload({
  MultipartUpload: {
    Parts: [
      { ETag: '"5ca418928f2f749b6f44d067eeff826d"', PartNumber: 1 },
      { ETag: '"6b8ec0a566b521b8efdf4970abf75b35"', PartNumber: 2 },
      { ETag: '"a16d82900b0c8b67bc2ce0883889d6e9"', PartNumber: 3 },
      { ETag: '"d90ed968d05aa9ff5d2ad64f72163988"', PartNumber: 4 },
      { ETag: '"e1320f5d6934c29ee01d259ea371c139"', PartNumber: 5 },
      { ETag: '"7404a30b9d472e0a609a4bab45f6ab2d"', PartNumber: 6 },
      { ETag: '"744993241e785abc5b4d7679c4b686ae"', PartNumber: 7 },
      { ETag: '"b7b24fdb3ecd3c2395c297fe18772853"', PartNumber: 8 },
      { ETag: '"74e50df7edf23e3bdf7e4b6ed11e428c"', PartNumber: 9 },
      { ETag: '"61cfa34fa72f1d5e6b259aeb7b0f09df"', PartNumber: 10 },
      [length]: 10
    ]
  },
  Bucket: 'serverless.preview.montoux.net',
  Key: 'serverless/rta/preview/1611874675727-2021-01-28T22:57:55.727Z/query.zip',
  UploadId: 'YljBkSL5F2F2RHf4ucrXrkX9v22GRXqBG9egVDx6lCxFq9Gtijih65E8QZmE_1G3KJHPEae2Us1F4ccs6HpTPQkdM0wz2tmj4HicVDr4MtZwTIzHQxaB9ukTxSxuMk2Rk5B87u8jSUn4StSDJaPlkLN.iqHTnD1YuMSkEzsoGEs-'
})
Serverless: Validating template...
Serverless: [AWS cloudformation 200 0.349s 0 retries] validateTemplate({
  TemplateURL: 'https://s3.amazonaws.com/serverless.preview.montoux.net/serverless/rta/preview/1611874675727-2021-01-28T22:57:55.727Z/compiled-cloudformation-template.json'
})
Serverless: Creating Stack...
Serverless: [AWS cloudformation 200 0.484s 0 retries] createStack({
  StackName: 'rta-preview',
  OnFailure: 'DELETE',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL: 'https://s3.amazonaws.com/serverless.preview.montoux.net/serverless/rta/preview/1611874675727-2021-01-28T22:57:55.727Z/compiled-cloudformation-template.json',
  Tags: [ { Key: 'STAGE', Value: 'preview' }, [length]: 1 ]
})
Serverless: Checking Stack create progress...
Serverless: [AWS cloudformation 200 0.213s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:ap-southeast-2:542502350085:stack/rta-preview/54500b90-61bc-11eb-ad1e-068e268722ac'
})
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - rta-preview
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - QueryLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - QueryLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - QueryLogGroup
Serverless: [AWS cloudformation 200 0.261s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:ap-southeast-2:542502350085:stack/rta-preview/54500b90-61bc-11eb-ad1e-068e268722ac'
})
CloudFormation - DELETE_IN_PROGRESS - AWS::CloudFormation::Stack - rta-preview
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Function - QueryLambdaFunction
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - QueryLogGroup
Serverless: [AWS cloudformation 200 0.219s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:ap-southeast-2:542502350085:stack/rta-preview/54500b90-61bc-11eb-ad1e-068e268722ac'
})
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - QueryLogGroup
CloudFormation - DELETE_COMPLETE - AWS::CloudFormation::Stack - rta-preview
Serverless: Stack create finished...
Serverless: Invoke aws:info
Serverless: [AWS cloudformation 400 0.203s 0 retries] describeStacks({ StackName: 'rta-preview' })

  Serverless Error ---------------------------------------

  ServerlessError: Stack with id rta-preview does not exist
      at /Users/sebastian/Clones/rta/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:622:27
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.7.0
     Framework Version:         2.21.1
     Plugin Version:            4.4.2
     SDK Version:               2.3.2
     Components Version:        3.6.0
```

</details>

<b>Installed version</b>

```
Framework Core: 2.21.1
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.6.0

```

**Comment by pgrzesik** [comment]
Hello @sblask, thanks a lot for reporting. I've setup the following example locally to debug/reproduce the issue you're experiencing:

```
frameworkVersion: '2'
service: servicename

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  role: arn:aws:iam::111111111111:role/rta-execution-role


functions:
  hello:
    handler: index.handler
```

I was not able to reproduce the issue in two following scenarios:
- Deploying a fresh service
- Updating an existing service (I've deployed a version without `role` set and later tried to update with role)

In both cases, `sls deploy` resulted in the following error:

```
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
....
Serverless: Operation failed!
Serverless: View the full error output: https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3A600238737408%3Astack%2Fservicename-dev%2F6fa58140-63b5-11eb-b6a6-12cf4a8c2bc2

  Serverless Error ---------------------------------------

  An error occurred: HelloLambdaFunction - Cross-account pass role is not allowed. (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: 68f416e5-5e4a-41b4-9d74-3cf7ac70f0cd; Proxy: null).

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.15.0
     Framework Version:         2.21.1 (local)
     Plugin Version:            4.4.2
     SDK Version:               2.3.2
     Components Version:        3.5.1
```

Are there any other details specific to your case that I should take into account while reproducing the issue? Thanks in advance :bow:

**Comment by sblask** [comment]
Strange, my setup triggered the problem consistently. The differences I see are: Python lambda vs Node lambda, ap-southeast-2 vs us-east-1 and Mac vs Linux. None of which could explain the problem?

My events look like this:
```

2021-01-29 10:54:00 UTC+1300 | rta-preview | DELETE_COMPLETE | -
-- | -- | -- | --
2021-01-29 10:53:59 UTC+1300 | QueryLogGroup | DELETE_COMPLETE | -
2021-01-29 10:53:58 UTC+1300 | QueryLogGroup | DELETE_IN_PROGRESS | -
2021-01-29 10:53:57 UTC+1300 | QueryLambdaFunction | DELETE_COMPLETE | -
2021-01-29 10:53:54 UTC+1300 | rta-preview | DELETE_IN_PROGRESS | The following resource(s) failed to create: [QueryLambdaFunction]. Delete requested by user.
2021-01-29 10:53:54 UTC+1300 | QueryLambdaFunction | CREATE_FAILED | Cross-account pass role is not allowed. (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: 12ae74e2-f0fa-406b-84a3-da5a46da6f33; Proxy: null)
2021-01-29 10:53:53 UTC+1300 | QueryLambdaFunction | CREATE_IN_PROGRESS | -
2021-01-29 10:53:51 UTC+1300 | QueryLogGroup | CREATE_COMPLETE | -
2021-01-29 10:53:51 UTC+1300 | QueryLogGroup | CREATE_IN_PROGRESS | Resource creation Initiated
2021-01-29 10:53:49 UTC+1300 | QueryLogGroup | CREATE_IN_PROGRESS | -
2021-01-29 10:53:46 UTC+1300 | rta-preview | CREATE_IN_PROGRESS | User Initiated
```
I had a quick look at the code: https://github.com/serverless/serverless/blob/cf7b25e4580290f4f6720a46ba4dbecdaf6e13cf/lib/plugins/aws/lib/monitorStack.js#L34 and If I understand it correctly it can happen that the stack events are checked when I am already in DELETE_COMPLETE and the `slice` would cut off events before DELETE_IN_PROGRESS so the code in here: https://github.com/serverless/serverless/blob/cf7b25e4580290f4f6720a46ba4dbecdaf6e13cf/lib/plugins/aws/lib/monitorStack.js#L40 would never see the CREATE_FAILED? So it's a bit of a timing issue?

**Comment by pgrzesik** [comment]
Thanks for reporting back @sblask. I'm reading the code as well and it seems like it might be a timing issue potentially, however, I've tried to reproduce it with adjusting the frequency via `SLS_AWS_MONITORING_FREQUENCY` and couldn't replicate the problem, even when raising it to 30 seconds. Would you be willing to try out lowering the frequency via this variable to see if the problem persists?

Btw - I've also switched to Mac, Python and `ap-southeast-2` region to eliminate potential issues here (even if they sound highly unlikely).

**Comment by sblask** [comment]
I set SLS_AWS_MONITORING_FREQUENCY to 100 and now I sometimes get the expected error and sometimes I don't. I just saw there is a difference in the node_modules/serverless/lib/plugins/aws/lib/monitorStack.js and https://github.com/serverless/serverless/blob/cf7b25e4580290f4f6720a46ba4dbecdaf6e13cf/lib/plugins/aws/lib/monitorStack.js#L31 The part that I think is relevant looks like this for me:

```
              stackEvents.some((event, index) => {
                if (event.ResourceType !== 'AWS::CloudFormation::Stack') return false;
                if (!processInitializatonStates.has(event.ResourceStatus)) return false;
                stackEvents = stackEvents.slice(0, index + 1);
                return true;
              });

```

My guess now is that I am in DELETE_IN_PROGRESS which means it cuts off there and doesn't see the FAILED. The version on Github checks for the status that corresponds to the action which I think might fix the problem. Now the question is whether you have the version that I am using or the Github version? I did a fresh `npm install`, so I'd expect to be up to date?

**Comment by pgrzesik** [comment]
That's very interesting - it looks like you're using older version of Framework, however, in the listing you provided it was showing as `2.21.1` - can you confirm that you're on that version? The change to that piece of code was introduced with this commit: https://github.com/serverless/serverless/commit/9bc1060dce which I believe was released with `2.16.0`. How are you installing and running `serverless`?

**Comment by sblask** [comment]
I think I can confirm:
```
$ serverless --version
Framework Core: 2.21.1
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.6.0
```

I installed serverless with `$ npm install -g serverless`

But I also found this in my package.json:

```
{
  "name": "rta",
  "version": "1.2.4",
  "description": "Something something",
  "main": "index.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "serverless": "^1.52.2",
    "serverless-prune-plugin": "^1.4.1",
    "serverless-pseudo-parameters": "^2.4.0",
    "serverless-python-requirements": "^4.3.0"
  }
}
```
Does `"serverless": "^1.52.2",` take precedence over the installed version? If yes, would that be a bug in `serverless --version`? Because that should give me exactly what will be used?

**Comment by pgrzesik** [comment]
Hello @sblask, it seems to be the case - when running a global version and local one is detected, the local one will be used for running the command. However, the error handler will incorrectly print out the global version which creates confusion. I've managed to reproduce such scenario using the `package.json` that you posted above. Thanks for helping uncover that bug. 

As for your original issue - do you have the option to try out upgrading the local version or reproducing it with the latest version of the framework?

**Comment by sblask** [comment]
I just removed the dependency to serverless from my package.json and it now works as expected, so I'll close this issue. Had `--version` shown me the old version that would have saved us a lot of time I guess. I remember using `--version` and saw I was not on the latest so I updated and retested before submitting this issue. So it would be great if that could be fixed. Should I create an issue for it, do you want to or is there maybe one already?

**Comment by pgrzesik** [comment]
Thank you @sblask - sorry for the troubles caused by that confusion, proper resolution of `--version` would save us a lot of time indeed. No need to create an issue as I'm wrapping up a PR that should resolve that problem :crossed_fingers:
