### ISSUE TITLE
Unable to create project: Cant find AWS credentials

### ISSUE THREAD

**Issue by keyclipse** [serverless/serverless#887]
Hi guys,
 
I have got a problem creating a project even though i have followed the guide. Can someone help me with this issue?

MacbookPro:Serverless skitono$ serverless project create
 _______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v0.5.0
`-------'

Serverless: Initializing Serverless Project...  
Serverless: Enter a name for this project:  (serverless-e1ka9u) serverlessDemo
Serverless: Enter a new stage name for this project:  serverlessStage
Serverless: For the "serverlessstage" stage, do you want to use an existing Amazon Web Services profile or create a new one?
  > Existing Profile
    Create A New Profile
Serverless: Select a profile for your project: 
  > Samuel Kitono
    default
Serverless: Creating stage "serverlessstage"...  
Serverless: Select a new region for your stage: 
    us-east-1
    us-west-2
    eu-west-1
    eu-central-1
  > ap-northeast-1
Serverless: Creating region "ap-northeast-1" in stage "serverlessstage"...  
Serverless: Deploying resources to stage "serverlessstage" in region "ap-northeast-1" via Cloudformation (~3 minutes)...  
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

ServerlessError: Cant find AWS credentials
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/Error.js:17:11)
    at ServerlessProviderAws.getCredentials (/usr/local/lib/node_modules/serverless/lib/ProviderAws.js:192:15)
    at ServerlessProviderAws.request (/usr/local/lib/node_modules/serverless/lib/ProviderAws.js:59:52)
    at ResourcesDeploy._createOrUpdateResourcesStack (/usr/local/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:285:18)
    at /usr/local/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:186:26
From previous event:
    at ResourcesDeploy._deployResources (/usr/local/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:159:12)
From previous event:
    at ResourcesDeploy.resourcesDeploy (/usr/local/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:73:12)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:206:25
    at Array.reduce (native)
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:205:26)
    at Object.actions.(anonymous function) [as resourcesDeploy] (/usr/local/lib/node_modules/serverless/lib/Serverless.js:424:20)
    at RegionCreate._deployResources (/usr/local/lib/node_modules/serverless/lib/actions/RegionCreate.js:153:24)
From previous event:
    at RegionCreate.regionCreate (/usr/local/lib/node_modules/serverless/lib/actions/RegionCreate.js:81:12)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:206:25
    at Array.reduce (native)
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:205:26)
    at Object.actions.(anonymous function) [as regionCreate] (/usr/local/lib/node_modules/serverless/lib/Serverless.js:424:20)
    at StageCreate._createRegion (/usr/local/lib/node_modules/serverless/lib/actions/StageCreate.js:298:24)
From previous event:
    at StageCreate.stageCreate (/usr/local/lib/node_modules/serverless/lib/actions/StageCreate.js:86:12)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:206:25
    at Array.reduce (native)
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:205:26)
    at Object.actions.(anonymous function) [as stageCreate] (/usr/local/lib/node_modules/serverless/lib/Serverless.js:424:20)
    at ProjectInit._createStageAndRegion (/usr/local/lib/node_modules/serverless/lib/actions/ProjectInit.js:262:24)
    at /usr/local/lib/node_modules/serverless/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:43:10
From previous event:
    at ProjectInit.projectInit (/usr/local/lib/node_modules/serverless/lib/actions/ProjectInit.js:93:10)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:206:25
    at Array.reduce (native)
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:205:26)
    at Object.actions.(anonymous function) [as projectInit] (/usr/local/lib/node_modules/serverless/lib/Serverless.js:424:20)
    at ProjectCreate.createProject (/usr/local/lib/node_modules/serverless/lib/actions/ProjectCreate.js:75:24)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:181:31
    at Array.reduce (native)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:180:32
From previous event:
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:178:12)
    at Serverless.actions.(anonymous function) (/usr/local/lib/node_modules/serverless/lib/Serverless.js:424:20)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:393:38)
    at /usr/local/lib/node_modules/serverless/bin/serverless:19:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3

**Comment by mharris717** [comment]
Which profile did you pick? Does that profile has an entry with valid aws keys in ~/.aws/credentials?

**Comment by ac360** [comment]
Hi @keyclipse.  Make sure your `~/.aws/credentials` file is formatted correctly too.

**Comment by arithmetric** [comment]
@keyclipse I ran into the same error when using a profile with uppercase letters. If I used a profile with only lowercase letters, I could workaround this issue.

I submitted a patch to fix handling of profiles with uppercase letters in #938.

**Comment by adodson** [comment]
I get this error because I have no ~/.aws/credentials. Is it possible to do a serverless deployment without having .aws/credentials?  I set up the project and did initial deployment from my laptop, but now I would like my jenkins host to deploy using the IAM role attached to it.  My jenkins host currently has no IAM user credentials.  Is this possible?

**Comment by benaghaeipour** [comment]
Just had the same error using v0.5.6 but noticed I was missing the admin.env file containing
```
AWS_LIVE_PROFILE=default
```
