### ISSUE TITLE
As of v2.20.0 "serverless remove" requires ECR IAM permissions even if not using lambda container images

### ISSUE THREAD

**Issue by johan1252** [serverless/serverless#8892]
Due to changes that went into https://github.com/serverless/serverless/pull/8725, performing `sls remove` when `provider=aws` now requires ECR read-only permissions.
Specifically the following error will be seen if no ECR permissions are present:
```
ServerlessError: User: arn:aws:iam::<redacted>:user/<redacted> is not authorized to perform: ecr:DescribeRepositories on resource: arn:aws:ecr:us-east-1:<redacted>:repository/serverless-someservice-dev
```

The existence of the ECR repository is checked during the remove stage even if `lambda container images` are never used.
https://github.com/serverless/serverless/blob/7c998e03ca104948c6c2673c9fee6992689219df/lib/plugins/aws/remove/index.js#L28

A user shouldn't need to provide ECR permissions to serverless if they aren't going to be using the lambda container image feature.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: someService

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: us-east-1
```

</details>

<details>
<summary><b><code>serverless remove --stage dev</code> output</b></summary>

```
$ sls remove --stage dev
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Deprecation warning: Serverless constructor expects resolved service configuration path to be provided via "config.configurationPath".
            Starting from next major Serverless will no longer auto resolve that path internally.
            More Info: https://www.serverless.com/framework/docs/deprecations/#MISSING_SERVICE_CONFIGURATION_PATH
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.22.0")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Deprecation warning: Starting with next major version, default value of provider.lambdaHashingVersion will be equal to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Invoke remove
Serverless: [AWS cloudformation 200 0.333s 0 retries] describeStackResource({
  StackName: 'someService-dev',
  LogicalResourceId: 'ServerlessDeploymentBucket'
})
Serverless: Getting all objects in S3 bucket...
Serverless: [AWS sts 200 0.427s 0 retries] getCallerIdentity({})
Serverless: [AWS s3 200 0.494s 0 retries] listObjectsV2({
  Bucket: 'someservice-dev-serverlessdeploymentbucket-1op9n1cge5fgr',
  Prefix: 'serverless/someService/dev'
})
Serverless: Removing objects in S3 bucket...
Serverless: [AWS ecr 400 0.449s 0 retries] describeRepositories({
  repositoryNames: [ 'serverless-someservice-dev', [length]: 1 ],
  registryId: '<redacted>'
})
 
  Serverless Error ---------------------------------------
 
  ServerlessError: User: arn:aws:iam::<redacted>:user/<redacted> is not authorized to perform: ecr:DescribeRepositories on resource: arn:aws:ecr:us-east-1:<redacted>:repository/serverless-someservice-dev
      at /Users/johanc/git/johanc/test/node_modules/serverless/lib/plugins/aws/provider.js:1413:27
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.18.1
     Framework Version:         2.15.0 (standalone)
     Plugin Version:            4.2.0
     SDK Version:               2.3.2
     Components Version:        3.4.3
```

</details>

<b>Installed version</b>

```
2.22.0
```

**Comment by pgrzesik** [comment]
Thanks for reporting @johan1252. I totally agree that we should never break and require ECR-specific permissions for people that never use ECR in their services :100: The selected approach was based on the fact, that there still might be ECR repository created for service, even if `images` are no longer defined in `serverless.yml` file and ECR repository is not managed via CloudFormation. But,as I now see, we will have to adjust that approach. :+1:

**Comment by leidsongermano** [comment]
Hey, version 2.35.0 still with the same issue, tested with localstack 0.12.6.
