### ISSUE TITLE
better warning for normalizedFunctionName

### ISSUE THREAD

**Issue by DanielWarfield1** [serverless/serverless#8910]
Sorry if this is inappropriate, I'm new to open source contribution.

I struggled with debugging this error when mounting EFS to a Lambda function with the serverless framework:

`Every Resources object must contain a Type member`

this was caused by using a non normalized resource name, as described in my stack exchange question [here](https://stackoverflow.com/questions/66094737/serverless-framework-error-every-resources-object-must-contain-a-type-member/66100689#66100689). 

I believe mounting an EFS to Lambda is going to become a very popular use case, especially for ML deployment. I think checking for non-normalized names and improving the output of this error (and potentially other similar errors) would make it much less likely for people pursuing similar use cases, especially for the first time.

**Comment by pgrzesik** [comment]
Hello @DanielWarfield1, thanks a lot for reporting your issue. At the moment, we should have a deprecation being shown in case someone tries to extend a resource that does not exist: https://github.com/serverless/serverless/blob/05f48b6ad1703f69dffc9e6e872c03274e70fae1/lib/plugins/aws/package/lib/mergeCustomProviderResources.js#L35 and we plan to throw errors starting with next major. What version of the framework are you using currently? 

As for EFS support, the recommended way is to use native support: https://www.serverless.com/framework/docs/providers/aws/guide/functions/#efs-configuration

**Comment by DanielWarfield1** [comment]
Here's my environment info

     Operating System:          linux
     Node Version:              10.23.1
     Framework Version:         2.19.0
     Plugin Version:            4.4.2
     SDK Version:               2.3.2
     Components Version:        3.4.7

Also, I'll check out native support. The tutorials I was following are a bit old; excited to try out a cleaner solution.

**Comment by pgrzesik** [comment]
Thank you @DanielWarfield1 - while using `2.19.0`, did you not run into the deprecation warning about referencing nonexistent resources when trying to extend them? You should see a warning and if that wasn't the case, we might have a bug in that logic.

**Comment by DanielWarfield1** [comment]
@pgrzesik, I rolled back the correction and reran it, this was the full output:
```

Serverless: Configuration warning at 'functions.test': unrecognized property 'iamManagedPolicies'
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Deprecation warning: Starting with next major version, default value of provider.lambdaHashingVersion will be equal to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Deprecation warning: Starting with next major version, API Gateway naming will be changed from "{stage}-{service}" to "{service}-{stage}".
            Set "provider.apiGateway.shouldStartNameWithService" to "true" to adapt to the new behavior now.
            More Info: https://www.serverless.com/framework/docs/deprecations/#AWS_API_GATEWAY_NAME_STARTING_WITH_SERVICE
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Deprecation warning: Starting with next major version, extensions to nonexistent resources will throw an error instead of passing silently.
            More Info: https://www.serverless.com/framework/docs/deprecations/#RESOURCES_EXTENSIONS_REFERENCE_TO_NONEXISTENT_RESOURCE
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service test2EFS.zip file to S3 (926 B)...
Serverless: Validating template...
 
  Error --------------------------------------------------
 
  Error: The CloudFormation template is invalid: Template format error: [/Resources/testLambdaFunction] Every Resources object must contain a Type member.
      at provider.request.catch (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:20:13)
      at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:725:18)
      at _drainQueueStep (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              10.23.1
     Framework Version:         2.19.0
     Plugin Version:            4.4.2
     SDK Version:               2.3.2
     Components Version:        3.4.7
```

**Comment by pgrzesik** [comment]
Hello @DanielWarfield1 :wave: Thanks for providing more details. In the listing you showed, there's a deprecation warning:

```
Serverless: Deprecation warning: Starting with next major version, extensions to nonexistent resources will throw an error instead of passing silently.
            More Info: https://www.serverless.com/framework/docs/deprecations/#RESOURCES_EXTENSIONS_REFERENCE_TO_NONEXISTENT_RESOURCE
```

which suggests that you're trying to extend a nonexistent resource. With the next major, this is going to throw an error unconditionally, which should help to catch these.
