### ISSUE TITLE
aws-layers generating error in deploy

### ISSUE THREAD

**Issue by luisdemarchi** [serverless/serverless#8915]
From version 2.3.0 to the last, every time I configure a layer and deployed is generating an error saying that the layer name was not found. At first I thought it was libraries, until I removed all libraries and the error persists.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
frameworkVersion: ">=2.0.0 <3.0.0"
service: abcd

provider:
    name: aws
    stackName: "abcd"
    runtime: nodejs12.x
    stage: local
    tracing:
        lambda: true

layers:
    libs:       // <== tried with "Libs"
        path: libs
        description: test abcd
        retain: true
        compatibleRuntimes:
            - nodejs12.x

package:
    individually: true

functions:
    tempActiveAllBots:
        handler: src/test.handler
        layers:
            - { Ref: LibsLambdaLayer }

```

</details>

<details>
<summary><b><code>serverless deploy </code> output</b></summary>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Deprecation warning: Serverless constructor expects resolved service configuration path to be provided via "config.configurationPath".
            Starting from next major Serverless will no longer auto resolve that path internally.
            More Info: https://www.serverless.com/framework/docs/deprecations/#MISSING_SERVICE_CONFIGURATION_PATH
simple-git deprecation notice: git.silent: logging should be configured using the `debug` library / `DEBUG` environment variable, this will be an error in version 3
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Deprecation warning: Starting with next major version, default value of provider.lambdaHashingVersion will be equal to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: [AWS cloudformation 400 0.777s 0 retries] describeStacks({ StackName: 'abcd' })
 
  Type Error ---------------------------------------------
 
  TypeError: Cannot read property '_serverlessLayerName' of undefined
      at /Users/luis/Projetos/OmniChat/botmaker-backend/node_modules/serverless/lib/plugins/aws/package/compile/functions.js:727:29
      at Array.forEach (<anonymous>)
      at extractLayerConfigurationsFromFunction (/Users/luis/Projetos/OmniChat/botmaker-backend/node_modules/serverless/lib/plugins/aws/package/compile/functions.js:723:29)
      at AwsCompileFunctions.compileFunction (/Users/luis/Projetos/OmniChat/botmaker-backend/node_modules/serverless/lib/plugins/aws/package/compile/functions.js:448:9)
      at /Users/luis/Projetos/OmniChat/botmaker-backend/node_modules/serverless/lib/plugins/aws/package/compile/functions.js:668:64
      at Array.map (<anonymous>)
      at AwsCompileFunctions.compileFunctions (/Users/luis/Projetos/OmniChat/botmaker-backend/node_modules/serverless/lib/plugins/aws/package/compile/functions.js:668:37)
      at AwsCompileFunctions.tryCatcher (/Users/luis/Projetos/OmniChat/botmaker-backend/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/luis/Projetos/OmniChat/botmaker-backend/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/luis/Projetos/OmniChat/botmaker-backend/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/Users/luis/Projetos/OmniChat/botmaker-backend/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/Users/luis/Projetos/OmniChat/botmaker-backend/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/Users/luis/Projetos/OmniChat/botmaker-backend/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/Users/luis/Projetos/OmniChat/botmaker-backend/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/Users/luis/Projetos/OmniChat/botmaker-backend/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues (/Users/luis/Projetos/OmniChat/botmaker-backend/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:131:23)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
```

</details>

<b>Your Environment Information</b>

```
     Operating System:          darwin
     Node Version:              12.9.0
     Framework Version:         2.23.0 (local)
     Plugin Version:            4.4.2
     SDK Version:               2.3.2
     Components Version:        3.6.2
```

**Comment by pgrzesik** [comment]
Hello @luisdemarchi, thanks a lot for reporting your issue and sorry to hear that you've run into trouble. I've investigated the problem and it seems like there are two separate problems:
1. When resolving local layers, we don't check properly check if a layer is actually defined as a part of service, which results in a similar error as above - we should either issue a warning or throw a more meaningful error
2. When using `retain: true` option for layers, referencing them via `Ref` is pretty very inconvenient, because the LogicalID of such Layer is no longer a simple `LibsLambdaLayer` but rather looks like this: `LibsLambdaLayer3c43d58d7d8d2a0dc7b53082ac26e78705923f88`, as it has `sha` digest appended to ensure uniqueness. So, in order for it to be recognized properly, we would have to reference it via this unwieldy logical id. 

Addressing 1. should be fairly straightforward, but 2. needs a bit more consideration on how we should actually define and resolve such references.

**Comment by pgrzesik** [comment]
Hello @luisdemarchi, I've investigated the issue a little bit more and I've come up with an implementation proposal for addressing 2. which I present below:

## Implementation proposal

In order to ease the development and configuration of functions with `layers`, especially when `retain:t true` is used, we should be able to reference `layers` not only with `Ref`, but also by it's `name` as defined in `serverless.yml`. It could look like this:

```
layers:
  libs:
    path: layers/common
    retain: true
    description: common set of functions

functions:
  hello:
    handler: lambdas/handler.hello
    layers:
      - name: libs
      - arn: arn:aws:lambda:region:XXXXXX:layer:LayerName:Y
      - arn:aws:lambda:region:XXXXXX:layer:LayerName:Y
      - {Ref: LibsLambdaLayer}
```

The above example shows all potentially supported notations, with the first two being newly introduced as a part of this change. I also think that we might consider deprecating the last two and instead require explicitly specifying referenced ARNs with `arn: !Ref ...`.

### Potential implementation steps:
1. Introduce util function that is able to resolve a reference to a Layer based on it's `name` in order to support `name: libs` notation. This util might either depend on the logic that computes `layerLogicalId` (https://github.com/serverless/serverless/blob/1eaa6260aa9f747d0aa01006ce54d3313e7b7e0f/lib/plugins/aws/package/compile/layers.js#L52-L72) or can take advantage of `_serverlessLayerName` added to Layer resources (https://github.com/serverless/serverless/blob/1eaa6260aa9f747d0aa01006ce54d3313e7b7e0f/lib/plugins/aws/package/compile/layers.js#L29). 
2. Use that util to properly set `Layers` property on `function` Resource - https://github.com/serverless/serverless/blob/1eaa6260aa9f747d0aa01006ce54d3313e7b7e0f/lib/plugins/aws/package/compile/functions.js#L419-L423
3. Update config schema for `layers`: https://github.com/serverless/serverless/blob/1eaa6260aa9f747d0aa01006ce54d3313e7b7e0f/lib/plugins/aws/provider.js#L446-L448
4. Update documentation for layers: https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/layers.md
5. Update reference `serverless.yml` file: https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/serverless.yml.md


All feedback on the above is welcome :raised_hands:

**Comment by medikoo** [comment]
@pgrzesik great spec! I have just few comments:

> The above example shows all potentially supported notations, with the first two being newly introduced as a part of this change. I also think that we might consider deprecating the last two and instead require explicitly specifying referenced ARNs with arn: !Ref

I believe what we support is simply an ARN in what whatever CF supported notation -> https://github.com/serverless/serverless/blob/1eaa6260aa9f747d0aa01006ce54d3313e7b7e0f/lib/plugins/aws/provider.js#L417

That means it can be literal ARN string, or CF instruction that resolves ARN string (and by referencing layers in same stack via `Ref`, user instructs AWS CF to resolve ARN's of needed layer).

I think there's no need to deprecate any _arn_ variant, but we simply may add support for _name_ string, and simply recognize it by fact that it doesn't start with `arn:` (unfortunately we didn't imply any restrictive rules on layer names, we can add it, but it'll have to be behind deprecation) - I think already in some other places we have same type of support (ARN or internal name) 

> Introduce util function that is able to resolve a reference to a Layer based on it's name in order to support name: libs notation. This util might either depend on the logic that computes layerLogicalId (

How about doing something like that:

1. In `compilerLayer`, expose resolved [`layerLogicalId`](https://github.com/serverless/serverless/blob/1eaa6260aa9f747d0aa01006ce54d3313e7b7e0f/lib/plugins/aws/package/compile/layers.js#L52-L68) on [`layerObject`](https://github.com/serverless/serverless/blob/1eaa6260aa9f747d0aa01006ce54d3313e7b7e0f/lib/plugins/aws/package/compile/layers.js#L27) (at e.g. `_generatedLogicalId` property)
2. In `compileFunction` having layer name and access to layers configuration, simply resolve _layer logical Id_ via `layerLogicalId = layers[layerName]._generatedLogicalId` and translate it to: `{ Ref: layerLogicalId }`

Can that work, or do I miss something?

**Comment by pgrzesik** [comment]
Thank you @medikoo :bow: 

That's correct, currently we're supporting any ARN variant, what I meant with potential suggestion is to enforce specification of arn with `arn:` key so it's easily distinguishable from `name` where we have `name:` key. But I agree that we can avoid using more verbose configuration and just try to deduct if someone is referencing `name` instead of `arn` by checking as you suggested. 

As for your suggestion on how to resolve/pass `layerLogicalId` - I really like the idea you proposed, I've just quickly prototyped it locally and can confirm that it should work perfectly :raised_hands: I don't see any potential issues at this point.

**Comment by pgrzesik** [comment]
I believe the original proposal + ideas from @medikoo are the best way to move forward with this. If someone from community is interested in picking this up, we'd love to accept a PR :raised_hands:
