### ISSUE TITLE
Since 2.23 there is an error when using serverless-export-env plugin

### ISSUE THREAD

**Issue by serverlesspolska** [serverless/serverless#8955]
Up to SF v2.22 my project that uses `serverless-export-env` plugin works correctly. Any newer (2.23, 2.24, 2.25) version does not work with the plugin. Fetching environment variables from AWS cloud (what plugin does) causes an error.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
plugins:
  - serverless-pseudo-parameters
  - serverless-iam-roles-per-function
  - serverless-export-env
```

</details>

<details>
<summary><b><code>sls export-env</code> output</b></summary>

```
Serverless: Deprecation warning: Detected ".env" files. Note that Framework now supports loading variables from those files when "useDotenv: true" is set (and that will be the default from next major release)
            More Info: https://www.serverless.com/framework/docs/deprecations/#LOAD_VARIABLES_FROM_ENV_FILES
Serverless: Deprecation warning: Starting with next major version, default value of provider.lambdaHashingVersion will be equal to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
 
  Type Error ---------------------------------------------
 
  TypeError: AWS.request(...).then(...).return is not a function
      at describeStack (/Users/pawel/moje/wordpress-integrator/node_modules/serverless-export-env/src/lib/collectStackOutputs.js:16:12)
      at collectStackOutputs (/Users/pawel/moje/wordpress-integrator/node_modules/serverless-export-env/src/lib/collectStackOutputs.js:28:10)
      at /Users/pawel/moje/wordpress-integrator/node_modules/serverless-export-env/src/index.js:60:9
      at tryCatcher (/Users/pawel/moje/wordpress-integrator/node_modules/bluebird/js/release/util.js:16:23)
      at Function.Promise.attempt.Promise.try (/Users/pawel/moje/wordpress-integrator/node_modules/bluebird/js/release/method.js:39:29)
      at ExportEnv.collectEnvVars (/Users/pawel/moje/wordpress-integrator/node_modules/serverless-export-env/src/index.js:56:25)
      at /Users/pawel/.nvm/versions/node/v12.18.4/lib/node_modules/serverless/lib/classes/PluginManager.js:500:55
      at tryCatcher (/Users/pawel/.nvm/versions/node/v12.18.4/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/Users/pawel/.nvm/versions/node/v12.18.4/lib/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:168:18)
      at Object.gotAccum (/Users/pawel/.nvm/versions/node/v12.18.4/lib/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (/Users/pawel/.nvm/versions/node/v12.18.4/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/pawel/.nvm/versions/node/v12.18.4/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/pawel/.nvm/versions/node/v12.18.4/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (/Users/pawel/.nvm/versions/node/v12.18.4/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (/Users/pawel/.nvm/versions/node/v12.18.4/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/Users/pawel/.nvm/versions/node/v12.18.4/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/Users/pawel/.nvm/versions/node/v12.18.4/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/Users/pawel/.nvm/versions/node/v12.18.4/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.18.4
     Framework Version:         2.23.0
     Plugin Version:            4.4.3
     SDK Version:               2.3.2
     Components Version:        3.7.0
```

</details>

<b>Installed version</b>

```
Framework Core: 2.23.0
Plugin: 4.4.3
SDK: 2.3.2
Components: 3.7.0
```

**Comment by pgrzesik** [comment]
Hello :wave: Sorry for the trouble and thanks for reporting. We are aware of that problem and there's already a PR proposed with the fix that is waiting for a review from the plugin maintainer - https://github.com/arabold/serverless-export-env/pull/28

**Comment by pgrzesik** [comment]
I'm going to close this one - let's track it on corresponding issue/PR in plugin's repository

**Comment by serverlesspolska** [comment]
Oh, I didn't know. Thanks and keep up the good work :-)

**Comment by pgrzesik** [comment]
No worries :100: Hopefully it will be merged soon on the plugin side :crossed_fingers:
