### ISSUE TITLE
Can not install serverless "command failed"

### ISSUE THREAD

**Issue by mykolasmolis** [serverless/serverless#8977]
Can not install serverless:
```
npm install serverless
...
npm ERR! code 1
npm ERR! path /home/me/projects/project1/node_modules/serverless
npm ERR! command failed
npm ERR! command sh -c node ./scripts/postinstall.js
```

Detailed log:
```
3380 verbose stack Error: command failed
3380 verbose stack     at ChildProcess.proc.on (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
3380 verbose stack     at ChildProcess.emit (events.js:198:13)
3380 verbose stack     at maybeClose (internal/child_process.js:982:16)
3380 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
3381 verbose pkgid serverless@2.25.2
```

**Comment by mykolasmolis** [comment]
Anyone else is facing such issue?

**Comment by mykolasmolis** [comment]
Ok - to be honest it does not matter. I decided to install the `serverless` not as NPM package, rather curl.
