### ISSUE TITLE
Windows-style path separators (i.e. backslashes) are not supported in include pattern

### ISSUE THREAD

**Issue by BenLanglois** [serverless/serverless#9004]
Glob patterns/file paths in `package.include` are not matched if they contain windows-style path separators (i.e. backslashes). This appears to be the result of upgrading the `globby` package to `>= v10.0.0` since one of the breaking changes of that version is that backslash path separators are no longer supported. The call to globby is [here](https://github.com/serverless/serverless/blob/v2.27.0/lib/plugins/package/lib/packageService.js#L217). I'm not sure if windows-style path separators are valid in `package.include`, but [this comment](https://github.com/serverless/serverless/blob/v2.27.0/lib/plugins/package/lib/packageService.js#L227) seems to imply that they are.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: test-service
frameworkVersion: ^2.0.0

package:
  include:
    - '!**'
    - 'src\\foo.js'

functions:
  foo:
    events:
    handler: 'src\\foo.handler'

provider:
  name: aws
```

</details>

<details>
<summary><b><code>SLS_DEBUG=* sls package</code> output</b></summary>

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Deprecation warning: Starting with next major version, default value of provider.lambdaHashingVersion will be equal to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...

  Serverless Error ---------------------------------------

  ServerlessError: No file matches include / exclude patterns
      at C:\path\to\project\node_modules\serverless\lib\plugins\package\lib\packageService.js:242:13
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at Package.packageService (C:\path\to\project\node_modules\serverless\lib\plugins\package\lib\packageService.js:92:76)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              14.15.4
     Framework Version:         2.27.0 (local)
     Plugin Version:            4.4.3
     SDK Version:               2.3.2
     Components Version:        3.7.1
```

Note that the file `src\foo.js` exists and is successfully matched if the include pattern uses forward slashes (i.e. `src/foo.js`).

</details>

<b>Installed version</b>

```
Framework Core: 2.27.0 (local)
Plugin: 4.4.3
SDK: 2.3.2
Components: 3.7.1
```

**Comment by pgrzesik** [comment]
Hello @BenLanglois, thanks for reporting and sorry for not responding sooner - I've somehow missed notification about this issue. I will investigate on Windows machine and will get back to you as soon as possible. Thanks for your patience :bow:

**Comment by pgrzesik** [comment]
Hello @BenLanglois - sorry for dropping the ball on this one :sweat: I've had a few other priorities come up and I didn't manage to properly investigate this one up until now. Thanks a lot for your patience. 

I've managed to reproduce that issue and you're totally right - it's caused by an upgrade of `globby`, which depends on `fast-glob` that dropped support for backslashes in it's `v3` release and relies on `micromatch` which reserves backslashes for escaping characters (https://github.com/micromatch/micromatch#backslashes). To be honest, I agree with the notion of treating globs as it's own regular language which is mentioned by `micromatch` authors, however, I see how it's a breaking change for current users who were relying on previous functionality. What is even more problematic is the fact that at the moment, simply trying to change backslashes to slashes might break the functionality for people that already rely on `micromatch` functionality to use backslashes for escaping. Oof! 

I think that moving forward, we should stick to one convention and I'm leaning towards treating `globs` in `include/exclude` similarly as `micromatch` and stick to `/` as path separator. 

I think the potential next steps could be:
1. Document the supported format for `include/exclude` glob patterns
2. Configure deprecation for people that use `\` in their paths to warn them that if they're using `\` as path separator, it won't work as expected 
3. Remove the deprecation with the next major (v3)

Alternatively, if we would like to try to do our best to bring back the old functionality, we could do the following:
1. Replace `\` with `/` before a call to `globby`
2. Configure deprecation for people that use `\` in their paths to warn them that if theyr'e using it as path separator, from the next major it won't work as expected
3. When releasing new major, document supported formats for `include/exclude` glob patterns and remove replacing `\` with `/`. 

The alternative approach has the problem of potentially breaking for people that already take advantage of `\` for escaping.

What do you think @BenLanglois ?

@medikoo I would love to hear your opinion on this as well

**Comment by medikoo** [comment]
>  it's caused by an upgrade of `globby`

@pgrzesik @BenLanglois Technically we've upgraded `globby` with v2. So this change happened with major release of a Framwork. Ofc omission is that it was not communicated with deprecation at v1. We were not aware of all implications that comes with it.

> Configure deprecation for people that use `\` in their paths

Technically we're fine to throw, as it's invalid syntax that have no chance of working, but I agree that suddenly throwing maybe harmful. So indeed we probably should warn now (with deprecation) that it cannot work, and in v3 simply crash if we find such separators

> Replace \ with / before a call to globby

I would rather educate users to just use `\`, it's same when writing paths for Node.js modules.

**Comment by pgrzesik** [comment]
Thanks @medikoo, so to recap, the next steps here would be:
1. Configure deprecation if someone is using `\` in `include/exclude` globs. Keep in mind that `\\` is a valid escape character notation for micromatch.
2. Improve documentation with highlight what format is supported for `include/exclude` globs.
3. With next major remove deprecation and throw an error if someone is using `\` as separator in paths

> I would rather educate users to just use \, it's same when writing paths for Node.js modules.
Fully agree, `.gitignore`, `.npmignore` use the same globbing patterns and I think it's just a better practice overall.

**Comment by medikoo** [comment]
@pgrzesik As I think of it, I wonder weather we should rather just keep it as warning. Thing is that on linux `\` can be a part of a filename. And while it's edge case to use this character in filename, I think we should not make impossible to write rule against it (If I understand correctly `minimatch` will simply treat `\\` as `\` character that's not a path separator ?)

So in such case I would probably introduce a warning, and a configuration option (in `package` context) through which warning could be silenced

**Comment by pgrzesik** [comment]
@medikoo That is a great point. I've just validated it and you're right - it's a valid name and as such is correctly supported by `micromatch` that we use internally - so we should not crash on that notation :+1:
