### ISSUE TITLE
serverless plugin install package list has extra character at line 1

### ISSUE THREAD

**Issue by wcx628** [serverless/serverless#9104]
[{
    "name": "serverless-plugin-typetalk",
    "description": "Sends notification to Typetalk",
    "githubUrl": "https://github.com/is2ei/serverless-plugin-typetalk",
    "status": "active"
}, {

[Container] 2021/03/12 18:41:41 Running command serverless plugin install -n serverless-python-requirements
--
226 | Serverless: Running "serverless" installed locally (in service node_modules)
227 | Serverless: Configuration warning at root: unrecognized property 'stepFunctions'
228 | Serverless:
229 | Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
230 | Serverless:
231 |  
232 | Fetch Error --------------------------------------------
233 |  
234 | FetchError: invalid json response body at https://raw.githubusercontent.com/serverless/plugins/master/plugins.json reason: Unexpected token : in JSON at position 3
235 | at /codebuild/output/src046/src/git-codecommit.us-east-1.amazonaws.com/v1/repos/bnym-is-vkg-repo-py/node_modules/node-fetch/lib/index.js:272:32
236 | at process._tickCallback (internal/process/next_tick.js:68:7)
237 |  
238 | For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

**Comment by wcx628** [comment]
Not sure what happened but it works now, this is really weird, it failed for at least 20 mins but it recovers now
