### ISSUE TITLE
can't use stage name with uppercase letters 

### ISSUE THREAD

**Issue by goldylucks** [serverless/serverless#912]
creating a stage works:
`sls stage create -s stageName`
but deploying functions get this error:
```
sls function deploy - stageName
TypeError: Cannot read property 'regions' of undefined
    at ServerlessMeta.getRegions (/home/adam/.node/lib/node_modules/serverless/lib/ServerlessMeta.js:141:42)
    at StageRemove._removeAllRegions (/home/adam/.node/lib/node_modules/serverless/lib/actions/StageRemove.js:145:44)
From previous event:
    at StageRemove.stageRemove (/home/adam/.node/lib/node_modules/serverless/lib/actions/StageRemove.js:71:10)
From previous event:
    at /home/adam/.node/lib/node_modules/serverless/lib/Serverless.js:156:29
    at Array.reduce (native)
    at /home/adam/.node/lib/node_modules/serverless/lib/Serverless.js:155:30
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Serverless._execute (/home/adam/.node/lib/node_modules/serverless/lib/Serverless.js:153:10)
    at Serverless.actions.(anonymous function) (/home/adam/.node/lib/node_modules/serverless/lib/Serverless.js:381:20)
    at Serverless.command (/home/adam/.node/lib/node_modules/serverless/lib/Serverless.js:350:38)
    at Object.<anonymous> (/home/adam/.node/lib/node_modules/serverless/bin/serverless:16:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by eahefnawy** [comment]
@Adam-Goldman7 we convert the stage name to lower case on stage creation. So if you try `sls dash summary`, you'll find that your stage exists but it's called `stagename`. If you then run `sls function deploy -s stagename` it should work.

Generally we don't recommend/encourage naming your stages with capital letters since this name is used in all sorts of places (lambda alias name, file name...etc), each might have it's own naming policy. So we think stage names should be simple.

Hope this helps :blush:

**Comment by Adam-Goldman7** [comment]
It helps :)

so maybe add a validation to prevent future errors?

**Comment by eahefnawy** [comment]
for sure! @Adam-Goldman7
