### ISSUE TITLE
Error: Cannot find module 'please-upgrade-node' in serverless offline.

### ISSUE THREAD

**Issue by arslanalidev** [serverless/serverless#9150]
I am facing this below error while I am trying to run the serverless offline.
Error ---------------------------------------------------

  Error: Cannot find module 'please-upgrade-node'
  Require stack:
  - C:\Users\Arslan Titan\AppData\Roaming\npm\node_modules\serverless-offline\dist\checkEngine.js
  - C:\Users\Arslan Titan\AppData\Roaming\npm\node_modules\serverless-offline\dist\index.js
  - C:\Users\Arslan Titan\AppData\Roaming\npm\node_modules\serverless-offline\dist\main.js
  - C:\Users\Arslan Titan\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js
  - C:\Users\Arslan Titan\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js
  - C:\Users\Arslan Titan\AppData\Roaming\npm\node_modules\serverless\scripts\serverless.js
  - C:\Users\Arslan Titan\AppData\Roaming\npm\node_modules\serverless\bin\serverless.js
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
      at Function.Module._load (internal/modules/cjs/loader.js:687:27)
      at Module.require (internal/modules/cjs/loader.js:849:19)
      at require (internal/modules/cjs/helpers.js:74:18)
      at Object.<anonymous> (C:\Users\Arslan Titan\AppData\Roaming\npm\node_modules\serverless-offline\dist\checkEngine.js:3:49)
      at Module._compile (internal/modules/cjs/loader.js:956:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
      at Module.load (internal/modules/cjs/loader.js:812:32)
      at Function.Module._load (internal/modules/cjs/loader.js:724:14)
      at Module.require (internal/modules/cjs/loader.js:849:19)
      at require (internal/modules/cjs/helpers.js:74:18)
      at Object.<anonymous> (C:\Users\Arslan Titan\AppData\Roaming\npm\node_modules\serverless-offline\dist\index.js:13:1)
      at Module._compile (internal/modules/cjs/loader.js:956:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
      at Module.load (internal/modules/cjs/loader.js:812:32)
      at Function.Module._load (internal/modules/cjs/loader.js:724:14)
      at Module.require (internal/modules/cjs/loader.js:849:19)
      at require (internal/modules/cjs/helpers.js:74:18)
      at Object.<anonymous> (C:\Users\Arslan Titan\AppData\Roaming\npm\node_modules\serverless-offline\dist\main.js:11:18)
      at Module._compile (internal/modules/cjs/loader.js:956:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
      at Module.load (internal/modules/cjs/loader.js:812:32)
      at Function.Module._load (internal/modules/cjs/loader.js:724:14)
      at Module.require (internal/modules/cjs/loader.js:849:19)
      at require (internal/modules/cjs/helpers.js:74:18)
      at requireServicePlugin (C:\Users\Arslan Titan\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:28:12)
      at C:\Users\Arslan Titan\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:164:20
      at Array.map (<anonymous>)
      at PluginManager.resolveServicePlugins (C:\Users\Arslan Titan\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:161:8)
      at PluginManager.loadAllPlugins (C:\Users\Arslan Titan\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:147:10)
      at Serverless.init (C:\Users\Arslan Titan\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:171:30)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async C:\Users\Arslan Titan\AppData\Roaming\npm\node_modules\serverless\scripts\serverless.js:235:7

**Comment by medikoo** [comment]
Please report at `serverless offline`

**Comment by arslanalidev** [comment]
ok Done
