### ISSUE TITLE
Deploying a single function (deploy -f) no longer working (aws-nodejs-typescript)

### ISSUE THREAD

**Issue by ffxsam** [serverless/serverless#9184]
Running `sls deploy -f someFunc` results in an error. It expects all functions to be deployed at once via full deploy.

<details>
<summary><code>serverless.ts</code></summary>

```ts
import type { AWS } from '@serverless/typescript';
import { hello, goodbye } from '@functions/index';

const serverlessConfiguration: AWS = {
  service: 'test1',
  frameworkVersion: '2',
  custom: {
    webpack: {
      webpackConfig: './webpack.config.js',
      includeModules: true,
    },
  },
  package: { individually: true },
  plugins: ['serverless-webpack'],
  provider: {
    name: 'aws',
    runtime: 'nodejs12.x',
    apiGateway: {
      minimumCompressionSize: 1024,
      shouldStartNameWithService: true,
    },
    environment: {
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1',
    },
    lambdaHashingVersion: '20201221',
  },
  // import the function via paths
  functions: { hello, goodbye},
};

module.exports = serverlessConfiguration;
```
</details>

<details>
<summary><b><code>sls deploy -f goodbye</code> output</b></summary>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Deprecation warning: Starting with next major version, "http.request.schema" property will be replaced by "http.request.schemas".
            More Info: https://www.serverless.com/framework/docs/deprecations/#AWS_API_GATEWAY_SCHEMAS
Serverless: Bundling with Webpack...
asset src/functions/goodbye/handler.js 1.19 KiB [emitted] [minimized] (name: src/functions/goodbye/handler) 1 related asset
runtime modules 937 bytes 4 modules
built modules 803 bytes [built]
  cacheable modules 677 bytes
    ./src/functions/goodbye/handler.ts 348 bytes [built] [code generated]
    ./src/libs/lambda.ts 192 bytes [built] [code generated]
    ./src/libs/apiGateway.ts 137 bytes [built] [code generated]
  modules by path external "@middy/ 84 bytes
    external "@middy/core" 42 bytes [built] [code generated]
    external "@middy/http-json-body-parser" 42 bytes [built] [code generated]
  external "source-map-support/register" 42 bytes [built] [code generated]
webpack compiled successfully in 307 ms
(node:73889) [DEP_WEBPACK_CHUNK_MODULES_ITERABLE] DeprecationWarning: Chunk.modulesIterable: Use new ChunkGraph API
(node:73889) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
Serverless: Packing external modules: @middy/core@^1.5.2, @middy/http-json-body-parser@^1.5.2, source-map-support@^0.5.19
Serverless: Copying existing artifacts...

 Error ---------------------------------------------------

  Error: ENOENT: no such file or directory, copyfile '/Users/samh/test1/.webpack/hello.zip' -> '.serverless/hello.zip'
      at Object.copyFileSync (fs.js:1907:3)
      at ServerlessWebpack.copyArtifactByName (/Users/samh/test1/node_modules/serverless-webpack/lib/packageModules.js:86:6)
      at /Users/samh/test1/node_modules/serverless-webpack/lib/packageModules.js:133:66
      at arrayEach (/Users/samh/test1/node_modules/lodash/lodash.js:530:11)
      at Function.forEach (/Users/samh/test1/node_modules/lodash/lodash.js:9410:14)
      at ServerlessWebpack.copyExistingArtifacts (/Users/samh/test1/node_modules/serverless-webpack/lib/packageModules.js:133:9)
      at ServerlessWebpack.tryCatcher (/Users/samh/test1/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/samh/test1/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/samh/test1/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (/Users/samh/test1/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (/Users/samh/test1/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/Users/samh/test1/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/Users/samh/test1/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/Users/samh/test1/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:461:21)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.20.1
     Framework Version:         2.31.0 (local)
     Plugin Version:            4.5.2
     SDK Version:               4.2.2
     Components Version:        3.7.7
```
</details>

<b>Installed version</b>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.31.0 (local)
Plugin: 4.5.2
SDK: 4.2.2
Components: 3.7.7
```

**Comment by medikoo** [comment]
@ffxsam you're relying on some plugins, and I believe it's a problem with them. Please either minimize the test case so no plugins are involved, or report at corresponding plugin issue tracker

**Comment by ffxsam** [comment]
Ah! Looks like this is a new issue in the serverless-webpack plugin: https://github.com/serverless-heaven/serverless-webpack/issues/737

Thanks!
