### ISSUE TITLE
Regression: No updates are to be performed

### ISSUE THREAD

**Issue by roni-frantchi** [serverless/serverless#9241]
When no changes in the stack occur, a `No updates are to be performed` error is thrown from AWS.  
Serverless checks and resolves if the error thrown matches that text.  
But ever since 2.31.0 the error has changed to contain the status code and stack trace (specifically, since #9148, I think).  

To recreate - deploy the stack below once.  
Once completed, deploy again with no changes - see command and output below.  
**_Edit: You must turn on `SLS_DEBUG=*`_**

<details>
<summary><code>serverless.yml</code></summary>

```yaml
# deploy this serverless.yml once - then try to deploy again (with no changes made)
frameworkVersion: 2.31.0

service: foobar

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}

resources:
  Resources:
    SelfHostedReleaseBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: foobar
```

</details>

<details>
<summary><b><code>sls deploy -s dev</code> output</b></summary>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Deprecation warning: Starting with next major version, "enableLocalInstallationFallback" setting will no longer be supported.CLI will unconditionally fallback to service local installation when its found.
            Remove this setting to clear this deprecation warning
            More Info: https://www.serverless.com/framework/docs/deprecations/#DISABLE_LOCAL_INSTALLATION_FALLBACK_SETTING
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Validating template...
Serverless: Updating Stack...
 
  Serverless Error ---------------------------------------
 
  ServerlessError: ValidationError: No updates are to be performed.
      at Request.extractError (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/protocol/query.js:50:29)
      at Request.callListeners (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at Request.emit (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/request.js:688:14)
      at Request.transition (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/request.js:690:12)
      at Request.callListeners (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at Request.emit (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/request.js:688:14)
      at Request.transition (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/request.js:690:12)
      at Request.callListeners (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at callNextListener (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
      at IncomingMessage.onEnd (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/event_listeners.js:313:13)
      at IncomingMessage.emit (events.js:327:22)
      at IncomingMessage.EventEmitter.emit (domain.js:467:12)
      at endReadableNT (internal/streams/readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
  ----------------------------------------------------------------------------------------------------
      at Request.extractError (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/protocol/query.js:50:29)
      at Request.callListeners (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at Request.emit (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/request.js:688:14)
      at Request.transition (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/request.js:690:12)
      at Request.callListeners (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at Request.emit (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/request.js:688:14)
      at Request.transition (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/request.js:690:12)
      at Request.callListeners (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at callNextListener (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
      at IncomingMessage.onEnd (/Users/roni/dev/env0/node_modules/serverless/node_modules/aws-sdk/lib/event_listeners.js:313:13)
      at IncomingMessage.emit (events.js:327:22)
      at IncomingMessage.EventEmitter.emit (domain.js:467:12)
      at endReadableNT (internal/streams/readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
      at /Users/roni/dev/env0/node_modules/serverless/lib/aws/request.js:202:11
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at persistentRequest (/Users/roni/dev/env0/node_modules/serverless/lib/aws/request.js:140:14)
  From previous event:
      at processImmediate (internal/timers.js:461:21)
  From previous event:
      at Object.<anonymous> (/Users/roni/.nvm/versions/node/v14.16.0/lib/node_modules/serverless/scripts/serverless.js:58:4)
      at Module._compile (internal/modules/cjs/loader.js:1063:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
      at Module.load (internal/modules/cjs/loader.js:928:32)
      at Function.Module._load (internal/modules/cjs/loader.js:769:14)
      at Module.require (internal/modules/cjs/loader.js:952:19)
      at require (internal/modules/cjs/helpers.js:88:18)
      at Object.<anonymous> (/Users/roni/.nvm/versions/node/v14.16.0/lib/node_modules/serverless/bin/serverless.js:41:1)
      at Module._compile (internal/modules/cjs/loader.js:1063:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
      at Module.load (internal/modules/cjs/loader.js:928:32)
      at Function.Module._load (internal/modules/cjs/loader.js:769:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
      at internal/main/run_main_module.js:17:47
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.16.0
     Framework Version:         1.83.3 (local)
     Plugin Version:            3.8.4
     SDK Version:               2.3.2
     Components Version:        2.34.9

```

</details>

<b>Installed version</b>

```
2.33.1
```

I have downgraded all the way down to 2.31.0 and the issue persists.  

Downgrading to 2.30.3 does the trick

**Comment by pgrzesik** [comment]
Thanks @roni-frantchi for reporting - it will be fixed with next release :+1:
