### ISSUE TITLE
Inaccessible host: `cloudformation.us-east-2.amazonaws.com'

### ISSUE THREAD

**Issue by corydorning53** [serverless/serverless#9244]
When attempting to deploy, I'm getting an `Inaccessible host: `cloudformation.us-east-2.amazonaws.com'` error. I am behind a corporate proxy, but have `https_proxy` set.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
# Welcome to Serverless!
service: serverless-lambda-demo

frameworkVersion: '2'

provider:
  name: aws
  region: us-east-2
  runtime: nodejs14.x
  stage: dev
  endpointType: regional

functions:
  hello:
    handler: index.hello
    events:
      - http:
          path: /hello
          method: get
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
❯ npx sls deploy    
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Deprecation warning: Resolution of lambda version hashes was improved with better algorithm, which will be used in next major release.
            Switch to it now by setting "provider.lambdaHashingVersion" to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Deprecation warning: Starting with next major version, API Gateway naming will be changed from "{stage}-{service}" to "{service}-{stage}".
            Set "provider.apiGateway.shouldStartNameWithService" to "true" to adapt to the new behavior now.
            More Info: https://www.serverless.com/framework/docs/deprecations/#AWS_API_GATEWAY_NAME_STARTING_WITH_SERVICE
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation undefined 0.623s 3 retries] describeStacks({ StackName: 'serverless-lambda-demo-dev' })
Serverless: Recoverable error occurred (Inaccessible host: `cloudformation.us-east-2.amazonaws.com'. This service may not be available in the `us-east-2' region.), sleeping for ~4 seconds. Try 1 of 4
Serverless: [AWS cloudformation undefined 0.38s 3 retries] describeStacks({ StackName: 'serverless-lambda-demo-dev' })
Serverless: Recoverable error occurred (Inaccessible host: `cloudformation.us-east-2.amazonaws.com'. This service may not be available in the `us-east-2' region.), sleeping for ~4 seconds. Try 2 of 4
Serverless: [AWS cloudformation undefined 0.41s 3 retries] describeStacks({ StackName: 'serverless-lambda-demo-dev' })
Serverless: Recoverable error occurred (Inaccessible host: `cloudformation.us-east-2.amazonaws.com'. This service may not be available in the `us-east-2' region.), sleeping for ~6 seconds. Try 3 of 4
Serverless: [AWS cloudformation undefined 0.463s 3 retries] describeStacks({ StackName: 'serverless-lambda-demo-dev' })
Serverless: Recoverable error occurred (Inaccessible host: `cloudformation.us-east-2.amazonaws.com'. This service may not be available in the `us-east-2' region.), sleeping for ~5 seconds. Try 4 of 4
Serverless: [AWS cloudformation undefined 0.504s 3 retries] describeStacks({ StackName: 'serverless-lambda-demo-dev' })
 
  Serverless Error ---------------------------------------
 
  ServerlessError: Inaccessible host: `cloudformation.us-east-2.amazonaws.com'. This service may not be available in the `us-east-2' region.
      at /Users/cory/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/serverless/lib/plugins/aws/provider.js:1481:27
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.15.4
     Framework Version:         2.28.1 (local)
     Plugin Version:            4.4.3
     SDK Version:               2.3.2
     Components Version:        3.7.1
```

</details>

<b>Installed version</b>

```
Framework Core: 2.28.1 (local)
Plugin: 4.4.3
SDK: 2.3.2
Components: 3.7.1
```

**Comment by pgrzesik** [comment]
Hello @corydorning53 - it looks like an issue with the proxy, do you have the ability to update to the latest version of the Framework to confirm if it's still the case? There was an improvement introduced recently to handling of proxy urls.

**Comment by corydorning53** [comment]
sure just updated but facing the same issue still:

```
❯ npx sls deploy
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Deprecation warning: Resolution of lambda version hashes was improved with better algorithm, which will be used in next major release.
            Switch to it now by setting "provider.lambdaHashingVersion" to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: Recoverable error occurred (UnknownEndpoint: Inaccessible host: `cloudformation.us-east-2.amazonaws.com'. This service may not be available in the `us-east-2' region.
    at Request.ENOTFOUND_ERROR (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/event_listeners.js:507:46)
    at Request.callListeners (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/request.js:688:14)
    at ClientRequest.error (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/event_listeners.js:339:22)
    at ClientRequest.<anonymous> (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/http/node.js:96:19)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at onerror (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/agent-base/dist/src/index.js:117:21)
    at callbackError (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/agent-base/dist/src/index.js:136:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
----------------------------------------------------------------------------------------------------), sleeping for ~5 seconds. Try 1 of 4
Serverless: Recoverable error occurred (UnknownEndpoint: Inaccessible host: `cloudformation.us-east-2.amazonaws.com'. This service may not be available in the `us-east-2' region.
    at Request.ENOTFOUND_ERROR (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/event_listeners.js:507:46)
    at Request.callListeners (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/request.js:688:14)
    at ClientRequest.error (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/event_listeners.js:339:22)
    at ClientRequest.<anonymous> (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/http/node.js:96:19)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at onerror (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/agent-base/dist/src/index.js:117:21)
    at callbackError (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/agent-base/dist/src/index.js:136:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
----------------------------------------------------------------------------------------------------), sleeping for ~5 seconds. Try 2 of 4
Serverless: Recoverable error occurred (UnknownEndpoint: Inaccessible host: `cloudformation.us-east-2.amazonaws.com'. This service may not be available in the `us-east-2' region.
    at Request.ENOTFOUND_ERROR (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/event_listeners.js:507:46)
    at Request.callListeners (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/request.js:688:14)
    at ClientRequest.error (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/event_listeners.js:339:22)
    at ClientRequest.<anonymous> (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/http/node.js:96:19)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at onerror (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/agent-base/dist/src/index.js:117:21)
    at callbackError (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/agent-base/dist/src/index.js:136:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
----------------------------------------------------------------------------------------------------), sleeping for ~5 seconds. Try 3 of 4
Serverless: Recoverable error occurred (UnknownEndpoint: Inaccessible host: `cloudformation.us-east-2.amazonaws.com'. This service may not be available in the `us-east-2' region.
    at Request.ENOTFOUND_ERROR (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/event_listeners.js:507:46)
    at Request.callListeners (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/request.js:688:14)
    at ClientRequest.error (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/event_listeners.js:339:22)
    at ClientRequest.<anonymous> (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/http/node.js:96:19)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at onerror (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/agent-base/dist/src/index.js:117:21)
    at callbackError (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/agent-base/dist/src/index.js:136:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
----------------------------------------------------------------------------------------------------), sleeping for ~6 seconds. Try 4 of 4
 
 Serverless Error ----------------------------------------
 
  ServerlessError: UnknownEndpoint: Inaccessible host: `cloudformation.us-east-2.amazonaws.com'. This service may not be available in the `us-east-2' region.
      at Request.ENOTFOUND_ERROR (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/event_listeners.js:507:46)
      at Request.callListeners (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at Request.emit (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/request.js:688:14)
      at ClientRequest.error (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/event_listeners.js:339:22)
      at ClientRequest.<anonymous> (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/aws-sdk/lib/http/node.js:96:19)
      at ClientRequest.emit (events.js:315:20)
      at ClientRequest.EventEmitter.emit (domain.js:467:12)
      at onerror (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/agent-base/dist/src/index.js:117:21)
      at callbackError (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/agent-base/dist/src/index.js:136:17)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
  ----------------------------------------------------------------------------------------------------
      at /Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/serverless/lib/aws/request.js:202:11
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async persistentRequest (/Users/e022145/Web/www-local/github-enterprise/serverless-app-demo/sls/node_modules/serverless/lib/aws/request.js:140:14)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.15.4
     Framework Version:         2.33.1 (local)
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.8.1
 ```

```
❯ npx sls --version
Framework Core: 2.33.1 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.1
```

**Comment by corydorning53** [comment]
I got it working. error was on my side. forgot to add `http://` to my `http_proxy` variables. doh.

for anyone else that finds this, make sure you set as follows:
```
export http_proxy=http://your-proxy.com:8080
export https_proxy=http://your-proxy.com:8080
```

instead of:
```
export http_proxy=your-proxy.com:8080
export https_proxy=your-proxy.com:8080
```

**Comment by pgrzesik** [comment]
Glad to hear that you've managed to make it work :raised_hands:
