### ISSUE TITLE
getAllFunctions() return every functions in the service when deploying a single function

### ISSUE THREAD

**Issue by jacobb35** [serverless/serverless#9252]
The issue occurs when using Serverless with Serverless-Webpack.

When deploying a single function in a service with the `-f` or `--function` option, Serverless keeps every function of the service in it's `this.functions` object of the `Service` class. This causes the function `getAllFunctions()` to return every function of the service.

When Serverless-Webpack calls the function `getAllFunctions()` to get the name of the function it needs to copy the artifacts of, it gets the name of every functions in the service and tries to copy their artifact, but fails once it reaches any function that was not the function specified in the deployment command since Webpack only compiled the specified function and the artifacts of the other function do not exist. Here, I wanted to deploy `GetUsers`, but because I also have `GetUser` in the service, it fails on `GetUser`.

That is why I think Serveless' `Service` class should only keep the function that are being deployed or only return the function that are being deployed when `getAllFunctions()` is called.

<details>
<summary>A working quick fix is to return the value of <code>options.function</code> in <code>getAllFunctions()</code> if <code>options.function</code> is present.</summary>

Like this in `serverless/lib/classes/Service.js` :
```
constructor(serverless, data) {
    // #######################################################################
    // ## KEEP SYNCHRONIZED WITH EQUIVALENT IN ~/lib/plugins/print/print.js ##
    // #######################################################################
    this.serverless = serverless;

    // Default properties
    this.service = null;
    this.serviceObject = null;
    this.provider = {
      stage: 'dev',
      variableSyntax: '\\${([^{}:]+?(?:\\(|:)(?:[^:{}][^{}]*?)?)}',
    };
    this.custom = {};
    this.plugins = [];
    this.pluginsData = {};
    this.functions = {};
    this.resources = {};
    this.package = {};
    this.configValidationMode = 'warn';
    this.disabledDeprecations = [];
    // Add this
    this.individualFunction = '';

    if (data) this.update(data);
  }

async load(rawOptions) {
    const options = rawOptions || {};
    if (!options.stage && options.s) options.stage = options.s;
    if (!options.region && options.r) options.region = options.r;

    // Add this
    if (options.function) {
      this.individualFunction = options.function;
    }

    const servicePath = this.serverless.config.servicePath;

    // skip if the service path is not found
    // because the user might be creating a new service
    if (!servicePath) return;

    try {
      this.loadServiceFileParam();
    } catch (error) {
      if (resolveCliInput().isHelpRequest) return;
      throw error;
    }
  }

getAllFunctions() {
    // Change this
    return this.individualFunction ? [this.individualFunction] : Object.keys(this.functions);
}
```
</details>

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: users

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: false
    packager: 'npm'
    excludeFiles: src/**/*.spec.ts

provider:
  name: aws
  region: ca-central-1
  runtime: nodejs12.x
  versionFunctions: false

  environment:
    STAGE: ${env:STAGE}


  iamRoleStatements:
  - Effect: Allow
    Action:
      - *:*
    Resource: "*"

package:
  individually: true

functions:
  getUsers:
      handler: src/api/users/getUsers.getUsersHandler
  getUser:
      handler: src/api/users/getUser.getUserHandler
```

</details>

<details>
<summary><b><code>SLS_DEBUG=* STAGE=dev serverless deploy --config @devops/serverless/serverless.users.yml -f getUsers --aws-profile dev</code> output</b></summary>

```
Serverless: Deprecation warning: Service configuration is expected to be placed in a root of a service (working directory). All paths, function handlers in a configuration are resolved against service directory".
            Starting from next major Serverless will no longer permit configurations nested in sub directories.
            More Info: https://www.serverless.com/framework/docs/deprecations/#NESTED_CUSTOM_CONFIGURATION_PATH
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.33.1")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command webpack
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless:
Serverless: Deprecation warning: Starting with next major, Serverless will throw on configuration errors by default. Adapt to this behavior now by adding "configValidationMode: error" to service configuration
            More Info: https://www.serverless.com/framework/docs/deprecations/#CONFIG_VALIDATION_MODE_DEFAULT
Serverless: Deprecation warning: Support for "package.include" and "package.exclude" will be removed with next major release. Please use "package.patterns" instead
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_PACKAGE_PATTERNS
Serverless: Deprecation warning: Starting with version 3.0.0, following property will be replaced:
              "provider.iamRoleStatements" -> "provider.iam.role.statements"
            More Info: https://www.serverless.com/framework/docs/deprecations/#PROVIDER_IAM_SETTINGS
Serverless: Invoke deploy
Serverless: Invoke deploy:function
Serverless: Invoke webpack:validate
Serverless: Invoke webpack:compile
Serverless: Bundling with Webpack...
Time: 5406ms
Built at: 04/06/2021 5:54:34 PM
                    Asset     Size  Chunks             Chunk Names
src/api/users/getUsers.js  244 KiB       0  [emitted]  src/api/users/getUsers
Entrypoint src/api/users/getUsers = src/api/users/getUsers.js
  [0] ./src/baseHandler/common/utils/log/log.ts 4.1 KiB {0} [built]
  [1] external "objection" 42 bytes {0} [built]
  [2] ./src/services/baseService.ts 2.11 KiB {0} [built]
  [4] ./src/services/usersService/usersService.ts 37 KiB {0} [built]
 [20] external "f2s-interfaces/interfaces/utilities/httpStatusCodesEnum" 42 bytes {0} [built]
 [21] ./src/baseHandler/common/utils/http/responseUtil.ts 1.08 KiB {0} [built]
 [28] external "reflect-metadata" 42 bytes {0} [built]
 [33] external "tsyringe" 42 bytes {0} [built]
 [35] ./src/services/usersService/model/session.ts 1.5 KiB {0} [built]
 [59] ./src/baseHandler/common/utils/encryption/rijndael.ts 2.31 KiB {0} [built]
 [73] ./src/api/users/getUsers.ts 3.86 KiB {0} [built]
 [75] ./src/api/decorators/authorized.ts 688 bytes {0} [built]
 [76] ./src/api/decorators/transaction.ts 1.08 KiB {0} [built]
 [85] ./src/api/abstractController.ts 4.84 KiB {0} [built]
[118] ./src/authorizations/usersAuthorizationManager.ts 3.33 KiB {0} [built]
    + 106 hidden modules

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/
Serverless: Invoke webpack:package
Serverless: Copying existing artifacts...

 Error ---------------------------------------------------

  Error: ENOENT: no such file or directory, copyfile '/home/jacob/elucidia/repositories/portal-api/.webpack/getUser.zip' -> '.serverless/getUser.zip'
      at Object.copyFileSync (fs.js:1991:3)
      at ServerlessWebpack.copyArtifactByName (/home/jacob/elucidia/repositories/portal-api/node_modules/serverless-webpack/lib/packageModules.js:86:6)
      at /home/jacob/elucidia/repositories/portal-api/node_modules/serverless-webpack/lib/packageModules.js:133:66
      at arrayEach (/home/jacob/elucidia/repositories/portal-api/node_modules/lodash/lodash.js:530:11)
      at Function.forEach (/home/jacob/elucidia/repositories/portal-api/node_modules/lodash/lodash.js:9410:14)
      at ServerlessWebpack.copyExistingArtifacts (/home/jacob/elucidia/repositories/portal-api/node_modules/serverless-webpack/lib/packageModules.js:133:9)
      at ServerlessWebpack.tryCatcher (/home/jacob/elucidia/repositories/portal-api/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/jacob/elucidia/repositories/portal-api/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/jacob/elucidia/repositories/portal-api/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (/home/jacob/elucidia/repositories/portal-api/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (/home/jacob/elucidia/repositories/portal-api/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/home/jacob/elucidia/repositories/portal-api/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/home/jacob/elucidia/repositories/portal-api/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/home/jacob/elucidia/repositories/portal-api/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:461:21)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.15.1
     Framework Version:         2.33.1
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.8.1
```

</details>

<b>Installed version</b>

```
Framework Core: 2.33.1
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.1
```

**Comment by pgrzesik** [comment]
Hello @jacobb35, thanks for reporting. After reviewing, I feel like this is not an issue on Framework but rather on plugin side. On Framework side, when no plugins are involved, only the considered function is packaged. Until you strongly feel that it's a bug on framework side, I'd recommend reporting that issue in `serverless-webpack` repository.

**Comment by jacobb35** [comment]
> Hello @jacobb35, thanks for reporting. After reviewing, I feel like this is not an issue on Framework but rather on plugin side. On Framework side, when no plugins are involved, only the considered function is packaged. Until you strongly feel that it's a bug on framework side, I'd recommend reporting that issue in `serverless-webpack` repository.

Thanks a lot, I will raise the problem on the `serverless-webpack` side!

Have a good one!

**Comment by pgrzesik** [comment]
Thanks @jacobb35 - I'm going to close this one for now - we can reopen if that's indeed a bug on Framework side.
