### ISSUE TITLE
Breaking change made to `httpApi.authorizers.cognitoAuthorizer.identitySource` with no deprecation warning

### ISSUE THREAD

**Issue by ffxsam** [serverless/serverless#9269]
It appears there's been a change that made `sls deploy` break when parsing serverless.ts:

<img width="710" alt="image" src="https://user-images.githubusercontent.com/12532733/114063278-0ef1af80-985e-11eb-950d-8b324b6824bf.png">

This happened after doing `yarn upgrade` which upgraded the serverless dependencies.

<details>
<summary><code>serverless.yml</code></summary>

```ts
import type { AWS } from '@serverless/typescript';
import {
  xx
} from './src/functions';

const serverlessConfiguration: AWS = {
  service: 'api',
  frameworkVersion: '2',
  custom: {
    webpack: {
      webpackConfig: './webpack.config.js',
      includeModules: true,
    },
    'serverless-offline': {
      httpPort: 9001,
      ignoreJWTSignature: true,
    },
    apiHostnames: {
      dev: 'xx.com',
      prod: 'xx.com',
    },
    customDomain: {
      domainName: '${self:custom.apiHostnames.${self:provider.stage}}',
      basePath: '',
      stage: '${self:provider.stage}',
      createRoute53Record: true,
      apiType: 'http',
      certificateName: '*.xx.com',
      endpointType: 'regional',
    },
  },
  useDotenv: true,
  package: {
    individually: true,
  },
  plugins: [
    'serverless-webpack',
    'serverless-offline',
    'serverless-domain-manager',
  ],
  provider: {
    name: 'aws',
    runtime: 'nodejs12.x',
    memorySize: 256,
    versionFunctions: false,
    // @ts-ignore
    logRetentionInDays: '${env:LOG_RETENTION_DAYS}',
    stage: '${opt:stage, "dev"}',
    apiGateway: {
      minimumCompressionSize: 1024,
      shouldStartNameWithService: true,
    },
    environment: {
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1',
      SENTRY_DSN: '${env:SENTRY_DSN}',
      DB_SECRET_STORE_ARN: '${env:DB_SECRET_STORE_ARN}',
      DB_NAME: '${env:DB_NAME}',
      DB_ARN: '${env:DB_ARN}',
      STORAGE_URL: '${env:STORAGE_URL}',
    },
    lambdaHashingVersion: '20201221',
    tracing: {
      lambda: true,
    },
    httpApi: {
      authorizers: {
        cognitoAuthorizer: {
          identitySource: '$request.header.Authorization',
          issuerUrl:
            'https://cognito-idp.us-east-1.amazonaws.com/${env:USER_POOL_ID}',
          audience: [
            '${env:USER_POOL_CLIENT_ID}',
            // To satisfy a bug in serverless-offline
            'dummy',
          ],
        },
      },
      cors: true,
    },
    iam: {
      role: {
        statements: [
          {
            Effect: 'Allow',
            Action: [
              'rds-data:ExecuteSql',
              'rds-data:ExecuteStatement',
              'rds-data:BatchExecuteStatement',
              'rds-data:BeginTransaction',
              'rds-data:RollbackTransaction',
              'rds-data:CommitTransaction',
            ],
            Resource: '*',
          },
          {
            Effect: 'Allow',
            Action: 'secretsmanager:GetSecretValue',
            Resource: '*',
          },
        ],
      },
    },
  },
  functions: {
    xx
  },
};

module.exports = serverlessConfiguration;
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```

 Serverless Error ----------------------------------------

  Cannot load "serverless.ts": Initialization error: TSError: ⨯ Unable to compile TypeScript:
  serverless.ts:87:11 - error TS2322: Type 'string' is not assignable to type 'AwsCfInstruction[]'.

  87           identitySource: '$request.header.Authorization',
               ~~~~~~~~~~~~~~

    node_modules/@serverless/typescript/index.d.ts:778:15
      778               identitySource: AwsCfInstruction[];
                        ~~~~~~~~~~~~~~
      The expected type comes from property 'identitySource' which is declared here on type '{ type?: "jwt"; name?: string; identitySource: AwsCfInstruction[]; issuerUrl: AwsCfInstruction; audience: AwsCfInstruction | AwsCfInstruction[]; } | { ...; }'

      at createTSError (/Volumes/SuperData/Sites/xx/v2-api/node_modules/ts-node/src/index.ts:513:12)
      at reportTSError (/Volumes/SuperData/Sites/xx/v2-api/node_modules/ts-node/src/index.ts:517:19)
      at getOutput (/Volumes/SuperData/Sites/xx/v2-api/node_modules/ts-node/src/index.ts:752:36)
      at Object.compile (/Volumes/SuperData/Sites/xx/v2-api/node_modules/ts-node/src/index.ts:968:32)
      at Module.m._compile (/Volumes/SuperData/Sites/xx/v2-api/node_modules/ts-node/src/index.ts:1056:42)
      at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
      at Object.require.extensions.<computed> [as .ts] (/Volumes/SuperData/Sites/xx/v2-api/node_modules/ts-node/src/index.ts:1059:12)
      at Module.load (internal/modules/cjs/loader.js:863:32)
      at Function.Module._load (internal/modules/cjs/loader.js:708:14)
      at Module.require (internal/modules/cjs/loader.js:887:19)
      at require (internal/modules/cjs/helpers.js:74:18)
      at /Volumes/SuperData/Sites/xx/v2-api/node_modules/serverless/lib/configuration/read.js:121:18
      at parseConfigurationFile (/Volumes/SuperData/Sites/xx/v2-api/node_modules/serverless/lib/configuration/read.js:136:9)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at module.exports (/Volumes/SuperData/Sites/xx/v2-api/node_modules/serverless/lib/configuration/read.js:163:23)
      at /Volumes/SuperData/Sites/xx/v2-api/node_modules/serverless/scripts/serverless.js:112:22
      at /Volumes/SuperData/Sites/xx/v2-api/node_modules/serverless/scripts/serverless.js:110:11

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.20.1
     Framework Version:         2.34.0 (local)
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.8.2
```

</details>

<b>Installed version</b>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.34.0 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.2
```

**Comment by pgrzesik** [comment]
Hello @ffxsam :wave: Thanks for reporting and sorry you've run into trouble. While on the Framework side the schema is correct, I've noticed that the `serverless/typescript` has troubles with generating correct schema for `array` type, which in the Framework case also accept single values and coerces them to array with one element. I've proposed a small PR that should address this specific case.

**Comment by ffxsam** [comment]
Thanks @pgrzesik!
