### ISSUE TITLE
Pseudo parameters with variables doesn't work on the authorizer property 

### ISSUE THREAD

**Issue by ricardomozartlino** [serverless/serverless#9360]
As mentioned in the plugin [serverless pseudo parameters], sls framework now supports pseudo parameters natively.
```This is now natively supported in Serverless Framework 2.3.0, this plugin should still work, but I advise you to upgrade.```

But unfortunately the authorizer arn property does not seem to support the !Sub cloudformation function

when I do that I got the error bellow:
```yaml
authorizer:
      arn: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:xxx-v1-${self:provider.stage}-authorizer
```
```shell
TypeError: functionArn.split is not a function
```

am I missing something?

<details>
<summary><code>serverless.yml</code></summary>

```yaml

custom:
  authorizer:
      arn: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:xxx-v1-${self:provider.stage}-authorizer
      resultTtlInSeconds: 0
      identitySource: method.request.header.Cookie
      type: request

functions:
  person:
    handler: src/handler.default
    description: ""
    events:
      - http:
          method: any
          path: /get-xxx-details
          authorizer: ${self:custom.authorizer}
```

</details>

<details>
<summary><b><code>sls package</code> output</b></summary>

```shell
Serverless: Packaging service...
 
  Type Error ---------------------------------------------
 
  TypeError: functionArn.split is not a function
      at Object.extractAuthorizerNameFromArn (/Users/kadu/Documents/workspace/dgx-common-person-service/node_modules/serverless/lib/plugins/aws/lib/naming.js:136:34)
      at AwsCompileApigEvents.getAuthorizer (/Users/kadu/Documents/workspace/dgx-common-person-service/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js:241:39)
      at /Users/kadu/Documents/workspace/dgx-common-person-service/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js:52:36
      at Array.forEach (<anonymous>)
      at /Users/kadu/Documents/workspace/dgx-common-person-service/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js:44:37
      at Array.forEach (<anonymous>)
      at AwsCompileApigEvents.validate (/Users/kadu/Documents/workspace/dgx-common-person-service/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js:43:55)
      at Object.package:compileEvents [as hook] (/Users/kadu/Documents/workspace/dgx-common-person-service/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/index.js:251:31)
      at /Users/kadu/Documents/workspace/dgx-common-person-service/node_modules/serverless/lib/classes/PluginManager.js:510:55
      at tryCatcher (/Users/kadu/Documents/workspace/dgx-common-person-service/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/Users/kadu/Documents/workspace/dgx-common-person-service/node_modules/bluebird/js/release/reduce.js:168:18)
      at Object.gotAccum (/Users/kadu/Documents/workspace/dgx-common-person-service/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (/Users/kadu/Documents/workspace/dgx-common-person-service/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/kadu/Documents/workspace/dgx-common-person-service/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/kadu/Documents/workspace/dgx-common-person-service/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/Users/kadu/Documents/workspace/dgx-common-person-service/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/Users/kadu/Documents/workspace/dgx-common-person-service/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/Users/kadu/Documents/workspace/dgx-common-person-service/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/Users/kadu/Documents/workspace/dgx-common-person-service/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/Users/kadu/Documents/workspace/dgx-common-person-service/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/Users/kadu/Documents/workspace/dgx-common-person-service/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:458:21)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.8.0
     Framework Version:         2.19.0
     Plugin Version:            4.4.2
     SDK Version:               2.3.2
     Components Version:        3.4.7
 
```

</details>

<b>Installed version</b>

```
Framework Core: 2.19.0
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.4.7
```

[serverless pseudo parameters]: https://www.npmjs.com/package/serverless-pseudo-parameters

**Comment by pgrzesik** [comment]
Hello - in this case it's not supported, because while `Sub` is supported, it's resolved on the CloudFormation side, while the plugin resolved it beforehand. In your particular use case, you can either continue using the plugin. Alternatively, supplying the `name` for authorizer should also resolve that issue. Please let me know if that helped in any way.

**Comment by HXMOZARR** [comment]
> Alternatively, supplying the `name` for authorizer should also resolve that issue.

Do you mean

**Comment by HXMOZARR** [comment]
Can we add support for this property to accept cloudformation functions? I can open a PR (if this functionality is possible, of course).

I don't want to use the plugin since they already closed(Archived) it.

So is it possible?

**Comment by HXMOZARR** [comment]
@pgrzesik, what do you think?

**Comment by pgrzesik** [comment]
Hello @HXMOZARR, sorry for not responding sooner, I've missed your message. I believe we should be able to support it by also requiring to provide `name` for authorizer in such cases, because extracting name from `Sub` is not reliable. The implementation should be adjusted here: https://github.com/serverless/serverless/blob/f5b2b9be395c9c2d3de4c4f91f991276bc22dc33/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js#L198

**Comment by ricardomozartlino** [comment]
`supplying the name for authorizer should also resolve that issue`

I didn't understand before, I added the name and everything works perfectly. I will close this issue!
