### ISSUE TITLE
Cannot read property 'defineFunctionProperties' of undefined

### ISSUE THREAD

**Issue by tsyedr** [serverless/serverless#9381]
serverless package --stage dev
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
 
  Type Error ---------------------------------------------
 
  Cannot read property 'defineFunctionProperties' of undefined
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
TypeError: Cannot read property 'defineFunctionProperties' of undefined
    at new AlertsPlugin (/mnt/data/jenkins/workspace/rvice-available-modalities_PR-87/node_modules/serverless-plugin-aws-alerts/src/index.js:13:36)
    at PluginManager.addPlugin (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:64:28)
    at plugins.forEach (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:107:14)
    at Array.forEach (<anonymous>)
    at PluginManager.loadPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:101:13)
    at PluginManager.loadServicePlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:156:10)
    at PluginManager.loadAllPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:96:10)
    at pluginManager.loadConfigFile.then.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:74:26)
From previous event:
    at Serverless.init (/usr/local/lib/node_modules/serverless/lib/Serverless.js:72:8)
    at initializeErrorReporter.then (/usr/local/lib/node_modules/serverless/bin/serverless:42:21)
    at processImmediate (internal/timers.js:443:21)
    at process.topLevelDomainCallback (domain.js:136:23)
From previous event:
    at /usr/local/lib/node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:65:4)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     OS:                     linux
     Node Version:           11.15.0
     Serverless Version:     1.46.1

**Comment by yyamano** [comment]
@tsyedr similar issue is reported to serverless-plugin-aws-alerts repo. See https://github.com/ACloudGuru/serverless-plugin-aws-alerts/issues/173 for workaround.

**Comment by pgrzesik** [comment]
Hello @tsyedr - looks like you're using quite outdated version of the Serverless Framework. Is there anything that is stopping you from an upgrade?

**Comment by tsyedr** [comment]
Upgrading serverless and serverless-plugin-aws-alerts resolved the issue. Thanks

**Comment by tomchiverton** [comment]
I've done npm i serverless-plugin-aws-alerts serverless-mysql serverless

```
...
+ serverless-mysql@1.5.4
+ serverless-plugin-aws-alerts@1.7.4
+ serverless@2.64.1
added 630 packages from 391 contributors, updated 3 packages and audited 652 packages in 118.474s
...
```

yet still

```
$ sls deploy --aws-profile serverless-dev-extravision --stage live
 
  Type Error ---------------------------------------------
 
  TypeError: Cannot read property 'defineFunctionProperties' of undefined
      at new AlertsPlugin (/home/falken/workspace/serverless/bt-serverless-quiz/node_modules/serverless-plugin-aws-alerts/src/index.js:13:36)
      at PluginManager.addPlugin (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:84:28)
      at /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:121:31
      at Array.forEach (<anonymous>)
      at PluginManager.loadAllPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:121:8)
      at /usr/local/lib/node_modules/serverless/lib/Serverless.js:98:35
```

**Comment by tomchiverton** [comment]
Setting in `package.json` the plugin version to "1.6.1" fixes it
