### ISSUE TITLE
Function deploy fails when subnetIds uses Fn::Split

### ISSUE THREAD

**Issue by MikeRippon** [serverless/serverless#9423]
When `"Fn::split"` is used in `subnetIds` property, `serverless deploy -f hello` fails with the following message:

```
Expected params.VpcConfig.SubnetIds to be an Array
```

Running a full `serverless deploy` works as expected (no error, subnet string is split correctly).

This makes deploying a single function impossible if the subnet ids need to be parameterized (e.g. by retrieving from an SSM parameter).

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: serverless-subnet-bug
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  vpc:
    securityGroupIds: 
      - sg-mysecretsecuritygroup
    subnetIds:
      "Fn::Split":
        - ","
        - "subnet-1,subnet-2,subnet-3" # In practice, get these from SSM

functions:
  hello:
    handler: handler.hello
```

</details>

<details>
<summary><b><code>serverless deploy -f hello</code> output</b></summary>

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Configuration warning at 'provider.vpc.subnetIds['Fn::Split'][1]': unsupported configuration format
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Deprecation warning: Starting with next major, Serverless will throw on configuration errors by default. Adapt to this behavior now by adding "configValidationMode: error" to service configuration
            More Info: https://www.serverless.com/framework/docs/deprecations/#CONFIG_VALIDATION_MODE_DEFAULT
Serverless: Invoke deploy
Serverless: Invoke deploy:function
Serverless: Invoke package:function
Serverless: Packaging function: hello...
Serverless: Excluding development dependencies...
Serverless: Code not changed. Skipping function deployment.

 Serverless Error ----------------------------------------

  ServerlessError: InvalidParameterType: Expected params.VpcConfig.SubnetIds to be an Array
      at ParamValidator.fail (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\param_validator.js:50:37)
      at ParamValidator.validateType (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\param_validator.js:232:10)
      at ParamValidator.validateList (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\param_validator.js:99:14)
      at ParamValidator.validateMember (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\param_validator.js:90:21)
      at ParamValidator.validateStructure (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\param_validator.js:75:14)
      at ParamValidator.validateMember (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\param_validator.js:88:21)
      at ParamValidator.validateStructure (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\param_validator.js:75:14)
      at ParamValidator.validateMember (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\param_validator.js:88:21)
      at ParamValidator.validate (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\param_validator.js:34:10)
      at Request.VALIDATE_PARAMETERS (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\event_listeners.js:132:42)
      at Request.callListeners (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
      at callNextListener (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\sequential_executor.js:96:12)
      at C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\event_listeners.js:86:9
      at finish (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\config.js:386:7)
      at C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\config.js:404:9
      at SharedIniFileCredentials.get (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\credentials.js:127:7)
      at getAsyncCredentials (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\config.js:398:24)
      at Config.getCredentials (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\config.js:418:9)
      at Request.VALIDATE_CREDENTIALS (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\event_listeners.js:81:26)
      at Request.callListeners (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\sequential_executor.js:102:18)
      at Request.emit (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
      at Request.emit (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\request.js:688:14)
      at Request.transition (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\request.js:22:10)
      at AcceptorStateMachine.runTo (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\state_machine.js:14:12)
      at Request.runTo (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\request.js:408:15)
      at C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\request.js:797:12
      at new Promise (<anonymous>)
      at Request.promise (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\request.js:783:12)
      at C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\lib\aws\request.js:174:26
      at persistentRequest (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\lib\aws\request.js:140:20)
      at Object.promiseGenerator (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\lib\aws\request.js:170:5)
      at Queue._dequeue (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\promise-queue\lib\index.js:153:30)
      at C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\promise-queue\lib\index.js:109:18
      at new Promise (<anonymous>)
      at Queue.add (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\node_modules\promise-queue\lib\index.js:94:16)
      at awsRequest (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\lib\aws\request.js:169:38)
      at AwsProvider.request (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\provider.js:1396:60)
      at callWithRetry (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deployFunction.js:145:29)
      at AwsDeployFunction.callUpdateFunctionConfiguration (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deployFunction.js:166:11)
      at AwsDeployFunction.updateFunctionConfiguration (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deployFunction.js:361:16)
      at Object.deploy:function:deploy [as hook] (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deployFunction.js:55:20)
      at async PluginManager.invoke (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:565:9)
      at async PluginManager.spawn (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:587:5)
      at async Object.before:deploy:deploy [as hook] (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\lib\plugins\deploy.js:42:11)
      at async PluginManager.invoke (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:565:9)
      at async PluginManager.run (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:616:7)
      at async Serverless.run (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:324:5)
      at async C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\scripts\serverless.js:649:9
  ----------------------------------------------------------------------------------------------------
      at C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\lib\aws\request.js:202:11
      at async persistentRequest (C:\Users\miker\AppData\Roaming\npm\node_modules\serverless\lib\aws\request.js:140:14)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              14.16.0
     Framework Version:         2.39.1
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.9.1
```

</details>

<b>Installed version</b>

```
Framework Core: 2.39.1
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.9.1
```

**Comment by pgrzesik** [comment]
Hello @MikeRippon - thanks for reporting and sorry you've run into trouble. We should definitely not fail in such situations, however, as the `deploy function` uses SDK calls instead of CloudFormation(https://github.com/serverless/serverless/blob/42bbfecd51f0f403668090e38db6141bdeb70a1a/lib/plugins/aws/deployFunction.js#L288), the `vpc` configuration should not be updated in such situations. The "offending" piece of code is here - I'll submit a PR for that and it will be released probably sometime later this week.
