### ISSUE TITLE
Serverless command "create_domain" not found. Run "serverless help" for a list of all available commands

### ISSUE THREAD

**Issue by stefanhorning** [serverless/serverless#9426]
## Describe the issue
when running the `serverless create_domain` subcommand I get this error:

`Serverless command "create_domain" not found. Run "serverless help" for a list of all available commands.`

However when running serverless help I get this output:

```
Serverless: Resolution of service configuration failed when resolving variables: 
  - Cannot resolve variable at "provider.stage": Value not found at "opt" source

Serverless: Running "serverless" installed locally (in service node_modules)

Commands
* You can run commands with "serverless" or the shortcut "sls"
* Pass "--verbose" to this command to get in-depth plugin info
* Pass "--no-color" to disable CLI colors
* Pass "--help" after any <command> for contextual help

Interactive Quickstart
* Run serverless (or shortcut sls) without any arguments to initialize an interactive setup
  of functionalities related to given service or current environment
* Pass "--help-interactive" for contextual help on interactive CLI options

Framework
* Documentation: http://slss.io/docs

Environment Variables
* Set SLS_DEBUG=* to see debugging logs
* Set SLS_WARNING_DISABLE=* to hide warnings from the output

config ........................ Configure Serverless
config credentials ............ Configures a new provider profile for the Serverless Framework
config tabcompletion install .. Install a <tab> completion for chosen shell
config tabcompletion uninstall  Uninstall a <tab> completion for chosen shell
create ........................ Create new Serverless service
install ....................... Install a Serverless service from GitHub or a plugin from the Serverless registry
package ....................... Packages a Serverless service
deploy ........................ Deploy a Serverless service
deploy function ............... Deploy a single function from the service
deploy list ................... List deployed version of your Serverless Service
deploy list functions ......... List all the deployed functions and their versions
invoke ........................ Invoke a deployed function
invoke local .................. Invoke function locally
info .......................... Display information about the service
logs .......................... Output the logs of a deployed function
metrics ....................... Show metrics for a specific function
print ......................... Print your compiled and resolved config file
remove ........................ Remove Serverless service and all resources
rollback ...................... Rollback the Serverless service to a specific deployment
rollback function ............. Rollback the function to a specific version
slstats ....................... Enable or disable stats
plugin ........................ Plugin management for Serverless
plugin install ................ Install and add a plugin to your service
plugin uninstall .............. Uninstall and remove a plugin from your service
plugin list ................... Lists all available plugins
plugin search ................. Search for plugins
create_domain ................. Creates a domain using the domain name defined in the serverless file
delete_domain ................. Deletes a domain using the domain name defined in the serverless file
offline ....................... Simulates API Gateway to call your lambda functions offline.
offline start ................. Simulates API Gateway to call your lambda functions offline using backward compatible initialization.
login ......................... Login or sign up for Serverless
logout ........................ Logout from Serverless
generate-event ................ Generate event
test .......................... Run HTTP tests
dashboard ..................... Open the Serverless dashboard
output ........................ 
output get .................... Get value of dashboard deployment profile parameter
output list ................... List all dashboard deployment profile parameters
param ......................... 
param get ..................... Get value of dashboard service output
param list .................... List all dashboard service outputs

Plugins
ApiGatewayCachingPlugin, ApiGwyBinaryPlugin, AwsCommon, AwsCompileAlbEvents, AwsCompileAlexaSkillEvents, AwsCompileAlexaSmartHomeEvents, AwsCompileApigEvents, AwsCompileCloudFrontEvents, AwsCompileCloudWatchEventEvents, AwsCompileCloudWatchLogEvents, AwsCompileCognitoUserPoolEvents, AwsCompileEventBridgeEvents, AwsCompileFunctions, AwsCompileIoTEvents, AwsCompileLayers, AwsCompileS3Events, AwsCompileSNSEvents, AwsCompileSQSEvents, AwsCompileScheduledEvents, AwsCompileStreamEvents, AwsCompileWebsockets, AwsConfigCredentials, AwsDeploy, AwsDeployFunction, AwsDeployList, AwsInfo, AwsInvoke, AwsInvokeLocal, AwsLogs, AwsMetrics, AwsPackage, AwsProvider, AwsRemove, AwsRollback, AwsRollbackFunction, BinarySupport, Config, Create, Deploy, Executable, Info, Install, InteractiveCli, Invoke, Logs, Metrics, Package, Plugin, PluginInstall, PluginList, PluginSearch, PluginUninstall, Print, Remove, Rollback, ServerlessCustomDomain, ServerlessEnterprisePlugin, ServerlessOffline, SlStats
```

I have installed the serverless command with `nvm install -g serverless`. And just run npm install for the project itself which brings in all plugins. As it didn't work I also tried the global install for the serververless-domain-manager package, without any change.

Anyhow this is clearly a bug in the resolving in commands, as the plugin clearly correctly installed as serverless help indicates.

Also I have this section in my serverless.yml:

```
plugins:
  - serverless-api-gateway-caching
  - serverless-apigw-binary
  - serverless-apigwy-binary
  - serverless-domain-manager
  - serverless-offline
```

## Full Output of `serverless create_domain` command:

```
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command create_domain
Serverless: Load command delete_domain
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
 
 Serverless Error ----------------------------------------
 
  ServerlessError: Serverless command "create_domain" not found. Run "serverless help" for a list of all available commands.
      at module.exports (/home/stefan/.nvm/versions/node/v14.16.1/lib/node_modules/serverless/lib/cli/ensure-supported-command.js:38:11)
      at /home/stefan/.nvm/versions/node/v14.16.1/lib/node_modules/serverless/scripts/serverless.js:440:55
      at /home/stefan/.nvm/versions/node/v14.16.1/lib/node_modules/serverless/scripts/serverless.js:642:9
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.16.1
     Framework Version:         2.39.1 (local)
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.9.1
 
 
 Type Error ----------------------------------------------
 
  TypeError: Cannot read property 'options' of undefined
      at module.exports (/home/stefan/.nvm/versions/node/v14.16.1/lib/node_modules/serverless/lib/utils/telemetry/generatePayload.js:133:66)
      at module.exports (/home/stefan/.nvm/versions/node/v14.16.1/lib/node_modules/serverless/lib/cli/handle-error.js:145:30)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.16.1
     Framework Version:         2.39.1 (local)
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.9.1
 

/home/stefan/.nvm/versions/node/v14.16.1/lib/node_modules/serverless/lib/utils/telemetry/generatePayload.js:133
  const availableOptionNames = new Set(Object.keys(commandSchema.options));
                                                                 ^
TypeError: Cannot read property 'options' of undefined
    at module.exports (/home/stefan/.nvm/versions/node/v14.16.1/lib/node_modules/serverless/lib/utils/telemetry/generatePayload.js:133:66)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at module.exports (/home/stefan/.nvm/versions/node/v14.16.1/lib/node_modules/serverless/lib/cli/handle-error.js:145:30)
```

The `TypeError: Cannot read property 'options' of undefined` is another issue, but maybe worth another ticket.

## Serverless version output

```
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 1.61.3
Plugin: 3.3.0
SDK: 2.3.0
Components Core: 1.1.2
Components CLI: 1.4.0
```

**Comment by stefanhorning** [comment]
there is also stackoverflow issue about this already https://stackoverflow.com/questions/67224273/serverless-command-create-domain-not-found (not by me).

**Comment by pgrzesik** [comment]
Hello @stefanhorning, thanks for reporting. I'm a bit confused about reporting of versions - according to the error output, locally you're using `2.39.1` version of the Framework, but in version output you're reporting use of `1.61.3`. Could you please confirm what global and local version are you using? I've tried to reproduce your issue but so far without much luck. Could you please also share a minimal reproducible example of `serverless.yml` with anonymized data? It would be much appreciated.

**Comment by stefanhorning** [comment]
The version missmatch might stem from installing the serverless command with `nvm install -g serverless` (global install) while the project I am using it in has serverless in it's package.json too, locking in a different version. But it's a good point, I will try to align both versions by changing the package.json perhaps.

But the confusion is still there, why it would use one version (or executable?) for some stuff while using another version for other. Thus maybe not finding plugins in one run but not in the other, while the serverless comand should always point to the same executable.

**Comment by stefanhorning** [comment]
So I solved the problem now by aligning versions. A few things are still weird though, hence I will put a few details here.

When I was in my projects dir with the package.json saying serverless: 1.61.3 I got this output for serverless --version:

```
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 1.61.3
Plugin: 3.3.0
SDK: 2.3.0
Components Core: 1.1.2
Components CLI: 1.4.0
```

Outside this dir it would say:
```
Framework Core: 2.39.1
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.9.1
```

Which kind of makes sense so far. Also note the extra message `Serverless: Running "serverless" installed locally (in service node_modules)`.

However when changing back into the project dir where it would use the locally installed version and I run serverless create_version (or any other non working subcommand). It would still print the Running serverless locally message but with a different version!

```
Serverless: Running "serverless" installed locally (in service node_modules)
 
 Serverless Error ----------------------------------------
 
  Serverless command "create_version" not found. Run "serverless help" for a list of all available commands.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.16.1
     Framework Version:         2.39.1 (local)
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.9.1
```

So this can't be right. Either it runs the local version, but then it would be 1.61.3, or it doesn't (which it looks like), then it's the 2.39.1, which also doesn't know about any plugins. I just don't know what mechanism makes the version change "randomly" here. But it's definetely using different executables depending if you use a subcommand or not.

So the way to solve it is simple (once understood):
change `package.json` in your project to match the version globally installed (only reliably testable when leaving project dir and doing `serverless --version`).

In my case looks like this:
```
    "serverless": "^2.39.1",
    "serverless-api-gateway-caching": "*",
    "serverless-apigw-binary": "*",
    "serverless-apigwy-binary": "*",
    "serverless-domain-manager": "*",
```

Remove any lock files if present (or use nvm upgrade), then do a nvm install.

After that subcommand will work again.

@pgrzesik Thanks for your help. Also I don't think the serverless.yml is relevant here. It's about loading executables/paths etc. Maybe my nvm setup, maybe serverless code issue etc.

**Comment by pgrzesik** [comment]
Thanks a lot for the detailed overview @stefanhorning :bow: Generally it should work without issues, however, when older versions are involved (such as `1.61.3`), then we might have situations where the error might report the version incorrectly - it has been resolved in newer versions of the Framework. It should still work correctly even if the versions are not exactly the same for local and global and when falling back to local version, it will use the locally installed plugins, not the ones installed globally.

**Comment by pgrzesik** [comment]
It should be no longer an issue with the new `2.40.0` version. Thank you @stefanhorning :bow:
