### ISSUE TITLE
Cannot find module './stores/memory.js'

### ISSUE THREAD

**Issue by Goufix** [serverless/serverless#9450]
I'm trying to change from a server aplication to a serverless one based on my needs. I've made all the steps to make it work. Based mainly on that [tutorial](https://nishabe.medium.com/nestjs-serverless-lambda-aws-in-shortest-steps-e914300faed5).

When I run the aplication locally using `sls offline start`, it runs and works perfectly.

The real problem comes when I try to deploy it. The deploy comes successfully, but when I call any application route, it turns an `502 - Bad gateway / internal server errror`. Trying to see the logs, there's an error called: `Cannot find module './stores/memory.js'`. And there's no stacktrace too.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service:
  name: snackin-integrator

package:
  exclude:
    - './**'
    - '!node_modules/**'
    - '!dist/**'
    - '.git/**'

plugins:
  - 'serverless-plugin-typescript'
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x

functions:
  main: # The name of the lambda function
    # The module 'handler' is exported in the file 'src/lambda'
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}
```

</details>

<details>
<summary><b><code>sls logs -f main</code> output</b></summary>

```
Serverless: Deprecation warning: Detected ".env" files. In the next major release variables from ".env" files will be automatically loaded into the serverless build process. Set "useDotenv: true" to adopt that behavior now.
            More Info: https://www.serverless.com/framework/docs/deprecations/#LOAD_VARIABLES_FROM_ENV_FILES
Serverless: Deprecation warning: Starting from next major object notation for "service" property will no longer be recognized. Set "service" property directly with service name.
            More Info: https://www.serverless.com/framework/docs/deprecations/#SERVICE_OBJECT_NOTATION
Serverless: DOTENV: Loading environment variables from .env:
Serverless:      - GOOGLE_MAPS_API_KEY
Serverless:      - DB_DATABASE
Serverless:      - DB_USER
Serverless:      - DB_PASSWORD
Serverless:      - DB_HOST
Serverless:      - DB_PORT
Serverless:      - BUGSNAG_API_KEY
Serverless:      - VMPAY_BASE_URL
Serverless:      - VMPAY_ACCESS_TOKEN
Serverless:      - NODE_ENV
Serverless:      - SANKHYA_BASE_URL
Serverless:      - SANKHYA_USERNAME
Serverless:      - SANKHYA_PASSWORD
Serverless:      - SANKHYA_SNACKIN_ID
Serverless:      - SANKHYA_SNACKIN_PARTNER_ID
Serverless:      - SANKHYA_SNACKIN_NEGOCIATION_TYPE
Serverless:      - SANKHYA_COMPANY
Serverless:      - START_DATE_CHECK
Serverless:      - ENABLE_ROUTINES
Serverless: Deprecation warning: Support for "package.include" and "package.exclude" will be removed with next major release. Please use "package.patterns" instead
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_PACKAGE_PATTERNS
Serverless: Deprecation warning: Resolution of lambda version hashes was improved with better algorithm, which will be used in next major release.
            Switch to it now by setting "provider.lambdaHashingVersion" to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
START RequestId: 06b8e3fc-59ec-4d5c-8772-8a36b0664266 Version: $LATEST
2021-05-10 09:57:00.288 (-03:00)        undefined       ERROR   (node:9) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[Nest] 9   - 05/10/2021, 12:57:00 PM   [NestFactory] Starting Nest application...
2021-05-10 09:57:00.524 (-03:00)        06b8e3fc-59ec-4d5c-8772-8a36b0664266    DEBUG   [bugsnag] Loaded!
[Nest] 9   - 05/10/2021, 12:57:00 PM   [InstanceLoader] AppModule dependencies initialized +193ms
[Nest] 9   - 05/10/2021, 12:57:00 PM   [InstanceLoader] DatabaseModule dependencies initialized +0ms
[Nest] 9   - 05/10/2021, 12:57:00 PM   [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 9   - 05/10/2021, 12:57:00 PM   [InstanceLoader] BugsnagModule dependencies initialized +1ms
[Nest] 9   - 05/10/2021, 12:57:00 PM   [InstanceLoader] HttpModule dependencies initialized +0ms
[Nest] 9   - 05/10/2021, 12:57:00 PM   [InstanceLoader] HttpModule dependencies initialized +0ms
[Nest] 9   - 05/10/2021, 12:57:00 PM   [InstanceLoader] ConfigHostModule dependencies initialized +1ms
[Nest] 9   - 05/10/2021, 12:57:00 PM   [ExceptionHandler] Cannot find module './stores/memory.js'
Require stack:
- /var/task/_optimize/snackin-integrator-dev-main/src/lambda.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js +1ms
Error: Cannot find module './stores/memory.js'
Require stack:
- /var/task/_optimize/snackin-integrator-dev-main/src/lambda.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
at Function.Module._load (internal/modules/cjs/loader.js:725:27)
at Module.require (internal/modules/cjs/loader.js:952:19)
at require (internal/modules/cjs/helpers.js:88:18)
at o (/var/task/_optimize/snackin-integrator-dev-main/src/lambda.js:1:492)
at /var/task/_optimize/snackin-integrator-dev-main/src/lambda.js:1:683
at Object.caching (/var/task/_optimize/snackin-integrator-dev-main/src/lambda.js:33602:22)
at InstanceWrapper.useFactory [as metatype] (/var/task/_optimize/snackin-integrator-dev-main/src/lambda.js:4834:46)
at Injector.instantiateClass (/var/task/_optimize/snackin-integrator-dev-main/src/lambda.js:11515:55)
at callback (/var/task/_optimize/snackin-integrator-dev-main/src/lambda.js:11268:41)
END RequestId: 06b8e3fc-59ec-4d5c-8772-8a36b0664266
REPORT RequestId: 06b8e3fc-59ec-4d5c-8772-8a36b0664266  Duration: 217.11 ms     Billed Duration: 218 ms Memory Size: 1024 MB     Max Memory Used: 180 MB Init Duration: 1042.96 ms

RequestId: 06b8e3fc-59ec-4d5c-8772-8a36b0664266 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

</details>

<b>Installed version</b>

```
Framework Core: 2.40.0
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.9.2
```

**Comment by pgrzesik** [comment]
Hello @Goufix, this tracker is intended for bugs and enhancement proposals, I will move this to Discussions.
