### ISSUE TITLE
S3 artifact uploads fail with inaccessible host

### ISSUE THREAD

**Issue by johnclarke94** [serverless/serverless#9461]
S3 artifact upload fails consistently with the following error

```
Serverless: Recoverable error occurred (Inaccessible host: `my-bucket-name.s3.eu-west-1.amazonaws.com'. This service may not be available in the `eu-west-1' region.), sleeping for ~4 seconds. Try 1 of 4
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: my-service
frameworkVersion: '>=2.41.0'

provider:
  name: aws
  runtime: java11
  region: eu-west-1
  stage: test
  deploymentBucket: my-bucket-name
  versionFunctions: false
  timeout: 30
  memorySize: 512

package:
  artifact: my-jar.jar

functions:
  Register:
    handler: com.test.MyHandler
    events:
      - http:
          path: foo/bar
          method: post
```

</details>

<details>
<summary><b><code>sls deploy -v</code> output</b></summary>

```
sls deploy -v
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading my-jar.jar file to S3 (26.96 MB)...
Serverless: Recoverable error occurred (UnknownEndpoint: Inaccessible host: `my-bucket-name.s3.eu-west-1.amazonaws.com'. This service may not be available in the `eu-west-1' region.
    at Request.ENOTFOUND_ERROR (<PATH>/node_modules/aws-sdk/lib/event_listeners.js:507:46)
    at Request.callListeners (<PATH>/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (<PATH>/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (<PATH>/node_modules/aws-sdk/lib/request.js:688:14)
    at ClientRequest.error (<PATH>/node_modules/aws-sdk/lib/event_listeners.js:339:22)
    at ClientRequest.<anonymous> (<PATH>/node_modules/aws-sdk/lib/http/node.js:96:19)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:485:12)
    at TLSSocket.socketErrorListener (_http_client.js:467:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:485:12)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
----------------------------------------------------------------------------------------------------), sleeping for ~7 seconds. Try 1 of 4
```

</details>

<b>Installed version</b>

```
Framework Core: 2.41.0 (standalone)
Plugin: 4.6.0
SDK: 4.2.2
Components: 3.9.2
```

**Comment by pgrzesik** [comment]
Hello @johnclarke94, thanks for reporting. Does the `my-bucket-name` already exist and do you have access to it? It seems like a pretty generic name that is probably already taken. Does that issue started to happen for `2.41.0` or you experienced it for previous versions as well?

**Comment by johnclarke94** [comment]
Interestingly I can see the file `compiled-cloudformation-template.json` was uploaded successfully to the bucket

**Comment by pgrzesik** [comment]
Does other people on your team can succesfully deploy/upload to the bucket while you cannot access it? It seems to me like it's some kind of intermittent issue with DNS (or internal resolution mechanism for S3) where it cannot resolve path to your bucket.

**Comment by johnclarke94** [comment]
I've noticed that uploads are successful when the artifact size is a below a certain limit. This suggests the cause is something external and not at all relevant to the framework. Thank you very much for your assistance @pgrzesik and apologies for any time wasted!

**Comment by pgrzesik** [comment]
No worries @johnclarke94 :+1:
