### ISSUE TITLE
serverless function run - produce SUtils.fileReadSync TypeError

### ISSUE THREAD

**Issue by EchoZulu** [serverless/serverless#947]
os windows7 
serverless version 0.5.2

When i run `sls function run` on  clean project serverless project its ends with error.

> sls function run
C:\...\node_modules\serverless\node_modules\bluebird\js\release\async.js:49
        fn = function () { throw arg; };
                           ^
TypeError: SUtils.fileReadSync is not a function
    at FunctionRun._validateAndPrepare (C:\...\node_modules\serverless\lib\actions\FunctionRun.js:114:40)
From previous event:
    at FunctionRun.functionRun (C:\...\node_modules\serverless\lib\actions\FunctionRun.js:81:10)
From previous event:
    at C:\...\node_modules\serverless\lib\Serverless.js:185:31
    at Array.reduce (native)
    at C:\...\node_modules\serverless\lib\Serverless.js:184:32
From previous event:
    at Serverless._execute (C:\...\node_modules\serverless\lib\Serverless.js:182:12)
    at Serverless.actions.(anonymous function) (C:\...\node_modules\serverless\lib\Serverless.js:428:20)
    at Serverless.command (C:\...\node_modules\serverless\lib\Serverless.js:397:38)
    at C:\...\node_modules\serverless\bin\serverless:19:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Object.<anonymous> (C:\...\node_modules\serverless\bin\serverless:18:4)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

**Comment by eahefnawy** [comment]
Yep! I've noticed this one and pushed a fix to master. Not released yet though. If you could work out of master you shouldn't see this issue again :blush:
