### ISSUE TITLE
resolveVariable errors when passed an s3:bucket/key source

### ISSUE THREAD

**Issue by rally25rs** [serverless/serverless#9478]
When using a `file(whatever.js)` with `variablesResolutionMode "20210326"` the `resolveVariable` function errors if passed `s3:bucket/key`

<details>

platformConfig.js
```js
module.exports = async ({ options, resolveVariable }) => {
  const config = await resolveVariable(`s3:whateverbucket/exports/${options.stage}/config.json`);
  return JSON.parse(config);
};
```

```yaml
service: whatever
variablesResolutionMode: "20210326"

custom:
  stage: ${opt:stage}
  platformConfig: ${file(./platformConfig.js)}
```

</details>

<details>
<summary><b><code>yarn run serverless deploy -s whatever</code> output</b></summary>

```
 Serverless Error ----------------------------------------

  Cannot resolve serverless.yml: Variables resolution errored with:
    - Cannot resolve variable at "custom.platformConfig": Cannot resolve "platformConfig.js": Returned JS function errored with: ServerlessError: Cannot resolve variable at "custom.platformConfig": Value not found at "s3" source
      at VariablesResolver.resolveVariable (/whateverproject/node_modules/serverless/lib/configuration/variables/resolve.js:202:30)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async /whateverproject/node_modules/serverless/lib/configuration/variables/resolve.js:88:9
      at async Promise.all (index 0)
      at async VariablesResolver.resolveVariables (/whateverproject/node_modules/serverless/lib/configuration/variables/resolve.js:82:5)
      at async resolveVariable (/whateverproject/node_modules/serverless/lib/configuration/variables/resolve.js:503:13)
      at async module.exports (/whateverproject/services/api/resources/platformConfig.js:2:18)
      at async /whateverproject/node_modules/serverless/lib/configuration/variables/sources/file.js:126:22
      at async Object.resolve (/whateverproject/node_modules/serverless/lib/configuration/variables/sources/file.js:62:21)
      at async VariablesResolver.Object.defineProperties.memoizeMethods.resolveSource.d.normalizer.type.type (/whateverproject/node_modules/serverless/lib/configuration/variables/resolve.js:472:24)
      at async /whateverproject/node_modules/serverless/lib/configuration/variables/resolve.js:243:20
      at async VariablesResolver.resolveVariableSource (/whateverproject/node_modules/serverless/lib/configuration/variables/resolve.js:241:9)
      at async VariablesResolver.resolveVariable (/whateverproject/node_modules/serverless/lib/configuration/variables/resolve.js:157:24)
      at async /whateverproject/node_modules/serverless/lib/configuration/variables/resolve.js:88:9
      at async Promise.all (index 0)
      at async VariablesResolver.resolveVariables (/whateverproject/node_modules/serverless/lib/configuration/variables/resolve.js:82:5)
      at async VariablesResolver.self (/whateverproject/node_modules/serverless/lib/configuration/variables/resolve.js:363:9)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.18.3
     Framework Version:         2.41.2 (local)
     Plugin Version:            5.0.0
     SDK Version:               4.2.2
     Components Version:        3.9.2
```

</details>

<b>Installed version</b>

```
Framework Core: 2.41.2 (local)
Plugin: 5.0.0
SDK: 4.2.2
Components: 3.9.2
```

**Comment by rally25rs** [comment]
Suddenly started working.
I suspect the error might have been indicating that the s3 key did not exist at the time. The normal `${s3:bucket/key}` directly in serverless.yml gives a clearer error message if the key does not exist, which I think messed me up when trying it from `resolveVariable`

**Comment by medikoo** [comment]
> I suspect the error might have been indicating that the s3 key did not exist at the time

Yes, this is what was outlined in error message (`..Value not found at "s3" source`). Still there are some issues with message construction, we'll fix it, so in future version it's more readable.

If you would like to gentle handle missing value, you may add `, null` fallback to variable construct, and then you'll end with `null` in such case and not resolution error.

**Comment by medikoo** [comment]
Error reporting will be fixed with https://github.com/serverless/serverless/pull/9482
