### ISSUE TITLE
slss function run: "SUtils.fileReadSync is not a function"

### ISSUE THREAD

**Issue by jayzalowitz** [serverless/serverless#949]
Im running from within a function so that dosen't seem to be the issue:

/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

TypeError: SUtils.fileReadSync is not a function
    at FunctionRun._validateAndPrepare (/usr/local/lib/node_modules/serverless/lib/actions/FunctionRun.js:114:40)
From previous event:
    at FunctionRun.functionRun (/usr/local/lib/node_modules/serverless/lib/actions/FunctionRun.js:81:10)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:185:31
    at Array.reduce (native)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:184:32
From previous event:
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:182:12)
    at Serverless.actions.(anonymous function) (/usr/local/lib/node_modules/serverless/lib/Serverless.js:428:20)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:397:38)
    at /usr/local/lib/node_modules/serverless/bin/serverless:19:16
    at processImmediate [as _immediateCallback] (timers.js:516:17)
From previous event:
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3

**Comment by jayzalowitz** [comment]
This runs on 0.5.1 and this error happens on 0.5.2, what changed here?

**Comment by HyperBrain** [comment]
Fixed already by @eahefnawy with commit 5d3553a9b57c76ed5b0d876bc2f9483b51844a1b on 4/3.
I think it will be in the next release.

**Comment by eahefnawy** [comment]
Confirmed! :+1:
