### ISSUE TITLE
TypeError: Cannot read property 'has' of undefined - Only in v2.41.2

### ISSUE THREAD

**Issue by fabricioagm** [serverless/serverless#9497]
The following error occurs when I try to create a new serverless application:

<details>
<summary><b><code>sls</code> output</b></summary>

```
TypeError: Cannot read property 'has' of undefined
      at /home/fabricio/.nvm/versions/node/v14.17.0/lib/node_modules/serverless/node_modules/@serverless/dashboard-plugin/lib/cli/interactive-setup/dashboard-set-org.js:126:44
      at Object.setOrgAndApp (/home/fabricio/.nvm/versions/node/v14.17.0/lib/node_modules/serverless/node_modules/@serverless/dashboard-plugin/lib/cli/interactive-setup/dashboard-set-org.js:130:9)
      at Object.run (/home/fabricio/.nvm/versions/node/v14.17.0/lib/node_modules/serverless/node_modules/@serverless/dashboard-plugin/lib/cli/interactive-setup/dashboard-set-org.js:316:17)
      at module.exports (/home/fabricio/.nvm/versions/node/v14.17.0/lib/node_modules/serverless/lib/cli/interactive-setup/index.js:20:18)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async /home/fabricio/.nvm/versions/node/v14.17.0/lib/node_modules/serverless/scripts/serverless.js:401:7

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.17.0
     Framework Version:         2.41.2
     Plugin Version:            5.1.0
     SDK Version:               4.2.2
     Components Version:        3.9.2
```

</details>

When I uninstalled the current version and installed version <b>2.40.0</b> the framework worked correctly.

**Comment by pgrzesik** [comment]
Hello @fabiorogeriosj, thanks for reporting - this is an omission on my part, it will be fixed tomorrow.

**Comment by Alchemist-defi** [comment]
Same bug for me 

For anyone that doesnt know how to uninstall 

npm uninstall -g serverless
npm install -g serverless@2.40.0

**Comment by pgrzesik** [comment]
It should be now fixed with the new release of `dashboard-plugin` - please do a fresh install and ensure to not use cached version of `dashboard-plugin`.
