### ISSUE TITLE
`variablesResolutionMode` doesn't work if global serverless doesn't support it even when using local serverless

### ISSUE THREAD

**Issue by Hilzu** [serverless/serverless#9523]
I have globally installed serverless and it's currently at version 2.28.7.

```
 $ npm ls -g
/Users/hilzu/.fnm/node-versions/v16.2.0/installation/lib
├── npm@7.14.0
└── serverless@2.28.7
```

I'm using the global serverless binary to deploy a service that has the latest serverless 2.43.1 installed as a development dependency. When running serverless commands it logs that it's using the locally installed version.

I'm using `variablesResolutionMode: 20210326` in my `serverless.yml` to resolve AWS Secrets Manager parameters with the new simpler syntax. The parameter resolution fails if the global serverless version isn't updated to a version that supports this feature even when using local serverless.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: serverless-local-bug
frameworkVersion: "^2.43.1"
variablesResolutionMode: 20210326
unresolvedVariablesNotificationMode: error
custom:
  test: ${ssm:/aws/reference/secretsmanager/sls-local-test-secret}
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
functions:
  hello:
    handler: handler.hello
```

</details>

<details>
<summary><b><code>SLS_DEBUG=* sls package</code> output</b></summary>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio

 Serverless Error ----------------------------------------

  ServerlessError: A valid SSM parameter to satisfy the declaration 'ssm:/aws/reference/secretsmanager/sls-local-test-secret' could not be found.
      at Variables.handleUnresolved (/Users/hilzu/Code/serverless-local-bug/node_modules/serverless/lib/classes/Variables.js:986:13)
      at Variables.renderMatches (/Users/hilzu/Code/serverless-local-bug/node_modules/serverless/lib/classes/Variables.js:375:12)
      at /Users/hilzu/Code/serverless-local-bug/node_modules/serverless/lib/classes/Variables.js:396:31
      at tryCatcher (/Users/hilzu/Code/serverless-local-bug/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/hilzu/Code/serverless-local-bug/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/hilzu/Code/serverless-local-bug/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/Users/hilzu/Code/serverless-local-bug/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/Users/hilzu/Code/serverless-local-bug/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/Users/hilzu/Code/serverless-local-bug/node_modules/bluebird/js/release/promise.js:673:18)
      at PromiseArray._resolve (/Users/hilzu/Code/serverless-local-bug/node_modules/bluebird/js/release/promise_array.js:127:19)
      at PromiseArray._promiseFulfilled (/Users/hilzu/Code/serverless-local-bug/node_modules/bluebird/js/release/promise_array.js:145:14)
      at Promise._settlePromise (/Users/hilzu/Code/serverless-local-bug/node_modules/bluebird/js/release/promise.js:609:26)
      at Promise._settlePromise0 (/Users/hilzu/Code/serverless-local-bug/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/Users/hilzu/Code/serverless-local-bug/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/Users/hilzu/Code/serverless-local-bug/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/Users/hilzu/Code/serverless-local-bug/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/Users/hilzu/Code/serverless-local-bug/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/Users/hilzu/Code/serverless-local-bug/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (node:internal/timers:464:21)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              16.2.0
     Framework Version:         2.43.1 (local)
     Plugin Version:            5.1.3
     SDK Version:               4.2.2
     Components Version:        3.10.1
```

</details>

The issue is solved when updating the global serverless version

```
$ npm i -g serverless@2.43.1
```

and running serverless again:

<details>
<summary><b><code>SLS_DEBUG=* sls package</code> output</b></summary>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
```
</details>

<b>Installed version</b>

```
$ npm ls -g
/Users/hilzu/.fnm/node-versions/v16.2.0/installation/lib
├── npm@7.14.0
└── serverless@2.28.7

$ npm ls
serverless-local-bug@1.0.0 /Users/hilzu/Code/serverless-local-bug
└── serverless@2.43.1

$ serverless --version
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.43.1 (local)
Plugin: 5.1.3
SDK: 4.2.2
Components: 3.10.1
```

**Comment by pgrzesik** [comment]
Hello @Hilzu, thanks for reporting and sorry you've run into trouble. The problem here is that variable resolution has been moved earlier in the process and it happens before fallback to local version - we aim to change the behavior of local fallback to happen at the very beginning of processing with new major, but for now the solution here would be to upgrade the global version of the Framework. Please let me know if it resolves your problem.

**Comment by Hilzu** [comment]
What other logic is run from the global serverless before fallback to the local version?

We have several services that are deployed with a single CI process. The CI has a global older serverless version for fallback and most services have a local serverless as a dependency. The idea was that the serverless versions of the services can be upgraded and pinned independently but now that seems like a bad idea if it means that during deploy a mix of logic from the global and local serverless versions are used.

**Comment by pgrzesik** [comment]
Hello @Hilzu - it's really the only thing at the moment and with `v3` major release which should happen in the coming months the local fallback will be done as the very first thing.

**Comment by medikoo** [comment]
@Hilzu @pgrzesik I think we can fix it in v2.

In case of local fallback and information from upstream that some variables are not resolved, we can trigger again the variables resolution internally. Let me patch a PR (it feels as a bug that'll be good to have fixed)

**Comment by chriszirkel** [comment]
I still get the following even though my local and global serverless packages are on the latest version 2.60:

```
 Serverless Error ----------------------------------------
 
  Cannot resolve "aws:*" variable sources with old variables resolver.
  Set "variablesResolutionMode: 20210326" in your service config to unconditionally switch to the new resolver
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              15.3.0
     Framework Version:         2.60.0 (local)
     Plugin Version:            5.4.4
     SDK Version:               4.3.0
     Components Version:        3.17.1
``` 

The variable resolution mode has been set as `variablesResolutionMode: 20210326`.

**Comment by medikoo** [comment]
@chriszirkel if you have `variablesResolutionMode: 20210326` set in your config, and see the above error. It's a clear bug. Please open a bug report filling carefully all details (we need a working reproducible case to be able to coin it)

**Comment by shaun-ayogo** [comment]
FWIW...We had the same problem here (global and local at 2.66.2) and still getting the error. We were able trace it to an outdated step_functions dependency.
