### ISSUE TITLE
invoke local cannot find module

### ISSUE THREAD

**Issue by goda-kazuki** [serverless/serverless#9535]
I'm using layer
`layer->nodejs->node_module`

It will try to call it from lambda.
`const MySQL = require('moment');`
(moment is included in node_module)

`sls invoke local -f main`
`Error: Cannot find module 'moment'`

It works in the aws lambda console

What should I do?

**Comment by pgrzesik** [comment]
Hello, could you please follow the issue template that is visible when you create a new one? From the above report it's hard to evaluate if this is a bug in the Framework or some misconfiguration. Thanks in advance

**Comment by goda-kazuki** [comment]
@pgrzesik 
thank you!

Created a sample repository
https://github.com/goda-kazuki/serverless-framework-sample

It works on AWS Lambda consoles
![ 2021-06-02 11 15 40](https://user-images.githubusercontent.com/40490074/120414136-7591d600-c394-11eb-9a40-82636caa141c.jpg)


It does not work in a local environment
```
[my-service]$ npx sls invoke local -f hello                                                                                                                           ![main]
Error: Cannot find module 'moment'
Require stack:
- /Users/gouda/PhpstormProjects/serverless-framework-sample/my-service/handler.js
- /Users/gouda/PhpstormProjects/serverless-framework-sample/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js
- /Users/gouda/PhpstormProjects/serverless-framework-sample/node_modules/serverless/lib/plugins/index.js
- /Users/gouda/PhpstormProjects/serverless-framework-sample/node_modules/serverless/lib/classes/PluginManager.js
- /Users/gouda/PhpstormProjects/serverless-framework-sample/node_modules/serverless/lib/Serverless.js
- /Users/gouda/PhpstormProjects/serverless-framework-sample/node_modules/serverless/scripts/serverless.js
- /Users/gouda/PhpstormProjects/serverless-framework-sample/node_modules/serverless/bin/serverless.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/gouda/PhpstormProjects/serverless-framework-sample/my-service/handler.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at AwsInvokeLocal.invokeLocalNodeJs (/Users/gouda/PhpstormProjects/serverless-framework-sample/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:763:33)
    at AwsInvokeLocal.invokeLocal (/Users/gouda/PhpstormProjects/serverless-framework-sample/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:230:19)
    at Object.invoke:local:invoke [as hook] (/Users/gouda/PhpstormProjects/serverless-framework-sample/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:49:47)
    at PluginManager.invoke (/Users/gouda/PhpstormProjects/serverless-framework-sample/node_modules/serverless/lib/classes/PluginManager.js:576:20)
    at async PluginManager.run (/Users/gouda/PhpstormProjects/serverless-framework-sample/node_modules/serverless/lib/classes/PluginManager.js:634:7)
    at async Serverless.run (/Users/gouda/PhpstormProjects/serverless-framework-sample/node_modules/serverless/lib/Serverless.js:327:5)
    at async /Users/gouda/PhpstormProjects/serverless-framework-sample/node_modules/serverless/scripts/serverless.js:704:9 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/gouda/PhpstormProjects/serverless-framework-sample/my-service/handler.js',
    '/Users/gouda/PhpstormProjects/serverless-framework-sample/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js',
    '/Users/gouda/PhpstormProjects/serverless-framework-sample/node_modules/serverless/lib/plugins/index.js',
    '/Users/gouda/PhpstormProjects/serverless-framework-sample/node_modules/serverless/lib/classes/PluginManager.js',
    '/Users/gouda/PhpstormProjects/serverless-framework-sample/node_modules/serverless/lib/Serverless.js',
    '/Users/gouda/PhpstormProjects/serverless-framework-sample/node_modules/serverless/scripts/serverless.js',
    '/Users/gouda/PhpstormProjects/serverless-framework-sample/node_modules/serverless/bin/serverless.js'
  ]
}
 
 Serverless Error ----------------------------------------
 
  Exception encountered when loading /Users/gouda/PhpstormProjects/serverless-framework-sample/my-service/handler
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.9.0
     Framework Version:         2.43.1 (local)
     Plugin Version:            5.1.4
     SDK Version:               4.2.2
     Components Version:        3.10.1
```

**Comment by goda-kazuki** [comment]
Does it have to be this one?
npm install serverless
↓
npm install serverless -g

**Comment by pgrzesik** [comment]
Hello @goda-kazuki :wave: Thanks for additional details. I believe the problem here is with configuration, so I'm going to move this to "Discussions" section.

As for the problem itself, it looks like in the example in Lambda console, you're not using any additional dependencies which are imported from `node_modules`. In the shared example however, you're importing `moment` with `require('moment')`, which is not installed/available in `node_modules`. The general idea is to list your required dependencies in `package.json` under `dependencies`. You can also install them with `npm install --save <depedency-name>`, so they will be automatically added to your `package.json`. 

Could you please try again after ensuring that `moment` dependency is installed?
