### ISSUE TITLE
Getting `Error: unable to get local issuer certificate` when running serverless in Jenkins

### ISSUE THREAD

**Issue by corydorning** [serverless/serverless#9548]
Referencing issue #9515. Everything is working fine locally, but when i attempt to run `sls deploy` in my Jenkins environment, i'm getting the error below. I realize it's probably a setting somewhere in my environment, but trying to figure out what my cause this so i know where to look. I know the creds are correct as i've double and triple checked them and in other serverless projects the `serverless-vpc-discovery` plugin is able to retrieve my vpc id. All projects get this same error when trying to deploy though. Any thoughts on things to consider would be greatly appreciated.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: serverless-automation
frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  region: us-east-2
  stage: ${opt:stage, 'dev'}

package:
  artifact: ${env:ARTIFACT}
  
layers:
  serverless-automation:
    path: dist
    description: Lambda layer used to automate operational tasks for the serverless platform.
    compatibleRuntimes:
      - nodejs14.x
    retain: true
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
> webpack && export SLS_DEBUG=* && npx serverless deploy

asset index.js 315 KiB [emitted] (name: main)
runtime modules 211 bytes 2 modules
modules by path ./node_modules/ 276 KiB 45 modules
modules by path ./src/ 29.5 KiB
  ./src/index.js 3.11 KiB [built] [code generated]
  ./src/libs/client-refresh.js 2.75 KiB [built] [code generated]
  ./src/libs/helpers.js 1.79 KiB [built] [code generated]
  ./src/libs/check-options.js 2.95 KiB [built] [code generated]
  ./src/libs/authenticate.js 1.65 KiB [built] [code generated]
  ./src/libs/serverless-api.js 17.2 KiB [built] [code generated]
15 modules
webpack 5.37.1 compiled successfully in 1028 ms
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
........
Serverless: Stack create finished...
Serverless: Recoverable error occurred (Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1491:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:485:12)
    at TLSSocket._finishInit (_tls_wrap.js:933:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:691:12)
----------------------------------------------------------------------------------------------------), sleeping for ~6 seconds. Try 1 of 4
Serverless: Recoverable error occurred (Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1491:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:485:12)
    at TLSSocket._finishInit (_tls_wrap.js:933:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:691:12)
----------------------------------------------------------------------------------------------------), sleeping for ~6 seconds. Try 2 of 4
Serverless: Recoverable error occurred (Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1491:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:485:12)
    at TLSSocket._finishInit (_tls_wrap.js:933:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:691:12)
----------------------------------------------------------------------------------------------------), sleeping for ~5 seconds. Try 3 of 4
Serverless: Recoverable error occurred (Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1491:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:485:12)
    at TLSSocket._finishInit (_tls_wrap.js:933:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:691:12)
----------------------------------------------------------------------------------------------------), sleeping for ~5 seconds. Try 4 of 4
 
 Serverless Error ----------------------------------------
 
  ServerlessError: Error: unable to get local issuer certificate
      at TLSSocket.onConnectSecure (_tls_wrap.js:1491:34)
      at TLSSocket.emit (events.js:315:20)
      at TLSSocket.EventEmitter.emit (domain.js:485:12)
      at TLSSocket._finishInit (_tls_wrap.js:933:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:691:12)
  ----------------------------------------------------------------------------------------------------
      at /home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/serverless/lib/aws/request.js:208:11
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async persistentRequest (/home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/serverless/lib/aws/request.js:145:14)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.2.0
     Framework Version:         2.43.1 (local)
     Plugin Version:            5.1.3
     SDK Version:               4.2.2
     Components Version:        3.10.1
 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serverless-automation@0.0.1 jenkinsDeploy: `webpack && export SLS_DEBUG=* && npx serverless deploy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serverless-automation@0.0.1 jenkinsDeploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jenkins/.npm/_logs/2021-06-02T14_56_48_126Z-debug.log
```

</details>

<b>Installed version</b>

```
Framework Core: 2.43.1 (local)
Plugin: 5.1.3
SDK: 4.2.2
Components: 3.10.1
```

**Comment by corydorning** [comment]
The contents of `.env` is as follows if needed:
```
ARTIFACT='./.serverless/unbound-automation.zip'
```

**Comment by corydorning** [comment]
The contents of `.env` is as follows if needed:
```
ARTIFACT='./.serverless/serverless-automation.zip'
```

**Comment by pgrzesik** [comment]
Thanks for providing more details @corydorning. It looks like the potential issue might be with outdated CA certs on your Jenkins instance. Could you ensure they're up-to-date? If you're using e.g. Ubuntu, you can install/update `ca-certificates` package via `apt`.

**Comment by corydorning** [comment]
in talking with our Jenkins admins the ca's were updated in the docker image build. do you know of a way to confirm this as the issue by chance?

**Comment by pgrzesik** [comment]
Thanks for the response @corydorning. 

> Wanted to point out that this is being run behind a corporate proxy. 

I believe this might be causing this. Could you please try to set env variable `HTTPS_PROXY` to your proxy URL?

**Comment by corydorning** [comment]
Think I've get this worked out, but am receiving another error now. will post a new issue. Thanks!

**Comment by corydorning** [comment]
Just for reference, proxy wasn't the issue, it was pointing node to our certs via `NODE_EXTRA_CA_CERTS`
