### ISSUE TITLE
ServerlessError: XMLParserError: Non-whitespace before first tag.

### ISSUE THREAD

**Issue by corydorning** [serverless/serverless#9585]
when running the `deploy` command, i'm getting the following error:
```
ServerlessError: XMLParserError: Non-whitespace before first tag.
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: serverless-automation
frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  region: us-east-2
  stage: ${opt:stage, 'dev'}

package:
  artifact: ${env:ARTIFACT}

layers:
  serverless-automation:
    path: dist
    description: Lambda layer used to automate operational tasks for the serverless platform.
    compatibleRuntimes:
      - nodejs14.x
    retain: true
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
> webpack && export SLS_DEBUG=* && npx serverless deploy

asset index.js 315 KiB [emitted] (name: main)
runtime modules 211 bytes 2 modules
modules by path ./node_modules/ 276 KiB 45 modules
modules by path ./src/ 29.5 KiB
  ./src/index.js 3.11 KiB [built] [code generated]
  ./src/libs/client-refresh.js 2.75 KiB [built] [code generated]
  ./src/libs/helpers.js 1.79 KiB [built] [code generated]
  ./src/libs/check-options.js 2.95 KiB [built] [code generated]
  ./src/libs/authenticate.js 1.65 KiB [built] [code generated]
  ./src/libs/serverless-api.js 17.2 KiB [built] [code generated]
15 modules
webpack 5.38.1 compiled successfully in 826 ms
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
 
 Serverless Error ----------------------------------------
 
  ServerlessError: XMLParserError: Non-whitespace before first tag.
  Line: 0
  Column: 1
  Char: {
      at error (/home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/sax/lib/sax.js:667:10)
      at strictFail (/home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/sax/lib/sax.js:693:7)
      at beginWhiteSpace (/home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/sax/lib/sax.js:967:7)
      at SAXParser.write (/home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/sax/lib/sax.js:1019:11)
      at Parser.exports.Parser.Parser.parseString (/home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/xml2js/lib/parser.js:322:31)
      at Parser.parseString (/home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/xml2js/lib/parser.js:5:59)
      at NodeXmlParser.parse (/home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/aws-sdk/lib/xml/node_parser.js:31:10)
      at Request.extractError (/home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/aws-sdk/lib/services/s3.js:704:39)
      at Request.callListeners (/home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at Request.emit (/home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/aws-sdk/lib/request.js:688:14)
      at Request.transition (/home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/aws-sdk/lib/request.js:690:12)
      at Request.callListeners (/home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at Request.emit (/home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/aws-sdk/lib/request.js:688:14)
      at Request.transition (/home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/aws-sdk/lib/request.js:690:12)
      at Request.callListeners (/home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at callNextListener (/home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
      at IncomingMessage.onEnd (/home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/aws-sdk/lib/event_listeners.js:313:13)
      at IncomingMessage.emit (events.js:327:22)
      at IncomingMessage.EventEmitter.emit (domain.js:485:12)
      at endReadableNT (_stream_readable.js:1225:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)
  ----------------------------------------------------------------------------------------------------
      at /home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/serverless/lib/aws/request.js:212:11
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async persistentRequest (/home/jenkins/agent/workspace/tomation_feature_node-refactor_2/node_modules/serverless/lib/aws/request.js:145:14)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.2.0
     Framework Version:         2.45.2 (local)
     Plugin Version:            5.3.0
     SDK Version:               4.2.3
     Components Version:        3.12.0
 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serverless-automation@0.0.1 jenkinsDeploy: `webpack && export SLS_DEBUG=* && npx serverless deploy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serverless-automation@0.0.1 jenkinsDeploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jenkins/.npm/_logs/2021-06-09T13_49_02_752Z-debug.log
```

</details>

<b>Installed version</b>

```
Framework Core: 2.45.2 (local)
Plugin: 5.3.0
SDK: 4.2.3
Components: 3.12.0
```

**Comment by corydorning** [comment]
turned out to be proxy related.
