### ISSUE TITLE
NoSuchMethodError for local invoke with Quarkus project

### ISSUE THREAD

**Issue by tlloyd-synalogik** [serverless/serverless#9710]
The local invoke command fails with `NoSuchMethodError` in a Java project bootstrapped with the Quarkus [amazon-lambda-http](https://quarkus.io/guides/amazon-lambda-http) library.

### System details
```
macOS Catalina @ 10.15.7 / 2.6 GHz / 32 GB
mvn @ 3.6.3 
node @ 16.3.0
npm @ 7.15.1
java @ 11.0.10
```

### Steps to reproduce
<details>
<summary><code>steps</code></summary>

Bootstrap Quarkus project with Maven (`cd` into generated project folder):
```shell script
mvn archetype:generate \
       -DarchetypeGroupId=io.quarkus \
       -DarchetypeArtifactId=quarkus-amazon-lambda-http-archetype \
       -DarchetypeVersion=2.0.1.Final
```

Remove unused web libraries from `pom.xml` (keep `quarkus-resteasy`):
```shell script
mvn quarkus:remove-extensions -Dextensions=undertow,vertx-web,funqy-http
```

Remove unused classes
```shell script
find . -name '*.java' -not -name '*Resource*' | xargs rm
```

Package the Lambda function
```
mvn package
```
Install serverless
```shell script
npm install --save-dev serverless@2.51.0
```

Create `serverless.yml` file with contents:
```yaml
service: greeting-service
frameworkVersion: '2.51.0'
provider:
  name: aws
  runtime: java11
package:
  artifact: target/function.zip
functions:
  greeting:
    handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
    events:
      - httpApi:
          path: /hello
          method: get
```

Create test event `event.json` file with contents:
```json
{
  "body": "",
  "cookies": [],
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip, deflate, br",
    "Connection": "keep-alive",
    "Host": "127.0.0.1:3000",
    "Postman-Token": "2fc588c1-2ce2-4c34-b1b5-6b570ae1a6a7",
    "User-Agent": "PostmanRuntime/7.28.0",
    "X-Forwarded-Port": "3000",
    "X-Forwarded-Proto": "http"
  },
  "isBase64Encoded": false,
  "pathParameters": {
    "any_path": "/hello"
  },
  "queryStringParameters": {},
  "rawPath": "/hello",
  "rawQueryString": "",
  "requestContext": {
    "accountId": "123456789012",
    "apiId": "1234567890",
    "authorizer": null,
    "domainName": null,
    "domainPrefix": null,
    "http": {
      "method": "GET",
      "path": "/hello",
      "protocol": "HTTP/1.1",
      "sourceIp": "127.0.0.1",
      "userAgent": "Custom User Agent String"
    },
    "requestId": "29a23d8e-0830-4533-afce-eeadf5a28eae",
    "routeKey": "$default",
    "stage": null,
    "time": null,
    "timeEpoch": 0
  },
  "routeKey": "$default",
  "stageVariables": null,
  "version": "2.0"
}
```

Invoke the Lambda function locally:
```shell script
npx sls invoke local -f greeting -p event.json
```
</details>

### Solution

Update the `aws-lambda-java-events` dependency to at least version `3.1.1` in the file:
```
node_modules/serverless/lib/plugins/aws/invokeLocal/runtimeWrappers/java/pom.xml
```
This applies a lombok config fix applied and described in commit `7f7b089` of the `aws-lambda-java-libs` github repo relating to jackson deserialization.

After updating the dependency version and re-packaging the jar, the local invoke command succeeds and the error is gone. 

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: greeting-service
frameworkVersion: '2.51.0'
provider:
  name: aws
  runtime: java11
package:
  artifact: target/function.zip
functions:
  greeting:
    handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
    events:
      - httpApi:
          path: /hello
          method: get
```

</details>

<details>
<summary><b><code>SLS_DEBUG=* npx sls invoke local -f greeting -p event.json</code> output</b></summary>

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Invoke invoke:local
Serverless: In order to get human-readable output, please implement "toString()" method of your "ApiGatewayResponse" object.
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2021-07-07 12:58:04,196 INFO  [io.quarkus] (main) test 1.0-SNAPSHOT on JVM (powered by Quarkus 2.0.1.Final) started in 0.863s. 

2021-07-07 12:58:04,200 INFO  [io.quarkus] (main) Profile prod activated. 
2021-07-07 12:58:04,201 INFO  [io.quarkus] (main) Installed features: [amazon-lambda, cdi, resteasy, smallrye-context-propagation]

java.lang.reflect.InvocationTargetException

        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)

        at com.serverless.InvokeBridge.invoke(InvokeBridge.java:86)
        at com.serverless.InvokeBridge.<init>(InvokeBridge.java:38)
        at com.serverless.InvokeBridge.main(InvokeBridge.java:137)

Caused by: java.lang.NoSuchMethodError: 'boolean com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPEvent.getIsBase64Encoded()'

        at io.quarkus.amazon.lambda.http.LambdaHttpHandler.nettyDispatch(LambdaHttpHandler.java:194)
        at io.quarkus.amazon.lambda.http.LambdaHttpHandler.handleRequest(LambdaHttpHandler.java:65)
        at io.quarkus.amazon.lambda.http.LambdaHttpHandler.handleRequest(LambdaHttpHandler.java:45)

        at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder.handle(AmazonLambdaRecorder.java:71)
        at io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler.handleRequest(QuarkusStreamHandler.java:58)
        ... 7 more

```

</details>

<b>Installed version</b>

```
Framework Core: 2.51.0 (local)
Plugin: 5.4.3
SDK: 4.2.3
Components: 3.13.3
```

**Comment by medikoo** [comment]
@tlloyd-synalogik great thanks for reporting. Is there a chance you can prepare a PR with a fix? We'll be grateful!
