### ISSUE TITLE
V0.6: Auto Plugin Detection via package.json Is Broken

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#978]
We tried to play around with the boilerplate using the v0.6 branch, but we keep hitting this error:

```
serverless:lib.node_modules.serverless.lib.Serverless Attempting to load plugin from /Users/austen/Desktop/s/s_code/boilerplate-graphql/node_modules/aws-sdk +1ms
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
       fn = function () { throw arg; };
                          ^

TypeError: PluginClass is not a function
   at Serverless._loadPlugins (/usr/local/lib/node_modules/serverless/lib/Serverless.js:294:25)
   at Serverless.loadProjectPlugins (/usr/local/lib/node_modules/serverless/lib/Serverless.js:249:10)
   at /usr/local/lib/node_modules/serverless/lib/Serverless.js:76:41
```

It seems that the new auto plugin detection code thinks `aws-sdk` is a plugin.

@pmuens could you take a look at this when you have some time? :) ... hope it won't get too hacky

**Comment by pmuens** [comment]
Sorry for this one. Will look into this ASAP!
