### ISSUE TITLE
i need help with the tf2 bot i type  node dist/app.js and say this Error: STEAM_ACCOUNT_NAME must be set in the environment     at Object.loadOptions (C:\Users\maras\Desktop\tf2 bot\tf2autobot\tf2autobot\dist\classes\Options.js:1215:15)     at Object.<anonymous> (C:\Users\maras\Desktop\tf2 bot\tf2autobot\tf2autobot\dist\app.js:45:27)     at Module._compile (internal/modules/cjs/loader.js:1072:14)     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)     at Module.load (internal/modules/cjs/loader.js:937:32)     at Function.Module._load (internal/modules/cjs/loader.js:778:12)     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)     at internal/main/run_main_module.js:17:47

### ISSUE THREAD

**Issue by bababoiss** [serverless/serverless#9862]
⚠️⚠️ REPLACE WITH DESCRIPTION

<details>
<summary><code>serverless.yml</code></summary>

```yaml
# ⚠️⚠️ REPLACE THIS COMMENT WITH FULL serverless.yml CONTENT
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
⚠️⚠️ REPLACE WITH FULL COMMAND OUTPUT
```

</details>

<b>Installed version</b>

```
⚠️⚠️ REPLACE WITH `serverless --version` OUTPUT
```

**Comment by pgrzesik** [comment]
I believe that was created as a mistake, if you'd like to report a bug, please follow our template.
