### ISSUE TITLE
Azure Service Bus Example is incorrect

### ISSUE THREAD

**Issue by henrique73** [serverless/serverless#9911]
When following the Azure Service Bus Example you will receive an error, after many hours searching what could be the solution, it's necessary to add a 'true' after the `- serviceBus: `, I'm fairly new to the Serverless framework, and don't know why it would need a 'true' there, it would be great to change it so people following the example in the future don't run into this problem.

Example of what would work:

```
functions:
  example:
    handler: handler.hello
    events:
      - serviceBus: true
      ....
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
provider:
  name: azure
  runtime: nodejs12

functions:
  sampleHandler:
    handler: handlers/index.handler
    events:
      - serviceBus: true
        name: <sensitive>
        queueName: <sensitive>
        accessRights: manage
        connection: <sensitive>
```

</details>

<details>
<summary><b><code>sls offline</code> output</b></summary>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Initializing provider configuration...
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command invoke:apim
Serverless: Load command remove
Serverless: Load command deploy
Serverless: Load command deploy:list
Serverless: Load command deploy:apim
Serverless: Load command func
Serverless: Load command func:add
Serverless: Load command func:remove
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command offline:build
Serverless: Load command offline:cleanup
Serverless: Load command rollback
Serverless: Load command info
Serverless: Load command webpack
Serverless: DOTENV: Could not find .env file.
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Configuration warning: Unrecognized provider 'azure'
Serverless:  
Serverless: You're relying on provider plugin which doesn't provide a validation schema for its config.
Serverless: Please report the issue at its bug tracker linking: https://www.serverless.com/framework/docs/providers/aws/guide/plugins#extending-validation-schema
Serverless: You may turn off this message with "configValidationMode: off" setting
Serverless:  
Serverless: Invoke offline
Serverless: Building offline service
Serverless: Parsing Azure Functions Bindings.json...
 
 Error ---------------------------------------------------

  Error: Binding  nameTrigger not supported
      at Function.<anonymous> (C:\Users\Henrique\Desktop\notf\notification\node_modules\serverless-azure-functions\lib\shared\utils.js:99:39)
      at step (C:\Users\Henrique\Desktop\notf\notification\node_modules\serverless-azure-functions\lib\shared\utils.js:43:23)
      at Object.next (C:\Users\Henrique\Desktop\notf\notification\node_modules\serverless-azure-functions\lib\shared\utils.js:24:53)
      at fulfilled (C:\Users\Henrique\Desktop\notf\notification\node_modules\serverless-azure-functions\lib\shared\utils.js:15:58)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              14.16.0
     Framework Version:         2.55.0 (local)
     Plugin Version:            5.4.3
     SDK Version:               4.2.6
     Components Version:        3.15.1

```

</details>

<b>Installed version</b>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.55.0 (local)
Plugin: 5.4.3
SDK: 4.2.6
Components: 3.15.1
```

**Comment by verikono** [comment]
6 mths ago I reviewed using serverless for Azure functions and EventHubs but was disappointed when I couldn't recommend it due to issues like this.
