### ISSUE TITLE
Serverless Error "You cannot specify a name when defining more than one rate expression"

### ISSUE THREAD

**Issue by kitto006** [serverless/serverless#9974]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

https://github.com/serverless/serverless/blob/7eba95fcb7f9b09a8a2aebd50c433f92e15cac97/lib/plugins/aws/package/compile/events/schedule.js  (Line 109) throws ServerlessError

              if (ScheduleExpressions.length > 1 && Name) {
                throw new ServerlessError(
                  'You cannot specify a name when defining more than one rate expression',
                  'SCHEDULE_NAME_NOT_ALLOWED_MULTIPLE_RATES'
                );
              }

My serverless.yml file looks like this:

.....
custom:
  warmup:
    default:
      enabled: true # Whether to warm up functions by default or not
      name: warmer-${self:service}-${self:custom.stage}
      events:
        - schedule: 
            name: rule-warmer-${self:service}-${self:custom.stage}
            description: rule-warmer-${self:service}-${self:custom.stage}
            rate: rate(5 minutes)
...

Even though I only have 1 schedule expression and I want to name it (so in CloudWatch / EventBridge my rule doesn't t get a long ugly name like ... xxxWarmUpPluginDefaultEvent-P53HGRVWTSCU)

The work arounds are:

Option 1:  give up naming the rule  (go back to ugly name)
                 - just comment out the name, description, rate lines

        - schedule: 'rate(5 minutes)'
       ##     name: rule-warmer-${self:service}-${self:custom.stage}
       ##     description: rule-warmer-${self:service}-${self:custom.stage}
       ##    rate: rate(5 minutes)
        
Option 2:  use older version of serverless
    npm install -g serverless@2.56.0
    
  
This issue just started happening since the Sept 8, 2021 commit 9f0bc68
I'm using Option 2 until this bug gets fixed.

### Service configuration (serverless.yml) content

```yaml
.....
custom:
  warmup:
    default:
      enabled: true # Whether to warm up functions by default or not
      name: warmer-${self:service}-${self:custom.stage}
      events:
        - schedule: 
            name: rule-warmer-${self:service}-${self:custom.stage}
            description: rule-warmer-${self:service}-${self:custom.stage}
            rate: rate(5 minutes)
...
```

### Command name and used flags

serverless deploy --stage ${SLS_STAGE} -v

### Command output

```shell
+ serverless deploy --stage ${SLS_STAGE} -v
Serverless: WarmUp: Creating warmer "default" to warm up 7 functions:
Serverless:           * dev_payment-capture_order_create
Serverless:           * dev_payment-capture_order_item_create
Serverless:           * dev_payment-capture_order_item_delete
Serverless:           * dev_payment-capture_order_get
Serverless:           * dev_payment-capture_order_execute
Serverless:           * dev_payment-capture_order_capture
Serverless:           * dev_payment-capture_webhook_notify
Serverless: WarmUp: Creating warmer "default" to warm up 7 functions:
Serverless:           * dev_payment-capture_order_create
Serverless:           * dev_payment-capture_order_item_create
Serverless:           * dev_payment-capture_order_item_delete
Serverless:           * dev_payment-capture_order_get
Serverless:           * dev_payment-capture_order_execute
Serverless:           * dev_payment-capture_order_capture
Serverless:           * dev_payment-capture_webhook_notify
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
 
 Serverless Error ----------------------------------------
 
  You cannot specify a name when defining more than one rate expression
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.13.0
     Framework Version:         2.59.0
     Plugin Version:            5.4.4
     SDK Version:               4.3.0
     Components Version:        3.17.0
```

### Environment information

```shell
bitbucket pipeline
image: node:12.13.0-alpine
```

**Comment by medikoo** [comment]
@kitto006 you're referring to the configuration as set in `custom`, while Framework doesn't process it in any way. It's a free form configuration area.

If you want to report some issue with `schedule` event. Please provide as simplest as possible `schedule` event configuration that doesn't work for you, e.g.:

```yaml
functions:
  foo:
    events:
      - schedule:
            rate: rate(5 minutes)
```

Also ensure that test case doesn't involve any plugins (if issue is influenced by a plugin, it should be reported at plugin repository)

**Comment by mnapoli** [comment]
The configuration is in `custom` because that's how the warmup plugin works. In the plugin they then copy the function definition to the Framework's native function section: https://github.com/juanjoDiaz/serverless-plugin-warmup/blob/master/src/warmer.js#L213-L232

It could be an incompatibility in the plugin though, but at first look it seems like the plugin does copy the whole function over entirely.

@kitto006 it might be worth trying to reproduce this without the plugin, by defining the function in `functions` (not custom). If the problem is reproduced that way, then it will help identify the bug in the Framework (please post it here). If the problem is not reproduced, then it's most likely a bug in the plugin.

**Comment by kitto006** [comment]
Hi @mnapoli , tried your suggestion, I get this error when I try to define the warmer inside functions.

+ serverless deploy -v
Serverless: Configuration warning at 'functions.warmup': unrecognized property 'default'
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
 
 Error ---------------------------------------------------
 
  Error: WarmUp: Invalid function-level warmup configuration (default) in function bug9974. Every warmer should be declared in the custom section.
      at /opt/atlassian/pipelines/agent/build/node_modules/serverless-plugin-warmup/src/config.js:103:15
      at Array.map (<anonymous>)
      at getFunctionsByWarmer (/opt/atlassian/pipelines/agent/build/node_modules/serverless-plugin-warmup/src/config.js:88:6)
      at getConfigsByWarmer (/opt/atlassian/pipelines/agent/build/node_modules/serverless-plugin-warmup/src/config.js:179:29)
      at WarmUp.configPlugin (/opt/atlassian/pipelines/agent/build/node_modules/serverless-plugin-warmup/src/index.js:88:10)
      at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:580:20)
      at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:602:16)
      at Object.after:package:initialize [as hook] (/opt/atlassian/pipelines/agent/build/node_modules/serverless-plugin-warmup/src/index.js:63:71)
      at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:580:20)
      at async PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:602:5)
      at async Object.before:deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/deploy.js:61:11)
      at async PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:580:9)
      at async PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:640:7)
      at async Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:457:5)
      at async /usr/local/lib/node_modules/serverless/scripts/serverless.js:803:9
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.13.0
     Framework Version:         2.59.0
     Plugin Version:            5.4.4
     SDK Version:               4.3.0
     Components Version:        3.17.0
 
Serverless: Deprecation warnings:
Starting with v3.0.0, "-v" will no longer be supported as alias for "--verbose" option. Please use "--verbose" flag instead.
More Info: https://www.serverless.com/framework/docs/deprecations/#CLI_VERBOSE_OPTION_ALIAS
Starting with next major, Serverless will throw on configuration errors by default. Adapt to this behavior now by adding "configValidationMode: error" to service configuration
More Info: https://www.serverless.com/framework/docs/deprecations/#CONFIG_VALIDATION_MODE_DEFAULT
Support for "package.include" and "package.exclude" will be removed with next major release. Please use "package.patterns" instead
More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_PACKAGE_PATTERNS

**Comment by kitto006** [comment]
@medikoo I've published this public repo https://github.com/kitto006/serverless-bug9974
serverless1.yml works with serverless 2.56.0 or earlier, it allows for the custom naming of the generated cloudwatch rule.
serverless2.yml is a work-around for the current version 2.59.0 but cannot custom name the generated cloudwatch rule.
serverless3.yml is the suggestion from @mnapoli  which confirms the warmer must be declared inside custom section.

**Comment by medikoo** [comment]
@kitto006 can you update the test cases so they do not involve `serverless-plugin-warmup` plugin?

If bug you observe happens only with `serverless-plugin-warmup` plugin, it means it's a bug on plugin side, and should be reported to its repository

**Comment by kitto006** [comment]
@medikoo I've updated the test cases (added serverless4.yml) which omits "serverless-plugin-warmup" plugin as you suggested
see my repo -->  https://github.com/kitto006/serverless-bug9974
The result is, no error, but no warmer lambda function and no cloudwatch schedule rule generated.
My understanding is if I want warmers (which I need because I run my lambda functions inside a VPC) then I must use this plugin
https://www.serverless.com/plugins/serverless-plugin-warmup/ 

It looks like the issue is the latest version of serverless framework made the existing plugin not work the way it used to.
I can additionally report it on the plug-in side, can you point me to it?

**Comment by medikoo** [comment]
@kitto006 if there's no issue when using plain Framework, and it only occurs when using `serverless-plugin-warmup`. Please open an issue on plugin side.

It's likely that a way in how plugin processes the configuration in `custom` section is not compatible with how Framework processes things and plugin simply needs to be updated.

**Comment by juanjoDiaz** [comment]
The problem here is that serverless has introduced a breaking change as part of a minor version. Which is not OK imho.

https://github.com/serverless/serverless/issues/9867 was the issue and https://github.com/serverless/serverless/commit/9f0bc689cc2ac3e53b4db665b899e1446ac37456 was the "fix".

Before that, Serverless took a string and now it takes an array.
The issue happens because when trying to get the length of the array it gets the length of the string.
You should be able to workaround the issue by simply using the new format of array.

```yaml
# ...
custom:
  warmup:
    default:
      enabled: true # Whether to warm up functions by default or not
      name: warmer-${self:service}-${self:custom.stage}
      events:
        - schedule: 
            name: rule-warmer-${self:service}-${self:custom.stage}
            description: rule-warmer-${self:service}-${self:custom.stage}
            rate:
              - rate(5 minutes)
# ...
```

This type of breaking changes are a problem.
If I maintain the string, it will fail in v2.58+ and if I move to an array it will fail in all previous version.
Backwards compatibility is essential for a public API.

@medikoo I'll do a PR so strings are allowed again to bring back compatibility. But the current broken versions will stay broken and it would be good to document that in the release notes.

**Comment by kitto006** [comment]
@juanjoDiaz thank you very much for clarifying the situation.

**Comment by medikoo** [comment]
>  The problem here is that serverless has introduced a breaking change as part of a minor version.

@juanjoDiaz That's not the case. Framework didn't change anything in how old format (_string_) is supported. It just added support for the new (_array_) form.

Issue you're observing is specific to the plugin. Let me explain. 

Framework in all cases normalizes user input configuration (e.g., where _string_ is expected and someone inputs _number_, it's normalized to _string_. Where _array of strings_ is expected and some puts _string_ it's normalized to an array containing that single string, etc.), and all internal processing is configured to work against normalized configuration input (it's also to avoid the significant maintenance cost of adding validation or normalization logic directly in feature internals)

The problem on the plugin side, is that it somewhat hacks the configuration input, and provides to Framework internals the input that was not normalized against our schema, (e.g. in this specific case the _string_ input is not normalized to an array that holds this single string) and as our internals are configured to strictly work with normalized input, an error occurs

The only real fix to this issue (and many others that may surface) is to ensure that plugin applies the config validation and normalization on configuration parts that are moved from the `custom` section to sections as recognized by Framework.

For reference internal normalization is applied here: https://github.com/serverless/serverless/blob/2027f13fab44137611f74915f76670d94c4614ff/lib/classes/ConfigSchemaHandler/index.js#L111-L119 
In plugin, I believe you need to retrieve schema specific to the section you move, and apply it before schema validation before it's injected to Framework input. That will fix this issue

**Comment by medikoo** [comment]
> The plugin already configures it's schema and it was copied from serverless.configSchemaHandler.schema. 

That technically should be good enough.

I've just looked into the plugin, and I wonder whether the following schema is correct: https://github.com/juanjoDiaz/serverless-plugin-warmup/blob/8e7e5808c510118675ce07397760cfcf7717bde8/src/schema.js#L125-L126

Normally property names by the pattern are set via `patternProperties` setting (as e.g. here: https://github.com/serverless/serverless/blob/f8ad7bca6a26e39864d139fec4aadddd24b34a5b/lib/configSchema.js#L37-L40)

Problem with AJV version we're relying on, is that'll ignore properties it doesn't recognize without any notice, and [`.*`](https://github.com/juanjoDiaz/serverless-plugin-warmup/blob/8e7e5808c510118675ce07397760cfcf7717bde8/src/schema.js#L126) looks to me as one to be ignored.

**Comment by juanjoDiaz** [comment]
This was working until the changed that I mentioned above.
I tested `.*` and it definitely was working.
 
Maybe the problem is not with AJV but with the normalizing logic?
I cannot find anywhere in the code where strings are automatically converted to arrays as you mentioned in your previous comment. And that is exactly the issue that we are facing that the string is not being accepted as it was before.

**Comment by medikoo** [comment]
@juanjoDiaz I just doubled checked, and can confirm, that plugin doesn't apply any schema validation.

e.g. I've created [a simple service](https://github.com/medikoo/test-serverless/blob/plugin-serverless-plugin-warmup/) that defines in `custom`  function settings, `memorySize: foo` , and this comes without any notice (while if put into regular section it'll immediately fail)

Things start to work, once in plugin definition of schema is changed to:

```javascript
serverless.configSchemaHandler.defineCustomProperties({
  properties: {
    warmup: {
      patternProperties: {
        '.*': {
          type: 'object',
          properties: { ...globalConfigSchemaProperties, ...functionConfigSchemaProperties },
          additionalProperties: false,
        },
      },
    },
  },
});
```

**Comment by juanjoDiaz** [comment]
Hummm interesting.
Thanks for that.
I'll definitely dig deeper into it.

Still, we are diverting from the actual issue.
The JsonSchema has changed from accepting a string to accepting an array of strings.
You claim that it doesn't matter because Serverless automatically converts the string into an array.
But that's clearly not happening for the function that I add in the `after:package:initialize`.
So either such conversion is not happening or it's happening before that.
Could you point me to the code within Serverless that performs the normalization?

**Comment by medikoo** [comment]
> The JsonSchema has changed from accepting a string to accepting an array of strings.
> You claim that it doesn't matter because Serverless automatically converts the string into an array.

Yes, AJV JSON schema validator is configured to normalize strings into arrays, if an array of strings is expected (it's an internal feature of schema validator, and not something that's added aside)

Schema defines _target_ type, and any _input_ that can be normalized (per specific rules) to _target_ type is assumed as valid.

**Comment by medikoo** [comment]
> But that's clearly not happening

if you cover this in schema, that's defined in the plugin constructor, then it'll work. Otherwise, it wouldn't (schema, as introduced by plugins, should always be added at  the plugin initialization phase, so in plugin constructor)

**Comment by juanjoDiaz** [comment]
Thanks mate!
The fact that AJV already does the normalization is what I was missing.

Do you have any guidelines on how to test the schema validation for plugins?
I wonder how to avoid this kind of thing happening in the future.

**Comment by medikoo** [comment]
> Do you have any guidelines on how to test the schema validation for plugins?

On the Framework side, we have all tests configured to work with validation crashing (`configValidationMode: error` set in config), and we use [`runServerless`](https://github.com/serverless/test/blob/master/docs/run-serverless.md) util, to ensure all internal machinery is run.
Having that we test just valid configurations, e.g. we [test that using `rate: <string>` works](https://github.com/serverless/serverless/blob/9b5e6b12371317356d9cb4600a4a574df305f63f/test/unit/lib/plugins/aws/package/compile/events/schedule.test.js#L58). On plugin side you may confirm the same, when `rate: <string>` is input via `custom` section
