### ISSUE TITLE
S3 bucket already exists error, only for certain environment?

### ISSUE THREAD

**Issue by rnnyrk** [serverless/serverless#9986]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I'm trying to deploy my Serverless project for several environments. We would like to run a develop, staging and production environment. To make this work I'm using `serverless-dotenv-plugin` with a `NODE_ENV=development` or `NODE_ENV=acceptation` (in this case). Everything related to the plugin works. 

Everything related to the plugin seems to work. When I deploy for development or acceptance it loads the correct `.env` file, as well it does try to create the related S3 buckets. 

<img width="1412" alt="Screenshot 2021-09-22 at 11 44 58" src="https://user-images.githubusercontent.com/4519142/134323924-3f4649ef-e739-48a5-9896-bcffd239a2de.png">

As you can see in the attached image there are two buckets for each environment which I want to link to a Route53 domain. The initial deployment created the correct buckets. When I now deploy again, **for development there is no issue**. Although when I deploy for acceptance I get the error `An error occurred: BucketGatsbySite - project-bucket-acc-www-gatsby already exists.`, **so the build breaks**.

Of course the bucket already exists, but because it's already created it shouldn't be re-created. This seems to work for development, but not for acceptance and I have no clue why. In this [AWS documentation](https://docs.aws.amazon.com/es_es/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html) I can't find anything related to this. Although as you can see below I do have the `DeletionPolicy: Retain`, which I think should mean there shouldn't be a new one created, but the old one should be retained. 

So to summarise, I want to create a bucket but not overwrite it. Only create it once and after that retain the old ones and don't try to create new ones. 

### Service configuration (serverless.yml) content

```yaml
service: project

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${env:STAGE}
  region: ${env:REGION}
  environment:
    REGION: ${env:REGION}
    STAGE: ${env:STAGE}
    NODE_ENV: ${env:NODE_ENV}
    CLIENT_ID: ${env:AWS_CLIENT_ID}
    TABLE: "project-db-${env:STAGE}"
    BUCKET: "project-bucket-${env:STAGE}"
    POOL: "project-userpool-${env:STAGE}"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - !GetAtt projectTable.Arn

BucketReactApp:
  Type: AWS::S3::Bucket
  DeletionPolicy: Retain
  Properties:
    AccessControl: PublicRead
    BucketName: "${self:provider.environment.BUCKET}-www-react"
BucketGatsbySite:
  Type: AWS::S3::Bucket
  DeletionPolicy: Retain
  Properties:
    AccessControl: PublicRead
    BucketName: "${self:provider.environment.BUCKET}-www-gatsby"
```
```


### Command name and used flags

NODE_ENV=acceptance sls deploy

### Command output

```shell
> npm run deploy:acc

> project-backend@1.0.0 deploy:acc
> NODE_ENV=acceptance SLS_DEBUG=* sls deploy

Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.59.0")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command webpack
Serverless: Load command s3sync
Serverless: Load command s3sync:bucket
Serverless: Load command delete-appsync
Serverless: Load command validate-schema
Serverless: Load command graphql-playground
Serverless: Load command deploy-appsync
Serverless: Load command update-appsync
Serverless: DOTENV: Loading environment variables from .env.acceptance:
Serverless: 	 - REGION
Serverless: 	 - STAGE
Serverless: 	 - NODE_ENV
Serverless: 	 - AWS_CLIENT_ID
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
AppSync Plugin: GraphQl schema valid
Serverless: Invoke webpack:validate
Serverless: Invoke webpack:compile
Serverless: Bundling with Webpack...
asset src/lambda/cognitoCustomMails.js 16.1 KiB [emitted] [minimized] (name: src/lambda/cognitoCustomMails) 1 related asset
runtime modules 670 bytes 3 modules
orphan modules 14.7 KiB [orphan] 2 modules
./src/lambda/cognitoCustomMails.ts + 2 modules 15.8 KiB [built] [code generated]
webpack compiled successfully in 7019 ms
asset src/lambda/createUser.js 919 bytes [emitted] [minimized] (name: src/lambda/createUser) 1 related asset
runtime modules 670 bytes 3 modules
orphan modules 42 bytes [orphan] 1 module
./src/lambda/createUser.ts + 1 modules 871 bytes [not cacheable] [built] [code generated]
webpack compiled successfully in 7092 ms
asset src/lambda/recurringTasks.js 3.02 KiB [emitted] [minimized] (name: src/lambda/recurringTasks) 1 related asset
runtime modules 670 bytes 3 modules
orphan modules 3.19 KiB [orphan] 2 modules
./src/lambda/recurringTasks.ts + 2 modules 7.27 KiB [not cacheable] [built] [code generated]
webpack compiled successfully in 7157 ms
Serverless: Invoke webpack:package
Serverless: Package lock found - Using locked versions
Serverless: Packing external modules: aws-sdk@2.992.0
Serverless: Copying existing artifacts...
Serverless: Packaging service...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service cognitoCustomMails.zip file to S3 (8.14 kB)...
Serverless: Uploading service createUser.zip file to S3 (9.09 MB)...
Serverless: Uploading service recurringTasks.zip file to S3 (9.09 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
...............
Serverless: Operation failed!
Serverless: View the full error output: https://eu-central-1.console.aws.amazon.com/cloudformation/home?region=eu-central-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aeu-central-1%3A491491561102%3Astack%2Fproject-acc%2F907c7030-1ae5-11ec-bfca-060e73bf9c74

 Serverless Error ----------------------------------------

  ServerlessError: An error occurred: BucketGatsbySite - project-bucket-acc-www-gatsby already exists.
      at /Users/ronnyrook/Developer/Node/project-backend/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:168:23
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async AwsDeploy.update (/Users/ronnyrook/Developer/Node/project-backend/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:149:5)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.16.0
     Framework Version:         2.59.0 (local)
     Plugin Version:            5.4.4
     SDK Version:               4.3.0
     Components Version:        3.17.0

Serverless: Deprecation warning: Variables resolver reports following resolution errors:
              - Cannot resolve variable at "provider.stage": Value not found at "env" source
            From a next major this will be communicated with a thrown error.
            Set "variablesResolutionMode: 20210326" in your service config, to adapt to new behavior now
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
```

### Environment information

```shell
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.59.0 (local)
Plugin: 5.4.4
SDK: 4.3.0
Components: 3.17.0
```

**Comment by medikoo** [comment]
@rnnyrk When you add  any resource to CloudFormation, AWS assumes it's a new resource to be created  (and owned) by the stack.

Here if I understand correctly you've tried to recreate same S3 bucket with different stack (different stage) and it's why deployment failed.

I'm moving it to discussions, as it doesn't seem to point any issue in Framework iteslf
